CREATE TABLE [aies].[ecs_exp_declcoexport] (
    [decl_id]                      NUMERIC (19)    NOT NULL,
    [exp_gross_mass]               NUMERIC (18, 3) NULL,
    [exp_gross_mass_br_c]          NVARCHAR (140)  NULL,
    [exp_no_of_items_br_c]         NVARCHAR (140)  NULL,
    [crb_code]                     VARCHAR (2)     NULL,
    [crb_state_of_seals]           TINYINT         NULL,
    [pad_place]                    NVARCHAR (35)   NULL,
    [pad_capacity]                 NVARCHAR (35)   NULL,
    [pad_phone]                    NVARCHAR (15)   NULL,
    [pad_name]                     NVARCHAR (35)   NULL,
    [pad_date]                     DATETIME        NULL,
    [si_quantity]                  INT             NULL,
    [cr_code]                      VARCHAR (2)     NULL,
    [lof_co]                       VARCHAR (8)     NULL,
    [lof_location_desc]            NVARCHAR (35)   NULL,
    [lof_location_code]            VARCHAR (17)    NULL,
    [pos_location_desc]            NVARCHAR (35)   NULL,
    [pos_location_code]            VARCHAR (17)    NULL,
    [it_identity_br]               VARCHAR (31)    NULL,
    [it_identity_br_c]             NVARCHAR (140)  NULL,
    [it_identity]                  VARCHAR (31)    NULL,
    [it_mode]                      VARCHAR (2)     NULL,
    [exp_co_of_exit]               VARCHAR (8)     NULL,
    [exp_co_of_exit_changed_to]    VARCHAR (8)     NULL,
    [exp_storing]                  TINYINT         NULL,
    [exp_co_of_export]             VARCHAR (8)     NULL,
    [exp_decl_type_1a]             VARCHAR (2)     NULL,
    [exp_no_of_items]              INT             NULL,
    [exp_no_of_items_br]           INT             NULL,
    [exp_no_of_packages]           INT             NULL,
    [exp_no_of_packages_br]        INT             NULL,
    [exp_no_of_packages_br_c]      NVARCHAR (140)  NULL,
    [exp_country_of_export]        VARCHAR (2)     NULL,
    [exp_country_of_destinatnion]  VARCHAR (2)     NULL,
    [exp_containers]               TINYINT         NULL,
    [exp_gross_mass_br]            NUMERIC (18, 3) NULL,
    [exp_acceptance_date]          DATETIME        NULL,
    [exp_time_to_border_arrival]   DATETIME        NULL,
    [dt_code]                      VARCHAR (3)     NULL,
    [dt_place]                     NVARCHAR (35)   NULL,
    [dt_place_code]                VARCHAR (1)     NULL,
    [w_location_code]              VARCHAR (14)    NULL,
    [w_type]                       VARCHAR (1)     NULL,
    [w_country]                    VARCHAR (2)     NULL,
    [tab_country]                  VARCHAR (2)     NULL,
    [tab_identity]                 VARCHAR (31)    NULL,
    [tab_mode]                     VARCHAR (2)     NULL,
    [sc_street_and_number]         NVARCHAR (35)   NULL,
    [sc_post_code]                 VARCHAR (9)     NULL,
    [sc_city]                      NVARCHAR (35)   NULL,
    [sc_co]                        VARCHAR (8)     NULL,
    [sc_name]                      NVARCHAR (35)   NULL,
    [sc_country]                   VARCHAR (2)     NULL,
    [td_amount]                    NUMERIC (17, 2) NULL,
    [td_exchange_rate]             NUMERIC (11, 5) NULL,
    [td_nature_of_transation]      VARCHAR (2)     NULL,
    [td_currency]                  VARCHAR (3)     NULL,
    [exp_decl_type_1b]             VARCHAR (1)     NULL,
    [exp_crn]                      NVARCHAR (70)   NULL,
    [exp_un_dangerous_goods]       VARCHAR (4)     NULL,
    [exp_taxes_amount]             NUMERIC (17, 2) NULL,
    [exp_specific_circumstance]    VARCHAR (1)     NULL,
    [exp_digital_signature]        TINYINT         NULL,
    [exp_time_to_release_decision] DATETIME        NULL,
    [exp_time_to_exit_results]     DATETIME        NULL,
    [exp_time_to_send_exp_confirm] DATETIME        NULL,
    [exp_sp]                       TINYINT         NULL,
    [exp_exit_date]                DATETIME        NULL,
    [exp_exit_stopped_date]        DATETIME        NULL,
    [exp_release_date]             DATETIME        NULL,
    [exp_status]                   CHAR (1)        NOT NULL,
    [exp_time_to_auto_acceptance]  DATETIME        NULL,
    [exp_transport_charges_mp]     VARCHAR (1)     NULL,
    [exp_tran_char_mp_di]          VARCHAR (1)     NULL,
    [exp_tran_char_mp_di_c]        VARCHAR (140)   NULL,
    [exp_crn_di]                   VARCHAR (70)    NULL,
    [exp_crn_di_c]                 VARCHAR (140)   NULL,
    [exp_supp_decl_delivery_date]  DATETIME        NULL,
    [exp_co_of_supplement]         VARCHAR (8)     NULL,
    [exp_time_to_delivery_suppl]   DATETIME        NULL,
    [exp_supplement_decl]          TINYINT         NULL,
    [printead]                     NUMERIC (1)     NULL,
    [from_emcs]                    TINYINT         NULL,
    [exp_co_of_present]            VARCHAR (8)     NULL,
    [transit]                      BIT             NOT NULL,
    [presentation_goods_co]        VARCHAR (8)     NULL,
    [centralised_customs]          BIT             NOT NULL,
    CONSTRAINT [pk_ecs_exp_declcoexport] PRIMARY KEY CLUSTERED ([decl_id] ASC)
);

