CREATE TABLE [aies].[ecs_ext_declcoexit] (
    [decl_id]                      NUMERIC (19)    NOT NULL,
    [ext_gross_mass]               NUMERIC (18, 3) NULL,
    [ext_gross_mass_br_c]          NVARCHAR (255)  NULL,
    [ext_no_of_items_br_c]         NVARCHAR (140)  NULL,
    [crb_code]                     VARCHAR (2)     NULL,
    [crb_state_of_seals]           TINYINT         NULL,
    [pad_place]                    NVARCHAR (35)   NULL,
    [pad_date]                     DATETIME        NULL,
    [s_quantity]                   INT             NULL,
    [cr_code]                      VARCHAR (2)     NULL,
    [log_co]                       VARCHAR (8)     NULL,
    [log_location_desc]            VARCHAR (35)    NULL,
    [log_location_code]            VARCHAR (17)    NULL,
    [pos_location_desc]            VARCHAR (35)    NULL,
    [pos_location_code]            VARCHAR (17)    NULL,
    [it_identity_br]               VARCHAR (31)    NULL,
    [it_identity_br_c]             VARCHAR (140)   NULL,
    [it_identity]                  VARCHAR (31)    NULL,
    [ext_ecs_decl]                 TINYINT         NULL,
    [ext_co_of_exit]               VARCHAR (8)     NULL,
    [ext_co_of_exit_declared]      VARCHAR (8)     NULL,
    [ext_co_of_exit_changed_to]    VARCHAR (8)     NULL,
    [ext_storing]                  TINYINT         NULL,
    [ext_co_of_export]             VARCHAR (8)     NULL,
    [ext_decl_type_1a]             VARCHAR (2)     NULL,
    [ext_no_of_items]              INT             NULL,
    [ext_no_of_items_br]           INT             NULL,
    [ext_no_of_package]            INT             NULL,
    [ext_no_of_packages_br]        INT             NULL,
    [ext_no_of_packages_br_c]      NVARCHAR (140)  NULL,
    [ext_country_of_export]        VARCHAR (2)     NULL,
    [ext_country_of_dest]          VARCHAR (2)     NULL,
    [ext_containers]               TINYINT         NULL,
    [ext_gross_mass_br]            NUMERIC (18, 3) NULL,
    [ext_acceptance_date]          DATETIME        NULL,
    [ext_issuing_date]             DATETIME        NULL,
    [ext_ead_language]             VARCHAR (2)     NULL,
    [ext_time_to_send_exit_result] DATETIME        NULL,
    [ext_time_to_border_arrival]   DATETIME        NULL,
    [ext_presentation_date]        DATETIME        NULL,
    [ext_notification_date]        DATETIME        NULL,
    [ext_status]                   CHAR (1)        NOT NULL,
    [ext_exit_date]                DATETIME        NULL,
    [ext_exit_stopped_date]        DATETIME        NULL,
    [ext_com_ref_num]              VARCHAR (70)    NULL,
    [ext_com_ref_num_di]           VARCHAR (70)    NULL,
    [ext_com_ref_num_di_c]         VARCHAR (140)   NULL,
    [ext_dec_sub_tim]              DATETIME        NULL,
    [ext_tra_cha_met]              VARCHAR (1)     NULL,
    [ext_tra_cha_met_di]           VARCHAR (1)     NULL,
    [ext_tra_cha_met_di_c]         VARCHAR (140)   NULL,
    [ext_spe_cir_ind]              VARCHAR (1)     NULL,
    [pad_realDate]                 DATETIME        NULL,
    [crb_code_before_transit]      VARCHAR (2)     NULL,
    [transit]                      BIT             NOT NULL,
    CONSTRAINT [pk_ecs_ext_declcoexit] PRIMARY KEY CLUSTERED ([decl_id] ASC)
);

