CREATE TABLE [aies].[ecs_ext_goods_item] (
    [id]                        NUMERIC (19)    NOT NULL,
    [gi_gross_mass]             NUMERIC (18, 3) NULL,
    [gi_country_of_export]      VARCHAR (2)     NULL,
    [gi_country_of_destination] VARCHAR (2)     NULL,
    [gi_gross_mass_br]          NUMERIC (18, 3) NULL,
    [gi_item_no]                INT             NULL,
    [gi_commodity_code]         VARCHAR (22)    NULL,
    [gi_state_br]               CHAR (1)        NOT NULL,
    [gi_desc_br]                NVARCHAR (280)  NULL,
    [gi_commodity_code_br]      VARCHAR (22)    NULL,
    [gi_net_mass]               NUMERIC (18, 3) NULL,
    [gi_net_mass_br]            NUMERIC (18, 3) NULL,
    [gi_desc]                   NVARCHAR (280)  NULL,
    [declcoexit_decl_id]        NUMERIC (19)    NOT NULL,
    [gi_pro_req]                VARCHAR (2)     NULL,
    [gi_pre_pro]                VARCHAR (2)     NULL,
    [gi_com_nom_di]             VARCHAR (8)     NULL,
    [gi_tar_cod_di]             VARCHAR (2)     NULL,
    [gi_met_of_pay]             VARCHAR (1)     NULL,
    [gi_com_nat_pro]            VARCHAR (3)     NULL,
    [gi_sta_val_cur]            VARCHAR (3)     NULL,
    [gi_sta_val_amo]            NUMERIC (17, 2) NULL,
    [gi_com_ref_num]            VARCHAR (70)    NULL,
    [gi_un_dan_goo_cod]         VARCHAR (4)     NULL,
    [gi_com_nom]                VARCHAR (8)     NULL,
    [gi_tar_cod]                VARCHAR (2)     NULL,
    [gi_tar_fir_add_cod]        VARCHAR (4)     NULL,
    [gi_tar_sec_add_cod]        VARCHAR (4)     NULL,
    [gi_nat_dd_cod]             VARCHAR (4)     NULL,
    [gi_com_nat_pro_di]         VARCHAR (3)     NULL,
    [gi_com_ref_num_di]         VARCHAR (70)    NULL,
    [gi_met_of_pay_di]          VARCHAR (1)     NULL,
    [gi_sta_val_amo_di]         NUMERIC (17, 2) NULL,
    [gi_sta_val_cur_di]         VARCHAR (3)     NULL,
    [gi_tar_fir_add_cod_di]     VARCHAR (4)     NULL,
    [gi_tar_sec_add_cod_di]     VARCHAR (4)     NULL,
    [gi_un_dan_goo_cod_di]      VARCHAR (4)     NULL,
    CONSTRAINT [pk_ecs_ext_goods_item] PRIMARY KEY CLUSTERED ([id] ASC)
);

