CREATE TABLE [aies].[ecs_sum_declcoexit] (
    [decl_id]                      NUMERIC (19)    NOT NULL,
    [pad_place]                    VARCHAR (35)    NULL,
    [pad_phone]                    VARCHAR (15)    NULL,
    [pad_date]                     DATETIME        NULL,
    [exp_no_of_items]              INT             NULL,
    [exp_co_of_exit]               VARCHAR (8)     NULL,
    [exp_no_of_packages]           INT             NULL,
    [gross_mass]                   NUMERIC (18, 3) NULL,
    [cr_code]                      VARCHAR (2)     NULL,
    [exp_acceptance_date]          DATETIME        NULL,
    [crn]                          VARCHAR (70)    NULL,
    [gross_mass_br]                NUMERIC (18, 3) NULL,
    [log_co]                       VARCHAR (8)     NULL,
    [log_location_desc]            VARCHAR (255)   NULL,
    [log_location_code]            VARCHAR (255)   NULL,
    [exp_co_of_exit_chto]          VARCHAR (8)     NULL,
    [exp_no_of_items_br]           INT             NULL,
    [exp_no_of_items_brc]          VARCHAR (140)   NULL,
    [exp_no_of_packages_br]        INT             NULL,
    [exp_no_of_packages_brc]       VARCHAR (140)   NULL,
    [gross_mass_brc]               VARCHAR (140)   NULL,
    [exp_storing]                  TINYINT         NULL,
    [exp_digital_signature]        TINYINT         NULL,
    [exp_time_to_release_decision] DATETIME        NULL,
    [exp_time_to_auto_acceptance]  DATETIME        NULL,
    [exp_exit_date]                DATETIME        NULL,
    [exp_exit_stopped_date]        DATETIME        NULL,
    [exp_release_date]             DATETIME        NULL,
    [pres_date]                    DATETIME        NULL,
    [transport_fee_pay_type]       VARCHAR (1)     NULL,
    [exp_co_of_trader]             VARCHAR (8)     NULL,
    [sum_co_of_lodg]               VARCHAR (8)     NULL,
    [peculiar_circumstances]       VARCHAR (1)     NULL,
    [exp_exit_agreementDate]       DATETIME        NULL,
    [regi_date]                    DATETIME        NULL,
    [exp_status]                   CHAR (1)        NULL,
    [exp_notification_date]        DATETIME        NULL,
    CONSTRAINT [ecs_sum_de_7534347271] PRIMARY KEY CLUSTERED ([decl_id] ASC)
);

