CREATE TABLE [aies].[ecs_query_exportquery] (
    [q_query_decl_id]          NUMERIC (19)    NOT NULL,
    [q_acceptance_date]        DATETIME        NULL,
    [q_co_exit]                VARCHAR (8)     NULL,
    [q_co_export]              VARCHAR (8)     NULL,
    [q_co_request]             VARCHAR (8)     NULL,
    [q_container_indicator]    TINYINT         NULL,
    [q_control_date_limit]     DATETIME        NULL,
    [q_control_result_code]    VARCHAR (2)     NULL,
    [q_country_dep_code]       VARCHAR (2)     NULL,
    [q_dest_country_code]      VARCHAR (2)     NULL,
    [q_dispatch_country_code]  VARCHAR (2)     NULL,
    [q_crn]                    VARCHAR (70)    NULL,
    [q_request_date]           DATETIME        NULL,
    [q_decl_type]              VARCHAR (9)     NULL,
    [q_decl_submit_time]       DATETIME        NULL,
    [q_ead_lang_code]          VARCHAR (2)     NULL,
    [q_exp_oper_state_type]    VARCHAR (3)     NULL,
    [q_gross_mass]             NUMERIC (11, 3) NULL,
    [q_identity_of_transport]  VARCHAR (27)    NULL,
    [q_id_of_tran_lang]        VARCHAR (2)     NULL,
    [q_issue_date]             DATETIME        NULL,
    [q_mrn]                    VARCHAR (21)    NULL,
    [q_number_of_items]        INT             NULL,
    [q_num_of_packages]        INT             NULL,
    [q_oth_mov_info_reqest]    VARCHAR (350)   NULL,
    [q_oth_mov_info_req_lang]  VARCHAR (2)     NULL,
    [q_oth_mov_info_response]  VARCHAR (350)   NULL,
    [q_oth_mov_info_resp_lang] VARCHAR (2)     NULL,
    [q_query_reason_code]      VARCHAR (3)     NULL,
    [s_seals_number]           INT             NULL,
    [q_spec_circum_indicator]  VARCHAR (1)     NULL,
    [q_status]                 CHAR (1)        NULL,
    [q_tran_method_of_payment] VARCHAR (1)     NULL,
    [request_msg_id]           NUMERIC (19)    NULL,
    [dts]                      CHAR (1)        NOT NULL,
    CONSTRAINT [ecs_query__18671506661] PRIMARY KEY CLUSTERED ([q_query_decl_id] ASC)
);

