CREATE TABLE [aies].[ecs_exp_goods_item] (
    [id]                          NUMERIC (19)    NOT NULL,
    [gi_gross_mass]               NUMERIC (18, 3) NULL,
    [gi_country_of_export]        VARCHAR (2)     NULL,
    [gi_country_of_destination]   VARCHAR (2)     NULL,
    [gi_gross_mass_br]            NUMERIC (18, 3) NULL,
    [gi_crn]                      NVARCHAR (70)   NULL,
    [gi_un_dangerous_goods]       VARCHAR (4)     NULL,
    [gi_taxes_amount]             NUMERIC (17, 2) NULL,
    [gi_item_no]                  INT             NULL,
    [gi_state_br]                 CHAR (1)        NOT NULL,
    [vog_statistical_value]       NUMERIC (17, 2) NULL,
    [vog_statistical_currency]    VARCHAR (3)     NULL,
    [gi_desc_br]                  NVARCHAR (280)  NULL,
    [gi_cn_code]                  VARCHAR (8)     NULL,
    [gi_taric_code]               VARCHAR (2)     NULL,
    [gi_commodity_code_br]        VARCHAR (22)    NULL,
    [gi_country_of_origin]        VARCHAR (2)     NULL,
    [gi_proc_requested]           VARCHAR (2)     NULL,
    [gi_proc_previous]            VARCHAR (2)     NULL,
    [gi_proc_detail]              VARCHAR (3)     NULL,
    [gi_net_mass]                 NUMERIC (18, 3) NULL,
    [gi_net_mass_br]              NUMERIC (18, 3) NULL,
    [gi_quantity_suppl_unit]      NUMERIC (19, 3) NULL,
    [gi_desc]                     NVARCHAR (280)  NULL,
    [declcoexport_decl_id]        NUMERIC (19)    NULL,
    [gi_transport_charges_mp]     VARCHAR (1)     NULL,
    [gi_crn_di]                   VARCHAR (70)    NULL,
    [gi_tar_fir_cod_di]           VARCHAR (4)     NULL,
    [gi_tar_sec_cod_di]           VARCHAR (4)     NULL,
    [gi_transport_charges_mp_di]  VARCHAR (1)     NULL,
    [gi_un_dangerous_goods_di]    VARCHAR (4)     NULL,
    [vog_statistical_currency_di] VARCHAR (3)     NULL,
    [vog_statistical_value_di]    NUMERIC (17, 2) NULL,
    CONSTRAINT [pk_ecs_exp_goods_item] PRIMARY KEY CLUSTERED ([id] ASC)
);

