CREATE TABLE [aies].[ICS_ZCP_ITEM_ARR_DATA] (
    [ID]                         NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]                NUMERIC (19)    NULL,
    [CHK_DATE]                   DATETIME        NULL,
    [REQUEST_ID]                 VARCHAR (35)    NULL,
    [ADD_QUANTITY]               NUMERIC (16, 6) NULL,
    [QUANTITY_SUPPL_UNIT]        VARCHAR (3)     NULL,
    [PERMISSION_NO]              VARCHAR (50)    NULL,
    [DISCREPANCY_INFO]           VARCHAR (1024)  NULL,
    [AGRIM_VALID_TO]             DATETIME        NULL,
    [ZCP_ITEM_TARIC_QUANTITY_ID] NUMERIC (19)    NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_ARR_DATA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UQ_ICS_ZCP_ITEM_ARR_DATA_REQUEST_ID] UNIQUE NONCLUSTERED ([REQUEST_ID] ASC)
);

