CREATE TABLE [aies].[ICS_ENS_PROD_DOCU] (
    [ID]          NUMERIC (19)  NOT NULL,
    [CODE]        VARCHAR (4)   NULL,
    [COMM_BR]     VARCHAR (140) NULL,
    [NUMB]        VARCHAR (35)  NULL,
    [STATE_BR]    INT           NULL,
    [ENS_ITEM_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_PR_7673387671] PRIMARY KEY CLUSTERED ([ID] ASC)
);

