CREATE TABLE [aies].[ICS_DSK_POW_O_KONTROLI] (
    [ID]            NUMERIC (19)  NOT NULL,
    [ICS_DSK_ID]    NUMERIC (19)  NOT NULL,
    [CZAS_KONTROLI] DATETIME      NULL,
    [UWAGI]         VARCHAR (255) NULL,
    CONSTRAINT [pk_ICS_DSK_POW_O_KONTROLI] PRIMARY KEY CLUSTERED ([ID] ASC)
);

