CREATE TABLE [aies].[ICS_DSK_TOWAR_WNIOSKOWANE_UNIE] (
    [ID]               NUMERIC (19)   NOT NULL,
    [ICS_DSK_TOWAR_ID] NUMERIC (19)   NULL,
    [MRN]              VARCHAR (18)   NULL,
    [NR_POZYCJI]       NUMERIC (5)    NULL,
    [STATUS]           CHAR (4)       NULL,
    [UZASADNIENIE]     VARCHAR (1024) NULL,
    CONSTRAINT [pk_ICS_DSK_TOWAR_WNIOSKOWANE_UNIE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

