CREATE TABLE [aies].[ICS_ZCP_ITEM_VALUE_DETAILS] (
    [ID]                     NUMERIC (19) NOT NULL,
    [ZCP_ITEM_VALUE_INFO_ID] NUMERIC (19) NOT NULL,
    [POSITION_ID]            NUMERIC (1)  NOT NULL,
    [CODE]                   VARCHAR (5)  NOT NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_VALUE_DETAILS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

