CREATE TABLE [aies].[ICS_DSK_TRANSPORT_WEWN] (
    [ID]                          NUMERIC (19) NOT NULL,
    [ICS_DSK_ID]                  NUMERIC (19) NOT NULL,
    [RODZAJ_TRANSPORTU]           VARCHAR (4)  NULL,
    [ZNAKI_SRODKA_TRANSPORTU]     VARCHAR (35) NULL,
    [PANSTWO_AKTYWNEGO_SR_TRANSP] CHAR (2)     NULL,
    CONSTRAINT [pk_ICS_DSK_TRANSPORT_WEWN] PRIMARY KEY CLUSTERED ([ID] ASC)
);

