CREATE TABLE [aies].[ICS_ZCP_ITEM] (
    [ID]                            NUMERIC (19)    NOT NULL,
    [ZCP_ID]                        NUMERIC (19)    NULL,
    [LEGAL_ANNOTATIONS]             VARCHAR (2000)  NULL,
    [CALC_DATE]                     DATETIME        NULL,
    [RELEASE_OF_GOODS_DATE]         DATETIME        NULL,
    [QUANTITY_SUPPL_UNIT]           NUMERIC (16, 6) NULL,
    [CN_CODE]                       VARCHAR (8)     NULL,
    [CUS_CODE]                      VARCHAR (18)    NULL,
    [TARIC_CODE]                    VARCHAR (2)     NULL,
    [ITEM_CODE]                     VARCHAR (18)    NULL,
    [COUNTRY_OF_ORIGIN]             VARCHAR (2)     NULL,
    [COUNTRY_OF_DESTINATION]        VARCHAR (2)     NULL,
    [COUNTRY_OF_DESTINATION_REGION] VARCHAR (9)     NULL,
    [COUNTRY_OF_EXPORT]             VARCHAR (2)     NULL,
    [MEASURE_NO]                    NUMERIC (2)     NULL,
    [ITEM_NO]                       NUMERIC (5)     NULL,
    [PARCEL_REFERENCE_NUMBER]       VARCHAR (35)    NULL,
    [DEFFERED_PAYMENT]              VARCHAR (35)    NULL,
    [PREFERENCE_CODE]               VARCHAR (3)     NULL,
    [ZCP_ITEM_STATUS]               VARCHAR (4)     NULL,
    [ARR_STATUS]                    VARCHAR (4)     NULL,
    [EMCS_STATUS]                   VARCHAR (4)     NULL,
    [SUSPENSION_OF_RELEASE]         VARCHAR (10)    NULL,
    [MEASURE_TYPE_CODE]             VARCHAR (3)     NULL,
    [TRANS_RATE_OF_EXCHANGE]        NUMERIC (12, 5) NULL,
    [TRANS_TYPE]                    NUMERIC (2)     NULL,
    [TRANS_CURRENCY]                VARCHAR (3)     NULL,
    [EMCS_CN_CODE]                  VARCHAR (4)     NULL,
    [EMCS_NET_MASS]                 NUMERIC (16, 6) NULL,
    [EMCS_ARC_NO]                   VARCHAR (35)    NULL,
    [PROCEDURE_CODE]                VARCHAR (7)     NULL,
    [PROCEDURE_DETAILS]             VARCHAR (3)     NULL,
    [DESCR_OF_IRREGULARITY]         VARCHAR (1024)  NULL,
    [ICS_ENS_ITEMS_ID]              NUMERIC (19)    NULL,
    [NP_SENDER_ID]                  NUMERIC (19)    NULL,
    [BE_SENDER_ID]                  NUMERIC (19)    NULL,
    [NP_RECEIVER_ID]                NUMERIC (19)    NULL,
    [BE_RECEIVER_ID]                NUMERIC (19)    NULL,
    [NP_CONTACT_ID]                 NUMERIC (19)    NULL,
    [BE_CONTACT_ID]                 NUMERIC (19)    NULL,
    [ITEM_DESCRIPTION]              VARCHAR (1000)  NULL,
    [NOTES]                         VARCHAR (260)   NULL,
    [GROSS_MASS_KG]                 NUMERIC (16, 6) NULL,
    [NET_MASS_KG]                   NUMERIC (16, 6) NULL,
    [QUANTITY]                      NUMERIC (16, 6) NULL,
    [ICS_GAN_CUST_DATA_DETL_ID]     NUMERIC (19)    NULL,
    [AGRIM]                         BIT             NOT NULL,
    [E_AD]                          BIT             NOT NULL,
    [PAYMENT_DONE]                  BIT             NOT NULL,
    [NP_SELLER_ID]                  NUMERIC (19)    NULL,
    [BE_SELLER_ID]                  NUMERIC (19)    NULL,
    [BE_BUYER_ID]                   NUMERIC (19)    NULL,
    [NP_BUYER_ID]                   NUMERIC (19)    NULL,
    [CONTINUE_PROCESSING]           BIT             NOT NULL,
    [VERIF_RESULT]                  VARCHAR (4)     NULL,
    [NET_MASS_REAL]                 NUMERIC (16, 6) NULL,
    [CN_CODE_REAL]                  VARCHAR (8)     NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM] PRIMARY KEY CLUSTERED ([ID] ASC)
);

