CREATE TABLE [aies].[ICS_DSK_ZAMK_CELNE_NUMERY] (
    [ID]                    NUMERIC (19) NOT NULL,
    [ICS_DSK_ZAMK_CELNE_ID] NUMERIC (19) NOT NULL,
    [NUMER]                 VARCHAR (35) NULL,
    CONSTRAINT [pk_ICS_DSK_ZAMK_CELNE_NUMERY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

