CREATE TABLE [aies].[ICS_OPER] (
    [ID]      NUMERIC (19)   NOT NULL,
    [ANNO]    VARCHAR (1024) NULL,
    [CODE]    VARCHAR (4)    NULL,
    [OPER]    VARCHAR (40)   NULL,
    [TIME]    DATETIME       NULL,
    [DECL_ID] NUMERIC (19)   NULL,
    CONSTRAINT [ICS_OPER_11033399641] PRIMARY KEY CLUSTERED ([ID] ASC)
);

