CREATE TABLE [aies].[ICS_ENS_ITEM_CONT] (
    [ID]          NUMERIC (19)  NOT NULL,
    [NUMBER]      VARCHAR (255) NULL,
    [STATE_BR]    VARCHAR (4)   NULL,
    [ENS_ITEM_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_IT_6073381971] PRIMARY KEY CLUSTERED ([ID] ASC)
);

