CREATE TABLE [aies].[ICS_ZCP_TRANSPORT_DOCUMENT] (
    [ID]     NUMERIC (19) NOT NULL,
    [ZCP_ID] NUMERIC (19) NULL,
    [CODE]   VARCHAR (4)  NULL,
    [DOC_NO] VARCHAR (35) NULL,
    CONSTRAINT [pk_ICS_ZCP_TRANSPORT_DOCUMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

