CREATE TABLE [aies].[ICS_DSK_OPERACJA_DECYZJA] (
    [ID]                  NUMERIC (19) NOT NULL,
    [ICS_DSK_OPERACJA_ID] NUMERIC (19) NOT NULL,
    [DATA_DECYZJI]        DATETIME     NULL,
    [MRN]                 VARCHAR (18) NULL,
    [NR_DECYZJI]          VARCHAR (40) NULL,
    [NR_POZYCJI]          NUMERIC (5)  NULL,
    [RODZAJ_DECYZJI]      VARCHAR (4)  NULL,
    CONSTRAINT [pk_ICS_DSK_OPERACJA_DECYZJA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

