CREATE TABLE [aies].[ICS_DSK] (
    [ID]                           NUMERIC (19)    NOT NULL,
    [DATA_PRZYJECIA]               DATETIME        NULL,
    [DODATKOWY_EMAIL1]             VARCHAR (35)    NULL,
    [MASA_BRUTTO]                  NUMERIC (16, 6) NULL,
    [NUMER_REFERENCYJNY_PRZESYLKI] VARCHAR (35)    NULL,
    [PLACOWKA_PODMIOTU]            VARCHAR (2)     NULL,
    [PODPIS_ELEKTRONICZNY]         BIT             NOT NULL,
    [RODZAJ_TRANSPORTU_NA_GRANICY] VARCHAR (4)     NULL,
    [STATUS]                       VARCHAR (4)     NULL,
    [TYP_ZGLOSZENIA]               VARCHAR (3)     NULL,
    [UC_DEKLARACJI]                VARCHAR (8)     NULL,
    [XMLNS]                        VARCHAR (255)   NULL,
    [OF_ODBIORCA_ID]               NUMERIC (19)    NULL,
    [PG_ODBIORCA_ID]               NUMERIC (19)    NULL,
    [OF_PODM_DO_KONTAKTU_ID]       NUMERIC (19)    NULL,
    [PG_PODM_DO_KONTAKTU_ID]       NUMERIC (19)    NULL,
    [OF_PRZEDSTAWICIEL_ID]         NUMERIC (19)    NULL,
    [PG_PRZEDSTAWICIEL_ID]         NUMERIC (19)    NULL,
    [OF_SKLAD_DEKL_ID]             NUMERIC (19)    NULL,
    [PG_SKLAD_DEKL_ID]             NUMERIC (19)    NULL,
    [REFERENCJE_DO_ZT]             BIT             NOT NULL,
    CONSTRAINT [pk_ICS_DSK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

