CREATE TABLE [aies].[ICS_ZCP_ADDRESS] (
    [ID]            NUMERIC (19) NOT NULL,
    [ZIP_CODE]      VARCHAR (9)  NULL,
    [COUNTRY]       VARCHAR (2)  NULL,
    [CITY]          VARCHAR (35) NULL,
    [STREET_AND_NO] VARCHAR (70) NULL,
    CONSTRAINT [pk_ICS_ZCP_ADDRESS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

