CREATE TABLE [aies].[ICS_ZCP_ITEM_TARIC_QUANTITY] (
    [ID]                NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]       NUMERIC (19)    NULL,
    [UNIT]              VARCHAR (3)     NULL,
    [QUALIFIER_OF_UNIT] VARCHAR (1)     NULL,
    [QUANTITY]          NUMERIC (16, 6) NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_TARIC_QUANTITY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

