CREATE TABLE [aies].[ICS_ZCP_ITEM_ERROR] (
    [ID]          NUMERIC (19)   NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19)   NULL,
    [CODE]        VARCHAR (50)   NULL,
    [MESSAGE]     VARCHAR (1024) NULL,
    [ORIGIN]      VARCHAR (20)   NULL,
    [DATE]        DATETIME       NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_ERROR] PRIMARY KEY CLUSTERED ([ID] ASC)
);

