CREATE TABLE [aies].[ICS_ZCP_ITEM_REQ_DOC] (
    [ID]          NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19) NULL,
    [DOC_CODE]    VARCHAR (4)  NULL,
    [DOC_NUMBER]  VARCHAR (35) NULL,
    [DOC_NOTES]   VARCHAR (35) NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_REQ_DOC] PRIMARY KEY CLUSTERED ([ID] ASC)
);

