CREATE TABLE [aies].[ICS_ZCP_NOTIF_ABOUT_CONTROL] (
    [ID]      NUMERIC (19)  NOT NULL,
    [ZCP_ID]  NUMERIC (19)  NULL,
    [TIME]    DATETIME      NULL,
    [REMARKS] VARCHAR (255) NULL,
    CONSTRAINT [pk_ICS_ZCP_NOTIF_ABOUT_CONTROL] PRIMARY KEY CLUSTERED ([ID] ASC)
);

