CREATE TABLE [aies].[ICS_ZCP_ITEM_CUSTOM_DEST] (
    [ID]          NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19)    NULL,
    [NAME]        VARCHAR (4)     NULL,
    [DOCUMENT_NO] VARCHAR (40)    NULL,
    [DATE]        DATETIME        NULL,
    [QUANTITY]    NUMERIC (16, 6) NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_CUSTOM_DEST] PRIMARY KEY CLUSTERED ([ID] ASC)
);

