CREATE TABLE [aies].[ICS_ZCP_CORRECTION] (
    [ID]               NUMERIC (19)   NOT NULL,
    [ZCP_OPERATION_ID] NUMERIC (19)   NULL,
    [XQLPATH]          VARCHAR (255)  NULL,
    [VALUE_BEFORE]     VARCHAR (1024) NULL,
    [VALUE_AFTER]      VARCHAR (1024) NULL,
    CONSTRAINT [pk_ICS_ZCP_CORRECTION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

