CREATE TABLE [aies].[ICS_DSK_TOWAR] (
    [ID]                           NUMERIC (19)    NOT NULL,
    [ICS_DSK_ID]                   NUMERIC (19)    NOT NULL,
    [ILOSC_TOWARU]                 NUMERIC (16, 6) NULL,
    [JEDNOSTKA_MIARY]              CHAR (3)        NULL,
    [KWOTA]                        NUMERIC (15, 2) NULL,
    [NR_POZYCJI]                   NUMERIC (5)     NULL,
    [NUMER_REFERENCYJNY_PRZESYLKI] VARCHAR (35)    NULL,
    [STATUS_POZYCJI_DSK]           VARCHAR (4)     NULL,
    [TERMIN]                       DATETIME        NULL,
    [OPIS_NIEPRAWIDL]              VARCHAR (1024)  NULL,
    [ICS_ENS_ITEMS_ID]             NUMERIC (19)    NULL,
    [OF_ODBIORCA_ID]               NUMERIC (19)    NULL,
    [PG_ODBIORCA_ID]               NUMERIC (19)    NULL,
    [OF_PODM_DO_KONTAKTU_ID]       NUMERIC (19)    NULL,
    [PG_PODM_DO_KONTAKTU_ID]       NUMERIC (19)    NULL,
    [ICS_DSK_JEDNOSTKA_MIARY_ID]   NUMERIC (19)    NULL,
    [MASA_BRUTTO]                  NUMERIC (16, 6) NULL,
    [MASA_NETTO]                   NUMERIC (16, 6) NULL,
    [OPIS_TOWARU]                  VARCHAR (1000)  NULL,
    [UWAGI]                        VARCHAR (260)   NULL,
    [REFERENCJE_DO_ZT]             BIT             NOT NULL,
    [WYNIK_KONTROLI]               VARCHAR (60)    NULL,
    [PRZETERMINOWANY]              BIT             NOT NULL,
    CONSTRAINT [pk_ICS_DSK_TOWAR] PRIMARY KEY CLUSTERED ([ID] ASC)
);

