CREATE TABLE [aies].[ICS_MESS] (
    [ID]          NUMERIC (19)  NOT NULL,
    [DESCRIPTION] VARCHAR (70)  NULL,
    [DIRECTION]   VARCHAR (1)   NULL,
    [DOC_ID]      VARCHAR (40)  NOT NULL,
    [DOC_TIME]    DATETIME      NULL,
    [MIME_TYPE]   VARCHAR (255) NULL,
    [NAMESPACE]   VARCHAR (255) NULL,
    [RECIPIENT]   VARCHAR (17)  NULL,
    [REF_NO]      VARCHAR (35)  NULL,
    [SELF_REF]    VARCHAR (25)  NULL,
    [SENDER]      VARCHAR (17)  NULL,
    [VERSION]     INT           NULL,
    [XML_NAME]    VARCHAR (255) NULL,
    [ATTACH_ID]   NUMERIC (19)  NULL,
    [DECL_ID]     NUMERIC (19)  NULL,
    [RESP_TO]     NUMERIC (19)  NULL,
    CONSTRAINT [ICS_MESS_10553397931] PRIMARY KEY CLUSTERED ([ID] ASC)
);

