CREATE TABLE [aies].[ICS_GAN] (
    [ACCP_DATE]        DATETIME      NULL,
    [CONT]             TINYINT       NULL,
    [ARRV_DATE]        DATETIME      NULL,
    [DECL_COUT]        VARCHAR (2)   NULL,
    [FACT_ENTRY]       VARCHAR (8)   NULL,
    [GROSS_MASS]       FLOAT (53)    NULL,
    [GROSS_MASS_BR]    FLOAT (53)    NULL,
    [GROSS_MASS_BRC]   VARCHAR (255) NULL,
    [INTRO_DATE]       DATETIME      NULL,
    [ITEM_NUMB]        INT           NULL,
    [ITEM_NUMB_BR]     INT           NULL,
    [ITEM_NUMB_BRC]    VARCHAR (255) NULL,
    [PACK_NUMB]        INT           NULL,
    [PACK_NUMB_BR]     INT           NULL,
    [PACK_NUMB_BRC]    VARCHAR (255) NULL,
    [PRES_DATE]        DATETIME      NULL,
    [REGI_CUST_EMAIL]  VARCHAR (35)  NULL,
    [REGI_DATE]        DATETIME      NULL,
    [STATUS]           VARCHAR (4)   NULL,
    [TAB_SINGS]        VARCHAR (31)  NULL,
    [TAB_TYPE]         VARCHAR (2)   NULL,
    [TRANS_DOC_CODE]   VARCHAR (4)   NULL,
    [TRANS_DOC_NUMB]   VARCHAR (35)  NULL,
    [ID]               NUMERIC (19)  NOT NULL,
    [PLDT_DATE]        DATETIME      NULL,
    [PLDT_PLACE]       VARCHAR (35)  NULL,
    [TAB_COUN]         VARCHAR (2)   NULL,
    [SEND_302_TIME]    DATETIME      NULL,
    [FIRST_FACT_ENTRY] VARCHAR (8)   NULL,
    CONSTRAINT [ICS_GAN_8953392231] PRIMARY KEY CLUSTERED ([ID] ASC)
);

