CREATE TABLE [aies].[ICS_ENS_SPEC_MENT] (
    [ID]          NUMERIC (19) NOT NULL,
    [CODE]        VARCHAR (5)  NULL,
    [TEXT]        VARCHAR (35) NULL,
    [ENS_ITEM_ID] NUMERIC (19) NULL,
    CONSTRAINT [ICS_ENS_SP_8313389951] PRIMARY KEY CLUSTERED ([ID] ASC)
);

