CREATE TABLE [aies].[ICS_ZCP_DIRECTIVES] (
    [ID]        NUMERIC (19)   NOT NULL,
    [ZCP_ID]    NUMERIC (19)   NULL,
    [DIRECTIVE] VARCHAR (255)  NULL,
    [ID_UNIQUE] VARCHAR (5)    NULL,
    [POS_NO]    NUMERIC (5)    NULL,
    [POINTER]   VARCHAR (255)  NULL,
    [VALUE]     VARCHAR (1024) NULL,
    CONSTRAINT [pk_ICS_ZCP_DIRECTIVES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

