CREATE TABLE [aies].[ICS_ZCP_ITEM_PACK] (
    [ID]               NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID]      NUMERIC (19) NULL,
    [PACK_QUANTITY]    NUMERIC (8)  NULL,
    [PACK_NUMBER_SIGN] VARCHAR (42) NULL,
    [PACK_TYPE]        VARCHAR (3)  NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_PACK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

