CREATE TABLE [aies].[ICS_ZCP_ADDITIONAL_INFO] (
    [ID]          NUMERIC (19)  NOT NULL,
    [ZCP_ID]      NUMERIC (19)  NULL,
    [CODE]        VARCHAR (5)   NULL,
    [DESCRIPTION] VARCHAR (512) NULL,
    CONSTRAINT [pk_ICS_ZCP_ADDITIONAL_INFO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

