CREATE TABLE [aies].[ICS_DIRT] (
    [ID]                    NUMERIC (19)   NOT NULL,
    [ADDRESSEE]             VARCHAR (40)   NULL,
    [AUTHOR]                VARCHAR (255)  NULL,
    [DIR_FOR_NEXT_CO]       VARCHAR (500)  NULL,
    [DIR_DISPATCHER]        VARCHAR (100)  NULL,
    [INFORMATION]           VARCHAR (200)  NULL,
    [WARUE]                 VARCHAR (5)    NULL,
    [WAR1]                  VARCHAR (1)    NULL,
    [WAR234]                VARCHAR (3)    NULL,
    [WAR5]                  VARCHAR (1)    NULL,
    [COMMENT]               VARCHAR (1024) NULL,
    [CONTROL_METHOD]        VARCHAR (20)   NULL,
    [MRN]                   VARCHAR (18)   NULL,
    [CONTROL_TOOL]          VARCHAR (20)   NULL,
    [ITEM_NUMBER]           NUMERIC (3)    NULL,
    [ALGORITHM_NUMBER]      VARCHAR (30)   NULL,
    [OBJECTION_NUMBER]      VARCHAR (30)   NULL,
    [RISK_AREA]             VARCHAR (12)   NULL,
    [RISK_LEVEL]            VARCHAR (1)    NULL,
    [samples]               TINYINT        NULL,
    [PROFILE]               VARCHAR (24)   NULL,
    [SEGMENT]               VARCHAR (2)    NULL,
    [STATUS]                VARCHAR (4)    NOT NULL,
    [TEXT]                  VARCHAR (1024) NULL,
    [CONTROL_TYPE]          CHAR (1)       NULL,
    [POINTER]               VARCHAR (255)  NULL,
    [RESULT]                VARCHAR (1024) NULL,
    [SOURCE]                VARCHAR (1024) NULL,
    [DECL_ID]               NUMERIC (19)   NOT NULL,
    [ITEM_TYPE]             CHAR (3)       NULL,
    [METHOD_RISK_LEVEL]     CHAR (1)       NULL,
    [REALISATION_DATE]      DATETIME       NULL,
    [ID_VERIFICATION_ITEM]  NUMERIC (19)   NULL,
    [DIRTYPE]               CHAR (3)       NULL,
    [INTRO]                 INT            NULL,
    [ORIGIN]                VARCHAR (40)   NULL,
    [VERIFICATION_REQUIRED] TINYINT        NULL,
    [MODIFIED_BY]           VARCHAR (255)  NULL,
    CONSTRAINT [pk_ICS_DIRT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

