CREATE TABLE [aies].[ICS_DSK_LOKALIZACJA] (
    [ID]                             NUMERIC (19) NOT NULL,
    [ICS_DSK_ID]                     NUMERIC (19) NOT NULL,
    [KOD_MIEJSCA_LOKALIZACJI_TOW]    VARCHAR (17) NULL,
    [KRAJ]                           CHAR (2)     NULL,
    [KWALIFIKATOR_LOKALIZACJI]       CHAR (1)     NULL,
    [MIEJSCE_LOKALIZACJI_TOWAROW_UC] VARCHAR (8)  NULL,
    [OPIS_MIEJSCA_LOKALIZACJI_TOW]   VARCHAR (70) NULL,
    [TYP_LOKALIZACJI]                CHAR (1)     NULL,
    CONSTRAINT [pk_ICS_DSK_LOKALIZACJA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

