CREATE TABLE [cel].[sad_spec_tow] (
    [id_dok]       VARCHAR (30)   NOT NULL,
    [PozId]        NUMERIC (6)    NOT NULL,
    [SpcPozId]     NUMERIC (4)    NOT NULL,
    [Opis]         VARCHAR (255)  NULL,
    [RodzOpak]     VARCHAR (255)  NULL,
    [LiczbaOpak]   NUMERIC (14)   NULL,
    [TowIlosc]     NUMERIC (14)   NULL,
    [Jm]           VARCHAR (14)   NULL,
    [ZawAlk]       NUMERIC (6, 2) NULL,
    [ZawCukru]     NUMERIC (6, 2) NULL,
    [ZawPlato]     NUMERIC (6, 2) NULL,
    [IlPaliwAkcyz] NUMERIC (14)   NULL,
    [Pref]         CHAR (1)       NULL,
    [Samochod]     CHAR (1)       NULL,
    [SamRok]       NUMERIC (4)    NULL,
    [SamMarka]     VARCHAR (30)   NULL,
    [SamTyp]       VARCHAR (30)   NULL,
    [SamPS]        VARCHAR (10)   NULL,
    [SamNrPN]      VARCHAR (30)   NULL,
    [SamNrS]       VARCHAR (30)   NULL,
    [samRP]        VARCHAR (14)   NULL,
    CONSTRAINT [PK_SAD_SPEC_TOW] PRIMARY KEY CLUSTERED ([id_dok] ASC, [PozId] ASC, [SpcPozId] ASC) WITH (FILLFACTOR = 90) ON [FG_CEL],
    CONSTRAINT [FK_SAD_SPEC_REFERENCE_SAD_TOW] FOREIGN KEY ([id_dok], [PozId]) REFERENCES [cel].[sad_tow] ([id_dok], [PozId])
);

