CREATE TABLE [cel].[sad_tow] (
    [id_dok]        VARCHAR (30)    NOT NULL,
    [PozId]         NUMERIC (6)     NOT NULL,
    [P31KwotaBand]  NUMERIC (14, 2) NULL,
    [P31RodzZw]     VARCHAR (7)     NULL,
    [P31LSpecTow]   NUMERIC (6)     NULL,
    [P31LNrKonten]  NUMERIC (6)     NULL,
    [P31LOpAkcyz]   NUMERIC (6)     NULL,
    [P32]           NUMERIC (2)     NULL,
    [P33]           VARCHAR (11)    NULL,
    [P34]           VARCHAR (2)     NULL,
    [P36]           VARCHAR (3)     NULL,
    [P37]           VARCHAR (6)     NULL,
    [P38]           NUMERIC (14)    NULL,
    [P41IloscTow]   NUMERIC (14)    NULL,
    [P41Jm]         VARCHAR (14)    NULL,
    [P42Wart]       NUMERIC (14, 2) NULL,
    [P44Kwota]      NUMERIC (14, 2) NULL,
    [P44MatPowierz] NUMERIC (14, 2) NULL,
    [P45Korekta]    NUMERIC (14, 2) NULL,
    [P46WartStat]   NUMERIC (14, 2) NULL,
    [TowarStrat]    CHAR (1)        NULL,
    [IdWzPodkl]     NUMERIC (6)     NULL,
    CONSTRAINT [PK_SAD_TOW] PRIMARY KEY CLUSTERED ([id_dok] ASC, [PozId] ASC) WITH (FILLFACTOR = 90) ON [FG_CEL],
    CONSTRAINT [FK_SAD_TOW_REFERENCE_DOK_SAD] FOREIGN KEY ([id_dok]) REFERENCES [cel].[dok_sad] ([id_dok])
);

