CREATE TABLE [pta].[AD_Dokument] (
    [Id]                                        BIGINT          NOT NULL,
    [ARC]                                       VARCHAR (21)    NOT NULL,
    [Status]                                    VARCHAR (20)    NOT NULL,
    [NrPorzadkowy]                              DECIMAL (2)     NOT NULL,
    [LRN]                                       NVARCHAR (22)   NOT NULL,
    [MRN]                                       VARCHAR (21)    NULL,
    [CzyMiejsceWysylkiKrajowe]                  BIT             DEFAULT ('0') NULL,
    [CzyPrzemieszczenieKrajowe]                 BIT             DEFAULT ('0') NULL,
    [KodPrzemieszczenia]                        CHAR (1)        NULL,
    [DataPowiadomieniaKontroli]                 DATETIME        NULL,
    [DataCzasZatwierdzeniaAD]                   DATETIME        NULL,
    [DataEksportu]                              DATETIME        NULL,
    [DataUniewaznienia]                         DATETIME        NULL,
    [DataCzasZatwierdzeniaUzup]                 DATETIME        NULL,
    [DataRaportuODostarczeniu]                  DATETIME        NULL,
    [DataCzasWysylki]                           DATETIME        NOT NULL,
    [TypZgloszenia]                             CHAR (1)        NULL,
    [KodRodzMiejscaPochRozpPrzem]               CHAR (1)        NULL,
    [KodRodzMiejscaPrzezn]                      CHAR (1)        NULL,
    [CzasPrzewozu]                              CHAR (3)        NOT NULL,
    [OrganizacjaPrzewozu]                       CHAR (1)        NOT NULL,
    [FlagaOdroczeniaPotwierdzenia]              CHAR (1)        DEFAULT ('0') NULL,
    [NrFaktury]                                 VARCHAR (35)    NOT NULL,
    [DataFaktury]                               DATE            NULL,
    [WysylajacyNrAkcyzowy]                      VARCHAR (13)    NOT NULL,
    [WysylajacyNazwa]                           NVARCHAR (182)  NOT NULL,
    [WysylajacyUlica]                           NVARCHAR (65)   NOT NULL,
    [WysylajacyNrDomu]                          NVARCHAR (11)   NULL,
    [WysylajacyKodPocztowy]                     NVARCHAR (10)   NOT NULL,
    [WysylajacyMiejscowosc]                     NVARCHAR (50)   NOT NULL,
    [MiejsceWysylkiNrSkladuPod]                 VARCHAR (13)    NULL,
    [MiejsceWysylkiNazwaPodm]                   NVARCHAR (182)  NULL,
    [MiejsceWysylkiUlica]                       NVARCHAR (65)   NULL,
    [MiejsceWysylkiNrDomu]                      NVARCHAR (11)   NULL,
    [MiejsceWysylkiKodPocztowy]                 NVARCHAR (10)   NULL,
    [MiejsceWysylkiMiejscowosc]                 NVARCHAR (50)   NULL,
    [UrzadNadzoruWMiejscuWysylki]               VARCHAR (8)     NOT NULL,
    [UrzadKontroliWMiejscuWysylki]              VARCHAR (8)     NULL,
    [OddzialDoKontroliWMiejscuZgloszenia]       VARCHAR (8)     NULL,
    [OdbierajacyIdentyfikacja]                  NVARCHAR (16)   NULL,
    [OdbierajacyNazwa]                          NVARCHAR (182)  NULL,
    [OdbierajacyUlica]                          NVARCHAR (65)   NULL,
    [OdbierajacyNrDomu]                         NVARCHAR (11)   NULL,
    [OdbierajacyKodPocztowy]                    NVARCHAR (10)   NULL,
    [OdbierajacyMiejscowosc]                    NVARCHAR (50)   NULL,
    [UzupOdbierajacyKodKraju]                   CHAR (2)        NULL,
    [UzupOdbierajacyNrSwiadectwaZwol]           VARCHAR (255)   NULL,
    [CzyOdbierajacyZmieniony]                   BIT             DEFAULT ('0') NULL,
    [MiejsceDostawyIdentyfikacja]               NVARCHAR (16)   NULL,
    [MiejsceDostawyNazwaPodm]                   NVARCHAR (182)  NULL,
    [MiejsceDostawyUlica]                       NVARCHAR (65)   NULL,
    [MiejsceDostawyNrDomu]                      NVARCHAR (11)   NULL,
    [MiejsceDostawyKodPocztowy]                 NVARCHAR (10)   NULL,
    [MiejsceDostawyMiejscowosc]                 NVARCHAR (50)   NULL,
    [UrzadNadzoruWMiejscuOdbioru]               VARCHAR (8)     NULL,
    [UrzadKontroliWMiejscuOdbioru]              VARCHAR (8)     NULL,
    [GwarantKodRodz]                            VARCHAR (4)     NULL,
    [GRN]                                       VARCHAR (17)    NULL,
    [OdbierajacyTIN]                            VARCHAR (12)    NULL,
    [GwarantTIN]                                VARCHAR (12)    NULL,
    [KwotaGwarancji]                            DECIMAL (38, 2) NULL,
    [PozostalaKwotaGwarancji]                   DECIMAL (38, 2) NULL,
    [BrakujacaKwotaGwarancji]                   DECIMAL (38, 2) NULL,
    [Gwarant1NrAkcyzowy]                        VARCHAR (13)    NULL,
    [Gwarant1Nazwa]                             NVARCHAR (182)  NULL,
    [Gwarant1Ulica]                             NVARCHAR (65)   NULL,
    [Gwarant1NrDomu]                            NVARCHAR (11)   NULL,
    [Gwarant1KodPocztowy]                       NVARCHAR (10)   NULL,
    [Gwarant1Miejscowosc]                       NVARCHAR (50)   NULL,
    [Gwarant1NrVAT]                             VARCHAR (35)    NULL,
    [Gwarant2NrAkcyzowy]                        VARCHAR (13)    NULL,
    [Gwarant2Nazwa]                             NVARCHAR (182)  NULL,
    [Gwarant2Ulica]                             NVARCHAR (65)   NULL,
    [Gwarant2NrDomu]                            NVARCHAR (11)   NULL,
    [Gwarant2KodPocztowy]                       NVARCHAR (10)   NULL,
    [Gwarant2Miejscowosc]                       NVARCHAR (50)   NULL,
    [Gwarant2NrVAT]                             VARCHAR (35)    NULL,
    [TransportKodRodz]                          CHAR (2)        NOT NULL,
    [OrganizatorTranspNrVAT]                    VARCHAR (35)    NULL,
    [OrganizatorTranspNazwa]                    NVARCHAR (182)  NULL,
    [OrganizatorTranspUlica]                    NVARCHAR (65)   NULL,
    [OrganizatorTranspNrDomu]                   NVARCHAR (11)   NULL,
    [OrganizatorTranspKodPocztowy]              NVARCHAR (10)   NULL,
    [OrganizatorTranspMiejscowosc]              NVARCHAR (50)   NULL,
    [PierwszyPrzewoznikNrVAT]                   VARCHAR (35)    NULL,
    [PierwszyPrzewoznikNazwa]                   NVARCHAR (182)  NULL,
    [PierwszyPrzewoznikUlica]                   NVARCHAR (65)   NULL,
    [PierwszyPrzewoznikNrDomu]                  NVARCHAR (11)   NULL,
    [PierwszyPrzewoznikKodPocztowy]             NVARCHAR (10)   NULL,
    [PierwszyPrzewoznikMiejscowosc]             NVARCHAR (50)   NULL,
    [CzyPrzewoznikZmieniony]                    BIT             DEFAULT ('0') NULL,
    [CzySkontrolowanoMiejsceWysylki]            BIT             DEFAULT ('0') NULL,
    [CzySkontrolowanoMiejsceDostawy]            BIT             DEFAULT ('0') NULL,
    [CzyPowiadomionoODostarczeniu]              BIT             NULL,
    [CzyOpozniony]                              BIT             DEFAULT ('0') NULL,
    [CzyWyjasnieniaZgloszonePrzezWysylajacego]  BIT             DEFAULT ('0') NULL,
    [CzyWyjasnieniaZgloszonePrzezOdbierajacego] BIT             DEFAULT ('0') NULL,
    [CzyPrzemieszczeniePrzeterminowane]         BIT             DEFAULT ('0') NULL,
    [NadrzednyARC]                              VARCHAR (21)    NULL,
    [DataOdrzuceniaLubOstrzezenia]              DATETIME        NULL,
    [DataPodzialuPrzesylki]                     DATETIME        NULL,
    CONSTRAINT [PK_AD_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC)
);

