CREATE TABLE [pta].[AD_Wyrob] (
    [Id]                            BIGINT          NOT NULL,
    [IdPozycjiTowarowej]            BIGINT          NULL,
    [KategoriaWyrobuAkcyzowego]     CHAR (1)        NOT NULL,
    [KodWyrobuAkcyzowego]           VARCHAR (4)     NOT NULL,
    [KodCN]                         VARCHAR (8)     NOT NULL,
    [Ilosc]                         DECIMAL (18, 3) NOT NULL,
    [PozostalaIlosc]                DECIMAL (18, 3) NOT NULL,
    [IloscDodJednMiary]             DECIMAL (18, 3) NULL,
    [IloscDodJednMiaryPoOdbiorze]   DECIMAL (18, 3) NULL,
    [MasaBrutto]                    DECIMAL (17, 2) NOT NULL,
    [PozostalaWagaBrutto]           DECIMAL (17, 2) NOT NULL,
    [MasaNetto]                     DECIMAL (17, 2) NOT NULL,
    [PozostalaWagaNetto]            DECIMAL (17, 2) NOT NULL,
    [ZawartoscAlkoholu]             DECIMAL (7, 2)  NULL,
    [StopienPlato]                  DECIMAL (7, 2)  NULL,
    [TypPaliwa]                     CHAR (1)        NULL,
    [OlejeNiebarwioneINieoznaczane] CHAR (1)        NULL,
    [IloscDodanychBiokomponentow]   DECIMAL (18, 3) NULL,
    [MaksymalnaCenaDetaliczna]      DECIMAL (7, 2)  NULL,
    [ZnakiAkcyzy]                   NVARCHAR (350)  NULL,
    [ZnakAkcyzy]                    CHAR (1)        NULL,
    [MiejscePochodzenia]            NVARCHAR (350)  NULL,
    [WielkoscProducenta]            VARCHAR (15)    NULL,
    [Gestosc]                       DECIMAL (7, 2)  NULL,
    [OpisHandlowy]                  NVARCHAR (350)  NULL,
    [MarkaWyrobow]                  NVARCHAR (350)  NULL,
    [KategoriaWyrobuWiniarskiego]   CHAR (1)        NULL,
    [KodStrefyUprawyWinorosli]      CHAR (2)        NULL,
    [KrajTrzeciPochodzeniaWino]     CHAR (2)        NULL,
    [DodInfWino]                    NVARCHAR (350)  NULL,
    [NiedoborLubNadwyzka]           CHAR (1)        NULL,
    [IloscNiedoboruLubNadwyzki]     DECIMAL (18, 3) NULL,
    [KwotaGwarancji]                DECIMAL (38, 2) NULL,
    [PozostalaKwotaGwarancji]       DECIMAL (38, 2) NULL,
    [BrakujacaKwotaGwarancji]       DECIMAL (38, 2) NULL,
    [PotwProduktDostarczony]        CHAR (1)        DEFAULT ('0') NULL,
    [IdDokAD]                       BIGINT          NOT NULL,
    [BiokomponentyCzySpelWymJakosc] CHAR (1)        NULL,
    CONSTRAINT [PK_AD_Wyrob] PRIMARY KEY CLUSTERED ([Id] ASC)
);

