CREATE TABLE [ncts2].[AnalizaRyzykaObslugaWskazanKontroli] (
    [Id]                                       BIGINT          NOT NULL,
    [IdDokumentuAR]                            BIGINT          NULL,
    [Zrodlo]                                   NVARCHAR (36)   NULL,
    [NumerAlgorytmu]                           NVARCHAR (30)   NULL,
    [Autor]                                    NVARCHAR (30)   NULL,
    [War1]                                     NVARCHAR (36)   NULL,
    [War1SO]                                   NVARCHAR (36)   NULL,
    [War24]                                    NVARCHAR (36)   NULL,
    [War24SO]                                  NVARCHAR (36)   NULL,
    [War5]                                     NVARCHAR (36)   NULL,
    [War5SO]                                   NVARCHAR (36)   NULL,
    [ZmianaWarUzasadnienieSO]                  NVARCHAR (200)  NULL,
    [ObszarRyzyka]                             NVARCHAR (36)   NULL,
    [ZmianaMetodKontroliUzasadnienieSO]        NVARCHAR (200)  NULL,
    [TrescDyrektywy]                           NVARCHAR (350)  NULL,
    [InformacjaDlaDyspozytora]                 NVARCHAR (200)  NULL,
    [DecyzjaDyspozytoraSO]                     SMALLINT        NULL,
    [OdstapienieOdKontroliUzasadnienieSO]      NVARCHAR (100)  NULL,
    [AdresaciDyrektywySO]                      NVARCHAR (1000) NULL,
    [ZalecenieDyspozytoraSO]                   NVARCHAR (350)  NULL,
    [DyrektywaDlaKolejnegoUCWprowadzeniaSO]    NVARCHAR (500)  NULL,
    [ZakresPrzebiegKontroliSO]                 NVARCHAR (200)  NULL,
    [WynikKontroliSO]                          NVARCHAR (36)   NULL,
    [MetodaAnalizy]                            NVARCHAR (1)    NULL,
    [CzyWidocznaWInnychUC]                     NVARCHAR (1)    NOT NULL,
    [NumerProfiluAlgorytmu]                    INT             NULL,
    [NumerZastrzezenia]                        INT             NULL,
    [RolaWystepowaniaPodmiotu]                 NVARCHAR (36)   NULL,
    [PoziomRyzyka]                             NVARCHAR (1)    NULL,
    [Status]                                   NVARCHAR (1)    NULL,
    [IdUzytkownikaObslugujacego]               BIGINT          NULL,
    [IdUzytkownikaRejestrujacegoWynikKontroli] BIGINT          NULL,
    [KontrolerObszarRyzyka]                    NVARCHAR (50)   NULL,
    [KontrolerPowodZmianyMetody]               NVARCHAR (200)  NULL,
    [DyspozytorPowodZmianyMetody]              NVARCHAR (200)  NULL,
    [KontrolerWynikKontroli]                   NVARCHAR (1)    NULL,
    [KontrolerPrzebiegKontroli]                NVARCHAR (1000) NULL,
    [Segment]                                  NVARCHAR (36)   NULL,
    [CzasZarejestrowaniaWyniku]                DATETIME        NULL,
    [CzasObslugi]                              DATETIME        NULL,
    [Dyspozycja]                               NVARCHAR (1000) NULL,
    CONSTRAINT [AnalizaRyzykaObslugaWskazanKontroli_pk] PRIMARY KEY CLUSTERED ([Id] ASC)
);

