CREATE TABLE [ncts2].[Towary] (
    [Id]                                        BIGINT          NOT NULL,
    [IdOperacjiTranzytowej]                     BIGINT          NULL,
    [IdPozycji]                                 INT             NULL,
    [TypDeklaracji]                             NVARCHAR (5)    NULL,
    [KrajWysylki]                               NVARCHAR (2)    NULL,
    [KrajPrzeznaczenia]                         NVARCHAR (2)    NULL,
    [Opis]                                      NVARCHAR (280)  NULL,
    [KodTowarowy]                               NVARCHAR (8)    NULL,
    [MasaBrutto]                                NUMERIC (14, 3) NULL,
    [MasaNetto]                                 NUMERIC (14, 3) NULL,
    [NadawcaNazwa]                              NVARCHAR (35)   NULL,
    [NadawcaUlicaNumer]                         NVARCHAR (35)   NULL,
    [NadawcaKodPocztowy]                        NVARCHAR (9)    NULL,
    [NadawcaMiejscowosc]                        NVARCHAR (35)   NULL,
    [NadawcaKraj]                               NVARCHAR (2)    NULL,
    [NadawcaTIN]                                NVARCHAR (17)   NULL,
    [OdbiorcaNazwa]                             NVARCHAR (35)   NULL,
    [OdbiorcaUlicaNumer]                        NVARCHAR (35)   NULL,
    [OdbiorcaKodPocztowy]                       NVARCHAR (9)    NULL,
    [OdbiorcaMiejscowosc]                       NVARCHAR (35)   NULL,
    [OdbiorcaKraj]                              NVARCHAR (2)    NULL,
    [OdbiorcaTIN]                               NVARCHAR (17)   NULL,
    [BezpieczenstwoFormaPlatnosci]              NVARCHAR (1)    NULL,
    [BezpieczenstwoNrReferencyjnyPrzesylki]     NVARCHAR (70)   NULL,
    [BezpieczenstwoKodUNTowarowNiebezpiecznych] NVARCHAR (4)    NULL,
    [BezpieczenstwoNadawcaNazwa]                NVARCHAR (35)   NULL,
    [BezpieczenstwoNadawcaUlicaNumer]           NVARCHAR (35)   NULL,
    [BezpieczenstwoNadawcaKodPocztowy]          NVARCHAR (9)    NULL,
    [BezpieczenstwoNadawcaMiejscowosc]          NVARCHAR (35)   NULL,
    [BezpieczenstwoNadawcaKraj]                 NVARCHAR (2)    NULL,
    [BezpieczenstwoNadawcaTIN]                  NVARCHAR (17)   NULL,
    [BezpieczenstwoOdbiorcaNazwa]               NVARCHAR (35)   NULL,
    [BezpieczenstwoOdbiorcaUlicaNumer]          NVARCHAR (35)   NULL,
    [BezpieczenstwoOdbiorcaKodPocztowy]         NVARCHAR (9)    NULL,
    [BezpieczenstwoOdbiorcaMiejscowosc]         NVARCHAR (35)   NULL,
    [BezpieczenstwoOdbiorcaKraj]                NVARCHAR (2)    NULL,
    [BezpieczenstwoOdbiorcaTIN]                 NVARCHAR (17)   NULL,
    [TrybUtworzeniaPozycji]                     NVARCHAR (1)    NULL,
    [IteracjaUwagRozladunkowych]                SMALLINT        NULL,
    [NadawcaCertyfikatAEO]                      NVARCHAR (35)   NULL,
    [OdbiorcaCertyfikatAEO]                     NVARCHAR (35)   NULL,
    [BezpieczenstwoNadawcaCertyfikatAEO]        NVARCHAR (35)   NULL,
    [BezpieczenstwoOdbiorcaCertyfikatAEO]       NVARCHAR (35)   NULL,
    [OpisJezyk]                                 NVARCHAR (2)    NULL,
    CONSTRAINT [Towary_pk] PRIMARY KEY CLUSTERED ([Id] ASC)
);

