CREATE TABLE [osoz].[zabezpieczenia] (
    [id]                                         BIGINT          NOT NULL,
    [czas_modyfikacji]                           DATETIME        NULL,
    [data_decyzji_zgody_na_ryczalt]              DATETIME        NULL,
    [data_ostatniej_windykacji]                  DATETIME        NULL,
    [data_przyjecia_zabezpieczenia_gry]          DATETIME        NULL,
    [data_rejestracji_zabezpieczenia]            DATETIME        NOT NULL,
    [data_wydania_karnetu]                       DATETIME        NULL,
    [data_wydania_potwierdzenia]                 DATETIME        NULL,
    [data_wydania_zwolnienia]                    DATETIME        NULL,
    [grn]                                        VARCHAR (50)    NULL,
    [karnet_papierowy_porzekazany]               BIT             NULL,
    [karnet_tir]                                 BIT             NULL,
    [kod_dostepu]                                VARCHAR (255)   NULL,
    [kontrahent_windykowany]                     BIT             NULL,
    [kraj_zlozenia_zabezpieczenia]               VARCHAR (255)   NOT NULL,
    [krotnosc_zlozonych_zabezpieczen]            INT             NULL,
    [kwota_windykacji]                           NUMERIC (19, 2) NULL,
    [kwota_zabezpieczenia]                       NUMERIC (19, 2) NOT NULL,
    [liczba_kasyn_punktow_przyjmowania_zakladow] INT             NULL,
    [nabywca_wewnetrzny_z_zaplacona_akcyza]      BIT             NULL,
    [niewazne_na_terenie_ue]                     BIT             NULL,
    [nr_decyzji_naczelnika_urzedu]               VARCHAR (30)    NULL,
    [nr_decyzji_zgoda_na_ryczalt]                VARCHAR (30)    NULL,
    [obcy_sklad_podatkowy]                       BIT             NULL,
    [obszar_waznosci_akcyza]                     VARCHAR (2)     NULL,
    [podatnik_okreslony_w_art_13_ust_3]          BIT             NULL,
    [powod_uniewaznienia]                        VARCHAR (255)   NULL,
    [przedstawiciel_podatkowy]                   BIT             NULL,
    [rodzaj]                                     VARCHAR (6)     NULL,
    [saldo_zabezpieczenia]                       NUMERIC (19, 2) NOT NULL,
    [status]                                     VARCHAR (2)     NOT NULL,
    [typ]                                        VARCHAR (2)     NOT NULL,
    [urzad_przeznaczenia]                        VARCHAR (255)   NULL,
    [urzad_wyjscia]                              VARCHAR (255)   NULL,
    [wariant]                                    VARCHAR (2)     NULL,
    [wazne_do]                                   DATETIME        NULL,
    [wazne_na_towary_wrazliwe]                   BIT             NULL,
    [wazne_na_towary_zawieszone]                 BIT             NULL,
    [wazne_od]                                   DATETIME        NOT NULL,
    [wskaznik_uzycia]                            BIGINT          NULL,
    [zgoda_naczelnika]                           BIT             NULL,
    [kontrahent_id]                              BIGINT          NOT NULL,
    [pozwolenie_id]                              BIGINT          NULL,
    [urzad_zlozenia_zabezpieczenia_id]           BIGINT          NOT NULL,
    [sl_waluty_id]                               BIGINT          NULL,
    [nr_decyzji_kancelaryjny]                    VARCHAR (30)    NULL,
    [opl_paliw]                                  BIT             NULL,
    [w_tym_opl_paliw]                            NUMERIC (19, 2) NULL,
    CONSTRAINT [PK__zabezpie__3213E83FEB553A06] PRIMARY KEY CLUSTERED ([id] ASC)
);

