-- =============================================
-- Author:		Aleksander Łużny
-- Create date: 2014-07-09
-- Description:	Procedura czyści wszystkie tabele przygotowując je do zasilenia (przyrostowego) z systemu EMCS
-- =============================================
CREATE PROCEDURE [emcs].[TruncateAllFromEMCS]
AS
BEGIN
	SET NOCOUNT ON;
		
		TRUNCATE TABLE emcs.DICTIONARIES;
		TRUNCATE TABLE emcs.DICTIONARY_VALUES;
		TRUNCATE TABLE emcs.ECS_DECL_VERIFY_RESULTS;
		TRUNCATE TABLE emcs.ECS_DECLARATION_MVMTS;
		TRUNCATE TABLE emcs.ECS_DECLARATIONS;
		TRUNCATE TABLE emcs.EMCS_ACO;
		TRUNCATE TABLE emcs.EMCS_ACO_MESSAGE_RELATIONS;
		TRUNCATE TABLE emcs.EMCS_ACO_MESSAGES;
		TRUNCATE TABLE emcs.EMCS_ACO_MOVEMENTS;
		TRUNCATE TABLE emcs.EMCS_ACO_PROCESS_INSTANCES;
		TRUNCATE TABLE emcs.EMCS_ACO_READERS;
		TRUNCATE TABLE emcs.EMCS_DOWN_MESSAGES;
		TRUNCATE TABLE emcs.EMCS_DOWN_MOVEMENTS;
		TRUNCATE TABLE emcs.EMCS_DOWN_MVMT_PROD;
		TRUNCATE TABLE emcs.EMCS_EXCISE_RATES;
		TRUNCATE TABLE emcs.EMCS_FOLLOW_UP_MESSAGES;
		TRUNCATE TABLE emcs.EMCS_TIMER_TYPES;
		TRUNCATE TABLE emcs.EMCS_TIMERS;
		TRUNCATE TABLE emcs.EMCS_USER_TASK_TYPES;
		TRUNCATE TABLE emcs.EMCS_USER_TASKS;
		TRUNCATE TABLE emcs.EMCS_USER_TASKS_JN;
		TRUNCATE TABLE emcs.EMCS_USER_TASKS_SAD_DOCS;
		TRUNCATE TABLE emcs.EXCISE_PRODUCTS;
		TRUNCATE TABLE emcs.MESSAGE_TYPES;
		TRUNCATE TABLE emcs.[MESSAGES];
		TRUNCATE TABLE emcs.MOVEMENTS;
		TRUNCATE TABLE emcs.MVMT_CERTIFICATES;
		TRUNCATE TABLE emcs.MVMT_DOWNSTREAM_MOVEMENTS;
		TRUNCATE TABLE emcs.MVMT_INTERESTED_OFFICES;
		TRUNCATE TABLE emcs.MVMT_PACKAGES;
		TRUNCATE TABLE emcs.MVMT_PRODUCTS;
		TRUNCATE TABLE emcs.MVMT_SAD_DOCUMENTS;
		TRUNCATE TABLE emcs.MVMT_TRANSPORT_DETAILS;
		TRUNCATE TABLE emcs.MVMT_WINE_OPERATION_CODES;
		TRUNCATE TABLE emcs.PACKAGING_CODES;
		TRUNCATE TABLE emcs.REF_SD2_MIEJSCA_ODBIORU;
		TRUNCATE TABLE emcs.REF_SD2_PODMIOTY;
		TRUNCATE TABLE emcs.REF_SD2_PRZEDSTAWICIELE;
		TRUNCATE TABLE emcs.REF_SD2_UBYTKI_TRANS;
		TRUNCATE TABLE emcs.REF_SD2_UBYTKI_TRANS_KODY_CN;
		TRUNCATE TABLE emcs.REF_SD2_UBYTKI_TRANS_OPAK;
		TRUNCATE TABLE emcs.REF_SD2_UBYTKI_TRANS_SRODKI;
		TRUNCATE TABLE emcs.REF_SD2_WLASCICIELE;
		TRUNCATE TABLE emcs.REF_SD2_WYROBY;
		TRUNCATE TABLE emcs.REF_SD2_ZABEZPIECZENIA;
		TRUNCATE TABLE emcs.REQUEST_MESSAGES;
		TRUNCATE TABLE emcs.TFILE;

	END