CREATE TABLE [MF\FPLC].[N2_Spytk] (
    [DataOtw]              DATETIME        NULL,
    [DataZwoln]            DATETIME        NULL,
    [mrn]                  NVARCHAR (18)   NULL,
    [TypDekl]              NVARCHAR (5)    NULL,
    [NrPoz]                INT             NULL,
    [UCWyj]                NVARCHAR (8)    NULL,
    [UCPrzyb]              NVARCHAR (35)   NULL,
    [UCPrzznD]             NVARCHAR (8)    NULL,
    [UCPrzzn]              NVARCHAR (8)    NULL,
    [KrWys]                NVARCHAR (2)    NULL,
    [KrPrzzn]              NVARCHAR (2)    NULL,
    [GZ_tin]               NVARCHAR (17)   NULL,
    [GZ_nazwa]             NVARCHAR (35)   NULL,
    [GZ_ulica]             NVARCHAR (100)  NULL,
    [GZ_kodP]              NVARCHAR (9)    NULL,
    [GZ_miejsc]            NVARCHAR (52)   NULL,
    [GZ_kraj]              NVARCHAR (2)    NULL,
    [GZPrz_nazwa]          NVARCHAR (35)   NULL,
    [GZPrz_ulica]          NVARCHAR (100)  NULL,
    [GZPrz_kodP]           NVARCHAR (9)    NULL,
    [GZPrz_miejsc]         NVARCHAR (52)   NULL,
    [GZPrz_kraj]           NVARCHAR (2)    NULL,
    [nadawca_tin]          NVARCHAR (17)   NULL,
    [nadawca_nazwa]        NVARCHAR (35)   NULL,
    [nadawca_ulica_numer]  NVARCHAR (100)  NULL,
    [nadawca_kod_pocztowy] NVARCHAR (9)    NULL,
    [nadawca_miejscowosc]  NVARCHAR (52)   NULL,
    [nadawca_kraj]         NVARCHAR (2)    NULL,
    [N_tinT]               NVARCHAR (17)   NULL,
    [N_nazwaT]             NVARCHAR (35)   NULL,
    [N_ulicaT]             NVARCHAR (35)   NULL,
    [N_kodpT]              NVARCHAR (9)    NULL,
    [N_miejT]              NVARCHAR (35)   NULL,
    [N_krajT]              NVARCHAR (2)    NULL,
    [N_tinTB]              NVARCHAR (17)   NULL,
    [N_nazwaTB]            NVARCHAR (35)   NULL,
    [N_adresTB]            NVARCHAR (35)   NULL,
    [N_kodpTB]             NVARCHAR (9)    NULL,
    [N_miejscTB]           NVARCHAR (35)   NULL,
    [N_krajTB]             NVARCHAR (2)    NULL,
    [O_TIN]                NVARCHAR (17)   NULL,
    [O_nazwa]              NVARCHAR (35)   NULL,
    [O_ulica]              NVARCHAR (100)  NULL,
    [O_kp]                 NVARCHAR (9)    NULL,
    [O_miejsc]             NVARCHAR (52)   NULL,
    [O_kraj]               NVARCHAR (2)    NULL,
    [O_TIN_T]              NVARCHAR (17)   NULL,
    [O_nazwaT]             NVARCHAR (35)   NULL,
    [O_ulicaT]             NVARCHAR (35)   NULL,
    [O_kodpT]              NVARCHAR (9)    NULL,
    [O_miejT]              NVARCHAR (35)   NULL,
    [O_krajT]              NVARCHAR (2)    NULL,
    [UpowOdbTIN]           NVARCHAR (17)   NULL,
    [O_TIN_TB]             NVARCHAR (17)   NULL,
    [O_nazwaTB]            NVARCHAR (35)   NULL,
    [O_ulicaTB]            NVARCHAR (35)   NULL,
    [O_kodpTB]             NVARCHAR (9)    NULL,
    [O_miejTB]             NVARCHAR (35)   NULL,
    [O_krajTB]             NVARCHAR (2)    NULL,
    [PrzedstTIN]           NVARCHAR (17)   NULL,
    [PrzedstN]             NVARCHAR (35)   NULL,
    [PrzedstAdr]           NVARCHAR (100)  NULL,
    [PrzedstKP]            NVARCHAR (9)    NULL,
    [PrzedstMjsc]          NVARCHAR (52)   NULL,
    [PrzedstKr]            NVARCHAR (2)    NULL,
    [PrzedstPrzedstawTIN]  NVARCHAR (17)   NULL,
    [PrzewozTIN_B]         NVARCHAR (17)   NULL,
    [PrzewozN_B]           NVARCHAR (35)   NULL,
    [PrzewozAdr_B]         NVARCHAR (100)  NULL,
    [PrzewozKP_B]          NVARCHAR (9)    NULL,
    [PrzewozMjsc_B]        NVARCHAR (52)   NULL,
    [PrzewozKr_B]          NVARCHAR (2)    NULL,
    [D_Przyb]              DATETIME        NULL,
    [D_Zwoln]              DATETIME        NULL,
    [TypTrW]               NVARCHAR (2)    NULL,
    [KrajTrW]              NVARCHAR (27)   NULL,
    [ZnakiTrW]             NVARCHAR (2)    NULL,
    [TypTrGr]              NVARCHAR (2)    NULL,
    [ZnakiTrGr]            NVARCHAR (2)    NULL,
    [KrajTrGr]             NVARCHAR (27)   NULL,
    [ZnakiTransp]          NVARCHAR (140)  NULL,
    [KrajTransp]           NVARCHAR (2)    NULL,
    [Kontr_UCWyj]          NVARCHAR (2)    NULL,
    [KodT]                 NVARCHAR (8)    NULL,
    [OpisT]                NVARCHAR (250)  NULL,
    [MasaB]                NUMERIC (14, 3) NULL,
    [MasaN]                NUMERIC (14, 3) NULL,
    [TypGw]                NVARCHAR (1)    NULL,
    [NrGwar1]              NVARCHAR (24)   NULL,
    [NrGw2]                NVARCHAR (35)   NULL,
    [KwotaGwWal]           NUMERIC (15, 2) NULL,
    [Waluta]               NVARCHAR (3)    NULL,
    [KwotaGwPLN]           NUMERIC (15, 2) NULL,
    [Stat_UCWy]            NVARCHAR (8)    NULL,
    [Stat_UCPrzzn]         NVARCHAR (8)    NULL
);

