CREATE TABLE [aes2].[AEO_CERTIFICATE_GROUP] (
    [id]         NUMERIC (19)  NOT NULL,
    [QUERY_DATE] DATETIME2 (3) NULL,
    CONSTRAINT [AEO_CERTIFICATE_GROUP$pk_id] PRIMARY KEY CLUSTERED ([id] ASC)
);

