CREATE TABLE [aes2].[aes_other] (
    [decl_id]                NUMERIC (19)    NOT NULL,
    [status]                 NCHAR (1)       NOT NULL,
    [source_document_number] NVARCHAR (35)   NULL,
    [gross_mass]             NUMERIC (22, 6) NULL,
    [nett_mass]              NUMERIC (22, 6) NULL,
    [co_declaration]         NVARCHAR (8)    NULL,
    [co_destination]         NVARCHAR (8)    NULL,
    [acceptance_date]        DATETIME2 (3)   NULL,
    [closing_date]           DATETIME2 (3)   NULL,
    [closing_date_limit]     DATETIME2 (3)   NULL,
    [quantity]               NUMERIC (22, 6) NULL,
    [type]                   NVARCHAR (35)   NULL,
    [procedure_s]            NVARCHAR (10)   NULL,
    [goods_description]      NVARCHAR (1536) NULL,
    [currency]               NVARCHAR (3)    NULL,
    [value]                  NUMERIC (22, 6) NULL,
    [identity_of_transport]  NVARCHAR (1536) NULL,
    [means_of_transport]     NVARCHAR (2)    NULL,
    [measure_unit]           NVARCHAR (3)    NULL,
    [kind_of_packages]       NVARCHAR (2)    NULL,
    [number_of_packages]     INT             NULL,
    [marks_of_packages]      NVARCHAR (1536) NULL,
    [reamarks]               NVARCHAR (3072) NULL,
    [assigned_flag]          TINYINT         NULL,
    [assigned_date]          DATETIME2 (3)   NULL,
    CONSTRAINT [aes_other$pk_aes_other] PRIMARY KEY CLUSTERED ([decl_id] ASC)
);

