CREATE TABLE [aes2].[AES_PSW_ITEM_CONTAINER] (
    [ID]               NUMERIC (19)  NOT NULL,
    [PSW_ITEM_ID]      NUMERIC (19)  NULL,
    [CONTAINER_NUMBER] NVARCHAR (17) NULL,
    CONSTRAINT [AES_PSW_ITEM_CONTAINER$pk_id] PRIMARY KEY CLUSTERED ([ID] ASC)
);

