CREATE TABLE [aes2].[customs_directive] (
    [id]                          NUMERIC (19)    NOT NULL,
    [addressee]                   NVARCHAR (70)   NULL,
    [author]                      NVARCHAR (255)  NULL,
    [dir_for_next_co]             NVARCHAR (500)  NULL,
    [dir_dispatcher]              NVARCHAR (300)  NULL,
    [information]                 NVARCHAR (200)  NULL,
    [warue]                       NVARCHAR (5)    NULL,
    [war1]                        NVARCHAR (1)    NULL,
    [war234]                      NVARCHAR (3)    NULL,
    [war5]                        NVARCHAR (1)    NULL,
    [comment]                     NTEXT           NULL,
    [control_method]              NVARCHAR (20)   NULL,
    [mrn]                         NVARCHAR (18)   NULL,
    [algorithm_number]            NVARCHAR (30)   NULL,
    [objection_number]            NVARCHAR (30)   NULL,
    [risk_area]                   NVARCHAR (12)   NULL,
    [samples]                     TINYINT         NULL,
    [profile]                     NVARCHAR (24)   NULL,
    [status]                      NVARCHAR (4)    NOT NULL,
    [text]                        NTEXT           NULL,
    [control_type]                NCHAR (1)       NULL,
    [pointer]                     NVARCHAR (255)  NULL,
    [result]                      NVARCHAR (1024) NULL,
    [source]                      NVARCHAR (1024) NULL,
    [decl_id]                     NUMERIC (19)    NOT NULL,
    [item_type]                   NCHAR (3)       NULL,
    [realisation_date]            DATETIME2 (3)   NULL,
    [id_verification_item]        NUMERIC (19)    NULL,
    [dirtype]                     NCHAR (3)       NULL,
    [intro]                       INT             NULL,
    [origin]                      NVARCHAR (40)   NULL,
    [verification_required]       TINYINT         NULL,
    [MODIFIED_BY]                 NVARCHAR (255)  NULL,
    [RISK_ANALYSIS_RESULT]        NVARCHAR (1)    NULL,
    [RESERVATION_NUMBER]          NVARCHAR (30)   NULL,
    [INFORMATION_FOR_DISPATCHER]  NVARCHAR (200)  NULL,
    [ADD_TEXT]                    NTEXT           NULL,
    [forced_veri]                 BIT             NOT NULL,
    [correct_calc_tsk]            TINYINT         NULL,
    [zisar_source]                NVARCHAR (20)   NULL,
    [zisar_id]                    NVARCHAR (100)  NULL,
    [ENTITY_ROLE]                 NVARCHAR (3)    NULL,
    [ADDRESSED_TO_CUSTOMS_OFFICE] BIT             NOT NULL,
    CONSTRAINT [customs_directive$PK_customs_directive] PRIMARY KEY CLUSTERED ([id] ASC)
);

