CREATE TABLE [aes2].[ecs_spp_declcoexpsuppl] (
    [spp_co_of_exit]                NVARCHAR (8)    NULL,
    [spp_co_of_exit_spp]            NVARCHAR (8)    NULL,
    [spp_co_of_export]              NVARCHAR (8)    NULL,
    [spp_co_of_export_spp]          NVARCHAR (8)    NULL,
    [spp_co_of_suppl]               NVARCHAR (255)  NULL,
    [spp_co_of_suppl_spp]           NVARCHAR (255)  NULL,
    [spp_containers]                TINYINT         NULL,
    [spp_containers_spp]            TINYINT         NULL,
    [spp_country_of_dest]           NVARCHAR (2)    NULL,
    [spp_country_of_dest_spp]       NVARCHAR (2)    NULL,
    [spp_country_of_export]         NVARCHAR (2)    NULL,
    [spp_country_of_export_spp]     NVARCHAR (2)    NULL,
    [spp_crn]                       NVARCHAR (70)   NULL,
    [spp_crn_spp]                   NVARCHAR (70)   NULL,
    [spp_decl_type_1a]              NVARCHAR (2)    NULL,
    [spp_decl_type_1b]              NVARCHAR (1)    NULL,
    [dt_code]                       NVARCHAR (3)    NULL,
    [dt_code_spp]                   NVARCHAR (3)    NULL,
    [dt_place]                      NVARCHAR (35)   NULL,
    [dt_place_code]                 NVARCHAR (1)    NULL,
    [dt_place_code_spp]             NVARCHAR (1)    NULL,
    [spp_digital_signature]         TINYINT         NULL,
    [spp_gross_mass]                NUMERIC (18, 3) NULL,
    [spp_gross_mass_spp]            NUMERIC (18, 3) NULL,
    [it_identity]                   NVARCHAR (31)   NULL,
    [it_identity_spp]               NVARCHAR (31)   NULL,
    [it_mode]                       NVARCHAR (2)    NULL,
    [it_mode_spp]                   NVARCHAR (2)    NULL,
    [lof_co]                        NVARCHAR (8)    NULL,
    [lof_co_spp]                    NVARCHAR (8)    NULL,
    [lof_location_code]             NVARCHAR (17)   NULL,
    [lof_location_code_spp]         NVARCHAR (17)   NULL,
    [lof_location_desc]             NVARCHAR (35)   NULL,
    [spp_no_of_items]               INT             NULL,
    [spp_no_of_items_spp]           INT             NULL,
    [spp_no_of_packages]            INT             NULL,
    [spp_no_of_packages_spp]        INT             NULL,
    [pad_capacity]                  NVARCHAR (35)   NULL,
    [pad_date]                      DATETIME2 (3)   NULL,
    [pad_name]                      NVARCHAR (35)   NULL,
    [pad_phone]                     NVARCHAR (15)   NULL,
    [pad_place]                     NVARCHAR (35)   NULL,
    [pos_location_code]             NVARCHAR (17)   NULL,
    [pos_location_code_spp]         NVARCHAR (17)   NULL,
    [pos_location_desc]             NVARCHAR (35)   NULL,
    [si_quantity]                   INT             NULL,
    [si_quantity_spp]               INT             NULL,
    [spp_specific_circumstance]     NVARCHAR (1)    NULL,
    [spp_specific_circumstance_spp] NVARCHAR (1)    NULL,
    [exp_status]                    NCHAR (1)       NULL,
    [spp_storing]                   TINYINT         NULL,
    [spp_storing_spp]               TINYINT         NULL,
    [exp_taxes_amount]              NUMERIC (17, 2) NULL,
    [spp_taxes_amount_spp]          NUMERIC (17, 2) NULL,
    [td_amount]                     NUMERIC (17, 2) NULL,
    [td_amount_spp]                 NUMERIC (17, 2) NULL,
    [td_currency]                   NVARCHAR (3)    NULL,
    [td_currency_spp]               NVARCHAR (3)    NULL,
    [td_exchange_rate]              NUMERIC (11, 5) NULL,
    [td_exchange_rate_spp]          NUMERIC (11, 5) NULL,
    [td_nature_of_transation]       NVARCHAR (2)    NULL,
    [td_nature_of_transation_spp]   NVARCHAR (2)    NULL,
    [tab_country]                   NVARCHAR (2)    NULL,
    [tab_country_spp]               NVARCHAR (2)    NULL,
    [tab_identity]                  NVARCHAR (31)   NULL,
    [tab_identity_spp]              NVARCHAR (31)   NULL,
    [tab_mode]                      NVARCHAR (2)    NULL,
    [tab_mode_spp]                  NVARCHAR (2)    NULL,
    [spp_transport_charges_mp]      NVARCHAR (1)    NULL,
    [spp_transport_charges_mp_spp]  NVARCHAR (1)    NULL,
    [spp_un_dangerous_goods]        NVARCHAR (4)    NULL,
    [spp_un_dangerous_goods_spp]    NVARCHAR (4)    NULL,
    [w_country]                     NVARCHAR (2)    NULL,
    [w_country_spp]                 NVARCHAR (2)    NULL,
    [w_location_code]               NVARCHAR (14)   NULL,
    [w_location_code_spp]           NVARCHAR (14)   NULL,
    [w_type]                        NVARCHAR (1)    NULL,
    [w_type_spp]                    NVARCHAR (1)    NULL,
    [decl_id]                       NUMERIC (19)    NOT NULL,
    [spp_link_date]                 DATETIME2 (3)   NULL,
    [spp_co_of_fold]                NVARCHAR (8)    NULL,
    CONSTRAINT [ecs_spp_declcoexpsuppl$ecs_spp_de_18873427571] PRIMARY KEY CLUSTERED ([decl_id] ASC)
);

