CREATE TABLE [aes2].[ecs_ext_declcoexit] (
    [decl_id]                      NUMERIC (19)    NOT NULL,
    [ext_gross_mass]               NUMERIC (18, 3) NULL,
    [ext_gross_mass_br_c]          NVARCHAR (765)  NULL,
    [ext_no_of_items_br_c]         NVARCHAR (420)  NULL,
    [crb_code]                     NVARCHAR (2)    NULL,
    [crb_state_of_seals]           TINYINT         NULL,
    [pad_place]                    NVARCHAR (105)  NULL,
    [pad_date]                     DATETIME2 (3)   NULL,
    [s_quantity]                   INT             NULL,
    [cr_code]                      NVARCHAR (2)    NULL,
    [log_co]                       NVARCHAR (8)    NULL,
    [log_location_desc]            NVARCHAR (765)  NULL,
    [log_location_code]            NVARCHAR (17)   NULL,
    [pos_location_desc]            NVARCHAR (765)  NULL,
    [pos_location_code]            NVARCHAR (17)   NULL,
    [it_identity_br]               NVARCHAR (255)  NULL,
    [it_identity_br_c]             NVARCHAR (765)  NULL,
    [it_identity]                  NVARCHAR (765)  NULL,
    [ext_ecs_decl]                 TINYINT         NULL,
    [ext_co_of_exit]               NVARCHAR (8)    NULL,
    [ext_co_of_exit_declared]      NVARCHAR (8)    NULL,
    [ext_co_of_exit_changed_to]    NVARCHAR (8)    NULL,
    [ext_storing]                  TINYINT         NULL,
    [ext_co_of_export]             NVARCHAR (8)    NULL,
    [ext_decl_type_1a]             NVARCHAR (2)    NULL,
    [ext_no_of_items]              INT             NULL,
    [ext_no_of_items_br]           INT             NULL,
    [ext_no_of_package]            INT             NULL,
    [ext_no_of_packages_br]        INT             NULL,
    [ext_no_of_packages_br_c]      NVARCHAR (420)  NULL,
    [ext_country_of_export]        NVARCHAR (2)    NULL,
    [ext_country_of_dest]          NVARCHAR (2)    NULL,
    [ext_containers]               TINYINT         NULL,
    [ext_gross_mass_br]            NUMERIC (18, 3) NULL,
    [ext_acceptance_date]          DATETIME2 (3)   NULL,
    [ext_issuing_date]             DATETIME2 (3)   NULL,
    [ext_ead_language]             NVARCHAR (2)    NULL,
    [ext_time_to_send_exit_result] DATETIME2 (3)   NULL,
    [ext_time_to_border_arrival]   DATETIME2 (3)   NULL,
    [ext_presentation_date]        DATETIME2 (3)   NULL,
    [ext_notification_date]        DATETIME2 (3)   NULL,
    [ext_status]                   NCHAR (1)       NOT NULL,
    [ext_exit_date]                DATETIME2 (3)   NULL,
    [ext_exit_stopped_date]        DATETIME2 (3)   NULL,
    [ext_com_ref_num]              NVARCHAR (70)   NULL,
    [ext_com_ref_num_di]           NVARCHAR (70)   NULL,
    [ext_com_ref_num_di_c]         NVARCHAR (140)  NULL,
    [ext_dec_sub_tim]              DATETIME2 (3)   NULL,
    [ext_tra_cha_met]              NVARCHAR (1)    NULL,
    [ext_tra_cha_met_di]           NVARCHAR (1)    NULL,
    [ext_tra_cha_met_di_c]         NVARCHAR (140)  NULL,
    [ext_spe_cir_ind]              NVARCHAR (1)    NULL,
    [pad_realDate]                 DATETIME2 (3)   NULL,
    [crb_code_before_transit]      NVARCHAR (2)    NULL,
    [transit]                      BIT             NOT NULL,
    [transit_over]                 NVARCHAR (1)    NULL,
    [canc_from_office]             BIT             CONSTRAINT [DF__ecs_ext_d__canc___7331B74C] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [ecs_ext_declcoexit$pk_ecs_ext_declcoexit] PRIMARY KEY CLUSTERED ([decl_id] ASC)
);

