CREATE TABLE [aes2].[MESSAGE_METADATA_ECS] (
    [MESSAGE_ID] NUMERIC (19)   NOT NULL,
    [META_VALUE] NVARCHAR (255) NULL,
    [META_KEY]   NVARCHAR (20)  NOT NULL,
    CONSTRAINT [PK_MESSAGE_METADATA_ECS] PRIMARY KEY CLUSTERED ([MESSAGE_ID] ASC)
);

