CREATE TABLE [aes2].[MESSAGE_LOG] (
    [ID]            NUMERIC (19)   NOT NULL,
    [DIRECTION]     NVARCHAR (10)  NULL,
    [MESSSAGE_TYPE] NVARCHAR (15)  NULL,
    [MRN]           NVARCHAR (50)  NULL,
    [MSG_TIMESTAMP] DATETIME2 (3)  NULL,
    [NAME]          NVARCHAR (100) NULL,
    CONSTRAINT [PK_MESSAGE_LOG] PRIMARY KEY CLUSTERED ([ID] ASC)
);

