CREATE TABLE [zc].[DT_Dokument] (
    [IdDok]                 VARCHAR (30) NOT NULL,
    [WersjaXML]             VARCHAR (7)  NULL,
    [DataWyeksportowania]   DATETIME     NULL,
    [RodzajDok]             VARCHAR (5)  NULL,
    [UrzadWyjsciaId]        VARCHAR (6)  NULL,
    [UrzadWyjsciaIdPid]     INT          NULL,
    [UrzadWyjsciaPas]       CHAR (2)     NULL,
    [DataRejestracji]       DATETIME     NULL,
    [DataZatwierdzenia]     DATETIME     NULL,
    [NrEwidencyjny]         VARCHAR (40) NULL,
    [TypDok]                VARCHAR (4)  NULL,
    [TranzytOtwarcie]       DATETIME     NULL,
    [TranzytZamkniecie]     DATETIME     NULL,
    [TranzytEtap]           CHAR (1)     NULL,
    [RodzajDokZrodl]        VARCHAR (6)  NULL,
    [NrDokZrodl]            VARCHAR (40) NULL,
    [NrEwidencjiZamykajacy] VARCHAR (40) NULL,
    [Status]                CHAR (1)     NULL,
    [EtapBilansowania]      CHAR (1)     NULL,
    [KrajWysylki]           CHAR (2)     NULL,
    [KrajWysylkiPid]        INT          NULL,
    [KrajDocelowy]          CHAR (2)     NULL,
    [KrajDocelowyPid]       INT          NULL,
    [IdJednPrzezn]          VARCHAR (9)  NULL,
    [IdJednPrzeznPid]       INT          NULL,
    [NrAkt]                 VARCHAR (40) NULL,
    [CharaktTowaru]         VARCHAR (10) NULL,
    [IdPodmiotu]            VARCHAR (30) NULL,
    CONSTRAINT [PK_DT_Dokument] PRIMARY KEY CLUSTERED ([IdDok] ASC) ON [FG_ZC],
    CONSTRAINT [FK_DT_Dokument_DT_Podmiot] FOREIGN KEY ([IdPodmiotu]) REFERENCES [zc].[DT_Podmiot] ([IdPodmiotu]),
    CONSTRAINT [FK_DT_Dokument_IdJednPrzeznPid] FOREIGN KEY ([IdJednPrzeznPid]) REFERENCES [pdr].[c001] ([c001_id]),
    CONSTRAINT [FK_DT_Dokument_KrajDocelowyPid] FOREIGN KEY ([KrajDocelowyPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_DT_Dokument_KrajWysylkiPid] FOREIGN KEY ([KrajWysylkiPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_DT_Dokument_UrzadWyjsciaIdPid] FOREIGN KEY ([UrzadWyjsciaIdPid]) REFERENCES [pdr].[c001] ([c001_id])
);

