CREATE TABLE [zc].[DWA_Dokument] (
    [Id]                         DECIMAL (19)    NOT NULL,
    [Status]                     CHAR (1)        NULL,
    [NrWlasny]                   VARCHAR (22)    NULL,
    [MRN]                        VARCHAR (35)    NULL,
    [CRN]                        VARCHAR (70)    NULL,
    [UrzadZlozenia]              VARCHAR (8)     NULL,
    [UrzadWyprowadzenia]         VARCHAR (8)     NULL,
    [UrzadWyprowadzeniaZm]       VARCHAR (8)     NULL,
    [SpecyficzneOkolicznosci]    CHAR (1)        NULL,
    [LiczbaPozycji]              INT             NULL,
    [LiczbaPozycjiNaGranicy]     INT             NULL,
    [LiczbaPozycjiNaGranicyKom]  VARCHAR (140)   NULL,
    [LiczbaOpakowan]             INT             NULL,
    [LiczbaOpakowanNaGranicy]    INT             NULL,
    [LiczbaOpakowanNaGranicyKom] VARCHAR (140)   NULL,
    [MasaBrutto]                 DECIMAL (18, 3) NULL,
    [MasaBruttoNaGranicy]        DECIMAL (18, 3) NULL,
    [MasaBruttoNaGranicyKom]     VARCHAR (140)   NULL,
    [KodTypOplatTransp]          CHAR (1)        NULL,
    [PodpisElektroniczny]        TINYINT         NULL,
    [EmailZwrotny]               VARCHAR (80)    NULL,
    [DataPrzyjecia]              DATETIME        NULL,
    [DataZgody]                  DATETIME        NULL,
    [Data]                       DATETIME        NULL,
    [Miejsce]                    VARCHAR (35)    NULL,
    [Telefon]                    VARCHAR (15)    NULL,
    CONSTRAINT [PK_DWA_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_ZC]
);

