CREATE TABLE [zc].[INNY_Dokument] (
    [IdDok]                         VARCHAR (30)    NOT NULL,
    [WersjaXML]                     VARCHAR (7)     NULL,
    [DataWyeksportowania]           DATETIME        NULL,
    [RodzajDok]                     VARCHAR (5)     NULL,
    [PlacowkaId]                    VARCHAR (6)     NULL,
    [PlacowkaIdPid]                 INT             NULL,
    [PlacowkaPas]                   CHAR (2)        NULL,
    [DataRejestracji]               DATETIME        NULL,
    [NrEwidencyjny]                 VARCHAR (40)    NULL,
    [DataPrzyjecia]                 DATETIME        NULL,
    [Status]                        CHAR (1)        NULL,
    [NrWlasny]                      VARCHAR (40)    NULL,
    [TypDok]                        VARCHAR (6)     NULL,
    [ProceduraBiezaca]              VARCHAR (6)     NULL,
    [ProceduraBiezacaPid]           INT             NULL,
    [ProceduraPoprzednia]           VARCHAR (6)     NULL,
    [ProceduraPoprzedniaPid]        INT             NULL,
    [Uwagi]                         VARCHAR (255)   NULL,
    [WartoscTowarow]                DECIMAL (17, 2) NULL,
    [SymbolWaluty]                  VARCHAR (3)     NULL,
    [SymbolWalutyPid]               INT             NULL,
    [Pozwolenie]                    VARCHAR (30)    NULL,
    [OdbiorcaEORI]                  VARCHAR (17)    NULL,
    [OdbiorcaTIN]                   VARCHAR (17)    NULL,
    [ZglaszajacyEORI]               VARCHAR (17)    NULL,
    [ZglaszajacyTIN]                VARCHAR (17)    NULL,
    [ZglaszajacyPrzedstawicielstwo] CHAR (1)        NULL,
    CONSTRAINT [PK_INNY_Dokument] PRIMARY KEY CLUSTERED ([IdDok] ASC) ON [FG_ZC],
    CONSTRAINT [FK_INNY_Dokument_PlacowkaIdPid] FOREIGN KEY ([PlacowkaIdPid]) REFERENCES [pdr].[c001] ([c001_id]),
    CONSTRAINT [FK_INNY_Dokument_ProceduraBiezacaPid] FOREIGN KEY ([ProceduraBiezacaPid]) REFERENCES [pdr].[s003] ([s003_id]),
    CONSTRAINT [FK_INNY_Dokument_ProceduraPoprzedniaPid] FOREIGN KEY ([ProceduraPoprzedniaPid]) REFERENCES [pdr].[s003] ([s003_id]),
    CONSTRAINT [FK_INNY_Dokument_SymbolWalutyPid] FOREIGN KEY ([SymbolWalutyPid]) REFERENCES [pdr].[s026] ([s026_id])
);

