CREATE TABLE [zc].[PDS_Towar] (
    [Id]                      DECIMAL (19)  NOT NULL,
    [NrPozycji]               INT           NULL,
    [CRN]                     VARCHAR (70)  NULL,
    [CRNUCWprow]              VARCHAR (70)  NULL,
    [OpisTowaru]              VARCHAR (280) NULL,
    [OpisTowaruUCWprow]       VARCHAR (280) NULL,
    [KodTowarowy]             VARCHAR (8)   NULL,
    [KodTowarowyUCWprow]      VARCHAR (8)   NULL,
    [MsceZaladunku]           VARCHAR (35)  NULL,
    [MsceZaladunkuUCWprow]    VARCHAR (35)  NULL,
    [MsceZaladunkuUCWprowKom] VARCHAR (140) NULL,
    [MsceWyladunku]           VARCHAR (35)  NULL,
    [MsceWyladunkuUCWprow]    VARCHAR (35)  NULL,
    [MsceWyladunkuUCWprowKom] VARCHAR (140) NULL,
    [UCWprowadzenia]          VARCHAR (8)   NULL,
    [MasaBrutto]              FLOAT (53)    NULL,
    [MasaBruttoUCWprow]       FLOAT (53)    NULL,
    [MasaBruttoSaldowanie]    FLOAT (53)    NULL,
    [KodTowNiebezp]           VARCHAR (4)   NULL,
    [KodTowNiebezpUCWprow]    VARCHAR (4)   NULL,
    [KodTowNiebezpUCWprowKom] VARCHAR (140) NULL,
    [OplTransp]               CHAR (1)      NULL,
    [OplTranspUCWprow]        CHAR (1)      NULL,
    [OplTranspUCWprowKom]     VARCHAR (140) NULL,
    [IloscOpakowanSaldowanie] INT           NULL,
    [StanPozTowUCWprow]       VARCHAR (4)   NULL,
    [StanPozTowUCWprowKom]    VARCHAR (140) NULL,
    [Status]                  VARCHAR (4)   NULL,
    [CzyPozBilansowana]       BIT           NULL,
    [CzyRoznicaIlosciPozycji] BIT           NULL,
    [Typ]                     VARCHAR (4)   NULL,
    [AnalizaRyzyka]           VARCHAR (4)   NULL,
    [Manualna]                TINYINT       NULL,
    [NrReferencyjny]          VARCHAR (35)  NULL,
    [EmailPodmiotu]           VARCHAR (80)  NULL,
    [IdPlacowki]              CHAR (2)      NULL,
    [NrWlasny]                VARCHAR (22)  NULL,
    [PodpisCyfrowy]           TINYINT       NULL,
    [IdDokPDS]                DECIMAL (19)  NULL,
    [FlagaOptimisticLock]     INT           NULL,
    CONSTRAINT [PK_PDS_Towar] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_ZC],
    CONSTRAINT [FK_PDS_Towar_IdDokPDS_PDS_Dokument_Id] FOREIGN KEY ([IdDokPDS]) REFERENCES [zc].[PDS_Dokument] ([Id])
);

