CREATE TABLE [zc].[PDS_Dokument] (
    [Id]                         DECIMAL (19)   NOT NULL,
    [UCWprowadzenia]             VARCHAR (8)    NULL,
    [UCZlozenia]                 VARCHAR (255)  NULL,
    [PrzedstawienieTowaru]       TINYINT        NULL,
    [LiczbaPozycji]              INT            NULL,
    [LiczbaOpakowan]             INT            NULL,
    [CRN]                        VARCHAR (70)   NULL,
    [NrPrzewozowy]               VARCHAR (35)   NULL,
    [MiejsceZaladunku]           VARCHAR (35)   NULL,
    [MiejsceWyladunku]           VARCHAR (35)   NULL,
    [MasaBrutto]                 FLOAT (53)     NULL,
    [SpecyficzneOkolicznosci]    CHAR (1)       NULL,
    [OplatyTransportoweMP]       CHAR (1)       NULL,
    [DataPrzybycia]              DATETIME       NULL,
    [DsSignature]                VARCHAR (4010) NULL,
    [FlagaPochodzeniaZgloszenia] TINYINT        NULL,
    [FlagaIE319]                 TINYINT        NULL,
    [Typ]                        VARCHAR (4)    NULL,
    [NrWlasny]                   VARCHAR (35)   NULL,
    [TransportKraj]              CHAR (2)       NULL,
    [TransportZnaki]             VARCHAR (31)   NULL,
    [TransportRodzaj]            CHAR (2)       NULL,
    [Miejsce]                    VARCHAR (35)   NULL,
    [Data]                       DATETIME       NULL,
    [DataPrzyjecia]              DATETIME       NULL,
    [AnalizaRyzyka]              VARCHAR (4)    NULL,
    [Manualna]                   TINYINT        NULL,
    [NrDokumentu]                VARCHAR (35)   NULL,
    [IdPlacowkiPodmiotu]         CHAR (2)       NULL,
    [PodpisCyfrowy]              TINYINT        NULL,
    [FlagaOptimisticLock]        INT            NULL,
    CONSTRAINT [PK_PDS_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_ZC]
);

