CREATE TABLE [zc].[PTW_Dokument] (
    [Id]                       NUMERIC (19)  NOT NULL,
    [NrWlasny]                 VARCHAR (35)  NULL,
    [UCWprowadzenia]           VARCHAR (8)   NULL,
    [PierwszyUCWprow]          VARCHAR (8)   NULL,
    [LiczbaPozycji]            INT           NULL,
    [LiczbaPozycjiUCWprow]     INT           NULL,
    [LiczbaPozycjiUCWprowKom]  VARCHAR (255) NULL,
    [LiczbaOpakowan]           INT           NULL,
    [LiczbaOpakowanUCWprow]    INT           NULL,
    [LiczbaOpakowanUCWprowKom] VARCHAR (255) NULL,
    [MasaBrutto]               FLOAT (53)    NULL,
    [MasaBruttoUCWprow]        FLOAT (53)    NULL,
    [MasaBruttoUCWprowKom]     VARCHAR (255) NULL,
    [KodKraju]                 CHAR (2)      NULL,
    [DataPrzyjecia]            DATETIME      NULL,
    [DataPrzybycia]            DATETIME      NULL,
    [DataRejestracji]          DATETIME      NULL,
    [DataWprowadzenia]         DATETIME      NULL,
    [DataPrzedstawienia]       DATETIME      NULL,
    [DataIE302]                DATETIME      NULL,
    [DsSignature]              VARCHAR (MAX) NULL,
    [EmailWprowadzajacego]     VARCHAR (35)  NULL,
    [Kontener]                 TINYINT       NULL,
    [Status]                   VARCHAR (4)   NULL,
    [TransportRodzaj]          CHAR (2)      NULL,
    [TransportZnaki]           VARCHAR (31)  NULL,
    CONSTRAINT [PK_PTW_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_ZC]
) TEXTIMAGE_ON [FG_ZC];

