CREATE TABLE [zc].[PWD_Dokument] (
    [IdDok]                           BIGINT          NOT NULL,
    [RodzajDok]                       VARCHAR (4)     NULL,
    [Identyfikator]                   VARCHAR (40)    NULL,
    [WersjaXML]                       VARCHAR (7)     NULL,
    [DataPrzeslania]                  DATETIME        NULL,
    [UrzadRejestracji]                VARCHAR (8)     NULL,
    [UrzadRejestracjiPid]             INT             NULL,
    [PasRejestracji]                  CHAR (2)        NULL,
    [Status]                          CHAR (1)        NULL,
    [IdJedn]                          VARCHAR (8)     NULL,
    [IdJednPid]                       INT             NULL,
    [NrCelina]                        VARCHAR (40)    NULL,
    [DataPrzyjecia]                   DATETIME        NULL,
    [Decyzja]                         CHAR (1)        NULL,
    [TerminOdpowiedzi]                DATETIME        NULL,
    [Zefir]                           CHAR (1)        NULL,
    [CzyZbiorcze]                     BIT             NULL,
    [NrWlasny]                        VARCHAR (14)    NULL,
    [Miejsce]                         VARCHAR (35)    NULL,
    [Data]                            DATETIME        NULL,
    [TowarLokalizacja]                VARCHAR (17)    NULL,
    [TerminDostarczenia]              DATETIME        NULL,
    [MasaBrutto]                      DECIMAL (14, 3) NULL,
    [TranzytRodzaj]                   VARCHAR (4)     NULL,
    [TranzytRodzajPid]                INT             NULL,
    [LiczbaOpakowan]                  INT             NULL,
    [Procedura]                       CHAR (2)        NULL,
    [ProceduraPid]                    INT             NULL,
    [WartoscStatystyczna]             BIGINT          NULL,
    [SprostowanieNrCelina]            VARCHAR (40)    NULL,
    [SprostowanieNr]                  SMALLINT        NULL,
    [SprostowanieData]                DATETIME        NULL,
    [ZamkniecieIlosc]                 SMALLINT        NULL,
    [ZamkniecieZdejmujacy]            VARCHAR (35)    NULL,
    [IdSkladajacy]                    INT             NULL,
    [IdUpowazniony]                   INT             NULL,
    [IdZglaszajacyPrzedstawiciel]     INT             NULL,
    [IdZglaszajacyPrzedstawicielEORI] INT             NULL,
    CONSTRAINT [PK_PWD_Dokument] PRIMARY KEY CLUSTERED ([IdDok] ASC) ON [FG_ZC],
    CONSTRAINT [FK_DOK_PWD_KONTRAHENT_ZP] FOREIGN KEY ([IdZglaszajacyPrzedstawiciel]) REFERENCES [zc].[PWD_Kontrahent] ([idKontrahenta]),
    CONSTRAINT [FK_PWD_Dokument_IdJednPid] FOREIGN KEY ([IdJednPid]) REFERENCES [pdr].[c001] ([c001_id]),
    CONSTRAINT [FK_PWD_Dokument_IdSkladajacy_PWD_Skladajacy_idSkladajacy] FOREIGN KEY ([IdSkladajacy]) REFERENCES [zc].[PWD_Skladajacy] ([idSkladajacy]),
    CONSTRAINT [FK_PWD_Dokument_IdUpowazniony_PWD_Kontrahent_idKontrahenta] FOREIGN KEY ([IdUpowazniony]) REFERENCES [zc].[PWD_Kontrahent] ([idKontrahenta]),
    CONSTRAINT [FK_PWD_Dokument_ProceduraPid] FOREIGN KEY ([ProceduraPid]) REFERENCES [pdr].[s003] ([s003_id]),
    CONSTRAINT [FK_PWD_Dokument_TranzytRodzajPid] FOREIGN KEY ([TranzytRodzajPid]) REFERENCES [pdr].[s025] ([s025_id]),
    CONSTRAINT [FK_PWD_Dokument_UrzadRejestracjiPid] FOREIGN KEY ([UrzadRejestracjiPid]) REFERENCES [pdr].[c001] ([c001_id])
);

