CREATE TABLE [zc].[SAD_Towar] (
    [IdDok]                   BIGINT          NOT NULL,
    [IdPozycji]               SMALLINT        NOT NULL,
    [P1c]                     VARCHAR (5)     NULL,
    [KrajWysylki]             CHAR (2)        NULL,
    [KrajWysylkiPid]          INT             NULL,
    [KrajPrzeznaczenia]       CHAR (2)        NULL,
    [KrajPrzeznaczeniaPid]    INT             NULL,
    [MasaBrutto]              DECIMAL (14, 3) NULL,
    [IdOdbiorca]              INT             NULL,
    [IdNadawca]               INT             NULL,
    [KodTowarowy]             VARCHAR (8)     NULL,
    [KodTowarowyPid]          INT             NULL,
    [KodTaric]                CHAR (2)        NULL,
    [KrajPochodzenia]         CHAR (2)        NULL,
    [KrajPochodzeniaPid]      INT             NULL,
    [Preferencje]             CHAR (3)        NULL,
    [PreferencjePid]          INT             NULL,
    [ProceduraBiezaca]        VARCHAR (4)     NULL,
    [ProceduraBiezacaPid]     INT             NULL,
    [ProceduraPoprzednia]     VARCHAR (4)     NULL,
    [ProceduraPoprzedniaPid]  INT             NULL,
    [ProceduraSzczegoly]      CHAR (3)        NULL,
    [ProceduraSzczegolyPid]   INT             NULL,
    [MasaNetto]               DECIMAL (14, 3) NULL,
    [IloscTowaruUjm]          DECIMAL (14, 3) NULL,
    [WartoscPozycji]          DECIMAL (17, 2) NULL,
    [MetodaWartosciowania]    CHAR (1)        NULL,
    [MetodaWartosciowaniaPid] INT             NULL,
    [WartoscStatystyczna]     BIGINT          NULL,
    [OpisTowaru]              VARCHAR (1000)  NULL,
    [SamochodMarka]           CHAR (3)        NULL,
    [SamochodMarkaPid]        INT             NULL,
    [SamochodNrNadwozia]      VARCHAR (35)    NULL,
    [SamochodNrSilnika]       VARCHAR (35)    NULL,
    [SamochodPojemnosc]       INT             NULL,
    [SamochodRodzajPaliwa]    CHAR (2)        NULL,
    [SamochodRodzajPaliwaPid] INT             NULL,
    [SamochodRokProdukcji]    INT             NULL,
    CONSTRAINT [PK_SAD_Towar] PRIMARY KEY CLUSTERED ([IdDok] ASC, [IdPozycji] ASC) ON [FG_ZC],
    CONSTRAINT [FK_SAD_Towar_IdDok_SAD_Dokument_IdDok] FOREIGN KEY ([IdDok]) REFERENCES [zc].[SAD_Dokument] ([IdDok]),
    CONSTRAINT [FK_SAD_Towar_IdNadawca_SAD_Kontrahent_IdKontrahenta] FOREIGN KEY ([IdNadawca]) REFERENCES [zc].[SAD_Kontrahent] ([IdKontrahenta]),
    CONSTRAINT [FK_SAD_Towar_IdOdbiorca_SAD_Kontrahent_IdKontrahenta] FOREIGN KEY ([IdOdbiorca]) REFERENCES [zc].[SAD_Kontrahent] ([IdKontrahenta]),
    CONSTRAINT [FK_SAD_Towar_KrajPochodzeniaPid] FOREIGN KEY ([KrajPochodzeniaPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_SAD_Towar_KrajPrzeznaczeniaPid] FOREIGN KEY ([KrajPrzeznaczeniaPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_SAD_Towar_KrajWysylkiPid] FOREIGN KEY ([KrajWysylkiPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_SAD_Towar_MetodaWartosciowaniaPid] FOREIGN KEY ([MetodaWartosciowaniaPid]) REFERENCES [pdr].[s082] ([s082_id]),
    CONSTRAINT [FK_SAD_Towar_PreferencjePid] FOREIGN KEY ([PreferencjePid]) REFERENCES [pdr].[s013] ([s013_id]),
    CONSTRAINT [FK_SAD_Towar_ProceduraBiezacaPid] FOREIGN KEY ([ProceduraBiezacaPid]) REFERENCES [pdr].[s003] ([s003_id]),
    CONSTRAINT [FK_SAD_Towar_ProceduraPoprzedniaPid] FOREIGN KEY ([ProceduraPoprzedniaPid]) REFERENCES [pdr].[s003] ([s003_id]),
    CONSTRAINT [FK_SAD_Towar_ProceduraSzczegolyPid] FOREIGN KEY ([ProceduraSzczegolyPid]) REFERENCES [pdr].[s076] ([s076_id]),
    CONSTRAINT [FK_SAD_Towar_SamochodMarkaPid] FOREIGN KEY ([SamochodMarkaPid]) REFERENCES [pdr].[s110] ([s110_id]),
    CONSTRAINT [FK_SAD_Towar_SamochodRodzajPaliwaPid] FOREIGN KEY ([SamochodRodzajPaliwaPid]) REFERENCES [pdr].[s111] ([s111_id])
);

