CREATE TABLE [zc].[SAD_Dokument] (
    [IdDok]                 BIGINT          NOT NULL,
    [RodzajDok]             VARCHAR (4)     NULL,
    [Typ]                   CHAR (1)        NULL,
    [TypPid]                INT             NULL,
    [Podtyp]                CHAR (1)        NULL,
    [PodtypPid]             INT             NULL,
    [CzyPowiadomienie]      BIT             NULL,
    [NrCelina]              VARCHAR (40)    NULL,
    [IdentDok]              VARCHAR (40)    NULL,
    [WersjaXML]             VARCHAR (7)     NULL,
    [IdSkladajacy]          INT             NULL,
    [DataPrzeslania]        DATETIME        NULL,
    [UrzadRejestracji]      VARCHAR (8)     NULL,
    [UrzadRejestracjiPid]   INT             NULL,
    [PasRejestracji]        CHAR (2)        NULL,
    [DataPrzedstawienia]    DATETIME        NULL,
    [NrCelina2]             VARCHAR (40)    NULL,
    [Status]                CHAR (1)        NULL,
    [DataPrzyjecia]         DATETIME        NULL,
    [TerminPU]              DATETIME        NULL,
    [TerminNaSAD]           DATETIME        NULL,
    [DostarczenieSAD]       CHAR (1)        NULL,
    [ZwolnienieTowaru]      CHAR (1)        NULL,
    [PotwierdzenieWywozu]   CHAR (1)        NULL,
    [TerminBilansowania]    DATETIME        NULL,
    [EtapBilansowania]      CHAR (1)        NULL,
    [Zefir]                 CHAR (1)        NULL,
    [RejestrDluguCelnego]   VARCHAR (20)    NULL,
    [Wykaz]                 VARCHAR (30)    NULL,
    [PozycjaWykazu]         INT             NULL,
    [DataRejestracji]       DATETIME        NULL,
    [P1a]                   CHAR (2)        NULL,
    [P1aPid]                INT             NULL,
    [P1b]                   CHAR (1)        NULL,
    [P1bPid]                INT             NULL,
    [P1c]                   VARCHAR (5)     NULL,
    [P1cPid]                INT             NULL,
    [ListyTowarowe]         INT             NULL,
    [Pozycje]               SMALLINT        NULL,
    [LiczbaOpakowan]        INT             NULL,
    [NrAkt]                 VARCHAR (14)    NULL,
    [SzczegolyWartosci]     CHAR (1)        NULL,
    [SzczegolyWartosciPid]  INT             NULL,
    [Przedstawicielstwo]    CHAR (1)        NULL,
    [PrzedstawicielstwoPid] INT             NULL,
    [Wskaznik]              VARCHAR (5)     NULL,
    [WskaznikPid]           INT             NULL,
    [IdZglaszajacy]         INT             NULL,
    [DataWpisu]             DATETIME        NULL,
    [NrWpisu]               VARCHAR (35)    NULL,
    [KrajWysylki]           CHAR (2)        NULL,
    [KrajWysylkiPid]        INT             NULL,
    [KrajPrzeznaczenia]     CHAR (2)        NULL,
    [KrajPrzeznaczeniaPid]  INT             NULL,
    [CzyKontenery]          BIT             NULL,
    [KodDost]               CHAR (3)        NULL,
    [KodDostPid]            INT             NULL,
    [MiejsceDost]           VARCHAR (35)    NULL,
    [MiejsceKodDost]        CHAR (1)        NULL,
    [MiejsceKodDostPid]     INT             NULL,
    [Waluta]                CHAR (3)        NULL,
    [WalutaPid]             INT             NULL,
    [WartoscFaktury]        DECIMAL (17, 2) NULL,
    [KursWaluty]            DECIMAL (10, 4) NULL,
    [RodzTransakcji]        CHAR (2)        NULL,
    [RodzTransakcjiPid]     INT             NULL,
    [MasaBrutto]            DECIMAL (14, 3) NULL,
    [PlatnoscOdroczona]     VARCHAR (25)    NULL,
    [IdOdbiorcaKarty3]      INT             NULL,
    [KodWynikuKontroli]     CHAR (2)        NULL,
    [TerminDostarczenia]    DATETIME        NULL,
    [IloscZamkniec]         SMALLINT        NULL,
    [Miejsce]               VARCHAR (35)    NULL,
    [Data]                  DATETIME        NULL,
    [IdGlownyZobowiazany]   INT             NULL,
    [IdUpowaznionyOdbiorca] INT             NULL,
    CONSTRAINT [PK_SAD_Dokument] PRIMARY KEY CLUSTERED ([IdDok] ASC) ON [FG_ZC],
    CONSTRAINT [FK_SAD_Dokument_IdGlownyZobowiazany_SAD_Kontrahent_IdKontrahenta] FOREIGN KEY ([IdGlownyZobowiazany]) REFERENCES [zc].[SAD_Kontrahent] ([IdKontrahenta]),
    CONSTRAINT [FK_SAD_Dokument_IdOdbiorcaKarty3_SAD_Kontrahent_IdKontrahenta] FOREIGN KEY ([IdOdbiorcaKarty3]) REFERENCES [zc].[SAD_Kontrahent] ([IdKontrahenta]),
    CONSTRAINT [FK_SAD_Dokument_IdSkladajacy_SAD_Skladajacy_IdDok] FOREIGN KEY ([IdSkladajacy]) REFERENCES [zc].[SAD_Skladajacy] ([IdSkladajacy]),
    CONSTRAINT [FK_SAD_Dokument_IdUpowaznionyOdbiorca_SAD_Kontrahent_IdKontrahenta] FOREIGN KEY ([IdUpowaznionyOdbiorca]) REFERENCES [zc].[SAD_Kontrahent] ([IdKontrahenta]),
    CONSTRAINT [FK_SAD_Dokument_IdZglaszajacy_SAD_Kontrahent_IdKontrahenta] FOREIGN KEY ([IdZglaszajacy]) REFERENCES [zc].[SAD_Kontrahent] ([IdKontrahenta]),
    CONSTRAINT [FK_SAD_Dokument_KodDostPid] FOREIGN KEY ([KodDostPid]) REFERENCES [pdr].[s002] ([s002_id]),
    CONSTRAINT [FK_SAD_Dokument_KrajPrzeznaczeniaPid] FOREIGN KEY ([KrajPrzeznaczeniaPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_SAD_Dokument_KrajWysylkiPid] FOREIGN KEY ([KrajWysylkiPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_SAD_Dokument_MiejsceKodDostPid] FOREIGN KEY ([MiejsceKodDostPid]) REFERENCES [pdr].[s078] ([s078_id]),
    CONSTRAINT [FK_SAD_Dokument_P1aPid] FOREIGN KEY ([P1aPid]) REFERENCES [pdr].[s016] ([s016_id]),
    CONSTRAINT [FK_SAD_Dokument_P1bPid] FOREIGN KEY ([P1bPid]) REFERENCES [pdr].[s017] ([s017_id]),
    CONSTRAINT [FK_SAD_Dokument_P1cPid] FOREIGN KEY ([P1cPid]) REFERENCES [pdr].[s018] ([s018_id]),
    CONSTRAINT [FK_SAD_Dokument_PodtypPid] FOREIGN KEY ([PodtypPid]) REFERENCES [pdr].[s031] ([s031_id]),
    CONSTRAINT [FK_SAD_Dokument_PrzedstawicielstwoPid] FOREIGN KEY ([PrzedstawicielstwoPid]) REFERENCES [pdr].[s077] ([s077_id]),
    CONSTRAINT [FK_SAD_Dokument_RodzTransakcjiPid] FOREIGN KEY ([RodzTransakcjiPid]) REFERENCES [pdr].[s004] ([s004_id]),
    CONSTRAINT [FK_SAD_Dokument_SzczegolyWartosciPid] FOREIGN KEY ([SzczegolyWartosciPid]) REFERENCES [pdr].[s079] ([s079_id]),
    CONSTRAINT [FK_SAD_Dokument_TypPid] FOREIGN KEY ([TypPid]) REFERENCES [pdr].[s015] ([s015_id]),
    CONSTRAINT [FK_SAD_Dokument_UrzadRejestracjiPid] FOREIGN KEY ([UrzadRejestracjiPid]) REFERENCES [pdr].[c001] ([c001_id]),
    CONSTRAINT [FK_SAD_Dokument_WalutaPid] FOREIGN KEY ([WalutaPid]) REFERENCES [pdr].[s026] ([s026_id]),
    CONSTRAINT [FK_SAD_Dokument_WskaznikPid] FOREIGN KEY ([WskaznikPid]) REFERENCES [pdr].[s083] ([s083_id])
);

