CREATE TABLE [zc].[ST_Dokument] (
    [IdDok]               VARCHAR (30) NOT NULL,
    [WersjaXML]           VARCHAR (7)  NULL,
    [DataWyeksportowania] DATETIME     NULL,
    [RodzajDok]           VARCHAR (5)  NULL,
    [UrzadWyjsciaId]      VARCHAR (6)  NULL,
    [UrzadWyjsciaIdPid]   INT          NULL,
    [UrzadWyjsciaPas]     CHAR (2)     NULL,
    [DataRejestracji]     DATETIME     NULL,
    [DataPrzyjecia]       DATETIME     NULL,
    [NrEwidencyjny]       VARCHAR (40) NULL,
    [ZglaszajacyWejscie]  VARCHAR (30) NULL,
    [ZglaszajacyWyjscie]  VARCHAR (30) NULL,
    [NazwaJednostki]      VARCHAR (35) NULL,
    [Transport]           CHAR (2)     NULL,
    [TransportPid]        INT          NULL,
    [NrRejLloyda]         VARCHAR (7)  NULL,
    [Kraj]                CHAR (2)     NULL,
    [KrajPid]             INT          NULL,
    [Bandera]             CHAR (2)     NULL,
    [BanderaPid]          INT          NULL,
    [Wypornosc]           NUMERIC (11) NULL,
    [EtapObslugiPort]     CHAR (1)     NULL,
    [Status]              CHAR (1)     NULL,
    [DataZamknEwidencji]  DATETIME     NULL,
    CONSTRAINT [PK_ST_Dokument] PRIMARY KEY CLUSTERED ([IdDok] ASC) ON [FG_ZC],
    CONSTRAINT [FK_ST_Dokument_BanderaPid] FOREIGN KEY ([BanderaPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_ST_Dokument_KrajPid] FOREIGN KEY ([KrajPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_ST_Dokument_TransportPid] FOREIGN KEY ([TransportPid]) REFERENCES [pdr].[s005] ([s005_id]),
    CONSTRAINT [FK_ST_Dokument_UrzadWyjsciaIdPid] FOREIGN KEY ([UrzadWyjsciaIdPid]) REFERENCES [pdr].[c001] ([c001_id])
);

