CREATE TABLE [zc].[ZWA_Towar] (
    [Id]                   DECIMAL (19)    NOT NULL,
    [NrPozycji]            INT             NULL,
    [StanTowaruNaGranicy]  CHAR (1)        NULL,
    [KrajWysylki]          CHAR (2)        NULL,
    [KrajPrzeznaczenia]    CHAR (2)        NULL,
    [OpisTowaru]           NVARCHAR (280)  NULL,
    [OpisTowaruNaGranicy]  NVARCHAR (280)  NULL,
    [KodTowarowy]          VARCHAR (22)    NULL,
    [KodTowarowyNaGranicy] VARCHAR (22)    NULL,
    [MasaBrutto]           DECIMAL (18, 3) NULL,
    [MasaBruttoNaGranicy]  DECIMAL (18, 3) NULL,
    [MasaNetto]            DECIMAL (18, 3) NULL,
    [MasaNettoNaGranicy]   DECIMAL (18, 3) NULL,
    [KodTypOplTransp]      CHAR (1)        NULL,
    [ProceduraWnioskowana] CHAR (2)        NULL,
    [ProceduraWymagana]    CHAR (2)        NULL,
    [ProceduraKrajowa]     CHAR (3)        NULL,
    [WalutaWartosciStat]   CHAR (3)        NULL,
    [WartoscStatystyczna]  DECIMAL (17, 2) NULL,
    [CRN]                  VARCHAR (70)    NULL,
    [TowarNiebezpieczny]   VARCHAR (4)     NULL,
    [KodScalony]           VARCHAR (8)     NULL,
    [KodTARIC]             CHAR (2)        NULL,
    [DodKodTARIC1]         VARCHAR (4)     NULL,
    [DodKodTARIC2]         VARCHAR (4)     NULL,
    [KodDod]               VARCHAR (4)     NULL,
    [IdDokZWA]             DECIMAL (19)    NOT NULL,
    CONSTRAINT [PK_ZWA_Towar] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_ZC],
    CONSTRAINT [FK_ZWA_Towar_IdDokZWA_ZWA_Dokument_IdDok] FOREIGN KEY ([IdDokZWA]) REFERENCES [zc].[ZWA_Dokument] ([Id])
);

