CREATE TABLE [zc].[ZWA_Dokument] (
    [Id]                             DECIMAL (19)    NOT NULL,
    [Status]                         CHAR (1)        NULL,
    [MRN]                            VARCHAR (35)    NULL,
    [NrWlasny]                       VARCHAR (22)    NULL,
    [UrzadWywozu]                    VARCHAR (8)     NULL,
    [UrzadWyprDekl]                  VARCHAR (8)     NULL,
    [UrzadWypr]                      VARCHAR (8)     NULL,
    [UrzadWyprZm]                    VARCHAR (8)     NULL,
    [CzyECS]                         BIT             NULL,
    [KodEAD]                         CHAR (2)        NULL,
    [Skladowanie]                    TINYINT         NULL,
    [1a]                             CHAR (2)        NULL,
    [LiczbaPoz]                      INT             NULL,
    [LiczbaPozNaGranicy]             INT             NULL,
    [LiczbaPozNaGranicyKom]          NVARCHAR (140)  NULL,
    [LiczbaOpak]                     INT             NULL,
    [LiczbaOpakNaGranicy]            INT             NULL,
    [LiczbaOpakNaGranicyKom]         NVARCHAR (140)  NULL,
    [KrajWysylki]                    CHAR (2)        NULL,
    [KrajPrzeznaczenia]              CHAR (2)        NULL,
    [Kontenery]                      TINYINT         NULL,
    [MasaBrutto]                     DECIMAL (18, 3) NULL,
    [MasaBruttoNaGranicy]            DECIMAL (18, 3) NULL,
    [MasaBruttoNaGranicyKom]         NVARCHAR (255)  NULL,
    [EmailZwrotny]                   VARCHAR (80)    NULL,
    [TerminUrzadWypr]                DATETIME        NULL,
    [TerminWysylkiKontr]             DATETIME        NULL,
    [DataPrzyjecia]                  DATETIME        NULL,
    [DataZwolnienia]                 DATETIME        NULL,
    [CRN]                            VARCHAR (70)    NULL,
    [KodTypOplatTransp]              CHAR (1)        NULL,
    [SpecyficzneOkolicznosci]        CHAR (1)        NULL,
    [DataWyslania]                   DATETIME        NULL,
    [DataPrzedstawienia]             DATETIME        NULL,
    [PrzedstTowUC]                   VARCHAR (8)     NULL,
    [PrzedstTowPozaUCKod]            VARCHAR (17)    NULL,
    [PrzedstTowPozaUCBezKodu]        VARCHAR (35)    NULL,
    [SkladTowPozaUCKod]              VARCHAR (17)    NULL,
    [SkladTowPozaUCBezKodu]          VARCHAR (35)    NULL,
    [ZnakiSrodkaPrzewoz]             VARCHAR (31)    NULL,
    [ZnakiSrodkaPrzewozNaGranicy]    VARCHAR (31)    NULL,
    [ZnakiSrodkaPrzewozNaGranicyKom] VARCHAR (140)   NULL,
    [KontrolaWywozKod]               CHAR (2)        NULL,
    [ZamkCelneLiczba]                INT             NULL,
    [KontrolaWyprKod]                CHAR (2)        NULL,
    [KontrolaWyprStan]               TINYINT         NULL,
    [Miejsce]                        NVARCHAR (35)   NULL,
    [DataPowiadomienia]              DATETIME        NULL,
    [Data]                           DATETIME        NULL,
    CONSTRAINT [PK_ZWA_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_ZC]
);

