CREATE TABLE [zc].[ZWU_Towar] (
    [Id]                   DECIMAL (19)    NOT NULL,
    [NrPozycji]            INT             NULL,
    [StanNaGranicy]        CHAR (1)        NULL,
    [CRN]                  NVARCHAR (70)   NULL,
    [KrajWysylki]          CHAR (2)        NULL,
    [KrajPochodzeniaPid]   CHAR (2)        NULL,
    [KrajPrzeznaczenia]    CHAR (2)        NULL,
    [TowarNiebezpieczny]   VARCHAR (4)     NULL,
    [OpisTowaru]           NVARCHAR (280)  NULL,
    [OpisTowaruNaGranicy]  NVARCHAR (280)  NULL,
    [KodTowarowy]          VARCHAR (8)     NULL,
    [KodTowarowyNaGranicy] VARCHAR (22)    NULL,
    [KodTARIC]             CHAR (2)        NULL,
    [KodDodUE]             VARCHAR (4)     NULL,
    [KodDodPL]             VARCHAR (4)     NULL,
    [MasaBrutto]           DECIMAL (18, 3) NULL,
    [MasaBruttoNaGranicy]  DECIMAL (18, 3) NULL,
    [MasaNetto]            DECIMAL (18, 3) NULL,
    [MasaNettoNaGranicy]   DECIMAL (18, 3) NULL,
    [Procedura]            CHAR (2)        NULL,
    [ProceduraPoprz]       CHAR (2)        NULL,
    [ProceduraSzczegoly]   CHAR (3)        NULL,
    [IloscUjm]             DECIMAL (19, 3) NULL,
    [OplTranspKod]         CHAR (1)        NULL,
    [KodTypOplatTransp]    CHAR (1)        NULL,
    [IdDokZWU]             DECIMAL (19)    NULL,
    [WartoscStatystyczna]  DECIMAL (17, 2) NULL,
    [Waluta]               CHAR (3)        NULL,
    [SumaOplat]            DECIMAL (17, 2) NULL,
    CONSTRAINT [PK_ZWU_Towar] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_ZC],
    CONSTRAINT [FK_ZWU_Towar_IdDokZWU_ZWU_Dokument_Id] FOREIGN KEY ([IdDokZWU]) REFERENCES [zc].[ZWU_Dokument] ([Id])
);

