CREATE TABLE [aies].[ecs_spp_goods_item] (
    [id]                            NUMERIC (19)    NOT NULL,
    [gi_cn_code]                    VARCHAR (8)     NULL,
    [gi_cn_code_spp]                VARCHAR (8)     NULL,
    [gi_commodity_code_br]          VARCHAR (22)    NULL,
    [gi_country_of_destination]     VARCHAR (2)     NULL,
    [gi_country_of_destination_spp] VARCHAR (2)     NULL,
    [gi_country_of_export]          VARCHAR (2)     NULL,
    [gi_country_of_export_spp]      VARCHAR (2)     NULL,
    [gi_country_of_origin]          VARCHAR (2)     NULL,
    [gi_country_of_origin_spp]      VARCHAR (2)     NULL,
    [gi_crn]                        VARCHAR (70)    NULL,
    [gi_crn_spp]                    VARCHAR (70)    NULL,
    [gi_desc]                       VARCHAR (280)   NULL,
    [gi_desc_br]                    VARCHAR (280)   NULL,
    [gi_gross_mass]                 NUMERIC (18, 3) NULL,
    [gi_gross_mass_br]              NUMERIC (18, 3) NULL,
    [gi_gross_mass_spp]             NUMERIC (18, 3) NULL,
    [gi_item_no]                    INT             NULL,
    [gi_net_mass]                   NUMERIC (18, 3) NULL,
    [gi_net_mass_spp]               NUMERIC (18, 3) NULL,
    [gi_proc_detail]                VARCHAR (3)     NULL,
    [gi_proc_detail_spp]            VARCHAR (3)     NULL,
    [gi_proc_previous]              VARCHAR (2)     NULL,
    [gi_proc_previous_spp]          VARCHAR (2)     NULL,
    [gi_proc_requested]             VARCHAR (2)     NULL,
    [gi_proc_requested_spp]         VARCHAR (2)     NULL,
    [gi_quantity_suppl_unit]        NUMERIC (18, 3) NULL,
    [gi_quantity_suppl_unit_spp]    NUMERIC (18, 3) NULL,
    [gi_taric_code]                 VARCHAR (2)     NULL,
    [gi_taric_code_spp]             VARCHAR (2)     NULL,
    [gi_taxes_amount]               NUMERIC (17, 2) NULL,
    [gi_taxes_amount_spp]           NUMERIC (17, 2) NULL,
    [gi_transport_charges_mp]       VARCHAR (1)     NULL,
    [gi_un_dangerous_goods]         VARCHAR (4)     NULL,
    [gi_un_dangerous_goods_spp]     VARCHAR (4)     NULL,
    [vog_statistical_currency]      VARCHAR (3)     NULL,
    [vog_statistical_value]         NUMERIC (17, 2) NULL,
    [vog_statistical_value_spp]     NUMERIC (17, 2) NULL,
    [declcoexpsuppl_decl_id]        NUMERIC (19)    NULL,
    [gi_transport_charges_mp_spp]   VARCHAR (1)     NULL,
    CONSTRAINT [ecs_spp_go_20153432131] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AIES]
);

