CREATE TABLE [aies].[ecs_spp_declcoexpsuppl] (
    [spp_co_of_exit]                VARCHAR (8)     NULL,
    [spp_co_of_exit_spp]            VARCHAR (8)     NULL,
    [spp_co_of_export]              VARCHAR (8)     NULL,
    [spp_co_of_export_spp]          VARCHAR (8)     NULL,
    [spp_co_of_suppl]               VARCHAR (255)   NULL,
    [spp_co_of_suppl_spp]           VARCHAR (255)   NULL,
    [spp_containers]                TINYINT         NULL,
    [spp_containers_spp]            TINYINT         NULL,
    [spp_country_of_dest]           VARCHAR (2)     NULL,
    [spp_country_of_dest_spp]       VARCHAR (2)     NULL,
    [spp_country_of_export]         VARCHAR (2)     NULL,
    [spp_country_of_export_spp]     VARCHAR (2)     NULL,
    [spp_crn]                       VARCHAR (70)    NULL,
    [spp_crn_spp]                   VARCHAR (70)    NULL,
    [spp_decl_type_1a]              VARCHAR (2)     NULL,
    [spp_decl_type_1b]              VARCHAR (1)     NULL,
    [dt_code]                       VARCHAR (3)     NULL,
    [dt_code_spp]                   VARCHAR (3)     NULL,
    [dt_place]                      VARCHAR (35)    NULL,
    [dt_place_code]                 VARCHAR (1)     NULL,
    [dt_place_code_spp]             VARCHAR (1)     NULL,
    [spp_digital_signature]         TINYINT         NULL,
    [spp_gross_mass]                NUMERIC (18, 3) NULL,
    [spp_gross_mass_spp]            NUMERIC (18, 3) NULL,
    [it_identity]                   VARCHAR (31)    NULL,
    [it_identity_spp]               VARCHAR (31)    NULL,
    [it_mode]                       VARCHAR (2)     NULL,
    [it_mode_spp]                   VARCHAR (2)     NULL,
    [lof_co]                        VARCHAR (8)     NULL,
    [lof_co_spp]                    VARCHAR (8)     NULL,
    [lof_location_code]             VARCHAR (17)    NULL,
    [lof_location_code_spp]         VARCHAR (17)    NULL,
    [lof_location_desc]             VARCHAR (35)    NULL,
    [spp_no_of_items]               INT             NULL,
    [spp_no_of_items_spp]           INT             NULL,
    [spp_no_of_packages]            INT             NULL,
    [spp_no_of_packages_spp]        INT             NULL,
    [pad_capacity]                  VARCHAR (35)    NULL,
    [pad_date]                      DATETIME        NULL,
    [pad_name]                      VARCHAR (35)    NULL,
    [pad_phone]                     VARCHAR (15)    NULL,
    [pad_place]                     VARCHAR (35)    NULL,
    [pos_location_code]             VARCHAR (17)    NULL,
    [pos_location_code_spp]         VARCHAR (17)    NULL,
    [pos_location_desc]             VARCHAR (35)    NULL,
    [si_quantity]                   INT             NULL,
    [si_quantity_spp]               INT             NULL,
    [spp_specific_circumstance]     VARCHAR (1)     NULL,
    [spp_specific_circumstance_spp] VARCHAR (1)     NULL,
    [exp_status]                    CHAR (1)        NULL,
    [spp_storing]                   TINYINT         NULL,
    [spp_storing_spp]               TINYINT         NULL,
    [exp_taxes_amount]              NUMERIC (17, 2) NULL,
    [spp_taxes_amount_spp]          NUMERIC (17, 2) NULL,
    [td_amount]                     NUMERIC (17, 2) NULL,
    [td_amount_spp]                 NUMERIC (17, 2) NULL,
    [td_currency]                   VARCHAR (3)     NULL,
    [td_currency_spp]               VARCHAR (3)     NULL,
    [td_exchange_rate]              NUMERIC (11, 5) NULL,
    [td_exchange_rate_spp]          NUMERIC (11, 5) NULL,
    [td_nature_of_transation]       VARCHAR (2)     NULL,
    [td_nature_of_transation_spp]   VARCHAR (2)     NULL,
    [tab_country]                   VARCHAR (2)     NULL,
    [tab_country_spp]               VARCHAR (2)     NULL,
    [tab_identity]                  VARCHAR (31)    NULL,
    [tab_identity_spp]              VARCHAR (31)    NULL,
    [tab_mode]                      VARCHAR (2)     NULL,
    [tab_mode_spp]                  VARCHAR (2)     NULL,
    [spp_transport_charges_mp]      VARCHAR (1)     NULL,
    [spp_transport_charges_mp_spp]  VARCHAR (1)     NULL,
    [spp_un_dangerous_goods]        VARCHAR (4)     NULL,
    [spp_un_dangerous_goods_spp]    VARCHAR (4)     NULL,
    [w_country]                     VARCHAR (2)     NULL,
    [w_country_spp]                 VARCHAR (2)     NULL,
    [w_location_code]               VARCHAR (14)    NULL,
    [w_location_code_spp]           VARCHAR (14)    NULL,
    [w_type]                        VARCHAR (1)     NULL,
    [w_type_spp]                    VARCHAR (1)     NULL,
    [decl_id]                       NUMERIC (19)    NOT NULL,
    [spp_link_date]                 DATETIME        NULL,
    [spp_co_of_fold]                VARCHAR (8)     NULL,
    CONSTRAINT [ecs_spp_de_18873427571] PRIMARY KEY CLUSTERED ([decl_id] ASC) ON [FG_AIES]
);

