CREATE TABLE [aies].[ICS_ENS_SUBS_ENTR] (
    [ID]        NUMERIC (19)  NOT NULL,
    [CITY]      VARCHAR (35)  NULL,
    [COUNTRY]   VARCHAR (2)   NULL,
    [POST_CODE] VARCHAR (9)   NULL,
    [STREET]    VARCHAR (35)  NULL,
    [CODE]      VARCHAR (8)   NULL,
    [NAME]      VARCHAR (255) NULL,
    [ENS_ID]    NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_SU_8633391091] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

