CREATE TABLE [aies].[ICS_ENS_CUST] (
    [ID]        NUMERIC (19)  NOT NULL,
    [EMAIL]     VARCHAR (255) NULL,
    [NAME]      VARCHAR (35)  NULL,
    [TIN]       VARCHAR (17)  NULL,
    [CITY]      VARCHAR (50)  NULL,
    [COUNTRY]   VARCHAR (2)   NULL,
    [POST_CODE] VARCHAR (9)   NULL,
    [STREET]    VARCHAR (35)  NULL,
    [CUST_TYPE] VARCHAR (255) NULL,
    [ENS_ID]    NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_CU_5113378551] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

