CREATE TABLE [aies].[ICS_ZCP_DV1_INCREM_DEDUCTION] (
    [ID]               NUMERIC (19)    NOT NULL,
    [ZCP_ID]           NUMERIC (19)    NULL,
    [ZCP_ITEM_ID]      NUMERIC (19)    NULL,
    [INCREM_DEDUCTION] VARCHAR (3)     NULL,
    [AMOUNT]           NUMERIC (16, 2) NULL,
    CONSTRAINT [pk_ICS_ZCP_DV1_INCREM_DEDUCTION] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

