CREATE TABLE [aies].[ICS_ZCP_LOCATION] (
    [ID]             NUMERIC (19) NOT NULL,
    [ZCP_ID]         NUMERIC (19) NULL,
    [ZCP_ADDRESS_ID] NUMERIC (19) NULL,
    [CODE]           VARCHAR (35) NULL,
    [COUNTRY]        VARCHAR (2)  NULL,
    [QUALIFIER]      VARCHAR (1)  NOT NULL,
    [LOCATION_CO]    VARCHAR (8)  NULL,
    [DESCRIPTION]    VARCHAR (70) NULL,
    [TYPE]           VARCHAR (1)  NULL,
    CONSTRAINT [pk_ICS_ZCP_LOCATION] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

