CREATE TABLE [aies].[ICS_ZCP_DV1_VALUATION_RATIOS] (
    [ID]                           NUMERIC (19) NOT NULL,
    [ZCP_ID]                       NUMERIC (19) NULL,
    [ZCP_ITEM_ID]                  NUMERIC (19) NULL,
    [USE_RESTRICTIONS]             VARCHAR (1)  NULL,
    [BUYER_SELLER_CONNECT]         VARCHAR (1)  NULL,
    [SALE_PRICE_DEPEND]            VARCHAR (1)  NULL,
    [SALE_IS_SUBJECT_TO_AGREEMENT] VARCHAR (1)  NULL,
    CONSTRAINT [pk_ICS_ZCP_DV1_VALUATION_RATIOS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

