CREATE TABLE [aies].[ICS_DSK_OPERACJA] (
    [ID]         NUMERIC (19)   NOT NULL,
    [ICS_DSK_ID] NUMERIC (19)   NOT NULL,
    [ADNOTACJA]  VARCHAR (1024) NULL,
    [DATA]       DATETIME       NULL,
    [NAZWA]      VARCHAR (4)    NULL,
    [UWAGI]      VARCHAR (1024) NULL,
    [WYKONAL]    VARCHAR (40)   NULL,
    CONSTRAINT [pk_ICS_DSK_OPERACJA] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

