CREATE TABLE [aies].[ICS_DSK_TOWAR_DOKUMENT_POPRZ] (
    [ID]               NUMERIC (19) NOT NULL,
    [ICS_DSK_TOWAR_ID] NUMERIC (19) NULL,
    [KATEGORIA]        CHAR (1)     NULL,
    [KOD]              CHAR (3)     NULL,
    [NR_POZYCJI]       NUMERIC (5)  NULL,
    [NUMER]            VARCHAR (35) NULL,
    CONSTRAINT [pk_ICS_DSK_TOWAR_DOKUMENT_POPRZ] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

