CREATE TABLE [aies].[ICS_CHANG] (
    [ID]      NUMERIC (19)  NOT NULL,
    [AFTER]   VARCHAR (255) NULL,
    [BEFORE]  VARCHAR (255) NULL,
    [ITEM]    VARCHAR (255) NULL,
    [OPER_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_CHANG_3513372851] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

