CREATE TABLE [aies].[ICS_DSK_TOWAR_UPLYNIECIE_TERM] (
    [ID]               NUMERIC (19)  NOT NULL,
    [ICS_DSK_TOWAR_ID] NUMERIC (19)  NULL,
    [NR_POZYCJI]       NUMERIC (5)   NULL,
    [PRZYCZYNA]        VARCHAR (256) NULL,
    CONSTRAINT [pk_ICS_DSK_TOWAR_UPLYNIECIE_TERM] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

