CREATE TABLE [aies].[ICS_ENS_ITI] (
    [ID]      NUMERIC (19) NOT NULL,
    [COUNTRY] VARCHAR (2)  NULL,
    [ENS_ID]  NUMERIC (19) NULL,
    CONSTRAINT [ICS_ENS_IT_7353386531] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

