CREATE TABLE [aies].[ICS_GAN_CUST] (
    [ID]        NUMERIC (19)  NOT NULL,
    [EMAIL]     VARCHAR (255) NULL,
    [NAME]      VARCHAR (35)  NULL,
    [TIN]       VARCHAR (17)  NULL,
    [CITY]      VARCHAR (35)  NULL,
    [COUNTRY]   VARCHAR (2)   NULL,
    [POST_CODE] VARCHAR (9)   NULL,
    [STREET]    VARCHAR (35)  NULL,
    [CUST_TYPE] VARCHAR (4)   NULL,
    [GAN_ID]    NUMERIC (19)  NULL,
    CONSTRAINT [ICS_GAN_CU_9273393371] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

