CREATE TABLE [aies].[ICS_ZCP_INEFFECTIVE_GUARANT] (
    [ID]     NUMERIC (19)  NOT NULL,
    [ZCP_ID] NUMERIC (19)  NULL,
    [POS_NO] NUMERIC (5)   NULL,
    [REASON] VARCHAR (255) NULL,
    CONSTRAINT [pk_ICS_ZCP_INEFFECTIVE_GUARANT] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

