CREATE TABLE [aies].[ICS_ZCP_DELIVERY_REQS] (
    [ID]               NUMERIC (19)  NOT NULL,
    [ZCP_ID]           NUMERIC (19)  NULL,
    [CODE]             VARCHAR (3)   NULL,
    [DESTINATION_CODE] VARCHAR (255) NULL,
    [DESTINATION]      VARCHAR (255) NULL,
    CONSTRAINT [pk_ICS_ZCP_DELIVERY_REQS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

