CREATE TABLE [aies].[ICS_DSK_ZAMK_CELNE] (
    [ID]         NUMERIC (19) NOT NULL,
    [ICS_DSK_ID] NUMERIC (19) NULL,
    [ILOSC]      NUMERIC (4)  NULL,
    [RODZAJ]     VARCHAR (35) NULL,
    CONSTRAINT [pk_ICS_DSK_ZAMK_CELNE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

