CREATE TABLE [aies].[ICS_ZCP_ITEM_OSOZ2_GUARANTEE] (
    [ID]             NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]    NUMERIC (19)    NULL,
    [AMOUNT]         NUMERIC (16, 2) NULL,
    [OPERATION_NO]   VARCHAR (75)    NULL,
    [USE_DATE]       DATETIME        NULL,
    [RELIEF_BALANCE] NUMERIC (16, 2) NULL,
    [RELIEF_DATE]    DATETIME        NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_OSOZ2_GUARANTEE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

