CREATE TABLE [aies].[ICS_ZCP_WARNINGS] (
    [ID]        NUMERIC (19)  NOT NULL,
    [ZCP_ID]    NUMERIC (19)  NULL,
    [DIRECTIVE] VARCHAR (255) NULL,
    [TEXT]      VARCHAR (255) NULL,
    [TEXTEN]    VARCHAR (255) NULL,
    [TOTRADER]  BIT           NOT NULL,
    CONSTRAINT [pk_ICS_ZCP_WARNINGS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

