CREATE TABLE [aies].[ICS_ENS_ITEM_TRANS] (
    [ID]          NUMERIC (19)  NOT NULL,
    [COMM_BR]     VARCHAR (140) NULL,
    [NATION]      VARCHAR (2)   NULL,
    [NATION_BR]   VARCHAR (2)   NULL,
    [SINGS]       VARCHAR (31)  NULL,
    [STATE_BR]    VARCHAR (4)   NULL,
    [TAB_TYPE]    VARCHAR (2)   NULL,
    [ENS_ITEM_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_IT_7033385391] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

