CREATE TABLE [aies].[ICS_DSK_TRANSPORT_NA_GRANICY] (
    [ID]                           NUMERIC (19) NOT NULL,
    [ICS_DSK_ID]                   NUMERIC (19) NOT NULL,
    [PANSTWO_AKTYWNEGO_SR_TRANSP]  CHAR (2)     NULL,
    [RODZAJ_TRANSPORTU_NA_GRANICY] VARCHAR (4)  NULL,
    [ZNAKI_SRODKA_TRANSPORTU]      VARCHAR (35) NULL,
    CONSTRAINT [pk_ICS_DSK_TRANSPORT_NA_GRANICY] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

