CREATE TABLE [aies].[ICS_CANCEL_BALANCE_REQ] (
    [ID]                 NUMERIC (19)  NOT NULL,
    [REQUEST_ID]         VARCHAR (255) NULL,
    [STATUS]             VARCHAR (255) NULL,
    [BALANCE_REQUEST_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_CANCEL_3193371711] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

