CREATE TABLE [aies].[ICS_ENS_ITEM_ADD_INFO] (
    [ID]          NUMERIC (19) NOT NULL,
    [CODE]        VARCHAR (5)  NULL,
    [ENS_ITEM_ID] NUMERIC (19) NULL,
    CONSTRAINT [ICS_ENS_IT_5753380831] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

