CREATE TABLE [aies].[ICS_DSK_TOWAR_KONTENER] (
    [ID]               NUMERIC (19) NOT NULL,
    [ICS_DSK_TOWAR_ID] NUMERIC (19) NULL,
    [NUMER_KONTENERA]  VARCHAR (17) NULL,
    CONSTRAINT [pk_ICS_DSK_TOWAR_KONTENER] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

