CREATE TABLE [aies].[ICS_ENS_ITEMS] (
    [ID]                  NUMERIC (19)  NOT NULL,
    [BALANCE_GROSS_MASS]  FLOAT (53)    NULL,
    [BALANCE_PACKAGES]    INT           NULL,
    [BALN]                TINYINT       NULL,
    [CHARG_TYPE]          VARCHAR (1)   NULL,
    [CHARG_TYPE_BR]       VARCHAR (1)   NULL,
    [CHARG_TYPE_BRC]      VARCHAR (140) NULL,
    [CODE]                VARCHAR (8)   NULL,
    [CODE_BR]             VARCHAR (8)   NULL,
    [CRN]                 VARCHAR (70)  NULL,
    [CRN_BR]              VARCHAR (70)  NULL,
    [DANG_CODE]           VARCHAR (4)   NULL,
    [DANG_CODE_BR]        VARCHAR (4)   NULL,
    [DANG_CODE_BRC]       VARCHAR (140) NULL,
    [ITEM_DESC]           VARCHAR (280) NULL,
    [ITEM_DESC_BR]        VARCHAR (280) NULL,
    [GROSS_MASS]          FLOAT (53)    NULL,
    [GROSS_MASS_BR]       FLOAT (53)    NULL,
    [NUMB]                INT           NULL,
    [PLACE_OF_LOAD]       VARCHAR (35)  NULL,
    [PLACE_OF_LOAD_BR]    VARCHAR (35)  NULL,
    [PLACE_OF_LOAD_BRC]   VARCHAR (140) NULL,
    [PLACE_OF_UNLOAD]     VARCHAR (35)  NULL,
    [PLACE_OF_UNLOAD_BR]  VARCHAR (35)  NULL,
    [PLACE_OF_UNLOAD_BRC] VARCHAR (140) NULL,
    [STATE_BR]            VARCHAR (4)   NULL,
    [STATE_BRC]           VARCHAR (140) NULL,
    [STATUS]              VARCHAR (4)   NULL,
    [ENS_ID]              NUMERIC (19)  NULL,
    [FACT_ENTRY]          VARCHAR (8)   NULL,
    [FAKE]                TINYINT       NULL,
    [INTRO]               INT           NULL,
    [REF_NO]              VARCHAR (35)  NULL,
    [REF_COMPLETED]       TINYINT       NULL,
    CONSTRAINT [ICS_ENS_IT_5433379691] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

