CREATE TABLE [aies].[ICS_ZCP] (
    [ID]                            NUMERIC (19)    NOT NULL,
    [LEGAL_ANNOTATIONS]             VARCHAR (2000)  NULL,
    [CALC_DATE]                     DATETIME        NULL,
    [REJECT_DATE]                   DATETIME        NULL,
    [REGI_DATE]                     DATETIME        NULL,
    [CANCEL_DATE]                   DATETIME        NULL,
    [PREV_DOC_NR]                   VARCHAR (25)    NULL,
    [NUMB_FORMS]                    NUMERIC (5)     NULL,
    [TOTAL_ITEM_VALUE]              NUMERIC (16, 2) NULL,
    [ADDITIONAL_DECL_TYPE]          VARCHAR (1)     NULL,
    [EXPENDERS_EMAIL]               VARCHAR (35)    NULL,
    [CONTAINERS]                    BIT             DEFAULT ((0)) NOT NULL,
    [COUNTRY_OF_DESTINATION]        VARCHAR (2)     NULL,
    [COUNTRY_OF_DESTINATION_REGION] VARCHAR (9)     NULL,
    [COUNTRY_OF_EXPORT]             VARCHAR (2)     NULL,
    [NUMBER_OF_PACKAGES]            NUMERIC (8)     NULL,
    [NO_OF_ITEMS]                   NUMERIC (5)     NULL,
    [GROSS_MASS]                    NUMERIC (16, 6) NULL,
    [NO_OF_PERMISSION]              VARCHAR (35)    NULL,
    [ZCP_SYSTEM_NUMBER]             VARCHAR (35)    NULL,
    [DEFERRED_PAYMENT]              VARCHAR (35)    NULL,
    [ELECTR_SIGNATURE]              BIT             DEFAULT ((0)) NOT NULL,
    [ZCP_STATE]                     VARCHAR (4)     NULL,
    [KIND_OF_DECLARATION]           VARCHAR (3)     NULL,
    [PRESENTATION_GOODS_CO]         VARCHAR (8)     NULL,
    [DECLARATION_CO]                VARCHAR (8)     NULL,
    [XMLNS]                         VARCHAR (255)   NULL,
    [NP_SENDER_ID]                  NUMERIC (19)    NULL,
    [BE_SENDER_ID]                  NUMERIC (19)    NULL,
    [NP_RECEIVER_ID]                NUMERIC (19)    NULL,
    [BE_RECEIVER_ID]                NUMERIC (19)    NULL,
    [NP_BUYER_ID]                   NUMERIC (19)    NULL,
    [BE_BUYER_ID]                   NUMERIC (19)    NULL,
    [NP_REPRESENTATIVE_ID]          NUMERIC (19)    NULL,
    [BE_REPRESENTATIVE_ID]          NUMERIC (19)    NULL,
    [NP_DECLARANT_ID]               NUMERIC (19)    NULL,
    [BE_DECLARANT_ID]               NUMERIC (19)    NULL,
    [NP_ITEM_DECLARANT_ID]          NUMERIC (19)    NULL,
    [BE_ITEM_DECLARANT_ID]          NUMERIC (19)    NULL,
    [NP_SELLER_ID]                  NUMERIC (19)    NULL,
    [BE_SELLER_ID]                  NUMERIC (19)    NULL,
    [PRESENTATION_GOODS]            BIT             DEFAULT ((0)) NOT NULL,
    [ICS_GAN_CUST_DATA_ID]          NUMERIC (19)    NULL,
    CONSTRAINT [pk_ICS_ZCP] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

