CREATE TABLE [aies].[ICS_ZCP_NATURAL_PERSON] (
    [ID]                  NUMERIC (19) NOT NULL,
    [ZCP_ADDRESS_ID]      NUMERIC (19) NULL,
    [ZCP_DOC_SIGNER_ID]   NUMERIC (19) NULL,
    [IDENTIFIER]          VARCHAR (18) NOT NULL,
    [NAME]                VARCHAR (30) NULL,
    [SURNAME]             VARCHAR (40) NULL,
    [ID_NO]               VARCHAR (30) NULL,
    [PESEL]               VARCHAR (11) NULL,
    [REPRESENTATIVE_TYPE] CHAR (3)     NULL,
    CONSTRAINT [pk_ICS_ZCP_NATURAL_PERSON] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

