CREATE TABLE [aies].[ICS_DIRT_INTR] (
    [ID]      NUMERIC (19) NOT NULL,
    [CODE]    VARCHAR (4)  NULL,
    [DIRT_ID] NUMERIC (19) NULL,
    CONSTRAINT [pk_ICS_DIRT_INTR] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

