CREATE TABLE [aies].[ICS_ZCP_ITEM_VEHICLE] (
    [ID]              NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID]     NUMERIC (19) NULL,
    [MAKE]            VARCHAR (35) NULL,
    [BODYWORK_NO]     VARCHAR (35) NULL,
    [ENGINE_NO]       VARCHAR (35) NULL,
    [ENGINE_CAPACITY] NUMERIC (5)  NULL,
    [FUEL_TYPE]       VARCHAR (2)  NULL,
    [PROD_YEAR]       NUMERIC (4)  NULL,
    CONSTRAINT [pk_ICS_ZCP_ITEM_VEHICLE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

