CREATE TABLE [aies].[ICS_DSK_TOWAR_PRZEZN_CELNE] (
    [ID]               NUMERIC (19)    NOT NULL,
    [ICS_DSK_TOWAR_ID] NUMERIC (19)    NULL,
    [NAZWA]            CHAR (4)        NULL,
    [NR_DOKUMENTU]     VARCHAR (40)    NULL,
    [DATA]             DATETIME        NULL,
    [ILOSC]            NUMERIC (16, 6) NULL,
    CONSTRAINT [pk_ICS_DSK_TOWAR_PRZEZN_CELNE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

