CREATE TABLE [aies].[ICS_DSK_WSP_PODPISUJACY_DOK] (
    [ID]                     NUMERIC (19)  NOT NULL,
    [EMAIL]                  VARCHAR (35)  NULL,
    [IMIE]                   VARCHAR (30)  NOT NULL,
    [NAZWISKO]               VARCHAR (40)  NOT NULL,
    [SWIAD_ODP_KARNEJ]       VARCHAR (MAX) NULL,
    [TELEFON]                VARCHAR (15)  NULL,
    [AGENT_CELNY_DATA_WPISU] DATETIME      NULL,
    [AGENT_CELNY_NR_WPISU]   VARCHAR (35)  NULL,
    CONSTRAINT [pk_ICS_DSK_WSP_PODPISUJACY_DOK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
) TEXTIMAGE_ON [FG_AIES];

