CREATE TABLE [aies].[ICS_DSK_TOWAR_OPAKOWANIE] (
    [ID]                      NUMERIC (19) NOT NULL,
    [ICS_DSK_TOWAR_ID]        NUMERIC (19) NULL,
    [LICZBA_OPAKOWAN]         NUMERIC (8)  NULL,
    [NUMERY_I_ZNAKI_OPAKOWAN] VARCHAR (42) NULL,
    [RODZAJ_OPAKOWANIA]       CHAR (3)     NULL,
    CONSTRAINT [pk_ICS_DSK_TOWAR_OPAKOWANIE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIES]
);

