CREATE TABLE [intr2].[INTRASTAT_Towar] (
    [IdDeklWynikowej]             NVARCHAR (30)   NOT NULL,
    [IdPozycji]                   SMALLINT        NOT NULL,
    [Status]                      NCHAR (1)       NULL,
    [Komentarz]                   NVARCHAR (255)  NULL,
    [OpisTowaru]                  NVARCHAR (420)  NULL,
    [KrajPrzeznaczeniaWysylki]    NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaWysylkiPid] INT             NULL,
    [WarunkiDostawy]              NVARCHAR (3)    NULL,
    [WarunkiDostawyPid]           INT             NULL,
    [RodzajTransakcji]            NVARCHAR (4)    NULL,
    [RodzajTransakcjiPid]         INT             NULL,
    [RodzajTransportu]            NVARCHAR (4)    NULL,
    [RodzajTransportuPid]         INT             NULL,
    [KodTowarowy]                 NVARCHAR (8)    NULL,
    [KodTowarowyPid]              BIGINT          NULL,
    [KrajPochodzenia]             NVARCHAR (2)    NULL,
    [KrajPochodzeniaPid]          INT             NULL,
    [MasaNetto]                   NUMERIC (13, 2) NULL,
    [IloscUjm]                    NUMERIC (13, 2) NULL,
    [WartoscFaktury]              NUMERIC (17, 2) NULL,
    [WartoscStatystyczna]         NUMERIC (17, 2) NULL,
    [Flaga]                       NVARCHAR (12)   NULL,
    [IdKontrahenta]               NVARCHAR (17)   NULL,
    CONSTRAINT [INTRASTAT_Towar$PK_INTRASTAT_Towar] PRIMARY KEY CLUSTERED ([IdDeklWynikowej] ASC, [IdPozycji] ASC) ON [FG_INTR2],
    CONSTRAINT [FK_INTRASTAT_Towar_KodTowarowyPid] FOREIGN KEY ([KodTowarowyPid]) REFERENCES [pdr].[s028b] ([s028b_id]),
    CONSTRAINT [FK_INTRASTAT_Towar_KrajPochodzeniaPid] FOREIGN KEY ([KrajPochodzeniaPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_INTRASTAT_Towar_KrajPrzeznaczeniaWysylkiPid] FOREIGN KEY ([KrajPrzeznaczeniaWysylkiPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_INTRASTAT_Towar_RodzajTransakcjiPid] FOREIGN KEY ([RodzajTransakcjiPid]) REFERENCES [pdr].[s004] ([s004_id]),
    CONSTRAINT [FK_INTRASTAT_Towar_RodzajTransportuPid] FOREIGN KEY ([RodzajTransportuPid]) REFERENCES [pdr].[s005] ([s005_id]),
    CONSTRAINT [FK_INTRASTAT_Towar_WarunkiDostawyPid] FOREIGN KEY ([WarunkiDostawyPid]) REFERENCES [pdr].[s002] ([s002_id])
);

