CREATE TABLE [zef2DP].[AKCU_Towary] (
    [IdentyfikatorWpisu]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [IdentyfikatorDokumentu]                 BIGINT          NULL,
    [NazwaGrupyWyrobow]                      NVARCHAR (4000) NULL,
    [OpisTowaru]                             NVARCHAR (4000) NULL,
    [DataPowstaniaObowPodatk]                DATETIME2 (7)   NULL,
    [TerminPlatnosci]                        INT             NULL,
    [DataPlatnosci]                          DATETIME2 (7)   NULL,
    [Marka]                                  NVARCHAR (32)   NULL,
    [Model]                                  NVARCHAR (32)   NULL,
    [RokProdukcji]                           NVARCHAR (255)  NULL,
    [PojazdElektryczny]                      NVARCHAR (5)    NULL,
    [PojemnoscSkokowaSilnika]                DECIMAL (19, 4) NULL,
    [NiestandardowyNumerVIN]                 NVARCHAR (5)    NULL,
    [NumerVIN]                               NVARCHAR (255)  NULL,
    [InformacjeDodatkowe]                    NVARCHAR (4000) NULL,
    [KodCN]                                  NVARCHAR (255)  NULL,
    [PodstawObliczPodatkuIloscWyrobow]       DECIMAL (19, 4) NULL,
    [PodstawObliczPodatkuWartoscWyrobow]     DECIMAL (19, 4) NULL,
    [StawkaPodatkuProcent]                   DECIMAL (19, 4) NULL,
    [StawkaPodatkuKwota]                     DECIMAL (19, 4) NULL,
    [MinimalnaStawkaPodatkuOdWyrTytoniowych] DECIMAL (19, 4) NULL,
    [KwotaPodatku]                           DECIMAL (19, 2) NULL,
    [StawkaSpozaISZTAR]                      NVARCHAR (5)    NULL,
    [RodzajStawkiSpozaISZTAR]                NVARCHAR (16)   NULL,
    [WartoscStawkiSpozaISZTAR]               DECIMAL (19, 4) NULL,
    [DataArch]                               DATETIME2 (7)   NULL,
    [ID_Pismo_xml]                           BIGINT          NULL,
    [MieniePrzesiedlencze]                   NVARCHAR (5)    NULL,
    CONSTRAINT [AKCU_Towary_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorWpisu] ASC) ON [FG_ZEF2DP]
);

