CREATE TABLE [zef2DP].[Podmiot] (
    [IdentyfikatorWpisu]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [NIPLubPESELPodatnika]   NVARCHAR (30)   NULL,
    [CzyObcokrajowiec]       NVARCHAR (5)    NULL,
    [NumerPodatnika]         NVARCHAR (32)   NULL,
    [REGON]                  NVARCHAR (4000) NULL,
    [RodzajPodatnika]        NVARCHAR (16)   NULL,
    [NazwaPodatnika]         NVARCHAR (255)  NULL,
    [NazwiskoPodatnika]      NVARCHAR (255)  NULL,
    [ImiePodatnika]          NVARCHAR (255)  NULL,
    [Kraj]                   NVARCHAR (4000) NULL,
    [Wojewodztwo]            NVARCHAR (4000) NULL,
    [Powiat]                 NVARCHAR (4000) NULL,
    [Gmina]                  NVARCHAR (4000) NULL,
    [Ulica]                  NVARCHAR (4000) NULL,
    [NrDomu]                 NVARCHAR (4000) NULL,
    [NrLokalu]               NVARCHAR (4000) NULL,
    [Miejscowosc]            NVARCHAR (4000) NULL,
    [KodPocztowy]            NVARCHAR (4000) NULL,
    [Poczta]                 NVARCHAR (4000) NULL,
    [UwagiDoDanychPodmiotu]  NVARCHAR (4000) NULL,
    [DataArch]               DATETIME2 (7)   NULL,
    [ID_Pismo_xml]           BIGINT          NULL,
    [DataUrodzeniaPodatnika] DATETIME2 (7)   NULL,
    CONSTRAINT [Podmiot_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorWpisu] ASC) ON [FG_ZEF2DP]
);

