CREATE TABLE [zef2DP].[POG5_ZalacznikA] (
    [IdentyfikatorZalacznika]                      NVARCHAR (255)  NOT NULL,
    [IdentyfikatorDokumentu]                       BIGINT          NOT NULL,
    [OznaczenieZalacznika]                         NVARCHAR (32)   NULL,
    [NumerKolejnyZalacznika]                       INT             NULL,
    [NIPLubPESELPodatnika]                         NVARCHAR (18)   NULL,
    [DeklaracjaZaOkres]                            NVARCHAR (7)    NULL,
    [REGON]                                        NVARCHAR (4000) NULL,
    [NumerZezwolenia]                              NVARCHAR (128)  NULL,
    [DataWydaniaZezwolenia]                        DATETIME2 (7)   NULL,
    [OrganWydajacyZezwolenie]                      NVARCHAR (128)  NULL,
    [Monopol]                                      NVARCHAR (128)  NULL,
    [DataUtworzenia]                               DATETIME2 (7)   NULL,
    [PodstawaOpodatkGryCylindrKasyno]              DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryAutomatKasyno]              DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryKartyKasyno]                DECIMAL (19, 4) NULL,
    [PodstawaOpodatkPozostaleGryKasyno]            NVARCHAR (4000) NULL,
    [RazemPodstawaOpodatkGryKasyno]                DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryKasyno]                       DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryKasyno]                        DECIMAL (19, 2) NULL,
    [PodstawaOpodatkGryBingoIPieniezne]            DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryBingoIPieniezne]              DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryBingoIPieniezne]               DECIMAL (19, 2) NULL,
    [PodstawaOpodatkZakladyDotWspolzawodnLudzi]    NVARCHAR (4000) NULL,
    [StawkaPodatkuZakladyDotWspolzawodnLudzi]      DECIMAL (19, 4) NULL,
    [KwotaPodatkuZakladyDotWspolzawodnLudzi]       DECIMAL (19, 2) NULL,
    [PodstawaOpodatkZakladyDotWspolzawodnZwierzat] NVARCHAR (4000) NULL,
    [StawkaPodatkuZakladyDotWspolzawodnZwierzat]   DECIMAL (19, 4) NULL,
    [KwotaPodatkuZakladyDotWspolzawodnZwierzat]    DECIMAL (19, 2) NULL,
    [PodstawaOpodatkPozostaleRodzZakladowWzajemn]  NVARCHAR (4000) NULL,
    [StawkaPodatkuPozostaleRodzZakladowWzajemn]    DECIMAL (19, 4) NULL,
    [KwotaPodatkuPozostaleRodzZakladowWzajemn]     DECIMAL (19, 2) NULL,
    [PodstawaOpodatkLoteriePieniezne]              DECIMAL (19, 4) NULL,
    [StawkaPodatkuLoteriePieniezne]                DECIMAL (19, 4) NULL,
    [KwotaPodatkuLoteriePieniezne]                 DECIMAL (19, 2) NULL,
    [PodstawaOpodatkGryTelebingo]                  DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryTelebingo]                    DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryTelebingo]                     DECIMAL (19, 2) NULL,
    [PodstawaOpodatkLoterieAudiotekstowe]          DECIMAL (19, 4) NULL,
    [StawkaPodatkuLoterieAudiotekstowe]            DECIMAL (19, 4) NULL,
    [KwotaPodatkuLoterieAudiotekstowe]             DECIMAL (19, 2) NULL,
    [RazemKwotaPodatku]                            DECIMAL (19, 2) NULL,
    [id1]                                          NVARCHAR (150)  NULL,
    CONSTRAINT [POG5_ZalacznikA_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorZalacznika] ASC, [IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DP]
);

