CREATE TABLE [pta].[AD_Zadanie] (
    [Id]                        BIGINT          NOT NULL,
    [Status]                    CHAR (1)        NOT NULL,
    [TypZadania]                VARCHAR (35)    NOT NULL,
    [TerminPlatnosci]           DATE            NULL,
    [OdpowiedzialnaRola]        BIGINT          NOT NULL,
    [OdpowiedzialnyUzytkownik]  DECIMAL (10)    NULL,
    [UrzadCelnyNrRef]           VARCHAR (8)     NULL,
    [Tytul]                     VARCHAR (250)   NOT NULL,
    [IdDokAD]                   BIGINT          NULL,
    [PodmiotIdentyfikacja]      NVARCHAR (16)   NULL,
    [PodmiotNazwa]              NVARCHAR (182)  NULL,
    [PodmiotUlica]              NVARCHAR (65)   NULL,
    [PodmiotNrDomu]             NVARCHAR (22)   NULL,
    [PodmiotKodPocztowy]        NVARCHAR (10)   NULL,
    [PodmiotMiejscowosc]        NVARCHAR (50)   NULL,
    [KodPowoduOdrzuceniaCla]    DECIMAL (1)     NULL,
    [NrRefDokumentu]            VARCHAR (21)    NULL,
    [DecyzjaKontroliDomyslna]   CHAR (1)        NULL,
    [DecyzjaKontroli]           CHAR (1)        NULL,
    [Ilosc]                     DECIMAL (38, 2) NULL,
    [CzyPrawidlowaOperacjaOSOZ] BIT             NULL,
    [DataUtworzenia]            DATETIME        NOT NULL,
    [DataZmian]                 DATETIME        NULL,
    [ZmienionePrzez]            VARCHAR (50)    NULL,
    [WersjaAudytu]              INT             CONSTRAINT [DF__AD_Zadani__Wersj__6D6D25A7] DEFAULT ((0)) NOT NULL,
    [ARC]                       VARCHAR (21)    NULL,
    [LRN]                       NVARCHAR (22)   NULL,
    [NazwaMiejscaKontroli]      NVARCHAR (182)  NULL,
    [CzyZadanieKontroli]        BIT             NULL,
    [DataPrzeladunku]           DATETIME        NULL,
    CONSTRAINT [PK_AD_Zadanie] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_PTA],
    CONSTRAINT [FK_AD_Zadanie_IdDokAD_AD_Dokument_Id] FOREIGN KEY ([IdDokAD]) REFERENCES [pta].[AD_Dokument] ([Id]),
    CONSTRAINT [FK_AD_Zadanie_TypZadania_AD_TypZadania_TypZadania] FOREIGN KEY ([TypZadania]) REFERENCES [pta].[AD_TypZadania] ([TypZadania])
);

