CREATE TABLE [akc].[AKC3_Deklaracja] (
    [IdDok]                            VARCHAR (30)    NOT NULL,
    [IdKomorki]                        VARCHAR (20)    NULL,
    [IdPodmiotu]                       INT             NULL,
    [RodzajDokumentu]                  CHAR (4)        NULL,
    [NumerDokumentu]                   VARCHAR (30)    NULL,
    [IdDokStowarzysz]                  VARCHAR (30)    NULL,
    [NumerDokumentuStowarzysz]         VARCHAR (30)    NULL,
    [ZnacznikKorekty]                  SMALLINT        NULL,
    [Status]                           CHAR (1)        NULL,
    [RokZlozeniaDok]                   SMALLINT        NULL,
    [DataRejestrDokWSyst]              DATETIME        NULL,
    [DeklaracjaZaOkres]                DATE            NULL,
    [MiejsceZlozeniaDok]               VARCHAR (20)    NULL,
    [DataZlozeniaDok]                  DATE            NULL,
    [DataWplywuDok]                    DATE            NULL,
    [TerminPlatnosci]                  DATE            NULL,
    [RazemPodatekAkcyzowy]             DECIMAL (19, 2) NULL,
    [WartoscZnakowAkcyzy]              DECIMAL (19, 2) NULL,
    [KwotaWplatDziennych]              DECIMAL (19, 2) NULL,
    [KwotaNadwyzDoRozlicz]             DECIMAL (19, 2) NULL,
    [KwotaNadwyzPoprzedMies]           DECIMAL (19, 2) NULL,
    [DoZaplaty]                        DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozlicz]             DECIMAL (19, 2) NULL,
    [DeklaracjaZerowa]                 CHAR (3)        NOT NULL,
    [DataZlozeniaDeklaracjiPierwotnej] DATE            NULL,
    [CzyOstatniaWersjaDeklaracji]      BIT             NULL,
    CONSTRAINT [PK_AKC3_Deklaracja] PRIMARY KEY CLUSTERED ([IdDok] ASC) ON [FG_AKC],
    CONSTRAINT [FK_AKC3_Deklaracja_IdKomorkiIdPodmiotu_Podmiot_IdKomorkiIdPodmiotu] FOREIGN KEY ([IdKomorki], [IdPodmiotu]) REFERENCES [akc].[Podmiot] ([IdKomorki], [IdPodmiotu])
);

