CREATE TABLE [akc].[POGP_Deklaracja] (
    [IdDok]                            VARCHAR (30)    NOT NULL,
    [IdKomorki]                        VARCHAR (20)    NULL,
    [IdPodmiotu]                       INT             NULL,
    [RodzajDokumentu]                  CHAR (4)        NULL,
    [NumerDokumentu]                   VARCHAR (30)    NULL,
    [IzbaCelnaZlozeniaDok]             VARCHAR (20)    NULL,
    [MiejsceZlozeniaDok]               VARCHAR (20)    NULL,
    [ZnacznikKorekty]                  SMALLINT        NULL,
    [Status]                           CHAR (1)        NULL,
    [DataRejestrDokWSyst]              DATETIME        NULL,
    [OkresSprawozdawczy]               DATE            NULL,
    [DataZlozeniaDok]                  DATE            NULL,
    [DataWplywuDok]                    DATE            NULL,
    [TerminPlatnosci]                  DATE            NULL,
    [CzyKorektaWewnetrzna]             BIT             NULL,
    [CzyKorektaZurzedu]                BIT             NULL,
    [PodstawObliczPodatku]             DECIMAL (19, 3) NULL,
    [StawkaPodatkuProcent]             DECIMAL (19, 2) NULL,
    [KwotaPobranegoPodatku]            DECIMAL (19, 2) NULL,
    [KwotaPotraconegoWynagrodz]        DECIMAL (19, 2) NULL,
    [KwotaDoWplaty]                    DECIMAL (19, 2) NULL,
    [DataZlozeniaDeklaracjiPierwotnej] DATE            NULL,
    [CzyOstatniaWersjaDeklaracji]      BIT             NULL,
    CONSTRAINT [PK_POGP_Deklaracja] PRIMARY KEY CLUSTERED ([IdDok] ASC) ON [FG_AKC],
    CONSTRAINT [FK_POGP_Deklaracja_IdKomorkiIdPodmiotu_Podmiot_IdKomorkiIdPodmiotu] FOREIGN KEY ([IdKomorki], [IdPodmiotu]) REFERENCES [akc].[Podmiot] ([IdKomorki], [IdPodmiotu])
);

