CREATE PROCEDURE [wpb].[TruncateAllStageWPB]
AS
BEGIN
	SET NOCOUNT ON;

	TRUNCATE TABLE wpb.RB27_Dokument;
	TRUNCATE TABLE wpb.RB27_Pozycje;
	TRUNCATE TABLE wpb.RB28_Dokument;
	TRUNCATE TABLE wpb.RB28_Pozycje;
	TRUNCATE TABLE wpb.RB28PR_Dokument;
	TRUNCATE TABLE wpb.RB28PR_Pozycje;
	TRUNCATE TABLE wpb.RB28UE_Dokument;
	TRUNCATE TABLE wpb.RB28UE_Pozycje;
	TRUNCATE TABLE wpb.RB70_Dokument;
	TRUNCATE TABLE wpb.RB70_Pozycje;

END