CREATE TABLE [aimp2].[DSK_Towar] (
    [IdPozycji]                          NUMERIC (19)    NOT NULL,
    [IdDok]                              NUMERIC (19)    NOT NULL,
    [IdPozycjiPTW]                       NUMERIC (19)    NULL,
    [IloscTowaru]                        NUMERIC (16, 6) NULL,
    [JednostkaMiary]                     NCHAR (3)       NULL,
    [JednostkaMiaryPid]                  INT             NULL,
    [KodCUS]                             NVARCHAR (8)    NULL,
    [KodTowarowy]                        NVARCHAR (18)   NULL,
    [MasaBrutto]                         NUMERIC (16, 6) NULL,
    [MasaNetto]                          NUMERIC (16, 6) NULL,
    [NumerPozycji]                       NUMERIC (5)     NULL,
    [NumerReferencyjnyPrzesylki]         NVARCHAR (35)   NULL,
    [IdOdbiorcyOsobaFizyczna]            NUMERIC (19)    NULL,
    [OpisNieprawidlowosci]               NVARCHAR (1024) NULL,
    [OpisTowaru]                         NVARCHAR (1000) NULL,
    [IdOdbiorcyPodmiotGospodarczy]       NUMERIC (19)    NULL,
    [Przeterminowanie]                   BIT             NOT NULL,
    [OdniesienieDoZT]                    BIT             NOT NULL,
    [StatusPozycjiDSK]                   NVARCHAR (4)    NULL,
    [AktualnyTerminCzasowegoSkladowania] DATETIME2 (3)   NULL,
    [UwagiDoTowaru]                      NVARCHAR (260)  NULL,
    [WynikKontroli]                      NVARCHAR (60)   NULL,
    [Zabezpieczono]                      TINYINT         NULL,
    CONSTRAINT [DSK_Towar_PK] PRIMARY KEY CLUSTERED ([IdPozycji] ASC) ON [FG_AIMP2],
    CONSTRAINT [DSK_Towar$FK_DSK_OsobaFizyczna] FOREIGN KEY ([IdOdbiorcyOsobaFizyczna]) REFERENCES [aimp2].[DSK_OsobaFizyczna] ([IdOsobyFizycznej]),
    CONSTRAINT [DSK_Towar$FK_DSK_PodmiotGospodarczy] FOREIGN KEY ([IdOdbiorcyPodmiotGospodarczy]) REFERENCES [aimp2].[DSK_PodmiotGospodarczy] ([IdPodmiotuGospodarczego])
);

