CREATE TABLE [emcs2].[AIS_VERIFICATIONS] (
    [ID]            NUMERIC (38)  NOT NULL,
    [CREATE_DATE]   DATETIME2 (6) NOT NULL,
    [MODIFIED_DATE] DATETIME2 (6) NOT NULL,
    [LRN]           NVARCHAR (22) NOT NULL,
    [ZCP_MRN]       NVARCHAR (40) NOT NULL,
    [QUERY_MSG_ID]  NUMERIC (38)  NOT NULL,
    CONSTRAINT [PK_AIS_VERIFICATIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

