CREATE TABLE [emcs2].[AIS_VERIFICATIONS_MVMT] (
    [ID]                   NUMERIC (38)  NOT NULL,
    [CREATE_DATE]          DATETIME2 (6) NOT NULL,
    [MODIFIED_DATE]        DATETIME2 (6) NOT NULL,
    [AIS_VERIFICATION_ID]  NUMERIC (38)  NOT NULL,
    [VERIFICATION_MSG_ID]  NUMERIC (38)  NOT NULL,
    [VERIFICATION_RESULT]  CHAR (1)      NOT NULL,
    [VERIFICATION_ARC]     VARCHAR (21)  NOT NULL,
    [VERIFICATION_MVMT_ID] NUMERIC (38)  NOT NULL,
    [CORRECTION_MSG_ID]    NUMERIC (38)  NULL,
    [CORRECTION_ARC]       VARCHAR (21)  NULL,
    [CORRECTION_MVMT_ID]   NUMERIC (38)  NULL,
    CONSTRAINT [PK_AIS_VERIFICATIONS_MVMT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

