CREATE TABLE [emcs2].[AR_KONTROLA_PODSUMOWANIE] (
    [ID]                          NUMERIC (38)  NOT NULL,
    [OBSLUGA_WSKAZAN_KONTROLI_ID] NUMERIC (38)  NOT NULL,
    [NR_POZYCJI]                  NUMERIC (38)  NOT NULL,
    [ZAKRES_PRZEBIEG_KONTROLI_SO] VARCHAR (200) NULL,
    [WYNIK_KONTROLI_SO]           VARCHAR (36)  NULL,
    CONSTRAINT [PK_AR_KONTROLA_PODSUMOWANIE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

