CREATE TABLE [emcs2].[ECS_DECLARATIONS] (
    [ID]     NUMERIC (38) NOT NULL,
    [MRN]    VARCHAR (18) NOT NULL,
    [STATUS] VARCHAR (8)  NOT NULL,
    CONSTRAINT [PK_ECS_DECLARATIONS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UK_ECS_DECLARATIONS_1] UNIQUE NONCLUSTERED ([MRN] ASC)
);

