CREATE TABLE [emcs2].[EMCS_ACO_MOVEMENTS] (
    [ID]              NUMERIC (38) NOT NULL,
    [ACO_ID]          NUMERIC (38) NOT NULL,
    [ARC]             VARCHAR (21) NOT NULL,
    [SEQUENCE_NUMBER] NUMERIC (2)  NOT NULL,
    [MVMT_ID]         NUMERIC (38) NULL,
    CONSTRAINT [PK_ACO_MOVEMENTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

