CREATE TABLE [emcs2].[EMCS_PROCESS_STATE_INST] (
    [ID]             NUMERIC (38)   NOT NULL,
    [PRIN_ID]        NUMERIC (38)   NOT NULL,
    [PRST_ID]        NUMERIC (38)   NOT NULL,
    [PRTR_ID]        NUMERIC (38)   NULL,
    [ATL]            VARCHAR (1000) NULL,
    [ROLE_ID]        NUMERIC (10)   NOT NULL,
    [OFFICE_REFNUM]  VARCHAR (8)    NULL,
    [CREATE_DATE]    DATETIME2 (6)  NOT NULL,
    [EXECUTION_DATE] DATETIME2 (6)  NULL,
    [EXECUTED_BY]    VARCHAR (50)   NULL,
    [VERSION]        NUMERIC (38)   NOT NULL,
    CONSTRAINT [PK_PROCESS_STATE_INST] PRIMARY KEY CLUSTERED ([ID] ASC)
);

