CREATE TABLE [emcs2].[EMCS_USER_TASKS_JN] (
    [JN_OPERATION]                  CHAR (3)        NOT NULL,
    [JN_ORACLE_USER]                VARCHAR (30)    NOT NULL,
    [JN_DATETIME]                   DATETIME2 (0)   NOT NULL,
    [JN_NOTES]                      VARCHAR (240)   NULL,
    [JN_APPLN]                      VARCHAR (35)    NULL,
    [JN_SESSION]                    NUMERIC (38)    NULL,
    [ID]                            NUMERIC (38)    NOT NULL,
    [STATUS]                        VARCHAR (1)     NULL,
    [TASK_TYPE]                     VARCHAR (40)    NOT NULL,
    [DUE_DATE]                      DATETIME2 (0)   NULL,
    [RESPONSIBLE_ROLE]              NUMERIC (38)    NULL,
    [RESPONSIBLE_USER]              NUMERIC (10)    NULL,
    [CUSTOM_OFFICE_REFNUM]          VARCHAR (8)     NULL,
    [TITLE]                         VARCHAR (250)   NULL,
    [DESCRIPTION]                   NVARCHAR (4000) NULL,
    [MVMT_ID]                       NUMERIC (38)    NULL,
    [MESSAGES_ID]                   NUMERIC (38)    NULL,
    [TRADER_IDENTIFICATION]         NVARCHAR (48)   NULL,
    [TRADER_NAME]                   NVARCHAR (546)  NULL,
    [TRADER_STREET_NAME]            NVARCHAR (195)  NULL,
    [TRADER_STREET_NUMBER]          NVARCHAR (66)   NULL,
    [TRADER_POSTCODE]               NVARCHAR (30)   NULL,
    [TRADER_CITY]                   NVARCHAR (150)  NULL,
    [USER_DESCRIPTION]              NVARCHAR (4000) NULL,
    [CUSTOMS_REJECTION_REASON_CODE] NUMERIC (1)     NULL,
    [DOCUMENT_REFERENCE_NUMBER]     VARCHAR (21)    NULL,
    [ZISAR_MESSAGE_ID]              NUMERIC (38)    NULL,
    [CONTROL_DEFAULT_DECISION]      CHAR (1)        NULL,
    [CONTROL_DECISION]              CHAR (1)        NULL,
    [REPORT_MESSAGE_ID]             NUMERIC (38)    NULL,
    [AMOUNT]                        NUMERIC (38, 2) NULL,
    [IS_OSOZ_ACTION_SUCCESSFULL]    CHAR (1)        NULL,
    [MESSAGE_WITH_ERROR_ID]         NUMERIC (38)    NULL,
    [CREATE_DATE]                   DATETIME2 (6)   NULL,
    [CHANGE_DATE]                   DATETIME2 (6)   NULL,
    [CHANGE_DESCRIPTION]            NVARCHAR (4000) NULL,
    [CHANGED_BY]                    VARCHAR (50)    NULL,
    [AUDIT_VER]                     NUMERIC (38)    NULL,
    [MVMT_ARC]                      VARCHAR (21)    NULL,
    [MVMT_LRN]                      NVARCHAR (66)   NULL,
    [PLACE_OF_CONTROL_NAME]         NVARCHAR (546)  NULL,
    [CONTROL_REQUESTED]             CHAR (1)        NULL,
    [TRANSHIPMENT_DATE]             DATETIME2 (6)   NULL
);

