CREATE TABLE [emcs2].[EMCS_PROCESS_INSTANCES] (
    [ID]            NUMERIC (38)    NOT NULL,
    [PROC_ID]       NUMERIC (38)    NOT NULL,
    [PAPI_ID]       NUMERIC (38)    NULL,
    [STATUS]        CHAR (1)        NOT NULL,
    [IS_TERMINATED] CHAR (1)        NOT NULL,
    [DESCRIPTION]   NVARCHAR (4000) NULL,
    [CREATE_DATE]   DATETIME2 (6)   NOT NULL,
    [CHANGE_DATE]   DATETIME2 (6)   NULL,
    [VERSION]       NUMERIC (38)    NOT NULL,
    CONSTRAINT [PK_PROCESS_INSTANCES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

