CREATE TABLE [emcs2].[EMCS_ACO_PROCESS_INSTANCES] (
    [ID]      NUMERIC (38) NOT NULL,
    [ACO_ID]  NUMERIC (38) NOT NULL,
    [PRIN_ID] NUMERIC (38) NOT NULL,
    CONSTRAINT [PK_ACO_PROCESS_INSTANCES] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UK_ACO_PROCESS_INSTANCES_1] UNIQUE NONCLUSTERED ([ACO_ID] ASC, [PRIN_ID] ASC)
);

