CREATE TABLE [emcs2].[EMCS_DOWN_DOWNSTREAM_MVMTS] (
    [ID]      NUMERIC (38) NOT NULL,
    [MVMT_ID] NUMERIC (38) NOT NULL,
    [ARC]     VARCHAR (21) NOT NULL,
    CONSTRAINT [PK_DOWN_DOWNSTREAM_MVMTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

