CREATE TABLE [emcs2].[EMCS_TIMERS] (
    [ID]           NUMERIC (38)  NOT NULL,
    [TYPE]         VARCHAR (20)  NOT NULL,
    [START_DATE]   DATETIME2 (6) NOT NULL,
    [RUNNING]      CHAR (1)      NOT NULL,
    [EXPIRED]      CHAR (1)      NOT NULL,
    [LIMIT_DATE]   DATETIME2 (6) NOT NULL,
    [STOP_DATE]    DATETIME2 (6) NULL,
    [MVMT_ID]      NUMERIC (38)  NULL,
    [USER_TASK_ID] NUMERIC (38)  NULL,
    [ACO_ID]       NUMERIC (38)  NULL,
    CONSTRAINT [PK_TIMERS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

