CREATE TABLE [emcs2].[EMCS_ACO_MESSAGE_RELATIONS] (
    [ID]            NUMERIC (38) NOT NULL,
    [ACOM1_ID]      NUMERIC (38) NOT NULL,
    [ACOM2_ID]      NUMERIC (38) NOT NULL,
    [RELATION_TYPE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ACO_MESSAGE_RELATIONS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UK_ACO_MESSAGE_RELATIONS_1] UNIQUE NONCLUSTERED ([ACOM2_ID] ASC, [ACOM1_ID] ASC)
);

