CREATE TABLE [emcs2].[MVMT_TRANSPORT_DETAILS] (
    [ID]                           NUMERIC (38)    NOT NULL,
    [TRANSPORT_UNIT_CODE]          VARCHAR (2)     NULL,
    [IDENTITY_OF_TRANSPORT_UNIT]   NVARCHAR (105)  NULL,
    [IDENTITY_OF_COMMERCIAL_SEAL]  NVARCHAR (105)  NULL,
    [SEAL_INFORMATION]             NVARCHAR (1050) NULL,
    [SEAL_INFORMATION_LANG_CODE]   VARCHAR (2)     NULL,
    [COMPLEMENTARY_INFORMATION]    NVARCHAR (1050) NULL,
    [COMPLEMENTARY_INFO_LANG_CODE] VARCHAR (2)     NULL,
    [MVMT_ID]                      NUMERIC (38)    NOT NULL,
    CONSTRAINT [PK_MVMTTRANSP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

