CREATE TABLE [emcs2].[MVMT_INTERESTED_OFFICES] (
    [ID]              NUMERIC (38) NOT NULL,
    [SEQUENCE_NUMBER] NUMERIC (2)  NOT NULL,
    [OFFICE_REFNUM]   VARCHAR (8)  NOT NULL,
    [MVMT_ID]         NUMERIC (38) NOT NULL,
    CONSTRAINT [PK_MVMT_INTERESTED_OFFICES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

