CREATE TABLE [emcs2].[MVMT_CONSIGNEE_HISTORY] (
    [ID]                          NUMERIC (38)  NOT NULL,
    [MVMT_ID]                     NUMERIC (38)  NOT NULL,
    [ARC]                         VARCHAR (21)  NOT NULL,
    [SEQUENCE_NUMBER]             NUMERIC (2)   NOT NULL,
    [CONSIGNEE_MSG_RECIPIENT]     VARCHAR (13)  NULL,
    [CONSIGNEE_MSG_EMAIL]         VARCHAR (100) NULL,
    [DESTINATION_TYPE_CODE]       VARCHAR (1)   NOT NULL,
    [IS_PLACEOFDELIVERY_DOMESTIC] CHAR (1)      NULL,
    CONSTRAINT [PK_MVMT_CONSIGNEE_HISTORY] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UK_MVMT_CONSIGNEE_HISTORY] UNIQUE NONCLUSTERED ([MVMT_ID] ASC, [SEQUENCE_NUMBER] ASC)
);

