CREATE TABLE [emcs2].[MVMT_PACKAGES] (
    [ID]                          NUMERIC (38)    NOT NULL,
    [KIND_OF_PACKAGES_CODE]       VARCHAR (2)     NOT NULL,
    [NUMBER_OF_PACKAGES]          FLOAT (53)      NULL,
    [IDENTITY_OF_COMMERCIAL_SEAL] VARCHAR (35)    NULL,
    [SEAL_INFORMATION]            NVARCHAR (1050) NULL,
    [SEAL_INFORMATION_LANG_CODE]  VARCHAR (2)     NULL,
    [MVMT_PRODUCT_ID]             NUMERIC (38)    NOT NULL,
    CONSTRAINT [PK_MVMTPCKGS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

