CREATE TABLE [emcs2].[MVMT_WINE_OPERATION_CODES] (
    [ID]                  NUMERIC (38) NOT NULL,
    [WINE_OPERATION_CODE] VARCHAR (2)  NOT NULL,
    [MVMT_PRODUCT_ID]     NUMERIC (38) NOT NULL,
    CONSTRAINT [PK_MVMTWOPCDS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

