CREATE TABLE [emcs2].[MVMT_CERTIFICATES] (
    [ID]                             NUMERIC (38)    NOT NULL,
    [REFERENCE_OF_DOCUMENT]          NVARCHAR (1050) NULL,
    [REFERENCE_OF_DOC_LANG_CODE]     VARCHAR (2)     NULL,
    [DOCUMENT_DESCRIPTION]           NVARCHAR (1050) NULL,
    [DOCUMENT_DESCRIPTION_LANG_CODE] VARCHAR (2)     NULL,
    [MVMT_ID]                        NUMERIC (38)    NOT NULL,
    CONSTRAINT [PK_MVMTCERT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

