CREATE TABLE [emcs2].[MVMT_SAD_DOCUMENTS] (
    [ID]         NUMERIC (38)  NOT NULL,
    [SAD_NUMBER] NVARCHAR (63) NOT NULL,
    [MVMT_ID]    NUMERIC (38)  NOT NULL,
    CONSTRAINT [PK_MVMTSAD] PRIMARY KEY CLUSTERED ([ID] ASC)
);

