CREATE TABLE [emcs2].[REF_SD2_WYROBY] (
    [ID]                   NUMERIC (38)    NOT NULL,
    [REF_SD2_PODMIOTY_NRA] VARCHAR (13)    NOT NULL,
    [KATEGORIA]            NVARCHAR (3)    NULL,
    [KOD]                  NVARCHAR (12)   NULL,
    [ILOSC]                NUMERIC (18, 3) NULL,
    [JEDNOSTKA]            NVARCHAR (21)   NULL,
    [REF_SD2_PODMIOTY_TYP] NVARCHAR (15)   NOT NULL,
    CONSTRAINT [PK_REF_SD2_WYROBY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

