CREATE TABLE [emcs2].[REF_SD2_UBYTKI_TRANS_OPAK] (
    [UBT_ID] NUMERIC (38)  NOT NULL,
    [GRUPA]  NVARCHAR (12) NOT NULL,
    CONSTRAINT [UTO_PK] PRIMARY KEY CLUSTERED ([UBT_ID] ASC, [GRUPA] ASC)
);

