CREATE TABLE [emcs2].[REF_SD2_MIEJSCA_ODBIORU] (
    [ID]                   NUMERIC (38)   NOT NULL,
    [REF_SD2_PODMIOTY_NRA] VARCHAR (13)   NOT NULL,
    [NAZWA]                NVARCHAR (900) NULL,
    [NR_AKCYZOWY]          NVARCHAR (39)  NULL,
    [UC_KONTROLI]          NVARCHAR (24)  NULL,
    [KOD_KRAJU]            NVARCHAR (6)   NOT NULL,
    [ULICA]                NVARCHAR (210) NULL,
    [NR_DOMU]              NVARCHAR (30)  NOT NULL,
    [NR_LOKALU]            NVARCHAR (30)  NULL,
    [MIEJSCOWOSC]          NVARCHAR (180) NULL,
    [KOD_POCZTOWY]         NVARCHAR (30)  NOT NULL,
    [POCZTA]               NVARCHAR (180) NULL,
    [REF_SD2_PODMIOTY_TYP] NVARCHAR (15)  NOT NULL,
    CONSTRAINT [PK_REF_SD2_MIEJSCA_ODBIORU] PRIMARY KEY CLUSTERED ([ID] ASC)
);

