CREATE TABLE [emcs2].[REF_SD2_PRZEDSTAWICIELE] (
    [ID]                   NUMERIC (38)   NOT NULL,
    [REF_SD2_PODMIOTY_NRA] VARCHAR (13)   NOT NULL,
    [IMIE]                 NVARCHAR (180) NULL,
    [NAZWISKO]             NVARCHAR (270) NULL,
    [PESEL]                NVARCHAR (33)  NULL,
    [X509_THUMBPRINT]      NVARCHAR (750) NULL,
    [REF_SD2_PODMIOTY_TYP] NVARCHAR (15)  NOT NULL,
    [IDSISCROF]            VARCHAR (17)   NULL,
    CONSTRAINT [PK_REF_SD2_PRZEDSTAWICIELE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

