CREATE TABLE [emcs2].[REF_SD2_UBYTKI_TRANS_KODY_CN] (
    [UBT_ID] NUMERIC (38)  NOT NULL,
    [KOD_CN] NVARCHAR (24) NOT NULL,
    CONSTRAINT [UTK_PK] PRIMARY KEY CLUSTERED ([UBT_ID] ASC, [KOD_CN] ASC)
);

