CREATE TABLE [aes2].[ZUZ_Towar] (
    [Id]                          NUMERIC (19)    NOT NULL,
    [KodTowarowyNaGranicy]        NVARCHAR (22)   NULL,
    [KodTowarowyNaGranicyPid]     NVARCHAR (22)   NULL,
    [KrajPrzeznaczenia]           NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaPid]        NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaWUzupln]    NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaWUzuplnPid] NVARCHAR (2)    NULL,
    [KrajWysylki]                 NVARCHAR (2)    NULL,
    [KrajWysylkiPid]              NVARCHAR (2)    NULL,
    [KrajWysylkiWUzupln]          NVARCHAR (2)    NULL,
    [KrajWysylkiWUzuplnPid]       NVARCHAR (2)    NULL,
    [KrajPochodzenia]             NVARCHAR (2)    NULL,
    [KrajPochodzeniaPid]          NVARCHAR (2)    NULL,
    [KrajPochodzeniaWUzupln]      NVARCHAR (2)    NULL,
    [KrajPochodzeniaWUzuplnPid]   NVARCHAR (2)    NULL,
    [CRN]                         NVARCHAR (70)   NULL,
    [CRNWUzupln]                  NVARCHAR (70)   NULL,
    [OpisTowaru]                  NVARCHAR (280)  NULL,
    [OpisTowaruNaGranicy]         NVARCHAR (280)  NULL,
    [OpisTowaru2]                 NUMERIC (18, 3) NULL,
    [OpisTowaruNaGranicy2]        NUMERIC (18, 3) NULL,
    [OpisTowaruWUzupln]           NUMERIC (18, 3) NULL,
    [NrPozycji]                   INT             NULL,
    [MasaNetto]                   NUMERIC (18, 3) NULL,
    [MasaNettoWUzupln]            NUMERIC (18, 3) NULL,
    [ProceduraSzczegoly]          NVARCHAR (3)    NULL,
    [ProceduraSzczegolyWUzupln]   NVARCHAR (3)    NULL,
    [ProceduraPoprz]              NVARCHAR (2)    NULL,
    [ProceduraPoprzPid]           NVARCHAR (2)    NULL,
    [ProceduraPoprzWUzupln]       NVARCHAR (2)    NULL,
    [ProceduraPoprzWUzuplnPid]    NVARCHAR (2)    NULL,
    [Procedura]                   NVARCHAR (2)    NULL,
    [ProceduraPid]                NVARCHAR (2)    NULL,
    [ProceduraWUzupln]            NVARCHAR (2)    NULL,
    [ProceduraWUzuplnPid]         NVARCHAR (2)    NULL,
    [IloscUjm]                    NUMERIC (18, 3) NULL,
    [IloscUjmWUzupln]             NUMERIC (18, 3) NULL,
    [KodTARIC]                    NVARCHAR (2)    NULL,
    [KodTARICWUzupln]             NVARCHAR (2)    NULL,
    [SumaOplat]                   NUMERIC (17, 2) NULL,
    [SumaOplatWUzupln]            NUMERIC (17, 2) NULL,
    [OplatyTransportowe]          NVARCHAR (1)    NULL,
    [TowarNiebezpieczny]          NVARCHAR (4)    NULL,
    [TowarNiebezpiecznyNaZWU]     NVARCHAR (4)    NULL,
    [Waluta]                      NVARCHAR (3)    NULL,
    [WartoscStatystyczna]         NUMERIC (17, 2) NULL,
    [WartoscStatystycznaNaZWU]    NUMERIC (17, 2) NULL,
    [IdDokZUZ]                    NUMERIC (19)    NULL,
    [OplatyTransportoweNaZWU]     NVARCHAR (1)    NULL,
    CONSTRAINT [ZUZ_Towar$PK_ZUZ_Towar] PRIMARY KEY CLUSTERED ([Id] ASC)
);

