CREATE TABLE [ais2].[ICS_BALANCE_REQ_POS] (
    [ID]              NUMERIC (19)    NOT NULL,
    [GROSS_MASS]      NUMERIC (14, 3) NULL,
    [PACKAGES]        INT             NULL,
    [POSITION_NUMBER] INT             NULL,
    [STATUS]          VARCHAR (20)    NULL,
    [ENS_ITEM_ID]     NUMERIC (19)    NULL,
    [REQUEST_ID]      NUMERIC (19)    NULL,
    CONSTRAINT [ICS_BALANCE_REQ_POS$ICS_BALANC_2873370571] PRIMARY KEY CLUSTERED ([ID] ASC)
);

