CREATE TABLE [ais2].[ICS_ENS] (
    [ACCP_DATE]        DATETIME2 (3)   NULL,
    [CHANG_FIRS_ENTR]  VARCHAR (8)     NULL,
    [COMM_REFE_NUMB]   NVARCHAR (70)   NULL,
    [CONTAINERS]       TINYINT         NULL,
    [CONV_REFE_NUMB]   VARCHAR (35)    NULL,
    [CUST_OFFI]        VARCHAR (255)   NULL,
    [DATE_OF_ARRIVING] DATETIME2 (3)   NULL,
    [FIRS_ENTR]        VARCHAR (8)     NULL,
    [FIRS_ENTR_BR]     VARCHAR (8)     NULL,
    [GOODS_PRES]       TINYINT         NULL,
    [ICS_DECL]         TINYINT         NULL,
    [LODGMENT]         VARCHAR (8)     NULL,
    [MRN]              VARCHAR (18)    NULL,
    [NUMB_ITEMS]       INT             NULL,
    [NUMB_PACK]        INT             NULL,
    [PLDT_DATE]        DATETIME2 (3)   NULL,
    [PLDT_PLACE]       VARCHAR (35)    NULL,
    [PLACE_OF_LOAD]    NVARCHAR (35)   NULL,
    [PLACE_OF_UNLOAD]  NVARCHAR (35)   NULL,
    [REGI_CUST_EMAIL]  VARCHAR (70)    NULL,
    [REGI_DATE]        DATETIME2 (3)   NULL,
    [REPR_CUST_EMAIL]  VARCHAR (70)    NULL,
    [SPEC_CIRC_INDI]   VARCHAR (1)     NULL,
    [STATUS]           VARCHAR (4)     NULL,
    [TIME_TO_RESULT]   DATETIME2 (3)   NULL,
    [TOTAL_GROSS_MASS] NUMERIC (14, 3) NULL,
    [TRAN_METH_PAYM]   VARCHAR (1)     NULL,
    [TAB_NATION]       VARCHAR (2)     NULL,
    [TAB_SINGS]        VARCHAR (31)    NULL,
    [TAB_TYPE]         VARCHAR (2)     NULL,
    [WAR_DATE]         DATETIME2 (3)   NULL,
    [ID]               NUMERIC (19)    NOT NULL,
    [AEO_CTRL_BTN]     TINYINT         NULL,
    [SEND_319_FLAG]    TINYINT         NULL,
    [SEND_351_FLAG]    TINYINT         NOT NULL,
    [INTRO]            INT             NULL,
    CONSTRAINT [ICS_ENS$ICS_ENS_4793377411] PRIMARY KEY CLUSTERED ([ID] ASC)
);

