CREATE TABLE [ais2].[ICS_MESS_KANAL] (
    [ID]      NUMERIC (19) NOT NULL,
    [MESS_ID] NUMERIC (19) NOT NULL,
    [KTYP]    VARCHAR (2)  NOT NULL,
    [KCHOICE] VARCHAR (4)  NOT NULL,
    [VAL]     VARCHAR (70) NOT NULL,
    [VAL_ADD] VARCHAR (70) NULL,
    CONSTRAINT [ICS_MESS_KANAL$ICS_MESS_KANAL_10553397931] PRIMARY KEY CLUSTERED ([ID] ASC)
);

