CREATE TABLE [ais2].[ICS_ENS_SEALS] (
    [ID]     NUMERIC (19)  NOT NULL,
    [NUMB]   NVARCHAR (20) NULL,
    [ENS_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_SEALS$ICS_ENS_SE_7993388811] PRIMARY KEY CLUSTERED ([ID] ASC)
);

