CREATE TABLE [ais2].[ICS_DIRT_POINTER] (
    [ID]      NUMERIC (19)   NOT NULL,
    [DIRT_ID] NUMERIC (19)   NULL,
    [NAME]    VARCHAR (1024) NULL,
    [TYPE]    INT            NULL,
    [VALUE]   VARCHAR (1024) NULL,
    CONSTRAINT [ICS_DIRT_POINTER$PK_ICS_DIRT_POINTER] PRIMARY KEY CLUSTERED ([ID] ASC)
);

