CREATE TABLE [ais2].[ICS_DIRT_IND] (
    [ID]           NUMERIC (19)  NOT NULL,
    [DIRECTIVE_ID] NUMERIC (19)  NOT NULL,
    [NAME]         VARCHAR (100) NOT NULL,
    [VALUE]        VARCHAR (100) NULL,
    [show]         BIT           DEFAULT ((1)) NOT NULL,
    CONSTRAINT [ICS_DIRT_IND$ICS_DIRT_I_9447193871] PRIMARY KEY CLUSTERED ([ID] ASC)
);

