CREATE TABLE [ais2].[ICS_DECL_PARAM] (
    [id]       NUMERIC (19) NOT NULL,
    [decl_id]  NUMERIC (19) NOT NULL,
    [key_name] VARCHAR (50) NOT NULL,
    [value]    VARCHAR (70) NOT NULL,
    CONSTRAINT [ICS_DECL_PARAM$ICS_DECL_PARAM_3513372851] PRIMARY KEY CLUSTERED ([id] ASC)
);

