CREATE TABLE [MF\BZRJ].[EM_1327_DZWR] (
    [NazwaKontrahenta]               NVARCHAR (255)  NULL,
    [RodzajKontrahenta]              NVARCHAR (64)   NULL,
    [NazwiskoKontrahenta]            NVARCHAR (255)  NULL,
    [KontrahentImie]                 NVARCHAR (255)  NULL,
    [KontrahentDataUrodzenia]        DATE            NULL,
    [KontrahentKraj]                 NVARCHAR (4000) NULL,
    [KontrahentWojewodztwo]          NVARCHAR (4000) NULL,
    [KontrahentPowiat]               NVARCHAR (4000) NULL,
    [KontrahentGmina]                NVARCHAR (4000) NULL,
    [UlicaKontrahenta]               NVARCHAR (4000) NULL,
    [NrDomuKontrahenta]              NVARCHAR (4000) NULL,
    [NrLokaluKontrahenta]            NVARCHAR (4000) NULL,
    [MiejscowoscKontrahenta]         NVARCHAR (4000) NULL,
    [KodPocztowyKontrahenta]         NVARCHAR (4000) NULL,
    [PocztaKontrahenta]              NVARCHAR (4000) NULL,
    [NrEoriKontrahenta]              NVARCHAR (4000) NULL,
    [NrDokumentuKontrahenta]         NVARCHAR (255)  NULL,
    [NumerVATUEKontrahenta]          NVARCHAR (4000) NULL,
    [NazwaPodatnikaRw]               NVARCHAR (255)  NULL,
    [KontrahentSystemZrodlowy]       NVARCHAR (8)    NULL,
    [NipPodatnikaRw]                 NVARCHAR (255)  NULL,
    [PeselPodatnikaRw]               NVARCHAR (255)  NULL,
    [RegonPodatnikaRw]               NVARCHAR (4000) NULL,
    [KontrahentUwagi]                NVARCHAR (MAX)  NULL,
    [DataDecyzji]                    DATE            NULL,
    [DataPoczatkuNaliczeniaOproc]    DATE            NULL,
    [ParametryWniosku]               NVARCHAR (50)   NULL,
    [AdnotacjeIUwagi]                NVARCHAR (512)  NULL,
    [RodzajPodatku]                  NVARCHAR (64)   NULL,
    [NumerDecyzji]                   NVARCHAR (255)  NULL,
    [TerminZwrotu]                   DATE            NULL,
    [TypDochodu]                     NVARCHAR (32)   NULL,
    [WnioskodawcaPostepowania]       NVARCHAR (25)   NULL,
    [PierwotneRodzaj]                NVARCHAR (255)  NULL,
    [PierwotneNumer]                 NVARCHAR (255)  NULL,
    [PierwotneDataUiszczenia]        DATE            NULL,
    [IdentyfikatorPozycji]           BIGINT          NULL,
    [PozycjeKwotaNaleznosci]         DECIMAL (19, 2) NULL,
    [PozycjeKwotaWplat]              DECIMAL (19, 2) NULL,
    [PozycjeKwotaZwrotu]             DECIMAL (19, 2) NULL,
    [PozycjeRodzajNaleznosci]        NVARCHAR (255)  NULL,
    [PozycjePierwotnyNumerDokumentu] NVARCHAR (255)  NULL,
    [SamochodyMarka]                 NVARCHAR (32)   NULL,
    [SamochodyModel]                 NVARCHAR (32)   NULL,
    [SamochodyRokProdukcji]          NVARCHAR (255)  NULL,
    [SamochodyVIN]                   NVARCHAR (25)   NULL,
    [SamochodyPojemnosc]             DECIMAL (19, 2) NULL,
    [SamochodyDataZaplaty]           DATE            NULL,
    [SamochodyZwrotCzesciowy]        NVARCHAR (5)    NULL,
    [SamochodyZwrotCalkowity]        NVARCHAR (5)    NULL,
    [SamochodyNumerDokumentu]        NVARCHAR (255)  NULL,
    [SamochodyPierwotnyPismoId]      NVARCHAR (255)  NULL
);

