CREATE TABLE [MF\BZRJ].[EM_1143_AKC4] (
    [Rodzaj dok/Załącznik]                         NVARCHAR (32)   NULL,
    [NIPLubPESELPodatnika]                         NVARCHAR (18)   NULL,
    [NumerDokumentu]                               NVARCHAR (255)  NULL,
    [NumerVATUE]                                   NVARCHAR (4000) NULL,
    [StatusDokumentu]                              NVARCHAR (4000) NULL,
    [Zarachowanie]                                 NVARCHAR (5)    NULL,
    [PowodZarachowania]                            NVARCHAR (4000) NULL,
    [DeklaracjaZaOkres]                            NVARCHAR (7)    NULL,
    [UrzadCelny]                                   NVARCHAR (255)  NULL,
    [DeklaracjaCzyKorekta]                         INT             NULL,
    [NumerDokumentuPierwotnego]                    NVARCHAR (255)  NULL,
    [UzasadnienieKorekty]                          NVARCHAR (4000) NULL,
    [RodzajKorekty]                                NVARCHAR (32)   NULL,
    [DataDoreczeniaKorektyZUrzedu]                 DATETIME2 (7)   NULL,
    [DataDoWniesieniaSprzeciwu]                    DATETIME2 (7)   NULL,
    [CzySprzeciwDoKorektyZUrzedu]                  NVARCHAR (5)    NULL,
    [RazemPodatekAkcyzowy]                         DECIMAL (19, 2) NULL,
    [KwotaZnakowAkcyzy]                            DECIMAL (19, 2) NULL,
    [KwotaWplatDziennych]                          DECIMAL (19, 2) NULL,
    [KwotaPrzedplatyAkcyzy]                        DECIMAL (19, 4) NULL,
    [NadwyzWplatDoRozliczOstatDeklar]              DECIMAL (19, 4) NULL,
    [NadwyzWplatDoRozliczPrzedplataAkcOstatDeklar] DECIMAL (19, 4) NULL,
    [DoZaplaty]                                    DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozlicz]                         DECIMAL (19, 4) NULL,
    [NadwyzWplatDoRozliczPrzedplataAkc]            INT             NULL,
    [ImiePelnomocnika]                             NVARCHAR (4000) NULL,
    [NazwiskoPelnomocnika]                         NVARCHAR (4000) NULL,
    [TelefonPodatnikaLubPelnomocnika]              NVARCHAR (4000) NULL,
    [EmailPodatnikaLubPelnomocnika]                NVARCHAR (4000) NULL,
    [UwagiUrzeduCelnego]                           NVARCHAR (4000) NULL,
    [Data złoż dok]                                CHAR (10)       NULL,
    [Data wpływu dok]                              CHAR (10)       NULL,
    [Data złoż dekl pierwotnej]                    CHAR (10)       NULL,
    [CzyOstatniaWersjaDeklaracji]                  NVARCHAR (5)    NULL,
    [FormaZlozeniaDok]                             NVARCHAR (255)  NULL,
    [NumerKolejnyZalacznika]                       INT             NULL,
    [KodCN]                                        NVARCHAR (255)  NULL,
    [NazwaGrupyWyrobow]                            NVARCHAR (4000) NULL,
    [LiczbaSamochObjetychPodatkiem]                DECIMAL (19, 4) NULL,
    [PodstawaOpodatkowania]                        DECIMAL (19, 2) NULL,
    [StawkaPodatku]                                DECIMAL (19, 4) NULL,
    [StawkaSpozaISZTAR]                            NVARCHAR (5)    NULL,
    [WartoscStawkiSpozaISZTAR]                     DECIMAL (19, 4) NULL,
    [KwotaPodatku]                                 DECIMAL (19, 2) NULL
);

