CREATE TABLE [MF\BZRJ].[EM_907_ECS_EXP_Tabak] (
    [Data przyjęcia zgłoszenia]      CHAR (10)       NULL,
    [Data wyprowadzenia]             CHAR (10)       NULL,
    [Nr zgłoszenia]                  NVARCHAR (35)   NULL,
    [Nadawca: Regon]                 NVARCHAR (14)   NULL,
    [Nadawca: TIN]                   NVARCHAR (17)   NULL,
    [Nadawca: Firma]                 NVARCHAR (105)  NULL,
    [Nadwaca: Ulica]                 NVARCHAR (105)  NULL,
    [Nadawca: Kod pocztowy]          NVARCHAR (9)    NULL,
    [Nadawca: Miejscowość]           NVARCHAR (105)  NULL,
    [Nadawca: Kraj]                  NVARCHAR (2)    NULL,
    [Nadawca towaru: Regon]          NVARCHAR (14)   NULL,
    [Nadawca towaru:TIN]             NVARCHAR (17)   NULL,
    [Nadawca towaru: Firma]          NVARCHAR (105)  NULL,
    [Nadawca towaru: Ulica]          NVARCHAR (105)  NULL,
    [Nadawca towaru: Kod pocztowy]   NVARCHAR (9)    NULL,
    [Nadawca towaru: Miejscowość]    NVARCHAR (105)  NULL,
    [Nadawca towaru: Kraj]           NVARCHAR (2)    NULL,
    [Odbiorca: Regon]                NVARCHAR (14)   NULL,
    [Odbiorca: TIN]                  NVARCHAR (17)   NULL,
    [Odbiorca: Firma]                NVARCHAR (105)  NULL,
    [Odbiorca: Ulica]                NVARCHAR (105)  NULL,
    [Odbiorca: Kod pocztowy]         NVARCHAR (9)    NULL,
    [Odbiorca: Miejscowość]          NVARCHAR (105)  NULL,
    [Odbiorca: Kraj]                 NVARCHAR (2)    NULL,
    [Odbiorca towaru: Regon]         NVARCHAR (14)   NULL,
    [Odbiorca towaru: TIN]           NVARCHAR (17)   NULL,
    [Odbiorca towaru: Firma]         NVARCHAR (105)  NULL,
    [Odbiorca towaru: Ulica]         NVARCHAR (105)  NULL,
    [Odbiorca towaru: Kod pocztowy]  NVARCHAR (9)    NULL,
    [Odbiorca towaru: Miejscowość]   NVARCHAR (105)  NULL,
    [Odbiorca towaru: Kraj]          NVARCHAR (2)    NULL,
    [Zgłaszający: REGON]             NVARCHAR (14)   NULL,
    [Zgłaszający: TIN]               NVARCHAR (17)   NULL,
    [Zgłaszający: Firma]             NVARCHAR (105)  NULL,
    [Zgłaszający: Ulica]             NVARCHAR (105)  NULL,
    [Zgłaszający: Kod pocztowy]      NVARCHAR (9)    NULL,
    [Zgłaszający: Miejscowość]       NVARCHAR (105)  NULL,
    [Zgłaszający: Kraj]              NVARCHAR (2)    NULL,
    [Kraj wysyłki]                   NVARCHAR (2)    NULL,
    [Kraj przeznaczenia]             NVARCHAR (2)    NULL,
    [UC wywozu]                      NVARCHAR (8)    NULL,
    [UC wyprowadzenia]               NVARCHAR (8)    NULL,
    [UC wypr zmieniony na]           NVARCHAR (8)    NULL,
    [Nr pozycji]                     INT             NULL,
    [Kod towaru]                     NVARCHAR (8)    NULL,
    [Opis towaru]                    NVARCHAR (840)  NULL,
    [Procedura]                      NVARCHAR (4)    NULL,
    [Masa brutto w kg]               NUMERIC (18, 3) NULL,
    [Masa netto w kg]                NUMERIC (18, 3) NULL,
    [Ilość w uz. jm]                 NUMERIC (19, 3) NULL,
    [Wartość statystyczna w PLN]     NUMERIC (17, 2) NULL,
    [Waluta]                         NVARCHAR (3)    NULL,
    [Kurs waluty]                    NUMERIC (11, 5) NULL,
    [Wartość w walucie]              NUMERIC (17, 2) NULL,
    [Rodzaj śr. transp. granica]     NVARCHAR (2)    NULL,
    [Znaki śr. transp. granica]      NVARCHAR (31)   NULL,
    [Kraj śr. transp. granica]       NVARCHAR (2)    NULL,
    [Rodzaj śr. transp. wewn. kraju] NVARCHAR (2)    NULL,
    [Znakiśr. transp. wewn. kraju]   NVARCHAR (31)   NULL
);

