CREATE TABLE [MF\BZRJ].[EM_ECS_ZWA_Wawrz] (
    [Data prezentacji]                    DATETIME2 (3)   NULL,
    [Status]                              NCHAR (1)       NOT NULL,
    [Numer MRN]                           NVARCHAR (35)   NULL,
    [UC wywozu]                           NVARCHAR (8)    NULL,
    [UC wyprowadzenia]                    NVARCHAR (8)    NULL,
    [Nadawca: NIP]                        NVARCHAR (17)   NULL,
    [Nadawca: Firma]                      NVARCHAR (105)  NULL,
    [Nadawca towaru: TIN]                 NVARCHAR (17)   NULL,
    [Nadawca towaru: firma ]              NVARCHAR (105)  NULL,
    [Odbiorca: NIP]                       NVARCHAR (17)   NULL,
    [Odbiorca: Firma]                     NVARCHAR (105)  NULL,
    [Odbiorca towaru: TIN]                NVARCHAR (17)   NULL,
    [Odbiorca towaru: firma]              NVARCHAR (105)  NULL,
    [Przedstawiający: NIP]                NVARCHAR (17)   NULL,
    [Przedstawiający: Firma]              NVARCHAR (105)  NULL,
    [Wartość statystyczna]                NUMERIC (17, 2) NULL,
    [Waluta]                              NVARCHAR (3)    NULL,
    [Masa brutto pozycji w kg]            NUMERIC (18, 3) NULL,
    [Masa brutto pozycji na granicy w kg] NUMERIC (18, 3) NULL,
    [Masa netto pozycji w kg]             NUMERIC (18, 3) NULL,
    [Masa netto pozycji na granicy w kg]  NUMERIC (18, 3) NULL,
    [Kontrola]                            NVARCHAR (2)    NULL,
    [Autor]                               NVARCHAR (255)  NULL,
    [Wykonawca]                           NVARCHAR (70)   NULL,
    [Dyrektywa]                           NTEXT           NULL,
    [Komentarz]                           NTEXT           NULL,
    [Wynik kontroli]                      NVARCHAR (1024) NULL,
    [Operator-podsumowanie kontroli]      NVARCHAR (40)   NULL,
    [Podsumowanie kontroli]               NVARCHAR (3072) NULL,
    [Operator-rejestracji rozbieżności]   NVARCHAR (40)   NULL,
    [Rejestracja rozbieżności]            NVARCHAR (3072) NULL,
    [Zamknięcia celne: liczba]            INT             NULL,
    [Zamknięcia celne: znaki]             NVARCHAR (60)   NULL
);

