CREATE TABLE [MF\BZRJ].[EM_ECS_ZWU_Wawrz] (
    [Data wywozu]                       DATETIME        NULL,
    [Data wyprowadzenia]                DATETIME        NULL,
    [Status]                            NCHAR (1)       NOT NULL,
    [id]                                NUMERIC (19)    NULL,
    [1a.Deklaracja]                     NVARCHAR (2)    NULL,
    [1b.Deklaracja]                     NVARCHAR (1)    NULL,
    [2.2.Eksporter: Firma]              NVARCHAR (105)  NULL,
    [2.Eksporter: TIN]                  NVARCHAR (17)   NULL,
    [8.8.Odbiorca: Firma]               NVARCHAR (105)  NULL,
    [8.Odbiorca: TIN]                   NVARCHAR (17)   NULL,
    [14.14.Zgłaszający: Firma]          NVARCHAR (105)  NULL,
    [14.Zgłaszający: TIN]               NVARCHAR (17)   NULL,
    [Numer MRN]                         NVARCHAR (35)   NULL,
    [UC wywozu]                         NVARCHAR (8)    NULL,
    [UC wyprowadzenia]                  NVARCHAR (8)    NULL,
    [15.Kod_kraju_wywyozu]              NVARCHAR (2)    NULL,
    [32.Pozycja Nr]                     INT             NULL,
    [35.Masa brutto (kg)]               NUMERIC (18, 3) NULL,
    [37.Procedura]                      NVARCHAR (4)    NULL,
    [38.Masa netto (kg)]                NUMERIC (18, 3) NULL,
    [40.Dokument poprzedni typ]         NVARCHAR (6)    NULL,
    [40.Dokument poprzedni nr]          NVARCHAR (105)  NULL,
    [41.Ilość_w_uzup._jednostce_miary]  NUMERIC (19, 3) NULL,
    [46.Wartość statystyczna]           NUMERIC (17, 2) NULL,
    [Kontrola]                          NVARCHAR (2)    NULL,
    [Autor]                             NVARCHAR (255)  NULL,
    [Wykonawca]                         NVARCHAR (70)   NULL,
    [Dyrektywa]                         NTEXT           NULL,
    [Komentarz]                         NTEXT           NULL,
    [Wynik kontroli]                    NVARCHAR (1024) NULL,
    [Operator-podsumowanie kontroli]    NVARCHAR (40)   NULL,
    [Podsumowanie kontroli]             NVARCHAR (3072) NULL,
    [Operator-rejestracji rozbieżności] NVARCHAR (40)   NULL,
    [Rejestracja rozbieżności]          NVARCHAR (3072) NULL,
    [Zamknięcia celne: liczba]          INT             NULL,
    [Zamknięcia celne: znaki]           NVARCHAR (765)  NULL
);

