CREATE TABLE [MF\BZRJ].[EM_ncts2_Wawrz] (
    [Nr zgłoszenia]                                  NVARCHAR (18)   NULL,
    [Typ dokumentu]                                  NVARCHAR (5)    NULL,
    [Data otwarcia]                                  DATETIME        NULL,
    [UC wyjścia]                                     NVARCHAR (8)    NULL,
    [UC przybycia]                                   NVARCHAR (35)   NULL,
    [Dekl UC przybycia]                              NVARCHAR (8)    NULL,
    [UC przeznaczenia]                               NVARCHAR (8)    NULL,
    [Kraj wysyłki]                                   NVARCHAR (2)    NULL,
    [Kraj przeznaczenia]                             NVARCHAR (2)    NULL,
    [EORI Nadawcy]                                   NVARCHAR (17)   NULL,
    [Nadawca]                                        NVARCHAR (35)   NULL,
    [Adres N]                                        NVARCHAR (100)  NULL,
    [KodP N]                                         NVARCHAR (9)    NULL,
    [Miejscowość N]                                  NVARCHAR (52)   NULL,
    [Kraj N]                                         NVARCHAR (2)    NULL,
    [nad_tin2]                                       NVARCHAR (17)   NULL,
    [nad_nazwa2]                                     NVARCHAR (35)   NULL,
    [nad_ulica2]                                     NVARCHAR (35)   NULL,
    [nad_kod_p2]                                     NVARCHAR (9)    NULL,
    [nad_miej2]                                      NVARCHAR (35)   NULL,
    [nad_kraj2]                                      NVARCHAR (2)    NULL,
    [EORI Odbiorcy]                                  NVARCHAR (17)   NULL,
    [Odbiorca]                                       NVARCHAR (35)   NULL,
    [Adres O]                                        NVARCHAR (100)  NULL,
    [KodP O]                                         NVARCHAR (9)    NULL,
    [Miejscowość O]                                  NVARCHAR (52)   NULL,
    [Kraj O]                                         NVARCHAR (2)    NULL,
    [odb_tin2]                                       NVARCHAR (17)   NULL,
    [odb_nazwa2]                                     NVARCHAR (35)   NULL,
    [odb_ulica2]                                     NVARCHAR (35)   NULL,
    [odb_kod_p2]                                     NVARCHAR (9)    NULL,
    [odb_miej2]                                      NVARCHAR (35)   NULL,
    [odb_kraj2]                                      NVARCHAR (2)    NULL,
    [EORI Gł Zobowiązanego]                          NVARCHAR (17)   NULL,
    [Główny Zobowiązany]                             NVARCHAR (35)   NULL,
    [Adres GZ]                                       NVARCHAR (100)  NULL,
    [KodP GZ]                                        NVARCHAR (9)    NULL,
    [Miejscowość GZ]                                 NVARCHAR (52)   NULL,
    [Kraj GZ]                                        NVARCHAR (2)    NULL,
    [glowny_zobowiazany_przedstawiciel_tin]          NVARCHAR (17)   NULL,
    [glowny_zobowiazany_przedstawiciel_nazwa]        NVARCHAR (35)   NULL,
    [glowny_zobowiazany_przedstawiciel_ulica_numer]  NVARCHAR (100)  NULL,
    [glowny_zobowiazany_przedstawiciel_kod_pocztowy] NVARCHAR (9)    NULL,
    [glowny_zobowiazany_przedstawiciel_miejscowosc]  NVARCHAR (52)   NULL,
    [glowny_zobowiazany_przedstawiciel_kraj]         NVARCHAR (2)    NULL,
    [EORI Przedstawiającego]                         NVARCHAR (17)   NULL,
    [Przedstawiający]                                NVARCHAR (35)   NULL,
    [Adres P]                                        NVARCHAR (100)  NULL,
    [KodP P]                                         NVARCHAR (9)    NULL,
    [Miejscowość P]                                  NVARCHAR (52)   NULL,
    [Kraj P]                                         NVARCHAR (2)    NULL,
    [EORI Przewoźnika]                               NVARCHAR (17)   NULL,
    [Przewoźnik]                                     NVARCHAR (35)   NULL,
    [Adres Prz]                                      NVARCHAR (100)  NULL,
    [KodP Prz]                                       NVARCHAR (9)    NULL,
    [Miejscowość Prz]                                NVARCHAR (52)   NULL,
    [Kraj Prz]                                       NVARCHAR (2)    NULL,
    [Termin dostawy]                                 DATETIME        NULL,
    [Data przybycia]                                 DATETIME        NULL,
    [Data zwolnienia]                                DATETIME        NULL,
    [transport_rodzaj]                               NVARCHAR (2)    NULL,
    [transport_kraj]                                 NVARCHAR (2)    NULL,
    [transport_znaki]                                NVARCHAR (27)   NULL,
    [transport_na_granicy_rodzaj]                    NVARCHAR (2)    NULL,
    [transport_na_granicy_kraj]                      NVARCHAR (2)    NULL,
    [transport_na_granicy_znaki]                     NVARCHAR (27)   NULL,
    [Status w UC wyjścia]                            NVARCHAR (8)    NULL,
    [Status w UC przeznaczenia]                      NVARCHAR (8)    NULL,
    [Nr pozycji]                                     INT             NULL,
    [Opis towaru]                                    NVARCHAR (280)  NULL,
    [Kod towaru]                                     NVARCHAR (8)    NULL,
    [Masa brutto w kg]                               NUMERIC (14, 3) NULL,
    [Masa netto w kg]                                NUMERIC (14, 3) NULL,
    [Nr gwarancji]                                   NVARCHAR (24)   NULL,
    [Odnośnik do gwarancji]                          NVARCHAR (35)   NULL,
    [Typ gwarancji]                                  NVARCHAR (1)    NULL,
    [Waluta]                                         NVARCHAR (3)    NULL,
    [Kwota]                                          NUMERIC (15, 2) NULL,
    [Kwota w pln]                                    NUMERIC (15, 2) NULL,
    [Kwota w euro]                                   NUMERIC (15, 2) NULL,
    [Kontrola w UC wyjścia]                          NVARCHAR (2)    NULL,
    [Kontrola w UC przeznaczenia]                    NVARCHAR (2)    NULL,
    [Dyrektywa]                                      NVARCHAR (36)   NULL,
    [Wynik]                                          NVARCHAR (1)    NULL,
    [Przebieg kontroli]                              NVARCHAR (1000) NULL
);

