CREATE TABLE [MF\BZRJ].[MW_1128_intr3] (
    [Nr Deklaracji]        NVARCHAR (30)   NOT NULL,
    [Rok]                  INT             NULL,
    [Miesiąc]              INT             NULL,
    [status_dekl]          NCHAR (1)       NULL,
    [status_poz]           NCHAR (1)       NULL,
    [Typ Deklaracji]       VARCHAR (7)     NULL,
    [typ]                  NCHAR (1)       NULL,
    [regon]                NVARCHAR (14)   NULL,
    [nip]                  NVARCHAR (10)   NULL,
    [nazwa]                NVARCHAR (255)  NULL,
    [ulica]                NVARCHAR (55)   NULL,
    [nr_dom]               NVARCHAR (12)   NULL,
    [nr_lok]               NVARCHAR (5)    NULL,
    [kod_poczt]            NVARCHAR (50)   NULL,
    [miejscowosc]          NVARCHAR (50)   NULL,
    [Aktualizacja]         DATETIME2 (3)   NULL,
    [Nr pozycji]           SMALLINT        NULL,
    [Kod CN]               NVARCHAR (8)    NULL,
    [Opis towaru]          NVARCHAR (420)  NULL,
    [Kraj pochodzenia]     NVARCHAR (2)    NULL,
    [Kraj przezn wysyłki]  NVARCHAR (2)    NULL,
    [Masa netto w kg]      NUMERIC (13, 2) NULL,
    [Ilość]                NUMERIC (13, 2) NULL,
    [Wartość fakturowa]    NUMERIC (17, 2) NULL,
    [Wartość statystyczna] NUMERIC (17, 2) NULL
);

