CREATE TABLE [ncts].[ADD_INF_REQ_TYP] (
    [ID]        CHAR (1) NOT NULL,
    [DAT_START] DATETIME NOT NULL,
    [DAT_END]   DATETIME NULL,
    CONSTRAINT [PK_ADD_INF_REQ_TYP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

