CREATE TABLE [ncts].[ADD_INF_RESP_TYP] (
    [ID]        CHAR (2) NOT NULL,
    [DAT_START] DATETIME NOT NULL,
    [DAT_END]   DATETIME NULL,
    CONSTRAINT [PK_ADD_INF_RESP_TYP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

