CREATE TABLE [ncts].[CONTR_GOODS_ITEM_SENS] (
    [SID]                  INT             NOT NULL,
    [CONTR_GOODS_ITEM_SID] INT             NULL,
    [SENS_GOODS_CLASS_SID] INT             NULL,
    [SENS_QUANT]           DECIMAL (14, 3) NOT NULL,
    [CONTR_LEV]            CHAR (1)        NULL,
    [SGI_CODE_TEXT]        NVARCHAR (140)  NULL,
    [SENS_QUANT_TEXT]      NVARCHAR (140)  NULL,
    CONSTRAINT [PK_CONTR_GOODS_ITEM_SENS] PRIMARY KEY CLUSTERED ([SID] ASC)
);

