CREATE TABLE [ncts].[CONTR_TRANS_OPER_DESCR] (
    [SID]           INT            NOT NULL,
    [MRN]           VARCHAR (21)   NOT NULL,
    [CONTR_LOC]     VARCHAR (3)    NOT NULL,
    [CONTR_IND]     CHAR (2)       NOT NULL,
    [POINTER]       VARCHAR (35)   NULL,
    [DESCR]         NVARCHAR (420) NULL,
    [DESCR_LNG]     CHAR (2)       NULL,
    [CORR_VAL]      VARCHAR (108)  NULL,
    [UNL_VERS_NUMB] DECIMAL (8)    NOT NULL,
    CONSTRAINT [PK_CONTR_TRANS_OPER_DESCR] PRIMARY KEY CLUSTERED ([SID] ASC)
);

