CREATE TABLE [ncts].[CROSS_BORD_TYP] (
    [ID]        VARCHAR (3) NOT NULL,
    [DAT_START] DATETIME    NOT NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_CROSS_BORD_TYP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

