CREATE TABLE [ncts].[CUST_OFF_ROL] (
    [STATUS]           CHAR (2)    NULL,
    [CUST_OFF_ACT_SID] INT         NOT NULL,
    [OFF_ROL_TYP_ID]   VARCHAR (3) NOT NULL,
    [TRAFF_TYP_ID]     VARCHAR (3) NOT NULL,
    CONSTRAINT [PK_CUST_OFF_ROL] PRIMARY KEY CLUSTERED ([CUST_OFF_ACT_SID] ASC, [OFF_ROL_TYP_ID] ASC, [TRAFF_TYP_ID] ASC)
);

