CREATE TABLE [ncts].[DECL_TRANS_OPER_DET] (
    [SID]                      INT             NOT NULL,
    [MRN]                      VARCHAR (21)    NULL,
    [TRANS_OPER_SID]           INT             NULL,
    [VERS_NUMB]                DECIMAL (3)     NOT NULL,
    [DECL_TYP_ID]              VARCHAR (5)     NULL,
    [NUMB_OF_LOAD_LISTS]       DECIMAL (5)     NULL,
    [TOT_NUMB_OF_ITEMS]        DECIMAL (5)     NULL,
    [TOT_NUMB_OF_PACK]         DECIMAL (7)     NULL,
    [DISP_COUNTRY_ID]          CHAR (2)        NULL,
    [DEST_COUNTRY_ID]          CHAR (2)        NULL,
    [IDENT_AT_DEP]             VARCHAR (81)    NULL,
    [IDENT_AT_DEP_LNG]         CHAR (2)        NULL,
    [NAT_AT_DEP]               CHAR (2)        NULL,
    [CONT]                     CHAR (1)        NULL,
    [SENS]                     CHAR (1)        NULL,
    [NAT_CROSS_BORD]           CHAR (2)        NULL,
    [IDENT_CROSS_BORD]         VARCHAR (81)    NULL,
    [IDENT_CROSS_BORD_LNG]     CHAR (2)        NULL,
    [TRANSP_TYP_CROSS_BORD]    VARCHAR (3)     NULL,
    [TRANSP_MOD_AT_BORD]       CHAR (2)        NULL,
    [INL_TRANSP_MOD]           CHAR (2)        NULL,
    [LOAD_PLAC]                NVARCHAR (17)   NULL,
    [CUST_OFF_ADDR_SID]        INT             NULL,
    [TOT_GROSS_MASS]           DECIMAL (14, 3) NOT NULL,
    [NCTS_ACC_DOC_LANG_ID]     CHAR (2)        NULL,
    [DIAL_LANG_ID]             CHAR (2)        NULL,
    [CONSIGNOR_TRAD_SID]       INT             NULL,
    [CONSIGNOR_TRADS_SID]      INT             NULL,
    [CONSIGNEE_TRAD_SID]       INT             NULL,
    [CONSIGNEE_TRADS_SID]      INT             NULL,
    [REPR_NAM]                 NVARCHAR (105)  NULL,
    [REPR_TRAD_SID]            INT             NULL,
    [REPR_CAP]                 NVARCHAR (105)  NULL,
    [REPR_CAP_LNG]             CHAR (2)        NULL,
    [AUTH_CONSIGNEE_TRAD_SID]  INT             NULL,
    [AUTH_CONSIGNEE_TRADS_SID] INT             NULL,
    [DEST_CUST_OFF_ID]         VARCHAR (8)     NULL,
    [AGR_GOODS_LOC]            NVARCHAR (105)  NULL,
    [AGR_GOODS_LOC_LNG]        CHAR (2)        NULL,
    [AGR_GOODS_LOC_COD]        NVARCHAR (17)   NULL,
    [DAT_EXP_ARR]              DATETIME        NULL,
    [PROC]                     CHAR (2)        NULL,
    [NUMB_OF_SEALS]            DECIMAL (4)     NULL,
    [AUD_USER_ID]              VARCHAR (7)     NOT NULL,
    [AUD_DAT_TIM]              DATETIME        NOT NULL,
    [SUSP_GOODS]               CHAR (1)        NULL,
    [SPECIFIC_CIRC_INDICATOR]  CHAR (1)        NULL,
    [TRANSPORT_CHARGE_PAYMENT] CHAR (1)        NULL,
    [COMM_REF_NUMBER]          VARCHAR (70)    NULL,
    [SECURITY_INDICATOR]       DECIMAL (1)     NULL,
    [CONVEY_REF_NUMBER]        VARCHAR (35)    NULL,
    [PLAC_UNLOAD_CODE]         NVARCHAR (105)  NULL,
    [SEC_CONSIGNEE_TRAD_SID]   INT             NULL,
    [SEC_CONSIGNEE_TRADS_SID]  INT             NULL,
    [SEC_CONSIGNOR_TRADS_SID]  INT             NULL,
    [SEC_CONSIGNOR_TRAD_SID]   INT             NULL,
    [SEC_CARRIER_TRADS_SID]    INT             NULL,
    [SEC_CARRIER_TRAD_SID]     INT             NULL,
    CONSTRAINT [PK_DECL_TRANS_OPER_DET] PRIMARY KEY CLUSTERED ([SID] ASC)
);

