CREATE TABLE [ncts].[ENQ_INF_COD_TYP] (
    [ID]        DECIMAL (2) NOT NULL,
    [DAT_START] DATETIME    NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_ENQ_INF_COD_TYP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

