CREATE TABLE [ncts].[ENQ_COMM] (
    [SID]              INT             NOT NULL,
    [MRN]              VARCHAR (21)    NOT NULL,
    [CUST_OFF_ID]      VARCHAR (8)     NOT NULL,
    [DEP_CUST_OFF_ID]  VARCHAR (8)     NOT NULL,
    [COMP_AUTH_OFF_ID] VARCHAR (8)     NOT NULL,
    [DAT_CAN]          DATETIME        NULL,
    [REMARKS]          NVARCHAR (1050) NULL,
    [INF_AVAIL]        CHAR (1)        NULL,
    [TCR]              CHAR (1)        NULL,
    [DAT_ENQ]          DATETIME        NULL,
    [DAT_DEL]          DATETIME        NULL,
    [ENQ_ENGAGED]      CHAR (1)        NULL,
    [DAT_ENQ_RESP]     DATETIME        NULL,
    [MOV_UNKNOWN]      CHAR (1)        NULL,
    [DAT_RET_COPY]     DATETIME        NULL,
    [DAT_TIM_EXP]      DATETIME        NULL,
    [DAT_ENQ_ANS]      DATETIME        NULL,
    [COUNTRY_ID]       CHAR (2)        NULL,
    [CITY]             NVARCHAR (105)  NULL,
    [NAM]              NVARCHAR (105)  NULL,
    [POST_COD]         VARCHAR (27)    NULL,
    [STR_AND_NUMB]     NVARCHAR (105)  NULL,
    [TIN]              VARCHAR (17)    NULL,
    [ENQ_OPEN]         DECIMAL (1)     NOT NULL,
    [COUNTER_REQS]     DECIMAL (4)     NULL,
    [DAT_ENQ_RCY]      DATETIME        NULL,
    CONSTRAINT [PK_ENQ_COMM] PRIMARY KEY CLUSTERED ([SID] ASC)
);

