CREATE TABLE [ncts].[ENQ_REM] (
    [DAT_ENQ_REM]      DATETIME    NOT NULL,
    [ENQ_COMM_SID]     INT         NOT NULL,
    [HIGH_AUTH_OFF_ID] VARCHAR (8) NOT NULL,
    CONSTRAINT [PK_ENQ_REM] PRIMARY KEY CLUSTERED ([DAT_ENQ_REM] ASC, [ENQ_COMM_SID] ASC, [HIGH_AUTH_OFF_ID] ASC)
);

