CREATE TABLE [ncts].[ENQUIRY_REQUEST] (
    [SID]                INT            NOT NULL,
    [TRANS_OPER_SID]     INT            NOT NULL,
    [MRN]                VARCHAR (21)   NOT NULL,
    [DEP_CUST_OFF_ID]    VARCHAR (8)    NOT NULL,
    [CMP_CUST_OFF_ID]    VARCHAR (8)    NOT NULL,
    [REQ_CUST_OFF_ID]    VARCHAR (8)    NOT NULL,
    [ENQ_DATE]           DATETIME       NOT NULL,
    [TCC_DELIVERED]      DECIMAL (1)    NOT NULL,
    [DEL_DATE_TC11]      DATETIME       NULL,
    [INFO_TEXT]          NVARCHAR (420) NULL,
    [INFO_AVAILABLE]     DECIMAL (1)    NOT NULL,
    [ACT_CONS_TRAD_SID]  INT            NULL,
    [ACT_CONS_TRADS_SID] INT            NULL,
    [ACT_CONS_TRAD_TIN]  VARCHAR (17)   NULL,
    [CONT_PERSON]        NVARCHAR (420) NULL,
    [RESP_RECEIVED]      DECIMAL (1)    NOT NULL,
    [TIMER_EXPIRED]      DECIMAL (1)    NOT NULL,
    CONSTRAINT [PK_ENQUIRY_REQUEST] PRIMARY KEY CLUSTERED ([SID] ASC)
);

