CREATE TABLE [ncts].[ENQUIRY_INF_REQ_DET] (
    [SID]                    INT            NOT NULL,
    [ENQUIRY_INF_REQ_SID]    INT            NOT NULL,
    [ENQ_REQ_INF_COD_TYP_ID] CHAR (2)       NOT NULL,
    [ENQ_REQ_INF_TEXT]       NVARCHAR (420) NULL,
    CONSTRAINT [PK_ENQUIRY_INF_REQ_DET] PRIMARY KEY CLUSTERED ([SID] ASC)
);

