CREATE TABLE [ncts].[ENQUIRY_RESPONSE] (
    [SID]                 INT            NOT NULL,
    [ENQUIRY_REQUEST_SID] INT            NOT NULL,
    [TRANS_OPER_SID]      INT            NOT NULL,
    [MRN]                 VARCHAR (21)   NOT NULL,
    [CMP_CUST_OFF_ID]     VARCHAR (8)    NOT NULL,
    [REQ_CUST_OFF_ID]     VARCHAR (8)    NOT NULL,
    [ENQ_RESP_DATE]       DATETIME       NOT NULL,
    [RET_COPY_DATE]       DATETIME       NULL,
    [RESP_CODE]           DECIMAL (2)    NOT NULL,
    [RESP_INFO]           NVARCHAR (140) NULL,
    [INFO_TEXT]           NVARCHAR (420) NULL,
    [INFO_AVAILABLE]      DECIMAL (1)    NOT NULL,
    [CONT_PERSON]         NVARCHAR (420) NULL,
    CONSTRAINT [PK_ENQUIRY_RESPONSE] PRIMARY KEY CLUSTERED ([SID] ASC)
);

