CREATE TABLE [ncts].[GUARANTEE_TYP] (
    [ID]        CHAR (2) NOT NULL,
    [DAT_START] DATETIME NOT NULL,
    [DAT_END]   DATETIME NULL,
    CONSTRAINT [PK_GUARANTEE_TYP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

