CREATE TABLE [ncts].[OFF_ROL_TYP] (
    [ID]        VARCHAR (3) NOT NULL,
    [DAT_START] DATETIME    NOT NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_OFF_ROL_TYP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

