CREATE TABLE [ncts].[RISK_ANA_TYP] (
    [ID]        VARCHAR (1) NOT NULL,
    [DAT_START] DATETIME    NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_RISK_ANA_TYP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

