CREATE TABLE [ncts].[SEAL_DET_VERS] (
    [TRANS_OPER_SID]       INT         NOT NULL,
    [TRANS_OPER_VERS_NUMB] DECIMAL (3) NOT NULL,
    [SEAL_DET_SID]         INT         NOT NULL,
    CONSTRAINT [PK_SEAL_DET_VERS] PRIMARY KEY CLUSTERED ([TRANS_OPER_SID] ASC, [TRANS_OPER_VERS_NUMB] ASC, [SEAL_DET_SID] ASC)
);

