CREATE TABLE [ncts].[SP_AUTH_GOODS_EXCL] (
    [TRAD_SP_AUTH_ID]   VARCHAR (17) NOT NULL,
    [HS_GOODS_CLASS_ID] VARCHAR (6)  NOT NULL,
    [CN_GOODS_CLASS_ID] CHAR (2)     NULL,
    CONSTRAINT [SPAGE_UK] UNIQUE NONCLUSTERED ([CN_GOODS_CLASS_ID] ASC, [HS_GOODS_CLASS_ID] ASC, [TRAD_SP_AUTH_ID] ASC)
);

