CREATE TABLE [ncts].[SPEC_MENT_TYP] (
    [ID]        VARCHAR (5)  NOT NULL,
    [COMM_DOM]  CHAR (1)     NULL,
    [DAT_START] DATETIME     NOT NULL,
    [DESCR]     VARCHAR (35) NULL,
    [DAT_END]   DATETIME     NULL,
    CONSTRAINT [PK_SPEC_MENT_TYP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

