CREATE TABLE [ncts].[TRAD_OFF_SP_AUTH] (
    [CUST_OFF_ID]     VARCHAR (8)  NOT NULL,
    [TRAD_SP_AUTH_ID] VARCHAR (17) NOT NULL,
    CONSTRAINT [PK_TRAD_OFF_SP_AUTH] PRIMARY KEY CLUSTERED ([CUST_OFF_ID] ASC, [TRAD_SP_AUTH_ID] ASC)
);

