CREATE TABLE [ncts].[TRAD_OFF_SP_AUTH_LOC] (
    [CUST_OFF_ID]     VARCHAR (8)  NOT NULL,
    [TRAD_SP_AUTH_ID] VARCHAR (17) NOT NULL,
    [LOC]             VARCHAR (17) NOT NULL,
    CONSTRAINT [PK_TRAD_OFF_SP_AUTH_LOC] PRIMARY KEY CLUSTERED ([CUST_OFF_ID] ASC, [TRAD_SP_AUTH_ID] ASC, [LOC] ASC)
);

