CREATE TABLE [ncts].[TRADER_ENQUIRY_REQ] (
    [SID]                     INT          NOT NULL,
    [MRN]                     VARCHAR (21) NOT NULL,
    [TRANS_OPER_SID]          INT          NOT NULL,
    [DATE_LIMIT_FOR_RESPONSE] DATETIME     NOT NULL,
    [DATE_OF_REQUEST]         DATETIME     NOT NULL,
    [COMP_CUST_OFF_ID]        VARCHAR (8)  NOT NULL,
    [DEP_CUST_OFF_ID]         VARCHAR (8)  NOT NULL,
    [RECEIVED_REPLY]          DECIMAL (1)  NOT NULL,
    CONSTRAINT [PK_TRADER_ENQUIRY_REQ] PRIMARY KEY CLUSTERED ([SID] ASC)
);

