CREATE TABLE [ncts].[TRADER_ENQUIRY_RESP] (
    [SID]                INT            NOT NULL,
    [TRANS_OPER_SID]     INT            NOT NULL,
    [MRN]                VARCHAR (21)   NOT NULL,
    [PRES_CUST_OFF_ID]   VARCHAR (8)    NULL,
    [TCC_DELIVERED]      DECIMAL (1)    NOT NULL,
    [DEL_DATE_TC11]      DATETIME       NULL,
    [INFO_TEXT]          NVARCHAR (420) NULL,
    [INFO_AVAILABLE]     DECIMAL (1)    NOT NULL,
    [ACT_CONS_TRAD_SID]  INT            NULL,
    [ACT_CONS_TRADS_SID] INT            NULL,
    [ACT_CONS_TRAD_TIN]  VARCHAR (17)   NULL,
    CONSTRAINT [PK_TRADER_ENQUIRY_RESP] PRIMARY KEY CLUSTERED ([SID] ASC)
);

