CREATE TABLE [ncts].[TRAFF_TYP_DESCR] (
    [TRAFF_TYP_ID] VARCHAR (3)   NOT NULL,
    [LANG_ID]      CHAR (2)      NOT NULL,
    [DESCR]        VARCHAR (140) NULL,
    [DAT_START]    DATETIME      NULL,
    [DAT_END]      DATETIME      NULL
);

