CREATE TABLE [ncts].[TRANSP_MOD] (
    [ID]        CHAR (2) NOT NULL,
    [DAT_START] DATETIME NOT NULL,
    [DAT_END]   DATETIME NULL,
    CONSTRAINT [PK_TRANSP_MOD] PRIMARY KEY CLUSTERED ([ID] ASC)
);

