CREATE TABLE [ncts].[UN_DANGER_GOODS] (
    [ID]        VARCHAR (4) NOT NULL,
    [DAT_START] DATETIME    NOT NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_UN_DANGER_GOODS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

