CREATE TABLE [zab].[Zabezpieczenia] (
    [IdZabezpieczenia]                    INT             NOT NULL,
    [NumerGRN]                            VARCHAR (50)    NULL,
    [TypZabezpieczeniaPid]                INT             NOT NULL,
    [RodzajZabezpieczeniaPid]             INT             NULL,
    [WariantZabezpieczeniaPid]            INT             NULL,
    [IdPodmiotu]                          BIGINT          NULL,
    [DataRejestracji]                     DATETIME        NOT NULL,
    [UrzadZlozeniaZabezpieczeniaPid]      INT             NULL,
    [KwotaZabezpieczenia]                 DECIMAL (19, 2) NULL,
    [KwotaReferencyjna]                   DECIMAL (19, 2) NULL,
    [ProcentKwotyReferencyjnej]           VARCHAR (5)     NULL,
    [WalutaPid]                           INT             NULL,
    [SaldoZabezpieczenia]                 DECIMAL (19, 2) NULL,
    [WazneOd]                             DATETIME        NOT NULL,
    [WazneDo]                             DATETIME        NULL,
    [StatusPid]                           INT             NULL,
    [AkcyzaCzyObcySkladPodatkowy]         BIT             NULL,
    [AkcyzaCzyNabywcaWewnZaplAkcyzaArt78] BIT             NULL,
    [AkcyzaCzyPodatnikOkreslonyArt13Ust3] BIT             NULL,
    [AkcyzaObszarWaznosci]                CHAR (2)        NULL,
    [TranzytCzyNiewazneNaTerenieUE]       BIT             NULL,
    [GryKrotnoscZlozonychZabezpieczen]    INT             NULL,
    [GryLiczbaKasynPunktowSalonow]        INT             NULL,
    [OplataPaliwowa]                      BIT             NULL,
    [WtymNaOplPaliw]                      NUMERIC (19, 2) NULL,
    CONSTRAINT [PK_Zabezpieczenia] PRIMARY KEY CLUSTERED ([IdZabezpieczenia] ASC) ON [FG_ZAB],
    CONSTRAINT [FK_Zabezpieczenia_IdPodmiotu_Podmiot_IdPodmiotu] FOREIGN KEY ([IdPodmiotu]) REFERENCES [zab].[Podmiot] ([IdPodmiotu]),
    CONSTRAINT [FK_Zabezpieczenia_RodzajZabezpieczeniaPid] FOREIGN KEY ([RodzajZabezpieczeniaPid]) REFERENCES [pdr].[c350234] ([c350234_id]),
    CONSTRAINT [FK_Zabezpieczenia_StatusPid] FOREIGN KEY ([StatusPid]) REFERENCES [pdr].[c3510] ([c3510_id]),
    CONSTRAINT [FK_Zabezpieczenia_TypZabezpieczenia] FOREIGN KEY ([TypZabezpieczeniaPid]) REFERENCES [pdr].[c3501] ([c3501_id]),
    CONSTRAINT [FK_Zabezpieczenia_UrzadZlozeniaZabezpieczenia] FOREIGN KEY ([UrzadZlozeniaZabezpieczeniaPid]) REFERENCES [pdr].[c001] ([c001_id]),
    CONSTRAINT [FK_Zabezpieczenia_WalutaPid] FOREIGN KEY ([WalutaPid]) REFERENCES [pdr].[s026] ([s026_id]),
    CONSTRAINT [FK_Zabezpieczenia_WariantZabezpieczenia] FOREIGN KEY ([WariantZabezpieczeniaPid]) REFERENCES [pdr].[c3505] ([c3505_id])
);

