CREATE TABLE [zef2DW].[DOOD_Dokument] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [DokumentArchiwalny]                    NVARCHAR (5)    NULL,
    [DecyzjaWydanaPrzez]                    NVARCHAR (25)   NULL,
    [OrganWydajacyIc]                       BIGINT          NULL,
    [NumerDecyzji]                          NVARCHAR (255)  NULL,
    [DataWydania]                           DATE            NULL,
    [DataDoreczenia]                        DATE            NULL,
    [TerminPlatnosciWynikajacyZDeklaracji]  DATE            NULL,
    [TerminPlatnosci]                       DATE            NULL,
    [ZaOkres]                               NVARCHAR (7)    NULL,
    [TerminOdsetki]                         DATE            NULL,
    [WWynikuKontroliPostepowania]           NVARCHAR (12)   NULL,
    [NrUpowaznienia]                        NVARCHAR (255)  NULL,
    [NrPostanowieniaOWszczeciuPostepowania] NVARCHAR (255)  NULL,
    [WynikKontroliNumerWniosku]             NVARCHAR (255)  NULL,
    [PierwotnyRodzajDokumentu]              NVARCHAR (255)  NULL,
    [PierwotnyNumerDokumentu]               NVARCHAR (255)  NULL,
    [RazemNalezneZaliczki]                  DECIMAL (19, 2) NULL,
    [RazemOdsetki]                          DECIMAL (19, 2) NULL,
    [JakiOkresRozliczeniowy]                NVARCHAR (16)   NULL,
    [WnioskodawcaPostepowania]              NVARCHAR (25)   NULL,
    [OrganWydajacyUks]                      BIGINT          NULL,
    [OrganWydajacyUs]                       BIGINT          NULL,
    [MigracjaReczna]                        NVARCHAR (5)    NULL,
    [RaportWyslaniaSK]                      NVARCHAR (MAX)  NULL,
    [DataArch]                              DATE            NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [operacja]                              NVARCHAR (1)    NULL,
    [IdentyfikatorPodatnika]                BIGINT          NULL,
    [KodJednostki]                          NVARCHAR (6)    NULL,
    [AdnotacjeIUwagi]                       NVARCHAR (255)  NULL,
    CONSTRAINT [DOOD_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

