CREATE TABLE [zef2DW].[DUNA_Dokument] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [DataDecyzji]                           DATE            NULL,
    [DataDoreczenia]                        DATE            NULL,
    [PrzyczynyUmorzenia]                    NVARCHAR (25)   NULL,
    [RazemNaleznosc]                        DECIMAL (19, 2) NULL,
    [RazemUmorzenie]                        DECIMAL (19, 2) NULL,
    [NumerDecyzji]                          NVARCHAR (255)  NULL,
    [WWynikuKontroliPostepowania]           NVARCHAR (12)   NULL,
    [TypDochodu]                            NVARCHAR (32)   NULL,
    [WpisDoRejestruCelnego]                 NVARCHAR (5)    NULL,
    [NrPostanowieniaOWszczeciuPostepowania] NVARCHAR (255)  NULL,
    [NrUpowaznienia]                        NVARCHAR (255)  NULL,
    [WynikKontroliNumerWniosku]             NVARCHAR (255)  NULL,
    [PierwotnyRodzaj]                       NVARCHAR (255)  NULL,
    [PierwotnyNumer]                        NVARCHAR (255)  NULL,
    [WnioskodawcaPostepowania]              NVARCHAR (25)   NULL,
    [RaportWyslaniaSK]                      NVARCHAR (MAX)  NULL,
    [AdnotacjeIUwagi]                       NVARCHAR (512)  NULL,
    [DataArch]                              DATE            NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [operacja]                              NVARCHAR (1)    NULL,
    [IdentyfikatorPodatnika]                BIGINT          NULL,
    [DataRejestracjiRDC]                    DATE            NULL,
    CONSTRAINT [DUNA_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

