CREATE TABLE [zef2DW].[Kontrahent] (
    [NumerPodatnika]           NVARCHAR (4000) NULL,
    [NazwaKontrahenta]         NVARCHAR (255)  NULL,
    [RodzajKontrahenta]        NVARCHAR (64)   NULL,
    [NazwiskoKontrahenta]      NVARCHAR (255)  NULL,
    [KontrahentImie]           NVARCHAR (255)  NULL,
    [KontrahentDataUrodzenia]  DATE            NULL,
    [KontrahentKraj]           NVARCHAR (4000) NULL,
    [KontrahentWojewodztwo]    NVARCHAR (4000) NULL,
    [KontrahentPowiat]         NVARCHAR (4000) NULL,
    [KontrahentGmina]          NVARCHAR (4000) NULL,
    [UlicaKontrahenta]         NVARCHAR (4000) NULL,
    [NrDomuKontrahenta]        NVARCHAR (4000) NULL,
    [NrLokaluKontrahenta]      NVARCHAR (4000) NULL,
    [MiejscowoscKontrahenta]   NVARCHAR (4000) NULL,
    [KodPocztowyKontrahenta]   NVARCHAR (4000) NULL,
    [PocztaKontrahenta]        NVARCHAR (4000) NULL,
    [NrEoriKontrahenta]        NVARCHAR (4000) NULL,
    [NrDokumentuKontrahenta]   NVARCHAR (255)  NULL,
    [NumerVATUEKontrahenta]    NVARCHAR (4000) NULL,
    [NazwaPodatnikaRw]         NVARCHAR (255)  NULL,
    [KontrahentSystemZrodlowy] NVARCHAR (8)    NULL,
    [NipPodatnikaRw]           NVARCHAR (255)  NULL,
    [PeselPodatnikaRw]         NVARCHAR (255)  NULL,
    [RegonPodatnikaRw]         NVARCHAR (4000) NULL,
    [KontrahentUwagi]          NVARCHAR (MAX)  NULL,
    [DataArch]                 DATE            NULL,
    [ID_Pismo_xml]             BIGINT          NULL,
    [operacja]                 NVARCHAR (1)    NULL,
    [IdentyfikatorPodatnika]   BIGINT          NULL
);

