CREATE TABLE [zef2DW].[NCPR_Dokument] (
    [IdentyfikatorDokumentu] BIGINT          NOT NULL,
    [DokumentArchiwalny]     NVARCHAR (5)    NULL,
    [DataOtrzymania]         DATE            NULL,
    [DataUprawomocnienia]    DATE            NULL,
    [DataWystawienia]        DATE            NULL,
    [OdDnia]                 DATE            NULL,
    [Odsetki]                NVARCHAR (255)  NULL,
    [NumerDokumentu]         NVARCHAR (255)  NULL,
    [Skala]                  NVARCHAR (10)   NULL,
    [StawkaOdsetek]          DECIMAL (19, 2) NULL,
    [TerminPlatnosci]        DATE            NULL,
    [kwotaRazem]             DECIMAL (19, 2) NULL,
    [MigracjaReczna]         NVARCHAR (5)    NULL,
    [RaportWyslaniaSK]       NVARCHAR (MAX)  NULL,
    [DataArch]               DATE            NULL,
    [ID_Pismo_xml]           BIGINT          NULL,
    [operacja]               NVARCHAR (1)    NULL,
    [IdentyfikatorPodatnika] BIGINT          NULL,
    [AdnotacjeIUwagi]        NVARCHAR (255)  NULL,
    [MigracjaKAS]            NVARCHAR (5)    NULL,
    [Rodzaj]                 NVARCHAR (255)  NULL,
    [NaliczycOdsetkiOd]      DATE            NULL,
    CONSTRAINT [NCPR_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

