CREATE TABLE [zef2DW].[PODZ_Dokument] (
    [IdentyfikatorDokumentu]                    BIGINT          NOT NULL,
    [DataWystawienia]                           DATE            NULL,
    [AdnotacjeIUwagi]                           NVARCHAR (512)  NULL,
    [NumerDokumentu]                            NVARCHAR (255)  NULL,
    [NumerPostanowienia]                        NVARCHAR (255)  NULL,
    [TypRejestracji]                            NVARCHAR (7)    NULL,
    [DataObciazeniaZabezpieczeniaGeneralnego]   DATE            NULL,
    [KodDostepuZabezpieczeniaGeneralnego]       NVARCHAR (4000) NULL,
    [KwotaZabezpieczeniaGeneralnego]            DECIMAL (19, 2) NULL,
    [NIPKontrahentaZabezpieczeniaGeneralnego]   NVARCHAR (4000) NULL,
    [NumerZabezpieczeniaGeneralnego]            NVARCHAR (255)  NULL,
    [DataObciazeniaZabezpieczeniaJednorazowego] DATE            NULL,
    [KwotaZabezpieczeniaJednorazowego]          DECIMAL (19, 2) NULL,
    [NIPKontrahentaZabezpieczeniaJednorazowego] NVARCHAR (10)   NULL,
    [NumerZabezpieczeniaJednorazowego]          NVARCHAR (255)  NULL,
    [NumerRozstrzygniecia]                      NVARCHAR (255)  NULL,
    [DataZwolnienia]                            DATE            NULL,
    [KwotaZwolnienia]                           DECIMAL (19, 2) NULL,
    [RaportWyslaniaSK]                          NVARCHAR (MAX)  NULL,
    [TypZabezpieczenia]                         NVARCHAR (11)   NULL,
    [DataArch]                                  DATE            NULL,
    [ID_Pismo_xml]                              BIGINT          NULL,
    [operacja]                                  NVARCHAR (1)    NULL,
    [IdentyfikatorPodatnika]                    BIGINT          NULL,
    CONSTRAINT [PODZ_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

