CREATE TABLE [zef2DW].[WNSB_Dokument] (
    [IdentyfikatorDokumentu]             BIGINT          NOT NULL,
    [AdresProducenta]                    NVARCHAR (4000) NULL,
    [AkcjeCzyZarejestrowanyPlatnikWynik] NVARCHAR (5)    NULL,
    [AkcjePozwoleniaWynik]               NVARCHAR (5)    NULL,
    [CzyPesel]                           NVARCHAR (5)    NULL,
    [DataRejestracji]                    DATE            NULL,
    [DataWniosku]                        DATE            NULL,
    [DataWplywu]                         DATE            NULL,
    [DataZlozenia]                       DATE            NULL,
    [DoKorekty]                          NVARCHAR (5)    NULL,
    [ListaZalacznikow]                   NVARCHAR (32)   NULL,
    [MiejsceWydania]                     NVARCHAR (4000) NULL,
    [RodzajWyrobow]                      NVARCHAR (33)   NULL,
    [ImiePelnomocnika]                   NVARCHAR (4000) NULL,
    [NazwiskoPelnomocnika]               NVARCHAR (4000) NULL,
    [NrDowoduPelnomocnika]               NVARCHAR (4000) NULL,
    [PeselPelnomocnika]                  NVARCHAR (4000) NULL,
    [AdresPelnomocnika]                  NVARCHAR (4000) NULL,
    [NrWniosku]                          NVARCHAR (255)  NULL,
    [Oswiadczenie]                       NVARCHAR (255)  NULL,
    [PodatnikDataUrodzenia]              DATE            NULL,
    [PodatnikNazwa]                      NVARCHAR (255)  NULL,
    [PodatnikNazwisko]                   NVARCHAR (255)  NULL,
    [PodatnikNipRegon]                   NVARCHAR (4000) NULL,
    [PodatnikPierwszeimie]               NVARCHAR (255)  NULL,
    [RazemDoZaplaty]                     DECIMAL (19, 2) NULL,
    [SumaKosztowWytworzenia]             DECIMAL (19, 2) NULL,
    [WartoscPodatkowychZnakowAkcyzy]     DECIMAL (19, 2) NULL,
    [RodzajBanderoli]                    NVARCHAR (32)   NULL,
    [NazwaUrzedu]                        NVARCHAR (255)  NULL,
    [UserLogin]                          NVARCHAR (255)  NULL,
    [Uwagi]                              NVARCHAR (4000) NULL,
    [Typwyrobow]                         NVARCHAR (255)  NULL,
    [PodatnikNipKraj]                    NVARCHAR (4000) NULL,
    [PodatnikKraj]                       NVARCHAR (4000) NULL,
    [PodatnikNipWojewodztwo]             NVARCHAR (4000) NULL,
    [PodatnikWojewodztwo]                NVARCHAR (4000) NULL,
    [PodatnikNipPowiat]                  NVARCHAR (4000) NULL,
    [PodatnikPowiat]                     NVARCHAR (4000) NULL,
    [PodatnikNipGmina]                   NVARCHAR (4000) NULL,
    [PodatnikGmina]                      NVARCHAR (4000) NULL,
    [PodatnikNipUlica]                   NVARCHAR (4000) NULL,
    [PodatnikUlica]                      NVARCHAR (4000) NULL,
    [PodatnikNipNrDomu]                  NVARCHAR (4000) NULL,
    [PodatnikNrDomu]                     NVARCHAR (4000) NULL,
    [PodatnikNipNrLokalu]                NVARCHAR (4000) NULL,
    [PodatnikNrLokalu]                   NVARCHAR (4000) NULL,
    [PodatnikNipMiejscowosc]             NVARCHAR (4000) NULL,
    [PodatnikMiejscowosc]                NVARCHAR (4000) NULL,
    [PodatnikNipKodPocztowy]             NVARCHAR (4000) NULL,
    [KodPocztowyPodatnika]               NVARCHAR (4000) NULL,
    [PodatnikNIPmiejscowoscPoczty]       NVARCHAR (4000) NULL,
    [PodatnikPoczta]                     NVARCHAR (4000) NULL,
    [RaportWyslaniaSK]                   NVARCHAR (MAX)  NULL,
    [DataArch]                           DATE            NULL,
    [ID_Pismo_xml]                       BIGINT          NULL,
    [operacja]                           NVARCHAR (1)    NULL,
    [IdentyfikatorPodatnika]             BIGINT          NULL,
    CONSTRAINT [WNSB_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

