CREATE TABLE [zef2DW].[ZAKP_Dokument] (
    [IdentyfikatorDokumentu]           BIGINT          NOT NULL,
    [CzyBezterminowe]                  NVARCHAR (5)    NULL,
    [DataWydaniaPotwierdzenia]         DATE            NULL,
    [FormaZabezpieczeniaInna]          NVARCHAR (4000) NULL,
    [FormaZabezpieczeniaPokwitowanie]  NVARCHAR (26)   NULL,
    [KwotaZabezpieczeniaAkcyzowego]    DECIMAL (19, 2) NULL,
    [NazwaZglaszajacego]               NVARCHAR (255)  NULL,
    [NipZglaszajacego]                 NVARCHAR (255)  NULL,
    [NumerZglaszajacego]               NVARCHAR (32)   NULL,
    [PeselZglaszajacego]               NVARCHAR (255)  NULL,
    [NumerDokumentu]                   NVARCHAR (255)  NULL,
    [ZobowiazanieDoZlozZabezpieczenia] NVARCHAR (60)   NULL,
    [PotwierdzeniePokwitowanie]        NVARCHAR (25)   NULL,
    [RegonZglaszajacego]               NVARCHAR (4000) NULL,
    [RodzajZobowiazan]                 NVARCHAR (100)  NULL,
    [StatusPodmiotu]                   NVARCHAR (50)   NULL,
    [TerminDoDnia]                     DATE            NULL,
    [TerminOdDnia]                     DATE            NULL,
    [zabezpieczenieAkcyzowe]           NVARCHAR (17)   NULL,
    [ZglaszajacyGmina]                 NVARCHAR (4000) NULL,
    [ZglaszajacyKodPocztowy]           NVARCHAR (4000) NULL,
    [ZglaszajacyKraj]                  NVARCHAR (4000) NULL,
    [ZglaszajacyMiejscowosc]           NVARCHAR (4000) NULL,
    [ZglaszajacyNrDokumentu]           NVARCHAR (4000) NULL,
    [ZglaszajacyNrDomu]                NVARCHAR (4000) NULL,
    [ZglaszajacyNrEori]                NVARCHAR (4000) NULL,
    [ZglaszajacyNrLokalu]              NVARCHAR (4000) NULL,
    [ZglaszajacyNumerVatUe]            NVARCHAR (4000) NULL,
    [ZglaszajacyPoczta]                NVARCHAR (4000) NULL,
    [ZglaszajacyPowiat]                NVARCHAR (4000) NULL,
    [ZglaszajacyUlica]                 NVARCHAR (4000) NULL,
    [ZglaszajacyUwagi]                 NVARCHAR (4000) NULL,
    [ZglaszajacyWojewodztwo]           NVARCHAR (4000) NULL,
    [DataUrodzeniaZglaszajacego]       DATE            NULL,
    [ImieZglaszajacego]                NVARCHAR (4000) NULL,
    [NazwaPelnaZglaszajacego]          NVARCHAR (4000) NULL,
    [NazwiskoZglaszajacego]            NVARCHAR (4000) NULL,
    [RodzajZglaszajacego]              NVARCHAR (64)   NULL,
    [System]                           NVARCHAR (8)    NULL,
    [DataArch]                         DATE            NULL,
    [ID_Pismo_xml]                     BIGINT          NULL,
    [operacja]                         NVARCHAR (1)    NULL,
    [IdentyfikatorPodatnika]           BIGINT          NULL,
    CONSTRAINT [ZAKP_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

