CREATE TABLE [intr2].[intr_okres_sprawozd] (
    [id_pod]                          NVARCHAR (35)   NOT NULL,
    [nr_poz]                          INT             NOT NULL,
    [rok]                             INT             NULL,
    [typ]                             NCHAR (1)       NULL,
    [miesiac]                         INT             NULL,
    [operator]                        NVARCHAR (40)   NULL,
    [data_zmiany]                     DATETIME2 (3)   NULL,
    [deklaracja]                      DECIMAL (14, 2) NULL,
    [vat]                             DECIMAL (14, 2) NULL,
    [vies]                            DECIMAL (14, 2) NULL,
    [vies_trojstronne]                DECIMAL (14, 2) NULL,
    [status_deklaracji]               NCHAR (1)       NULL,
    [deklaracja_pozycje_FLKZ]         DECIMAL (14, 2) NULL,
    [deklaracja_kod_transakcji_1]     DECIMAL (14, 2) NULL,
    [status_vat]                      NCHAR (1)       NULL,
    [status_vies]                     NCHAR (1)       NULL,
    [status_szczegolowosci]           NCHAR (1)       NULL,
    [zgodnosc_deklaracji_vat]         NCHAR (1)       NULL,
    [zgodnosc_deklaracji_vies]        NCHAR (1)       NULL,
    [zgodnosc_vat_vies]               NCHAR (1)       NULL,
    [intrastatViesRoznica12m]         NUMERIC (38)    NULL,
    [intrastatViesRoznicaProcent12m]  NUMERIC (38)    NULL,
    [intrastatBViesRoznica12m]        NUMERIC (38)    NULL,
    [intrastatBViesRoznicaProcent12m] NUMERIC (38)    NULL,
    [intrastat1ViesRoznica12m]        NUMERIC (38)    NULL,
    [intrastat1ViesRoznicaProcent12m] NUMERIC (38)    NULL,
    [vatViesRoznica12m]               NUMERIC (38)    NULL,
    [vatViesRoznicaProcent12m]        NUMERIC (38)    NULL,
    CONSTRAINT [intr_okres_sprawozd$PK_INTR_OKRES_SPRAWOZD] PRIMARY KEY CLUSTERED ([id_pod] ASC, [nr_poz] ASC) ON [FG_INTR2],
    CONSTRAINT [intr_okres_sprawozd$FK_INTR_OKR_SPR_REF_DANE_POD] FOREIGN KEY ([id_pod]) REFERENCES [intr2].[intr_dane_pod] ([id_pod])
);

