CREATE TABLE [intr2].[QRTZ_SIMPROP_TRIGGERS] (
    [SCHED_NAME]    NVARCHAR (120)  NOT NULL,
    [TRIGGER_NAME]  NVARCHAR (80)   NOT NULL,
    [TRIGGER_GROUP] NVARCHAR (80)   NOT NULL,
    [STR_PROP_1]    NVARCHAR (512)  NULL,
    [STR_PROP_2]    NVARCHAR (512)  NULL,
    [STR_PROP_3]    NVARCHAR (512)  NULL,
    [INT_PROP_1]    INT             NULL,
    [INT_PROP_2]    INT             NULL,
    [LONG_PROP_1]   NUMERIC (13)    NULL,
    [LONG_PROP_2]   NUMERIC (13)    NULL,
    [DEC_PROP_1]    NUMERIC (13, 4) NULL,
    [DEC_PROP_2]    NUMERIC (13, 4) NULL,
    [BOOL_PROP_1]   BIT             NOT NULL,
    [BOOL_PROP_2]   BIT             NOT NULL,
    CONSTRAINT [QRTZ_SIMPROP_TRIGGERS$PK_qrtz_simprop_triggers] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC) ON [FG_INTR2],
    CONSTRAINT [QRTZ_SIMPROP_TRIGGERS$FK_simprop_triggers_triggers] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [intr2].[QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
);

