CREATE TABLE [intr2].[QRTZ_FIRED_TRIGGERS] (
    [SCHED_NAME]        NVARCHAR (120) NOT NULL,
    [ENTRY_ID]          NVARCHAR (95)  NOT NULL,
    [TRIGGER_NAME]      NVARCHAR (80)  NOT NULL,
    [TRIGGER_GROUP]     NVARCHAR (80)  NOT NULL,
    [INSTANCE_NAME]     NVARCHAR (80)  NOT NULL,
    [FIRED_TIME]        NUMERIC (13)   NOT NULL,
    [SCHED_TIME]        NUMERIC (13)   NOT NULL,
    [PRIORITY]          INT            NOT NULL,
    [STATE]             NVARCHAR (16)  NOT NULL,
    [JOB_NAME]          NVARCHAR (80)  NULL,
    [JOB_GROUP]         NVARCHAR (80)  NULL,
    [IS_NONCONCURRENT]  BIT            NOT NULL,
    [REQUESTS_RECOVERY] BIT            NOT NULL,
    CONSTRAINT [QRTZ_FIRED_TRIGGERS$PK_qrtz_fired_triggers] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [ENTRY_ID] ASC) ON [FG_INTR2]
);

