CREATE TABLE [intr2].[QRTZ_SIMPLE_TRIGGERS] (
    [SCHED_NAME]      NVARCHAR (120) NOT NULL,
    [TRIGGER_NAME]    NVARCHAR (80)  NOT NULL,
    [TRIGGER_GROUP]   NVARCHAR (80)  NOT NULL,
    [REPEAT_COUNT]    NUMERIC (13)   NOT NULL,
    [REPEAT_INTERVAL] NUMERIC (13)   NOT NULL,
    [TIMES_TRIGGERED] NUMERIC (13)   NOT NULL,
    CONSTRAINT [QRTZ_SIMPLE_TRIGGERS$PK_qrtz_simple_triggers] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC) ON [FG_INTR2]
);

