CREATE TABLE [intr2].[QRTZ_BLOB_TRIGGERS] (
    [SCHED_NAME]    NVARCHAR (120) NOT NULL,
    [TRIGGER_NAME]  NVARCHAR (80)  NOT NULL,
    [TRIGGER_GROUP] NVARCHAR (80)  NOT NULL,
    [BLOB_DATA]     IMAGE          NULL,
    CONSTRAINT [QRTZ_BLOB_TRIGGERS$PK_qrtz_blob_triggers] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC) ON [FG_INTR2],
    CONSTRAINT [QRTZ_BLOB_TRIGGERS$FK_blob_triggers_triggers] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [intr2].[QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
) TEXTIMAGE_ON [FG_INTR2];

