CREATE TABLE [intr2].[QRTZ_CRON_TRIGGERS] (
    [SCHED_NAME]      NVARCHAR (120) NOT NULL,
    [TRIGGER_NAME]    NVARCHAR (80)  NOT NULL,
    [TRIGGER_GROUP]   NVARCHAR (80)  NOT NULL,
    [CRON_EXPRESSION] NVARCHAR (120) NOT NULL,
    [TIME_ZONE_ID]    NVARCHAR (80)  NULL,
    CONSTRAINT [QRTZ_CRON_TRIGGERS$PK_qrtz_cron_triggers] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC) ON [FG_INTR2],
    CONSTRAINT [QRTZ_CRON_TRIGGERS$FK_cron_triggers_triggers] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) REFERENCES [intr2].[QRTZ_TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
);

