CREATE TABLE [intr2].[QRTZ_LOCKS] (
    [SCHED_NAME] NVARCHAR (120) NOT NULL,
    [LOCK_NAME]  NVARCHAR (40)  NOT NULL,
    CONSTRAINT [QRTZ_LOCKS$PK_qrtz_locks] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [LOCK_NAME] ASC) ON [FG_INTR2]
);

