CREATE TABLE [emcs].[ECS_DECLARATIONS] (
    [ID]     BIGINT       NOT NULL,
    [MRN]    VARCHAR (18) NOT NULL,
    [STATUS] VARCHAR (8)  NOT NULL,
    CONSTRAINT [PK_ECS_DECLARATIONS] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [UK_ECS_DECLARATIONS_1] UNIQUE NONCLUSTERED ([MRN] ASC)
);

