CREATE TABLE [emcs].[EMCS_TIMERS] (
    [ID]           BIGINT       NOT NULL,
    [TYPE]         VARCHAR (20) NOT NULL,
    [START_DATE]   DATETIME     NOT NULL,
    [RUNNING]      CHAR (1)     DEFAULT ('1') NOT NULL,
    [EXPIRED]      CHAR (1)     DEFAULT ('0') NOT NULL,
    [LIMIT_DATE]   DATETIME     NOT NULL,
    [STOP_DATE]    DATETIME     NULL,
    [MVMT_ID]      BIGINT       NULL,
    [USER_TASK_ID] BIGINT       NULL,
    [ACO_ID]       BIGINT       NULL,
    CONSTRAINT [PK_TIMERS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

