CREATE TABLE [emcs].[EMCS_ACO_PROCESS_INSTANCES] (
    [ID]      BIGINT NOT NULL,
    [ACO_ID]  BIGINT NOT NULL,
    [PRIN_ID] BIGINT NOT NULL,
    CONSTRAINT [PK_ACO_PROCESS_INSTANCES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

