CREATE TABLE [emcs].[EMCS_TIMER_TYPES] (
    [TIMER_TYPE]  VARCHAR (20)  NOT NULL,
    [DESCRIPTION] VARCHAR (350) NOT NULL,
    CONSTRAINT [PK_TIMER_TYPES] PRIMARY KEY CLUSTERED ([TIMER_TYPE] ASC)
);

