CREATE TABLE [emcs].[EMCS_ACO_MESSAGE_RELATIONS] (
    [ID]            BIGINT       NOT NULL,
    [ACOM1_ID]      BIGINT       NOT NULL,
    [ACOM2_ID]      BIGINT       NOT NULL,
    [RELATION_TYPE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ACO_MESSAGE_RELATIONS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

