CREATE TABLE [emcs].[EMCS_ACO] (
    [ID]                          BIGINT         NOT NULL,
    [WORKFLOW_STATUS]             CHAR (1)       NOT NULL,
    [REQUEST_TYPE]                DECIMAL (1)    NULL,
    [DEADLINE_FOR_RESULTS]        DATETIME       NULL,
    [STATUS]                      CHAR (1)       NULL,
    [FOLLOW_UP_CORRELATION_ID]    VARCHAR (28)   NOT NULL,
    [DATE_OF_ISSUANCE]            DATETIME       NOT NULL,
    [SENDER_MEMBER_STATE_CODE]    CHAR (2)       NOT NULL,
    [SENDER_OFFICE_REF_NUM]       VARCHAR (20)   NULL,
    [SENDER_OFFICER]              NVARCHAR (50)  NULL,
    [ADDRESSEE_MEMBER_STATE_CODE] CHAR (2)       NOT NULL,
    [ADDRESSEE_OFFICE_REF_NUM]    VARCHAR (8)    NULL,
    [ADDRESSEE_OFFICER]           NVARCHAR (240) NULL,
    [WARNING_FLAG]                CHAR (1)       NOT NULL,
    [HAS_ATTACHMENTS]             CHAR (1)       NOT NULL,
    [HISTORY_REQUEST_SCOPE]       DECIMAL (1)    NULL,
    [HISTORY_SCOPE_DATE]          DATETIME       NULL,
    [ARCS]                        VARCHAR (4000) NULL,
    [MOVEMENTS]                   VARCHAR (4000) NULL,
    [IE721_MESSAGE_ID]            BIGINT         NULL,
    [IE820_MESSAGE_ID]            BIGINT         NULL,
    [IE867_MESSAGE_ID]            BIGINT         NULL,
    [IE868_DEL_MESSAGE_ID]        BIGINT         NULL,
    [IE868_REF_MESSAGE_ID]        BIGINT         NULL,
    [IE869_MESSAGE_ID]            BIGINT         NULL,
    [CREATE_DATE]                 DATETIME       NOT NULL,
    [CREATE_BY]                   VARCHAR (50)   NOT NULL,
    [CHANGE_DATE]                 DATETIME       NULL,
    [CHANGE_BY]                   VARCHAR (50)   NULL,
    [VERSION]                     INT            NOT NULL,
    CONSTRAINT [PK_ACO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

