CREATE TABLE [emcs].[EMCS_EXCISE_RATES] (
    [ID]                          BIGINT          NOT NULL,
    [VALID_FROM]                  DATE            NOT NULL,
    [VALID_TO]                    DATE            NULL,
    [EXCISE_NUMBER_CODE]          VARCHAR (4)     NOT NULL,
    [FISCAL_MARK]                 CHAR (1)        NULL,
    [CN_CODE_FROM]                VARCHAR (8)     NULL,
    [CN_CODE_TO]                  VARCHAR (8)     NULL,
    [SIZE_OF_PRODUCER_FROM]       DECIMAL (15)    NULL,
    [SIZE_OF_PRODUCER_TO]         DECIMAL (15)    NULL,
    [DENSITY_FROM]                DECIMAL (15, 5) NULL,
    [DENSITY_TO]                  DECIMAL (15, 5) NULL,
    [NOT_COLORED_AND_MARKED_OILS] CHAR (1)        NULL,
    [FUEL_TYPE]                   CHAR (1)        NULL,
    [EXEMPTION_AMOUNT]            DECIMAL (15, 5) NULL,
    [AMOUNT_RATE]                 DECIMAL (15, 5) NOT NULL,
    [PERCENT_RATE]                DECIMAL (10, 5) NULL,
    [MINIMAL_RATE]                DECIMAL (15, 5) NULL,
    [ALGORITHM_TYPE]              CHAR (1)        NOT NULL,
    [ADDITIONAL_UNIT]             CHAR (1)        NOT NULL,
    [BIO_COMPONENT_RATE]          DECIMAL (15, 5) NULL,
    [BIOFUEL_CONTENT_QUALITY]     CHAR (1)        NULL,
    [ALC_STRENGTH_FROM]           DECIMAL (15, 5) NULL,
    [ALC_STRENGTH_TO]             DECIMAL (15, 5) NULL,
    CONSTRAINT [EER_PK] PRIMARY KEY CLUSTERED ([ID] ASC)
);

