CREATE TABLE [emcs].[MVMT_WINE_OPERATION_CODES] (
    [ID]                  BIGINT   NOT NULL,
    [WINE_OPERATION_CODE] CHAR (2) NOT NULL,
    [MVMT_PRODUCT_ID]     BIGINT   NOT NULL,
    CONSTRAINT [PK_MVMTWOPCDS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

