CREATE TABLE [emcs].[MVMT_INTERESTED_OFFICES] (
    [ID]              BIGINT      NOT NULL,
    [SEQUENCE_NUMBER] DECIMAL (2) NOT NULL,
    [OFFICE_REFNUM]   VARCHAR (8) NOT NULL,
    [MVMT_ID]         BIGINT      NOT NULL,
    CONSTRAINT [PK_MVMT_INTERESTED_OFFICES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

