CREATE TABLE [emcs].[MVMT_DOWNSTREAM_MOVEMENTS] (
    [ID]      BIGINT       NOT NULL,
    [MVMT_ID] BIGINT       NOT NULL,
    [ARC]     VARCHAR (21) NOT NULL,
    CONSTRAINT [PK_MVMT_DOWNSTREAM_MOVEMENTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

