CREATE TABLE [emcs].[REF_SD2_PRZEDSTAWICIELE] (
    [ID]                   BIGINT        NOT NULL,
    [REF_SD2_PODMIOTY_NRA] VARCHAR (13)  NOT NULL,
    [IMIE]                 NVARCHAR (60) NULL,
    [NAZWISKO]             NVARCHAR (90) NULL,
    [PESEL]                VARCHAR (11)  NULL,
    [X509_THUMBPRINT]      VARCHAR (250) NULL,
    [REF_SD2_PODMIOTY_TYP] VARCHAR (5)   NOT NULL,
    CONSTRAINT [PK_REF_SD2_PRZEDSTAWICIELE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

