CREATE TABLE [emcs].[REF_SD2_UBYTKI_TRANS_KODY_CN] (
    [UBT_ID] BIGINT      NOT NULL,
    [KOD_CN] VARCHAR (8) NOT NULL,
    CONSTRAINT [UTK_PK] PRIMARY KEY CLUSTERED ([UBT_ID] ASC, [KOD_CN] ASC)
);

