CREATE TABLE [emcs].[REF_SD2_ZABEZPIECZENIA] (
    [ID]                   BIGINT       NOT NULL,
    [REF_SD2_PODMIOTY_NRA] VARCHAR (13) NOT NULL,
    [NR_GRN]               VARCHAR (17) NOT NULL,
    [OBOWIAZUJE_OD]        DATE         NOT NULL,
    [OBOWIAZUJE_DO]        DATE         NULL,
    [REF_SD2_PODMIOTY_TYP] VARCHAR (5)  NOT NULL,
    CONSTRAINT [PK_REF_SD2_ZABEZPIECZENIA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

