CREATE TABLE [emcs].[REF_SD2_WLASCICIELE] (
    [ID]             BIGINT       NOT NULL,
    [NRA]            VARCHAR (13) NOT NULL,
    [TYP]            VARCHAR (5)  NOT NULL,
    [WLASCICIEL_NRA] VARCHAR (13) NOT NULL,
    [WLASCICIEL_TYP] VARCHAR (5)  DEFAULT ('AWK') NOT NULL,
    CONSTRAINT [PK_REF_SD2_WLASCICIELE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

