CREATE TABLE [ARIFORM].[F_MW_SPR_K_BACKUP] (
    [ID]                           BIGINT          NOT NULL,
    [ROK]                          VARCHAR (4)     NULL,
    [KWARTAL]                      SMALLINT        NULL,
    [USP_IMP_LICZ_ZGL]             BIGINT          NULL,
    [USP_IMP_LICZ_POZ_ZGL]         BIGINT          NULL,
    [USP_IMP_LICZ_ZGL_ELE]         BIGINT          NULL,
    [USP_IMP_LICZ_POZ_ZGL_ELE]     BIGINT          NULL,
    [USP_IMP_LICZ_POZ_ZGL_UZU]     BIGINT          NULL,
    [USP_IMP_LICZ_POZ_ZGL_UZU_ELE] BIGINT          NULL,
    [USP_EXP_LICZ_ZGL]             BIGINT          NULL,
    [USP_EXP_LICZ_POZ_ZGL]         BIGINT          NULL,
    [USP_EXP_LICZ_ZGL_ELE]         BIGINT          NULL,
    [USP_EXP_LICZ_POZ_ZGL_ELE]     BIGINT          NULL,
    [USP_EXP_LICZ_POZ_ZGL_UZU]     BIGINT          NULL,
    [USP_EXP_LICZ_POZ_ZGL_UZU_ELE] BIGINT          NULL,
    [KTRL_IMP_LICZ_ZGL_DOK]        BIGINT          NULL,
    [KTRL_IMP_LICZ_ZGL_FIZ]        BIGINT          NULL,
    [KTRL_IMP_LICZ_ZGL_LAB]        BIGINT          NULL,
    [KTRL_EXP_LICZ_ZGL_FIZ]        BIGINT          NULL,
    [KTRL_EXP_LICZ_ZGL_LAB]        BIGINT          NULL,
    [OCH_ILO_NAR_PRZE_SPOL]        BIGINT          NULL,
    [OCH_LICZ_NAR_CITES]           BIGINT          NULL,
    [OCH_LICZ_SKON_EGZ_SZT]        BIGINT          NULL,
    [OCH_LICZ_SKON_EGZ_KG]         DECIMAL (13, 1) CONSTRAINT [DF__F_MW_SPR___OCH_L__1A14E395] DEFAULT ((0)) NULL,
    [OCH_LICZ_PRZY_WYW_KUL]        BIGINT          NULL,
    [ID_STR_ORG]                   INT             NOT NULL,
    [ID_STATUS]                    SMALLINT        NULL,
    [KOMENTARZ]                    VARCHAR (2000)  NULL,
    [LOGIN]                        VARCHAR (255)   NULL,
    [DATA_EDYCJA]                  DATETIME        NOT NULL
);

