CREATE TABLE [ARIFORM].[F_TYP_DOK] (
    [ID_DOK]        SMALLINT     NOT NULL,
    [KOD_DOK]       CHAR (4)     NULL,
    [NAZ_DOK]       VARCHAR (30) NULL,
    [FLAGA_NOWY]    SMALLINT     NULL,
    [FLAGA_PODGLAD] SMALLINT     NULL,
    PRIMARY KEY CLUSTERED ([ID_DOK] ASC)
);

