CREATE TABLE [ARIFORM].[F_ZAL_32SC_APPRLOC] (
    [ID]     BIGINT          NOT NULL,
    [ID_DOK] BIGINT          NOT NULL,
    [DZ_01]  VARCHAR (160)   NOT NULL,
    [DZ_02]  VARCHAR (500)   NULL,
    [DZ_03]  VARCHAR (500)   NULL,
    [DZ_04]  VARCHAR (500)   NULL,
    [DZ_05]  VARCHAR (500)   NULL,
    [DZ_06]  VARCHAR (160)   NULL,
    [DZ_07]  VARCHAR (160)   NULL,
    [DZ_08]  DECIMAL (14, 3) NULL,
    [DZ_09]  VARCHAR (160)   NULL,
    [DZ_10]  VARCHAR (160)   NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [F_ZAL_32SC_APPRLOC_F_ZAL_FK] FOREIGN KEY ([ID_DOK]) REFERENCES [ARIFORM].[F_ZAL_32SC] ([ID]) ON DELETE CASCADE
);

