CREATE TABLE [ARIFORM].[F_ZAL_32SC_DZ3] (
    [ID]     BIGINT       NOT NULL,
    [ID_DOK] BIGINT       NOT NULL,
    [DZ_01]  VARCHAR (80) NOT NULL,
    [DZ_02]  BIGINT       NULL,
    [DZ_03]  BIGINT       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [F_ZAL_32S_F_ZAL_FK] FOREIGN KEY ([ID_DOK]) REFERENCES [ARIFORM].[F_ZAL_32SC] ([ID]) ON DELETE CASCADE
);

