CREATE TABLE [ARIFORM].[FA_ZAL_32SC_APPRLOC] (
    [ID]      BIGINT          NOT NULL,
    [DZ_01]   VARCHAR (160)   NOT NULL,
    [DZ_02]   VARCHAR (500)   NULL,
    [DZ_03]   VARCHAR (500)   NULL,
    [DZ_04]   VARCHAR (500)   NULL,
    [DZ_05]   VARCHAR (500)   NULL,
    [DZ_06]   VARCHAR (160)   NULL,
    [DZ_07]   VARCHAR (160)   NULL,
    [DZ_08]   DECIMAL (14, 3) NULL,
    [DZ_09]   VARCHAR (160)   NULL,
    [DZ_10]   VARCHAR (160)   NULL,
    [ID_ARCH] BIGINT          NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FA_ZAL_32SC_APPRLOC_FA_ZAL_32SC_FK] FOREIGN KEY ([ID_ARCH]) REFERENCES [ARIFORM].[FA_ZAL_32SC] ([ID_ARCH]) ON DELETE CASCADE
);

