CREATE TABLE [ARIFORM].[FA_ZAL_32SC_DZ3] (
    [ID]      BIGINT       NOT NULL,
    [DZ_01]   VARCHAR (80) NOT NULL,
    [DZ_02]   BIGINT       NULL,
    [DZ_03]   BIGINT       NULL,
    [ID_ARCH] BIGINT       NOT NULL,
    CONSTRAINT [FA_ZAL_32SC_DZ3_PK] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FA_ZAL_32_FA_ZA_FK] FOREIGN KEY ([ID_ARCH]) REFERENCES [ARIFORM].[FA_ZAL_32SC] ([ID_ARCH]) ON DELETE CASCADE
);

