CREATE TABLE [ARIFORM].[MF_MESSAGE] (
    [ID]      BIGINT        NOT NULL,
    [USER_ID] BIGINT        NOT NULL,
    [DESC]    VARCHAR (250) NOT NULL,
    [TYPE]    VARCHAR (50)  NULL,
    [READ]    INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([USER_ID]) REFERENCES [ARIFORM].[MF_USER] ([ID])
);

