CREATE TABLE [ARIFORM].[MF_PASSWORD_HISTORY] (
    [ID]       BIGINT        NOT NULL,
    [USER_ID]  BIGINT        NOT NULL,
    [PASSWORD] VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([USER_ID]) REFERENCES [ARIFORM].[MF_USER] ([ID])
);

