CREATE TABLE [ARIFORM].[MF_RIGHT] (
    [ID]   BIGINT        NOT NULL,
    [NAME] VARCHAR (50)  NOT NULL,
    [DESC] VARCHAR (255) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([NAME] ASC)
);

