CREATE TABLE [ARIFORM].[MF_SYSTEM_PARAMS] (
    [ID]    BIGINT        NOT NULL,
    [NAME]  VARCHAR (50)  NULL,
    [VALUE] VARCHAR (100) NULL,
    [DESC]  VARCHAR (250) NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

