CREATE TABLE [ARIFORM].[MF_USER_RIGHT] (
    [USER_ID]  BIGINT NOT NULL,
    [RIGHT_ID] BIGINT NOT NULL,
    FOREIGN KEY ([RIGHT_ID]) REFERENCES [ARIFORM].[MF_RIGHT] ([ID]),
    FOREIGN KEY ([USER_ID]) REFERENCES [ARIFORM].[MF_USER] ([ID])
);

