CREATE TABLE [int].[dokumenty] (
    [id_dok]            VARCHAR (30) NOT NULL,
    [id_jedn]           VARCHAR (20) NOT NULL,
    [id_rodz_dok]       VARCHAR (4)  NULL,
    [id_konta]          VARCHAR (6)  NULL,
    [id_kntr]           VARCHAR (20) NULL,
    [rok]               SMALLINT     NOT NULL,
    [id_stanow]         SMALLINT     NULL,
    [nr_dok]            INT          NULL,
    [sym_dok]           VARCHAR (30) NULL,
    [dat_wystaw_dok]    DATETIME     NOT NULL,
    [dat_zamkn]         DATETIME     NULL,
    [operator]          VARCHAR (15) NOT NULL,
    [status]            CHAR (1)     NOT NULL,
    [semafor]           VARCHAR (40) NULL,
    [wlasciciel]        VARCHAR (15) NULL,
    [etap_ar]           CHAR (1)     NULL,
    [data_wyst_ar]      DATETIME     NULL,
    [fsynch]            CHAR (1)     NULL,
    [data_synch]        DATETIME     NULL,
    [etap_bilans]       CHAR (1)     NULL,
    [data_formal_przyj] DATETIME     NULL,
    [login_usr]         VARCHAR (40) NULL,
    [id_jedn_sads]      VARCHAR (20) NULL,
    [src]               VARCHAR (20) NULL,
    [signed]            CHAR (1)     NULL,
    [ExtractDate]       DATETIME     NULL,
    [Flaga]             CHAR (1)     NULL,
    [lokalizacja]       VARCHAR (35) NULL,
    CONSTRAINT [PK_dokumenty] PRIMARY KEY CLUSTERED ([id_dok] ASC) WITH (FILLFACTOR = 90)
);

