CREATE TABLE [ais2].[PDS_Dokument] (
    [Id]                          NUMERIC (19)    NOT NULL,
    [Typ]                         VARCHAR (4)     NULL,
    [AnalizaRyzyka]               VARCHAR (4)     NULL,
    [Manualna]                    TINYINT         NULL,
    [NrDokumentu]                 VARCHAR (35)    NULL,
    [RETR_EMAIL]                  VARCHAR (80)    NULL,
    [IdPlacowkiPodmiotu]          VARCHAR (2)     NULL,
    [NrWlasny]                    VARCHAR (35)    NULL,
    [PodpisCyfrowy]               TINYINT         NULL,
    [FlagaOptimisticLock]         INT             NULL,
    [dts]                         CHAR (1)        NOT NULL,
    [DataPrzyjecia]               DATETIME2 (3)   NULL,
    [UCWprowadzeniaZmienionyNa]   VARCHAR (8)     NULL,
    [CRN]                         NVARCHAR (70)   NULL,
    [CONTAINERS]                  TINYINT         NULL,
    [NrPrzewozowy]                VARCHAR (35)    NULL,
    [UCZlozenia]                  VARCHAR (255)   NULL,
    [UCZlozeniaPid]               INT             NULL,
    [DataPrzybycia]               DATETIME2 (3)   NULL,
    [UCWprowadzenia]              VARCHAR (8)     NULL,
    [UCWprowadzeniaPid]           INT             NULL,
    [UCWprowadzeniaStanNaGranicy] VARCHAR (8)     NULL,
    [PrzedstawienieTowaru]        VARCHAR (3)     NULL,
    [FlagaPochodzeniaZgloszenia]  TINYINT         NULL,
    [LODGMENT]                    VARCHAR (8)     NULL,
    [MRN]                         VARCHAR (18)    NULL,
    [LiczbaPozycji]               INT             NULL,
    [LiczbaOpakowan]              INT             NULL,
    [Data]                        DATETIME2 (3)   NULL,
    [Miejsce]                     VARCHAR (35)    NULL,
    [MiejsceZaladunku]            NVARCHAR (35)   NULL,
    [MiejsceWyladunku]            NVARCHAR (35)   NULL,
    [REGI_CUST_EMAIL]             VARCHAR (70)    NULL,
    [DataRejestracji]             DATETIME2 (3)   NULL,
    [REPR_CUST_EMAIL]             VARCHAR (70)    NULL,
    [SpecyficzneOkolicznosci]     VARCHAR (1)     NULL,
    [SpecyficzneOkolicznosciPid]  INT             NULL,
    [STATUS]                      VARCHAR (4)     NULL,
    [TerminNaWynikWGranicy]       DATETIME2 (3)   NULL,
    [MasaBrutto]                  NUMERIC (14, 3) NULL,
    [OplatyTransportoweMP]        VARCHAR (1)     NULL,
    [OplatyTransportoweMPPid]     INT             NULL,
    [TransportKraj]               VARCHAR (2)     NULL,
    [TransportKrajPid]            INT             NULL,
    [TransportZnaki]              VARCHAR (31)    NULL,
    [TransportRodzaj]             VARCHAR (2)     NULL,
    [TransportRodzajPid]          INT             NULL,
    [DataZatwierdzeniaWAR]        DATETIME2 (3)   NULL,
    [AEO_CTRL_BTN]                TINYINT         NULL,
    [FlagaIE319]                  TINYINT         NULL,
    [FlagaIE351]                  VARCHAR (3)     NOT NULL,
    [FlagaWprowadzenia]           INT             NULL,
    CONSTRAINT [PDS_Dokument$PK_PDS_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AIS2]
);

