CREATE TABLE [ais2].[PDS_Towar] (
    [Id]                           NUMERIC (19)    NOT NULL,
    [MasaBruttoSaldowanie]         NUMERIC (14, 3) NULL,
    [IloscOpakowanSaldowanie]      INT             NULL,
    [CzyPozBilansowana]            VARCHAR (3)     NULL,
    [OplTransp]                    VARCHAR (1)     NULL,
    [OplTranspPid]                 INT             NULL,
    [OplTranspUCWprow]             VARCHAR (1)     NULL,
    [OplTranspUCWprowPid]          INT             NULL,
    [OplTranspUCWprowKom]          VARCHAR (140)   NULL,
    [KodTowarowy]                  VARCHAR (8)     NULL,
    [KodTowarowyPid]               INT             NULL,
    [KodTowarowyUCWprow]           VARCHAR (8)     NULL,
    [KodTowarowyUCWprowPid]        INT             NULL,
    [CRN]                          NVARCHAR (70)   NULL,
    [CRNUCWprow]                   VARCHAR (70)    NULL,
    [KodTowNiebezp]                VARCHAR (4)     NULL,
    [KodTowNiebezpPid]             INT             NULL,
    [KodTowNiebezpUCWprow]         VARCHAR (4)     NULL,
    [KodTowNiebezpUCWprowPid]      INT             NULL,
    [KodTowNiebezpUCWprowKom]      VARCHAR (140)   NULL,
    [KodTowNiebezpUCWprowKomPid]   INT             NULL,
    [OpisTowaru]                   NVARCHAR (280)  NULL,
    [OpisTowaruUCWprow]            VARCHAR (280)   NULL,
    [MasaBrutto]                   NUMERIC (14, 3) NULL,
    [MasaBruttoUCWprow]            NUMERIC (14, 3) NULL,
    [NrPozycji]                    INT             NULL,
    [MsceZaladunku]                NVARCHAR (35)   NULL,
    [MsceZaladunkuUCWprow]         VARCHAR (35)    NULL,
    [MsceZaladunkuUCWprowKom]      VARCHAR (140)   NULL,
    [MsceWyladunku]                NVARCHAR (35)   NULL,
    [MsceWyladunkuUCWprow]         VARCHAR (35)    NULL,
    [MsceWyladunkuUCWprowKom]      VARCHAR (140)   NULL,
    [StanPozTowUCWprow]            VARCHAR (4)     NULL,
    [StanPozTowUCWprowKom]         VARCHAR (140)   NULL,
    [Status]                       VARCHAR (4)     NULL,
    [IdDokPDS]                     NUMERIC (19)    NULL,
    [UCWprowadzenia]               VARCHAR (8)     NULL,
    [UCWprowadzeniaPid]            INT             NULL,
    [CzyRoznicaIlosciPozycji]      VARCHAR (3)     NULL,
    [FlagaWprowadzenia]            INT             NULL,
    [PowiadomienieOPrzybyciu_MRZ]  VARCHAR (35)    NULL,
    [FlagaCzyObsługaPTWzakonczona] TINYINT         NULL,
    CONSTRAINT [PDS_Towar$PK_PDS_Towar] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AIS2],
    CONSTRAINT [FK__PDS_Towar_IdDokPDS__PDS_Dokument_id] FOREIGN KEY ([IdDokPDS]) REFERENCES [ais2].[PDS_Dokument] ([Id])
);

