CREATE TABLE [zef2DP].[AKC4_ZalacznikK] (
    [IdentyfikatorZalacznika]               NVARCHAR (255)  NOT NULL,
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [OznaczenieZalacznika]                  NVARCHAR (32)   NULL,
    [NumerKolejnyZalacznika]                INT             NULL,
    [NIPLubPESELPodatnika]                  NVARCHAR (18)   NULL,
    [DeklaracjaZaOkres]                     NVARCHAR (7)    NULL,
    [PowiazanaDeklaracjaAKCPA]              NVARCHAR (255)  NULL,
    [NumerAkcyzowySkladuPodatnika]          NVARCHAR (255)  NULL,
    [NumerAkcyzowySkladuObcego]             NVARCHAR (4000) NULL,
    [AdresSkladu]                           NVARCHAR (4000) NULL,
    [NumerAkcyzowyZarejestrowanegoOdbiorcy] NVARCHAR (255)  NULL,
    [RazemObliczonyPodatek]                 DECIMAL (19, 2) NULL,
    [ZwolnieniaObnizenia]                   DECIMAL (19, 2) NULL,
    [OgolemPodatek]                         DECIMAL (19, 2) NULL,
    [KwotaPrzedplatyAkcyzy]                 DECIMAL (19, 2) NULL,
    [PodatekNalezny]                        DECIMAL (19, 2) NULL,
    [NadwyzkaPrzedplaty]                    DECIMAL (19, 2) NULL,
    [RazemKwotaNaleznychWplatDziennych]     DECIMAL (19, 2) NULL,
    [RazemKwotaNadwyzkiWplatPoprzDekl]      DECIMAL (19, 2) NULL,
    [RazemKwotaDokonanychWplatDziennych]    DECIMAL (19, 2) NULL,
    [EksportIloscWyrobowWTysLitrow]         DECIMAL (19, 4) NULL,
    [EksportStawkaPodatku]                  DECIMAL (19, 4) NULL,
    [EksportKwotaPodatku]                   DECIMAL (19, 4) NULL,
    [RazemIloscWyrobowWTysLitrow]           DECIMAL (19, 4) NULL,
    [RazemKwotaPodatku]                     DECIMAL (19, 2) NULL,
    [id1]                                   NVARCHAR (150)  NULL,
    [operacja]                              NVARCHAR (1)    NULL,
    CONSTRAINT [AKC4_ZalacznikK_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorZalacznika] ASC, [IdentyfikatorDokumentu] ASC)
);

