CREATE TABLE [zef2DP].[AKCUS_Towary] (
    [IdentyfikatorDokumentu]             INT             NULL,
    [DataPowstaniaObowPodatk]            DATETIME2 (7)   NULL,
    [TerminPlatnosci]                    INT             NULL,
    [DataPlatnosci]                      DATETIME2 (7)   NULL,
    [StanSamochodu]                      VARCHAR (15)    NULL,
    [Marka]                              VARCHAR (255)   NULL,
    [Model]                              VARCHAR (255)   NULL,
    [RokProdukcji]                       VARCHAR (4)     NULL,
    [SposobNapedu]                       VARCHAR (255)   NULL,
    [PojemnoscSkokowaSilnika]            DECIMAL (19, 4) NULL,
    [PrzebiegKm]                         VARCHAR (255)   NULL,
    [NiestandardowyNumerVIN]             VARCHAR (5)     NULL,
    [NumerVIN]                           VARCHAR (255)   NULL,
    [NumerVINDotyczy]                    VARCHAR (30)    NULL,
    [MocSilnikaKW]                       VARCHAR (255)   NULL,
    [RodzajSkrzyniBiegow]                VARCHAR (15)    NULL,
    [StanTechniczny]                     VARCHAR (50)    NULL,
    [PodstawObliczPodatkuWartoscWyrobow] DECIMAL (19, 4) NULL,
    [StawkaPodatkuProcent]               DECIMAL (19, 4) NULL,
    [KwotaPodatku]                       DECIMAL (19, 4) NULL,
    [MieniePrzesiedlencze]               VARCHAR (5)     NULL,
    [Wspolwlasnosc]                      VARCHAR (5)     NULL,
    [DataArch]                           DATETIME2 (7)   NULL,
    [ID_Pismo_xml]                       BIGINT          NULL,
    [operacja]                           NVARCHAR (1)    NULL
);

