CREATE TABLE [zef2DP].[INF_Informacja_B] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [LoginUzytkownikaWprowadzDok]           NVARCHAR (255)  NULL,
    [CzyZweryfikowany]                      NVARCHAR (5)    NULL,
    [NIPLubPESELPodatnika]                  NVARCHAR (18)   NULL,
    [NumerDokumentu]                        NVARCHAR (255)  NULL,
    [NumerPaczki]                           NVARCHAR (255)  NULL,
    [SystemZrodlowy]                        NVARCHAR (8)    NULL,
    [StatusDokumentu]                       NVARCHAR (4000) NULL,
    [NumerVATUE]                            NVARCHAR (4000) NULL,
    [UrzadCelny]                            NVARCHAR (255)  NULL,
    [UrzadSkarbowyDoKtoregoAdresowaneNazwa] NVARCHAR (4000) NULL,
    [DeklaracjaCzyKorekta]                  INT             NULL,
    [DataZlozeniaDok]                       DATETIME2 (7)   NULL,
    [DataWplywuDok]                         DATETIME2 (7)   NULL,
    [NumerDokumentuPierwotnego]             NVARCHAR (255)  NULL,
    [RodzajKorekty]                         NVARCHAR (32)   NULL,
    [DataDoreczeniaKorektyZUrzedu]          DATETIME2 (7)   NULL,
    [DataDoWniesieniaSprzeciwu]             DATETIME2 (7)   NULL,
    [CzySprzeciwDoKorektyZUrzedu]           NVARCHAR (5)    NULL,
    [NumerAkcyzowySkladuPodatnika]          NVARCHAR (255)  NULL,
    [NumerAkcyzowySkladu]                   NVARCHAR (64)   NULL,
    [AdresSkladu]                           NVARCHAR (4000) NULL,
    [ZapasPoczatkowy]                       DECIMAL (19, 4) NULL,
    [KwotaOdpowZapasPoczatk]                DECIMAL (19, 4) NULL,
    [IloscWyrobPrzyjetaNaSklad]             DECIMAL (19, 4) NULL,
    [IloscWyprodukWyrobAkc]                 DECIMAL (19, 4) NULL,
    [IloscWyrobZuzytychDoProd]              DECIMAL (19, 4) NULL,
    [IloscWyrobZeSklad]                     DECIMAL (19, 4) NULL,
    [IloscWyrobZeSkladWprocedZawiesz]       DECIMAL (19, 4) NULL,
    [IloscWyrobZeSkladPozaProcedZawiesz]    DECIMAL (19, 4) NULL,
    [UbytkiCalkowZniszcz]                   DECIMAL (19, 4) NULL,
    [ZapasKoncowy]                          DECIMAL (19, 4) NULL,
    [KwotaOdpowZapasKoncow]                 DECIMAL (19, 4) NULL,
    [ImiePelnomocnika]                      NVARCHAR (4000) NULL,
    [NazwiskoPelnomocnika]                  NVARCHAR (4000) NULL,
    [TelefonPodatnikaLubPelnomocnika]       NVARCHAR (4000) NULL,
    [EmailPodatnikaLubPelnomocnika]         NVARCHAR (4000) NULL,
    [SprawdzPelnomocnictwa]                 NVARCHAR (5)    NULL,
    [UwagiUrzeduCelnego]                    NVARCHAR (4000) NULL,
    [DataZlozeniaDeklaracjiPierwotnej]      DATETIME2 (7)   NULL,
    [CzyOstatniaWersjaDeklaracji]           NVARCHAR (5)    NULL,
    [DataArch]                              DATETIME2 (7)   NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [operacja]                              NVARCHAR (1)    NULL,
    [FormaZlozeniaDok]                      NVARCHAR (255)  NULL,
    [DeklaracjaZaOkres]                     NVARCHAR (7)    NULL,
    CONSTRAINT [INF_Informacja_B_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

