CREATE TABLE [zef2DP].[OplataPaliwowa] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [LoginUzytkownikaWprowadzDok]           NVARCHAR (255)  NULL,
    [CzyZweryfikowany]                      NVARCHAR (5)    NULL,
    [NIPPodatnika]                          NVARCHAR (18)   NULL,
    [NumerDokumentu]                        NVARCHAR (255)  NULL,
    [NumerPaczki]                           NVARCHAR (255)  NULL,
    [StatusDokumentu]                       NVARCHAR (4000) NULL,
    [Zarachowanie]                          NVARCHAR (5)    NULL,
    [PowodZarachowania]                     NVARCHAR (4000) NULL,
    [DeklaracjaZaOkres]                     NVARCHAR (7)    NULL,
    [DeklaracjaZaRok]                       NVARCHAR (50)   NULL,
    [UrzadCelny]                            NVARCHAR (255)  NULL,
    [DataZlozeniaDok]                       DATETIME2 (7)   NULL,
    [DataWplywuDok]                         DATETIME2 (7)   NULL,
    [PowiazanySADLubDPDZ]                   NVARCHAR (255)  NULL,
    [RodzajDzialalnosci]                    NVARCHAR (10)   NULL,
    [NumerZabezpieczeniaJednorazowego]      NVARCHAR (4000) NULL,
    [NumerZabezpieczeniaGeneralnego]        NVARCHAR (4000) NULL,
    [PrzewidywanaDataDostawy]               DATETIME2 (7)   NULL,
    [RazemKwotaOplPaliw]                    DECIMAL (19, 2) NULL,
    [TerminPlatnosci]                       DATETIME2 (7)   NULL,
    [ImiePelnomocnika]                      NVARCHAR (4000) NULL,
    [NazwiskoPelnomocnika]                  NVARCHAR (4000) NULL,
    [TelefonPodatnikaLubPelnomocnika]       NVARCHAR (4000) NULL,
    [EmailPodatnikaLubPelnomocnika]         NVARCHAR (4000) NULL,
    [SprawdzPelnomocnictwa]                 NVARCHAR (5)    NULL,
    [WynikSprawdzeniaPelnomocnictwa]        NVARCHAR (3)    NULL,
    [UwagiUrzeduCelnego]                    NVARCHAR (4000) NULL,
    [DataZlozeniaDeklaracjiPierwotnej]      DATETIME2 (7)   NULL,
    [CzyOstatniaWersjaDeklaracji]           NVARCHAR (5)    NULL,
    [DataArch]                              DATETIME2 (7)   NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [operacja]                              NVARCHAR (1)    NULL,
    [UrzadSkarbowyDoKtoregoAdresowaneNazwa] NVARCHAR (4000) NULL,
    [FormaZlozeniaDok]                      NVARCHAR (255)  NULL,
    [SumaKwotOplatyPaliwowej]               DECIMAL (19, 4) NULL,
    CONSTRAINT [OplataPaliwowa_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

