CREATE TABLE [zef2DP].[PKOPRG_Towary] (
    [IdentyfikatorDokumentu]                            BIGINT          NOT NULL,
    [DataArch]                                          DATETIME2 (7)   NULL,
    [ID_Pismo_xml]                                      BIGINT          NULL,
    [operacja]                                          NVARCHAR (1)    NULL,
    [IloscGazuZiemnegoArt7aUst4]                        DECIMAL (19, 4) NULL,
    [IloscGazuZiemnegoArt7aUst6Pkt1]                    DECIMAL (19, 4) NULL,
    [IloscGazuZiemnegoArt7aUst6Pkt2]                    DECIMAL (19, 4) NULL,
    [IloscGazuZiemnegoArt7aUst8]                        DECIMAL (19, 4) NULL,
    [SredniaCenaGazuZiemnegoArt7aUst4]                  DECIMAL (19, 4) NULL,
    [SredniaCenaGazuZiemnegoArt7aUst6Pkt1]              DECIMAL (19, 4) NULL,
    [SredniaCenaGazuZiemnegoArt7aUst6Pkt2]              DECIMAL (19, 4) NULL,
    [SredniaCenaGazuZiemnegoArt7aUst8]                  DECIMAL (19, 4) NULL,
    [WartoscWydobytegoGazuZiemnegoArt7aUst4]            DECIMAL (19, 4) NULL,
    [WartoscWydobytegoGazuZiemnegoArt7aUst6Pkt1]        DECIMAL (19, 4) NULL,
    [WartoscWydobytegoGazuZiemnegoArt7aUst6Pkt2]        DECIMAL (19, 4) NULL,
    [WartoscWydobytegoGazuZiemnegoArt7aUst8]            DECIMAL (19, 4) NULL,
    [StawkaPodatkuGazuZiemnegoArt7aUst4]                DECIMAL (19, 4) NULL,
    [StawkaPodatkuGazuZiemnegoArt7aUst6Pkt1]            DECIMAL (19, 4) NULL,
    [StawkaPodatkuGazuZiemnegoArt7aUst6Pkt2]            DECIMAL (19, 4) NULL,
    [StawkaPodatkuGazuZiemnegoArt7aUst8]                DECIMAL (19, 4) NULL,
    [KwotaPodatkuGazuZiemnegoArt7aUst4]                 DECIMAL (19, 4) NULL,
    [KwotaPodatkuGazuZiemnegoArt7aUst6Pkt1]             DECIMAL (19, 4) NULL,
    [KwotaPodatkuGazuZiemnegoArt7aUst6Pkt2]             DECIMAL (19, 4) NULL,
    [KwotaPodatkuGazuZiemnegoArt7aUst8]                 DECIMAL (19, 4) NULL,
    [IloscRopyNaftowejArt7aUst7Pkt1]                    DECIMAL (19, 4) NULL,
    [IloscRopyNaftowejArt7aUst7Pkt2]                    DECIMAL (19, 4) NULL,
    [IloscRopyNaftowejArt7aUst8]                        DECIMAL (19, 4) NULL,
    [SredniaCenaRopyNaftowejArt7aUst7Pkt1]              DECIMAL (19, 4) NULL,
    [SredniaCenaRopyNaftowejArt7aUst7Pkt2]              DECIMAL (19, 4) NULL,
    [SredniaCenaRopyNaftowejArt7aUst8]                  DECIMAL (19, 4) NULL,
    [WartoscWydobytejRopyNaftowejArt7aUst7Pkt1]         DECIMAL (19, 4) NULL,
    [WartoscWydobytejRopyNaftowejArt7aUst7Pkt2]         DECIMAL (19, 4) NULL,
    [WartoscWydobytejRopyNaftowejArt7aUst8]             DECIMAL (19, 4) NULL,
    [StawkaPodatkuRopyNaftowejArt7aUst7Pkt1]            DECIMAL (19, 4) NULL,
    [StawkaPodatkuRopyNaftowejArt7aUst7Pkt2]            DECIMAL (19, 4) NULL,
    [StawkaPodatkuRopyNaftowejArt7aUst8]                DECIMAL (19, 4) NULL,
    [KwotaPodatkuRopyNaftowejArt7aUst7Pkt1]             DECIMAL (19, 4) NULL,
    [KwotaPodatkuRopyNaftowejArt7aUst7Pkt2]             DECIMAL (19, 4) NULL,
    [KwotaPodatkuRopyNaftowejArt7aUst8]                 DECIMAL (19, 4) NULL,
    [KwotaPodatkuGazuZiemnegoArt7aUst4SekcjaC]          DECIMAL (19, 4) NULL,
    [KwotaPodatkuGazuZiemnegoArt7aUst6Pkt1SekcjaC]      DECIMAL (19, 4) NULL,
    [KwotaPodatkuGazuZiemnegoArt7aUst6Pkt2SekcjaC]      DECIMAL (19, 4) NULL,
    [KwotaPodatkuGazuZiemnegoArt7aUst8SekcjaC]          DECIMAL (19, 4) NULL,
    [KwotaPodatkuRopyNaftowejArt7aUst7Pkt1SekcjaC]      DECIMAL (19, 4) NULL,
    [KwotaPodatkuRopyNaftowejArt7aUst7Pkt2SekcjaC]      DECIMAL (19, 4) NULL,
    [KwotaPodatkuRopyNaftowejArt7aUst8SekcjaC]          DECIMAL (19, 4) NULL,
    [KwotaZwolnieniaGazuZiemnegoArt7aUst4]              DECIMAL (19, 4) NULL,
    [KwotaZwolnieniaGazuZiemnegoArt7aUst6Pkt1]          DECIMAL (19, 4) NULL,
    [KwotaZwolnieniaGazuZiemnegoArt7aUst6Pkt2]          DECIMAL (19, 4) NULL,
    [KwotaZwolnieniaGazuZiemnegoArt7aUst8]              DECIMAL (19, 4) NULL,
    [KwotaZwolnieniaRopyNaftowejArt7aUst7Pkt1]          DECIMAL (19, 4) NULL,
    [KwotaZwolnieniaRopyNaftowejArt7aUst7Pkt2]          DECIMAL (19, 4) NULL,
    [KwotaZwolnieniaRopyNaftowejArt7aUst8]              DECIMAL (19, 4) NULL,
    [KwotaPodatkuPoZwolnieniuGazuZiemnegoArt7aUst4]     DECIMAL (19, 4) NULL,
    [KwotaPodatkuPoZwolnieniuGazuZiemnegoArt7aUst6Pkt1] DECIMAL (19, 4) NULL,
    [KwotaPodatkuPoZwolnieniuGazuZiemnegoArt7aUst6Pkt2] DECIMAL (19, 4) NULL,
    [KwotaPodatkuPoZwolnieniuGazuZiemnegoArt7aUst8]     DECIMAL (19, 4) NULL,
    [KwotaPodatkuPoZwolnieniuRopyNaftowejArt7aUst7Pkt1] DECIMAL (19, 4) NULL,
    [KwotaPodatkuPoZwolnieniuRopyNaftowejArt7aUst7Pkt2] DECIMAL (19, 4) NULL,
    [KwotaPodatkuPoZwolnieniuRopyNaftowejArt7aUst8]     DECIMAL (19, 4) NULL
);

