CREATE TABLE [zef2DP].[POG5_Deklaracja] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [LoginUzytkownikaWprowadzDok]           NVARCHAR (255)  NULL,
    [CzyZweryfikowany]                      NVARCHAR (5)    NULL,
    [NIPLubPESELPodatnika]                  NVARCHAR (18)   NULL,
    [NumerDokumentu]                        NVARCHAR (255)  NULL,
    [NumerPaczki]                           NVARCHAR (255)  NULL,
    [SystemZrodlowy]                        NVARCHAR (8)    NULL,
    [StatusDokumentu]                       NVARCHAR (4000) NULL,
    [NumerVATUE]                            NVARCHAR (4000) NULL,
    [Zarachowanie]                          NVARCHAR (5)    NULL,
    [PowodZarachowania]                     NVARCHAR (4000) NULL,
    [DeklaracjaZaOkres]                     NVARCHAR (7)    NULL,
    [UrzadSkarbowyDoKtoregoAdresowaneKod]   NVARCHAR (6)    NULL,
    [UrzadSkarbowyDoKtoregoAdresowaneNazwa] NVARCHAR (4000) NULL,
    [UrzadZlozenia]                         NVARCHAR (6)    NULL,
    [DeklaracjaCzyKorekta]                  INT             NULL,
    [DataZlozeniaDok]                       DATETIME2 (7)   NULL,
    [DataWplywuDok]                         DATETIME2 (7)   NULL,
    [NumerDokumentuPierwotnego]             NVARCHAR (255)  NULL,
    [RodzajKorekty]                         NVARCHAR (32)   NULL,
    [DataDoreczeniaKorektyZUrzedu]          DATETIME2 (7)   NULL,
    [DataDoWniesieniaSprzeciwu]             DATETIME2 (7)   NULL,
    [CzySprzeciwDoKorektyZUrzedu]           NVARCHAR (5)    NULL,
    [LiczbaZlozonychZalacznikowPOG5A]       INT             NULL,
    [LiczbaZlozonychZalacznikowPOG5C]       INT             NULL,
    [LiczbaZlozonychZalacznikowPOG5D]       INT             NULL,
    [KwotaPodatkuPOG5A]                     DECIMAL (19, 2) NULL,
    [KwotaPodatkuPOG5C]                     DECIMAL (19, 2) NULL,
    [KwotaPodatkuPOG5D]                     DECIMAL (19, 2) NULL,
    [RazemKwotaPodatkuPOG]                  DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozliczOstatDeklar]       INT             NULL,
    [KwotaWplatDziennych]                   DECIMAL (19, 2) NULL,
    [DoZaplaty]                             DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozlicz]                  INT             NULL,
    [ImiePelnomocnika]                      NVARCHAR (4000) NULL,
    [NazwiskoPelnomocnika]                  NVARCHAR (4000) NULL,
    [TelefonPodatnikaLubPelnomocnika]       NVARCHAR (4000) NULL,
    [EmailPodatnikaLubPelnomocnika]         NVARCHAR (4000) NULL,
    [WynikSprawdzeniaPelnomocnictwa]        NVARCHAR (3)    NULL,
    [UwagiUrzeduSkarbowego]                 NVARCHAR (4000) NULL,
    [DataZlozeniaDeklaracjiPierwotnej]      DATETIME2 (7)   NULL,
    [CzyOstatniaWersjaDeklaracji]           NVARCHAR (5)    NULL,
    [DataArch]                              DATETIME2 (7)   NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [operacja]                              NVARCHAR (1)    NULL,
    [RazemKwotaPodatkuPOGSPR]               DECIMAL (19, 2) NULL,
    [DoZaplatySPR]                          DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozliczSPR]               DECIMAL (19, 2) NULL,
    [FormaZlozeniaDok]                      NVARCHAR (255)  NULL,
    [UzasadnienieKorekty]                   NVARCHAR (4000) NULL,
    CONSTRAINT [POG5_Deklaracja_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

