CREATE TABLE [zef2DP].[POG5_ZalacznikC_v4] (
    [IdentyfikatorZalacznika]                  NVARCHAR (255)  NOT NULL,
    [IdentyfikatorDokumentu]                   BIGINT          NOT NULL,
    [OznaczenieZalacznika]                     NVARCHAR (32)   NULL,
    [NumerKolejnyZalacznika]                   INT             NULL,
    [NIPLubPESELPodatnika]                     NVARCHAR (18)   NULL,
    [DeklaracjaZaOkres]                        NVARCHAR (7)    NULL,
    [REGON]                                    NVARCHAR (4000) NULL,
    [Monopol]                                  NVARCHAR (128)  NULL,
    [DataUtworzeniaMonopol]                    DATETIME2 (7)   NULL,
    [PodstawaOpodatkGryLiczbowe]               DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryLiczbowe]                 DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryLiczbowe]                  DECIMAL (19, 4) NULL,
    [PodstawaOpodatkLoteriePieniezne]          DECIMAL (19, 4) NULL,
    [StawkaPodatkuLoteriePieniezne]            DECIMAL (19, 4) NULL,
    [KwotaPodatkuLoteriePieniezne]             DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryTelebingo]              DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryTelebingo]                DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryTelebingo]                 DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryAutomaty]               DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryAutomaty]                 DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryAutomaty]                  DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryLiczboweInternet]       DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryLiczboweInternet]         DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryLiczboweInternet]          DECIMAL (19, 4) NULL,
    [PodstawaOpodatkLoteriePieniezneInternet]  DECIMAL (19, 4) NULL,
    [StawkaPodatkuLoteriePieniezneInternet]    DECIMAL (19, 4) NULL,
    [KwotaPodatkuLoteriePieniezneInternet]     DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryTelebingoInternet]      DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryTelebingoInternet]        DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryTelebingoInternet]         DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryCylindryczneInternet]   DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryCylindryczneInternet]     DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryCylindryczneInternet]      DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryAutomatyInternet]       DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryAutomatyInternet]         DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryAutomatyInternet]          DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryKartyInternet]          DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryKartyInternet]            DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryKartyInternet]             DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryKosciInternet]          DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryKosciInternet]            DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryKosciInternet]             DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryBingoPieniezneInternet] DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryBingoPieniezneInternet]   DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryBingoPieniezneInternet]    DECIMAL (19, 4) NULL,
    [PodstawaOpodatkLoterieFantoweInternet]    DECIMAL (19, 4) NULL,
    [StawkaPodatkuLoterieFantoweInternet]      DECIMAL (19, 4) NULL,
    [KwotaPodatkuLoterieFantoweInternet]       DECIMAL (19, 4) NULL,
    [PodstawaOpodatkGryBingoFantoweInternet]   DECIMAL (19, 4) NULL,
    [StawkaPodatkuGryBingoFantoweInternet]     DECIMAL (19, 4) NULL,
    [KwotaPodatkuGryBingoFantoweInternet]      DECIMAL (19, 4) NULL,
    [RazemKwotaPodatku]                        DECIMAL (19, 4) NULL,
    [RazemKwotaPodatkuSPR]                     DECIMAL (19, 4) NULL,
    [id1]                                      NVARCHAR (150)  NULL,
    [operacja]                                 NVARCHAR (1)    NULL,
    [PodatekWplacony]                          DECIMAL (19, 4) NULL,
    CONSTRAINT [POG5_ZalacznikC_v4_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorZalacznika] ASC, [IdentyfikatorDokumentu] ASC)
);

