CREATE TABLE [zef2DP].[VAT14_Deklaracja] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [CzyZweryfikowany]                      NVARCHAR (5)    NULL,
    [CzyObcokrajowiec]                      NVARCHAR (5)    NULL,
    [NIPLubPESELPodatnika]                  NVARCHAR (18)   NULL,
    [NumerDokumentu]                        NVARCHAR (255)  NULL,
    [NumerPaczki]                           NVARCHAR (255)  NULL,
    [StatusDokumentu]                       NVARCHAR (100)  NULL,
    [DeklaracjaZaOkres]                     NVARCHAR (7)    NULL,
    [UrzadCelny]                            NVARCHAR (255)  NULL,
    [UrzadSkarbowyDoKtoregoAdresowaneNazwa] NVARCHAR (4000) NULL,
    [IdUrzeduCelnego]                       NVARCHAR (255)  NULL,
    [DeklaracjaCzyKorekta]                  INT             NULL,
    [NumerDokumentuPierwotnego]             NVARCHAR (255)  NULL,
    [UzasadnienieKorekty]                   NVARCHAR (4000) NULL,
    [RodzajKorekty]                         NVARCHAR (32)   NULL,
    [DataDoreczeniaKorektyZUrzedu]          DATETIME2 (7)   NULL,
    [DataDoWniesieniaSprzeciwu]             DATETIME2 (7)   NULL,
    [CzySprzeciwDoKorektyZUrzedu]           NVARCHAR (5)    NULL,
    [CzySkladajacyJestPodatnikiem]          NVARCHAR (5)    NULL,
    [CzySkladajacyJestPlatnikiem]           NVARCHAR (5)    NULL,
    [RazemWartoscTransakcji]                DECIMAL (19, 4) NULL,
    [RazemKwotaPodatekNalezny]              DECIMAL (19, 4) NULL,
    [RazemKwotaZryczWynagrodzPlatnika]      DECIMAL (19, 4) NULL,
    [PodatekDoZaplaty]                      DECIMAL (19, 4) NULL,
    [ImiePelnomocnika]                      NVARCHAR (4000) NULL,
    [NazwiskoPelnomocnika]                  NVARCHAR (4000) NULL,
    [TelefonPodatnikaLubPelnomocnika]       NVARCHAR (4000) NULL,
    [EmailPodatnikaLubPelnomocnika]         NVARCHAR (4000) NULL,
    [SprawdzPelnomocnictwa]                 NVARCHAR (25)   NULL,
    [WynikSprawdzeniaPelnomocnictwa]        NVARCHAR (25)   NULL,
    [UwagiUrzeduCelnego]                    NVARCHAR (4000) NULL,
    [NumerReferencyjny]                     NVARCHAR (255)  NULL,
    [DataArch]                              DATETIME2 (7)   NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [operacja]                              NVARCHAR (1)    NULL,
    [DataZlozeniaDok]                       DATETIME2 (7)   NULL,
    [DataWplywuDok]                         DATETIME2 (7)   NULL,
    [FormaZlozeniaDok]                      NVARCHAR (255)  NULL,
    [CzyOstatniaWersjaDeklaracji]           NVARCHAR (5)    NULL,
    [DataZlozeniaDeklaracjiPierwotnej]      DATETIME2 (7)   NULL,
    CONSTRAINT [VAT14_Deklaracja_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC)
);

