CREATE TABLE [zc].[DS_Dokument] (
    [IdDok]                 BIGINT       NOT NULL,
    [Identyfikator]         VARCHAR (40) NULL,
    [RodzajDok]             VARCHAR (4)  NULL,
    [WersjaXML]             VARCHAR (7)  NULL,
    [DataPrzeslania]        DATETIME     NULL,
    [UrzadRejestracji]      VARCHAR (8)  NULL,
    [UrzadRejestracjiPid]   INT          NULL,
    [PasRejestracji]        CHAR (2)     NULL,
    [Status]                CHAR (1)     NULL,
    [Placowka]              VARCHAR (8)  NULL,
    [PlacowkaPid]           INT          NULL,
    [NrCelina]              VARCHAR (40) NULL,
    [DataPrzyjecia]         DATETIME     NULL,
    [NrWlasny]              VARCHAR (14) NULL,
    [LokalizacjaMiejsce]    VARCHAR (17) NULL,
    [LokalizacjaUC]         VARCHAR (8)  NULL,
    [LokalizacjaUCPid]      INT          NULL,
    [LokalizacjaOpis]       VARCHAR (35) NULL,
    [TowarDataPrzedst]      DATETIME     NULL,
    [TerminNaPrzeznaczenie] DATETIME     NULL,
    [PotwierdzenieWywozu]   CHAR (1)     NULL,
    [NrCelina2]             VARCHAR (40) NULL,
    [SkladajacyMiejsce]     VARCHAR (35) NULL,
    [SkladajacyData]        DATETIME     NULL,
    [SprostowanieNrCelina]  VARCHAR (40) NULL,
    [SprostowanieNr]        SMALLINT     NULL,
    [SprostowanieData]      DATETIME     NULL,
    [IdPrzedstawiajacy]     INT          NULL,
    [IdSkladajacy]          INT          NULL,
    CONSTRAINT [PK_DS_Dokument] PRIMARY KEY CLUSTERED ([IdDok] ASC)
);

