CREATE TABLE [zc].[DWU_Dokument] (
    [Id]                         DECIMAL (19)    NOT NULL,
    [Status]                     CHAR (1)        NULL,
    [NrWlasny]                   VARCHAR (22)    NULL,
    [MRN]                        VARCHAR (35)    NULL,
    [CRN]                        VARCHAR (70)    NULL,
    [UCZlozenia]                 VARCHAR (8)     NULL,
    [UCZlozeniaPid]              INT             NULL,
    [UCWyprowadzenia]            VARCHAR (8)     NULL,
    [UCWyprowadzeniaPid]         INT             NULL,
    [SpecyficzneOkolicznosci]    CHAR (1)        NULL,
    [SpecyficzneOkolicznosciPid] INT             NULL,
    [LiczbaPozycji]              INT             NULL,
    [LiczbaOpakowan]             INT             NULL,
    [MasaBrutto]                 DECIMAL (18, 3) NULL,
    [KodTypOplatTransp]          CHAR (1)        NULL,
    [KodTypOplatTranspPid]       INT             NULL,
    [PodpisElektroniczny]        TINYINT         NULL,
    [DataPrzyjecia]              DATETIME        NULL,
    [DataZgody]                  DATETIME        NULL,
    [Data]                       DATETIME        NULL,
    [Miejsce]                    VARCHAR (35)    NULL,
    CONSTRAINT [PK_DWU_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC)
);

