CREATE TABLE [zc].[PDS_Towar] (
    [Id]                         DECIMAL (19)  NOT NULL,
    [NrPozycji]                  INT           NULL,
    [CRN]                        VARCHAR (70)  NULL,
    [CRNUCWprow]                 VARCHAR (70)  NULL,
    [OpisTowaru]                 VARCHAR (280) NULL,
    [OpisTowaruUCWprow]          VARCHAR (280) NULL,
    [KodTowarowy]                VARCHAR (8)   NULL,
    [KodTowarowyPid]             INT           NULL,
    [KodTowarowyUCWprow]         VARCHAR (8)   NULL,
    [MsceZaladunku]              VARCHAR (35)  NULL,
    [MsceZaladunkuUCWprow]       VARCHAR (35)  NULL,
    [MsceZaladunkuUCWprowPid]    INT           NULL,
    [MsceZaladunkuUCWprowKom]    VARCHAR (140) NULL,
    [MsceWyladunku]              VARCHAR (35)  NULL,
    [MsceWyladunkuUCWprow]       VARCHAR (35)  NULL,
    [MsceWyladunkuUCWprowKom]    VARCHAR (140) NULL,
    [UCWprowadzenia]             VARCHAR (8)   NULL,
    [UCWprowadzeniaPid]          INT           NULL,
    [MasaBrutto]                 FLOAT (53)    NULL,
    [MasaBruttoUCWprow]          FLOAT (53)    NULL,
    [MasaBruttoSaldowanie]       FLOAT (53)    NULL,
    [KodTowNiebezp]              VARCHAR (4)   NULL,
    [KodTowNiebezpPid]           INT           NULL,
    [KodTowNiebezpUCWprow]       VARCHAR (4)   NULL,
    [KodTowNiebezpUCWprowPid]    INT           NULL,
    [KodTowNiebezpUCWprowKom]    VARCHAR (140) NULL,
    [KodTowNiebezpUCWprowKomPid] INT           NULL,
    [OplTransp]                  CHAR (1)      NULL,
    [OplTranspPid]               INT           NULL,
    [OplTranspUCWprow]           CHAR (1)      NULL,
    [OplTranspUCWprowPid]        INT           NULL,
    [OplTranspUCWprowKom]        VARCHAR (140) NULL,
    [IloscOpakowanSaldowanie]    INT           NULL,
    [StanPozTowUCWprow]          VARCHAR (4)   NULL,
    [StanPozTowUCWprowKom]       VARCHAR (140) NULL,
    [Status]                     VARCHAR (4)   NULL,
    [CzyPozBilansowana]          BIT           NULL,
    [CzyRoznicaIlosciPozycji]    BIT           NULL,
    [Typ]                        VARCHAR (4)   NULL,
    [AnalizaRyzyka]              VARCHAR (4)   NULL,
    [Manualna]                   TINYINT       NULL,
    [NrReferencyjny]             VARCHAR (35)  NULL,
    [EmailPodmiotu]              VARCHAR (80)  NULL,
    [IdPlacowki]                 CHAR (2)      NULL,
    [NrWlasny]                   VARCHAR (22)  NULL,
    [PodpisCyfrowy]              TINYINT       NULL,
    [IdDokPDS]                   DECIMAL (19)  NULL,
    [FlagaOptimisticLock]        INT           NULL,
    CONSTRAINT [PK_PDS_Towar] PRIMARY KEY CLUSTERED ([Id] ASC)
);

