CREATE TABLE [zc].[PWD_Dokument] (
    [IdDok]                           BIGINT          NOT NULL,
    [RodzajDok]                       VARCHAR (4)     NULL,
    [Identyfikator]                   VARCHAR (40)    NULL,
    [WersjaXML]                       VARCHAR (7)     NULL,
    [DataPrzeslania]                  DATETIME        NULL,
    [UrzadRejestracji]                VARCHAR (8)     NULL,
    [UrzadRejestracjiPid]             INT             NULL,
    [PasRejestracji]                  CHAR (2)        NULL,
    [Status]                          CHAR (1)        NULL,
    [IdJedn]                          VARCHAR (8)     NULL,
    [IdJednPid]                       INT             NULL,
    [NrCelina]                        VARCHAR (40)    NULL,
    [DataPrzyjecia]                   DATETIME        NULL,
    [Decyzja]                         CHAR (1)        NULL,
    [TerminOdpowiedzi]                DATETIME        NULL,
    [Zefir]                           CHAR (1)        NULL,
    [CzyZbiorcze]                     BIT             NULL,
    [NrWlasny]                        VARCHAR (14)    NULL,
    [Miejsce]                         VARCHAR (35)    NULL,
    [Data]                            DATETIME        NULL,
    [TowarLokalizacja]                VARCHAR (17)    NULL,
    [TerminDostarczenia]              DATETIME        NULL,
    [MasaBrutto]                      DECIMAL (14, 3) NULL,
    [TranzytRodzaj]                   VARCHAR (4)     NULL,
    [TranzytRodzajPid]                INT             NULL,
    [LiczbaOpakowan]                  INT             NULL,
    [Procedura]                       CHAR (2)        NULL,
    [ProceduraPid]                    INT             NULL,
    [WartoscStatystyczna]             BIGINT          NULL,
    [SprostowanieNrCelina]            VARCHAR (40)    NULL,
    [SprostowanieNr]                  SMALLINT        NULL,
    [SprostowanieData]                DATETIME        NULL,
    [ZamkniecieIlosc]                 SMALLINT        NULL,
    [ZamkniecieZdejmujacy]            VARCHAR (35)    NULL,
    [IdSkladajacy]                    INT             NULL,
    [IdUpowazniony]                   INT             NULL,
    [IdZglaszajacyPrzedstawiciel]     INT             NULL,
    [IdZglaszajacyPrzedstawicielEORI] INT             NULL,
    CONSTRAINT [PK_PWD_Dokument] PRIMARY KEY CLUSTERED ([IdDok] ASC)
);

