CREATE TABLE [zc].[SAD_Towar] (
    [IdDok]                   BIGINT          NOT NULL,
    [IdPozycji]               SMALLINT        NOT NULL,
    [P1c]                     VARCHAR (5)     NULL,
    [KrajWysylki]             CHAR (2)        NULL,
    [KrajWysylkiPid]          INT             NULL,
    [KrajPrzeznaczenia]       CHAR (2)        NULL,
    [KrajPrzeznaczeniaPid]    INT             NULL,
    [MasaBrutto]              DECIMAL (14, 3) NULL,
    [IdOdbiorca]              INT             NULL,
    [IdNadawca]               INT             NULL,
    [KodTowarowy]             VARCHAR (8)     NULL,
    [KodTowarowyPid]          INT             NULL,
    [KodTaric]                CHAR (2)        NULL,
    [KrajPochodzenia]         CHAR (2)        NULL,
    [KrajPochodzeniaPid]      INT             NULL,
    [Preferencje]             CHAR (3)        NULL,
    [PreferencjePid]          INT             NULL,
    [ProceduraBiezaca]        VARCHAR (4)     NULL,
    [ProceduraBiezacaPid]     INT             NULL,
    [ProceduraPoprzednia]     VARCHAR (4)     NULL,
    [ProceduraPoprzedniaPid]  INT             NULL,
    [ProceduraSzczegoly]      CHAR (3)        NULL,
    [ProceduraSzczegolyPid]   INT             NULL,
    [MasaNetto]               DECIMAL (14, 3) NULL,
    [IloscTowaruUjm]          DECIMAL (14, 3) NULL,
    [WartoscPozycji]          DECIMAL (17, 2) NULL,
    [MetodaWartosciowania]    CHAR (1)        NULL,
    [MetodaWartosciowaniaPid] INT             NULL,
    [WartoscStatystyczna]     BIGINT          NULL,
    [OpisTowaru]              VARCHAR (1000)  NULL,
    [SamochodMarka]           CHAR (3)        NULL,
    [SamochodMarkaPid]        INT             NULL,
    [SamochodNrNadwozia]      VARCHAR (35)    NULL,
    [SamochodNrSilnika]       VARCHAR (35)    NULL,
    [SamochodPojemnosc]       INT             NULL,
    [SamochodRodzajPaliwa]    CHAR (2)        NULL,
    [SamochodRodzajPaliwaPid] INT             NULL,
    [SamochodRokProdukcji]    INT             NULL,
    CONSTRAINT [PK_SAD_Towar] PRIMARY KEY CLUSTERED ([IdDok] ASC, [IdPozycji] ASC)
);

