CREATE TABLE [akc].[AKC4_Deklaracja] (
    [IdDok]                                        VARCHAR (30)    NOT NULL,
    [IdKomorki]                                    VARCHAR (20)    NULL,
    [IdKomorkiPid]                                 INT             NULL,
    [IdPodmiotu]                                   INT             NULL,
    [RodzajDokumentu]                              CHAR (4)        NULL,
    [NumerDokumentu]                               VARCHAR (30)    NULL,
    [IdDokStowarzysz]                              VARCHAR (30)    NULL,
    [NumerDokumentuStowarzysz]                     VARCHAR (30)    NULL,
    [IzbaCelnaZlozeniaDok]                         VARCHAR (20)    NULL,
    [IzbaCelnaZlozeniaDokPid]                      INT             NULL,
    [MiejsceZlozeniaDok]                           VARCHAR (20)    NULL,
    [MiejsceZlozeniaDokPid]                        INT             NULL,
    [RokZlozeniaDok]                               SMALLINT        NULL,
    [ZnacznikKorekty]                              SMALLINT        NULL,
    [DataRejestrDokWSyst]                          DATETIME        NULL,
    [DataWplywuDok]                                DATE            NULL,
    [Status]                                       CHAR (1)        NULL,
    [DeklaracjaZaOkres]                            DATE            NULL,
    [RazemPodatekAkcyzowy]                         DECIMAL (19, 2) NULL,
    [WartoscZnakowAkcyzy]                          DECIMAL (19, 2) NULL,
    [KwotaWplatDziennych]                          DECIMAL (19, 2) NULL,
    [KwotaWplatMiesiecznych]                       DECIMAL (19, 2) NULL,
    [KwotaPrzedplatyAkcyzy]                        DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozliczOstatDeklar]              DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozliczPrzedplataAkcOstatDeklar] DECIMAL (19, 2) NULL,
    [DoZaplaty]                                    DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozlicz]                         DECIMAL (19, 2) NULL,
    [NadwyzWplatDoRozliczPrzedplataAkc]            DECIMAL (19, 2) NULL,
    [CzyKorektaWewnetrzna]                         BIT             NULL,
    [CzyKorektaZurzedu]                            BIT             NULL,
    [TerminPlatnosci]                              DATE            NULL,
    [DeklaracjaZerowa]                             CHAR (3)        NOT NULL,
    [DataZlozeniaDeklaracjiPierwotnej]             DATE            NULL,
    [CzyOstatniaWersjaDeklaracji]                  BIT             NULL,
    [DataZlozeniaDok]                              DATETIME        NULL,
    CONSTRAINT [PK_AKC4_Deklaracja] PRIMARY KEY CLUSTERED ([IdDok] ASC)
);

