CREATE TABLE [akc].[AKCU_Deklaracja] (
    [IdDok]                            VARCHAR (30)    NOT NULL,
    [IdKomorki]                        VARCHAR (20)    NULL,
    [IdKomorkiPid]                     INT             NULL,
    [IdPodmiotu]                       INT             NULL,
    [RodzajDokumentu]                  CHAR (4)        NULL,
    [NumerDokumentu]                   VARCHAR (30)    NULL,
    [IdDokStowarzysz]                  VARCHAR (30)    NULL,
    [NumerDokumentuStowarzysz]         VARCHAR (30)    NULL,
    [IzbaCelnaZlozeniaDok]             VARCHAR (20)    NULL,
    [IzbaCelnaZlozeniaDokPid]          INT             NULL,
    [MiejsceZlozeniaDok]               VARCHAR (20)    NULL,
    [MiejsceZlozeniaDokPid]            INT             NULL,
    [RokZlozeniaDok]                   SMALLINT        NULL,
    [ZnacznikKorekty]                  SMALLINT        NULL,
    [Status]                           CHAR (1)        NULL,
    [SystemowyNumerDok]                INT             NULL,
    [DataRejestrDokWSyst]              DATETIME        NULL,
    [DataZamkniecia]                   DATE            NULL,
    [DataZlozeniaDok]                  DATE            NULL,
    [DataWplywuDok]                    DATE            NULL,
    [TerminPlatnosci]                  DATE            NULL,
    [NumerPaczki]                      VARCHAR (30)    NULL,
    [RazemPodatekAkcyzowy]             DECIMAL (19, 2) NULL,
    [ZwolnieniaObnizenia]              DECIMAL (19, 2) NULL,
    [KwotaZnakowAkcyzy]                DECIMAL (19, 2) NULL,
    [DoZaplaty]                        DECIMAL (19, 2) NULL,
    [DataZlozeniaDeklaracjiPierwotnej] DATE            NULL,
    [CzyOstatniaWersjaDeklaracji]      BIT             NULL,
    CONSTRAINT [PK_AKCU_Deklaracja] PRIMARY KEY CLUSTERED ([IdDok] ASC)
);

