CREATE TABLE [akc].[INF_Informacja_J] (
    [IdDok]                                   VARCHAR (30)    NOT NULL,
    [IdKomorki]                               VARCHAR (20)    NULL,
    [IdPodmiotu]                              INT             NULL,
    [RodzajInformacji]                        CHAR (1)        NOT NULL,
    [RodzajDokumentu]                         CHAR (4)        NULL,
    [NumerDokumentu]                          VARCHAR (30)    NULL,
    [NumerZalacznika]                         INT             NOT NULL,
    [NumerAkcyzowy]                           VARCHAR (40)    NULL,
    [IzbaCelnaZlozeniaDok]                    VARCHAR (20)    NULL,
    [MiejsceZlozeniaDok]                      VARCHAR (20)    NULL,
    [ZnacznikKorekty]                         SMALLINT        NULL,
    [Status]                                  CHAR (1)        NULL,
    [OkresSprawozdawczy]                      DATE            NULL,
    [DataRejestrDokWSyst]                     DATETIME        NULL,
    [DataZlozeniaDok]                         DATE            NULL,
    [DataWplywuDok]                           DATE            NULL,
    [ZapasPoczatkowyTysKg]                    DECIMAL (19, 3) NULL,
    [KwotaOdpowZapasPoczatk]                  DECIMAL (19, 3) NULL,
    [IloscWyrobPrzyjetaNaSkladTysKg]          DECIMAL (19, 3) NULL,
    [IloscWyprodukWyrobAkcTysKg]              DECIMAL (19, 3) NULL,
    [IloscWyrobZuzytychDoProdTysKg]           DECIMAL (19, 3) NULL,
    [IloscWyrobZeSkladTysKg]                  DECIMAL (19, 3) NULL,
    [IloscWyrobZeSkladWprocedZawieszTysKg]    DECIMAL (19, 3) NULL,
    [IloscWyrobZeSkladPozaProcedZawieszTysKg] DECIMAL (19, 3) NULL,
    [UbytkiCalkowZniszczTysKg]                DECIMAL (19, 3) NULL,
    [ZapasKoncowyTysKg]                       DECIMAL (19, 3) NULL,
    [KwotaOdpowZapasKoncow]                   DECIMAL (19, 3) NULL,
    [ZapasPoczatkowyGJ]                       DECIMAL (19, 3) NULL,
    [IloscWyrobPrzyjetaNaSkladGJ]             DECIMAL (19, 3) NULL,
    [IloscWyprodukWyrobAkcGJ]                 DECIMAL (19, 3) NULL,
    [IloscWyrobZuzytychDoProdGJ]              DECIMAL (19, 3) NULL,
    [IloscWyrobZeSkladGJ]                     DECIMAL (19, 3) NULL,
    [IloscWyrobZeSkladWprocedZawieszGJ]       DECIMAL (19, 3) NULL,
    [IloscWyrobZeSkladPozaProcedZawieszGJ]    DECIMAL (19, 3) NULL,
    [UbytkiCalkowZniszczGJ]                   DECIMAL (19, 3) NULL,
    [ZapasKoncowyGJ]                          DECIMAL (19, 3) NULL,
    [DataZlozeniaDeklaracjiPierwotnej]        DATE            NULL,
    [CzyOstatniaWersjaDeklaracji]             BIT             NULL,
    CONSTRAINT [PK_INF_Informacja_J] PRIMARY KEY CLUSTERED ([IdDok] ASC, [NumerZalacznika] ASC)
);

