CREATE TABLE [zef2].[AtrybutyKlasyfikacji] (
    [KodAtrybutu]                       NVARCHAR (10)  NULL,
    [Nazwa]                             NVARCHAR (256) NULL,
    [CzyZablokowane]                    INT            NULL,
    [TypAtrybutuKlasyfikacji]           INT            NULL,
    [RodzajWydatku]                     INT            NULL,
    [OdwolanieDoAtrybutuNadrzednego]    BIGINT         NULL,
    [CzyWymaganyProgram]                INT            NULL,
    [CzyWymaganyProjekt]                INT            NULL,
    [KodGrupyZatrudnienia]              BIGINT         NULL,
    [GrupaEkonomicznaOgolna]            BIGINT         NULL,
    [CzyWidocznyWWymiarze]              INT            NULL,
    [RodzajBudzetu]                     BIGINT         NULL,
    [DataGodzOstatnModyfikacji]         DATETIME       NULL,
    [IdUzytkownikaOstatnModyfikujacego] NVARCHAR (8)   NULL,
    [IdTransakcjiModyfikacji]           BIGINT         NULL,
    [DataGodzUtworzeniaRekordu]         DATETIME       NULL,
    [IdUzytkownikaTworzacego]           NVARCHAR (8)   NULL,
    [IdTransakcjiUtworzeniaRekordu]     BIGINT         NULL,
    [WersjaRekordu]                     INT            NULL,
    [Partycja]                          BIGINT         NULL,
    [IdentyfikatorRekordu]              BIGINT         NOT NULL,
    [CzyWymaganaGrupaZatrDlaLimitow]    INT            NULL,
    [CzyRozdzialMacierzystyIC]          INT            NULL,
    [CzyRozdzialMacierzystyIS]          INT            NULL,
    [CzyRozdzialMacierzystyUKS]         INT            NULL,
    [operacja]                          NVARCHAR (1)   NULL,
    CONSTRAINT [AtrybutyKlasyfikacji_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC),
    CHECK ([IdentyfikatorRekordu]<>(0))
);

