CREATE TABLE [zef2].[DefinicjaPolaSprawozdania] (
    [EtykietaPola]                      NVARCHAR (80)    NULL,
    [CzyDoEdycji]                       INT              NULL,
    [IndeksPola]                        INT              NULL,
    [Sekwencja]                         INT              NULL,
    [CzyPlanFinansowy]                  INT              NULL,
    [CzyWykonanie]                      INT              NULL,
    [CzyWyliczeniowe]                   INT              NULL,
    [TagXML]                            NVARCHAR (50)    NULL,
    [PoleSumowane]                      NVARCHAR (120)   NULL,
    [KodWiersza]                        NVARCHAR (10)    NULL,
    [IdentyfikatorSprawozdania]         BIGINT           NULL,
    [DataGodzOstatnModyfikacji]         DATETIME         NULL,
    [IdUzytkownikaOstatnModyfikujacego] NVARCHAR (8)     NULL,
    [IdTransakcjiModyfikacji]           BIGINT           NULL,
    [DataGodzUtworzenia]                DATETIME         NULL,
    [IdUzytkownikaTworzacego]           NVARCHAR (8)     NULL,
    [IdTransakcjiUtworzeniaRekordu]     BIGINT           NULL,
    [WersjaRekordu]                     INT              NULL,
    [Partycja]                          BIGINT           NULL,
    [IdentyfikatorRekordu]              BIGINT           NOT NULL,
    [TagMRDOS]                          NVARCHAR (30)    NULL,
    [Zaokraglenie]                      NUMERIC (32, 16) NULL,
    [CzyWykluczZTrezora]                INT              NULL,
    [operacja]                          NVARCHAR (1)     NULL,
    CONSTRAINT [DefinicjaPolaSprawozdania_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC),
    CHECK ([IdentyfikatorRekordu]<>(0))
);

