CREATE TABLE [zef2].[DefinicjaEtapowZatwierdzen] (
    [WartoscStanu]                               NVARCHAR (20)    NOT NULL,
    [CzyGotowyDoKsiegowania]                     INT              NULL,
    [Grupa]                                      NVARCHAR (10)    NULL,
    [CzySprawdzArkusz]                           INT              NULL,
    [CzyEdycja]                                  INT              NULL,
    [GrupaZatwierdzen]                           NVARCHAR (10)    NOT NULL,
    [CzyZatwierdzenieZaksiegowanie]              INT              NULL,
    [Sekwencja]                                  INT              NULL,
    [AkceptacjaOdKwoty]                          NUMERIC (32, 16) NULL,
    [AkceptacjaDoKwoty]                          NUMERIC (32, 16) NULL,
    [CzyGotowyDoAkceptacjiCRU]                   INT              NULL,
    [CzyKasowanieUmowyCRU]                       INT              NULL,
    [CzyZatwierdzony]                            INT              NULL,
    [CzyWyslanoDoJednostkiNadrzednej]            INT              NULL,
    [CzyAktywneAnulowanie]                       INT              NULL,
    [CzyPrzekazaneDoNadrzednego]                 INT              NULL,
    [CzyPrzekazaneDoPodrzednego]                 INT              NULL,
    [GrupaUprawnionaDoEdytowania]                NVARCHAR (10)    NULL,
    [CzyWygenerowaneDoTrezora]                   INT              NULL,
    [CzyZerowanieStatusu]                        INT              NULL,
    [GrupaUprawnionaDoZerowaniaStatusuDok]       NVARCHAR (10)    NULL,
    [GrupaUprawnionaDoCofnieciaStatusuDok]       NVARCHAR (10)    NULL,
    [CzyCofanieDoPoprzStatusu]                   INT              NULL,
    [CzyWylaczenieMozliwosciZmianyStatusu]       INT              NULL,
    [CzyKomentarzPrzyUstawianiuNaTenStatus]      INT              NULL,
    [CzyKomentarzPrzyCofaniuZTegoStatus]         INT              NULL,
    [CzyKomentarzPrzyZerowaniuZTegoStatus]       INT              NULL,
    [CzyPrzekazaneDoDecyzji]                     INT              NULL,
    [CzyPrzekazaneDoDecyzjiNadrzednego]          INT              NULL,
    [CzyBladPrzerywaPrzetwarzanie]               INT              NULL,
    [AutomatycznyStatusNastepny]                 NVARCHAR (20)    NULL,
    [CzyNiePrzerywacPrzetwarzanieJesliBladPlanu] INT              NULL,
    [CzyEdycjaDatyKsiegowania]                   INT              NULL,
    [CzyAutomatycznaAkceptacja]                  INT              NULL,
    [CzyCofnieteZJednostkiNadrzednej]            INT              NULL,
    [CzyPrzyjete]                                INT              NULL,
    [CzySprawdzacCzyPrzyjete]                    INT              NULL,
    [AutomatycznyStatusPoczatkowy]               INT              NULL,
    [DataGodzOstatnModyfikacji]                  DATETIME         NULL,
    [IdUzytkownikaOstatnModyfikujacego]          NVARCHAR (8)     NULL,
    [IdTransakcjiModyfikacji]                    BIGINT           NULL,
    [DataGodzUtworzeniaRekordu]                  DATETIME         NULL,
    [IdUzytkownikaTworzacego]                    NVARCHAR (8)     NULL,
    [IdTransakcjiUtworzeniaRekordu]              BIGINT           NULL,
    [WersjaRekordu]                              INT              NULL,
    [Partycja]                                   BIGINT           NOT NULL,
    [IdentyfikatorRekordu]                       BIGINT           NULL,
    [CzyAnulowanieWniosku]                       INT              NULL,
    [CzyEdycjaPolaPrzetarg]                      INT              NULL,
    [CzyJednostkaInicjujaca]                     INT              NULL,
    [CzyJednostkaPotwierdzajaca]                 INT              NULL,
    [WartoscStanuZewnetrzna]                     NVARCHAR (20)    NULL,
    [CzyAktywnaListaWeryfikacyjna]               INT              NULL,
    [ListaWeryfikacyjnaDefinicjaDlaGrupy]        NVARCHAR (10)    NULL,
    [CzyEdycjaZleceniaDoKasy]                    INT              NULL,
    [CzyPrzyjety]                                INT              NULL,
    [operacja]                                   NVARCHAR (1)     NULL,
    CONSTRAINT [DefinicjaEtapowZatwierdzen_pk] PRIMARY KEY CLUSTERED ([Partycja] ASC, [GrupaZatwierdzen] ASC, [WartoscStanu] ASC),
    CHECK ([IdentyfikatorRekordu]<>(0))
);

