CREATE TABLE [zef2].[DefinicjaSprawozdania] (
    [CzyGenerowaneAutomatyczne]             INT            NULL,
    [CzyZablokowane]                        INT            NULL,
    [PlanTylkoDlaNiezerowych]               INT            NULL,
    [Klasa]                                 NVARCHAR (40)  NULL,
    [IdUzytkownikaTworzacego]               NVARCHAR (8)   NULL,
    [DataGodzUtworzeniaRekordu]             DATETIME       NULL,
    [IdTransakcjiUtworzeniaRekordu]         BIGINT         NULL,
    [NazwaKlasy]                            NVARCHAR (40)  NULL,
    [ObowiazujeOd]                          DATETIME       NULL,
    [DomyslnyTypSprawozdZbiorczego]         BIGINT         NULL,
    [DomyslnyTypSprawozdSkonsolidowanego]   BIGINT         NULL,
    [DomyslnyTypSprawozd]                   BIGINT         NULL,
    [Opis]                                  INT            NULL,
    [TypDokumentu]                          NVARCHAR (10)  NULL,
    [CzyDynamiczneWiersze]                  INT            NULL,
    [GrupyZatrudnienia]                     INT            NULL,
    [IndeksPola]                            INT            NULL,
    [JednostkaNadrzedna]                    BIGINT         NULL,
    [SeriaSprawozdZbiorczych]               NVARCHAR (15)  NULL,
    [IdentyfikatorWersjiSprawozdania]       NVARCHAR (10)  NULL,
    [KodGrupyDefinicji]                     BIGINT         NULL,
    [TypSprawozdania]                       INT            NULL,
    [WymaganaKlasyfikacja]                  INT            NULL,
    [IdUzytkownikaOstatnModyfikujacego]     NVARCHAR (8)   NULL,
    [DataGodzOstatnModyfikacji]             DATETIME       NULL,
    [IdTransakcjiModyfikacji]               BIGINT         NULL,
    [CzyImportMRDOS]                        INT            NULL,
    [CzyParagraf]                           INT            NULL,
    [Partycja]                              BIGINT         NULL,
    [CzyCzesc]                              INT            NULL,
    [Czesc]                                 INT            NULL,
    [PoziomKsiegowania]                     INT            NULL,
    [CzyKsiegowaneNaKonta]                  INT            NULL,
    [CzyKsiegowanieDoTransakcjiFinansowych] INT            NULL,
    [CzyKodProgramu]                        INT            NULL,
    [CzyDostepnyKodProjektu]                INT            NULL,
    [TypDokumentuChronionego]               NVARCHAR (10)  NULL,
    [IdentyfikatorRekordu]                  BIGINT         NOT NULL,
    [Adresat]                               NVARCHAR (100) NULL,
    [WersjaRekordu]                         INT            NULL,
    [CzyKolumnaUwagi]                       INT            NULL,
    [NazwaElementuMenu]                     NVARCHAR (40)  NULL,
    [CzyKodWiersza]                         INT            NULL,
    [CzyDzial]                              INT            NULL,
    [CzyRozdzial]                           INT            NULL,
    [NazwaKlasyImportuTrezor]               NVARCHAR (40)  NULL,
    [SeriaZalacznikow]                      NVARCHAR (15)  NULL,
    [CzyDzialanie]                          INT            NULL,
    [DokumentXML]                           NVARCHAR (40)  NULL,
    [PrzedzialXML]                          INT            NULL,
    [DokumentPodrzednyXML]                  INT            NULL,
    [TAGXML]                                NVARCHAR (50)  NULL,
    [operacja]                              NVARCHAR (1)   NULL,
    CONSTRAINT [DefinicjaSprawozdania_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC),
    CHECK ([IdentyfikatorRekordu]<>(0))
);

