CREATE TABLE [zef2].[GrupaDefinicjiSprawozdan] (
    [IdentyfikatorRekordu]              BIGINT         NOT NULL,
    [TypDefSprawozdania]                NVARCHAR (15)  NULL,
    [Opis]                              NVARCHAR (255) NULL,
    [TypSprawozdania]                   INT            NULL,
    [RodzajSprawozdania]                NVARCHAR (20)  NULL,
    [TypJednostkiSprawozdania]          INT            NULL,
    [RodzajOkresu]                      INT            NULL,
    [RodzajDokMRDOS]                    NVARCHAR (20)  NULL,
    [CzyImportMRDOS]                    INT            NULL,
    [CzySprawozdKonsolidacyjne]         INT            NULL,
    [Modul]                             INT            NULL,
    [CzyNaWszystkieIzby]                INT            NULL,
    [KodDokumentu]                      NVARCHAR (10)  NULL,
    [CzyWysylkaDoTrezora]               INT            NULL,
    [KodProcesuTrezor]                  NVARCHAR (20)  NULL,
    [IdUzytkownikaTworzacego]           NVARCHAR (8)   NULL,
    [DataGodzUtworzeniaRekordu]         DATETIME       NULL,
    [IdTransakcjiUtworzeniaRekordu]     BIGINT         NULL,
    [IdUzytkownikaOstatnModyfikujacego] NVARCHAR (8)   NULL,
    [DataGodzOstatnModyfikacji]         DATETIME       NULL,
    [IdTransakcjiModyfikacji]           BIGINT         NULL,
    [GrupaUzytkowWidocznosciSprawozd]   NVARCHAR (10)  NULL,
    [WersjaRekordu]                     INT            NULL,
    [Partycja]                          BIGINT         NULL,
    [operacja]                          NVARCHAR (1)   NULL,
    CONSTRAINT [GrupaDefinicjiSprawozdan_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC),
    CHECK ([IdentyfikatorRekordu]<>(0))
);

