CREATE TABLE [zef2].[JednostkiOrganizacyjne] (
    [IdentyfikatorRekordu]              BIGINT         NOT NULL,
    [KodJednostki]                      NVARCHAR (10)  NULL,
    [Nazwa]                             NVARCHAR (256) NULL,
    [CzyZablokowane]                    INT            NULL,
    [CzyDysponentIstopnia]              INT            NULL,
    [CzyDysponentIIstopnia]             INT            NULL,
    [CzyDysponentIIIstopnia]            INT            NULL,
    [CzyDysponentIVstopnia]             INT            NULL,
    [CzyDysponentVstopnia]              INT            NULL,
    [JednostkaNadrzedna]                BIGINT         NULL,
    [Firma]                             NVARCHAR (4)   NULL,
    [PionMF]                            BIGINT         NULL,
    [CzyOrganEgzekucyjny]               INT            NULL,
    [KodDysponenta]                     NVARCHAR (10)  NULL,
    [Czesc]                             INT            NULL,
    [CzyOrganPodatkowy]                 INT            NULL,
    [KodDysponentaOrganPodatkowy]       NVARCHAR (10)  NULL,
    [IdentyfikatorDanychAdresowych]     BIGINT         NULL,
    [AdresDecyzjiNaOdsetki]             NVARCHAR (80)  NULL,
    [SzablonEmailZadaniaZaplaty]        NVARCHAR (10)  NULL,
    [AdresEgzekucji]                    NVARCHAR (80)  NULL,
    [UzytkownicyEgzekucji]              NVARCHAR (80)  NULL,
    [NazwaSprawozdania]                 NVARCHAR (120) NULL,
    [REGON]                             NVARCHAR (15)  NULL,
    [CzyWidocznyWwymiarze]              INT            NULL,
    [NazwaNaWydrukuTytulu]              NVARCHAR (256) NULL,
    [SzablonEmailWniosekOzarachowanie]  NVARCHAR (10)  NULL,
    [AdresWnioskuOzarachowanie]         NVARCHAR (80)  NULL,
    [NumeracjaOdbiorcy]                 BIGINT         NULL,
    [KontoOdbiorcy]                     NVARCHAR (20)  NULL,
    [CzyWidocznyNaZarzadzZab]           INT            NULL,
    [SkrotDysponentaMF]                 NVARCHAR (16)  NULL,
    [CzyJestAdresatem]                  INT            NULL,
    [NazwaLimity]                       NVARCHAR (256) NULL,
    [IdentyfikatorDanychKontaktowych]   BIGINT         NULL,
    [KodJednBudzetTrezor]               NVARCHAR (10)  NULL,
    [DataGodzOstatnModyfikacji]         DATETIME       NULL,
    [IdUzytkownikaOstatnModyfikujacego] NVARCHAR (8)   NULL,
    [IdTransakcjiModyfikacji]           BIGINT         NULL,
    [DataGodzUtworzeniaRekordu]         DATETIME       NULL,
    [IdUzytkownikaTworzacego]           NVARCHAR (8)   NULL,
    [IdTransakcjiUtworzeniaRekordu]     BIGINT         NULL,
    [WersjaRekordu]                     INT            NULL,
    [Partycja]                          BIGINT         NULL,
    [operacja]                          NVARCHAR (1)   NULL,
    CONSTRAINT [JednostkiOrganizacyjne_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC),
    CHECK ([IdentyfikatorRekordu]<>(0))
);

