CREATE TABLE [zef].[dok_akc3z] (
    [id_dok]        VARCHAR (30)    NOT NULL,
    [zalacznik]     CHAR (1)        NOT NULL,
    [nr_zal]        INT             NOT NULL,
    [numer]         VARCHAR (10)    NULL,
    [seed_id_komor] VARCHAR (20)    NULL,
    [seed_id_kontr] NUMERIC (10)    NULL,
    [p_7]           DECIMAL (20, 3) NULL,
    [p_8]           DECIMAL (20, 3) NULL,
    [p_9]           DECIMAL (20, 3) NULL,
    [p_10]          DECIMAL (20, 3) NULL,
    [p_11]          DECIMAL (20, 3) NULL,
    [p_12]          DECIMAL (20, 3) NULL,
    [p_13]          DECIMAL (20, 3) NULL,
    [p_14]          DECIMAL (20, 3) NULL,
    [p_15]          DECIMAL (20, 3) NULL,
    [p_16]          DECIMAL (20, 3) NULL,
    [p_17]          DECIMAL (20, 3) NULL,
    [p_18]          DECIMAL (20, 3) NULL,
    [p_19]          DECIMAL (20, 3) NULL,
    [p_20]          DECIMAL (20, 3) NULL,
    [p_21]          DECIMAL (20, 3) NULL,
    [p_22]          DECIMAL (20, 3) NULL,
    [p_23]          DECIMAL (20, 3) NULL,
    [p_24]          DECIMAL (20, 3) NULL,
    [rodzaj]        VARCHAR (10)    NULL,
    CONSTRAINT [PK_DOK_AKC3Z] PRIMARY KEY CLUSTERED ([id_dok] ASC, [zalacznik] ASC, [nr_zal] ASC)
);

