CREATE TABLE [zef].[dok_ainf] (
    [id_dok]          VARCHAR (30) NOT NULL,
    [status]          VARCHAR (6)  NULL,
    [dekl_za]         DATETIME     NULL,
    [us_id_komor]     VARCHAR (20) NULL,
    [us_id_kontr]     NUMERIC (10) NULL,
    [us_id_centr]     NUMERIC (10) NULL,
    [dz_tyt_plat]     VARCHAR (9)  NULL,
    [dz_klasyf_budz]  VARCHAR (9)  NULL,
    [rep_id_komor]    VARCHAR (20) NULL,
    [rep_id_kontr]    NUMERIC (10) NULL,
    [rep_id_centr]    NUMERIC (10) NULL,
    [dat_wypel]       DATETIME     NULL,
    [dat_wplywu]      DATETIME     NULL,
    [term_plat]       DATETIME     NULL,
    [nr_paczki]       VARCHAR (30) NULL,
    [czy_wewn]        CHAR (1)     NULL,
    [seed_id_komor]   VARCHAR (20) NULL,
    [seed_id_kontr]   NUMERIC (10) NULL,
    [form_plat]       VARCHAR (6)  NULL,
    [korekta_pod]     CHAR (1)     NULL,
    [dat_powst_dlugu] DATETIME     NULL,
    [termin]          INT          NULL,
    CONSTRAINT [PK_DOK_AINF] PRIMARY KEY CLUSTERED ([id_dok] ASC)
);

