CREATE TABLE [zef].[dok_tytwyk] (
    [id_dok]          VARCHAR (30)    NOT NULL,
    [organ_egzek]     VARCHAR (60)    NULL,
    [nr_dok_spraw]    VARCHAR (30)    NULL,
    [rok_okres]       CHAR (8)        NULL,
    [naleznosc]       NUMERIC (20, 2) NULL,
    [data_nal_odset]  DATETIME        NULL,
    [rodz_nal]        VARCHAR (40)    NULL,
    [podst_praw]      VARCHAR (100)   NULL,
    [rodz_odset]      CHAR (1)        NULL,
    [proc_odset1]     NUMERIC (6, 2)  DEFAULT ((0)) NULL,
    [proc_odset2]     NUMERIC (6, 2)  DEFAULT ((0)) NULL,
    [podst_praw_34]   VARCHAR (255)   NULL,
    [podst_praw_56]   VARCHAR (255)   NULL,
    [podst_praw_37]   VARCHAR (80)    NULL,
    [form_plat]       CHAR (6)        NULL,
    [rodz_egzek]      CHAR (6)        NULL,
    [tresc_egz]       TEXT            NULL,
    [nr_upom]         VARCHAR (30)    NULL,
    [dat_dost_upom]   DATETIME        NULL,
    [koszt_upom]      NUMERIC (20, 2) NULL,
    [sposob_zapl]     CHAR (1)        NULL,
    [data_wnios]      DATETIME        NULL,
    [data_post]       DATETIME        NULL,
    [rok_okres2]      CHAR (8)        NULL,
    [rok_okres3]      CHAR (8)        NULL,
    [rok_okres4]      CHAR (8)        NULL,
    [naleznosc2]      NUMERIC (20, 2) NULL,
    [naleznosc3]      NUMERIC (20, 2) NULL,
    [naleznosc4]      NUMERIC (20, 2) NULL,
    [data_nal_odset2] DATETIME        NULL,
    [data_nal_odset3] DATETIME        NULL,
    [data_nal_odset4] DATETIME        NULL,
    [nal_zabezp]      CHAR (1)        NULL,
    [zabezp_forma]    VARCHAR (255)   NULL,
    [id_konta_wierz]  VARCHAR (10)    NULL,
    [podst_praw_30]   CHAR (1)        NULL,
    [rodzaj_nal]      VARCHAR (40)    NULL,
    [rodzaj_nal2]     VARCHAR (40)    NULL,
    [rodzaj_nal3]     VARCHAR (40)    NULL,
    [rodzaj_nal4]     VARCHAR (40)    NULL,
    [id_jedn]         VARCHAR (20)    NULL,
    [kwot_ods]        NUMERIC (20, 2) DEFAULT ((0)) NULL,
    [kwot_ods2]       NUMERIC (20, 2) DEFAULT ((0)) NULL,
    [kwot_ods3]       NUMERIC (20, 2) DEFAULT ((0)) NULL,
    [kwot_ods4]       NUMERIC (20, 2) DEFAULT ((0)) NULL,
    [bank_wierz]      VARCHAR (80)    NULL,
    [konto_wierz]     VARCHAR (60)    NULL,
    [data_zaw_od]     DATETIME        NULL,
    [data_zaw_do]     DATETIME        NULL,
    [data_zaw_od2]    DATETIME        NULL,
    [data_zaw_do2]    DATETIME        NULL,
    [data_zaw_od3]    DATETIME        NULL,
    [data_zaw_do3]    DATETIME        NULL,
    [flg_zaw]         CHAR (1)        DEFAULT ('Y') NULL,
    [flg_zob]         CHAR (1)        NULL,
    [id_komor]        VARCHAR (20)    NULL,
    [id_kontr]        DECIMAL (10)    NULL,
    [id_dok_pierw]    VARCHAR (30)    NULL,
    [nr_dok_pierw]    VARCHAR (30)    NULL,
    CONSTRAINT [PK_DOK_TYTWYK] PRIMARY KEY CLUSTERED ([id_dok] ASC)
);

