CREATE TABLE [zef].[dok_akc] (
    [id_dok]          VARCHAR (30)    NOT NULL,
    [status]          VARCHAR (6)     NULL,
    [dekl_za]         DATETIME        NULL,
    [us_id_kontr]     NUMERIC (10)    NULL,
    [us_id_komor]     VARCHAR (20)    NULL,
    [us_id_centr]     NUMERIC (10)    NULL,
    [akca_og]         NUMERIC (20, 2) NULL,
    [akcb_og]         NUMERIC (20, 2) NULL,
    [akcc_og]         NUMERIC (20, 2) NULL,
    [akcd_og]         NUMERIC (20, 2) NULL,
    [akce_og]         NUMERIC (20, 2) NULL,
    [akcf_og]         NUMERIC (20, 2) NULL,
    [akcg_og]         NUMERIC (20, 2) NULL,
    [akch_og]         NUMERIC (20, 2) NULL,
    [akc_og]          NUMERIC (20, 2) NULL,
    [zal_zs]          NUMERIC (20, 2) NULL,
    [nal_kw_wd]       NUMERIC (20, 2) NULL,
    [kw_nadw]         NUMERIC (20, 2) NULL,
    [kw_nadw_pm]      NUMERIC (20, 2) NULL,
    [do_zaplaty]      NUMERIC (20, 2) NULL,
    [dz_tyt_plat]     VARCHAR (9)     NULL,
    [dz_klasyf_budz]  VARCHAR (9)     NULL,
    [nadw_wpl]        NUMERIC (20, 2) NULL,
    [rep_id_kontr]    NUMERIC (10)    NULL,
    [rep_id_komor]    VARCHAR (20)    NULL,
    [rep_id_centr]    NUMERIC (10)    NULL,
    [dat_wypel]       DATETIME        NULL,
    [dat_wplywu]      DATETIME        NULL,
    [term_plat]       DATETIME        NULL,
    [nr_paczki]       VARCHAR (30)    NULL,
    [czy_wewn]        CHAR (1)        NULL,
    [akci_og]         NUMERIC (20, 2) NULL,
    [akcj_og]         NUMERIC (20, 2) NULL,
    [seed_id_kontr]   NUMERIC (10)    NULL,
    [seed_id_komor]   VARCHAR (20)    NULL,
    [form_plat]       VARCHAR (6)     NULL,
    [korekta_pod]     CHAR (1)        NULL,
    [dat_powst_dlugu] DATETIME        NULL,
    [termin]          INT             NULL,
    [akck_og]         NUMERIC (20, 2) NULL,
    [kw_nadw_pm_pa]   NUMERIC (20, 2) NULL,
    [nadw_wpl_pa]     NUMERIC (20, 2) NULL,
    [kw_wm]           NUMERIC (20, 2) NULL,
    [kw_pa]           NUMERIC (20, 2) NULL,
    [us]              CHAR (1)        NULL,
    [akcl_og]         DECIMAL (20, 2) NULL,
    [dekl_za_do]      DATETIME        NULL,
    CONSTRAINT [PK_DOK_AKC] PRIMARY KEY CLUSTERED ([id_dok] ASC)
);

