CREATE TABLE [zef].[ew_egz_agr] (
    [id_dok]         VARCHAR (30)    NOT NULL,
    [sym_dok]        VARCHAR (30)    NULL,
    [dat_wystaw_dok] DATETIME        NULL,
    [archiwum]       VARCHAR (30)    NULL,
    [id_dok_spraw]   VARCHAR (30)    NULL,
    [nr_dok_spraw]   VARCHAR (30)    NULL,
    [stat_spraw]     CHAR (6)        NULL,
    [stat_poprz]     CHAR (6)        NULL,
    [id_rodz_dok]    CHAR (4)        NULL,
    [id_komor]       VARCHAR (20)    NULL,
    [id_kontr]       NUMERIC (10)    NULL,
    [id_komor3]      VARCHAR (20)    NULL,
    [id_kontr3]      NUMERIC (10)    NULL,
    [data_wnios]     DATETIME        NULL,
    [data_przydz]    DATETIME        NULL,
    [data_zak]       DATETIME        NULL,
    [sp_zak_egz]     CHAR (6)        NULL,
    [kwot_nal]       NUMERIC (20, 2) NULL,
    [kwot_nal_sc]    NUMERIC (20, 2) NULL,
    [saldo_nal]      NUMERIC (20, 2) NULL,
    [kwot_ods]       NUMERIC (20, 2) NULL,
    [kwot_ods_sc]    NUMERIC (20, 2) NULL,
    [saldo_ods]      NUMERIC (20, 2) NULL,
    [kwot_upom]      NUMERIC (20, 2) NULL,
    [kwot_upom_sc]   NUMERIC (20, 2) NULL,
    [saldo_upom]     NUMERIC (20, 2) NULL,
    [kwot_egz]       NUMERIC (20, 2) NULL,
    [kwot_egz_sc]    NUMERIC (20, 2) NULL,
    [saldo_egz]      NUMERIC (20, 2) NULL,
    [kntr_dodat]     CHAR (1)        NULL,
    [kwot_we]        NUMERIC (20, 2) NULL,
    [kwot_we_sc]     NUMERIC (20, 2) NULL,
    [saldo_we]       NUMERIC (20, 2) NULL,
    CONSTRAINT [PK_ew_egz_agr] PRIMARY KEY CLUSTERED ([id_dok] ASC)
);

