CREATE TABLE [zef].[kontrahenci] (
    [id_komor]         VARCHAR (20)  NOT NULL,
    [id_kontr]         NUMERIC (10)  NOT NULL,
    [id_grp_kntr]      CHAR (6)      NULL,
    [id_centr]         VARCHAR (9)   NULL,
    [nazwa_pelna]      VARCHAR (255) NULL,
    [nazwa_krotka]     CHAR (40)     NULL,
    [rodzaj]           CHAR (1)      NULL,
    [kraj]             VARCHAR (40)  NULL,
    [miejsc]           VARCHAR (60)  NULL,
    [kpoczt]           CHAR (6)      NULL,
    [ulica]            VARCHAR (40)  NULL,
    [nr_domu]          CHAR (6)      NULL,
    [nr_lokalu]        CHAR (4)      NULL,
    [nip]              VARCHAR (20)  NULL,
    [regon]            VARCHAR (20)  NULL,
    [pesel]            VARCHAR (20)  NULL,
    [rodz_dzial]       VARCHAR (40)  NULL,
    [bank]             VARCHAR (80)  NULL,
    [konto]            VARCHAR (60)  NULL,
    [def1]             VARCHAR (40)  NULL,
    [def2]             VARCHAR (40)  NULL,
    [def3]             VARCHAR (40)  NULL,
    [operator]         VARCHAR (15)  NULL,
    [data_wprow]       DATETIME      NULL,
    [replika]          CHAR (1)      NULL,
    [replika2]         CHAR (1)      NULL,
    [status]           CHAR (1)      NULL,
    [poczta]           VARCHAR (20)  NULL,
    [telefon]          VARCHAR (20)  NULL,
    [fax]              VARCHAR (20)  NULL,
    [uwagi]            VARCHAR (255) NULL,
    [woj]              VARCHAR (40)  NULL,
    [powiat]           VARCHAR (60)  NULL,
    [nr_paszportu]     VARCHAR (20)  NULL,
    [email]            VARCHAR (60)  NULL,
    [czas_zmiany]      DATETIME      NULL,
    [gmina]            VARCHAR (40)  NULL,
    [data_tokenu]      DATETIME      NULL,
    [token]            VARCHAR (40)  NULL,
    [data_weryfikacji] DATETIME      NULL,
    CONSTRAINT [PK_KONTRAHENCI] PRIMARY KEY CLUSTERED ([id_komor] ASC, [id_kontr] ASC)
);

