CREATE TABLE [zef].[pspraw] (
    [id_dok]   VARCHAR (30)    NOT NULL,
    [nr_poz]   SMALLINT        NOT NULL,
    [kod_poz]  VARCHAR (10)    NULL,
    [dzial]    VARCHAR (10)    NULL,
    [rozdzial] VARCHAR (10)    NULL,
    [paragraf] VARCHAR (10)    NULL,
    [tytul]    VARCHAR (10)    NULL,
    [kwota1]   NUMERIC (20, 2) NULL,
    [kwota2]   NUMERIC (20, 2) NULL,
    [kwota3]   NUMERIC (20, 2) NULL,
    [kwota4]   NUMERIC (20, 2) NULL,
    [kwota5]   NUMERIC (20, 2) NULL,
    [kwota6]   NUMERIC (20, 2) NULL,
    [kwota7]   NUMERIC (20, 2) NULL,
    [kwota8]   NUMERIC (20, 2) NULL,
    [kwota9]   NUMERIC (20, 2) NULL,
    [sum_poz]  VARCHAR (10)    NULL,
    [czesc]    VARCHAR (10)    NULL,
    [opis]     VARCHAR (255)   NULL,
    [opis2]    VARCHAR (255)   NULL,
    [kwota10]  NUMERIC (20, 2) NULL,
    [kwota11]  NUMERIC (20, 2) NULL,
    [kwota12]  NUMERIC (20, 2) NULL,
    [data1]    DATETIME        NULL,
    [data2]    DATETIME        NULL,
    [data3]    DATETIME        NULL,
    [data4]    DATETIME        NULL,
    [data5]    DATETIME        NULL,
    [data6]    DATETIME        NULL,
    [data7]    DATETIME        NULL,
    [data8]    DATETIME        NULL,
    [kwota13]  NUMERIC (20, 2) NULL,
    [kwota14]  NUMERIC (20, 2) NULL,
    [kwota15]  NUMERIC (20, 2) NULL,
    [kwota16]  NUMERIC (20, 2) NULL,
    [kwota17]  NUMERIC (20, 2) NULL,
    [kwota18]  NUMERIC (20, 2) NULL,
    [kwota19]  NUMERIC (20, 2) NULL,
    [kwota20]  NUMERIC (20, 2) NULL,
    [activity] VARCHAR (12)    NULL,
    CONSTRAINT [PK_PSPRAW] PRIMARY KEY CLUSTERED ([id_dok] ASC, [nr_poz] ASC)
);

