CREATE TABLE [zef].[pwplat] (
    [id_dok]       VARCHAR (30)    NOT NULL,
    [nr_poz]       SMALLINT        NOT NULL,
    [tyt_plat]     VARCHAR (9)     NULL,
    [kwota]        NUMERIC (20, 2) DEFAULT ((0)) NULL,
    [sym_dok_stow] VARCHAR (30)    NULL,
    [tresc]        VARCHAR (60)    NULL,
    [klasyf_budz]  VARCHAR (9)     NULL,
    [id_dok_stow]  VARCHAR (30)    NULL,
    [id_jedn]      VARCHAR (20)    NULL,
    [korekta]      CHAR (1)        DEFAULT ('N') NULL,
    [oper_kor]     VARCHAR (30)    NULL,
    [data_korekty] DATETIME        NULL,
    [status]       CHAR (1)        NULL,
    [odprowadzona] CHAR (1)        DEFAULT ('N') NULL,
    [nr_poz_ewid]  SMALLINT        NULL,
    [odsetki]      CHAR (1)        NULL,
    [ods_do_poz]   SMALLINT        NULL,
    [id_konta]     VARCHAR (10)    NULL,
    [rodz_nal]     VARCHAR (9)     NULL,
    [id_dok_odpr]  VARCHAR (30)    NULL,
    [data_poz]     DATETIME        NULL,
    [id_komor]     VARCHAR (20)    NULL,
    [id_kontr]     NUMERIC (10)    NULL,
    [term_plat]    DATETIME        NULL,
    [flag_wind]    CHAR (1)        NULL,
    [segment4]     VARCHAR (9)     NULL,
    [segment7]     VARCHAR (9)     NULL,
    [nw]           CHAR (1)        NULL,
    [kntr_dodat]   CHAR (1)        NULL,
    [id_dok_zrod]  VARCHAR (30)    NULL,
    [nr_poz_zrod]  SMALLINT        NULL,
    CONSTRAINT [PK_PWPLAT] PRIMARY KEY CLUSTERED ([id_dok] ASC, [nr_poz] ASC)
);

