CREATE TABLE [aimp2].[ICS_ZCP_ITEM_TARIC_QUANTITY] (
    [ID]                NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]       NUMERIC (19)    NULL,
    [UNIT]              NVARCHAR (3)    NULL,
    [QUALIFIER_OF_UNIT] NVARCHAR (1)    NULL,
    [QUANTITY]          NUMERIC (16, 6) NULL,
    [POZ_ID_REQ_DOC]    NUMERIC (5)     NULL,
    [version]           INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_TARIC_QUANTITY$PK_ICS_ZCP_ITEM_TARIC_QUANTITY] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_TARIC_QUANTITY$FK_ICS_ZCP_ITEM_TARIC_QUANTITY_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);

