CREATE TABLE [aimp2].[ICS_DIRT] (
    [ID]                          NUMERIC (19)    NOT NULL,
    [ADDRESSEE]                   NVARCHAR (40)   NULL,
    [AUTHOR]                      NVARCHAR (255)  NULL,
    [DIR_FOR_NEXT_CO]             NVARCHAR (500)  NULL,
    [DIR_DISPATCHER]              NVARCHAR (100)  NULL,
    [INFORMATION]                 NVARCHAR (200)  NULL,
    [WARUE]                       NVARCHAR (5)    NULL,
    [WAR1]                        NVARCHAR (1)    NULL,
    [WAR234]                      NVARCHAR (3)    NULL,
    [WAR5]                        NVARCHAR (1)    NULL,
    [COMMENT]                     NTEXT           NULL,
    [MRN]                         NVARCHAR (18)   NULL,
    [ALGORITHM_NUMBER]            NVARCHAR (30)   NULL,
    [OBJECTION_NUMBER]            NVARCHAR (30)   NULL,
    [RISK_AREA]                   NVARCHAR (12)   NULL,
    [samples]                     TINYINT         NULL,
    [PROFILE]                     NVARCHAR (24)   NULL,
    [STATUS]                      NVARCHAR (4)    NOT NULL,
    [TEXT]                        NTEXT           NULL,
    [CONTROL_TYPE]                NCHAR (1)       NULL,
    [POINTER]                     NVARCHAR (255)  NULL,
    [RESULT]                      NVARCHAR (1024) NULL,
    [SOURCE]                      NVARCHAR (1024) NULL,
    [DECL_ID]                     NUMERIC (19)    NOT NULL,
    [ITEM_TYPE]                   NCHAR (3)       NULL,
    [REALISATION_DATE]            DATETIME2 (3)   NULL,
    [ID_VERIFICATION_ITEM]        NUMERIC (19)    NULL,
    [DIRTYPE]                     NCHAR (3)       NULL,
    [INTRO]                       INT             NULL,
    [ORIGIN]                      NVARCHAR (40)   NULL,
    [VERIFICATION_REQUIRED]       TINYINT         NULL,
    [MODIFIED_BY]                 NVARCHAR (255)  NULL,
    [RISK_ANALYSIS_RESULT]        NVARCHAR (1)    NULL,
    [RESERVATION_NUMBER]          NVARCHAR (30)   NULL,
    [INFORMATION_FOR_DISPATCHER]  NVARCHAR (200)  NULL,
    [AGRIM_DISCREPANCY]           BIT             NOT NULL,
    [OFFICIAL_ANNOTATION]         NVARCHAR (1024) NULL,
    [ADD_TEXT]                    NTEXT           NULL,
    [forced_veri]                 BIT             NOT NULL,
    [correct_calc_tsk]            TINYINT         NULL,
    [zisar_source]                NVARCHAR (20)   NULL,
    [zisar_id]                    NVARCHAR (100)  NULL,
    [ENTITY_ROLE]                 NVARCHAR (3)    NULL,
    [ADDRESSED_TO_CUSTOMS_OFFICE] BIT             NOT NULL,
    [DIR_ACF]                     NTEXT           NULL,
    CONSTRAINT [ICS_DIRT$PK_ICS_DIRT] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DIRT$FK_ICS_DIRT_ICS_DECL] FOREIGN KEY ([DECL_ID]) REFERENCES [aimp2].[ICS_DECL] ([ID])
) TEXTIMAGE_ON [FG_AIMP2];

