CREATE TABLE [aimp2].[ICS_DSK_TOWAR_ODMOWA_SKLAD] (
    [ID]                    NUMERIC (19)    NOT NULL,
    [ICS_DSK_TOWAR_ID]      NUMERIC (19)    NULL,
    [OPIS_NIEPRAWIDLOWOSCI] NVARCHAR (1024) NULL,
    [UZASADNIENIE]          NVARCHAR (256)  NULL,
    [version]               INT             NOT NULL,
    CONSTRAINT [ICS_DSK_TOWAR_ODMOWA_SKLAD$PK_ICS_DSK_TOWAR_ODMOWA_SKLAD] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DSK_TOWAR_ODMOWA_SKLAD$FK_ICS_DSK_TOWAR_ODMOWA_SKLAD_ICS_DSK_TOWAR] FOREIGN KEY ([ICS_DSK_TOWAR_ID]) REFERENCES [aimp2].[ICS_DSK_TOWAR] ([ID])
);

