CREATE TABLE [aimp2].[ICS_ZCP_TARIC_ADD_CODES] (
    [ID]          NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19) NULL,
    [TARIC_CODE]  NVARCHAR (4) NULL,
    [version]     INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_TARIC_ADD_CODES$PK_ICS_ZCP_TARIC_ADD_CODES] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_TARIC_ADD_CODES$FK_ICS_ZCP_TARIC_ADD_CODES_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);

