CREATE TABLE [aimp2].[ICS_ZCP_PREV_DOC] (
    [ID]       NUMERIC (19)  NOT NULL,
    [ZCP_ID]   NUMERIC (19)  NULL,
    [CATEGORY] NVARCHAR (1)  NOT NULL,
    [CODE]     NVARCHAR (3)  NOT NULL,
    [NUMBER]   NVARCHAR (35) NOT NULL,
    [ZCP_ACF]  NTEXT         NULL,
    [version]  INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_PREV_DOC_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_PREV_DOC$ICS_ZCP_PR_295109211] FOREIGN KEY ([ZCP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID])
) TEXTIMAGE_ON [FG_AIMP2];

