CREATE TABLE [aimp2].[ICS_DSK_TOWAR_OPAKOWANIE] (
    [ID]                      NUMERIC (19)   NOT NULL,
    [ICS_DSK_TOWAR_ID]        NUMERIC (19)   NULL,
    [LICZBA_OPAKOWAN]         NUMERIC (8)    NULL,
    [NUMERY_I_ZNAKI_OPAKOWAN] NVARCHAR (512) NULL,
    [RODZAJ_OPAKOWANIA]       NCHAR (3)      NULL,
    [version]                 INT            NOT NULL,
    CONSTRAINT [ICS_DSK_TOWAR_OPAKOWANIE$PK_ICS_DSK_TOWAR_OPAKOWANIE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DSK_TOWAR_OPAKOWANIE$FK_ICS_DSK_TOWAR_OPAKOWANIE_ICS_DSK_TOWAR] FOREIGN KEY ([ICS_DSK_TOWAR_ID]) REFERENCES [aimp2].[ICS_DSK_TOWAR] ([ID])
);

