CREATE TABLE [aimp2].[ICS_ZCP_ITEM_PACK] (
    [ID]               NUMERIC (19)  NOT NULL,
    [ZCP_ITEM_ID]      NUMERIC (19)  NULL,
    [PACK_QUANTITY]    NUMERIC (8)   NULL,
    [PACK_NUMBER_SIGN] NVARCHAR (42) NULL,
    [PACK_TYPE]        NVARCHAR (3)  NULL,
    [ZCP_ACF]          NTEXT         NULL,
    [version]          INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_PACK$PK_ICS_ZCP_ITEM_PACK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_PACK$FK_ICS_ZCP_ITEM_PACK_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
) TEXTIMAGE_ON [FG_AIMP2];

