CREATE TABLE [aimp2].[ICS_DIRT_IND] (
    [ID]           NUMERIC (19)   NOT NULL,
    [DIRECTIVE_ID] NUMERIC (19)   NOT NULL,
    [NAME]         NVARCHAR (100) NOT NULL,
    [VALUE]        NVARCHAR (100) NULL,
    [show]         BIT            DEFAULT ((1)) NOT NULL,
    [version]      INT            NOT NULL,
    CONSTRAINT [ICS_DIRT_IND_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DIRT_IND$FK_ICS_DIRT_SEG_IND] FOREIGN KEY ([DIRECTIVE_ID]) REFERENCES [aimp2].[ICS_DIRT] ([ID])
);

