CREATE TABLE [aimp2].[ICS_DECL_PARAM] (
    [id]       NUMERIC (19)  NOT NULL,
    [decl_id]  NUMERIC (19)  NOT NULL,
    [key_name] NVARCHAR (50) NOT NULL,
    [value]    NVARCHAR (70) NOT NULL,
    CONSTRAINT [ICS_DECL_ICS_DECL_PARAM_PK] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AIMP2],
    CONSTRAINT [FK_ICS_DECL_PARAM$FK4405DDEFD605A773] FOREIGN KEY ([decl_id]) REFERENCES [aimp2].[ICS_DECL] ([ID])
);

