CREATE TABLE [aimp2].[ICS_DSK_KONTENER] (
    [ID]              NUMERIC (19)  NOT NULL,
    [ICS_DSK_ID]      NUMERIC (19)  NOT NULL,
    [NUMER_KONTENERA] NVARCHAR (17) NOT NULL,
    [version]         INT           NOT NULL,
    CONSTRAINT [PK_ICS_DSK_KONTENER] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DSK_KONTENER$FK_ICS_DSK_KONTENER] FOREIGN KEY ([ICS_DSK_ID]) REFERENCES [aimp2].[ICS_DSK] ([ID])
);

