CREATE TABLE [aimp2].[ICS_ZCP_ITEM_CUSTOM_DEST] (
    [ID]          NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19)    NULL,
    [NAME]        NVARCHAR (4)    NULL,
    [DOCUMENT_NO] NVARCHAR (40)   NULL,
    [DATE]        DATETIME2 (3)   NULL,
    [QUANTITY]    NUMERIC (16, 6) NULL,
    [version]     INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_CUSTOM_DEST$PK_ICS_ZCP_ITEM_CUSTOM_DEST] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_CUSTOM_DEST$FK_ICS_ZCP_ITEM_CUSTOM_DEST_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);

