CREATE TABLE [aimp2].[ICS_ZCP_ITEM_PREV_DOC_POS] (
    [ID]                   NUMERIC (19) NOT NULL,
    [ZCP_ITEM_PREV_DOC_ID] NUMERIC (19) NOT NULL,
    [PREV_DOC_NO]          NUMERIC (5)  NOT NULL,
    [version]              INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_PREV_DOC_POS_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_PREV_DOC_POS$ICS_ZCP_IT_487109895] FOREIGN KEY ([ZCP_ITEM_PREV_DOC_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM_PREV_DOC] ([ID])
);

