CREATE TABLE [aimp2].[ICS_OTHER_ADDRESS] (
    [ID]            NUMERIC (19)  NOT NULL,
    [ZIP_CODE]      NVARCHAR (9)  NOT NULL,
    [COUNTRY]       NVARCHAR (2)  NOT NULL,
    [CITY]          NVARCHAR (35) NOT NULL,
    [STREET_AND_NO] NVARCHAR (70) NOT NULL,
    [version]       INT           NOT NULL,
    CONSTRAINT [ICS_OTHER_ADDRESS_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2]
);

