CREATE TABLE [aimp2].[ICS_ZCP_ITEM_PROCEDURE_DETAILS] (
    [ID]          NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19) NULL,
    [CODE]        NVARCHAR (3) NOT NULL,
    [ZCP_ACF]     NTEXT        NULL,
    [version]     INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_PROCEDURE_DETAILS_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_PROCEDURE_DETAILS$FK_ICS_ZCP_PROCEDURE_DETAILS_ZCP_ID] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
) TEXTIMAGE_ON [FG_AIMP2];

