CREATE TABLE [aimp2].[ICS_PWD_PROCEDURE_DETAIL] (
    [procedure_id] NUMERIC (19) NOT NULL,
    [code]         NVARCHAR (3) NOT NULL,
    CONSTRAINT [ICS_PWD_PROCEDURE_DETAIL$FK_ICS_PWD_PROCEDURE_DETAIL__ICS_PWD_PROCEDURE] FOREIGN KEY ([procedure_id]) REFERENCES [aimp2].[ICS_PWD_PROCEDURE] ([id]),
    CONSTRAINT [ICS_PWD_PROCEDURE_DETAIL$UQ_ICS_PWD_PROCEDURE_DETAIL] UNIQUE NONCLUSTERED ([procedure_id] ASC, [code] ASC) ON [FG_AIMP2]
) ON [FG_AIMP2];

