CREATE TABLE [aimp2].[ICS_CHANG] (
    [ID]      NUMERIC (19)   NOT NULL,
    [AFTER]   NVARCHAR (255) NULL,
    [BEFORE]  NVARCHAR (255) NULL,
    [ITEM]    NVARCHAR (255) NULL,
    [OPER_ID] NUMERIC (19)   NULL,
    CONSTRAINT [ICS_CHANG_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_CHANG$FK4405DDEFD605A773] FOREIGN KEY ([OPER_ID]) REFERENCES [aimp2].[ICS_OPER] ([ID])
);

