CREATE TABLE [aimp2].[ICS_ZCP_ITEM_VEHICLE] (
    [ID]              NUMERIC (19)  NOT NULL,
    [ZCP_ITEM_ID]     NUMERIC (19)  NULL,
    [MAKE]            NVARCHAR (35) NULL,
    [BODYWORK_NO]     NVARCHAR (35) NULL,
    [ENGINE_NO]       NVARCHAR (35) NULL,
    [ENGINE_CAPACITY] NUMERIC (5)   NULL,
    [FUEL_TYPE]       NVARCHAR (2)  NULL,
    [PROD_YEAR]       NUMERIC (4)   NULL,
    [MODEL]           NVARCHAR (35) NOT NULL,
    [version]         INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_VEHICLE$PK_ICS_ZCP_ITEM_VEHICLE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_VEHICLE$FK_ICS_ZCP_ITEM_VEHICLE_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);

