CREATE TABLE [aimp2].[ICS_ZCP_ITEM] (
    [ID]                            NUMERIC (19)    NOT NULL,
    [ZCP_ID]                        NUMERIC (19)    NULL,
    [LEGAL_ANNOTATIONS]             NVARCHAR (2000) NULL,
    [RELEASE_OF_GOODS_DATE]         DATETIME2 (3)   NULL,
    [QUANTITY_SUPPL_UNIT]           NUMERIC (16, 6) NULL,
    [CN_CODE]                       NVARCHAR (8)    NULL,
    [CUS_CODE]                      NVARCHAR (18)   NULL,
    [TARIC_CODE]                    NVARCHAR (2)    NULL,
    [COUNTRY_OF_ORIGIN]             NVARCHAR (2)    NULL,
    [COUNTRY_OF_DESTINATION]        NVARCHAR (2)    NULL,
    [COUNTRY_OF_DESTINATION_REGION] NVARCHAR (9)    NULL,
    [COUNTRY_OF_EXPORT]             NVARCHAR (2)    NULL,
    [MEASURE_NO]                    NUMERIC (2)     NULL,
    [ITEM_NO]                       NUMERIC (5)     NULL,
    [PARCEL_REFERENCE_NUMBER]       NVARCHAR (35)   NULL,
    [PREFERENCE_CODE]               NVARCHAR (3)    NULL,
    [ZCP_ITEM_STATUS]               NVARCHAR (4)    NULL,
    [ARR_STATUS]                    NVARCHAR (4)    NULL,
    [EMCS_STATUS]                   NVARCHAR (4)    NULL,
    [MEASURE_TYPE_CODE]             NVARCHAR (3)    NULL,
    [TRANS_TYPE]                    NUMERIC (2)     NULL,
    [EMCS_CN_CODE]                  NVARCHAR (8)    NULL,
    [EMCS_NET_MASS]                 NUMERIC (16, 6) NULL,
    [EMCS_ARC_NO]                   NVARCHAR (35)   NULL,
    [DESCR_OF_IRREGULARITY]         NVARCHAR (1024) NULL,
    [ICS_ENS_ITEMS_ID]              NUMERIC (19)    NULL,
    [NP_SENDER_ID]                  NUMERIC (19)    NULL,
    [BE_SENDER_ID]                  NUMERIC (19)    NULL,
    [NP_RECEIVER_ID]                NUMERIC (19)    NULL,
    [BE_RECEIVER_ID]                NUMERIC (19)    NULL,
    [NP_CONTACT_ID]                 NUMERIC (19)    NULL,
    [BE_CONTACT_ID]                 NUMERIC (19)    NULL,
    [ITEM_DESCRIPTION]              NVARCHAR (1000) NULL,
    [NOTES]                         NVARCHAR (260)  NULL,
    [GROSS_MASS_KG]                 NUMERIC (16, 6) NULL,
    [NET_MASS_KG]                   NUMERIC (16, 6) NULL,
    [QUANTITY]                      NUMERIC (16, 6) NULL,
    [ICS_GAN_CUST_DATA_DETL_ID]     NUMERIC (19)    NULL,
    [AGRIM]                         BIT             NOT NULL,
    [E_AD]                          BIT             NOT NULL,
    [PAYMENT_DONE]                  BIT             NOT NULL,
    [NP_SELLER_ID]                  NUMERIC (19)    NULL,
    [BE_SELLER_ID]                  NUMERIC (19)    NULL,
    [BE_BUYER_ID]                   NUMERIC (19)    NULL,
    [NP_BUYER_ID]                   NUMERIC (19)    NULL,
    [CONTINUE_PROCESSING]           BIT             NOT NULL,
    [VERIF_RESULT]                  NVARCHAR (4)    NULL,
    [NET_MASS_REAL]                 NUMERIC (16, 3) NULL,
    [CN_CODE_REAL]                  NVARCHAR (8)    NULL,
    [DPZ_STRATEGIC]                 BIT             NOT NULL,
    [PROCEDURE_PREVIOUS]            NVARCHAR (2)    NULL,
    [PROCEDURE_REQUESTED]           NVARCHAR (7)    NULL,
    [GUARANT_DONE]                  BIT             NOT NULL,
    [ITEMS_VALUE]                   DECIMAL (16, 2) NULL,
    [RS_DATE]                       DATETIME2 (3)   NULL,
    [RS_BASE]                       NVARCHAR (35)   NULL,
    [RS_TYPE]                       NVARCHAR (1024) NULL,
    [ARR_SALDO]                     NVARCHAR (4)    NULL,
    [SENT_TO_OSOZ_STATUS]           NVARCHAR (20)   NOT NULL,
    [SENT_TO_ZEFIR_STATUS]          NVARCHAR (20)   NOT NULL,
    [INVA_REASON]                   NVARCHAR (1024) NULL,
    [DEL_BY_ADM_ID]                 NUMERIC (19)    NULL,
    [INVA_MANU]                     BIT             NOT NULL,
    [INVA_REJ_REASON]               NVARCHAR (1024) NULL,
    [VAT7_CLOSED]                   BIT             NOT NULL,
    [INVA_SELF_REF]                 NVARCHAR (35)   NULL,
    [NULL_PAYMENT_DONE]             BIT             NOT NULL,
    [UZP_ID]                        NUMERIC (19)    NULL,
    [SENT_ZC272]                    BIT             NOT NULL,
    [PZC]                           BIT             NOT NULL,
    [tqsRejectedIn]                 BIT             NOT NULL,
    [EMCS_TRYB]                     NCHAR (2)       NULL,
    [STOP_WAITING_EMCS]             NCHAR (1)       NULL,
    [CALC_DATE1]                    DATETIME2 (3)   NULL,
    [CALC_DATE2]                    DATETIME2 (3)   NULL,
    [CURRENCY_CODE]                 NVARCHAR (3)    NULL,
    [VAT7_ADMINISTRATIVE_DECISION]  BIT             NULL,
    [VAT7_SETTLEMENT_DATE]          DATETIME        NULL,
    [OP_COUNTRY_CODE]               NVARCHAR (2)    NULL,
    [ITEM_CODE]                     NVARCHAR (8)    NULL,
    [INVA_DATE]                     DATETIME2 (3)   NULL,
    [ZEFIR_RECT_COUNTER]            INT             NULL,
    [CONSIGNEE_ID_BE_VALID_SC]      NUMERIC (19)    NULL,
    [ZCP_ITEM_ACF]                  NTEXT           NULL,
    [CRX_VAL_RES]                   INT             NULL,
    [ALL_GUARANT_PAYMENT_DONE]      BIT             NOT NULL,
    [ISZTAR_RECEIVED]               BIT             NOT NULL,
    [EMCS_LRN]                      NVARCHAR (30)   NULL,
    [PAY_REGISTRATION_ANNOTATION]   NVARCHAR (1024) NULL,
    [RELEASED_IN_OSOZ]              BIT             NOT NULL,
    [PAYMENT_D_DONE]                BIT             NOT NULL,
    [version]                       INT             NOT NULL,
    [TEMPORARY_DUTY]                NCHAR (1)       NOT NULL,
    [FINAL_DUTY]                    NCHAR (1)       NOT NULL,
    [EMCS_POWIADOM]                 NCHAR (1)       NULL,
    [EMCS_NUMER]                    INT             NULL,
    CONSTRAINT [ICS_ZCP_ITEM$PK_ICS_ZCP_ITEM] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_BE_BUY_ICS_ZCP_BUSINESS_ENTITY] FOREIGN KEY ([BE_BUYER_ID]) REFERENCES [aimp2].[ICS_ZCP_BUSINESS_ENTITY] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_BE_CON_ICS_ZCP_BUSINESS_ENTITY] FOREIGN KEY ([BE_CONTACT_ID]) REFERENCES [aimp2].[ICS_ZCP_BUSINESS_ENTITY] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_BE_REC_ICS_ZCP_BUSINESS_ENTITY] FOREIGN KEY ([BE_RECEIVER_ID]) REFERENCES [aimp2].[ICS_ZCP_BUSINESS_ENTITY] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_BE_SEN_ICS_ZCP_BUSINESS_ENTITY] FOREIGN KEY ([BE_SENDER_ID]) REFERENCES [aimp2].[ICS_ZCP_BUSINESS_ENTITY] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_ICS_UZP] FOREIGN KEY ([UZP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_ICS_ZCP] FOREIGN KEY ([ZCP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_ICS_ZCP_BUSINESS_ENTITY] FOREIGN KEY ([BE_SELLER_ID]) REFERENCES [aimp2].[ICS_ZCP_BUSINESS_ENTITY] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_ICS_ZCP_NATURAL_PERSON] FOREIGN KEY ([NP_SELLER_ID]) REFERENCES [aimp2].[ICS_ZCP_NATURAL_PERSON] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_NP_BUY_ICS_ZCP_NATURAL_PERSON] FOREIGN KEY ([NP_BUYER_ID]) REFERENCES [aimp2].[ICS_ZCP_NATURAL_PERSON] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_NP_CON_ICS_ZCP_NATURAL_PERSON] FOREIGN KEY ([NP_CONTACT_ID]) REFERENCES [aimp2].[ICS_ZCP_NATURAL_PERSON] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_NP_REC_ICS_ZCP_NATURAL_PERSON] FOREIGN KEY ([NP_RECEIVER_ID]) REFERENCES [aimp2].[ICS_ZCP_NATURAL_PERSON] ([ID]),
    CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_NP_SEN_ICS_ZCP_NATURAL_PERSON] FOREIGN KEY ([NP_SENDER_ID]) REFERENCES [aimp2].[ICS_ZCP_NATURAL_PERSON] ([ID])
) TEXTIMAGE_ON [FG_AIMP2];


GO
ALTER TABLE [aimp2].[ICS_ZCP_ITEM] NOCHECK CONSTRAINT [ICS_ZCP_ITEM$FK_ICS_ZCP_ITEM_ICS_UZP];

