CREATE TABLE [aimp2].[ICS_ZCP_DV1_INCREM_DEDUCTION] (
    [ID]               NUMERIC (19)    NOT NULL,
    [ZCP_ID]           NUMERIC (19)    NULL,
    [ZCP_ITEM_ID]      NUMERIC (19)    NULL,
    [INCREM_DEDUCTION] NVARCHAR (3)    NULL,
    [AMOUNT]           NUMERIC (16, 2) NULL,
    [version]          INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_DV1_INCREM_DEDUCTION$PK_ICS_ZCP_DV1_INCREM_DEDUCTION] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_DV1_INCREM_DEDUCTION$FK_ICS_ZCP_DV1_INCREM_DEDUCTION_ICS_ZCP] FOREIGN KEY ([ZCP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID]),
    CONSTRAINT [ICS_ZCP_DV1_INCREM_DEDUCTION$FK_ICS_ZCP_DV1_INCREM_DEDUCTION_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);

