CREATE TABLE [aimp2].[ICS_ZCP_NOTIF_ABOUT_CONTROL] (
    [ID]      NUMERIC (19)   NOT NULL,
    [ZCP_ID]  NUMERIC (19)   NULL,
    [TIME]    DATETIME2 (3)  NULL,
    [REMARKS] NVARCHAR (255) NULL,
    [version] INT            NOT NULL,
    CONSTRAINT [ICS_ZCP_NOTIF_ABOUT_CONTROL$PK_ICS_ZCP_NOTIF_ABOUT_CONTROL] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_NOTIF_ABOUT_CONTROL$FK_ICS_ZCP_NOTIF_ABOUT_CONTROL_ICS_ZCP] FOREIGN KEY ([ZCP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID])
);

