CREATE TABLE [aimp2].[ICS_DSK_POW_O_KONTROLI] (
    [ID]            NUMERIC (19)   NOT NULL,
    [ICS_DSK_ID]    NUMERIC (19)   NOT NULL,
    [CZAS_KONTROLI] DATETIME2 (3)  NULL,
    [UWAGI]         NVARCHAR (255) NULL,
    [version]       INT            NOT NULL,
    CONSTRAINT [ICS_DSK_POW_O_KONTROLI$PK_ICS_DSK_POW_O_KONTROLI] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DSK_POW_O_KONTROLI$FK_ICS_DSK_POW_O_KONTROLI] FOREIGN KEY ([ICS_DSK_ID]) REFERENCES [aimp2].[ICS_DSK] ([ID])
);

