CREATE TABLE [aimp2].[ICS_DIRT_POSITION] (
    [id]           NUMERIC (19) NOT NULL,
    [directive_id] NUMERIC (19) NULL,
    [position]     NUMERIC (5)  NOT NULL,
    CONSTRAINT [ICS_DIRT_POSITION_PK] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DIRT_POSITION$ICS_DIRT_P_1111112118] FOREIGN KEY ([directive_id]) REFERENCES [aimp2].[ICS_DIRT] ([ID])
);

