CREATE TABLE [aimp2].[ICS_MESS_KANAL] (
    [ID]      NUMERIC (19)  NOT NULL,
    [MESS_ID] NUMERIC (19)  NOT NULL,
    [KTYP]    NVARCHAR (2)  NOT NULL,
    [KCHOICE] NVARCHAR (4)  NOT NULL,
    [VAL]     NVARCHAR (70) NOT NULL,
    [VAL_ADD] NVARCHAR (70) NULL,
    CONSTRAINT [ICS_MESS_KANAL_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_MESS_KANAL$FK4405DDEFD605A773] FOREIGN KEY ([MESS_ID]) REFERENCES [aimp2].[ICS_MESS] ([ID])
);

