CREATE TABLE [aimp2].[ICS_DSK_DOKUMENT_POPRZ] (
    [ID]         NUMERIC (19)  NOT NULL,
    [ICS_DSK_ID] NUMERIC (19)  NULL,
    [KATEGORIA]  NCHAR (1)     NULL,
    [KOD]        NCHAR (3)     NULL,
    [NUMER]      NVARCHAR (35) NULL,
    [version]    INT           NOT NULL,
    CONSTRAINT [ICS_DSK_DOKUMENT_POPRZ$PK_ICS_DSK_DOKUMENT_POPRZ] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DSK_DOKUMENT_POPRZ$FK_ICS_DSK_DOKUMENT_POPRZ] FOREIGN KEY ([ICS_DSK_ID]) REFERENCES [aimp2].[ICS_DSK] ([ID])
);


GO
ALTER TABLE [aimp2].[ICS_DSK_DOKUMENT_POPRZ] NOCHECK CONSTRAINT [ICS_DSK_DOKUMENT_POPRZ$FK_ICS_DSK_DOKUMENT_POPRZ];

