CREATE TABLE [aimp2].[ICS_ZCP_ADDITIONAL_INFO] (
    [ID]          NUMERIC (19)   NOT NULL,
    [ZCP_ID]      NUMERIC (19)   NULL,
    [CODE]        NVARCHAR (5)   NULL,
    [DESCRIPTION] NVARCHAR (512) NULL,
    [version]     INT            NOT NULL,
    CONSTRAINT [ICS_ZCP_ADDITIONAL_INFO$PK_ICS_ZCP_ADDITIONAL_INFO] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ADDITIONAL_INFO$FK_ICS_ZCP_ADDITIONAL_INFO_ICS_ZCP] FOREIGN KEY ([ZCP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID])
);

