CREATE TABLE [aimp2].[ICS_ZCP_ITEM_OSOZ2_GUARANTEE] (
    [ID]             NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]    NUMERIC (19)    NULL,
    [AMOUNT]         NUMERIC (16, 2) NULL,
    [OPERATION_NO]   NVARCHAR (75)   NULL,
    [USE_DATE]       DATETIME2 (3)   NULL,
    [RELIEF_BALANCE] NUMERIC (16, 2) NULL,
    [RELIEF_DATE]    DATETIME2 (3)   NULL,
    [version]        INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_OSOZ2_GUARANTEE$PK_ICS_ZCP_ITEM_OSOZ2_GUARANTEE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_OSOZ2_GUARANTEE$FK_ICS_ZCP_ITEM_OSOZ2_GUARANTEE_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);

