CREATE TABLE [aimp2].[ICS_ZCP_CONTRACT] (
    [ID]         NUMERIC (19)  NOT NULL,
    [ZCP_ID]     NUMERIC (19)  NULL,
    [CONTR_DATE] DATETIME2 (3) NULL,
    [CONTR_NO]   NVARCHAR (35) NULL,
    [version]    INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_CONTRACT_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_CONTRACT$FK_ICS_ZCP] FOREIGN KEY ([ZCP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID])
);

