CREATE TABLE [aimp2].[ICS_ZCP_OSOZ_ZEFIR_OQ] (
    [id]               NUMERIC (19)  NOT NULL,
    [zcp_id]           NUMERIC (19)  NOT NULL,
    [operation]        NVARCHAR (60) NOT NULL,
    [procedure_type]   NVARCHAR (30) NOT NULL,
    [status]           NVARCHAR (30) NOT NULL,
    [zcp_item_id]      NUMERIC (19)  NOT NULL,
    [zcp_wdz_item_id]  NUMERIC (19)  NULL,
    [zcp_podz_item_id] NUMERIC (19)  NULL,
    [version]          INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_OSOZ_ZEFIR_OPERATIONS_QUEUE_PK] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_OSOZ_ZEFIR_OPERATIONS_QUEUE$ICS_ZCP_OS_1338588926] FOREIGN KEY ([zcp_id]) REFERENCES [aimp2].[ICS_ZCP] ([ID]),
    CONSTRAINT [ICS_ZCP_OSOZ_ZEFIR_OPERATIONS_QUEUE$ICS_ZCP_OS_1354588983] FOREIGN KEY ([zcp_item_id]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID]),
    CONSTRAINT [ICS_ZCP_OSOZ_ZEFIR_OPERATIONS_QUEUE$ICS_ZCP_OS_1370589040] FOREIGN KEY ([zcp_wdz_item_id]) REFERENCES [aimp2].[ICS_ZCP_ITEM_WDZ] ([ID]),
    CONSTRAINT [ICS_ZCP_OSOZ_ZEFIR_OPERATIONS_QUEUE$ICS_ZCP_OS_1386589097] FOREIGN KEY ([zcp_podz_item_id]) REFERENCES [aimp2].[ICS_ZCP_ITEM_PODZ] ([ID])
);

