CREATE TABLE [aimp2].[ICS_OPER] (
    [ID]        NUMERIC (19)    NOT NULL,
    [ANNO]      NVARCHAR (4000) NULL,
    [CODE]      NVARCHAR (4)    NULL,
    [OPER]      NVARCHAR (40)   NULL,
    [TIME]      DATETIME2 (3)   NULL,
    [DECL_ID]   NUMERIC (19)    NULL,
    [ANNO_KIND] NVARCHAR (20)   NULL,
    CONSTRAINT [ICS_OPER_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_OPER$FKA79605444640C1A] FOREIGN KEY ([DECL_ID]) REFERENCES [aimp2].[ICS_DECL] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20180906-115649]
    ON [aimp2].[ICS_OPER]([DECL_ID] ASC)
    ON [FG_AIMP2];


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20180906-135800]
    ON [aimp2].[ICS_OPER]([TIME] ASC)
    INCLUDE([DECL_ID])
    ON [FG_AIMP2];

