CREATE TABLE [aimp2].[ICS_ZCP_ITEM_PREV_DOC] (
    [ID]          NUMERIC (19)  NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19)  NULL,
    [CATEGORY]    NVARCHAR (1)  NULL,
    [CODE]        NVARCHAR (3)  NULL,
    [NUMBER]      NVARCHAR (35) NULL,
    [PREV_DOC_NO] NUMERIC (5)   NULL,
    [ZCP_ACF]     NTEXT         NULL,
    [version]     INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_PREV_DOC$PK_ICS_ZCP_ITEM_PREV_DOC] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_PREV_DOC$FK_ICS_ZCP_ITEM_PREV_DOC_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
) TEXTIMAGE_ON [FG_AIMP2];

