CREATE TABLE [aimp2].[ICS_ZCP_BUSINESS_ENTITY_AI] (
    [ID]                     NUMERIC (19) NOT NULL,
    [ZCP_BUSINESS_ENTITY_ID] NUMERIC (19) NULL,
    [CODE]                   NVARCHAR (5) NOT NULL,
    [version]                INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_BUSINESS_ENTITY_ADDITIONAL_INFO_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_BUSINESS_ENTITY_ADDITIONAL_INFO$ICS_ZCP_BU_583110237] FOREIGN KEY ([ZCP_BUSINESS_ENTITY_ID]) REFERENCES [aimp2].[ICS_ZCP_BUSINESS_ENTITY] ([ID])
);

