CREATE TABLE [aimp2].[ICS_ZCP_ITEM_ADD_INFO] (
    [ID]          NUMERIC (19)   NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19)   NULL,
    [CODE]        NVARCHAR (5)   NULL,
    [DESCRIPTION] NVARCHAR (512) NULL,
    [ZCP_ACF]     NTEXT          NULL,
    [version]     INT            NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_ADD_INFO$PK_ICS_ZCP_ITEM_ADD_INFO] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_ADD_INFO$FK_ICS_ZCP_ITEM_ADD_INFO_ICS_ZCP_ITEM] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
) TEXTIMAGE_ON [FG_AIMP2];

