CREATE TABLE [aimp2].[ICS_ZCP_DELIVERY_REQS] (
    [ID]               NUMERIC (19)   NOT NULL,
    [ZCP_ID]           NUMERIC (19)   NULL,
    [CODE]             NVARCHAR (3)   NULL,
    [DESTINATION_CODE] NVARCHAR (255) NULL,
    [DESTINATION]      NVARCHAR (255) NULL,
    [COUNTRY]          NVARCHAR (2)   NULL,
    [UNLOCODE]         NVARCHAR (17)  NULL,
    [version]          INT            NOT NULL,
    CONSTRAINT [ICS_ZCP_DELIVERY_REQS$PK_ICS_ZCP_DELIVERY_REQS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_DELIVERY_REQS$FK_ICS_ZCP_DELIVERY_REQS_ICS_ZCP] FOREIGN KEY ([ZCP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID])
);

