CREATE TABLE [aimp2].[ICS_DSK_TRANSPORT] (
    [ID]                           NUMERIC (19)  NOT NULL,
    [ICS_DSK_ID]                   NUMERIC (19)  NOT NULL,
    [ZNAKI_SRODKA_TRANSPORTU]      NVARCHAR (35) NULL,
    [OZNACZENIE_SRODKA_TRANSPORTU] NCHAR (2)     NULL,
    [version]                      INT           NOT NULL,
    CONSTRAINT [ICS_DSK_TRANSPORT$PK_ICS_DSK_TRANSPORT] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DSK_TRANSPORT$FK_ICS_DSK_TRANSPORT] FOREIGN KEY ([ICS_DSK_ID]) REFERENCES [aimp2].[ICS_DSK] ([ID])
);

