CREATE TABLE [aimp2].[ICS_ZCP_OFFICIAL_ANNOTATION] (
    [id]          NUMERIC (19)   NOT NULL,
    [zcp_item_id] NUMERIC (19)   NOT NULL,
    [annotation]  NVARCHAR (256) NOT NULL,
    [version]     INT            NOT NULL,
    CONSTRAINT [ICS_ZCP_OFFICIAL_ANNOTATION_PK] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_OFFICIAL_ANNOTATION$ICS_ZCP_OF_1514589553] FOREIGN KEY ([zcp_item_id]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);

