CREATE TABLE [aimp2].[ICS_ZCP_ITEM_POSTAGE] (
    [ID]            NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]   NUMERIC (19)    NOT NULL,
    [CURRENCY_CODE] NVARCHAR (3)    NOT NULL,
    [AMOUNT]        NUMERIC (16, 2) NOT NULL,
    [version]       INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_POSTAGE_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_ITEM_POSTAGE$ICS_ZCP_IT_135108641] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);

