CREATE TABLE [aimp2].[ICS_DSK_NIESKUTECZNE_ZAB] (
    [ID]           NUMERIC (19)   NOT NULL,
    [ICS_DSK_ID]   NUMERIC (19)   NOT NULL,
    [NR_POZYCJI]   NUMERIC (5)    NULL,
    [UZASADNIENIE] NVARCHAR (256) NULL,
    [version]      INT            NOT NULL,
    CONSTRAINT [PK_ICS_DSK_NIESKUTECZNE_ZAB] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_DSK_NIESKUTECZNE_ZAB$FK_ICS_DSK_NIESKUTECZNE_ZAB] FOREIGN KEY ([ICS_DSK_ID]) REFERENCES [aimp2].[ICS_DSK] ([ID])
);

