CREATE TABLE [aimp2].[ICS_ZCP_POD_ITEM] (
    [ID]          NUMERIC (19) NOT NULL,
    [ZCP_POD_ID]  NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19) NOT NULL,
    [version]     INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_POD_ITEM_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_POD_ITEM$ICS_ZCP_PO_906587387] FOREIGN KEY ([ZCP_ITEM_ID]) REFERENCES [aimp2].[ICS_ZCP_ITEM] ([ID])
);


GO
ALTER TABLE [aimp2].[ICS_ZCP_POD_ITEM] NOCHECK CONSTRAINT [ICS_ZCP_POD_ITEM$ICS_ZCP_PO_906587387];

