CREATE TABLE [aimp2].[ICS_ZCP_CONTAINER] (
    [ID]                NUMERIC (19)  NOT NULL,
    [ZCP_ID]            NUMERIC (19)  NULL,
    [CONTAINER_NUMBER]  NVARCHAR (17) NOT NULL,
    [ZCP_CONTAINER_ACF] NTEXT         NULL,
    [version]           INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_CONTAINER_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_ZCP_CONTAINER$ICS_ZCP_CO_39108299] FOREIGN KEY ([ZCP_ID]) REFERENCES [aimp2].[ICS_ZCP] ([ID])
) TEXTIMAGE_ON [FG_AIMP2];

