CREATE TABLE [aimp2].[ICS_OTHER_CUSTOM_DEST] (
    [ID]       NUMERIC (19)    NOT NULL,
    [DATE]     DATETIME2 (3)   NOT NULL,
    [COMMENT]  NVARCHAR (1000) NULL,
    [REF_NO]   NVARCHAR (18)   NULL,
    [TYPE]     NVARCHAR (35)   NOT NULL,
    [OTHER_ID] NUMERIC (19)    NOT NULL,
    [QUANTITY] NUMERIC (16, 6) NULL,
    [version]  INT             NOT NULL,
    CONSTRAINT [ICS_OTHER_CUSTOM_DEST_PK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2],
    CONSTRAINT [ICS_OTHER_CUSTOM_DEST$FK_ICS_OTHER_CUSTOM_DEST_ICS_OTHER] FOREIGN KEY ([OTHER_ID]) REFERENCES [aimp2].[ICS_OTHER] ([ID])
);

