CREATE TABLE [aimp2].[ICS_ZCP_ADDRESS] (
    [ID]            NUMERIC (19)  NOT NULL,
    [ZIP_CODE]      NVARCHAR (9)  NULL,
    [COUNTRY]       NVARCHAR (2)  NULL,
    [CITY]          NVARCHAR (35) NULL,
    [STREET_AND_NO] NVARCHAR (70) NULL,
    [version]       INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_ADDRESS$PK_ICS_ZCP_ADDRESS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIMP2]
);

