CREATE TABLE [emcs2].[AD_Dokument] (
    [Id]                                        NUMERIC (38)    NOT NULL,
    [ARC]                                       VARCHAR (21)    NOT NULL,
    [Status]                                    VARCHAR (20)    NOT NULL,
    [NrPorzadkowy]                              NUMERIC (2)     NULL,
    [LRN]                                       NVARCHAR (66)   NOT NULL,
    [MRN]                                       VARCHAR (21)    NULL,
    [CzyMiejsceWysylkiKrajowe]                  CHAR (1)        NOT NULL,
    [NadawcaNRA]                                VARCHAR (13)    NOT NULL,
    [NadawcaEmail]                              VARCHAR (100)   NULL,
    [CzyPrzemieszczenieKrajowe]                 CHAR (1)        NULL,
    [OdbiorcaNRA]                               VARCHAR (13)    NULL,
    [OdbiorcaPrzekierowanieEmail]               VARCHAR (100)   NULL,
    [KodPrzemieszczenia]                        VARCHAR (1)     NULL,
    [DataPowiadomieniaKontroli]                 DATETIME2 (6)   NULL,
    [DataCzasZatwierdzeniaAD]                   DATETIME2 (6)   NULL,
    [DataEksportu]                              DATETIME2 (6)   NULL,
    [DataUniewaznienia]                         DATETIME2 (6)   NULL,
    [DataCzasZatwierdzeniaUzup]                 DATETIME2 (6)   NULL,
    [DataRaportuODostarczeniu]                  DATETIME2 (6)   NULL,
    [DataCzasWysylki]                           DATETIME2 (6)   NOT NULL,
    [CzyJestUstawionyCzasWysylki]               CHAR (1)        NOT NULL,
    [TypZgloszenia]                             VARCHAR (1)     NOT NULL,
    [KodRodzMiejscaPochRozpPrzem]               VARCHAR (1)     NOT NULL,
    [KodRodzMiejscaPrzezn]                      VARCHAR (1)     NOT NULL,
    [CzasPrzewozu]                              VARCHAR (3)     NOT NULL,
    [OrganizacjaPrzewozu]                       VARCHAR (1)     NOT NULL,
    [FlagaOdroczeniaPotwierdzenia]              CHAR (1)        NOT NULL,
    [NrFaktury]                                 VARCHAR (35)    NOT NULL,
    [DataFaktury]                               DATETIME2 (0)   NULL,
    [WysylajacyNrAkcyzowy]                      VARCHAR (13)    NOT NULL,
    [WysylajacyNazwa]                           NVARCHAR (546)  NOT NULL,
    [WysylajacyUlica]                           NVARCHAR (195)  NOT NULL,
    [WysylajacyNrDomu]                          NVARCHAR (33)   NULL,
    [WysylajacyKodPocztowy]                     NVARCHAR (30)   NOT NULL,
    [WysylajacyMiejscowosc]                     NVARCHAR (150)  NOT NULL,
    [WysylajacyKodJezyka]                       VARCHAR (2)     NOT NULL,
    [MiejsceWysylkiNrSkladuPod]                 VARCHAR (13)    NULL,
    [MiejsceWysylkiNazwaPodm]                   NVARCHAR (546)  NULL,
    [MiejsceWysylkiUlica]                       NVARCHAR (195)  NULL,
    [MiejsceWysylkiNrDomu]                      NVARCHAR (33)   NULL,
    [MiejsceWysylkiKodPocztowy]                 NVARCHAR (30)   NULL,
    [MiejsceWysylkiMiejscowosc]                 NVARCHAR (150)  NULL,
    [MiejsceWysylkiKodJezyka]                   VARCHAR (2)     NULL,
    [UrzadNadzoruWMiejscuWysylki]               VARCHAR (8)     NOT NULL,
    [UrzadKontroliWMiejscuWysylki]              VARCHAR (8)     NULL,
    [OddzialDoKontroliWMiejscuZgloszenia]       VARCHAR (8)     NULL,
    [OdbierajacyIdentyfikacja]                  NVARCHAR (48)   NULL,
    [OdbierajacyNazwa]                          NVARCHAR (546)  NULL,
    [OdbierajacyUlica]                          NVARCHAR (195)  NULL,
    [OdbierajacyNrDomu]                         NVARCHAR (33)   NULL,
    [OdbierajacyKodPocztowy]                    NVARCHAR (30)   NULL,
    [OdbierajacyMiejscowosc]                    NVARCHAR (150)  NULL,
    [OdbierajacyKodJezyka]                      VARCHAR (2)     NULL,
    [UzupOdbierajacyKodKraju]                   VARCHAR (2)     NULL,
    [UzupOdbierajacyNrSwiadectwaZwol]           VARCHAR (255)   NULL,
    [CzyOdbierajacyZmieniony]                   CHAR (1)        NOT NULL,
    [MiejsceDostawyIdentyfikacja]               NVARCHAR (48)   NULL,
    [MiejsceDostawyNazwaPodm]                   NVARCHAR (546)  NULL,
    [MiejsceDostawyUlica]                       NVARCHAR (195)  NULL,
    [MiejsceDostawyNrDomu]                      NVARCHAR (33)   NULL,
    [MiejsceDostawyKodPocztowy]                 NVARCHAR (30)   NULL,
    [MiejsceDostawyMiejscowosc]                 NVARCHAR (150)  NULL,
    [MiejsceDostawyKodJezyka]                   VARCHAR (2)     NULL,
    [UrzadNadzoruWMiejscuOdbioru]               VARCHAR (8)     NULL,
    [UrzadKontroliWMiejscuOdbioru]              VARCHAR (8)     NULL,
    [GwarantKodRodz]                            VARCHAR (4)     NULL,
    [GRN]                                       VARCHAR (17)    NULL,
    [OdbierajacyTIN]                            VARCHAR (12)    NULL,
    [GwarantTIN]                                VARCHAR (12)    NULL,
    [KwotaGwarancji]                            NUMERIC (38, 2) NULL,
    [PozostalaKwotaGwarancji]                   NUMERIC (38, 2) NULL,
    [BrakujacaKwotaGwarancji]                   NUMERIC (38, 2) NULL,
    [ManualneZwolnienieKwotyGwarancji]          NUMERIC (38, 2) NULL,
    [Gwarant1NrAkcyzowy]                        VARCHAR (13)    NULL,
    [Gwarant1Nazwa]                             NVARCHAR (546)  NULL,
    [Gwarant1Ulica]                             NVARCHAR (195)  NULL,
    [Gwarant1NrDomu]                            NVARCHAR (33)   NULL,
    [Gwarant1KodPocztowy]                       NVARCHAR (30)   NULL,
    [Gwarant1Miejscowosc]                       NVARCHAR (150)  NULL,
    [Gwarant1NrVAT]                             VARCHAR (35)    NULL,
    [Gwarant1KodJezyka]                         VARCHAR (2)     NULL,
    [Gwarant2NrAkcyzowy]                        VARCHAR (13)    NULL,
    [Gwarant2Nazwa]                             NVARCHAR (546)  NULL,
    [Gwarant2Ulica]                             NVARCHAR (195)  NULL,
    [Gwarant2NrDomu]                            NVARCHAR (33)   NULL,
    [Gwarant2KodPocztowy]                       NVARCHAR (30)   NULL,
    [Gwarant2Miejscowosc]                       NVARCHAR (150)  NULL,
    [Gwarant2NrVAT]                             VARCHAR (35)    NULL,
    [Gwarant2KodJezyka]                         VARCHAR (2)     NULL,
    [TransportKodRodz]                          VARCHAR (2)     NOT NULL,
    [OrganizatorTranspNrVAT]                    VARCHAR (35)    NULL,
    [OrganizatorTranspNazwa]                    NVARCHAR (546)  NULL,
    [OrganizatorTranspUlica]                    NVARCHAR (195)  NULL,
    [OrganizatorTranspNrDomu]                   NVARCHAR (33)   NULL,
    [OrganizatorTranspKodPocztowy]              NVARCHAR (30)   NULL,
    [OrganizatorTranspMiejscowosc]              NVARCHAR (150)  NULL,
    [OrganizatorTranspKodJezyka]                VARCHAR (2)     NULL,
    [PierwszyPrzewoznikNrVAT]                   VARCHAR (35)    NULL,
    [PierwszyPrzewoznikNazwa]                   NVARCHAR (546)  NULL,
    [PierwszyPrzewoznikUlica]                   NVARCHAR (195)  NULL,
    [PierwszyPrzewoznikNrDomu]                  NVARCHAR (33)   NULL,
    [PierwszyPrzewoznikKodPocztowy]             NVARCHAR (30)   NULL,
    [PierwszyPrzewoznikMiejscowosc]             NVARCHAR (150)  NULL,
    [PierwszyPrzewoznikKodJezyka]               VARCHAR (2)     NULL,
    [CzyPrzewoznikZmieniony]                    CHAR (1)        NOT NULL,
    [CzySkontrolowanoMiejsceWysylki]            CHAR (1)        NULL,
    [CzySkontrolowanoMiejsceDostawy]            CHAR (1)        NULL,
    [CzyPowiadomionoODostarczeniu]              CHAR (1)        NULL,
    [CzyOpozniony]                              CHAR (1)        NOT NULL,
    [CzyWyjasnieniaZgloszonePrzezWysylajacego]  CHAR (1)        NOT NULL,
    [CzyWyjasnieniaZgloszonePrzezOdbierajacego] CHAR (1)        NOT NULL,
    [CzyPrzemieszczeniePrzeterminowane]         CHAR (1)        NOT NULL,
    [AERZnalezioneRozbiez]                      CHAR (1)        NULL,
    [NadrzednyARC]                              VARCHAR (21)    NULL,
    [DataOdrzuceniaLubOstrzezenia]              DATETIME2 (6)   NULL,
    [DataPodzialuPrzesylki]                     DATETIME2 (6)   NULL,
    [TransportDodatkoweInfo]                    NVARCHAR (1050) NULL,
    [TransportDodatkoweInfoKodJezyka]           VARCHAR (2)     NULL,
    [KodWyrobuAkcyzowego]                       VARCHAR (500)   NULL,
    [GRNDlaZabezpMagazyn]                       VARCHAR (17)    NULL,
    [TINWysylajacegoDlaZabezpMagazyn]           VARCHAR (12)    NULL,
    [KwotaGwarancjiDlaZabezpMagazyn]            NUMERIC (38, 2) NULL,
    [PozostalaGwaracjaDlaZabezpMagazyn]         NUMERIC (38, 2) NULL,
    [OdbierajacyEORI]                           VARCHAR (17)    NULL,
    CONSTRAINT [AD_Dokument$PK_AD_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC)
);

