CREATE TABLE [emcs2].[AD_Podmiot] (
    [NRA]                    VARCHAR (13)    COLLATE Polish_CS_AS NOT NULL,
    [Typ]                    NVARCHAR (15)   NOT NULL,
    [Nazwa]                  NVARCHAR (900)  NOT NULL,
    [NIP]                    NVARCHAR (105)  NOT NULL,
    [REGON]                  NVARCHAR (42)   NULL,
    [KodKraju]               NVARCHAR (6)    NOT NULL,
    [Ulica]                  NVARCHAR (210)  NULL,
    [NrDomu]                 NVARCHAR (33)   NOT NULL,
    [NrLokalu]               NVARCHAR (30)   NULL,
    [Miejscowosc]            NVARCHAR (180)  NULL,
    [KodPocztowy]            NVARCHAR (30)   NOT NULL,
    [Poczta]                 NVARCHAR (180)  NULL,
    [UCNadzoru]              VARCHAR (8)     NULL,
    [ObowiazujeOd]           DATETIME2 (0)   NOT NULL,
    [ObowiazujeDo]           DATETIME2 (0)   NOT NULL,
    [Wysylajacy]             VARCHAR (13)    NULL,
    [IntDomyslny]            NVARCHAR (3)    NULL,
    [PodstawowyEmail]        NVARCHAR (381)  NULL,
    [Email]                  NVARCHAR (720)  NULL,
    [WSLogin]                NVARCHAR (60)   NULL,
    [WSHaslo]                NVARCHAR (60)   NULL,
    [WSAdres]                NVARCHAR (3072) NULL,
    [UCWydania]              VARCHAR (8)     NOT NULL,
    [WSEmcsHaslo]            NVARCHAR (60)   NULL,
    [WSOdciskPalca]          NVARCHAR (750)  NULL,
    [CzyDostawaBezposrednia] CHAR (1)        NULL,
    [Wlasciciel]             VARCHAR (13)    NULL,
    [IDSISC]                 VARCHAR (200)   NULL,
    CONSTRAINT [AD_Podmiot$PK_AD_Podmiot] PRIMARY KEY CLUSTERED ([NRA] ASC, [Typ] ASC)
);

