CREATE TABLE [emcs2].[AD_Wyrob] (
    [Id]                            NUMERIC (38)    NOT NULL,
    [IdPozycjiTowarowej]            FLOAT (53)      NOT NULL,
    [IdPozycjiTowarowejTekst]       VARCHAR (3)     NOT NULL,
    [KategoriaWyrobuAkcyzowego]     VARCHAR (1)     NOT NULL,
    [KodWyrobuAkcyzowego]           VARCHAR (4)     NOT NULL,
    [KodCN]                         VARCHAR (8)     NOT NULL,
    [Ilosc]                         NUMERIC (18, 3) NULL,
    [PozostalaIlosc]                NUMERIC (18, 3) NULL,
    [IloscDodJednMiary]             NUMERIC (18, 3) NULL,
    [IloscDodJednMiaryPoOdbiorze]   NUMERIC (18, 3) NULL,
    [MasaBrutto]                    NUMERIC (17, 2) NULL,
    [PozostalaWagaBrutto]           NUMERIC (17, 2) NULL,
    [MasaNetto]                     NUMERIC (17, 2) NULL,
    [PozostalaWagaNetto]            NUMERIC (17, 2) NULL,
    [ZawartoscAlkoholu]             NUMERIC (7, 2)  NULL,
    [StopienPlato]                  NUMERIC (7, 2)  NULL,
    [TypPaliwa]                     VARCHAR (1)     NULL,
    [OlejeNiebarwioneINieoznaczane] CHAR (1)        NULL,
    [IloscDodanychBiokomponentow]   NUMERIC (18, 3) NULL,
    [MaksymalnaCenaDetaliczna]      NUMERIC (7, 2)  NULL,
    [ZnakiAkcyzy]                   NVARCHAR (1050) NULL,
    [ZnakAkcyzy]                    CHAR (1)        NULL,
    [MiejscePochodzenia]            NVARCHAR (1050) NULL,
    [WielkoscProducenta]            VARCHAR (15)    NULL,
    [Gestosc]                       NUMERIC (7, 2)  NULL,
    [OpisHandlowy]                  NVARCHAR (1050) NULL,
    [MarkaWyrobow]                  NVARCHAR (1050) NULL,
    [KategoriaWyrobuWiniarskiego]   VARCHAR (1)     NULL,
    [KodStrefyUprawyWinorosli]      VARCHAR (2)     NULL,
    [KrajTrzeciPochodzeniaWino]     VARCHAR (2)     NULL,
    [DodInfWino]                    NVARCHAR (1050) NULL,
    [ZnakiAkcyzyKodJezyka]          VARCHAR (2)     NULL,
    [MiejscePochodzeniaKodJezyka]   VARCHAR (2)     NULL,
    [OpisHandlowyKodJezyka]         VARCHAR (2)     NULL,
    [MarkaWyrobowKodJezyka]         VARCHAR (2)     NULL,
    [InneInformacjeKodJezyka]       VARCHAR (2)     NULL,
    [NiedoborLubNadwyzka]           VARCHAR (1)     NULL,
    [IloscNiedoboruLubNadwyzki]     NUMERIC (18, 3) NULL,
    [KwotaGwarancji]                NUMERIC (38, 2) NULL,
    [PozostalaKwotaGwarancji]       NUMERIC (38, 2) NULL,
    [BrakujacaKwotaGwarancji]       NUMERIC (38, 2) NULL,
    [PotwProduktDostarczony]        CHAR (1)        NOT NULL,
    [AERPozycjaNumer]               FLOAT (53)      NULL,
    [AERNiedoborLubNadwyzka]        NUMERIC (18, 3) NULL,
    [IdDokAD]                       NUMERIC (38)    NULL,
    [BiokomponentyCzySpelWymJakosc] CHAR (1)        NULL,
    [OstatnioDostIlosc]             NUMERIC (18, 3) NULL,
    [OplataPaliwowaKwota]           NUMERIC (38, 2) NULL,
    [OplataPaliwowaPozostalaKwota]  NUMERIC (38, 2) NULL,
    [OplataPaliwowaUbytekKwota]     NUMERIC (38, 2) NULL,
    [CzyStawkaZerowaDlaWyrobu]      CHAR (1)        NULL,
    CONSTRAINT [AD_Wyrob$PK_AD_Wyrob] PRIMARY KEY CLUSTERED ([Id] ASC)
);

