CREATE TABLE [emcs2].[AD_Zadanie] (
    [Id]                        NUMERIC (38)    NOT NULL,
    [Status]                    VARCHAR (1)     NOT NULL,
    [TypZadania]                VARCHAR (40)    NOT NULL,
    [TerminPlatnosci]           DATETIME2 (0)   NULL,
    [OdpowiedzialnaRola]        NUMERIC (38)    NULL,
    [OdpowiedzialnyUzytkownik]  NUMERIC (10)    NULL,
    [UrzadCelnyNrRef]           VARCHAR (8)     NULL,
    [Tytul]                     VARCHAR (250)   NOT NULL,
    [Opis]                      NVARCHAR (4000) NULL,
    [IdDokAD]                   NUMERIC (38)    NULL,
    [IdKomunikat]               NUMERIC (38)    NULL,
    [PodmiotIdentyfikacja]      NVARCHAR (48)   NULL,
    [PodmiotNazwa]              NVARCHAR (546)  NULL,
    [PodmiotUlica]              NVARCHAR (195)  NULL,
    [PodmiotNrDomu]             NVARCHAR (66)   NULL,
    [PodmiotKodPocztowy]        NVARCHAR (30)   NULL,
    [PodmiotMiejscowosc]        NVARCHAR (150)  NULL,
    [UzytkownikOpis]            NVARCHAR (4000) NULL,
    [KodPowoduOdrzuceniaCla]    NUMERIC (1)     NULL,
    [NrRefDokumentu]            VARCHAR (21)    NULL,
    [DecyzjaKontroliDomyslna]   CHAR (1)        NULL,
    [DecyzjaKontroli]           CHAR (1)        NULL,
    [idKomunikatuRaportu]       NUMERIC (38)    NULL,
    [Ilosc]                     NUMERIC (38, 2) NULL,
    [CzyPrawidlowaOperacjaOSOZ] CHAR (1)        NULL,
    [idKomuniktuBledu]          NUMERIC (38)    NULL,
    [DataUtworzenia]            DATETIME2 (6)   NOT NULL,
    [DataZmian]                 DATETIME2 (6)   NULL,
    [ZmianaOpis]                NVARCHAR (4000) NULL,
    [ZmienionePrzez]            VARCHAR (50)    NULL,
    [WersjaAudytu]              NUMERIC (38)    NULL,
    [ARC]                       VARCHAR (21)    NULL,
    [LRN]                       NVARCHAR (66)   NULL,
    [NazwaMiejscaKontroli]      NVARCHAR (546)  NULL,
    [CzyZadanieKontroli]        CHAR (1)        NULL,
    [DataPrzeladunku]           DATETIME2 (6)   NULL,
    CONSTRAINT [AD_Zadanie$PK_AD_Zadanie] PRIMARY KEY CLUSTERED ([Id] ASC)
);

