CREATE TABLE [ncts2].[OperacjeTranzytowe] (
    [Id]                                         BIGINT          NOT NULL,
    [DataUtworzenia]                             DATETIME        NULL,
    [DataModyfikacji]                            DATETIME        NULL,
    [DataZwolnienia]                             DATETIME        NULL,
    [UCWyjscia]                                  NVARCHAR (8)    NULL,
    [UCPrzeznaczenia]                            NVARCHAR (8)    NULL,
    [NadawcaNazwa]                               NVARCHAR (35)   NULL,
    [NadawcaUlicaNumer]                          NVARCHAR (100)  NULL,
    [NadawcaKodPocztowy]                         NVARCHAR (9)    NULL,
    [NadawcaMiejscowosc]                         NVARCHAR (52)   NULL,
    [NadawcaKraj]                                NVARCHAR (2)    NULL,
    [NadawcaTIN]                                 NVARCHAR (17)   NULL,
    [OdbiorcaNazwa]                              NVARCHAR (35)   NULL,
    [OdbiorcaUlicaNumer]                         NVARCHAR (100)  NULL,
    [OdbiorcaKodPocztowy]                        NVARCHAR (9)    NULL,
    [OdbiorcaMiejscowosc]                        NVARCHAR (52)   NULL,
    [OdbiorcaKraj]                               NVARCHAR (2)    NULL,
    [OdbiorcaTIN]                                NVARCHAR (17)   NULL,
    [GlownyZobowiazanyNazwa]                     NVARCHAR (35)   NULL,
    [GlownyZobowiazanyUlicaNumer]                NVARCHAR (100)  NULL,
    [GlownyZobowiazanyKodPocztowy]               NVARCHAR (9)    NULL,
    [GlownyZobowiazanyMiejscowosc]               NVARCHAR (52)   NULL,
    [GlownyZobowiazanyKraj]                      NVARCHAR (2)    NULL,
    [GlownyZobowiazanyTIN]                       NVARCHAR (17)   NULL,
    [GlownyZobowiazanyPrzedstawicielTIN]         NVARCHAR (17)   NULL,
    [UpowaznionyOdbiorcaTIN]                     NVARCHAR (17)   NULL,
    [TransportRodzaj]                            NVARCHAR (2)    NULL,
    [TransportZnaki]                             NVARCHAR (27)   NULL,
    [TransportKraj]                              NVARCHAR (2)    NULL,
    [TransportNaGranicyRodzaj]                   NVARCHAR (2)    NULL,
    [TransportNaGranicyZnaki]                    NVARCHAR (27)   NULL,
    [TransportNaGranicyKraj]                     NVARCHAR (2)    NULL,
    [WynikKontroliKod]                           NVARCHAR (2)    NULL,
    [WynikKontroliTerminDostarczenia]            DATETIME        NULL,
    [ZamknieciaCelneIlosc]                       INT             NULL,
    [ZamknieciaCelneNakladajacy]                 NVARCHAR (35)   NULL,
    [BezpieczenstwoSpecWarunki]                  NVARCHAR (1)    NULL,
    [BezpieczenstwoFormaPlatnosci]               NVARCHAR (1)    NULL,
    [BezpieczenstwoNrReferencyjnyPrzesylki]      NVARCHAR (70)   NULL,
    [BezpieczenstwoNrReferencyjnyPrzewozu]       NVARCHAR (35)   NULL,
    [BezpieczenstwoMiejsceRozladunku]            NVARCHAR (35)   NULL,
    [BezpieczenstwoNadawcaNazwa]                 NVARCHAR (35)   NULL,
    [BezpieczenstwoNadawcaUlicaNumer]            NVARCHAR (100)  NULL,
    [BezpieczenstwoNadawcaKodPocztowy]           NVARCHAR (9)    NULL,
    [BezpieczenstwoNadawcaMiejscowosc]           NVARCHAR (52)   NULL,
    [BezpieczenstwoNadawcaKraj]                  NVARCHAR (2)    NULL,
    [BezpieczenstwoNadawcaTIN]                   NVARCHAR (17)   NULL,
    [BezpieczenstwoOdbiorcaNazwa]                NVARCHAR (35)   NULL,
    [BezpieczenstwoOdbiorcaUlicaNumer]           NVARCHAR (100)  NULL,
    [BezpieczenstwoOdbiorcaKodPocztowy]          NVARCHAR (9)    NULL,
    [BezpieczenstwoOdbiorcaMiejscowosc]          NVARCHAR (52)   NULL,
    [BezpieczenstwoOdbiorcaKraj]                 NVARCHAR (2)    NULL,
    [BezpieczenstwoOdbiorcaTIN]                  NVARCHAR (17)   NULL,
    [BezpieczenstwoPrzewoznikNazwa]              NVARCHAR (35)   NULL,
    [BezpieczenstwoPrzewoznikUlicaNumer]         NVARCHAR (100)  NULL,
    [BezpieczenstwoPrzewoznikKodPocztowy]        NVARCHAR (9)    NULL,
    [BezpieczenstwoPrzewoznikMiejscowosc]        NVARCHAR (52)   NULL,
    [BezpieczenstwoPrzewoznikKraj]               NVARCHAR (2)    NULL,
    [BezpieczenstwoPrzewoznikTIN]                NVARCHAR (17)   NULL,
    [IE015ZgloszenieData]                        DATETIME        NULL,
    [TypDeklaracji]                              NVARCHAR (5)    NULL,
    [LiczbaPozycji]                              INT             NULL,
    [LiczbaOpakowan]                             INT             NULL,
    [KrajWysylki]                                NVARCHAR (2)    NULL,
    [KrajPrzeznaczenia]                          NVARCHAR (2)    NULL,
    [MasaBrutto]                                 NUMERIC (14, 3) NULL,
    [MiejsceZaladunku]                           NVARCHAR (17)   NULL,
    [ProceduraUproszczonaUCWyjscia]              BIT             NULL,
    [GlownyZobowiazanyTirholder]                 BIT             NULL,
    [Kontenery]                                  BIT             NULL,
    [LRN]                                        NVARCHAR (21)   NULL,
    [MRN]                                        NVARCHAR (18)   NULL,
    [StatusUCPrzeznaczeniaData]                  DATETIME        NULL,
    [StatusAnalizyRyzykaUCWyjscia]               NVARCHAR (1)    NULL,
    [FlagaStopUCWyjscia]                         BIT             NULL,
    [StatusUCWyjscia]                            NVARCHAR (8)    NULL,
    [DataZmianyStatusuUCWyjscia]                 DATETIME        NULL,
    [IE015ZgloszenieMiejsce]                     NVARCHAR (35)   NULL,
    [IE015ZgloszenieNazwiskoImie]                NVARCHAR (35)   NULL,
    [IE015ZgloszenieStanowisko]                  NVARCHAR (35)   NULL,
    [MiejsceUznane]                              NVARCHAR (1)    NULL,
    [RyzykoUCWyjscia]                            INT             NULL,
    [RyzykoUCPrzeznaczenia]                      INT             NULL,
    [DataDokonania]                              DATETIME        NULL,
    [WiazacaTrasaPrzewozu]                       NVARCHAR (200)  NULL,
    [OdpNaZapytanieOPrzesylke]                   NVARCHAR (500)  NULL,
    [PrzedstawiajacyNazwa]                       NVARCHAR (35)   NULL,
    [PrzedstawiajacyUlicaNumer]                  NVARCHAR (100)  NULL,
    [PrzedstawiajacyKodPocztowy]                 NVARCHAR (9)    NULL,
    [PrzedstawiajacyMiejscowosc]                 NVARCHAR (52)   NULL,
    [PrzedstawiajacyKraj]                        NVARCHAR (2)    NULL,
    [PrzedstawiajacyTIN]                         NVARCHAR (17)   NULL,
    [StatusAnalizyRyzykaUCPrzeznaczenia]         NVARCHAR (1)    NULL,
    [TowaryWrazliwe]                             BIT             NULL,
    [KomunikacjaPodmiotWyjscia]                  NVARCHAR (17)   NULL,
    [KomunikacjaKrajWyjscia]                     NVARCHAR (6)    NULL,
    [KomunikacjaPodmiotPrzeznaczenia]            NVARCHAR (17)   NULL,
    [KomunikacjaKrajPrzeznaczenia]               NVARCHAR (6)    NULL,
    [ProceduraUproszczonaUCPrzeznaczenia]        BIT             NULL,
    [DataPrzyjecia]                              DATETIME        NULL,
    [StatusUCPrzeznaczenia]                      NVARCHAR (8)    NULL,
    [NrKarnetuTIR]                               NVARCHAR (11)   NULL,
    [PrzedstawiajacyPrzedstawicielTIN]           NVARCHAR (17)   NULL,
    [UCPrzeznaczeniaDeklarowany]                 NVARCHAR (8)    NULL,
    [DataPrzybycia]                              DATETIME        NULL,
    [FlagaUniewaznienieUCWyjscia]                BIT             NULL,
    [JezykTDT]                                   NVARCHAR (2)    NULL,
    [DataKontroli]                               DATETIME        NULL,
    [Bezpieczenstwo]                             BIT             NULL,
    [FlagaAEO]                                   BIT             NULL,
    [FlagaRejGwarUCWyjscia]                      NVARCHAR (1)    NULL,
    [MiejscePrzybycia]                           NVARCHAR (35)   NULL,
    [FlagaGlowZobPozwNaProcUpro]                 BIT             NULL,
    [GlownyZobowiazanyPrzedstawicielNazwa]       NVARCHAR (35)   NULL,
    [GlownyZobowiazanyPrzedstawicieUlicaNumer]   NVARCHAR (100)  NULL,
    [GlownyZobowiazanyPrzedstawicielKodPocztowy] NVARCHAR (9)    NULL,
    [GlownyZobowiazanyPrzedstawicielMiejscowosc] NVARCHAR (52)   NULL,
    [GlownyZobowiazanyPrzedstawicielKraj]        NVARCHAR (2)    NULL,
    [TransportZnakiJezyk]                        NVARCHAR (2)    NULL,
    [FlagaUniewaznienieAES]                      BIT             NULL,
    [FlagaOstrzezenia]                           BIT             NULL,
    [PrzedstawiajacyNrPozwolenia]                NVARCHAR (35)   NULL,
    CONSTRAINT [OperacjeTranzytowe_pk] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_NCTS2]
);

