CREATE TABLE [ncts2].[RefUrzCel] (
    [Id]                         BIGINT         NOT NULL,
    [KodUC]                      NVARCHAR (8)   NULL,
    [KodUCGlowneBiuro]           NVARCHAR (8)   NULL,
    [KodUCWyzszyOrgan]           NVARCHAR (8)   NULL,
    [KodUCPrzejecia]             NVARCHAR (8)   NULL,
    [KodUCPoszukiwania]          NVARCHAR (8)   NULL,
    [KodUCPoboru]                NVARCHAR (8)   NULL,
    [KodKraju]                   NVARCHAR (2)   NULL,
    [KodMiasta]                  NVARCHAR (3)   NULL,
    [KodRegionu]                 NVARCHAR (3)   NULL,
    [DataWejsciaNCTS]            DATETIME       NULL,
    [NajblizszyUrzad]            NVARCHAR (175) NULL,
    [KodPocztowy]                NVARCHAR (9)   NULL,
    [Fax]                        NVARCHAR (35)  NULL,
    [Telefon]                    NVARCHAR (35)  NULL,
    [Telex]                      NVARCHAR (35)  NULL,
    [AdresEmail]                 NVARCHAR (70)  NULL,
    [KodPolozeniaGeograficznego] NVARCHAR (6)   NULL,
    [PodmiotPrzeznaczenia]       BIT            NULL,
    [WaznyOd]                    DATETIME       NULL,
    [WaznyDo]                    DATETIME       NULL,
    CONSTRAINT [RefUrzCel_pk] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_NCTS2]
);

