CREATE TABLE [ncts2].[WynikiKontroli] (
    [Id]                       BIGINT          NOT NULL,
    [IdOperacjiTranzytowej]    BIGINT          NULL,
    [DataKontroli]             DATETIME        NULL,
    [KodWyniku]                NVARCHAR (2)    NULL,
    [WyjasnianieNiezgodnosci]  BIT             NULL,
    [ZamknieciaPrawidlowe]     BIT             NULL,
    [LosoweTypowanie]          BIT             NULL,
    [ZwolnienieBezZastrzezen]  BIT             NULL,
    [KarnetTIRNieDotyczy]      BIT             NULL,
    [NumerStronyKarnetuTIR]    NVARCHAR (2)    NULL,
    [KarnetTIRTypRozladunku]   NVARCHAR (1)    NULL,
    [KarnetTIRNumerRozladunku] NVARCHAR (2)    NULL,
    [Skontrolowal]             NVARCHAR (35)   NULL,
    [Uwagi]                    NVARCHAR (350)  NULL,
    [UwagiJezyk]               NVARCHAR (2)    NULL,
    [LiczbaPozycji]            SMALLINT        NULL,
    [LiczbaPozycjiUwagi]       NVARCHAR (140)  NULL,
    [MasaBrutto]               NUMERIC (14, 3) NULL,
    [MasaBruttoUwagi]          NVARCHAR (140)  NULL,
    [LiczbaOpakowan]           INT             NULL,
    [LiczbaOpakowanUwagi]      NVARCHAR (140)  NULL,
    [TransportZnaki]           NVARCHAR (140)  NULL,
    [TransportZnakiUwagi]      NVARCHAR (140)  NULL,
    [TransportKraj]            NVARCHAR (2)    NULL,
    [TransportKrajUwagi]       NVARCHAR (140)  NULL,
    [DataUtworzenia]           DATETIME        NULL,
    CONSTRAINT [WynikiKontroli_pk] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_NCTS2],
    CONSTRAINT [WynikiKontroli_IdOperacjiTranzytowej_OperacjeTranzytowe_fk] FOREIGN KEY ([IdOperacjiTranzytowej]) REFERENCES [ncts2].[OperacjeTranzytowe] ([Id])
);

