CREATE TABLE [zef2].[AtrybutyKlasyfikacji] (
    [KodAtrybutu]                       NVARCHAR (10)  NOT NULL,
    [Nazwa]                             NVARCHAR (256) NOT NULL,
    [CzyZablokowane]                    INT            NOT NULL,
    [TypAtrybutuKlasyfikacji]           INT            NOT NULL,
    [RodzajWydatku]                     INT            NOT NULL,
    [OdwolanieDoAtrybutuNadrzednego]    BIGINT         NOT NULL,
    [CzyWymaganyProgram]                INT            NOT NULL,
    [CzyWymaganyProjekt]                INT            NOT NULL,
    [KodGrupyZatrudnienia]              BIGINT         NOT NULL,
    [GrupaEkonomicznaOgolna]            BIGINT         NOT NULL,
    [CzyWidocznyWWymiarze]              INT            NOT NULL,
    [RodzajBudzetu]                     BIGINT         NOT NULL,
    [DataGodzOstatnModyfikacji]         DATETIME       NOT NULL,
    [IdUzytkownikaOstatnModyfikujacego] NVARCHAR (8)   NOT NULL,
    [IdTransakcjiModyfikacji]           BIGINT         NOT NULL,
    [DataGodzUtworzeniaRekordu]         DATETIME       NOT NULL,
    [IdUzytkownikaTworzacego]           NVARCHAR (8)   NOT NULL,
    [IdTransakcjiUtworzeniaRekordu]     BIGINT         NOT NULL,
    [WersjaRekordu]                     INT            NOT NULL,
    [Partycja]                          BIGINT         NOT NULL,
    [IdentyfikatorRekordu]              BIGINT         NOT NULL,
    [CzyWymaganaGrupaZatrDlaLimitow]    INT            NOT NULL,
    [CzyRozdzialMacierzystyIC]          INT            NOT NULL,
    [CzyRozdzialMacierzystyIS]          INT            NOT NULL,
    [CzyRozdzialMacierzystyUKS]         INT            NOT NULL,
    CONSTRAINT [AtrybutyKlasyfikacji_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC) ON [FG_ZEF2],
    CHECK ([IdentyfikatorRekordu]<>(0))
);

