CREATE TABLE [zef2].[DefinicjaEtapowZatwierdzen] (
    [WartoscStanu]                               NVARCHAR (20)    NOT NULL,
    [CzyGotowyDoKsiegowania]                     INT              NOT NULL,
    [Grupa]                                      NVARCHAR (10)    NOT NULL,
    [CzySprawdzArkusz]                           INT              NOT NULL,
    [CzyEdycja]                                  INT              NOT NULL,
    [GrupaZatwierdzen]                           NVARCHAR (10)    NOT NULL,
    [CzyZatwierdzenieZaksiegowanie]              INT              NOT NULL,
    [Sekwencja]                                  INT              NOT NULL,
    [AkceptacjaOdKwoty]                          NUMERIC (32, 16) NOT NULL,
    [AkceptacjaDoKwoty]                          NUMERIC (32, 16) NOT NULL,
    [CzyGotowyDoAkceptacjiCRU]                   INT              NOT NULL,
    [CzyKasowanieUmowyCRU]                       INT              NOT NULL,
    [CzyZatwierdzony]                            INT              NOT NULL,
    [CzyWyslanoDoJednostkiNadrzednej]            INT              NOT NULL,
    [CzyAktywneAnulowanie]                       INT              NOT NULL,
    [CzyPrzekazaneDoNadrzednego]                 INT              NOT NULL,
    [CzyPrzekazaneDoPodrzednego]                 INT              NOT NULL,
    [GrupaUprawnionaDoEdytowania]                NVARCHAR (10)    NOT NULL,
    [CzyWygenerowaneDoTrezora]                   INT              NOT NULL,
    [CzyZerowanieStatusu]                        INT              NOT NULL,
    [GrupaUprawnionaDoZerowaniaStatusuDok]       NVARCHAR (10)    NOT NULL,
    [GrupaUprawnionaDoCofnieciaStatusuDok]       NVARCHAR (10)    NOT NULL,
    [CzyCofanieDoPoprzStatusu]                   INT              NOT NULL,
    [CzyWylaczenieMozliwosciZmianyStatusu]       INT              NOT NULL,
    [CzyKomentarzPrzyUstawianiuNaTenStatus]      INT              NOT NULL,
    [CzyKomentarzPrzyCofaniuZTegoStatus]         INT              NOT NULL,
    [CzyKomentarzPrzyZerowaniuZTegoStatus]       INT              NOT NULL,
    [CzyPrzekazaneDoDecyzji]                     INT              NOT NULL,
    [CzyPrzekazaneDoDecyzjiNadrzednego]          INT              NOT NULL,
    [CzyBladPrzerywaPrzetwarzanie]               INT              NOT NULL,
    [AutomatycznyStatusNastepny]                 NVARCHAR (20)    NOT NULL,
    [CzyNiePrzerywacPrzetwarzanieJesliBladPlanu] INT              NOT NULL,
    [CzyEdycjaDatyKsiegowania]                   INT              NOT NULL,
    [CzyAutomatycznaAkceptacja]                  INT              NOT NULL,
    [CzyCofnieteZJednostkiNadrzednej]            INT              NOT NULL,
    [CzyPrzyjete]                                INT              NOT NULL,
    [CzySprawdzacCzyPrzyjete]                    INT              NOT NULL,
    [AutomatycznyStatusPoczatkowy]               INT              NOT NULL,
    [DataGodzOstatnModyfikacji]                  DATETIME         NOT NULL,
    [IdUzytkownikaOstatnModyfikujacego]          NVARCHAR (8)     NOT NULL,
    [IdTransakcjiModyfikacji]                    BIGINT           NOT NULL,
    [DataGodzUtworzeniaRekordu]                  DATETIME         NOT NULL,
    [IdUzytkownikaTworzacego]                    NVARCHAR (8)     NOT NULL,
    [IdTransakcjiUtworzeniaRekordu]              BIGINT           NOT NULL,
    [WersjaRekordu]                              INT              NOT NULL,
    [Partycja]                                   BIGINT           NOT NULL,
    [IdentyfikatorRekordu]                       BIGINT           NOT NULL,
    [CzyAnulowanieWniosku]                       INT              NOT NULL,
    [CzyEdycjaPolaPrzetarg]                      INT              NOT NULL,
    [CzyJednostkaInicjujaca]                     INT              NOT NULL,
    [CzyJednostkaPotwierdzajaca]                 INT              NOT NULL,
    [WartoscStanuZewnetrzna]                     NVARCHAR (20)    NOT NULL,
    [CzyAktywnaListaWeryfikacyjna]               INT              NOT NULL,
    [ListaWeryfikacyjnaDefinicjaDlaGrupy]        NVARCHAR (10)    NOT NULL,
    [CzyEdycjaZleceniaDoKasy]                    INT              NOT NULL,
    [CzyPrzyjety]                                INT              NOT NULL,
    CONSTRAINT [DefinicjaEtapowZatwierdzen_pk] PRIMARY KEY CLUSTERED ([Partycja] ASC, [GrupaZatwierdzen] ASC, [WartoscStanu] ASC) ON [FG_ZEF2]
);

