CREATE TABLE [zef2].[DefinicjaSprawozdania] (
    [CzyGenerowaneAutomatyczne]             INT            NOT NULL,
    [CzyZablokowane]                        INT            NOT NULL,
    [PlanTylkoDlaNiezerowych]               INT            NOT NULL,
    [Klasa]                                 NVARCHAR (40)  NOT NULL,
    [IdUzytkownikaTworzacego]               NVARCHAR (8)   NOT NULL,
    [DataGodzUtworzeniaRekordu]             DATETIME       NOT NULL,
    [IdTransakcjiUtworzeniaRekordu]         BIGINT         NOT NULL,
    [NazwaKlasy]                            NVARCHAR (40)  NOT NULL,
    [ObowiazujeOd]                          DATETIME       NOT NULL,
    [DomyslnyTypSprawozdZbiorczego]         BIGINT         NOT NULL,
    [DomyslnyTypSprawozdSkonsolidowanego]   BIGINT         NOT NULL,
    [DomyslnyTypSprawozd]                   BIGINT         NOT NULL,
    [Opis]                                  INT            NOT NULL,
    [TypDokumentu]                          NVARCHAR (10)  NOT NULL,
    [CzyDynamiczneWiersze]                  INT            NOT NULL,
    [GrupyZatrudnienia]                     INT            NOT NULL,
    [IndeksPola]                            INT            NOT NULL,
    [JednostkaNadrzedna]                    BIGINT         NOT NULL,
    [SeriaSprawozdZbiorczych]               NVARCHAR (15)  NOT NULL,
    [IdentyfikatorWersjiSprawozdania]       NVARCHAR (10)  NOT NULL,
    [KodGrupyDefinicji]                     BIGINT         NOT NULL,
    [TypSprawozdania]                       INT            NOT NULL,
    [WymaganaKlasyfikacja]                  INT            NOT NULL,
    [IdUzytkownikaOstatnModyfikujacego]     NVARCHAR (8)   NOT NULL,
    [DataGodzOstatnModyfikacji]             DATETIME       NOT NULL,
    [IdTransakcjiModyfikacji]               BIGINT         NOT NULL,
    [CzyImportMRDOS]                        INT            NOT NULL,
    [CzyParagraf]                           INT            NOT NULL,
    [Partycja]                              BIGINT         NOT NULL,
    [CzyCzesc]                              INT            NOT NULL,
    [Czesc]                                 INT            NOT NULL,
    [PoziomKsiegowania]                     INT            NOT NULL,
    [CzyKsiegowaneNaKonta]                  INT            NOT NULL,
    [CzyKsiegowanieDoTransakcjiFinansowych] INT            NOT NULL,
    [CzyKodProgramu]                        INT            NOT NULL,
    [CzyDostepnyKodProjektu]                INT            NOT NULL,
    [TypDokumentuChronionego]               NVARCHAR (10)  NOT NULL,
    [IdentyfikatorRekordu]                  BIGINT         NOT NULL,
    [Adresat]                               NVARCHAR (100) NOT NULL,
    [WersjaRekordu]                         INT            NOT NULL,
    [CzyKolumnaUwagi]                       INT            NOT NULL,
    [NazwaElementuMenu]                     NVARCHAR (40)  NOT NULL,
    [CzyKodWiersza]                         INT            NOT NULL,
    [CzyDzial]                              INT            NOT NULL,
    [CzyRozdzial]                           INT            NOT NULL,
    [NazwaKlasyImportuTrezor]               NVARCHAR (40)  NOT NULL,
    [SeriaZalacznikow]                      NVARCHAR (15)  NOT NULL,
    [CzyDzialanie]                          INT            NOT NULL,
    [DokumentXML]                           NVARCHAR (40)  NOT NULL,
    [PrzedzialXML]                          INT            NOT NULL,
    [DokumentPodrzednyXML]                  INT            NOT NULL,
    [TAGXML]                                NVARCHAR (50)  NOT NULL,
    CONSTRAINT [DefinicjaSprawozdania_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC) ON [FG_ZEF2],
    CHECK ([IdentyfikatorRekordu]<>(0))
);

