CREATE TABLE [zef2].[GrupaDefinicjiSprawozdan] (
    [IdentyfikatorRekordu]              BIGINT         NOT NULL,
    [TypDefSprawozdania]                NVARCHAR (15)  NOT NULL,
    [Opis]                              NVARCHAR (255) NOT NULL,
    [TypSprawozdania]                   INT            NOT NULL,
    [RodzajSprawozdania]                NVARCHAR (20)  NOT NULL,
    [TypJednostkiSprawozdania]          INT            NOT NULL,
    [RodzajOkresu]                      INT            NOT NULL,
    [RodzajDokMRDOS]                    NVARCHAR (20)  NOT NULL,
    [CzyImportMRDOS]                    INT            NOT NULL,
    [CzySprawozdKonsolidacyjne]         INT            NOT NULL,
    [Modul]                             INT            NOT NULL,
    [CzyNaWszystkieIzby]                INT            NOT NULL,
    [KodDokumentu]                      NVARCHAR (10)  NOT NULL,
    [CzyWysylkaDoTrezora]               INT            NOT NULL,
    [KodProcesuTrezor]                  NVARCHAR (20)  NOT NULL,
    [IdUzytkownikaTworzacego]           NVARCHAR (8)   NOT NULL,
    [DataGodzUtworzeniaRekordu]         DATETIME       NOT NULL,
    [IdTransakcjiUtworzeniaRekordu]     BIGINT         NOT NULL,
    [IdUzytkownikaOstatnModyfikujacego] NVARCHAR (8)   NOT NULL,
    [DataGodzOstatnModyfikacji]         DATETIME       NOT NULL,
    [IdTransakcjiModyfikacji]           BIGINT         NOT NULL,
    [GrupaUzytkowWidocznosciSprawozd]   NVARCHAR (10)  NOT NULL,
    [WersjaRekordu]                     INT            NOT NULL,
    [Partycja]                          BIGINT         NOT NULL,
    CONSTRAINT [GrupaDefinicjiSprawozdan_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC) ON [FG_ZEF2],
    CHECK ([IdentyfikatorRekordu]<>(0))
);

