CREATE TABLE [zef2].[JednostkiOrganizacyjne] (
    [IdentyfikatorRekordu]              BIGINT         NOT NULL,
    [KodJednostki]                      NVARCHAR (10)  NOT NULL,
    [Nazwa]                             NVARCHAR (256) NOT NULL,
    [CzyZablokowane]                    INT            NOT NULL,
    [CzyDysponentIstopnia]              INT            NOT NULL,
    [CzyDysponentIIstopnia]             INT            NOT NULL,
    [CzyDysponentIIIstopnia]            INT            NOT NULL,
    [CzyDysponentIVstopnia]             INT            NOT NULL,
    [CzyDysponentVstopnia]              INT            NOT NULL,
    [JednostkaNadrzedna]                BIGINT         NOT NULL,
    [Firma]                             NVARCHAR (4)   NOT NULL,
    [PionMF]                            BIGINT         NOT NULL,
    [CzyOrganEgzekucyjny]               INT            NOT NULL,
    [KodDysponenta]                     NVARCHAR (10)  NOT NULL,
    [Czesc]                             INT            NOT NULL,
    [CzyOrganPodatkowy]                 INT            NOT NULL,
    [KodDysponentaOrganPodatkowy]       NVARCHAR (10)  NOT NULL,
    [IdentyfikatorDanychAdresowych]     BIGINT         NOT NULL,
    [AdresDecyzjiNaOdsetki]             NVARCHAR (80)  NOT NULL,
    [SzablonEmailZadaniaZaplaty]        NVARCHAR (10)  NOT NULL,
    [AdresEgzekucji]                    NVARCHAR (80)  NOT NULL,
    [UzytkownicyEgzekucji]              NVARCHAR (80)  NOT NULL,
    [NazwaSprawozdania]                 NVARCHAR (120) NOT NULL,
    [REGON]                             NVARCHAR (15)  NOT NULL,
    [CzyWidocznyWwymiarze]              INT            NOT NULL,
    [NazwaNaWydrukuTytulu]              NVARCHAR (256) NOT NULL,
    [SzablonEmailWniosekOzarachowanie]  NVARCHAR (10)  NOT NULL,
    [AdresWnioskuOzarachowanie]         NVARCHAR (80)  NOT NULL,
    [NumeracjaOdbiorcy]                 BIGINT         NOT NULL,
    [KontoOdbiorcy]                     NVARCHAR (20)  NOT NULL,
    [CzyWidocznyNaZarzadzZab]           INT            NOT NULL,
    [SkrotDysponentaMF]                 NVARCHAR (16)  NOT NULL,
    [CzyJestAdresatem]                  INT            NOT NULL,
    [NazwaLimity]                       NVARCHAR (256) NOT NULL,
    [IdentyfikatorDanychKontaktowych]   BIGINT         NOT NULL,
    [KodJednBudzetTrezor]               NVARCHAR (10)  NOT NULL,
    [DataGodzOstatnModyfikacji]         DATETIME       NOT NULL,
    [IdUzytkownikaOstatnModyfikujacego] NVARCHAR (8)   NOT NULL,
    [IdTransakcjiModyfikacji]           BIGINT         NOT NULL,
    [DataGodzUtworzeniaRekordu]         DATETIME       NOT NULL,
    [IdUzytkownikaTworzacego]           NVARCHAR (8)   NOT NULL,
    [IdTransakcjiUtworzeniaRekordu]     BIGINT         NOT NULL,
    [WersjaRekordu]                     INT            NOT NULL,
    [Partycja]                          BIGINT         NOT NULL,
    CONSTRAINT [JednostkiOrganizacyjne_pk] PRIMARY KEY CLUSTERED ([IdentyfikatorRekordu] ASC) ON [FG_ZEF2],
    CHECK ([IdentyfikatorRekordu]<>(0))
);

