CREATE TABLE [zef2].[RB27_Pozycje] (
    [IdentyfikatoRekordu]               BIGINT           NOT NULL,
    [IdSprawozdania]                    BIGINT           NOT NULL,
    [Opis]                              NVARCHAR (250)   NOT NULL,
    [NumerWiersza]                      NUMERIC (32, 16) NOT NULL,
    [Plan]                              NUMERIC (32, 16) NOT NULL,
    [Naleznosci]                        NUMERIC (32, 16) NOT NULL,
    [Potracenia]                        NUMERIC (32, 16) NOT NULL,
    [DochodyWykonane]                   NUMERIC (32, 16) NOT NULL,
    [DochodyPrzekazane]                 NUMERIC (32, 16) NOT NULL,
    [NaleznosciDoZaplatyOgolem]         NUMERIC (32, 16) NOT NULL,
    [NaleznosciDoZaplatyWTymNetto]      NUMERIC (32, 16) NOT NULL,
    [Nadplaty]                          NUMERIC (32, 16) NOT NULL,
    [KodPozycjiTrezor]                  NVARCHAR (60)    NOT NULL,
    [KodSekcjiTrezor]                   NVARCHAR (60)    NOT NULL,
    [Dzial]                             NVARCHAR (10)    NOT NULL,
    [Rozdzial]                          NVARCHAR (10)    NOT NULL,
    [Paragraf]                          NVARCHAR (10)    NOT NULL,
    [KodProjektu]                       NVARCHAR (18)    NOT NULL,
    [IdProgramu]                        NVARCHAR (18)    NOT NULL,
    [KodGrupyZatrudnienia]              NVARCHAR (10)    NOT NULL,
    [KontoKsiegowe]                     BIGINT           NOT NULL,
    [WersjaRekordu]                     INT              NOT NULL,
    [Partycja]                          BIGINT           NOT NULL,
    [IdUzytkownikaTworzacego]           NVARCHAR (8)     NOT NULL,
    [DataGodzUtworzeniaRekordu]         DATETIME         NOT NULL,
    [IdTransakcjiUtworzeniaRekordu]     BIGINT           NOT NULL,
    [AdresOdbiorcy]                     NVARCHAR (250)   NOT NULL,
    [NazwaOdbiorcy]                     NVARCHAR (200)   NOT NULL,
    [Klasyfikacja]                      BIGINT           NOT NULL,
    [Czesc]                             INT              NOT NULL,
    [Dzialanie]                         NVARCHAR (15)    NOT NULL,
    [Wymiar]                            BIGINT           NOT NULL,
    [IdUzytkownikaOstatnModyfikujacego] NVARCHAR (8)     NOT NULL,
    [DataGodzOstatnModyfikacji]         DATETIME         NOT NULL,
    [IdTransakcjiModyfikacji]           BIGINT           NOT NULL,
    [KodWiersza]                        NVARCHAR (10)    NOT NULL,
    [NazwaProgramu]                     NVARCHAR (200)   NOT NULL,
    [PrzyczynyDecyzjiUmorzenia]         INT              NOT NULL,
    [Uwagi]                             NVARCHAR (150)   NOT NULL,
    [PowodUmorzenia]                    INT              NOT NULL,
    CONSTRAINT [RB27_Pozycje_pk] PRIMARY KEY CLUSTERED ([IdentyfikatoRekordu] ASC) ON [FG_ZEF2],
    CHECK ([IdentyfikatoRekordu]<>(0))
);

