CREATE TABLE [zef2].[RBN_Pozycje] (
    [Opis]                                 NVARCHAR (250)   NOT NULL,
    [NumerWiersza]                         NUMERIC (32, 16) NOT NULL,
    [KwotaNaleznosciOgolem]                NUMERIC (32, 16) NOT NULL,
    [OgolemKolumna3]                       NUMERIC (32, 16) NOT NULL,
    [SektorFinansowPublicznych]            NUMERIC (32, 16) NOT NULL,
    [GrupaI]                               NUMERIC (32, 16) NOT NULL,
    [GrupaII]                              NUMERIC (32, 16) NOT NULL,
    [GrupaIII]                             NUMERIC (32, 16) NOT NULL,
    [GrupaIV]                              NUMERIC (32, 16) NOT NULL,
    [BankCentralny]                        NUMERIC (32, 16) NOT NULL,
    [Banki]                                NUMERIC (32, 16) NOT NULL,
    [PozostaleKrajoweInstytFinans]         NUMERIC (32, 16) NOT NULL,
    [PrzedsiebiorstwaNiefinansowe]         NUMERIC (32, 16) NOT NULL,
    [GospodarstwaDomowe]                   NUMERIC (32, 16) NOT NULL,
    [InstytNiekomercNaRzeczGospodarstwDom] NUMERIC (32, 16) NOT NULL,
    [OgolemKolumna15]                      NUMERIC (32, 16) NOT NULL,
    [PodmiotyNalezaceDoStrefyEuro]         NUMERIC (32, 16) NOT NULL,
    [PozostalePodmiotyZagraniczne]         NUMERIC (32, 16) NOT NULL,
    [KodWiersza]                           NVARCHAR (10)    NOT NULL,
    [IdSprawozdania]                       BIGINT           NOT NULL,
    [Wymiar]                               BIGINT           NOT NULL,
    [Klasyfikacja]                         BIGINT           NOT NULL,
    [Dzial]                                NVARCHAR (10)    NOT NULL,
    [Rozdzial]                             NVARCHAR (10)    NOT NULL,
    [Paragraf]                             NVARCHAR (10)    NOT NULL,
    [KodProjektu]                          NVARCHAR (18)    NOT NULL,
    [IdProgramu]                           NVARCHAR (18)    NOT NULL,
    [KodGrupyZatrudnienia]                 NVARCHAR (10)    NOT NULL,
    [KontoKsiegowe]                        BIGINT           NOT NULL,
    [DataGodzOstatnModyfikacji]            DATETIME         NOT NULL,
    [IdUzytkownikaOstatnModyfikujacego]    NVARCHAR (8)     NOT NULL,
    [IdTransakcjiModyfikacji]              BIGINT           NOT NULL,
    [DataGodzUtworzeniaRekordu]            DATETIME         NOT NULL,
    [IdUzytkownikaTworzacego]              NVARCHAR (8)     NOT NULL,
    [IdTransakcjiUtworzeniaRekordu]        BIGINT           NOT NULL,
    [WersjaRekordu]                        INT              NOT NULL,
    [Partycja]                             BIGINT           NOT NULL,
    [IdentyfikatoRekordu]                  BIGINT           NOT NULL,
    [Dzialanie]                            NVARCHAR (15)    NOT NULL,
    [Czesc]                                INT              NOT NULL,
    [NazwaProgramu]                        NVARCHAR (200)   NOT NULL,
    [NazwaOdbiorcy]                        NVARCHAR (200)   NOT NULL,
    [AdresOdbiorcy]                        NVARCHAR (250)   NOT NULL,
    [PrzyczynyDecyzjiUmorzenia]            INT              NOT NULL,
    [PowodUmorzenia]                       INT              NOT NULL,
    [KodPozycjiTrezor]                     NVARCHAR (60)    NOT NULL,
    [KodSekcjiTrezor]                      NVARCHAR (60)    NOT NULL,
    [Uwagi]                                NVARCHAR (150)   NOT NULL,
    CONSTRAINT [RBN_Pozycje_pk] PRIMARY KEY CLUSTERED ([IdentyfikatoRekordu] ASC) ON [FG_ZEF2]
);

