CREATE TABLE [intr2].[intr_ustalenia] (
    [nr_ustalenia]            INT            NOT NULL,
    [data]                    DATETIME2 (3)  NULL,
    [operator]                NVARCHAR (40)  NULL,
    [forma_kont]              NCHAR (1)      NULL,
    [kategoria]               NCHAR (2)      NULL,
    [opis]                    NVARCHAR (612) NULL,
    [id_pisma]                NVARCHAR (70)  NULL,
    [data_wys_pisma]          DATETIME2 (3)  NULL,
    [nip]                     NVARCHAR (10)  NOT NULL,
    [rok]                     INT            NOT NULL,
    [miesiac]                 INT            NOT NULL,
    [typ]                     NCHAR (1)      NOT NULL,
    [termin_real]             DATETIME2 (3)  NULL,
    [reakcja]                 NCHAR (1)      NULL,
    [id_dok]                  NVARCHAR (30)  NULL,
    [id_dok_nr_poz]           SMALLINT       NULL,
    [data_dostarczenia_pisma] DATETIME2 (3)  NULL,
    [szablon]                 NVARCHAR (30)  NULL,
    [html]                    NTEXT          NULL,
    [id_sprawy]               NVARCHAR (100) NULL,
    [identity_id]             NUMERIC (19)   NOT NULL,
    [status]                  NCHAR (1)      NULL,
    [inicjaly]                VARCHAR (6)    NULL,
    [prev_id_sprawy]          VARCHAR (100)  NULL,
    CONSTRAINT [intr_ustalenia$PK_INTR_USTALENIA] PRIMARY KEY CLUSTERED ([nr_ustalenia] ASC, [nip] ASC, [rok] ASC, [miesiac] ASC, [typ] ASC),
    CONSTRAINT [intr_ustalenia$UQ_intr_ustalenia__identity_id] UNIQUE NONCLUSTERED ([identity_id] ASC)
);

