CREATE TABLE [intr2].[intr_dane_pod] (
    [id_pod]                          NVARCHAR (35)   NOT NULL,
    [nip]                             NVARCHAR (10)   NULL,
    [regon]                           NVARCHAR (14)   NULL,
    [nazwa]                           NVARCHAR (255)  NULL,
    [imie]                            NVARCHAR (50)   NULL,
    [nazwisko]                        NVARCHAR (50)   NULL,
    [kod_kraj]                        NVARCHAR (2)    NULL,
    [kod_gmina]                       NVARCHAR (7)    NULL,
    [kod_poczt]                       NVARCHAR (50)   NULL,
    [poczta]                          NVARCHAR (50)   NULL,
    [miejscowosc]                     NVARCHAR (50)   NULL,
    [ulica]                           NVARCHAR (55)   NULL,
    [nr_dom]                          NVARCHAR (12)   NULL,
    [nr_lok]                          NVARCHAR (5)    NULL,
    [telefon]                         NVARCHAR (50)   NULL,
    [faks]                            NVARCHAR (50)   NULL,
    [email]                           NVARCHAR (128)  NULL,
    [data_wprow]                      DATETIME2 (3)   NULL,
    [uwagi]                           NVARCHAR (512)  NULL,
    [status]                          NVARCHAR (50)   NULL,
    [data_zakoncz]                    DATETIME2 (3)   NULL,
    [data_aktual]                     DATETIME2 (3)   NULL,
    [zobowiazany]                     NCHAR (1)       NULL,
    [przedstawiciel]                  NCHAR (1)       NULL,
    [dane_wlasne]                     NCHAR (1)       NULL,
    [dane_kontaktowe]                 NVARCHAR (1024) NULL,
    [id_old_pdr]                      NVARCHAR (100)  NULL,
    [tin]                             NVARCHAR (20)   NULL,
    [pesel]                           NVARCHAR (11)   NULL,
    [eori]                            NVARCHAR (100)  NULL,
    [nazwa_krotka]                    NVARCHAR (255)  NULL,
    [edi]                             NCHAR (1)       NULL,
    [podmiot_gospodarczy]             NVARCHAR (255)  NULL,
    [forma_dzialalnosci_gospodarczej] NVARCHAR (255)  NULL,
    [certyfikat_aeo]                  NVARCHAR (255)  NULL,
    [placowka]                        NVARCHAR (255)  NULL,
    [urzad_rejestrowy]                NVARCHAR (255)  NULL,
    [pomin_identyfikacje]             BIT             NOT NULL,
    [zgoda_komunikacja_elektroniczna] BIT             NOT NULL,
    [id_sisc]                         NVARCHAR (17)   NULL,
    [wyslano_info_prog_podstawowy]    BIT             NOT NULL,
    [wyslano_info_prog_szczegolowy]   BIT             NOT NULL,
    CONSTRAINT [intr_dane_pod$PK_INTR_DANE_POD] PRIMARY KEY CLUSTERED ([id_pod] ASC)
);

