CREATE TABLE [intr2].[QRTZ_CALENDARS] (
    [SCHED_NAME]    NVARCHAR (120) NOT NULL,
    [CALENDAR_NAME] NVARCHAR (80)  NOT NULL,
    [CALENDAR]      IMAGE          NOT NULL,
    CONSTRAINT [QRTZ_CALENDARS$PK_qrtz_calendars] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [CALENDAR_NAME] ASC)
);

