CREATE TABLE [intr2].[QRTZ_SCHEDULER_STATE] (
    [SCHED_NAME]        NVARCHAR (120) NOT NULL,
    [INSTANCE_NAME]     NVARCHAR (80)  NOT NULL,
    [LAST_CHECKIN_TIME] NUMERIC (13)   NOT NULL,
    [CHECKIN_INTERVAL]  NUMERIC (13)   NOT NULL,
    CONSTRAINT [QRTZ_SCHEDULER_STATE$PK_qrtz_scheduler_state] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [INSTANCE_NAME] ASC)
);

