CREATE TABLE [intr2].[QRTZ_JOB_DETAILS] (
    [SCHED_NAME]        NVARCHAR (120) NOT NULL,
    [JOB_NAME]          NVARCHAR (80)  NOT NULL,
    [JOB_GROUP]         NVARCHAR (80)  NOT NULL,
    [DESCRIPTION]       NVARCHAR (120) NULL,
    [JOB_CLASS_NAME]    NVARCHAR (128) NOT NULL,
    [IS_DURABLE]        BIT            NOT NULL,
    [IS_NONCONCURRENT]  BIT            NOT NULL,
    [IS_UPDATE_DATA]    BIT            NOT NULL,
    [REQUESTS_RECOVERY] BIT            NOT NULL,
    [JOB_DATA]          IMAGE          NULL,
    CONSTRAINT [QRTZ_JOB_DETAILS$PK_qrtz_job_details] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [JOB_NAME] ASC, [JOB_GROUP] ASC)
);

