CREATE TABLE [intr2].[QRTZ_BLOB_TRIGGERS] (
    [SCHED_NAME]    NVARCHAR (120) NOT NULL,
    [TRIGGER_NAME]  NVARCHAR (80)  NOT NULL,
    [TRIGGER_GROUP] NVARCHAR (80)  NOT NULL,
    [BLOB_DATA]     IMAGE          NULL,
    CONSTRAINT [QRTZ_BLOB_TRIGGERS$PK_qrtz_blob_triggers] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_NAME] ASC, [TRIGGER_GROUP] ASC)
);

