CREATE TABLE [intr2].[QRTZ_PAUSED_TRIGGER_GRPS] (
    [SCHED_NAME]    NVARCHAR (120) NOT NULL,
    [TRIGGER_GROUP] NVARCHAR (80)  NOT NULL,
    CONSTRAINT [QRTZ_PAUSED_TRIGGER_GRPS$PK_qrtz_paused_trigger_grps] PRIMARY KEY CLUSTERED ([SCHED_NAME] ASC, [TRIGGER_GROUP] ASC)
);

