CREATE TABLE [ncts].[ADD_INF_RESP_TYP_NAM] (
    [ADD_INF_RESP_TYP_ID] CHAR (2)      NOT NULL,
    [LANG_ID]             CHAR (2)      NOT NULL,
    [NAM]                 VARCHAR (210) NOT NULL,
    [DAT_START]           DATETIME      NULL,
    [DAT_END]             DATETIME      NULL,
    CONSTRAINT [AIRESN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [AIRESN_OF_AIREST] FOREIGN KEY ([ADD_INF_RESP_TYP_ID]) REFERENCES [ncts].[ADD_INF_RESP_TYP] ([ID]),
    CONSTRAINT [FK_AIRSTN_AIRST] FOREIGN KEY ([ADD_INF_RESP_TYP_ID]) REFERENCES [ncts].[ADD_INF_RESP_TYP] ([ID])
) ON [FG_NCTS];

