CREATE TABLE [ncts].[ADD_INF_REQ_TYP_NAM] (
    [ADD_INF_REQ_TYP_ID] CHAR (1)      NOT NULL,
    [LANG_ID]            CHAR (2)      NOT NULL,
    [NAM]                VARCHAR (210) NOT NULL,
    [DAT_START]          DATETIME      NULL,
    [DAT_END]            DATETIME      NULL,
    CONSTRAINT [AIREQN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [AIREQN_OF_AIREQT] FOREIGN KEY ([ADD_INF_REQ_TYP_ID]) REFERENCES [ncts].[ADD_INF_REQ_TYP] ([ID]),
    CONSTRAINT [FK_AIRQTN_AIRQT] FOREIGN KEY ([ADD_INF_REQ_TYP_ID]) REFERENCES [ncts].[ADD_INF_REQ_TYP] ([ID])
) ON [FG_NCTS];

