CREATE TABLE [ncts].[ARE] (
    [SID] INT      NOT NULL,
    [ID]  CHAR (2) NOT NULL,
    CONSTRAINT [PK_ARE] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS]
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [A_ID_IX]
    ON [ncts].[ARE]([ID] ASC)
    ON [FG_NCTS];

