CREATE TABLE [ncts].[ARE_ACT] (
    [SID]     INT         NOT NULL,
    [ARE_ID]  CHAR (2)    NOT NULL,
    [DAT_VAL] DATETIME    NOT NULL,
    [MOD_TYP] DECIMAL (1) NULL,
    [OPER]    CHAR (1)    NULL,
    CONSTRAINT [PK_ARE_ACT] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [AA_AI_A_I_FK] FOREIGN KEY ([ARE_ID]) REFERENCES [ncts].[ARE] ([ID]),
    CONSTRAINT [FK_AA_A] FOREIGN KEY ([ARE_ID]) REFERENCES [ncts].[ARE] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [AA_DV_I]
    ON [ncts].[ARE_ACT]([DAT_VAL] ASC)
    ON [FG_NCTS];

