CREATE TABLE [ncts].[CONTR_GOODS_ITEM_DOC] (
    [SID]                  INT            NOT NULL,
    [CONTR_GOODS_ITEM_SID] INT            NULL,
    [DOC_TYP_ID]           VARCHAR (6)    NULL,
    [SENT]                 CHAR (1)       NULL,
    [COMPL_OF_INF]         NVARCHAR (78)  NULL,
    [COMPL_OF_INF_LNG]     CHAR (2)       NULL,
    [CONTR_LEV]            CHAR (1)       NULL,
    [DOC_REF]              NVARCHAR (105) NULL,
    [DOC_REF_LNG]          CHAR (2)       NULL,
    [DOC_TYP_TEXT]         NVARCHAR (140) NULL,
    [DOC_REF_TEXT]         NVARCHAR (140) NULL,
    [COMPL_OF_INF_TEXT]    NVARCHAR (140) NULL,
    CONSTRAINT [PK_CONTR_GOODS_ITEM_DOC] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_CGIDC_CGI] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID]),
    CONSTRAINT [GID_C_COMPL_OF_INF_IN_L] FOREIGN KEY ([COMPL_OF_INF_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [GID_C_DOC_REF_IN_L] FOREIGN KEY ([DOC_REF_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [GID_C_FOR_GI_C] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID]),
    CONSTRAINT [GID_C_OF_DOT] FOREIGN KEY ([DOC_TYP_ID]) REFERENCES [ncts].[DOC_TYP] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [CGIDO_CGIS_I]
    ON [ncts].[CONTR_GOODS_ITEM_DOC]([CONTR_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];

