CREATE TABLE [ncts].[CONTR_GOODS_ITEM_SPEC_MENT] (
    [CONTR_GOODS_ITEM_SID] INT            NOT NULL,
    [SID]                  INT            NULL,
    [SPEC_MENT_TYP_ID]     VARCHAR (5)    NULL,
    [CONTR_LEV]            CHAR (1)       NOT NULL,
    [EXP_FROM_COUNTRY_ID]  CHAR (2)       NULL,
    [EXP_FROM_EC]          CHAR (1)       NULL,
    [TEXT]                 NVARCHAR (210) NULL,
    [TEXT_LNG]             CHAR (2)       NULL,
    CONSTRAINT [PK_CONTR_GOODS_ITEM_SPEC_MENT] PRIMARY KEY CLUSTERED ([CONTR_GOODS_ITEM_SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_CGISM_CGI] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID]),
    CONSTRAINT [GISM_C_FOR_GI_C] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID]),
    CONSTRAINT [GISM_C_IN_L] FOREIGN KEY ([TEXT_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [GISM_C_OF_SMT] FOREIGN KEY ([SPEC_MENT_TYP_ID]) REFERENCES [ncts].[SPEC_MENT_TYP] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [GISM_C_PK]
    ON [ncts].[CONTR_GOODS_ITEM_SPEC_MENT]([SID] ASC)
    ON [FG_NCTS];

