CREATE TABLE [ncts].[CONTR_GOODS_ITEM_SENS] (
    [SID]                  INT             NOT NULL,
    [CONTR_GOODS_ITEM_SID] INT             NULL,
    [SENS_GOODS_CLASS_SID] INT             NULL,
    [SENS_QUANT]           DECIMAL (14, 3) NOT NULL,
    [CONTR_LEV]            CHAR (1)        NULL,
    [SGI_CODE_TEXT]        NVARCHAR (140)  NULL,
    [SENS_QUANT_TEXT]      NVARCHAR (140)  NULL,
    CONSTRAINT [PK_CONTR_GOODS_ITEM_SENS] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_CGIS_CGI] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID]),
    CONSTRAINT [GIS_C_FOR_GC_S] FOREIGN KEY ([SENS_GOODS_CLASS_SID]) REFERENCES [ncts].[SENS_GOODS_CLASS] ([SID]),
    CONSTRAINT [GIS_C_FOR_GI_C] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [CGIS_CGIS_I]
    ON [ncts].[CONTR_GOODS_ITEM_SENS]([CONTR_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [GIS_C_UK]
    ON [ncts].[CONTR_GOODS_ITEM_SENS]([SENS_GOODS_CLASS_SID] ASC, [CONTR_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];

