CREATE TABLE [ncts].[CONTR_RES_TYP_NAM] (
    [CONTR_RES_TYP_ID] CHAR (2)      NOT NULL,
    [LANG_ID]          CHAR (2)      NOT NULL,
    [NAM]              VARCHAR (140) NULL,
    [DAT_END]          DATETIME      NULL,
    [DAT_START]        DATETIME      NULL,
    CONSTRAINT [CRTN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [CRTN_OF_CRT] FOREIGN KEY ([CONTR_RES_TYP_ID]) REFERENCES [ncts].[CONTR_RES_TYP] ([ID]),
    CONSTRAINT [FK_CRTN_CRT] FOREIGN KEY ([CONTR_RES_TYP_ID]) REFERENCES [ncts].[CONTR_RES_TYP] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [CRTN_CRTI_I]
    ON [ncts].[CONTR_RES_TYP_NAM]([CONTR_RES_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [CRTN_LI_I]
    ON [ncts].[CONTR_RES_TYP_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];

