CREATE TABLE [ncts].[CONTR_GOODS_ITEM_CONT] (
    [SID]                  INT            NOT NULL,
    [CONTR_GOODS_ITEM_SID] INT            NULL,
    [CONT_NUMB]            VARCHAR (17)   NULL,
    [CONTR_LEV]            CHAR (1)       NULL,
    [CONT_NUMB_TEXT]       NVARCHAR (140) NULL,
    CONSTRAINT [PK_CONTR_GOODS_ITEM_CONT] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_CGIC_CGI] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID]),
    CONSTRAINT [GIC_C_CONT_GI_C] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [CGIC_CGIS_I]
    ON [ncts].[CONTR_GOODS_ITEM_CONT]([CONTR_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];

