CREATE TABLE [ncts].[CONTR_TRANS_OPER_DET] (
    [MRN]                    VARCHAR (21)    NOT NULL,
    [CONTR_LOC]              VARCHAR (3)     NOT NULL,
    [TOT_NUMB_OF_ITEMS]      DECIMAL (5)     NULL,
    [TOT_NUMB_OF_PACK]       DECIMAL (7)     NULL,
    [IDENT_AT_DEP]           VARCHAR (27)    NULL,
    [IDENT_AT_DEP_LNG]       CHAR (2)        NULL,
    [NAT_AT_DEP]             CHAR (2)        NULL,
    [TOT_GROSS_MASS]         DECIMAL (14, 3) NULL,
    [NUMB_OF_SEALS]          DECIMAL (4)     NULL,
    [TOT_NUMB_OF_ITEMS_TEXT] NVARCHAR (420)  NULL,
    [IDENT_AT_DEP_TEXT]      NVARCHAR (420)  NULL,
    [NAT_AT_DEP_TEXT]        NVARCHAR (420)  NULL,
    [TOT_NUMB_OF_PACK_TEXT]  NVARCHAR (420)  NULL,
    [TOT_GROSS_MASS_TEXT]    NVARCHAR (420)  NULL,
    [NUMB_OF_SEALS_TEXT]     NVARCHAR (140)  NULL,
    CONSTRAINT [PK_CONTR_TRANS_OPER_DET] PRIMARY KEY NONCLUSTERED ([MRN] ASC, [CONTR_LOC] ASC) ON [FG_NCTS],
    CONSTRAINT [TOD_C_IDENT_AT_DEP_IN_L] FOREIGN KEY ([IDENT_AT_DEP_LNG]) REFERENCES [ncts].[LANG] ([ID])
) ON [FG_NCTS];

