CREATE TABLE [ncts].[CONTR_GOODS_ITEM_DESCR] (
    [SID]                  INT            NOT NULL,
    [CONTR_GOODS_ITEM_SID] INT            NULL,
    [CONTR_IND]            CHAR (2)       NULL,
    [POINTER]              VARCHAR (35)   NULL,
    [DESCR]                NVARCHAR (420) NULL,
    [DESCR_LNG]            CHAR (2)       NULL,
    CONSTRAINT [PK_CONTR_GOODS_ITEM_DESCR] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_CGID_CGI] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID]),
    CONSTRAINT [GI_C_DESCR_IN_L] FOREIGN KEY ([DESCR_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [GIDS_C_FOR_GI_C] FOREIGN KEY ([CONTR_GOODS_ITEM_SID]) REFERENCES [ncts].[CONTR_GOODS_ITEM] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [CGID_CGIS_I]
    ON [ncts].[CONTR_GOODS_ITEM_DESCR]([CONTR_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];

