CREATE TABLE [ncts].[CONTR_GOODS_ITEM] (
    [SID]               INT             NOT NULL,
    [MRN]               VARCHAR (21)    NOT NULL,
    [GOODS_ITEM_NUMB]   DECIMAL (5)     NOT NULL,
    [CONTR_LOC]         VARCHAR (3)     NOT NULL,
    [CONTR_IND]         CHAR (2)        NULL,
    [GROSS_MASS]        DECIMAL (14, 3) NULL,
    [NET_MASS]          DECIMAL (14, 3) NULL,
    [TEXT_DESCR]        NVARCHAR (840)  NULL,
    [TEXT_DESCR_LNG]    CHAR (2)        NULL,
    [HS_GOODS_CLASS_ID] VARCHAR (6)     NULL,
    [CN_GOODS_CLASS_ID] CHAR (2)        NULL,
    [TEXT_DESCR_TEXT]   NVARCHAR (140)  NULL,
    [COMM_COD_TEXT]     NVARCHAR (140)  NULL,
    [GROSS_MASS_TEXT]   NVARCHAR (140)  NULL,
    [NET_MASS_TEXT]     NVARCHAR (140)  NULL,
    [UNL_VERS_NUMB]     DECIMAL (8)     NOT NULL,
    CONSTRAINT [PK_CONTR_GOODS_ITEM] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [GI_C_TEXT_DESCR_IN_L] FOREIGN KEY ([TEXT_DESCR_LNG]) REFERENCES [ncts].[LANG] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [CGI_MRN_I]
    ON [ncts].[CONTR_GOODS_ITEM]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [GI_C_UK]
    ON [ncts].[CONTR_GOODS_ITEM]([CONTR_LOC] ASC, [GOODS_ITEM_NUMB] ASC, [MRN] ASC, [UNL_VERS_NUMB] ASC)
    ON [FG_NCTS];

