CREATE TABLE [ncts].[CROSS_BORD_TYP_DESCR] (
    [CROSS_BORD_TYP_ID] VARCHAR (3)   NOT NULL,
    [LANG_ID]           CHAR (2)      NULL,
    [DESCR]             VARCHAR (105) NULL,
    [DAT_START]         DATETIME      NULL,
    [DAT_END]           DATETIME      NULL,
    CONSTRAINT [CBTD_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [CBTD_OF_CBT] FOREIGN KEY ([CROSS_BORD_TYP_ID]) REFERENCES [ncts].[CROSS_BORD_TYP] ([ID]),
    CONSTRAINT [FK_CBTD_CBT] FOREIGN KEY ([CROSS_BORD_TYP_ID]) REFERENCES [ncts].[CROSS_BORD_TYP] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [CBTD_CBTI_I]
    ON [ncts].[CROSS_BORD_TYP_DESCR]([CROSS_BORD_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [CBTD_LI_I]
    ON [ncts].[CROSS_BORD_TYP_DESCR]([LANG_ID] ASC)
    ON [FG_NCTS];

