CREATE TABLE [ncts].[CUST_OFF_ACT] (
    [SID]         INT         NOT NULL,
    [CUST_OFF_ID] VARCHAR (8) NOT NULL,
    [MOD_TYP]     DECIMAL (1) NULL,
    [DAT_VAL]     DATETIME    NULL,
    [OPER]        CHAR (1)    NOT NULL,
    CONSTRAINT [PK_CUST_OFF_ACT] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [COA_CUST_OFF_ID_OF_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID]),
    CONSTRAINT [FK_COA_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [COA_COI_I]
    ON [ncts].[CUST_OFF_ACT]([CUST_OFF_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [COA_DV_I]
    ON [ncts].[CUST_OFF_ACT]([DAT_VAL] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [COA_O_I]
    ON [ncts].[CUST_OFF_ACT]([OPER] ASC)
    ON [FG_NCTS];

