CREATE TABLE [ncts].[CUST_OFF_TYP] (
    [CUST_OFF_ID] VARCHAR (8)  NOT NULL,
    [TYP]         VARCHAR (26) NULL,
    CONSTRAINT [PK_CUST_OFF_TYP] PRIMARY KEY CLUSTERED ([CUST_OFF_ID] ASC) ON [FG_NCTS],
    CONSTRAINT [TY_FK] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID])
);

