CREATE TABLE [ncts].[CUST_OFF_NAM] (
    [STATUS]           CHAR (1)       NULL,
    [PREF_SUFF_LEV]    CHAR (1)       NULL,
    [CUST_OFF_ACT_SID] INT            NOT NULL,
    [LANG_ID]          CHAR (2)       NOT NULL,
    [CUST_OFF_ID]      VARCHAR (8)    NOT NULL,
    [NAM]              NVARCHAR (105) NULL,
    [PREF]             CHAR (1)       NOT NULL,
    [CITY]             NVARCHAR (105) NULL,
    [STR_AND_NUMB]     NVARCHAR (105) NULL,
    [PREF_SUFF_NAM]    NVARCHAR (105) NULL,
    [ADD_SPAC]         CHAR (1)       NOT NULL,
    CONSTRAINT [CON_COAS_OF_COA] FOREIGN KEY ([CUST_OFF_ACT_SID]) REFERENCES [ncts].[CUST_OFF_ACT] ([SID]),
    CONSTRAINT [FK_CON_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID]),
    CONSTRAINT [FK_CON_COA] FOREIGN KEY ([CUST_OFF_ACT_SID]) REFERENCES [ncts].[CUST_OFF_ACT] ([SID]),
    CONSTRAINT [LD_N_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [LD_N_NAM_OF_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [CON_COILI_I]
    ON [ncts].[CUST_OFF_NAM]([CUST_OFF_ID] ASC, [LANG_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [CON_CUST_OFF_ACT_SID_IX]
    ON [ncts].[CUST_OFF_NAM]([CUST_OFF_ACT_SID] ASC)
    ON [FG_NCTS];

