CREATE TABLE [ncts].[CUST_OFF_ROL] (
    [STATUS]           CHAR (2)    NULL,
    [CUST_OFF_ACT_SID] INT         NOT NULL,
    [OFF_ROL_TYP_ID]   VARCHAR (3) NOT NULL,
    [TRAFF_TYP_ID]     VARCHAR (3) NOT NULL,
    CONSTRAINT [PK_CUST_OFF_ROL] PRIMARY KEY CLUSTERED ([CUST_OFF_ACT_SID] ASC, [OFF_ROL_TYP_ID] ASC, [TRAFF_TYP_ID] ASC) ON [FG_NCTS],
    CONSTRAINT [COR_COAS_OF_COA] FOREIGN KEY ([CUST_OFF_ACT_SID]) REFERENCES [ncts].[CUST_OFF_ACT] ([SID]),
    CONSTRAINT [COR_OF_ORT] FOREIGN KEY ([OFF_ROL_TYP_ID]) REFERENCES [ncts].[OFF_ROL_TYP] ([ID]),
    CONSTRAINT [FK_COR_COA] FOREIGN KEY ([CUST_OFF_ACT_SID]) REFERENCES [ncts].[CUST_OFF_ACT] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [COR_CUST_OFF_ACT_SID_IX]
    ON [ncts].[CUST_OFF_ROL]([CUST_OFF_ACT_SID] ASC)
    ON [FG_NCTS];

