CREATE TABLE [ncts].[DECL_GOODS_ITEM_CONT] (
    [SID]                 INT          NOT NULL,
    [CONT_NUMB]           VARCHAR (17) NOT NULL,
    [DECL_GOODS_ITEM_SID] INT          NULL,
    CONSTRAINT [PK_DECL_GOODS_ITEM_CONT] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_DGIC_DGI] FOREIGN KEY ([DECL_GOODS_ITEM_SID]) REFERENCES [ncts].[DECL_GOODS_ITEM] ([SID]),
    CONSTRAINT [GIC_D_PART_OF_GI_D] FOREIGN KEY ([DECL_GOODS_ITEM_SID]) REFERENCES [ncts].[DECL_GOODS_ITEM] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [DGIC_DGIS_I]
    ON [ncts].[DECL_GOODS_ITEM_CONT]([DECL_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];

