CREATE TABLE [ncts].[DECL_GOODS_ITEM] (
    [SID]                      INT             NOT NULL,
    [MRN]                      VARCHAR (21)    NULL,
    [TRANS_OPER_SID]           INT             NULL,
    [VERS_NUMB]                DECIMAL (3)     NULL,
    [GOODS_ITEM_NUMB]          DECIMAL (5)     NOT NULL,
    [HS_GOODS_CLASS_ID]        VARCHAR (6)     NULL,
    [CN_GOODS_CLASS_ID]        CHAR (2)        NULL,
    [TEXT_DESCR]               NVARCHAR (840)  NULL,
    [TEXT_DESCR_LNG]           CHAR (2)        NULL,
    [DECL_TYP_ID]              VARCHAR (5)     NULL,
    [GROSS_MASS]               DECIMAL (14, 3) NULL,
    [NET_MASS]                 DECIMAL (14, 3) NULL,
    [DISP_COUNTRY_ID]          CHAR (2)        NULL,
    [DEST_COUNTRY_ID]          CHAR (2)        NULL,
    [CONSIGNEE_TRAD_SID]       INT             NULL,
    [CONSIGNOR_TRAD_SID]       INT             NULL,
    [CONSIGNOR_TRADS_SID]      INT             NULL,
    [CONSIGNEE_TRADS_SID]      INT             NULL,
    [SUSP_GOODS]               CHAR (1)        NULL,
    [TRANSPORT_CHARGE_PAYMENT] CHAR (1)        NULL,
    [COMM_REF_NUMBER]          VARCHAR (70)    NULL,
    [UN_DANGER_CODE]           VARCHAR (4)     NULL,
    [SEC_CONSIGNEE_TRAD_SID]   INT             NULL,
    [SEC_CONSIGNEE_TRADS_SID]  INT             NULL,
    [SEC_CONSIGNOR_TRADS_SID]  INT             NULL,
    [SEC_CONSIGNOR_TRAD_SID]   INT             NULL,
    CONSTRAINT [PK_DECL_GOODS_ITEM] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_DGI_TOV] FOREIGN KEY ([TRANS_OPER_SID], [VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB])
);


GO
CREATE NONCLUSTERED INDEX [DGI_CETDS_I]
    ON [ncts].[DECL_GOODS_ITEM]([CONSIGNEE_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGI_CONSIGNEE_TRADS_SID_IX]
    ON [ncts].[DECL_GOODS_ITEM]([CONSIGNEE_TRADS_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGI_CONSIGNOR_TRADS_SID_IX]
    ON [ncts].[DECL_GOODS_ITEM]([CONSIGNOR_TRADS_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGI_CRTDS_I]
    ON [ncts].[DECL_GOODS_ITEM]([CONSIGNOR_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGI_MRN_I]
    ON [ncts].[DECL_GOODS_ITEM]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGI_SCETDS_I]
    ON [ncts].[DECL_GOODS_ITEM]([SEC_CONSIGNEE_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGI_SCRTDS_I]
    ON [ncts].[DECL_GOODS_ITEM]([SEC_CONSIGNOR_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGI_SCRTDSS_I]
    ON [ncts].[DECL_GOODS_ITEM]([SEC_CONSIGNOR_TRADS_SID] ASC, [VERS_NUMB] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGI_TOS_IX]
    ON [ncts].[DECL_GOODS_ITEM]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];

