CREATE TABLE [ncts].[DECL_TYP] (
    [ID]        VARCHAR (5) NOT NULL,
    [DAT_START] DATETIME    NOT NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_DECL_TYP] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

