CREATE TABLE [ncts].[DECL_GOODS_ITEM_SENS] (
    [SID]                  INT             NOT NULL,
    [DECL_GOODS_ITEM_SID]  INT             NULL,
    [SENS_GOODS_CLASS_SID] INT             NULL,
    [SENS_QUANT]           DECIMAL (14, 3) NOT NULL,
    CONSTRAINT [PK_DECL_GOODS_ITEM_SENS] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_DGIS_DGI] FOREIGN KEY ([DECL_GOODS_ITEM_SID]) REFERENCES [ncts].[DECL_GOODS_ITEM] ([SID]),
    CONSTRAINT [GIS_D_FOR_GC_S] FOREIGN KEY ([SENS_GOODS_CLASS_SID]) REFERENCES [ncts].[SENS_GOODS_CLASS] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [DGIS_DGIS_I]
    ON [ncts].[DECL_GOODS_ITEM_SENS]([DECL_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];

