CREATE TABLE [ncts].[DECL_TYP_NAM] (
    [DECL_TYP_ID] VARCHAR (5)   NOT NULL,
    [LANG_ID]     CHAR (2)      NOT NULL,
    [NAM]         VARCHAR (140) NULL,
    [DAT_START]   DATETIME      NULL,
    [DAT_END]     DATETIME      NULL,
    CONSTRAINT [DETN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [DETN_OF_DET] FOREIGN KEY ([DECL_TYP_ID]) REFERENCES [ncts].[DECL_TYP] ([ID]),
    CONSTRAINT [FK_DTN_DT] FOREIGN KEY ([DECL_TYP_ID]) REFERENCES [ncts].[DECL_TYP] ([ID])
) ON [FG_NCTS];

