CREATE TABLE [ncts].[DECL_GOODS_ITEM_DOC] (
    [DOC_TYP_ID]          VARCHAR (6)    NULL,
    [SID]                 INT            NOT NULL,
    [DECL_GOODS_ITEM_SID] INT            NULL,
    [SENT]                CHAR (1)       NOT NULL,
    [DOC_REF]             NVARCHAR (105) NULL,
    [DOC_REF_LNG]         CHAR (2)       NULL,
    [COMPL_OF_INF]        NVARCHAR (78)  NULL,
    [COMPL_OF_INF_LNG]    CHAR (2)       NULL,
    CONSTRAINT [PK_DECL_GOODS_ITEM_DOC] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_DGID_DGI] FOREIGN KEY ([DECL_GOODS_ITEM_SID]) REFERENCES [ncts].[DECL_GOODS_ITEM] ([SID]),
    CONSTRAINT [GID_D_COMPL_OF_INF_IN_L] FOREIGN KEY ([COMPL_OF_INF_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [GID_D_DOC_REF_IN_L] FOREIGN KEY ([DOC_REF_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [GID_D_OF_DOT] FOREIGN KEY ([DOC_TYP_ID]) REFERENCES [ncts].[DOC_TYP] ([ID]),
    CONSTRAINT [GID_D_PART_OF_GI_D] FOREIGN KEY ([DECL_GOODS_ITEM_SID]) REFERENCES [ncts].[DECL_GOODS_ITEM] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [DGID_DGIS_IX]
    ON [ncts].[DECL_GOODS_ITEM_DOC]([DECL_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGID_DOC_REF_IX]
    ON [ncts].[DECL_GOODS_ITEM_DOC]([DOC_REF] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DGID_DOC_TYP_IX]
    ON [ncts].[DECL_GOODS_ITEM_DOC]([DOC_TYP_ID] ASC)
    ON [FG_NCTS];

