CREATE TABLE [ncts].[DECL_TRANS_OPER_DET] (
    [SID]                      INT             NOT NULL,
    [MRN]                      VARCHAR (21)    NULL,
    [TRANS_OPER_SID]           INT             NULL,
    [VERS_NUMB]                DECIMAL (3)     NOT NULL,
    [DECL_TYP_ID]              VARCHAR (5)     NULL,
    [NUMB_OF_LOAD_LISTS]       DECIMAL (5)     NULL,
    [TOT_NUMB_OF_ITEMS]        DECIMAL (5)     NULL,
    [TOT_NUMB_OF_PACK]         DECIMAL (7)     NULL,
    [DISP_COUNTRY_ID]          CHAR (2)        NULL,
    [DEST_COUNTRY_ID]          CHAR (2)        NULL,
    [IDENT_AT_DEP]             VARCHAR (81)    NULL,
    [IDENT_AT_DEP_LNG]         CHAR (2)        NULL,
    [NAT_AT_DEP]               CHAR (2)        NULL,
    [CONT]                     CHAR (1)        NULL,
    [SENS]                     CHAR (1)        NULL,
    [NAT_CROSS_BORD]           CHAR (2)        NULL,
    [IDENT_CROSS_BORD]         VARCHAR (81)    NULL,
    [IDENT_CROSS_BORD_LNG]     CHAR (2)        NULL,
    [TRANSP_TYP_CROSS_BORD]    VARCHAR (3)     NULL,
    [TRANSP_MOD_AT_BORD]       CHAR (2)        NULL,
    [INL_TRANSP_MOD]           CHAR (2)        NULL,
    [LOAD_PLAC]                NVARCHAR (17)   NULL,
    [CUST_OFF_ADDR_SID]        INT             NULL,
    [TOT_GROSS_MASS]           DECIMAL (14, 3) NOT NULL,
    [NCTS_ACC_DOC_LANG_ID]     CHAR (2)        NULL,
    [DIAL_LANG_ID]             CHAR (2)        NULL,
    [CONSIGNOR_TRAD_SID]       INT             NULL,
    [CONSIGNOR_TRADS_SID]      INT             NULL,
    [CONSIGNEE_TRAD_SID]       INT             NULL,
    [CONSIGNEE_TRADS_SID]      INT             NULL,
    [REPR_NAM]                 NVARCHAR (105)  NULL,
    [REPR_TRAD_SID]            INT             NULL,
    [REPR_CAP]                 NVARCHAR (105)  NULL,
    [REPR_CAP_LNG]             CHAR (2)        NULL,
    [AUTH_CONSIGNEE_TRAD_SID]  INT             NULL,
    [AUTH_CONSIGNEE_TRADS_SID] INT             NULL,
    [DEST_CUST_OFF_ID]         VARCHAR (8)     NULL,
    [AGR_GOODS_LOC]            NVARCHAR (105)  NULL,
    [AGR_GOODS_LOC_LNG]        CHAR (2)        NULL,
    [AGR_GOODS_LOC_COD]        NVARCHAR (17)   NULL,
    [DAT_EXP_ARR]              DATETIME        NULL,
    [PROC]                     CHAR (2)        NULL,
    [NUMB_OF_SEALS]            DECIMAL (4)     NULL,
    [AUD_USER_ID]              VARCHAR (7)     NOT NULL,
    [AUD_DAT_TIM]              DATETIME        NOT NULL,
    [SUSP_GOODS]               CHAR (1)        NULL,
    [SPECIFIC_CIRC_INDICATOR]  CHAR (1)        NULL,
    [TRANSPORT_CHARGE_PAYMENT] CHAR (1)        NULL,
    [COMM_REF_NUMBER]          VARCHAR (70)    NULL,
    [SECURITY_INDICATOR]       DECIMAL (1)     NULL,
    [CONVEY_REF_NUMBER]        VARCHAR (35)    NULL,
    [PLAC_UNLOAD_CODE]         NVARCHAR (105)  NULL,
    [SEC_CONSIGNEE_TRAD_SID]   INT             NULL,
    [SEC_CONSIGNEE_TRADS_SID]  INT             NULL,
    [SEC_CONSIGNOR_TRADS_SID]  INT             NULL,
    [SEC_CONSIGNOR_TRAD_SID]   INT             NULL,
    [SEC_CARRIER_TRADS_SID]    INT             NULL,
    [SEC_CARRIER_TRAD_SID]     INT             NULL,
    CONSTRAINT [PK_DECL_TRANS_OPER_DET] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [DTOD_SCATS_T_S_FK] FOREIGN KEY ([SEC_CARRIER_TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [DTOD_SCATS_TS_S_FK] FOREIGN KEY ([SEC_CARRIER_TRADS_SID]) REFERENCES [ncts].[TRADS] ([SID]),
    CONSTRAINT [DTOD_SCETS_T_S_FK] FOREIGN KEY ([SEC_CONSIGNEE_TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [DTOD_SCETS_TS_S_FK] FOREIGN KEY ([SEC_CONSIGNEE_TRADS_SID]) REFERENCES [ncts].[TRADS] ([SID]),
    CONSTRAINT [DTOD_SCOTS_T_S_FK] FOREIGN KEY ([SEC_CONSIGNOR_TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [DTOD_SCOTS_TS_S_FK] FOREIGN KEY ([SEC_CONSIGNOR_TRADS_SID]) REFERENCES [ncts].[TRADS] ([SID]),
    CONSTRAINT [FK_DTOD_TOV] FOREIGN KEY ([TRANS_OPER_SID], [VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB]),
    CONSTRAINT [TOD_D_AUTH_AS_CONSIGNEE_T] FOREIGN KEY ([AUTH_CONSIGNEE_TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [TOD_D_AUTH_AS_CONSIGNEE_TS] FOREIGN KEY ([AUTH_CONSIGNEE_TRADS_SID]) REFERENCES [ncts].[TRADS] ([SID]),
    CONSTRAINT [TOD_D_DECL_END_AT_CO] FOREIGN KEY ([DEST_CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID]),
    CONSTRAINT [TOD_D_DECL_USING_DET] FOREIGN KEY ([DECL_TYP_ID]) REFERENCES [ncts].[DECL_TYP] ([ID]),
    CONSTRAINT [TOD_D_DISP_FROM_T] FOREIGN KEY ([CONSIGNOR_TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [TOD_D_DISP_FROM_TS] FOREIGN KEY ([CONSIGNOR_TRADS_SID]) REFERENCES [ncts].[TRADS] ([SID]),
    CONSTRAINT [TOD_D_FOR_CONTR_AT_OA_C] FOREIGN KEY ([CUST_OFF_ADDR_SID]) REFERENCES [ncts].[CUST_OFF_ADDR] ([SID]),
    CONSTRAINT [TOD_D_INT_FOR_T] FOREIGN KEY ([CONSIGNEE_TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [TOD_D_INT_FOR_TS] FOREIGN KEY ([CONSIGNEE_TRADS_SID]) REFERENCES [ncts].[TRADS] ([SID]),
    CONSTRAINT [TOD_D_OF_VERS] FOREIGN KEY ([TRANS_OPER_SID], [VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB]),
    CONSTRAINT [TOD_D_REPR_BY_T] FOREIGN KEY ([REPR_TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [TOD_D_REPR_CAP_IN_L] FOREIGN KEY ([REPR_CAP_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [TOD_D_TRANS_CROSS_BORD_BY_TM] FOREIGN KEY ([TRANSP_MOD_AT_BORD]) REFERENCES [ncts].[TRANSP_MOD] ([ID]),
    CONSTRAINT [TOD_D_TRANSP_CROSS_BORD_BY_CBT] FOREIGN KEY ([TRANSP_TYP_CROSS_BORD]) REFERENCES [ncts].[CROSS_BORD_TYP] ([ID]),
    CONSTRAINT [TOD_D_TRANSP_INL_BY_TM] FOREIGN KEY ([INL_TRANSP_MOD]) REFERENCES [ncts].[TRANSP_MOD] ([ID]),
    CONSTRAINT [TOD_D_USING_AS_DIAL_L] FOREIGN KEY ([DIAL_LANG_ID]) REFERENCES [ncts].[LANG] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [DTOD_AUTH_CONSIGNEE_TRADS_SID_IX]
    ON [ncts].[DECL_TRANS_OPER_DET]([AUTH_CONSIGNEE_TRADS_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_CETDS_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([CONSIGNEE_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_CONSIGNEE_TRADS_SID_IX]
    ON [ncts].[DECL_TRANS_OPER_DET]([CONSIGNEE_TRADS_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_CONSIGNOR_TRADS_SID_IX]
    ON [ncts].[DECL_TRANS_OPER_DET]([CONSIGNOR_TRADS_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_CRTDS_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([CONSIGNOR_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_DCOI_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([DEST_CUST_OFF_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_MRN_IX]
    ON [ncts].[DECL_TRANS_OPER_DET]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_SCATDS_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([SEC_CARRIER_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_SCATDSS_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([SEC_CARRIER_TRADS_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_SCETDS_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([SEC_CONSIGNEE_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_SCETDSS_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([SEC_CONSIGNEE_TRADS_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_SCRTDS_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([SEC_CONSIGNOR_TRAD_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_SCRTDSS_I]
    ON [ncts].[DECL_TRANS_OPER_DET]([SEC_CONSIGNOR_TRADS_SID] ASC, [VERS_NUMB] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTOD_TOSID_IX]
    ON [ncts].[DECL_TRANS_OPER_DET]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];

