CREATE TABLE [ncts].[DECL_GOODS_ITEM_PACK] (
    [SID]                      INT            NOT NULL,
    [PACK_TYP_ID]              CHAR (2)       NOT NULL,
    [PACK_MARKS_AND_IDENT]     NVARCHAR (126) NULL,
    [PACK_MARKS_AND_IDENT_LNG] CHAR (2)       NULL,
    [NUMB_OF_PACK]             DECIMAL (5)    NULL,
    [NUMB_OF_PIEC]             DECIMAL (5)    NULL,
    [DECL_GOODS_ITEM_SID]      INT            NULL,
    CONSTRAINT [PK_DECL_GOODS_ITEM_PACK] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_DGIP_DGI] FOREIGN KEY ([DECL_GOODS_ITEM_SID]) REFERENCES [ncts].[DECL_GOODS_ITEM] ([SID]),
    CONSTRAINT [GIP_D_MARKS_AND_IDENT_IN_L] FOREIGN KEY ([PACK_MARKS_AND_IDENT_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [GIP_D_OF_PT] FOREIGN KEY ([PACK_TYP_ID]) REFERENCES [ncts].[PACK_TYP] ([ID]),
    CONSTRAINT [GIP_D_PART_OF_GI_D] FOREIGN KEY ([DECL_GOODS_ITEM_SID]) REFERENCES [ncts].[DECL_GOODS_ITEM] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [DGIP_DGIS_I]
    ON [ncts].[DECL_GOODS_ITEM_PACK]([DECL_GOODS_ITEM_SID] ASC)
    ON [FG_NCTS];

