CREATE TABLE [ncts].[DOC_TYP_NAM] (
    [DOC_TYP_ID] VARCHAR (6)   NOT NULL,
    [LANG_ID]    CHAR (2)      NOT NULL,
    [NAM]        VARCHAR (350) NULL,
    [DAT_END]    DATETIME      NULL,
    [DAT_START]  DATETIME      NULL,
    CONSTRAINT [DOTN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [DOTN_OF_DOT] FOREIGN KEY ([DOC_TYP_ID]) REFERENCES [ncts].[DOC_TYP] ([ID]),
    CONSTRAINT [FK_DTNM_DT] FOREIGN KEY ([DOC_TYP_ID]) REFERENCES [ncts].[DOC_TYP] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTN_DTI_I]
    ON [ncts].[DOC_TYP_NAM]([DOC_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [DTN_LI_I]
    ON [ncts].[DOC_TYP_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];

