CREATE TABLE [ncts].[ENQ_REQ_INF_COD_TYP_NAM] (
    [ENQ_REQ_INF_COD_TYP_ID] CHAR (2)      NOT NULL,
    [LANG_ID]                CHAR (2)      NULL,
    [NAM]                    VARCHAR (420) NULL,
    [DAT_START]              DATETIME      NULL,
    [DAT_END]                DATETIME      NULL,
    CONSTRAINT [ERICTN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [ERICTN_OF_ERICT] FOREIGN KEY ([ENQ_REQ_INF_COD_TYP_ID]) REFERENCES [ncts].[ENQ_REQ_INF_COD_TYP] ([ID]),
    CONSTRAINT [FK_ERQICTN_ERQICT] FOREIGN KEY ([ENQ_REQ_INF_COD_TYP_ID]) REFERENCES [ncts].[ENQ_REQ_INF_COD_TYP] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [ERICTN_ERICTI_I]
    ON [ncts].[ENQ_REQ_INF_COD_TYP_NAM]([ENQ_REQ_INF_COD_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [ERICTN_LI_I]
    ON [ncts].[ENQ_REQ_INF_COD_TYP_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];

