CREATE TABLE [ncts].[ENQ_RESP_COD_TYP_NAM] (
    [ENQ_RESP_COD_TYP_ID] DECIMAL (2)   NOT NULL,
    [LANG_ID]             CHAR (2)      NULL,
    [NAM]                 VARCHAR (420) NULL,
    [DAT_START]           DATETIME      NULL,
    [DAT_END]             DATETIME      NULL,
    CONSTRAINT [ERCTN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [ERCTN_OF_ERCT] FOREIGN KEY ([ENQ_RESP_COD_TYP_ID]) REFERENCES [ncts].[ENQ_RESP_COD_TYP] ([ID]),
    CONSTRAINT [FK_ERSCTN_ERSCT] FOREIGN KEY ([ENQ_RESP_COD_TYP_ID]) REFERENCES [ncts].[ENQ_RESP_COD_TYP] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [ERCTN_ERCTI_I]
    ON [ncts].[ENQ_RESP_COD_TYP_NAM]([ENQ_RESP_COD_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [ERCTN_LI_I]
    ON [ncts].[ENQ_RESP_COD_TYP_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];

