CREATE TABLE [ncts].[ENQ_INF_RESP] (
    [CUST_OFF_ID]         VARCHAR (8)    NOT NULL,
    [ENQ_COMM_SID]        INT            NOT NULL,
    [SID]                 INT            NOT NULL,
    [ADD_INF_RESP_TYP_ID] CHAR (2)       NOT NULL,
    [TEXT]                NVARCHAR (420) NULL,
    [DAT_RESP]            DATETIME       NULL,
    [COUNTER_REQ]         DECIMAL (4)    NULL,
    CONSTRAINT [PK_ENQ_INF_RESP] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [EIRES_COI_OF_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [EIRP_COI_I]
    ON [ncts].[ENQ_INF_RESP]([CUST_OFF_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EIRP_ECS_I]
    ON [ncts].[ENQ_INF_RESP]([ENQ_COMM_SID] ASC)
    ON [FG_NCTS];

