CREATE TABLE [ncts].[ENQ_INF_COD_TYP_NAM] (
    [ENQ_INF_COD_TYP_ID] DECIMAL (2)   NOT NULL,
    [LANG_ID]            CHAR (2)      NULL,
    [NAM]                VARCHAR (420) NULL,
    [DAT_START]          DATETIME      NULL,
    [DAT_END]            DATETIME      NULL,
    CONSTRAINT [EICTN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [EICTN_OF_EICT] FOREIGN KEY ([ENQ_INF_COD_TYP_ID]) REFERENCES [ncts].[ENQ_INF_COD_TYP] ([ID]),
    CONSTRAINT [FK_EICTN_EICT] FOREIGN KEY ([ENQ_INF_COD_TYP_ID]) REFERENCES [ncts].[ENQ_INF_COD_TYP] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EICTN_EICTI_I]
    ON [ncts].[ENQ_INF_COD_TYP_NAM]([ENQ_INF_COD_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EICTN_LI_I]
    ON [ncts].[ENQ_INF_COD_TYP_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];

