CREATE TABLE [ncts].[ENQ_REQ_INF_COD_TYP] (
    [ID]        CHAR (2) NOT NULL,
    [DAT_START] DATETIME NULL,
    [DAT_END]   DATETIME NULL,
    CONSTRAINT [PK_ENQ_REQ_INF_COD_TYP] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

