CREATE TABLE [ncts].[ENQUIRY_INF_REQ] (
    [SID]                      INT          NOT NULL,
    [TRANS_OPER_SID]           INT          NOT NULL,
    [MRN]                      VARCHAR (21) NOT NULL,
    [CMP_DEP_CUST_OFF_INF_SID] INT          NOT NULL,
    [CMP_DES_CUST_OFF_INF_SID] INT          NULL,
    [ENQ_DATE]                 DATETIME     NOT NULL,
    CONSTRAINT [PK_ENQUIRY_INF_REQ] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS]
);


GO
CREATE NONCLUSTERED INDEX [EIR_CDCOIS_I]
    ON [ncts].[ENQUIRY_INF_REQ]([CMP_DEP_CUST_OFF_INF_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EIR_CDSCOIS_I]
    ON [ncts].[ENQUIRY_INF_REQ]([CMP_DES_CUST_OFF_INF_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EIR_MRN_I]
    ON [ncts].[ENQUIRY_INF_REQ]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EIR_TOS_I]
    ON [ncts].[ENQUIRY_INF_REQ]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];

