CREATE TABLE [ncts].[ENQUIRY_INF_DET] (
    [SID]                INT            NOT NULL,
    [ENQUIRY_INF_SID]    INT            NOT NULL,
    [ENQ_INF_COD_TYP_ID] DECIMAL (2)    NOT NULL,
    [ENQ_INF_TEXT]       NVARCHAR (420) NULL,
    CONSTRAINT [PK_ENQUIRY_INF_DET] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [EIS_EI_S] FOREIGN KEY ([ENQUIRY_INF_SID]) REFERENCES [ncts].[ENQUIRY_INF] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [EID_EIS_I]
    ON [ncts].[ENQUIRY_INF_DET]([ENQUIRY_INF_SID] ASC)
    ON [FG_NCTS];

