CREATE TABLE [ncts].[ENQUIRY_INF_REQ_DET] (
    [SID]                    INT            NOT NULL,
    [ENQUIRY_INF_REQ_SID]    INT            NOT NULL,
    [ENQ_REQ_INF_COD_TYP_ID] CHAR (2)       NOT NULL,
    [ENQ_REQ_INF_TEXT]       NVARCHAR (420) NULL,
    CONSTRAINT [PK_ENQUIRY_INF_REQ_DET] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [EIRS_EIR_S] FOREIGN KEY ([ENQUIRY_INF_REQ_SID]) REFERENCES [ncts].[ENQUIRY_INF_REQ] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [EIRD_EIRS_I]
    ON [ncts].[ENQUIRY_INF_REQ_DET]([ENQUIRY_INF_REQ_SID] ASC)
    ON [FG_NCTS];

