CREATE TABLE [ncts].[ENQUIRY_INF] (
    [SID]                      INT          NOT NULL,
    [TRANS_OPER_SID]           INT          NOT NULL,
    [MRN]                      VARCHAR (21) NOT NULL,
    [REQ_CUST_OFF_INF_SID]     INT          NULL,
    [CMP_DEP_CUST_OFF_INF_SID] INT          NOT NULL,
    [CMP_DES_CUST_OFF_INF_SID] INT          NULL,
    [ENQ_DATE]                 DATETIME     NOT NULL,
    [INF_FROM_PRINCIPAL]       DECIMAL (1)  NULL,
    CONSTRAINT [PK_ENQUIRY_INF] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS]
);


GO
CREATE NONCLUSTERED INDEX [EI_CDCOIS_I]
    ON [ncts].[ENQUIRY_INF]([CMP_DEP_CUST_OFF_INF_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EI_CDSCOIS_I]
    ON [ncts].[ENQUIRY_INF]([CMP_DES_CUST_OFF_INF_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EI_MRN_I]
    ON [ncts].[ENQUIRY_INF]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EI_RCOIS_I]
    ON [ncts].[ENQUIRY_INF]([REQ_CUST_OFF_INF_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [EI_TOS_I]
    ON [ncts].[ENQUIRY_INF]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];

