CREATE TABLE [ncts].[GUARANTEE_TYP_NAM] (
    [GUARANTEE_TYP_ID] CHAR (2)      NOT NULL,
    [LANG_ID]          CHAR (2)      NOT NULL,
    [NAM]              VARCHAR (420) NOT NULL,
    [DAT_END]          DATETIME      NULL,
    [DAT_START]        DATETIME      NULL,
    CONSTRAINT [FK_GTN_GT] FOREIGN KEY ([GUARANTEE_TYP_ID]) REFERENCES [ncts].[GUARANTEE_TYP] ([ID]),
    CONSTRAINT [GTN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [GTN_OF_GT] FOREIGN KEY ([GUARANTEE_TYP_ID]) REFERENCES [ncts].[GUARANTEE_TYP] ([ID])
) ON [FG_NCTS];

