CREATE TABLE [ncts].[GUARANTEE_I] (
    [SID]              INT         NOT NULL,
    [TRANS_OPER_SID]   INT         NULL,
    [VERS_NUMB]        DECIMAL (3) NULL,
    [GUARANTEE_TYP_ID] CHAR (2)    NOT NULL,
    CONSTRAINT [PK_GUARANTEE_I] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_GI_TOV] FOREIGN KEY ([TRANS_OPER_SID], [VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB]),
    CONSTRAINT [G_I_OF_VERS] FOREIGN KEY ([TRANS_OPER_SID], [VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB]),
    CONSTRAINT [G_I_TYP] FOREIGN KEY ([GUARANTEE_TYP_ID]) REFERENCES [ncts].[GUARANTEE_TYP] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [GI_TOSVM_I]
    ON [ncts].[GUARANTEE_I]([TRANS_OPER_SID] ASC, [VERS_NUMB] ASC)
    ON [FG_NCTS];

