CREATE TABLE [ncts].[INV_GUARANTEE_REAS_NAM] (
    [INV_GUARANTEE_REAS_ID] VARCHAR (3)   NOT NULL,
    [LANG_ID]               CHAR (2)      NULL,
    [NAM]                   VARCHAR (420) NULL,
    [DAT_START]             DATETIME      NULL,
    [DAT_END]               DATETIME      NULL,
    CONSTRAINT [FK_IGRN_IGR] FOREIGN KEY ([INV_GUARANTEE_REAS_ID]) REFERENCES [ncts].[INV_GUARANTEE_REAS] ([ID]),
    CONSTRAINT [IGRN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [IGRN_OF_IGR] FOREIGN KEY ([INV_GUARANTEE_REAS_ID]) REFERENCES [ncts].[INV_GUARANTEE_REAS] ([ID])
) ON [FG_NCTS];

