CREATE TABLE [ncts].[INV_GUARANTEE_REAS] (
    [ID]        VARCHAR (3) NOT NULL,
    [DAT_START] DATETIME    NOT NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_INV_GUARANTEE_REAS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

