CREATE TABLE [ncts].[ITINERARY] (
    [SID]            INT         NOT NULL,
    [TRANS_OPER_SID] INT         NOT NULL,
    [VERS_NUMB]      DECIMAL (8) NOT NULL,
    [COUNTRY_ID]     CHAR (2)    NOT NULL,
    CONSTRAINT [PK_ITINERARY] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [I_TOS_TO_S_FK] FOREIGN KEY ([TRANS_OPER_SID]) REFERENCES [ncts].[TRANS_OPER] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [I_TOSVN_I]
    ON [ncts].[ITINERARY]([TRANS_OPER_SID] ASC, [VERS_NUMB] ASC)
    ON [FG_NCTS];

