CREATE TABLE [ncts].[LANG] (
    [ID]        CHAR (2) NOT NULL,
    [DAT_START] DATETIME NOT NULL,
    [DAT_END]   DATETIME NULL,
    CONSTRAINT [PK_LANG] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

