CREATE TABLE [ncts].[LANG_NAM] (
    [LANG_ID]    CHAR (2)      NOT NULL,
    [IN_LANG_ID] CHAR (2)      NOT NULL,
    [NAM]        VARCHAR (140) NOT NULL,
    [DAT_START]  DATETIME      NULL,
    [DAT_END]    DATETIME      NULL,
    CONSTRAINT [FK_LN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [LN_IN_L] FOREIGN KEY ([IN_LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [LN_OF_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [LN_ILI_I]
    ON [ncts].[LANG_NAM]([IN_LANG_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [LN_LI_I]
    ON [ncts].[LANG_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];

