CREATE TABLE [ncts].[MEAS_UNIT_NAM] (
    [MEAS_UNIT_ID] VARCHAR (3)   NOT NULL,
    [LANG_ID]      CHAR (2)      NOT NULL,
    [NAM]          VARCHAR (140) NOT NULL,
    [DAT_START]    DATETIME      NULL,
    [DAT_END]      DATETIME      NULL,
    CONSTRAINT [FK_MEAS_UNIT_NAM_MEAS_UNIT] FOREIGN KEY ([MEAS_UNIT_ID]) REFERENCES [ncts].[MEAS_UNIT] ([ID])
) ON [FG_NCTS];

