CREATE TABLE [ncts].[MEAS_UNIT] (
    [ID]        VARCHAR (3) NOT NULL,
    [DAT_START] DATETIME    NOT NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_MEAS_UNIT] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

