CREATE TABLE [ncts].[OFF_ROL_TYP_DESCR] (
    [OFF_ROL_TYP_ID] VARCHAR (3)   NOT NULL,
    [LANG_ID]        CHAR (2)      NOT NULL,
    [DESCR]          VARCHAR (210) NULL,
    [DAT_END]        DATETIME      NULL,
    [DAT_START]      DATETIME      NULL,
    CONSTRAINT [FK_ORTD_ORT] FOREIGN KEY ([OFF_ROL_TYP_ID]) REFERENCES [ncts].[OFF_ROL_TYP] ([ID]),
    CONSTRAINT [ORTD_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [ORTD_OF_ORT] FOREIGN KEY ([OFF_ROL_TYP_ID]) REFERENCES [ncts].[OFF_ROL_TYP] ([ID])
) ON [FG_NCTS];

