CREATE TABLE [ncts].[PACK_TYP_NAM] (
    [PACK_TYP_ID] CHAR (2)      NOT NULL,
    [LANG_ID]     CHAR (2)      NOT NULL,
    [NAM]         VARCHAR (420) NULL,
    [DAT_END]     DATETIME      NULL,
    [DAT_START]   DATETIME      NULL,
    CONSTRAINT [FK_PTN_PT] FOREIGN KEY ([PACK_TYP_ID]) REFERENCES [ncts].[PACK_TYP] ([ID]),
    CONSTRAINT [PTN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [PTN_OF_PT] FOREIGN KEY ([PACK_TYP_ID]) REFERENCES [ncts].[PACK_TYP] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [PTM_LI_I]
    ON [ncts].[PACK_TYP_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [PTM_PTI_I]
    ON [ncts].[PACK_TYP_NAM]([PACK_TYP_ID] ASC)
    ON [FG_NCTS];

