CREATE TABLE [ncts].[RECOVERY_GUARANTEE] (
    [SID]                     INT          NOT NULL,
    [GRN]                     VARCHAR (24) NOT NULL,
    [RECOVERY_ACCEPTANCE_SID] INT          NULL,
    [RECOVERY_REQUEST_SID]    INT          NULL,
    CONSTRAINT [PK_RECOVERY_GUARANTEE] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS]
);


GO
CREATE NONCLUSTERED INDEX [RG_RAS_I]
    ON [ncts].[RECOVERY_GUARANTEE]([RECOVERY_ACCEPTANCE_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [RG_RRS_I]
    ON [ncts].[RECOVERY_GUARANTEE]([RECOVERY_REQUEST_SID] ASC)
    ON [FG_NCTS];

