CREATE TABLE [ncts].[RECOVERY_REQUEST] (
    [SID]                        INT            NOT NULL,
    [TRANS_OPER_SID]             INT            NOT NULL,
    [MRN]                        VARCHAR (21)   NOT NULL,
    [CMP_REQUESTING_CUST_OFF_ID] VARCHAR (8)    NOT NULL,
    [CMP_REQUESTED_CUST_OFF_ID]  VARCHAR (8)    NOT NULL,
    [INFO_TEXT]                  NVARCHAR (420) NULL,
    [CONT_PERSON]                NVARCHAR (420) NULL,
    [COMM_DATE]                  DATETIME       NOT NULL,
    [REQUESTED]                  DECIMAL (1)    NOT NULL,
    [RESPONSE_RECEIVED]          DECIMAL (1)    NOT NULL,
    [TIMER_EXPIRED]              DECIMAL (1)    NOT NULL,
    CONSTRAINT [PK_RECOVERY_REQUEST] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS]
);


GO
CREATE NONCLUSTERED INDEX [RR_M_I]
    ON [ncts].[RECOVERY_REQUEST]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [RR_TOS_I]
    ON [ncts].[RECOVERY_REQUEST]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];

