CREATE TABLE [ncts].[RISK_ANA_TYP_NAM] (
    [RISK_ANA_TYP_ID] VARCHAR (1)   NOT NULL,
    [LANG_ID]         CHAR (2)      NOT NULL,
    [NAM]             VARCHAR (420) NULL,
    [DAT_START]       DATETIME      NULL,
    [DAT_END]         DATETIME      NULL,
    CONSTRAINT [PK_RISK_ANA_TYP_NAM] PRIMARY KEY CLUSTERED ([RISK_ANA_TYP_ID] ASC, [LANG_ID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_RATN_RAT] FOREIGN KEY ([RISK_ANA_TYP_ID]) REFERENCES [ncts].[RISK_ANA_TYP] ([ID]),
    CONSTRAINT [RATN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [RATN_OF_RAT] FOREIGN KEY ([RISK_ANA_TYP_ID]) REFERENCES [ncts].[RISK_ANA_TYP] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [RATN_LI_I]
    ON [ncts].[RISK_ANA_TYP_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [RATN_RATI_I]
    ON [ncts].[RISK_ANA_TYP_NAM]([RISK_ANA_TYP_ID] ASC)
    ON [FG_NCTS];

