CREATE TABLE [ncts].[SEAL_DET] (
    [SID]                      INT          NOT NULL,
    [TRANS_OPER_SID]           INT          NULL,
    [VERS_NUMB]                DECIMAL (3)  NULL,
    [SEAL_IDENT]               VARCHAR (60) NOT NULL,
    [SEAL_IDENT_LNG]           CHAR (2)     NULL,
    [RE_USE]                   CHAR (1)     NULL,
    [TRANS_OPER_UNL_MRN]       VARCHAR (21) NULL,
    [EN_ROUT_EVENT_MRN]        VARCHAR (21) NULL,
    [EN_ROUT_EVENT_SEQ]        DECIMAL (4)  NULL,
    [DEP_TRANS_OPER_MRN]       VARCHAR (21) NULL,
    [FROM_HS_GOODS_CLASS_ID]   VARCHAR (6)  NULL,
    [FROM_CN_GOODS_CLASS_ID]   CHAR (2)     NULL,
    [FROM_SENS_GOODS_CLASS_ID] CHAR (2)     NULL,
    [TO_HS_GOODS_CLASS_ID]     VARCHAR (6)  NULL,
    [TO_CN_GOODS_CLASS_ID]     CHAR (2)     NULL,
    [TO_SENS_GOODS_CLASS_ID]   CHAR (2)     NULL,
    [CUST_OFF_ADDR_SID]        INT          NULL,
    [TRAD_SP_AUTH_SID]         VARCHAR (17) NULL,
    [UNL_VERS_NUMB]            DECIMAL (8)  NULL,
    CONSTRAINT [PK_SEAL_DET] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_SD_TOV] FOREIGN KEY ([TRANS_OPER_SID], [VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB]),
    CONSTRAINT [SD_REC_IN_ERE] FOREIGN KEY ([EN_ROUT_EVENT_MRN], [EN_ROUT_EVENT_SEQ]) REFERENCES [ncts].[EN_ROUT_EVENT] ([MRN], [SEQ]),
    CONSTRAINT [SD_SEAL_IDENT_IN_L] FOREIGN KEY ([SEAL_IDENT_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [SD_USED_AT_SPACL] FOREIGN KEY ([TRAD_SP_AUTH_SID], [CUST_OFF_ADDR_SID]) REFERENCES [ncts].[SP_AUTH_CONTR_LOC] ([TRAD_SP_AUTH_ID], [CUST_OFF_ADDR_SID]),
    CONSTRAINT [SD_USED_FROM_GC_S] FOREIGN KEY ([FROM_HS_GOODS_CLASS_ID], [FROM_SENS_GOODS_CLASS_ID]) REFERENCES [ncts].[SENS_GOODS_CLASS] ([HS_GOODS_CLASS_ID], [SGI_COD]),
    CONSTRAINT [SD_USED_OF_VERS] FOREIGN KEY ([TRANS_OPER_SID], [VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB])
);


GO
CREATE NONCLUSTERED INDEX [SD_DTOM_I]
    ON [ncts].[SEAL_DET]([DEP_TRANS_OPER_MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SD_EREMERES_I]
    ON [ncts].[SEAL_DET]([EN_ROUT_EVENT_MRN] ASC, [EN_ROUT_EVENT_SEQ] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SD_FHGFSG_I]
    ON [ncts].[SEAL_DET]([FROM_HS_GOODS_CLASS_ID] ASC, [FROM_SENS_GOODS_CLASS_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SD_SIL_I]
    ON [ncts].[SEAL_DET]([SEAL_IDENT_LNG] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SD_THGTSG_I]
    ON [ncts].[SEAL_DET]([TO_HS_GOODS_CLASS_ID] ASC, [TO_SENS_GOODS_CLASS_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SD_TOSVN_I]
    ON [ncts].[SEAL_DET]([TRANS_OPER_SID] ASC, [VERS_NUMB] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SD_TOUM]
    ON [ncts].[SEAL_DET]([TRANS_OPER_UNL_MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SD_TSASCOAS_I]
    ON [ncts].[SEAL_DET]([TRAD_SP_AUTH_SID] ASC, [CUST_OFF_ADDR_SID] ASC)
    ON [FG_NCTS];

