CREATE TABLE [ncts].[SEAL_DET_VERS] (
    [TRANS_OPER_SID]       INT         NOT NULL,
    [TRANS_OPER_VERS_NUMB] DECIMAL (3) NOT NULL,
    [SEAL_DET_SID]         INT         NOT NULL,
    CONSTRAINT [PK_SEAL_DET_VERS] PRIMARY KEY CLUSTERED ([TRANS_OPER_SID] ASC, [TRANS_OPER_VERS_NUMB] ASC, [SEAL_DET_SID] ASC) ON [FG_NCTS],
    CONSTRAINT [SDV_IN_TOV] FOREIGN KEY ([TRANS_OPER_SID], [TRANS_OPER_VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB]),
    CONSTRAINT [SDV_REF_TO_SD] FOREIGN KEY ([SEAL_DET_SID]) REFERENCES [ncts].[SEAL_DET] ([SID])
);

