CREATE TABLE [ncts].[SP_AUTH_GOODS_EXCL] (
    [TRAD_SP_AUTH_ID]   VARCHAR (17) NOT NULL,
    [HS_GOODS_CLASS_ID] VARCHAR (6)  NOT NULL,
    [CN_GOODS_CLASS_ID] CHAR (2)     NULL,
    CONSTRAINT [FK_SAGE_TSAI] FOREIGN KEY ([TRAD_SP_AUTH_ID]) REFERENCES [ncts].[TRAD_SP_AUTH_ID] ([ID]),
    CONSTRAINT [SPAGE_ON_TSPA] FOREIGN KEY ([TRAD_SP_AUTH_ID]) REFERENCES [ncts].[TRAD_SP_AUTH_ID] ([ID]),
    CONSTRAINT [SPAGE_UK] UNIQUE NONCLUSTERED ([CN_GOODS_CLASS_ID] ASC, [HS_GOODS_CLASS_ID] ASC, [TRAD_SP_AUTH_ID] ASC) ON [FG_NCTS]
) ON [FG_NCTS];

