CREATE TABLE [ncts].[SPEC_NOT_COD] (
    [DAT_END]   DATETIME    NULL,
    [DAT_START] DATETIME    NOT NULL,
    [ID]        VARCHAR (6) NOT NULL,
    CONSTRAINT [PK_SPEC_NOT_COD] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

