CREATE TABLE [ncts].[SPEC_CIRC_IND] (
    [ID]        CHAR (1) NOT NULL,
    [DAT_START] DATETIME NOT NULL,
    [DAT_END]   DATETIME NULL,
    CONSTRAINT [PK_SPEC_CIRC_IND] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

