CREATE TABLE [ncts].[SPEC_NOT_COD_NAM] (
    [DAT_END]         DATETIME       NULL,
    [DAT_START]       DATETIME       NULL,
    [NAM]             VARCHAR (1050) NOT NULL,
    [LANG_ID]         CHAR (2)       NOT NULL,
    [SPEC_NOT_COD_ID] VARCHAR (6)    NOT NULL,
    CONSTRAINT [FK_SNCN_SNC] FOREIGN KEY ([SPEC_NOT_COD_ID]) REFERENCES [ncts].[SPEC_NOT_COD] ([ID]),
    CONSTRAINT [SNCN_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [SNCN_OF_SNC] FOREIGN KEY ([SPEC_NOT_COD_ID]) REFERENCES [ncts].[SPEC_NOT_COD] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SNCN_LI_I]
    ON [ncts].[SPEC_NOT_COD_NAM]([LANG_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [SNCN_SNCI_I]
    ON [ncts].[SPEC_NOT_COD_NAM]([SPEC_NOT_COD_ID] ASC)
    ON [FG_NCTS];

