CREATE TABLE [ncts].[SPEC_CIRC_IND_NAM] (
    [SPEC_CIRC_IND_ID] CHAR (1)      NOT NULL,
    [LANG_ID]          CHAR (2)      NOT NULL,
    [NAM]              VARCHAR (210) NULL,
    [DAT_END]          DATETIME      NULL,
    [DAT_START]        DATETIME      NULL,
    CONSTRAINT [FK_SCIN_SCI] FOREIGN KEY ([SPEC_CIRC_IND_ID]) REFERENCES [ncts].[SPEC_CIRC_IND] ([ID])
) ON [FG_NCTS];

