CREATE TABLE [ncts].[TRAD_OFF_SP_AUTH] (
    [CUST_OFF_ID]     VARCHAR (8)  NOT NULL,
    [TRAD_SP_AUTH_ID] VARCHAR (17) NOT NULL,
    CONSTRAINT [PK_TRAD_OFF_SP_AUTH] PRIMARY KEY CLUSTERED ([CUST_OFF_ID] ASC, [TRAD_SP_AUTH_ID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_TOSA_TSAI] FOREIGN KEY ([TRAD_SP_AUTH_ID]) REFERENCES [ncts].[TRAD_SP_AUTH_ID] ([ID]),
    CONSTRAINT [TOSPA_BAS_ON_TSPA] FOREIGN KEY ([TRAD_SP_AUTH_ID]) REFERENCES [ncts].[TRAD_SP_AUTH_ID] ([ID]),
    CONSTRAINT [TOSPA_GIV_TO_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID])
);

