CREATE TABLE [ncts].[TRAD_SP_AUTH] (
    [ID]               VARCHAR (17)  NOT NULL,
    [LOC]              VARCHAR (3)   NOT NULL,
    [DAT_REQ]          DATETIME      NOT NULL,
    [DAT_SENT_TO_TRAD] DATETIME      NOT NULL,
    [DAT_EXP]          DATETIME      NULL,
    [MAX_JOURN_TIM]    DECIMAL (2)   NULL,
    [COMM]             VARCHAR (350) NULL,
    [TRAD_SID]         INT           NULL,
    [CUST_OFF_ID]      VARCHAR (8)   NOT NULL,
    [COMM_LNG]         CHAR (2)      NULL,
    [USER_ID]          VARCHAR (7)   NULL,
    [DECL_TYP]         VARCHAR (9)   NOT NULL,
    CONSTRAINT [PK_TRAD_SP_AUTH] PRIMARY KEY CLUSTERED ([ID] ASC, [LOC] ASC, [DECL_TYP] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_TSA_T] FOREIGN KEY ([TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [FK_TSA_TSAI] FOREIGN KEY ([ID]) REFERENCES [ncts].[TRAD_SP_AUTH_ID] ([ID]),
    CONSTRAINT [TSPA_COMM_IN_L] FOREIGN KEY ([COMM_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [TSPA_FOR_T] FOREIGN KEY ([TRAD_SID]) REFERENCES [ncts].[TRAD] ([SID]),
    CONSTRAINT [TSPA_GRANT_BY_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID]),
    CONSTRAINT [TSPA_ON_TSPAI] FOREIGN KEY ([ID]) REFERENCES [ncts].[TRAD_SP_AUTH_ID] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [TSA_TS_I]
    ON [ncts].[TRAD_SP_AUTH]([TRAD_SID] ASC)
    ON [FG_NCTS];

