CREATE TABLE [ncts].[TRADER_ENQUIRY_RESP] (
    [SID]                INT            NOT NULL,
    [TRANS_OPER_SID]     INT            NOT NULL,
    [MRN]                VARCHAR (21)   NOT NULL,
    [PRES_CUST_OFF_ID]   VARCHAR (8)    NULL,
    [TCC_DELIVERED]      DECIMAL (1)    NOT NULL,
    [DEL_DATE_TC11]      DATETIME       NULL,
    [INFO_TEXT]          NVARCHAR (420) NULL,
    [INFO_AVAILABLE]     DECIMAL (1)    NOT NULL,
    [ACT_CONS_TRAD_SID]  INT            NULL,
    [ACT_CONS_TRADS_SID] INT            NULL,
    [ACT_CONS_TRAD_TIN]  VARCHAR (17)   NULL,
    CONSTRAINT [PK_TRADER_ENQUIRY_RESP] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [TER_PCOI_CO_ID] FOREIGN KEY ([PRES_CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID]),
    CONSTRAINT [TERS_TOS_TO_S_FK] FOREIGN KEY ([TRANS_OPER_SID]) REFERENCES [ncts].[TRANS_OPER] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [TERS_MRN_I]
    ON [ncts].[TRADER_ENQUIRY_RESP]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TERS_MRN_TOS_U]
    ON [ncts].[TRADER_ENQUIRY_RESP]([MRN] ASC, [TRANS_OPER_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TERS_PCOI_I]
    ON [ncts].[TRADER_ENQUIRY_RESP]([PRES_CUST_OFF_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TERS_TOS_I]
    ON [ncts].[TRADER_ENQUIRY_RESP]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];

