CREATE TABLE [ncts].[TRAD_OFF_SP_AUTH_LOC] (
    [CUST_OFF_ID]     VARCHAR (8)  NOT NULL,
    [TRAD_SP_AUTH_ID] VARCHAR (17) NOT NULL,
    [LOC]             VARCHAR (17) NOT NULL,
    CONSTRAINT [PK_TRAD_OFF_SP_AUTH_LOC] PRIMARY KEY CLUSTERED ([CUST_OFF_ID] ASC, [TRAD_SP_AUTH_ID] ASC, [LOC] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_TOSAL_TOSA] FOREIGN KEY ([CUST_OFF_ID], [TRAD_SP_AUTH_ID]) REFERENCES [ncts].[TRAD_OFF_SP_AUTH] ([CUST_OFF_ID], [TRAD_SP_AUTH_ID]),
    CONSTRAINT [TOSPAL_BAS_ON_TSPA] FOREIGN KEY ([CUST_OFF_ID], [TRAD_SP_AUTH_ID]) REFERENCES [ncts].[TRAD_OFF_SP_AUTH] ([CUST_OFF_ID], [TRAD_SP_AUTH_ID])
);

