CREATE TABLE [ncts].[TRADER_ENQUIRY_REQ] (
    [SID]                     INT          NOT NULL,
    [MRN]                     VARCHAR (21) NOT NULL,
    [TRANS_OPER_SID]          INT          NOT NULL,
    [DATE_LIMIT_FOR_RESPONSE] DATETIME     NOT NULL,
    [DATE_OF_REQUEST]         DATETIME     NOT NULL,
    [COMP_CUST_OFF_ID]        VARCHAR (8)  NOT NULL,
    [DEP_CUST_OFF_ID]         VARCHAR (8)  NOT NULL,
    [RECEIVED_REPLY]          DECIMAL (1)  NOT NULL,
    CONSTRAINT [PK_TRADER_ENQUIRY_REQ] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [TER_TOS_TO_S_FK] FOREIGN KEY ([TRANS_OPER_SID]) REFERENCES [ncts].[TRANS_OPER] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [TER_CCOI_I]
    ON [ncts].[TRADER_ENQUIRY_REQ]([COMP_CUST_OFF_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TER_DCOI_I]
    ON [ncts].[TRADER_ENQUIRY_REQ]([DEP_CUST_OFF_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TER_MRN_TOS_U]
    ON [ncts].[TRADER_ENQUIRY_REQ]([MRN] ASC, [TRANS_OPER_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TER_TOS_I]
    ON [ncts].[TRADER_ENQUIRY_REQ]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];

