CREATE TABLE [ncts].[TRAFF_TYP] (
    [ID]        VARCHAR (3) NOT NULL,
    [NAT_DEF]   CHAR (1)    NULL,
    [DAT_START] DATETIME    NOT NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_TRAFF_TYP] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

