CREATE TABLE [ncts].[TRAFF_TYP_DESCR] (
    [TRAFF_TYP_ID] VARCHAR (3)   NOT NULL,
    [LANG_ID]      CHAR (2)      NOT NULL,
    [DESCR]        VARCHAR (140) NULL,
    [DAT_START]    DATETIME      NULL,
    [DAT_END]      DATETIME      NULL,
    CONSTRAINT [FK_TTD_TT] FOREIGN KEY ([TRAFF_TYP_ID]) REFERENCES [ncts].[TRAFF_TYP] ([ID]),
    CONSTRAINT [TTD_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [TTD_OF_TT] FOREIGN KEY ([TRAFF_TYP_ID]) REFERENCES [ncts].[TRAFF_TYP] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TTD_LI_I]
    ON [ncts].[TRAFF_TYP_DESCR]([LANG_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TTD_TTI_I]
    ON [ncts].[TRAFF_TYP_DESCR]([TRAFF_TYP_ID] ASC)
    ON [FG_NCTS];

