CREATE TABLE [ncts].[TRANS_OPER_MESS] (
    [CUST_OFF_ID]    VARCHAR (8)  NULL,
    [MESS_IDENT_ID]  VARCHAR (14) NOT NULL,
    [SID]            INT          NOT NULL,
    [MESS_ID]        VARCHAR (50) NOT NULL,
    [MESS_TYP_ID]    VARCHAR (6)  NOT NULL,
    [TRANS_OPER_SID] INT          NULL,
    [SENT]           CHAR (1)     NULL,
    [MESS_REC]       VARCHAR (50) NULL,
    [MESS_SEND]      VARCHAR (50) NULL,
    [UNIQ_REC_ID]    VARCHAR (50) NULL,
    [UNIQ_SEND_ID]   VARCHAR (50) NULL,
    [MRN]            VARCHAR (21) NULL,
    [LRN]            VARCHAR (22) NULL,
    [DAT_CR]         DATETIME     NULL,
    [DAT_REC]        DATETIME     NULL,
    [AUD_DAT_TIM]    DATETIME     NULL,
    [CHECK_SUM]      DECIMAL (8)  NULL,
    CONSTRAINT [PK_TRANS_OPER_MESS] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [TOM_CUST_OFF_ID_OF_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [TOM_LRN_IX]
    ON [ncts].[TRANS_OPER_MESS]([LRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOM_MI_I]
    ON [ncts].[TRANS_OPER_MESS]([MESS_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOM_MII_I]
    ON [ncts].[TRANS_OPER_MESS]([MESS_IDENT_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOM_MRN_IX]
    ON [ncts].[TRANS_OPER_MESS]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOM_MTI_I]
    ON [ncts].[TRANS_OPER_MESS]([MESS_TYP_ID] ASC)
    ON [FG_NCTS];

