CREATE TABLE [ncts].[TRANS_OPER_STAT_HIST] (
    [SID]                            BIGINT         NOT NULL,
    [TRANS_OPER_SID]                 INT            NULL,
    [TRANS_OPER_STAT_TYP_ID]         VARCHAR (3)    NULL,
    [TRANS_OPER_PASS_SID]            INT            NULL,
    [TRANS_OPER_STAT_TYP_ID_NA_TRAN] VARCHAR (3)    NULL,
    [USER_ID]                        DECIMAL (8)    NOT NULL,
    [GROUP_ID]                       DECIMAL (8)    NOT NULL,
    [ACTION]                         VARCHAR (100)  NULL,
    [REMARKS]                        VARCHAR (1500) NULL,
    [DAT_TIM_STAT]                   DATETIME       NOT NULL,
    [TRANS_OPER_PASS_STAT_TYP_ID]    VARCHAR (3)    NULL,
    CONSTRAINT [PK_TRANS_OPER_STAT_HIST] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_TOSH_TO] FOREIGN KEY ([TRANS_OPER_SID]) REFERENCES [ncts].[TRANS_OPER] ([SID]),
    CONSTRAINT [TOSH_TO] FOREIGN KEY ([TRANS_OPER_SID]) REFERENCES [ncts].[TRANS_OPER] ([SID]),
    CONSTRAINT [TOSH_TOP] FOREIGN KEY ([TRANS_OPER_PASS_SID]) REFERENCES [ncts].[TRANS_OPER_PASS] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [TOSH_TOPS_I]
    ON [ncts].[TRANS_OPER_STAT_HIST]([TRANS_OPER_PASS_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOSH_TOPSTI_I]
    ON [ncts].[TRANS_OPER_STAT_HIST]([TRANS_OPER_PASS_STAT_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOSH_TOSID_IX]
    ON [ncts].[TRANS_OPER_STAT_HIST]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOSH_TOSTI_I]
    ON [ncts].[TRANS_OPER_STAT_HIST]([TRANS_OPER_STAT_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOSH_TOSTINT_I]
    ON [ncts].[TRANS_OPER_STAT_HIST]([TRANS_OPER_STAT_TYP_ID_NA_TRAN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOSH_UI_I]
    ON [ncts].[TRANS_OPER_STAT_HIST]([USER_ID] ASC)
    ON [FG_NCTS];

