CREATE TABLE [ncts].[TRANS_CHRG_METH] (
    [ID]        VARCHAR (1) NOT NULL,
    [DAT_START] DATETIME    NOT NULL,
    [DAT_END]   DATETIME    NULL,
    CONSTRAINT [PK_TRANS_CHRG_METH] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_NCTS]
);

