CREATE TABLE [ncts].[TRANSP_MOD_DESCR] (
    [TRANSP_MOD_ID] CHAR (2)      NOT NULL,
    [LANG_ID]       CHAR (2)      NOT NULL,
    [DESCR]         VARCHAR (140) NULL,
    [DAT_START]     DATETIME      NULL,
    [DAT_END]       DATETIME      NULL,
    CONSTRAINT [FK_TMD_TM] FOREIGN KEY ([TRANSP_MOD_ID]) REFERENCES [ncts].[TRANSP_MOD] ([ID]),
    CONSTRAINT [TMD_IN_L] FOREIGN KEY ([LANG_ID]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [TMD_OF_TM] FOREIGN KEY ([TRANSP_MOD_ID]) REFERENCES [ncts].[TRANSP_MOD] ([ID])
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TMD_LI_I]
    ON [ncts].[TRANSP_MOD_DESCR]([LANG_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TMD_TMI_I]
    ON [ncts].[TRANSP_MOD_DESCR]([TRANSP_MOD_ID] ASC)
    ON [FG_NCTS];

