CREATE TABLE [ncts].[TRANS_OPER_VERS] (
    [TRANS_OPER_SID]          INT             NOT NULL,
    [VERS_NUMB]               DECIMAL (3)     NOT NULL,
    [TYP]                     CHAR (1)        NOT NULL,
    [STAT]                    CHAR (1)        NOT NULL,
    [DAT_SENT_BY_FIRST_PARTY] DATETIME        NULL,
    [DAT_TIM_FORM_DEC]        DATETIME        NULL,
    [DAT_REC_BY_SEC_PARTY]    DATETIME        NULL,
    [PLAC]                    NVARCHAR (105)  NULL,
    [PLAC_LNG]                CHAR (2)        NULL,
    [INIT_BY_CUST]            CHAR (1)        NULL,
    [REASON]                  NVARCHAR (1050) NULL,
    [REASON_LNG]              CHAR (2)        NULL,
    CONSTRAINT [PK_TRANS_OPER_VERS] PRIMARY KEY CLUSTERED ([TRANS_OPER_SID] ASC, [VERS_NUMB] ASC) ON [FG_NCTS],
    CONSTRAINT [FK_TOV_TO] FOREIGN KEY ([TRANS_OPER_SID]) REFERENCES [ncts].[TRANS_OPER] ([SID]),
    CONSTRAINT [TOV_PLAC_IN_L] FOREIGN KEY ([PLAC_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [TOV_REAS_LNG] FOREIGN KEY ([REASON_LNG]) REFERENCES [ncts].[LANG] ([ID]),
    CONSTRAINT [TOV_VERS_OF_TO] FOREIGN KEY ([TRANS_OPER_SID]) REFERENCES [ncts].[TRANS_OPER] ([SID])
);


GO
CREATE NONCLUSTERED INDEX [TOV_ST_I]
    ON [ncts].[TRANS_OPER_VERS]([STAT] ASC, [TYP] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOV_TS_I]
    ON [ncts].[TRANS_OPER_VERS]([TYP] ASC, [STAT] ASC)
    ON [FG_NCTS];

