CREATE TABLE [ncts].[TRANS_CHRG_METH_NAM] (
    [TRANS_CHRG_METH_ID] VARCHAR (1)   NOT NULL,
    [LANG_ID]            CHAR (2)      NULL,
    [NAM]                VARCHAR (210) NULL,
    [DAT_END]            DATETIME      NULL,
    [DAT_START]          DATETIME      NULL,
    CONSTRAINT [FK_TCMN_TCM] FOREIGN KEY ([TRANS_CHRG_METH_ID]) REFERENCES [ncts].[TRANS_CHRG_METH] ([ID])
) ON [FG_NCTS];

