CREATE TABLE [ncts].[TRANS_OPER_PASS] (
    [ATR_SENT]                    DECIMAL (1)  NULL,
    [SID]                         INT          NOT NULL,
    [MRN]                         VARCHAR (21) NULL,
    [TRANS_OPER_SID]              INT          NULL,
    [VERS_NUMB]                   DECIMAL (3)  NULL,
    [CUST_OFF_ID]                 VARCHAR (8)  NOT NULL,
    [DAT_TIM_OFF_ARR]             DATETIME     NULL,
    [TRANS_OPER_PASS_STAT_TYP_ID] VARCHAR (3)  NULL,
    [DAT_STAT_UPD]                DATETIME     NULL,
    [ARRIVED]                     CHAR (1)     NULL,
    [GUARANTEE_INV]               CHAR (1)     NULL,
    CONSTRAINT [PK_TRANS_OPER_PASS] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_NCTS],
    CONSTRAINT [TOP_OF_VERS] FOREIGN KEY ([TRANS_OPER_SID], [VERS_NUMB]) REFERENCES [ncts].[TRANS_OPER_VERS] ([TRANS_OPER_SID], [VERS_NUMB]),
    CONSTRAINT [TOP_TAK_PLAC_AT_CO] FOREIGN KEY ([CUST_OFF_ID]) REFERENCES [ncts].[CUST_OFF] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [TOP_COITOPSTI_I]
    ON [ncts].[TRANS_OPER_PASS]([CUST_OFF_ID] ASC, [TRANS_OPER_PASS_STAT_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOP_DSU_I]
    ON [ncts].[TRANS_OPER_PASS]([DAT_STAT_UPD] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOP_MRN_I]
    ON [ncts].[TRANS_OPER_PASS]([MRN] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOP_TOPSTI_I]
    ON [ncts].[TRANS_OPER_PASS]([TRANS_OPER_PASS_STAT_TYP_ID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOP_TOS]
    ON [ncts].[TRANS_OPER_PASS]([TRANS_OPER_SID] ASC)
    ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TOP_TOSVM_I]
    ON [ncts].[TRANS_OPER_PASS]([VERS_NUMB] ASC, [TRANS_OPER_SID] ASC)
    ON [FG_NCTS];

