CREATE TABLE [ncts].[TRANSH_CONT] (
    [MRN]               VARCHAR (21) NULL,
    [EN_ROUT_EVENT_SEQ] DECIMAL (4)  NOT NULL,
    [INC_IND]           VARCHAR (1)  NULL,
    [INC_FLAG]          VARCHAR (1)  NULL,
    [NEW_CONT_NUMB]     VARCHAR (17) NULL
) ON [FG_NCTS];


GO
CREATE NONCLUSTERED INDEX [TC_MERESI_I]
    ON [ncts].[TRANSH_CONT]([MRN] ASC, [EN_ROUT_EVENT_SEQ] ASC, [INC_IND] ASC)
    ON [FG_NCTS];

