CREATE TABLE [ncts].[UN_DANGER_GOODS_NAM] (
    [UN_DANGER_GOODS_ID] VARCHAR (4)   NOT NULL,
    [LANG_ID]            CHAR (2)      NULL,
    [NAM]                VARCHAR (420) NULL,
    [DAT_END]            DATETIME      NULL,
    [DAT_START]          DATETIME      NULL,
    CONSTRAINT [FK_UDGN_UDG] FOREIGN KEY ([UN_DANGER_GOODS_ID]) REFERENCES [ncts].[UN_DANGER_GOODS] ([ID])
) ON [FG_NCTS];

