CREATE TABLE [MF\FPLA].[AK_PDS_Małaszewicze_1_1_1] (
    [PDS_DokumentId]                NUMERIC (19)    NOT NULL,
    [PDS_TowarId]                   NUMERIC (19)    NULL,
    [PDS_Dokument_STATUS]           VARCHAR (4)     NULL,
    [NrWlasny]                      VARCHAR (35)    NULL,
    [Typ]                           VARCHAR (4)     NULL,
    [DataPrzybycia]                 DATETIME2 (3)   NULL,
    [DataPrzyjecia]                 DATETIME2 (3)   NULL,
    [DataRejestracji]               DATETIME2 (3)   NULL,
    [DataZatwierdzeniaWAR]          DATETIME2 (3)   NULL,
    [NrDokumentu]                   VARCHAR (35)    NULL,
    [NrPrzewozowy]                  VARCHAR (35)    NULL,
    [CRN]                           NVARCHAR (70)   NULL,
    [UCWprowadzenia]                VARCHAR (8)     NULL,
    [UCWprowadzeniaZmienionyNa]     VARCHAR (8)     NULL,
    [UCWprowadzeniaStanNaGranicy]   VARCHAR (8)     NULL,
    [UCZlozenia]                    VARCHAR (255)   NULL,
    [SpecyficzneOkolicznosci]       VARCHAR (1)     NULL,
    [OplatyTransportoweMP]          VARCHAR (1)     NULL,
    [MiejsceZaladunku]              NVARCHAR (35)   NULL,
    [MiejsceWyladunku]              NVARCHAR (35)   NULL,
    [LiczbaPozycji]                 INT             NULL,
    [PDS_Dokument_LiczbaOpakowan]   INT             NULL,
    [PDS_Dokument_MasaBrutto]       NUMERIC (14, 3) NULL,
    [PrzedstawienieTowaru]          VARCHAR (3)     NULL,
    [PodpisCyfrowy]                 TINYINT         NULL,
    [Nadawca_email]                 VARCHAR (255)   NULL,
    [Nadawca_nazwa]                 NVARCHAR (35)   NULL,
    [Nadawca_TIN]                   VARCHAR (17)    NULL,
    [Nadawca_Miejscowość]           NVARCHAR (35)   NULL,
    [Nadawca_Kraj]                  VARCHAR (2)     NULL,
    [Nadawca_KodPoczt]              VARCHAR (9)     NULL,
    [Nadawca_Ulica]                 NVARCHAR (35)   NULL,
    [Nadawca]                       VARCHAR (255)   NULL,
    [Odbiorca_email]                VARCHAR (255)   NULL,
    [Odbiorca_nazwa]                NVARCHAR (35)   NULL,
    [Odbiorca_TIN]                  VARCHAR (17)    NULL,
    [Odbiorca_Miejscowość]          NVARCHAR (35)   NULL,
    [Odbiorca_Kraj]                 VARCHAR (2)     NULL,
    [Odbiorca_KodPoczt]             VARCHAR (9)     NULL,
    [Odbiorca_Ulica]                NVARCHAR (35)   NULL,
    [Odbiorca]                      VARCHAR (255)   NULL,
    [Wprowadzający_email]           VARCHAR (255)   NULL,
    [Wprowadzający_nazwa]           NVARCHAR (35)   NULL,
    [Wprowadzający_TIN]             VARCHAR (17)    NULL,
    [Wprowadzający_Miejscowość]     NVARCHAR (35)   NULL,
    [Wprowadzający_Kraj]            VARCHAR (2)     NULL,
    [Wprowadzający_KodPoczt]        VARCHAR (9)     NULL,
    [Wprowadzający_Ulica]           NVARCHAR (35)   NULL,
    [Wprowadzający]                 VARCHAR (255)   NULL,
    [Składający_email]              VARCHAR (255)   NULL,
    [Składający_nazwa]              NVARCHAR (35)   NULL,
    [Składający_TIN]                VARCHAR (17)    NULL,
    [Składający_Miejscowość]        NVARCHAR (35)   NULL,
    [Składający_Kraj]               VARCHAR (2)     NULL,
    [Składający_KodPoczt]           VARCHAR (9)     NULL,
    [Składający_Ulica]              NVARCHAR (35)   NULL,
    [Składający]                    VARCHAR (255)   NULL,
    [Przedstawiciel_email]          VARCHAR (255)   NULL,
    [Przedstawiciel_nazwa]          NVARCHAR (35)   NULL,
    [Przedstawiciel_TIN]            VARCHAR (17)    NULL,
    [Przedstawiciel_Miejscowość]    NVARCHAR (35)   NULL,
    [Przedstawiciel_Kraj]           VARCHAR (2)     NULL,
    [Przedstawiciel_KodPoczt]       VARCHAR (9)     NULL,
    [Przedstawiciel_Ulica]          NVARCHAR (35)   NULL,
    [Przedstawiciel]                VARCHAR (255)   NULL,
    [OsobaKontakt_email]            VARCHAR (255)   NULL,
    [OsobaKontakt_nazwa]            NVARCHAR (35)   NULL,
    [OsobaKontakt_TIN]              VARCHAR (17)    NULL,
    [OsobaKontakt_Miejscowość]      NVARCHAR (35)   NULL,
    [OsobaKontakt_Kraj]             VARCHAR (2)     NULL,
    [OsobaKontakt_KodPoczt]         VARCHAR (9)     NULL,
    [OsobaKontakt_Ulica]            NVARCHAR (35)   NULL,
    [OsobaKontakt]                  VARCHAR (255)   NULL,
    [PDS_Towar_Id]                  NUMERIC (19)    NULL,
    [PDS_Towar_Status]              VARCHAR (4)     NULL,
    [NrPozycji]                     INT             NULL,
    [KodTowarowy]                   VARCHAR (8)     NULL,
    [KodTowarowyUCWprow]            VARCHAR (8)     NULL,
    [PDS_Towar_MasaBrutto]          NUMERIC (14, 3) NULL,
    [MasaBruttoUCWprow]             NUMERIC (14, 3) NULL,
    [OpisTowaru]                    NVARCHAR (280)  NULL,
    [OpisTowaruUCWprow]             VARCHAR (280)   NULL,
    [PowiadomienieOPrzybyciu_MRZ]   VARCHAR (35)    NULL,
    [Zamknięcia]                    NVARCHAR (20)   NULL,
    [LiczbaSztuk]                   INT             NULL,
    [LiczbaSztukNaGranicy]          INT             NULL,
    [RodzajOpakowan]                VARCHAR (2)     NULL,
    [RodzajNaGranicy]               VARCHAR (2)     NULL,
    [ZnakiOpakowan]                 VARCHAR (140)   NULL,
    [ZnakiNaGranicy]                VARCHAR (140)   NULL,
    [PDS_Opakowanie_LiczbaOpakowan] INT             NULL,
    [LiczbaOpakowanNaGranicy]       INT             NULL,
    [StanOpakowanNaGranicy]         VARCHAR (4)     NULL
);

