CREATE TABLE [cel].[v2_dok_pwd] (
    [idDokNr]                         BIGINT          NOT NULL,
    [LiczbaOpakowan]                  INT             NULL,
    [MasaBrutto]                      NUMERIC (14, 3) NULL,
    [TerminDostarczenia]              DATETIME        NULL,
    [Procedura]                       VARCHAR (2)     NULL,
    [WartoscStatystyczna]             BIGINT          NULL,
    [Zbiorcze]                        BIT             NULL,
    [UCPowiadomienia]                 VARCHAR (8)     NULL,
    [Lokalizacja_Miejsce]             VARCHAR (17)    NULL,
    [idUpowazniony]                   INT             NULL,
    [idOdbiorca]                      INT             NULL,
    [Tranzyt_Rodzaj]                  VARCHAR (4)     NULL,
    [Zamkniecia_Ilosc]                SMALLINT        NULL,
    [Zamkniecia_Zdejmujacy]           VARCHAR (35)    NULL,
    [ZwolnienieTowaru]                VARCHAR (1)     NULL,
    [TerminPU]                        DATETIME        NULL,
    [Zefir]                           VARCHAR (1)     NULL,
    [Sprostowanie_NrCelina]           VARCHAR (40)    NULL,
    [Sprostowanie_Nr]                 SMALLINT        NULL,
    [Sprostowanie_Data]               DATETIME        NULL,
    [idUpowaznionyEORI]               VARCHAR (20)    NULL,
    [idOdbiorcaEori]                  VARCHAR (20)    NULL,
    [idZglaszajacyPrzedstawiciel]     INT             NULL,
    [idZglaszajacyPrzedstawicielEORI] VARCHAR (20)    NULL,
    CONSTRAINT [PK_V2_DOK_PWD] PRIMARY KEY CLUSTERED ([idDokNr] ASC) WITH (FILLFACTOR = 90)
);

