CREATE TABLE [cel].[v2_dok_pzc] (
    [idDokNr]                 BIGINT          NOT NULL,
    [IdDok]                   VARCHAR (30)    NULL,
    [Typ]                     VARCHAR (1)     NULL,
    [Podtyp]                  VARCHAR (1)     NULL,
    [Powiadomienie]           BIT             NULL,
    [TypWPR1]                 VARCHAR (2)     NULL,
    [P1a]                     VARCHAR (2)     NULL,
    [P1b]                     VARCHAR (1)     NULL,
    [P1c]                     VARCHAR (5)     NULL,
    [ListyTowarowe]           INT             NULL,
    [LiczbaPozycji]           SMALLINT        NULL,
    [LiczbaOpakowan]          INT             NULL,
    [KrajWysylki]             VARCHAR (2)     NULL,
    [KrajPrzeznaczenia]       VARCHAR (2)     NULL,
    [Kontenery]               BIT             NULL,
    [RodzajTransakcji]        VARCHAR (2)     NULL,
    [MasaBrutto]              NUMERIC (14, 3) NULL,
    [PlatnoscOdroczona]       VARCHAR (25)    NULL,
    [idGlownyZobowiazany]     INT             NULL,
    [idOdbiorcaKarty3]        INT             NULL,
    [idUpowaznionyOdbiorca]   INT             NULL,
    [KodDost]                 VARCHAR (3)     NULL,
    [MiejsceDost]             VARCHAR (35)    NULL,
    [MiejsceKodDost]          VARCHAR (1)     NULL,
    [SzczegolyWartosci]       VARCHAR (1)     NULL,
    [Waluta]                  VARCHAR (3)     NULL,
    [Wartosc]                 NUMERIC (17, 2) NULL,
    [KursWaluty]              NUMERIC (10, 4) NULL,
    [KodWynKontr]             VARCHAR (2)     NULL,
    [TerminDostarczenia]      DATETIME        NULL,
    [IloscZamkniec]           SMALLINT        NULL,
    [idZglaszajacy]           INT             NULL,
    [Zgla_Przedstawicielstwo] VARCHAR (1)     NULL,
    [Zgla_Wskaznik]           VARCHAR (5)     NULL,
    [AdnotacjeUrzedowe]       VARCHAR (3000)  NULL,
    [Zgla_NRWpisu]            VARCHAR (35)    NULL,
    [Zgla_dataWpisu]          DATETIME        NULL,
    CONSTRAINT [PK_v2_dok_pzc] PRIMARY KEY CLUSTERED ([idDokNr] ASC) WITH (FILLFACTOR = 90)
);

