CREATE TABLE [cel].[v2_dok_dpdz] (
    [idDokNr]             BIGINT          NOT NULL,
    [LiczbaPozycji]       SMALLINT        NULL,
    [LiczbaOpakowan]      INT             NULL,
    [KrajWysylki]         VARCHAR (2)     NULL,
    [KrajPrzeznaczenia]   VARCHAR (2)     NULL,
    [MasaBrutto]          NUMERIC (14, 3) NULL,
    [ZwolnienieTowaru]    VARCHAR (1)     NULL,
    [PotwierdzenieWywozu] VARCHAR (1)     NULL,
    [NrCelina2]           VARCHAR (40)    NULL,
    [Zefir]               VARCHAR (1)     NULL,
    [RejestrDluguCelnego] VARCHAR (20)    NULL,
    [Wykaz]               VARCHAR (30)    NULL,
    [PozycjaWykazu]       INT             NULL,
    [Typ]                 VARCHAR (2)     NULL,
    [UCZgloszenia]        VARCHAR (8)     NULL,
    [Lokalizacja_Miejsce] VARCHAR (17)    NULL,
    [Lokalizacja_UC]      VARCHAR (8)     NULL,
    [Lokalizacja_Opis]    VARCHAR (35)    NULL,
    [Waluta]              VARCHAR (3)     NULL,
    [Wartosc]             NUMERIC (17, 2) NULL,
    [KursWaluty]          NUMERIC (10, 4) NULL,
    [idNadawca]           INT             NULL,
    [idOdbiorca]          INT             NULL,
    [IdZglaszajacy]       INT             NULL,
    CONSTRAINT [PK_V2_DOK_DPDZ] PRIMARY KEY CLUSTERED ([idDokNr] ASC) WITH (FILLFACTOR = 90)
);

