CREATE TABLE [dbo].[DSC_DZ8] (
    [ID]       INT    NOT NULL,
    [DZ8_1_01] BIGINT NULL,
    [DZ8_1_02] BIGINT NULL,
    CONSTRAINT [PK_DSC_DZ8] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DSC_DZ8_DSC_Naglowek] FOREIGN KEY ([ID]) REFERENCES [dbo].[DSC_Naglowek] ([ID])
);

