CREATE TABLE [dbo].[DSC_DZ10] (
    [ID]        INT    NOT NULL,
    [DZ10_1_01] BIGINT NULL,
    [DZ10_1_02] BIGINT NULL,
    [DZ10_1_03] BIGINT NULL,
    [DZ10_1_04] BIGINT NULL,
    [DZ10_1_05] BIGINT NULL,
    CONSTRAINT [PK_DSC_DZ10] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DSC_DZ10_DSC_Naglowek] FOREIGN KEY ([ID]) REFERENCES [dbo].[DSC_Naglowek] ([ID])
);

