CREATE TABLE [dbo].[DSC_DZ9] (
    [ID]        INT    NOT NULL,
    [DZ9_1_01]  BIGINT NULL,
    [DZ9_1_01A] BIGINT NULL,
    [DZ9_1_01B] BIGINT NULL,
    [DZ9_1_01C] BIGINT NULL,
    [DZ9_1_02]  BIGINT NULL,
    [DZ9_1_03]  BIGINT NULL,
    [DZ9_1_04]  BIGINT NULL,
    [DZ9_1_05]  BIGINT NULL,
    [DZ9_1_06]  BIGINT NULL,
    [DZ9_1_07]  BIGINT NULL,
    CONSTRAINT [PK_DSC_DZ9] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_DSC_DZ9_DSC_Naglowek] FOREIGN KEY ([ID]) REFERENCES [dbo].[DSC_Naglowek] ([ID])
);

