CREATE TABLE [dbo].[MOR_ANNUAL] (
    [ID]               INT             IDENTITY (1, 1) NOT NULL,
    [FormatkaKod]      VARCHAR (5)     NOT NULL,
    [JednostkaOrgId]   INT             NOT NULL,
    [Rok]              SMALLINT        NOT NULL,
    [StatusKod]        CHAR (1)        NOT NULL,
    [Wersja]           NUMERIC (5, 2)  NOT NULL,
    [ModyfikacjaLogin] NVARCHAR (256)  NOT NULL,
    [ModyfikacjaData]  DATETIME        NOT NULL,
    [Aktualny]         BIT             DEFAULT ((1)) NOT NULL,
    [Komentarz]        VARCHAR (3500)  NULL,
    [DZ3_1]            BIGINT          NULL,
    [DZ3_2_1]          DECIMAL (16, 2) NULL,
    [DZ3_2_2]          DECIMAL (16, 2) NULL,
    [DZ3_3]            BIGINT          NULL,
    [DZ4_1_1]          BIGINT          NULL,
    [DZ4_1_2]          BIGINT          NULL,
    [DZ4_2_1]          BIGINT          NULL,
    [DZ4_2_2]          BIGINT          NULL,
    [DZ5_1]            BIGINT          NULL,
    [DZ5_2]            BIGINT          NULL,
    [DZ5_3]            BIGINT          NULL,
    [DZ5_4]            BIGINT          NULL,
    [DZ5_5]            BIGINT          NULL,
    [DZ5_6]            BIGINT          NULL,
    [DZ5_6_1]          BIGINT          NULL,
    [DZ5_6_2]          BIGINT          NULL,
    [DZ5_6_3]          BIGINT          NULL,
    [DZ5_6_4]          BIGINT          NULL,
    [DZ5_6_5]          BIGINT          NULL,
    [DZ5_6_6]          BIGINT          NULL,
    [DZ6_1_01]         BIGINT          NULL,
    [DZ6_1_02]         BIGINT          NULL,
    [DZ6_1_03]         BIGINT          NULL,
    [DZ6_1_04]         DECIMAL (16, 2) NULL,
    [DZ6_1_05]         DECIMAL (16, 2) NULL,
    [DZ6_2_01]         BIGINT          NULL,
    [DZ6_2_02]         BIGINT          NULL,
    [DZ6_2_03]         BIGINT          NULL,
    [DZ6_2_04]         BIGINT          NULL,
    [DZ6_2_05]         BIGINT          NULL,
    [DZ6_2_06]         BIGINT          NULL,
    [DZ6_2_07]         DECIMAL (16, 2) NULL,
    [DZ6_2_08]         DECIMAL (16, 2) NULL,
    [DZ7_0]            DECIMAL (16, 2) NULL,
    [DZ7_1]            DECIMAL (16, 2) NULL,
    [DZ7_1_1]          DECIMAL (16, 2) NULL,
    [DZ7_1_2]          DECIMAL (16, 2) NULL,
    [DZ7_2]            DECIMAL (16, 2) NULL,
    [DZ7_2_1]          DECIMAL (16, 2) NULL,
    [DZ7_2_2]          DECIMAL (16, 2) NULL,
    [DZ7_2_3]          DECIMAL (16, 2) NULL,
    [DZ7_3]            DECIMAL (16, 2) NULL,
    [DZ7_4]            DECIMAL (16, 2) NULL,
    [DZ8_1_01]         BIGINT          NULL,
    [DZ8_1_02]         BIGINT          NULL,
    [DZ8_1_03]         BIGINT          NULL,
    [DZ8_1_04]         BIGINT          NULL,
    [DZ8_1_05]         BIGINT          NULL,
    [DZ8_1_06]         BIGINT          NULL,
    [DZ8_1_07]         BIGINT          NULL,
    [DZ8_2_01]         BIGINT          NULL,
    [DZ8_2_02]         BIGINT          NULL,
    [DZ8_2_03]         BIGINT          NULL,
    [DZ8_2_04]         BIGINT          NULL,
    [DZ8_2_05]         BIGINT          NULL,
    [DZ8_2_06]         BIGINT          NULL,
    [DZ8_2_07]         BIGINT          NULL,
    [DZ8_3_01]         BIGINT          NULL,
    [DZ8_3_02]         BIGINT          NULL,
    [DZ8_3_03]         BIGINT          NULL,
    [DZ8_3_04]         BIGINT          NULL,
    [DZ9_1_1_01]       BIGINT          NULL,
    [DZ9_1_1_02]       BIGINT          NULL,
    [DZ9_1_1_03]       BIGINT          NULL,
    [DZ9_1_1_04]       BIGINT          NULL,
    [DZ9_1_1_05]       BIGINT          NULL,
    [DZ9_1_1_06]       BIGINT          NULL,
    [DZ9_1_2_01]       BIGINT          NULL,
    [DZ9_1_2_02]       BIGINT          NULL,
    [DZ9_1_2_03]       BIGINT          NULL,
    [DZ9_1_2_04]       BIGINT          NULL,
    [DZ9_1_2_05]       BIGINT          NULL,
    [DZ9_1_2_06]       BIGINT          NULL,
    [DZ9_2_1_01]       BIGINT          NULL,
    [DZ9_2_1_02]       BIGINT          NULL,
    [DZ9_2_1_03]       BIGINT          NULL,
    [DZ9_2_1_04]       BIGINT          NULL,
    [DZ9_2_1_05]       BIGINT          NULL,
    [DZ9_2_1_06]       BIGINT          NULL,
    [DZ9_2_2_01]       BIGINT          NULL,
    [DZ9_2_2_02]       BIGINT          NULL,
    [DZ9_2_2_03]       BIGINT          NULL,
    [DZ9_2_2_04]       BIGINT          NULL,
    [DZ9_2_2_05]       BIGINT          NULL,
    [DZ9_2_2_06]       BIGINT          NULL,
    [ID_SharePoint]    INT             NULL,
    CONSTRAINT [PK_MOR_ANNUAL] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_MOR_ANNUAL_Formatka] FOREIGN KEY ([FormatkaKod]) REFERENCES [dbo].[Formatka] ([FormatkaKod]),
    CONSTRAINT [FK_MOR_ANNUAL_FormatkaStatus] FOREIGN KEY ([StatusKod]) REFERENCES [dbo].[FormatkaStatus] ([StatusKod]),
    CONSTRAINT [FK_MOR_ANNUAL_StrukturaOrganizacyjna] FOREIGN KEY ([JednostkaOrgId]) REFERENCES [dbo].[StrukturaOrganizacyjna] ([JednostkaId])
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ_MOR_ANNUAL]
    ON [dbo].[MOR_ANNUAL]([JednostkaOrgId] ASC, [FormatkaKod] ASC, [Rok] ASC, [Wersja] ASC);

