CREATE TABLE [MF\CSCH].[AP_27_ECS_EXT] (
    [decl_id]                           NUMERIC (19)    NULL,
    [Data_przedstawienia_w_UWA]         DATETIME2 (3)   NULL,
    [id]                                NUMERIC (19)    NULL,
    [status]                            NCHAR (1)       NULL,
    [numer_MRN]                         NVARCHAR (35)   NULL,
    [Data_przyjęcia_w_UWU_wywozu]       DATETIME2 (3)   NULL,
    [Data_zwolnienia_w_UWU_wywozu]      DATETIME2 (3)   NULL,
    [Urząd_wywozu]                      NVARCHAR (8)    NULL,
    [Deklarowany_UWA_wyprowadzenia]     NVARCHAR (8)    NULL,
    [Obsługujący_UWA_wyprowadzenia]     NVARCHAR (8)    NULL,
    [Obsługujacy_UWA_zmieniony_na]      NVARCHAR (8)    NULL,
    [Zgłoszenie_poch_z_ECS]             TINYINT         NULL,
    [kod_języka]                        NVARCHAR (2)    NULL,
    [Składowanie]                       TINYINT         NULL,
    [Deklaracja]                        NVARCHAR (2)    NULL,
    [Liczba_pozycji]                    INT             NULL,
    [Liczba_poz_na_granicy]             INT             NULL,
    [Komentarz_poz]                     NVARCHAR (420)  NULL,
    [Liczba_opakowań]                   INT             NULL,
    [Liczba_op_na_granicy]              INT             NULL,
    [Komentarz_op]                      NVARCHAR (420)  NULL,
    [Kraj_wysyłki]                      NVARCHAR (2)    NULL,
    [Kraj_przeznaczenia]                NVARCHAR (2)    NULL,
    [Kontenery]                         TINYINT         NULL,
    [Masa_brutto]                       NUMERIC (18, 3) NULL,
    [Masa_brutto_granica]               NUMERIC (18, 3) NULL,
    [Komentarz_masa]                    NVARCHAR (765)  NULL,
    [Termin_dotarcia_do_UWA]            DATETIME2 (3)   NULL,
    [Termin_na_wys_wyn_kontroli_do_UWU] DATETIME2 (3)   NULL,
    [Komentarze_z_granicy]              NVARCHAR (420)  NULL,
    [id_Przedstawiającego]              NUMERIC (19)    NULL,
    [Przedstawiający_nazwa]             NVARCHAR (105)  NULL,
    [Przed_adres]                       NVARCHAR (105)  NULL,
    [Przed_miasto]                      NVARCHAR (105)  NULL,
    [Przed_kod]                         NVARCHAR (9)    NULL,
    [Przed_kraj]                        NVARCHAR (2)    NULL,
    [Przed_NIP]                         NVARCHAR (17)   NULL,
    [id_Nadawcy]                        NUMERIC (19)    NULL,
    [Nadawca_nazwa]                     NVARCHAR (105)  NULL,
    [Nad_adres]                         NVARCHAR (105)  NULL,
    [Nad_miasto]                        NVARCHAR (105)  NULL,
    [Nad_kod]                           NVARCHAR (9)    NULL,
    [Nad_kraj]                          NVARCHAR (2)    NULL,
    [Nad_NIP]                           NVARCHAR (17)   NULL,
    [id_Odbiorcy]                       NUMERIC (19)    NULL,
    [Odbiorca_nazwa]                    NVARCHAR (105)  NULL,
    [Odb_adres]                         NVARCHAR (105)  NULL,
    [Odb_miasto]                        NVARCHAR (105)  NULL,
    [Odb_kod]                           NVARCHAR (9)    NULL,
    [Odb_kraj]                          NVARCHAR (2)    NULL,
    [Odb_NIP]                           NVARCHAR (17)   NULL,
    [id_Nadawcy_tow]                    NUMERIC (19)    NULL,
    [Nadawca_tow_nazwa]                 NVARCHAR (105)  NULL,
    [Nad_tow_adres]                     NVARCHAR (105)  NULL,
    [Nad_tow_miasto]                    NVARCHAR (105)  NULL,
    [Nad_tow_kod]                       NVARCHAR (9)    NULL,
    [Nad_tow_kraj]                      NVARCHAR (2)    NULL,
    [Nad_tow_NIP]                       NVARCHAR (17)   NULL,
    [id_Odbiorcy_tow]                   NUMERIC (19)    NULL,
    [Odbiorca_tow_nazwa]                NVARCHAR (105)  NULL,
    [Odb_tow_adres]                     NVARCHAR (105)  NULL,
    [Odb_tow_miasto]                    NVARCHAR (105)  NULL,
    [Odb_tow_kod]                       NVARCHAR (9)    NULL,
    [Odb_tow_kraj]                      NVARCHAR (2)    NULL,
    [Odb_tow_NIP]                       NVARCHAR (17)   NULL,
    [Urząd_celny]                       NVARCHAR (8)    NULL,
    [Miejsce_z_kodem_poza_UC]           NVARCHAR (17)   NULL,
    [Miejsce_bez_kodu_pozaUC]           NVARCHAR (765)  NULL,
    [Miej_składowania_z_kodem]          NVARCHAR (17)   NULL,
    [Miej_skład_bez_kodu]               NVARCHAR (765)  NULL,
    [Znaki_śr_transp_wewnetrznego]      NVARCHAR (765)  NULL,
    [Znaki_na_granicy]                  NVARCHAR (255)  NULL,
    [Trans_komentarz]                   NVARCHAR (765)  NULL,
    [NrPoz]                             INT             NULL,
    [Stan_na_granicy]                   NCHAR (1)       NULL,
    [Kraj_wysyłki_2]                    NVARCHAR (2)    NULL,
    [Kraj_przezn_2]                     NVARCHAR (2)    NULL,
    [Opis_towaru]                       NVARCHAR (840)  NULL,
    [Opis_towaru_granica]               NVARCHAR (840)  NULL,
    [Kod_towarowy]                      NVARCHAR (22)   NULL,
    [Kod_towarowy_granica]              NVARCHAR (22)   NULL,
    [Kod_towaru]                        NVARCHAR (8)    NULL,
    [Kod_Taric]                         NVARCHAR (2)    NULL,
    [Wartość_statystyczna]              NUMERIC (17, 2) NULL,
    [Waluta_wartości_statystycznej]     NVARCHAR (3)    NULL
);

