CREATE TABLE [MF\CSCH].[AP_29_Celina] (
    [Status]               CHAR (1)        NULL,
    [numer]                VARCHAR (40)    NULL,
    [DataPrzyjecia]        VARCHAR (10)    NULL,
    [Nadawca]              VARCHAR (14)    NULL,
    [NIP]                  VARCHAR (12)    NULL,
    [Nazwa]                VARCHAR (35)    NULL,
    [Ulica]                VARCHAR (35)    NULL,
    [Kod]                  VARCHAR (9)     NULL,
    [Miejscowosc]          VARCHAR (35)    NULL,
    [Odbiorca]             VARCHAR (14)    NULL,
    [TIN1]                 VARCHAR (12)    NULL,
    [Nazwa1]               VARCHAR (35)    NULL,
    [Ulica1]               VARCHAR (35)    NULL,
    [Kod1]                 VARCHAR (9)     NULL,
    [Miejscowosc1]         VARCHAR (35)    NULL,
    [Zgłaszający]          VARCHAR (14)    NULL,
    [TIN2]                 VARCHAR (12)    NULL,
    [Nazwa2]               VARCHAR (35)    NULL,
    [Ulica2]               VARCHAR (35)    NULL,
    [Kod2]                 VARCHAR (9)     NULL,
    [Miejscowosc2]         VARCHAR (35)    NULL,
    [KrajW]                VARCHAR (2)     NULL,
    [KodDos]               VARCHAR (3)     NULL,
    [Miejsce_dostawy]      VARCHAR (35)    NULL,
    [RodzajTransakcji]     VARCHAR (2)     NULL,
    [P1a]                  VARCHAR (2)     NULL,
    [P1b]                  CHAR (1)        NULL,
    [P1c]                  VARCHAR (5)     NULL,
    [LiczbaOpakowan]       INT             NULL,
    [Kod_msc]              CHAR (1)        NULL,
    [Waluta]               VARCHAR (3)     NULL,
    [KursW]                DECIMAL (10, 4) NULL,
    [WartFak]              DECIMAL (17, 2) NULL,
    [UC_wwozu]             VARCHAR (8)     NULL,
    [NrPozyc]              SMALLINT        NULL,
    [CN]                   VARCHAR (8)     NULL,
    [KodTaric]             VARCHAR (2)     NULL,
    [OpisCN]               VARCHAR (1000)  NULL,
    [KrajPoch]             VARCHAR (2)     NULL,
    [Proce]                VARCHAR (4)     NULL,
    [WartoscPozycji]       DECIMAL (17, 2) NULL,
    [MasaNetto]            DECIMAL (14, 3) NULL,
    [IloscUzupelniajacaJm] DECIMAL (14, 3) NULL,
    [WarStat]              BIGINT          NULL
);

