CREATE TABLE [MF\CSCH].[AP_27_dpdz] (
    [IdDoknr]                   BIGINT          NOT NULL,
    [Nr_zgłoszenia]             VARCHAR (40)    NULL,
    [Status]                    CHAR (1)        NULL,
    [Data_przyjęcia]            DATETIME        NULL,
    [ExtractDate]               DATETIME        NULL,
    [RodzajDok]                 VARCHAR (4)     NULL,
    [Opis]                      VARCHAR (250)   NULL,
    [Rodzaj]                    CHAR (1)        NULL,
    [Znaki]                     VARCHAR (27)    NULL,
    [UCZgloszenia]              VARCHAR (8)     NULL,
    [Typ]                       VARCHAR (2)     NULL,
    [Liczba_pozycji]            SMALLINT        NULL,
    [liczba_opakowań]           INT             NULL,
    [Wartość]                   DECIMAL (17, 2) NULL,
    [Kraj_Przeznaczenia]        VARCHAR (2)     NULL,
    [Kraj_wysyłki]              VARCHAR (2)     NULL,
    [Masa_brutto]               DECIMAL (14, 3) NULL,
    [Waluta]                    VARCHAR (3)     NULL,
    [Kurs_Waluty]               DECIMAL (10, 4) NULL,
    [NrCelina2]                 VARCHAR (40)    NULL,
    [Id_Zglaszjacego]           INT             NULL,
    [Nazwa_Zglaszjacego]        VARCHAR (35)    NULL,
    [REGON_Zglaszjacego]        VARCHAR (14)    NULL,
    [TIN_Zglaszjacego]          VARCHAR (12)    NULL,
    [Ulica_Nr_Zglaszjacego]     VARCHAR (35)    NULL,
    [Kod_pocztowy_Zglaszjacego] VARCHAR (9)     NULL,
    [Miejscowość_Zglaszjacego]  VARCHAR (35)    NULL,
    [Kraj_Zglaszjacego]         VARCHAR (2)     NULL,
    [Id_Odbiorcy]               INT             NULL,
    [Nazwa_Odbiorcy]            VARCHAR (35)    NULL,
    [REGON_Odbiorcy]            VARCHAR (14)    NULL,
    [TIN_Odbiorcy]              VARCHAR (12)    NULL,
    [Ulica_Nr_Odbiorcy]         VARCHAR (35)    NULL,
    [Kod_pocztowy_Odbiorcy]     VARCHAR (9)     NULL,
    [Miejscowość_Odbiorcy]      VARCHAR (35)    NULL,
    [Kraj_Odbiorcy]             VARCHAR (2)     NULL,
    [Id_Nadawcy]                INT             NULL,
    [Nazwa_Nadawcy]             VARCHAR (35)    NULL,
    [REGON_Nadawcy]             VARCHAR (14)    NULL,
    [TIN_Nadawcy]               VARCHAR (12)    NULL,
    [Ulica_Nr_Nadawcy]          VARCHAR (35)    NULL,
    [Kod_pocztowy_Nadawcy]      VARCHAR (9)     NULL,
    [Miejscowość_Nadawcy]       VARCHAR (35)    NULL,
    [Kraj_Nadawcy]              VARCHAR (2)     NULL,
    [LiczbaPozycji]             SMALLINT        NULL,
    [Pozycja]                   SMALLINT        NULL,
    [Kod_towaru]                VARCHAR (8)     NULL,
    [OpisTowaru]                VARCHAR (1000)  NULL,
    [Kraj_Pochodzenia]          VARCHAR (2)     NULL,
    [Procedura]                 VARCHAR (4)     NULL,
    [Procedura_szczegóły]       VARCHAR (3)     NULL,
    [Wartość_w_Walucie]         DECIMAL (17, 2) NULL,
    [Wartość_Statystyczna]      BIGINT          NULL,
    [Masa_Netto]                DECIMAL (14, 3) NULL,
    [Preferencje]               CHAR (3)        NULL,
    [Ilość_w_UzupJm]            DECIMAL (14, 3) NULL,
    [Samochod_Marka]            VARCHAR (3)     NULL,
    [Samochod_NrNadwozia]       VARCHAR (35)    NULL,
    [Samochod_NrSilnika]        VARCHAR (35)    NULL,
    [Samochod_Pojemnosc]        INT             NULL,
    [Samochod_RodzajPaliwa]     VARCHAR (2)     NULL,
    [Samochod_RokProdukcji]     INT             NULL
);

