CREATE TABLE [MF\CSCH].[AP_27_Celina] (
    [IdDokNr]                    BIGINT          NOT NULL,
    [Nr_zgłoszenia]              VARCHAR (40)    NULL,
    [Status]                     CHAR (1)        NULL,
    [Data_przyjęcia]             DATETIME        NULL,
    [ExtractDate]                DATETIME        NULL,
    [RodzajDok]                  VARCHAR (4)     NULL,
    [Kraj_Przeznaczenia]         VARCHAR (2)     NULL,
    [Kraj_wysyłki]               VARCHAR (2)     NULL,
    [Masa_brutto]                DECIMAL (14, 3) NULL,
    [Warunki_dostawy]            VARCHAR (3)     NULL,
    [Waluta]                     VARCHAR (3)     NULL,
    [Kurs_Waluty]                DECIMAL (10, 4) NULL,
    [RodzajTransakcji]           VARCHAR (2)     NULL,
    [LiczbaOpakowan]             INT             NULL,
    [P1a]                        VARCHAR (2)     NULL,
    [P1b]                        CHAR (1)        NULL,
    [P1c]                        VARCHAR (5)     NULL,
    [Id_Odbiorcy]                INT             NULL,
    [Nazwa_Odbiorcy]             VARCHAR (35)    NULL,
    [REGON_Odbiorcy]             VARCHAR (14)    NULL,
    [TIN_Odbiorcy]               VARCHAR (12)    NULL,
    [Ulica_Nr_Odbiorcy]          VARCHAR (35)    NULL,
    [Kod_pocztowy_Odbiorcy]      VARCHAR (9)     NULL,
    [Miejscowość_Odbiorcy]       VARCHAR (35)    NULL,
    [Kraj_Odbiorcy]              VARCHAR (2)     NULL,
    [Id_Nadawcy]                 INT             NULL,
    [Nazwa_Nadawcy]              VARCHAR (35)    NULL,
    [REGON_Nadawcy]              VARCHAR (14)    NULL,
    [TIN_Nadawcy]                VARCHAR (12)    NULL,
    [Ulica_Nr_Nadawcy]           VARCHAR (35)    NULL,
    [Kod_pocztowy_Nadawcy]       VARCHAR (9)     NULL,
    [Miejscowość_Nadawcy]        VARCHAR (35)    NULL,
    [Kraj_Nadawcy]               VARCHAR (2)     NULL,
    [Id_Zgłaszającego]           INT             NULL,
    [Nazwa_Zgłaszającego]        VARCHAR (35)    NULL,
    [REGON_Zgłaszającego]        VARCHAR (14)    NULL,
    [TIN_Zgłaszającego]          VARCHAR (12)    NULL,
    [Ulica_Nr_Zgłaszającego]     VARCHAR (35)    NULL,
    [Kod_pocztowy_Zgłaszającego] VARCHAR (9)     NULL,
    [Miejscowość_Zgłaszającego]  VARCHAR (35)    NULL,
    [Kraj_Zgłaszającego]         VARCHAR (2)     NULL,
    [składający]                 VARCHAR (35)    NULL,
    [Stanowisko]                 VARCHAR (35)    NULL,
    [Liczba_pozycji]             SMALLINT        NULL,
    [Pozycja]                    SMALLINT        NULL,
    [Kod_towaru]                 VARCHAR (8)     NULL,
    [OpisTowaru]                 VARCHAR (1000)  NULL,
    [Kraj_Pochodzenia]           VARCHAR (2)     NULL,
    [Procedura]                  VARCHAR (4)     NULL,
    [Procedura_szczegóły]        VARCHAR (3)     NULL,
    [Wartość_Pozycji_w_Walucie]  DECIMAL (17, 2) NULL,
    [Wartość_Statystyczna]       BIGINT          NULL,
    [Transport_na_granicy]       VARCHAR (27)    NULL,
    [Transport_w_kraju]          VARCHAR (27)    NULL,
    [Masa_Netto]                 DECIMAL (14, 3) NULL,
    [Preferencje]                CHAR (3)        NULL,
    [Ilość_w_UzupJm]             DECIMAL (14, 3) NULL,
    [Samochod_Marka]             VARCHAR (3)     NULL,
    [Samochod_NrNadwozia]        VARCHAR (35)    NULL,
    [Samochod_NrSilnika]         VARCHAR (35)    NULL,
    [Samochod_Pojemnosc]         INT             NULL,
    [Samochod_RodzajPaliwa]      VARCHAR (2)     NULL,
    [Samochod_RokProdukcji]      INT             NULL
);

