CREATE TABLE [MF\CSCH].[AP_37_AKCU_MW] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [LoginUzytkownikaWprowadzDok]           NVARCHAR (255)  NULL,
    [CzyZweryfikowany]                      NVARCHAR (5)    NULL,
    [NIPLubPESELPodatnika]                  NVARCHAR (30)   NULL,
    [NumerDokumentu]                        NVARCHAR (255)  NULL,
    [NumerPaczki]                           NVARCHAR (255)  NULL,
    [SystemZrodlowy]                        NVARCHAR (8)    NULL,
    [StatusDokumentu]                       NVARCHAR (100)  NULL,
    [NumerVATUE]                            NVARCHAR (4000) NULL,
    [Zarachowanie]                          NVARCHAR (5)    NULL,
    [PowodZarachowania]                     NVARCHAR (4000) NULL,
    [KodUrzeduSkarbowego]                   NVARCHAR (6)    NULL,
    [UrzadSkarbowyDoKtoregoAdresowaneNazwa] NVARCHAR (4000) NULL,
    [DeklaracjaCzyKorekta]                  INT             NULL,
    [DataZlozeniaDok]                       DATETIME2 (7)   NULL,
    [DataWplywuDok]                         DATETIME2 (7)   NULL,
    [NumerDokumentuPierwotnego]             NVARCHAR (255)  NULL,
    [UzasadnienieKorekty]                   NVARCHAR (4000) NULL,
    [RodzajKorekty]                         NVARCHAR (32)   NULL,
    [DataDoreczeniaKorektyZUrzedu]          DATETIME2 (7)   NULL,
    [DataDoWniesieniaSprzeciwu]             DATETIME2 (7)   NULL,
    [CzySprzeciwDoKorektyZUrzedu]           NVARCHAR (5)    NULL,
    [RazemKwotaPodatku]                     DECIMAL (19, 4) NULL,
    [ZwolnieniaObnizenia]                   DECIMAL (19, 4) NULL,
    [DoZaplaty]                             DECIMAL (19, 4) NULL,
    [TypIdentyfikatoraPelnomocnika]         NVARCHAR (15)   NULL,
    [IdentyfikatorPelnomocnika]             NVARCHAR (4000) NULL,
    [ImiePelnomocnika]                      NVARCHAR (4000) NULL,
    [NazwiskoPelnomocnika]                  NVARCHAR (4000) NULL,
    [TelefonPodatnikaLubPelnomocnika]       NVARCHAR (4000) NULL,
    [EmailPodatnikaLubPelnomocnika]         NVARCHAR (4000) NULL,
    [SprawdzPelnomocnictwa]                 NVARCHAR (5)    NULL,
    [UwagiUrzeduSkarbowego]                 NVARCHAR (4000) NULL,
    [FormaZlozeniaDok]                      NVARCHAR (255)  NULL,
    [DataZlozeniaDeklaracjiPierwotnej]      DATETIME2 (7)   NULL,
    [CzyOstatniaWersjaDeklaracji]           NVARCHAR (5)    NULL,
    [IdentyfikatorWpisu]                    BIGINT          NULL,
    [DataPowstaniaObowPodatk]               DATETIME2 (7)   NULL,
    [TerminPlatnosci]                       INT             NULL,
    [DataPlatnosci]                         DATETIME2 (7)   NULL,
    [StanSamochodu]                         VARCHAR (15)    NULL,
    [Marka]                                 VARCHAR (255)   NULL,
    [Model]                                 VARCHAR (255)   NULL,
    [RokProdukcji]                          VARCHAR (4)     NULL,
    [SposobNapedu]                          VARCHAR (255)   NULL,
    [PojemnoscSkokowaSilnika]               DECIMAL (19, 4) NULL,
    [PrzebiegKm]                            VARCHAR (255)   NULL,
    [NiestandardowyNumerVIN]                VARCHAR (5)     NULL,
    [NumerVIN]                              VARCHAR (255)   NULL,
    [NumerVINDotyczy]                       VARCHAR (30)    NULL,
    [MocSilnikaKW]                          VARCHAR (255)   NULL,
    [RodzajSkrzyniBiegow]                   VARCHAR (15)    NULL,
    [StanTechniczny]                        VARCHAR (50)    NULL,
    [PodstawObliczPodatkuWartoscWyrobow]    DECIMAL (19, 4) NULL,
    [StawkaPodatkuProcent]                  DECIMAL (19, 4) NULL,
    [KwotaPodatku]                          DECIMAL (19, 4) NULL,
    [MieniePrzesiedlencze]                  VARCHAR (5)     NULL,
    [Wspolwlasnosc]                         VARCHAR (5)     NULL
);

