CREATE TABLE [MF\CSCH].[AP_37_AKCU_MW_AKCU_1] (
    [IdentyfikatorDokumentu]                 BIGINT          NOT NULL,
    [ID_Pismo_xml]                           BIGINT          NULL,
    [NIPLubPESELPodatnika]                   NVARCHAR (500)  NULL,
    [CzyObcokrajowiec]                       NVARCHAR (5)    NULL,
    [NumerPodatnika]                         NVARCHAR (32)   NULL,
    [REGON]                                  NVARCHAR (4000) NULL,
    [RodzajPodatnika]                        NVARCHAR (16)   NULL,
    [NazwaPodatnika]                         NVARCHAR (255)  NULL,
    [NazwiskoPodatnika]                      NVARCHAR (255)  NULL,
    [ImiePodatnika]                          NVARCHAR (255)  NULL,
    [Kraj]                                   NVARCHAR (4000) NULL,
    [Wojewodztwo]                            NVARCHAR (4000) NULL,
    [Powiat]                                 NVARCHAR (4000) NULL,
    [Gmina]                                  NVARCHAR (4000) NULL,
    [Ulica]                                  NVARCHAR (4000) NULL,
    [NrDomu]                                 NVARCHAR (4000) NULL,
    [NrLokalu]                               NVARCHAR (4000) NULL,
    [Miejscowosc]                            NVARCHAR (4000) NULL,
    [KodPocztowy]                            NVARCHAR (4000) NULL,
    [Poczta]                                 NVARCHAR (4000) NULL,
    [NumerZPNW]                              NVARCHAR (255)  NULL,
    [NumerDokumentu]                         NVARCHAR (255)  NULL,
    [NumerPaczki]                            NVARCHAR (255)  NULL,
    [SystemZrodlowy]                         NVARCHAR (8)    NULL,
    [StatusDokumentu]                        NVARCHAR (4000) NULL,
    [NumerVATUE]                             NVARCHAR (4000) NULL,
    [DeklaracjaZaOkres]                      NVARCHAR (7)    NULL,
    [Zarachowanie]                           NVARCHAR (5)    NULL,
    [PowodZarachowania]                      NVARCHAR (4000) NULL,
    [UrzadCelny]                             NVARCHAR (255)  NULL,
    [DeklaracjaCzyKorekta]                   INT             NULL,
    [DataZlozeniaDok]                        DATETIME2 (7)   NULL,
    [DataWplywuDok]                          DATETIME2 (7)   NULL,
    [NumerDokumentuPierwotnego]              NVARCHAR (255)  NULL,
    [UzasadnienieKorekty]                    NVARCHAR (4000) NULL,
    [RodzajKorekty]                          NVARCHAR (32)   NULL,
    [DataDoreczeniaKorektyZUrzedu]           DATETIME2 (7)   NULL,
    [DataDoWniesieniaSprzeciwu]              DATETIME2 (7)   NULL,
    [CzySprzeciwDoKorektyZUrzedu]            NVARCHAR (5)    NULL,
    [RazemKwotaPodatku]                      DECIMAL (19, 2) NULL,
    [ZwolnieniaObnizenia]                    DECIMAL (19, 2) NULL,
    [KwotaZnakowAkcyzy]                      DECIMAL (19, 2) NULL,
    [ZwolnieniaObnizeniaDlaGrupy]            DECIMAL (19, 2) NULL,
    [KwotaZnakowAkcyzyDlaGrupy]              DECIMAL (19, 2) NULL,
    [KwotaPodatkuPoObnizeniach]              DECIMAL (19, 4) NULL,
    [DoZaplaty]                              DECIMAL (19, 2) NULL,
    [NumerZabezpieczenia]                    NVARCHAR (4000) NULL,
    [KwotaZwolnienia]                        INT             NULL,
    [ImiePelnomocnika]                       NVARCHAR (4000) NULL,
    [NazwiskoPelnomocnika]                   NVARCHAR (4000) NULL,
    [TelefonPodatnikaLubPelnomocnika]        NVARCHAR (4000) NULL,
    [EmailPodatnikaLubPelnomocnika]          NVARCHAR (4000) NULL,
    [SprawdzPelnomocnictwa]                  NVARCHAR (5)    NULL,
    [UwagiUrzeduCelnego]                     NVARCHAR (4000) NULL,
    [DataZlozeniaDeklaracjiPierwotnej]       DATETIME2 (7)   NULL,
    [CzyOstatniaWersjaDeklaracji]            NVARCHAR (5)    NULL,
    [IdentyfikatorWpisu]                     BIGINT          NULL,
    [ID_Tow]                                 BIGINT          NULL,
    [NazwaGrupyWyrobow]                      NVARCHAR (4000) NULL,
    [OpisTowaru]                             NVARCHAR (4000) NULL,
    [DataPowstaniaObowPodatk]                DATETIME2 (7)   NULL,
    [TerminPlatnosci]                        INT             NULL,
    [DataPlatnosci]                          DATETIME2 (7)   NULL,
    [Marka]                                  NVARCHAR (32)   NULL,
    [Model]                                  NVARCHAR (32)   NULL,
    [RokProdukcji]                           NVARCHAR (255)  NULL,
    [PojazdElektryczny]                      NVARCHAR (5)    NULL,
    [PojemnoscSkokowaSilnika]                DECIMAL (19, 4) NULL,
    [NiestandardowyNumerVIN]                 NVARCHAR (5)    NULL,
    [NumerVIN]                               NVARCHAR (255)  NULL,
    [InformacjeDodatkowe]                    NVARCHAR (4000) NULL,
    [KodCN]                                  NVARCHAR (255)  NULL,
    [PodstawObliczPodatkuIloscWyrobow]       DECIMAL (19, 4) NULL,
    [PodstawObliczPodatkuWartoscWyrobow]     DECIMAL (19, 4) NULL,
    [StawkaPodatkuProcent]                   DECIMAL (19, 4) NULL,
    [StawkaPodatkuKwota]                     DECIMAL (19, 4) NULL,
    [MinimalnaStawkaPodatkuOdWyrTytoniowych] DECIMAL (19, 4) NULL,
    [KwotaPodatku]                           DECIMAL (19, 2) NULL,
    [StawkaSpozaISZTAR]                      NVARCHAR (5)    NULL,
    [RodzajStawkiSpozaISZTAR]                NVARCHAR (16)   NULL,
    [WartoscStawkiSpozaISZTAR]               DECIMAL (19, 4) NULL,
    [DataArch]                               DATETIME2 (7)   NULL
);

