CREATE TABLE [MF\CSCH].[AP_grudzień_2018_AP__część_2] (
    [KodTowarowy]         VARCHAR (8)     NULL,
    [OpisTowaru]          VARCHAR (1000)  NULL,
    [MasaNetto]           DECIMAL (14, 3) NULL,
    [IloscTowaruUjm]      DECIMAL (14, 3) NULL,
    [WartoscStatystyczna] BIGINT          NULL,
    [ProceduraBiezaca]    VARCHAR (4)     NULL,
    [ProceduraPoprzednia] VARCHAR (4)     NULL,
    [NrCelina]            VARCHAR (40)    NULL,
    [DataPrzyjecia]       DATETIME        NULL,
    [KrajPochodzenia]     CHAR (2)        NULL,
    [KrajWysylki]         CHAR (2)        NULL,
    [TIN_Odb]             VARCHAR (12)    NULL,
    [REGON_Odb]           VARCHAR (14)    NULL,
    [Kraj_Odb]            CHAR (2)        NULL,
    [Miejscowosc_Odb]     VARCHAR (35)    NULL,
    [KodPocztowy_Odb]     VARCHAR (9)     NULL,
    [UlicaNumer_Odb]      VARCHAR (35)    NULL,
    [Nazwa_Odb]           VARCHAR (35)    NULL,
    [TINnad]              VARCHAR (12)    NULL,
    [REGONnad]            VARCHAR (14)    NULL,
    [KrajNad]             CHAR (2)        NULL,
    [MiejscowoscNad]      VARCHAR (35)    NULL,
    [KodPocztowyNad]      VARCHAR (9)     NULL,
    [UlicaNrNad]          VARCHAR (35)    NULL,
    [NazwaNad]            VARCHAR (35)    NULL
);

