CREATE TABLE [MF\CSCH].[AP_INTRASTAT_PALIWA_MIESIĘCZNE_styczeń_grudzień_2018_P] (
    [Status_Deklaracji]            NVARCHAR (16)   NULL,
    [Status_Pozycji]               NVARCHAR (17)   NULL,
    [Typ_Dok]                      NCHAR (1)       NULL,
    [Miesiąc_sprawozdawczy]        INT             NULL,
    [Rok_sprawozdawczy]            INT             NULL,
    [NIP_zobowiązanego]            NVARCHAR (10)   NULL,
    [REGON_zobowiązanego]          NVARCHAR (14)   NULL,
    [Nazwa_podmiotu]               NVARCHAR (255)  NULL,
    [Kraj_podmiotu]                NVARCHAR (2)    NULL,
    [Kod_pocztowy]                 NVARCHAR (50)   NULL,
    [Poczta]                       NVARCHAR (50)   NULL,
    [Miejscowość]                  NVARCHAR (50)   NULL,
    [Ulica]                        NVARCHAR (55)   NULL,
    [Nr_domu]                      NVARCHAR (12)   NULL,
    [Imię]                         NVARCHAR (50)   NULL,
    [Nazwisko]                     NVARCHAR (50)   NULL,
    [Numer_deklaracji]             NVARCHAR (30)   NOT NULL,
    [Nr_kontrahenta_zagranicznego] NVARCHAR (17)   NULL,
    [Nr_pozycji_towarowej]         SMALLINT        NULL,
    [Kod_towarowy]                 NVARCHAR (8)    NULL,
    [Opis_towaru]                  NVARCHAR (420)  NULL,
    [Kraj_wysyłki]                 NVARCHAR (2)    NULL,
    [Warunki_dostawy]              NVARCHAR (3)    NULL,
    [Rodzaj_transakcji]            NVARCHAR (4)    NULL,
    [Rodzaj_transportu]            NVARCHAR (4)    NULL,
    [Kraj_pochodzenia]             NVARCHAR (2)    NULL,
    [Masa_netto]                   NUMERIC (13, 2) NULL,
    [Uzup_jednostka_miary]         NUMERIC (13, 2) NULL,
    [Wartość_faktury]              NUMERIC (17, 2) NULL,
    [Wartość_statystyczna]         NUMERIC (17, 2) NULL
);

