CREATE TABLE [MF\CSCH].[AP_listopad_2018_AP__część_2] (
    [KodTowarowy]         VARCHAR (8)     NULL,
    [OpisTowaru]          VARCHAR (1000)  NULL,
    [MasaNetto]           DECIMAL (14, 3) NULL,
    [IloscTowaruUjm]      DECIMAL (14, 3) NULL,
    [WartoscStatystyczna] BIGINT          NULL,
    [ProceduraBiezaca]    VARCHAR (4)     NULL,
    [ProceduraPoprzednia] VARCHAR (4)     NULL,
    [NrCelina]            VARCHAR (40)    NULL,
    [DataPrzyjecia]       DATETIME        NULL,
    [KrajPochodzenia]     CHAR (2)        NULL,
    [KrajWysylki]         CHAR (2)        NULL,
    [TIN]                 VARCHAR (12)    NULL,
    [REGON]               VARCHAR (14)    NULL,
    [Kraj]                CHAR (2)        NULL,
    [Miejscowosc]         VARCHAR (35)    NULL,
    [KodPocztowy]         VARCHAR (9)     NULL,
    [UlicaNumer]          VARCHAR (35)    NULL,
    [Nazwa]               VARCHAR (35)    NULL,
    [TINnad]              VARCHAR (12)    NULL,
    [REGONnad]            VARCHAR (14)    NULL,
    [KrajNad]             CHAR (2)        NULL,
    [MiejscowoscNad]      VARCHAR (35)    NULL,
    [KodPocztowyNad]      VARCHAR (9)     NULL,
    [UlicaNrNad]          VARCHAR (35)    NULL,
    [NazwaNad]            VARCHAR (35)    NULL
);

