CREATE TABLE [MF\CSCH].[AP_REDAN_Dok_wymiarowe_POZA] (
    [IdentyfikatorDokumentu]     BIGINT          NOT NULL,
    [DataDoreczenia]             DATE            NULL,
    [DataPostanowienia]          DATE            NULL,
    [Instancja]                  NVARCHAR (10)   NULL,
    [NrPostanowieniaIInstancji]  NVARCHAR (255)  NULL,
    [RazemKwota]                 DECIMAL (19, 2) NULL,
    [RazemOdsetki]               DECIMAL (19, 2) NULL,
    [NumerPostanowienia]         NVARCHAR (255)  NULL,
    [UtrzymanieUchylenie]        NVARCHAR (10)   NULL,
    [AdnotacjeIUwagi]            NVARCHAR (512)  NULL,
    [RwPodstawaPrawna]           NVARCHAR (4000) NULL,
    [RwUzasadnienie]             NVARCHAR (MAX)  NULL,
    [ID_Pismo_xml]               BIGINT          NULL,
    [IdentyfikatorWpisu]         BIGINT          NOT NULL,
    [PierwotneNumer]             NVARCHAR (255)  NULL,
    [PierwotneData]              DATE            NULL,
    [IdentyfikatorPozycji]       NVARCHAR (255)  NULL,
    [PozycjeKwota]               DECIMAL (19, 2) NULL,
    [PozycjeOdsetki]             DECIMAL (19, 2) NULL,
    [PozycjeOplataProlongacyjna] DECIMAL (19, 2) NULL,
    [PozycjeRodzajNaleznosci]    NVARCHAR (255)  NULL,
    [TerminPlatnosci]            DATE            NULL
);

