CREATE TABLE [MF\CSCH].[AP_REDAN_emcs] (
    [Dok_ARC]                                   VARCHAR (21)    NOT NULL,
    [Status_dok]                                VARCHAR (20)    NOT NULL,
    [NrPorzadkowy]                              NUMERIC (2)     NULL,
    [Dok_LRN]                                   NVARCHAR (66)   NOT NULL,
    [MRN]                                       VARCHAR (21)    NULL,
    [CzyMiejsceWysylkiKrajowe]                  CHAR (1)        NOT NULL,
    [CzyPrzemieszczenieKrajowe]                 CHAR (1)        NULL,
    [KodPrzemieszczenia]                        VARCHAR (1)     NULL,
    [DataPowiadomieniaKontroli]                 DATETIME2 (6)   NULL,
    [DataCzasZatwierdzeniaAD]                   DATETIME2 (6)   NULL,
    [DataEksportu]                              DATETIME2 (6)   NULL,
    [DataUniewaznienia]                         DATETIME2 (6)   NULL,
    [DataCzasZatwierdzeniaUzup]                 DATETIME2 (6)   NULL,
    [DataRaportuODostarczeniu]                  DATETIME2 (6)   NULL,
    [DataCzasWysylki]                           DATETIME2 (6)   NOT NULL,
    [TypZgloszenia]                             VARCHAR (1)     NOT NULL,
    [KodRodzMiejscaPochRozpPrzem]               VARCHAR (1)     NOT NULL,
    [KodRodzMiejscaPrzezn]                      VARCHAR (1)     NOT NULL,
    [CzasPrzewozu]                              VARCHAR (3)     NOT NULL,
    [OrganizacjaPrzewozu]                       VARCHAR (1)     NOT NULL,
    [FlagaOdroczeniaPotwierdzenia]              CHAR (1)        NOT NULL,
    [NrFaktury]                                 VARCHAR (35)    NOT NULL,
    [DataFaktury]                               DATETIME2 (0)   NULL,
    [WysylajacyNrAkcyzowy]                      VARCHAR (13)    NOT NULL,
    [WysylajacyNazwa]                           NVARCHAR (546)  NOT NULL,
    [WysylajacyUlica]                           NVARCHAR (195)  NOT NULL,
    [WysylajacyNrDomu]                          NVARCHAR (33)   NULL,
    [WysylajacyKodPocztowy]                     NVARCHAR (30)   NOT NULL,
    [WysylajacyMiejscowosc]                     NVARCHAR (150)  NOT NULL,
    [MiejsceWysylkiNrSkladuPod]                 VARCHAR (13)    NULL,
    [MiejsceWysylkiNazwaPodm]                   NVARCHAR (546)  NULL,
    [MiejsceWysylkiUlica]                       NVARCHAR (195)  NULL,
    [MiejsceWysylkiNrDomu]                      NVARCHAR (33)   NULL,
    [MiejsceWysylkiKodPocztowy]                 NVARCHAR (30)   NULL,
    [MiejsceWysylkiMiejscowosc]                 NVARCHAR (150)  NULL,
    [UrzadNadzoruWMiejscuWysylki]               VARCHAR (8)     NOT NULL,
    [UrzadKontroliWMiejscuWysylki]              VARCHAR (8)     NULL,
    [OddzialDoKontroliWMiejscuZgloszenia]       VARCHAR (8)     NULL,
    [OdbierajacyIdentyfikacja]                  NVARCHAR (48)   NULL,
    [OdbierajacyNazwa]                          NVARCHAR (546)  NULL,
    [OdbierajacyUlica]                          NVARCHAR (195)  NULL,
    [OdbierajacyNrDomu]                         NVARCHAR (33)   NULL,
    [OdbierajacyKodPocztowy]                    NVARCHAR (30)   NULL,
    [OdbierajacyMiejscowosc]                    NVARCHAR (150)  NULL,
    [UzupOdbierajacyKodKraju]                   VARCHAR (2)     NULL,
    [UzupOdbierajacyNrSwiadectwaZwol]           VARCHAR (255)   NULL,
    [CzyOdbierajacyZmieniony]                   CHAR (1)        NOT NULL,
    [MiejsceDostawyIdentyfikacja]               NVARCHAR (48)   NULL,
    [MiejsceDostawyNazwaPodm]                   NVARCHAR (546)  NULL,
    [MiejsceDostawyUlica]                       NVARCHAR (195)  NULL,
    [MiejsceDostawyNrDomu]                      NVARCHAR (33)   NULL,
    [MiejsceDostawyKodPocztowy]                 NVARCHAR (30)   NULL,
    [MiejsceDostawyMiejscowosc]                 NVARCHAR (150)  NULL,
    [UrzadNadzoruWMiejscuOdbioru]               VARCHAR (8)     NULL,
    [UrzadKontroliWMiejscuOdbioru]              VARCHAR (8)     NULL,
    [GwarantKodRodz]                            VARCHAR (4)     NULL,
    [GRN]                                       VARCHAR (17)    NULL,
    [OdbierajacyTIN]                            VARCHAR (12)    NULL,
    [GwarantTIN]                                VARCHAR (12)    NULL,
    [KwotaGwarancji]                            NUMERIC (38, 2) NULL,
    [PozostalaKwotaGwarancji]                   NUMERIC (38, 2) NULL,
    [BrakujacaKwotaGwarancji]                   NUMERIC (38, 2) NULL,
    [Gwarant1NrAkcyzowy]                        VARCHAR (13)    NULL,
    [Gwarant1Nazwa]                             NVARCHAR (546)  NULL,
    [Gwarant1Ulica]                             NVARCHAR (195)  NULL,
    [Gwarant1NrDomu]                            NVARCHAR (33)   NULL,
    [Gwarant1KodPocztowy]                       NVARCHAR (30)   NULL,
    [Gwarant1Miejscowosc]                       NVARCHAR (150)  NULL,
    [Gwarant1NrVAT]                             VARCHAR (35)    NULL,
    [Gwarant2NrAkcyzowy]                        VARCHAR (13)    NULL,
    [Gwarant2Nazwa]                             NVARCHAR (546)  NULL,
    [Gwarant2Ulica]                             NVARCHAR (195)  NULL,
    [Gwarant2NrDomu]                            NVARCHAR (33)   NULL,
    [Gwarant2KodPocztowy]                       NVARCHAR (30)   NULL,
    [Gwarant2Miejscowosc]                       NVARCHAR (150)  NULL,
    [Gwarant2NrVAT]                             VARCHAR (35)    NULL,
    [TransportKodRodz]                          VARCHAR (2)     NOT NULL,
    [OrganizatorTranspNrVAT]                    VARCHAR (35)    NULL,
    [OrganizatorTranspNazwa]                    NVARCHAR (546)  NULL,
    [OrganizatorTranspUlica]                    NVARCHAR (195)  NULL,
    [OrganizatorTranspNrDomu]                   NVARCHAR (33)   NULL,
    [OrganizatorTranspKodPocztowy]              NVARCHAR (30)   NULL,
    [OrganizatorTranspMiejscowosc]              NVARCHAR (150)  NULL,
    [PierwszyPrzewoznikNrVAT]                   VARCHAR (35)    NULL,
    [PierwszyPrzewoznikNazwa]                   NVARCHAR (546)  NULL,
    [PierwszyPrzewoznikUlica]                   NVARCHAR (195)  NULL,
    [PierwszyPrzewoznikNrDomu]                  NVARCHAR (33)   NULL,
    [PierwszyPrzewoznikKodPocztowy]             NVARCHAR (30)   NULL,
    [PierwszyPrzewoznikMiejscowosc]             NVARCHAR (150)  NULL,
    [CzyPrzewoznikZmieniony]                    CHAR (1)        NOT NULL,
    [CzySkontrolowanoMiejsceWysylki]            CHAR (1)        NULL,
    [CzySkontrolowanoMiejsceDostawy]            CHAR (1)        NULL,
    [CzyPowiadomionoODostarczeniu]              CHAR (1)        NULL,
    [CzyOpozniony]                              CHAR (1)        NOT NULL,
    [CzyWyjasnieniaZgloszonePrzezWysylajacego]  CHAR (1)        NOT NULL,
    [CzyWyjasnieniaZgloszonePrzezOdbierajacego] CHAR (1)        NOT NULL,
    [CzyPrzemieszczeniePrzeterminowane]         CHAR (1)        NOT NULL,
    [NadrzednyARC]                              VARCHAR (21)    NULL,
    [DataOdrzuceniaLubOstrzezenia]              DATETIME2 (6)   NULL,
    [DataPodzialuPrzesylki]                     DATETIME2 (6)   NULL,
    [Id]                                        NUMERIC (38)    NULL,
    [NrSAD]                                     NVARCHAR (63)   NULL,
    [KodJednTransp]                             VARCHAR (2)     NULL,
    [OznJednTransp]                             NVARCHAR (105)  NULL,
    [OznaczeniePieczecHandl]                    NVARCHAR (105)  NULL,
    [InfPieczec]                                NVARCHAR (1050) NULL,
    [InformacjaPieczecKodJezyka]                VARCHAR (2)     NULL,
    [DodInf]                                    NVARCHAR (1050) NULL,
    [DodatkoweInformacjeKodJezyka]              VARCHAR (2)     NULL,
    [IdPozycjiTowarowej]                        FLOAT (53)      NULL,
    [KategoriaWyrobuAkcyzowego]                 VARCHAR (1)     NULL,
    [KodWyrAkc]                                 VARCHAR (4)     NULL,
    [KodCN]                                     VARCHAR (8)     NULL,
    [Wyrob_ilosc]                               NUMERIC (18, 3) NULL,
    [PozostalaIlosc]                            NUMERIC (18, 3) NULL,
    [IloscDodJednMiary]                         NUMERIC (18, 3) NULL,
    [IloscDodJednMiaryPoOdbiorze]               NUMERIC (18, 3) NULL,
    [MasaBrutto]                                NUMERIC (17, 2) NULL,
    [PozostalaWagaBrutto]                       NUMERIC (17, 2) NULL,
    [MasaNetto]                                 NUMERIC (17, 2) NULL,
    [PozostalaWagaNetto]                        NUMERIC (17, 2) NULL,
    [ZawartoscAlkoholu]                         NUMERIC (7, 2)  NULL,
    [StopienPlato]                              NUMERIC (7, 2)  NULL,
    [TypPaliwa]                                 VARCHAR (1)     NULL,
    [OlejeNiebarwioneINieoznaczane]             CHAR (1)        NULL,
    [IloscDodanychBiokomponentow]               NUMERIC (18, 3) NULL,
    [MaksymalnaCenaDetaliczna]                  NUMERIC (7, 2)  NULL,
    [ZnakiAkcyzy]                               NVARCHAR (1050) NULL,
    [ZnakAkcyzy]                                CHAR (1)        NULL,
    [MiejscePochodzenia]                        NVARCHAR (1050) NULL,
    [WielkoscProducenta]                        VARCHAR (15)    NULL,
    [Gestosc]                                   NUMERIC (7, 2)  NULL,
    [OpisHandlowy]                              NVARCHAR (1050) NULL,
    [MarkaWyrobow]                              NVARCHAR (1050) NULL,
    [KategoriaWyrobuWiniarskiego]               VARCHAR (1)     NULL,
    [KodStrefyUprawyWinorosli]                  VARCHAR (2)     NULL,
    [KrajTrzeciPochodzeniaWino]                 VARCHAR (2)     NULL,
    [DodInfWino]                                NVARCHAR (1050) NULL,
    [NiedoborLubNadwyzka]                       VARCHAR (1)     NULL,
    [IloscNiedoboruLubNadwyzki]                 NUMERIC (18, 3) NULL,
    [Wyrób_KwotaGwarancji]                      NUMERIC (38, 2) NULL,
    [Wyrób_PozostalaKwotaGwarancji]             NUMERIC (38, 2) NULL,
    [Wyrób_BrakujacaKwotaGwarancji]             NUMERIC (38, 2) NULL,
    [PotwProduktDostarczony]                    CHAR (1)        NULL,
    [BiokomponentyCzySpelWymJakosc]             CHAR (1)        NULL,
    [Status]                                    VARCHAR (1)     NULL,
    [TypZadania]                                VARCHAR (40)    NULL,
    [TerminPlatnosci]                           DATETIME2 (0)   NULL,
    [OdpowiedzialnaRola]                        NUMERIC (38)    NULL,
    [OdpowiedzialnyUzytkownik]                  NUMERIC (10)    NULL,
    [UrzadCelnyNrRef]                           VARCHAR (8)     NULL,
    [Tytul]                                     VARCHAR (250)   NULL,
    [PodmiotIdentyfikacja]                      NVARCHAR (48)   NULL,
    [PodmiotNazwa]                              NVARCHAR (546)  NULL,
    [PodmiotUlica]                              NVARCHAR (195)  NULL,
    [PodmiotNrDomu]                             NVARCHAR (66)   NULL,
    [PodmiotKodPocztowy]                        NVARCHAR (30)   NULL,
    [PodmiotMiejscowosc]                        NVARCHAR (150)  NULL,
    [KodPowoduOdrzuceniaCla]                    NUMERIC (1)     NULL,
    [NrRefDokumentu]                            VARCHAR (21)    NULL,
    [DecyzjaKontroliDomyslna]                   CHAR (1)        NULL,
    [DecyzjaKontroli]                           CHAR (1)        NULL,
    [Ilosc]                                     NUMERIC (38, 2) NULL,
    [CzyPrawidlowaOperacjaOSOZ]                 CHAR (1)        NULL,
    [DataUtworzenia]                            DATETIME2 (6)   NULL,
    [DataZmian]                                 DATETIME2 (6)   NULL,
    [ZmienionePrzez]                            VARCHAR (50)    NULL,
    [WersjaAudytu]                              NUMERIC (38)    NULL,
    [ARC]                                       VARCHAR (21)    NULL,
    [LRN]                                       NVARCHAR (66)   NULL,
    [NazwaMiejscaKontroli]                      NVARCHAR (546)  NULL,
    [CzyZadanieKontroli]                        CHAR (1)        NULL,
    [DataPrzeladunku]                           DATETIME2 (6)   NULL,
    [NrDok]                                     NVARCHAR (1050) NULL,
    [KrotkiOpis]                                NVARCHAR (1050) NULL,
    [KodCzynnosciWino]                          VARCHAR (2)     NULL,
    [KodRodzOpakowan]                           VARCHAR (2)     NULL,
    [LiczbaOpakowan]                            FLOAT (53)      NULL,
    [OznPieczecHandl]                           VARCHAR (35)    NULL,
    [InfPieczecHandl]                           NVARCHAR (1050) NULL
);

