CREATE TABLE [aimp2].[ICS_DSK_TOWAR_WNIOSKOWANE_UNIE] (
    [ID]               NUMERIC (19)    NOT NULL,
    [ICS_DSK_TOWAR_ID] NUMERIC (19)    NULL,
    [MRN]              NVARCHAR (18)   NULL,
    [NR_POZYCJI]       NUMERIC (5)     NULL,
    [STATUS]           NCHAR (4)       NULL,
    [UZASADNIENIE]     NVARCHAR (1024) NULL,
    [version]          INT             NOT NULL,
    CONSTRAINT [ICS_DSK_TOWAR_WNIOSKOWANE_UNIE$PK_ICS_DSK_TOWAR_WNIOSKOWANE_UNIE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

