CREATE TABLE [aimp2].[ICS_DSK_TOWAR] (
    [ID]                           NUMERIC (19)    NOT NULL,
    [ICS_DSK_ID]                   NUMERIC (19)    NOT NULL,
    [ILOSC_TOWARU]                 NUMERIC (16, 6) NULL,
    [JEDNOSTKA_MIARY]              NCHAR (3)       NULL,
    [KWOTA]                        NUMERIC (15, 2) NULL,
    [NR_POZYCJI]                   NUMERIC (5)     NULL,
    [NUMER_REFERENCYJNY_PRZESYLKI] NVARCHAR (35)   NULL,
    [STATUS_POZYCJI_DSK]           NVARCHAR (4)    NULL,
    [TERMIN]                       DATETIME2 (3)   NULL,
    [OPIS_NIEPRAWIDL]              NVARCHAR (1024) NULL,
    [ICS_ENS_ITEMS_ID]             NUMERIC (19)    NULL,
    [OF_ODBIORCA_ID]               NUMERIC (19)    NULL,
    [PG_ODBIORCA_ID]               NUMERIC (19)    NULL,
    [MASA_BRUTTO]                  NUMERIC (16, 6) NULL,
    [MASA_NETTO]                   NUMERIC (16, 6) NULL,
    [OPIS_TOWARU]                  NVARCHAR (1000) NULL,
    [UWAGI]                        NVARCHAR (260)  NULL,
    [REFERENCJE_DO_ZT]             BIT             NOT NULL,
    [WYNIK_KONTROLI]               NVARCHAR (60)   NULL,
    [PRZETERMINOWANY]              BIT             NOT NULL,
    [ZABEZPIECZONO]                TINYINT         NULL,
    [KOD_CUS]                      NVARCHAR (8)    NULL,
    [KOD_TOWAROWY]                 NVARCHAR (18)   NULL,
    [version]                      INT             NOT NULL,
    CONSTRAINT [ICS_DSK_TOWAR$PK_ICS_DSK_TOWAR] PRIMARY KEY CLUSTERED ([ID] ASC)
);

