CREATE TABLE [aimp2].[ICS_ZCP_ITEM_REQ_DOC] (
    [ID]                 NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]        NUMERIC (19)    NULL,
    [DOC_CODE]           NVARCHAR (4)    NULL,
    [DOC_NUMBER]         NVARCHAR (35)   NULL,
    [DOC_NOTES]          NVARCHAR (35)   NULL,
    [ITEM_QUANTITY]      NUMERIC (16, 6) NULL,
    [QUANTITY_UNIT]      NVARCHAR (3)    NULL,
    [AGRIM_RESULT]       NVARCHAR (3)    NULL,
    [AGRIM_DISCREP_INFO] NVARCHAR (3072) NULL,
    [POZ_ID]             NUMERIC (5)     NULL,
    [INSTITUTION_NAME]   NVARCHAR (70)   NULL,
    [EXPIRATION_DATE]    DATETIME2 (3)   NULL,
    [ZCP_ACF]            NTEXT           NULL,
    [DOC_IDENTITY]       NVARCHAR (35)   NULL,
    [version]            INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_REQ_DOC$PK_ICS_ZCP_ITEM_REQ_DOC] PRIMARY KEY CLUSTERED ([ID] ASC)
);

