CREATE TABLE [aimp2].[ICS_ZCP_ADDITIONAL_INFO] (
    [ID]          NUMERIC (19)   NOT NULL,
    [ZCP_ID]      NUMERIC (19)   NULL,
    [CODE]        NVARCHAR (5)   NULL,
    [DESCRIPTION] NVARCHAR (512) NULL,
    [version]     INT            NOT NULL,
    CONSTRAINT [ICS_ZCP_ADDITIONAL_INFO$PK_ICS_ZCP_ADDITIONAL_INFO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

