CREATE TABLE [aimp2].[ICS_ZCP_POD_ITEM] (
    [ID]          NUMERIC (19) NOT NULL,
    [ZCP_POD_ID]  NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19) NOT NULL,
    [version]     INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_POD_ITEM$ICS_ZCP_PO_18455785821] PRIMARY KEY CLUSTERED ([ID] ASC)
);

