CREATE TABLE [aimp2].[ICS_ZCP_DV1_INCREM_DEDUCTION] (
    [ID]               NUMERIC (19)    NOT NULL,
    [ZCP_ID]           NUMERIC (19)    NULL,
    [ZCP_ITEM_ID]      NUMERIC (19)    NULL,
    [INCREM_DEDUCTION] NVARCHAR (3)    NULL,
    [AMOUNT]           NUMERIC (16, 2) NULL,
    [version]          INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_DV1_INCREM_DEDUCTION$PK_ICS_ZCP_DV1_INCREM_DEDUCTION] PRIMARY KEY CLUSTERED ([ID] ASC)
);

