CREATE TABLE [aimp2].[ICS_PWD_PROCEDURE_DETAIL] (
    [procedure_id] NUMERIC (19) NOT NULL,
    [code]         NVARCHAR (3) NOT NULL,
    CONSTRAINT [ICS_PWD_PROCEDURE_DETAIL$UQ_ICS_PWD_PROCEDURE_DETAIL] UNIQUE NONCLUSTERED ([procedure_id] ASC, [code] ASC)
);

