CREATE TABLE [aimp2].[ICS_ZCP_BUSINESS_ENTITY_AI] (
    [ID]                     NUMERIC (19) NOT NULL,
    [ZCP_BUSINESS_ENTITY_ID] NUMERIC (19) NULL,
    [CODE]                   NVARCHAR (5) NOT NULL,
    [version]                INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_BUSINESS_ENTITY_ADDITIONAL_INFO$ICS_ZCP_BU_10330516851] PRIMARY KEY CLUSTERED ([ID] ASC)
);

