CREATE TABLE [aimp2].[ICS_CHANG] (
    [ID]      NUMERIC (19)   NOT NULL,
    [AFTER]   NVARCHAR (255) NULL,
    [BEFORE]  NVARCHAR (255) NULL,
    [ITEM]    NVARCHAR (255) NULL,
    [OPER_ID] NUMERIC (19)   NULL,
    CONSTRAINT [ICS_CHANG$ICS_CHANG_3513372851] PRIMARY KEY CLUSTERED ([ID] ASC)
);

