CREATE TABLE [aimp2].[ICS_ZCP_TRANSPORT_DOCUMENT] (
    [ID]      NUMERIC (19)  NOT NULL,
    [ZCP_ID]  NUMERIC (19)  NULL,
    [CODE]    NVARCHAR (4)  NULL,
    [DOC_NO]  NVARCHAR (35) NULL,
    [version] INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_TRANSPORT_DOCUMENT$PK_ICS_ZCP_TRANSPORT_DOCUMENT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

