CREATE TABLE [aimp2].[ICS_DSK_ZAMK_CELNE] (
    [ID]         NUMERIC (19)  NOT NULL,
    [ICS_DSK_ID] NUMERIC (19)  NULL,
    [ILOSC]      NUMERIC (4)   NULL,
    [RODZAJ]     NVARCHAR (35) NULL,
    [version]    INT           NOT NULL,
    CONSTRAINT [ICS_DSK_ZAMK_CELNE$PK_ICS_DSK_ZAMK_CELNE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

