CREATE TABLE [aimp2].[ICS_DSK_OPERACJA] (
    [ID]         NUMERIC (19)    NOT NULL,
    [ICS_DSK_ID] NUMERIC (19)    NOT NULL,
    [ADNOTACJA]  NVARCHAR (1024) NULL,
    [DATA]       DATETIME2 (3)   NULL,
    [NAZWA]      NVARCHAR (4)    NULL,
    [UWAGI]      NVARCHAR (1024) NULL,
    [WYKONAL]    NVARCHAR (40)   NULL,
    [version]    INT             NOT NULL,
    CONSTRAINT [ICS_DSK_OPERACJA$PK_ICS_DSK_OPERACJA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

