CREATE TABLE [aimp2].[ICS_ZCP_ITEM_PROCEDURE_DETAILS] (
    [ID]          NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19) NULL,
    [CODE]        NVARCHAR (3) NOT NULL,
    [ZCP_ACF]     NTEXT        NULL,
    [version]     INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_PROCEDURE_DETAILS$ICS_ZCP_IT_17725303171] PRIMARY KEY CLUSTERED ([ID] ASC)
);

