CREATE TABLE [aimp2].[ICS_MESS_KANAL] (
    [ID]      NUMERIC (19)  NOT NULL,
    [MESS_ID] NUMERIC (19)  NOT NULL,
    [KTYP]    NVARCHAR (2)  NOT NULL,
    [KCHOICE] NVARCHAR (4)  NOT NULL,
    [VAL]     NVARCHAR (70) NOT NULL,
    [VAL_ADD] NVARCHAR (70) NULL,
    CONSTRAINT [ICS_MESS_KANAL$ICS_MESS_KANAL_10553397931] PRIMARY KEY CLUSTERED ([ID] ASC)
);

