CREATE TABLE [aimp2].[ICS_DIRT_CONTROL_METHOD] (
    [directive_id] NUMERIC (19)  NOT NULL,
    [code]         NVARCHAR (10) NOT NULL,
    CONSTRAINT [ICS_DIRT_CONTROL_METHOD$PK_ICS_DIRT_CONTROL_METHOD] PRIMARY KEY CLUSTERED ([directive_id] ASC, [code] ASC)
);

