CREATE TABLE [aimp2].[ICS_ZCP_ITEM_ENTITY_ICD] (
    [ID]          NUMERIC (19)  NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19)  NULL,
    [ENTITY_ID]   NVARCHAR (17) NOT NULL,
    [ENTITY_ROLE] NVARCHAR (3)  NOT NULL,
    [version]     INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_ENTITY_IN_CHAIN_DELIVERY$ICS_ZCP_IT_19005307731] PRIMARY KEY CLUSTERED ([ID] ASC)
);

