CREATE TABLE [aimp2].[ICS_ZCP_ENTITY_ICD] (
    [ID]          NUMERIC (19)  NOT NULL,
    [ZCP_ID]      NUMERIC (19)  NULL,
    [ENTITY_ROLE] NVARCHAR (3)  NOT NULL,
    [ENTITY_ID]   NVARCHAR (17) NOT NULL,
    [ZCP_ACF]     NTEXT         NULL,
    [version]     INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_ENTITY_IN_CHAIN_DELIVERY$ICS_ZCP_EN_11200039901] PRIMARY KEY CLUSTERED ([ID] ASC)
);

