CREATE TABLE [aimp2].[ICS_ZCP_ITEM_TAX_IDENTITY] (
    [ID]          NUMERIC (19)  NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19)  NULL,
    [VAT_NUMBER]  NVARCHAR (17) NOT NULL,
    [TAX_ROLE]    NVARCHAR (3)  NOT NULL,
    [version]     INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_TAX_IDENTITY$ICS_ZCP_IT_15965296901] PRIMARY KEY CLUSTERED ([ID] ASC)
);

