CREATE TABLE [aimp2].[ICS_ZCP_ITEM_ARR_DATA] (
    [ID]                         NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]                NUMERIC (19)    NULL,
    [CHK_DATE]                   DATETIME2 (3)   NULL,
    [REQUEST_ID]                 NVARCHAR (35)   NULL,
    [ADD_QUANTITY]               NUMERIC (16, 6) NULL,
    [QUANTITY_SUPPL_UNIT]        NVARCHAR (3)    NULL,
    [PERMISSION_NO]              NVARCHAR (50)   NULL,
    [DISCREPANCY_INFO]           NVARCHAR (1024) NULL,
    [AGRIM_VALID_TO]             DATETIME2 (3)   NULL,
    [ZCP_ITEM_TARIC_QUANTITY_ID] NUMERIC (19)    NULL,
    [version]                    INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_ARR_DATA$PK_ICS_ZCP_ITEM_ARR_DATA] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [ICS_ZCP_ITEM_ARR_DATA$UQ_ICS_ZCP_ITEM_ARR_DATA_REQUEST_ID] UNIQUE NONCLUSTERED ([REQUEST_ID] ASC)
);

