CREATE TABLE [aimp2].[ICS_ZCP_NAT_ADD_CODES] (
    [ID]            NUMERIC (19) NOT NULL,
    [ZCP_ITEM_ID]   NUMERIC (19) NULL,
    [NATIONAL_CODE] NVARCHAR (4) NULL,
    [version]       INT          NOT NULL,
    CONSTRAINT [ICS_ZCP_NAT_ADD_CODES$PK_ICS_ZCP_NAT_ADD_CODES] PRIMARY KEY CLUSTERED ([ID] ASC)
);

