CREATE TABLE [aimp2].[ICS_DSK_TOWAR_DOKUMENT_WYMAG] (
    [ID]               NUMERIC (19)  NOT NULL,
    [ICS_DSK_TOWAR_ID] NUMERIC (19)  NULL,
    [KOD]              NCHAR (4)     NULL,
    [NUMER]            NVARCHAR (35) NULL,
    [UWAGI]            NVARCHAR (35) NULL,
    [version]          INT           NOT NULL,
    CONSTRAINT [ICS_DSK_TOWAR_DOKUMENT_WYMAG$PK_ICS_DSK_TOWAR_DOKUMENT_WYMAG] PRIMARY KEY CLUSTERED ([ID] ASC)
);

