CREATE TABLE [aimp2].[ICS_ZCP_CONTRACT] (
    [ID]         NUMERIC (19)  NOT NULL,
    [ZCP_ID]     NUMERIC (19)  NULL,
    [CONTR_DATE] DATETIME2 (3) NULL,
    [CONTR_NO]   NVARCHAR (35) NULL,
    [version]    INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_CONTRACT$ICS_ZCP_CONTRACT] PRIMARY KEY CLUSTERED ([ID] ASC)
);

