CREATE TABLE [aimp2].[ICS_ZCP_TAX_IDENTITY] (
    [ID]         NUMERIC (19)  NOT NULL,
    [ZCP_ID]     NUMERIC (19)  NULL,
    [VAT_NUMBER] NVARCHAR (17) NOT NULL,
    [TAX_ROLE]   NVARCHAR (3)  NOT NULL,
    [ZCP_ACF]    NTEXT         NULL,
    [version]    INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_TAX_IDENTITY$ICS_ZCP_TA_11485280941] PRIMARY KEY CLUSTERED ([ID] ASC)
);

