CREATE TABLE [aimp2].[ICS_ZCP_ITEM_ADD_INFO] (
    [ID]          NUMERIC (19)   NOT NULL,
    [ZCP_ITEM_ID] NUMERIC (19)   NULL,
    [CODE]        NVARCHAR (5)   NULL,
    [DESCRIPTION] NVARCHAR (512) NULL,
    [ZCP_ACF]     NTEXT          NULL,
    [version]     INT            NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_ADD_INFO$PK_ICS_ZCP_ITEM_ADD_INFO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

