CREATE TABLE [aimp2].[ICS_ZCP] (
    [ID]                            NUMERIC (19)    NOT NULL,
    [LEGAL_ANNOTATIONS]             NVARCHAR (2000) NULL,
    [CALC_DATE]                     DATETIME2 (3)   NULL,
    [REJECT_DATE]                   DATETIME2 (3)   NULL,
    [REGI_DATE]                     DATETIME2 (3)   NULL,
    [CANCEL_DATE]                   DATETIME2 (3)   NULL,
    [PREV_DOC_NR]                   NVARCHAR (25)   NULL,
    [NUMB_FORMS]                    NUMERIC (5)     NULL,
    [TOTAL_ITEM_VALUE]              NUMERIC (16, 2) NULL,
    [ADDITIONAL_DECL_TYPE]          NVARCHAR (5)    NULL,
    [CONTAINERS]                    BIT             NOT NULL,
    [COUNTRY_OF_DESTINATION]        NVARCHAR (2)    NULL,
    [COUNTRY_OF_DESTINATION_REGION] NVARCHAR (9)    NULL,
    [COUNTRY_OF_EXPORT]             NVARCHAR (2)    NULL,
    [NUMBER_OF_PACKAGES]            NUMERIC (8)     NULL,
    [NO_OF_ITEMS]                   NUMERIC (5)     NULL,
    [GROSS_MASS]                    NUMERIC (16, 6) NULL,
    [NO_OF_PERMISSION]              NVARCHAR (35)   NULL,
    [ZCP_SYSTEM_NUMBER]             NVARCHAR (35)   NULL,
    [DEFERRED_PAYMENT]              NVARCHAR (35)   NULL,
    [ELECTR_SIGNATURE]              BIT             NOT NULL,
    [ZCP_STATE]                     NVARCHAR (4)    NULL,
    [KIND_OF_DECLARATION]           NVARCHAR (3)    NULL,
    [PRESENTATION_GOODS_CO]         NVARCHAR (8)    NULL,
    [DECLARATION_CO]                NVARCHAR (8)    NULL,
    [PRESENTATION_GOODS]            BIT             NOT NULL,
    [ICS_GAN_CUST_DATA_ID]          NUMERIC (19)    NULL,
    [DPZ_POD]                       DATE            NULL,
    [DPZ_POSTAL]                    BIT             NOT NULL,
    [DPZ_PARCEL_NUM]                NVARCHAR (35)   NULL,
    [ACCEPTANCE_DATE]               DATETIME2 (3)   NULL,
    [DPZ_CONS_RELEASE_DATE]         DATE            NULL,
    [REGO_DATE]                     DATE            NULL,
    [DPZ_REGO_MANNER]               NVARCHAR (1024) NULL,
    [EMCS_STATUS]                   NVARCHAR (8)    NULL,
    [ZCP_DECL_TYPE]                 NVARCHAR (3)    NULL,
    [ACCEPTANCE_DATE_TIME]          DATETIME2 (3)   NULL,
    [DPZ_RECEIVABLE_PROTECTION]     NVARCHAR (1)    NULL,
    [registry_num]                  NVARCHAR (10)   NULL,
    [DPZ_CONTROL_RESULT]            NVARCHAR (35)   NULL,
    [ZCP_UZP_CUT_OFF_DATE]          DATETIME2 (3)   NULL,
    [ZCP_VAT7]                      TINYINT         NULL,
    [rectification_body]            NTEXT           NULL,
    [UZP_ID]                        NUMERIC (19)    NULL,
    [tqsVersion]                    TINYINT         NOT NULL,
    [tqsSent]                       BIT             NOT NULL,
    [DPZ_RELEASE_DATE]              DATE            NULL,
    [DPZ_RECEIVABLES]               NVARCHAR (1)    NULL,
    [ZCP_DOC_SIGNER_ID]             NUMERIC (19)    NULL,
    [PARCEL_REFERENCE_NUMBER]       NVARCHAR (35)   NULL,
    [CURRENCY_CODE]                 NVARCHAR (3)    NULL,
    [ENTRY_CO]                      NVARCHAR (8)    NULL,
    [CONTROL_CO]                    NVARCHAR (8)    NULL,
    [ZCP_ACF]                       NTEXT           NULL,
    [PRESENT_DATE]                  DATETIME2 (3)   NULL,
    [tqsSent2]                      BIT             NOT NULL,
    [releasedInPresentationCo]      BIT             NOT NULL,
    [ZCP_VAT7_CLOSED_DATE]          DATETIME2 (3)   NULL,
    [ZCP_VAT7_REF_DATE]             DATETIME2 (3)   NULL,
    [ZCP_VAT7_DEADLINE_DATE]        DATETIME2 (3)   NULL,
    [ZCP_UZP_PROC]                  BIT             NOT NULL,
    [ZCP_VAT_BL_PROC]               BIT             NOT NULL,
    [EMAIL_PERMIT_HOLDER_BONDED_WH] NVARCHAR (35)   NULL,
    [EMAIL_WAREHOUSE_TEMP_STORAGE]  NVARCHAR (35)   NULL,
    [PDR_PARM_SUBM_TIME_SUPP_DECL]  NUMERIC (4)     NULL,
    [OSOZ_HAND_GUAR_SING]           BIT             NOT NULL,
    [ISZTAR_RECEIVED]               BIT             NOT NULL,
    [ISZTAR_CALLED]                 BIT             NOT NULL,
    [CALCD_RECEIVED]                BIT             NOT NULL,
    [CALCD_CALLED]                  BIT             NOT NULL,
    CONSTRAINT [ICS_ZCP$PK_ICS_ZCP] PRIMARY KEY CLUSTERED ([ID] ASC)
);

