CREATE TABLE [aimp2].[ICS_ZCP_ITEM_POSTAL_VALUE] (
    [ID]            NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]   NUMERIC (19)    NOT NULL,
    [CURRENCY_CODE] NVARCHAR (3)    NOT NULL,
    [VALUE]         NUMERIC (16, 2) NOT NULL,
    [version]       INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_POSTAL_VALUE$ICS_ZCP_IT_19680070111] PRIMARY KEY CLUSTERED ([ID] ASC)
);

