CREATE TABLE [aimp2].[ICS_ZCP_ITEM_QUOTA_GRANTED] (
    [ID]                    NUMERIC (19)    NOT NULL,
    [ZCP_ITEM_ID]           NUMERIC (19)    NULL,
    [ISSUED_QUANTITY_UNIT]  NVARCHAR (3)    NULL,
    [QUALIFIER_OF_UNIT]     NVARCHAR (1)    NULL,
    [QUOTA_NO]              NVARCHAR (17)   NULL,
    [ISSUED_QUOTA_QUANTITY] NUMERIC (15, 3) NULL,
    [POS_ID]                NUMERIC (1)     NULL,
    [version]               INT             NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_QUOTA_GRANTED$PK_ICS_ZCP_ITEM_QUOTA_GRANTED] PRIMARY KEY CLUSTERED ([ID] ASC)
);

