CREATE TABLE [aimp2].[ICS_OTHER_NATURAL_PERSON] (
    [ID]               NUMERIC (19)  NOT NULL,
    [IDENTIFIER]       NVARCHAR (18) NULL,
    [NAME]             NVARCHAR (30) NOT NULL,
    [SURNAME]          NVARCHAR (40) NOT NULL,
    [ID_NO]            NVARCHAR (30) NULL,
    [PESEL]            NVARCHAR (11) NULL,
    [OTHER_ADDRESS_ID] NUMERIC (19)  NULL,
    [version]          INT           NOT NULL,
    CONSTRAINT [ICS_OTHER_NATURAL_PERSON$ICS_OTHER__18775786961] PRIMARY KEY CLUSTERED ([ID] ASC)
);

