CREATE TABLE [aimp2].[ICS_ZCP_PERMITS_HOLDER] (
    [ID]          NUMERIC (19)  NOT NULL,
    [ZCP_ID]      NUMERIC (19)  NOT NULL,
    [PERMIT_TYPE] NVARCHAR (4)  NOT NULL,
    [IDENTIFY]    NVARCHAR (17) NOT NULL,
    [version]     INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_PERMITS_HOLDER$ICS_ZCP_PE_11561961381] PRIMARY KEY CLUSTERED ([ID] ASC)
);

