CREATE TABLE [aimp2].[ICS_ZCP_ITEM_CONTAINER] (
    [ID]               NUMERIC (19)  NOT NULL,
    [ZCP_ITEM_ID]      NUMERIC (19)  NULL,
    [CONTAINER_NUMBER] NVARCHAR (17) NULL,
    [ZCP_ACF]          NTEXT         NULL,
    [version]          INT           NOT NULL,
    CONSTRAINT [ICS_ZCP_ITEM_CONTAINER$PK_ICS_ZCP_ITEM_CONTAINER] PRIMARY KEY CLUSTERED ([ID] ASC)
);

