CREATE TABLE [aimp2].[ICS_DSK_WSP_INFORMACJA_DOD] (
    [ID]               NUMERIC (19)   NOT NULL,
    [ICS_DSK]          NUMERIC (19)   NULL,
    [ICS_DSK_TOWAR_ID] NUMERIC (19)   NULL,
    [KOD]              NCHAR (5)      NULL,
    [OPIS]             NVARCHAR (512) NULL,
    [version]          INT            NOT NULL,
    CONSTRAINT [ICS_DSK_WSP_INFORMACJA_DOD$PK_ICS_DSK_WSP_INFORMACJA_DOD] PRIMARY KEY CLUSTERED ([ID] ASC)
);

