CREATE TABLE [aimp2].[ICS_GAN_ZCP_CUST_DATA_DETL] (
    [ID]                   NUMERIC (19) NOT NULL,
    [GAN_ZCP_CUST_DATA_ID] NUMERIC (19) NOT NULL,
    [POSITION_NO]          NUMERIC (5)  NOT NULL,
    CONSTRAINT [ICS_GAN_ZCP_CUST_DATA_DETL$ICS_GAN_ZC_6740984111] PRIMARY KEY CLUSTERED ([ID] ASC)
);

