CREATE TABLE [aimp2].[ICS_DPZ_DECISION] (
    [ID]          NUMERIC (19)    NOT NULL,
    [DEC_DATE]    DATETIME2 (3)   NOT NULL,
    [DECL_ID]     NUMERIC (19)    NOT NULL,
    [MRN]         NVARCHAR (18)   NOT NULL,
    [DEC_NO]      NVARCHAR (40)   NOT NULL,
    [POSITIONS]   NVARCHAR (300)  NOT NULL,
    [DESCRIPTION] NVARCHAR (1000) NOT NULL,
    [DTYPE]       NVARCHAR (4)    NOT NULL,
    [version]     INT             NOT NULL,
    CONSTRAINT [ICS_DPZ_DECISION$ICS_DPZ_DE_12181003491] PRIMARY KEY CLUSTERED ([ID] ASC)
);

