



CREATE PROCEDURE [emcs2].[TruncateAllFromEMCS2]
AS
BEGIN
	SET NOCOUNT ON;
		
	TRUNCATE TABLE emcs2.AIS_VERIFICATIONS;
	TRUNCATE TABLE emcs2.AIS_VERIFICATIONS_MVMT;
	TRUNCATE TABLE emcs2.DICTIONARIES;
	TRUNCATE TABLE emcs2.DICTIONARY_VALUES;
	TRUNCATE TABLE emcs2.ECS_DECL_VERIFY_RESULTS;
	TRUNCATE TABLE emcs2.ECS_DECLARATION_MVMTS;
	TRUNCATE TABLE emcs2.ECS_DECLARATIONS;
	TRUNCATE TABLE emcs2.EMCS_ACO;
	TRUNCATE TABLE emcs2.EMCS_ACO_MESSAGE_RELATIONS;
	TRUNCATE TABLE emcs2.EMCS_ACO_MESSAGES;
	TRUNCATE TABLE emcs2.EMCS_ACO_MOVEMENTS;
	TRUNCATE TABLE emcs2.EMCS_ACO_OUTER_MESSAGES;
	TRUNCATE TABLE emcs2.EMCS_ACO_PROCESS_INSTANCES;
	TRUNCATE TABLE emcs2.EMCS_ACO_READERS;
	TRUNCATE TABLE emcs2.EMCS_DOWN_DOWNSTREAM_MVMTS;
	TRUNCATE TABLE emcs2.EMCS_DOWN_MESSAGES;
	TRUNCATE TABLE emcs2.EMCS_DOWN_MOVEMENTS;
	TRUNCATE TABLE emcs2.EMCS_DOWN_MVMT_PROD;
	TRUNCATE TABLE emcs2.EMCS_EXCISE_RATES;
	TRUNCATE TABLE emcs2.EMCS_FOLLOW_UP_MESSAGES;
	TRUNCATE TABLE emcs2.EMCS_FUEL_EXCISE_RATES;
	TRUNCATE TABLE emcs2.EMCS_HELPDESK;
	TRUNCATE TABLE emcs2.EMCS_PROCESS_COMM;
	TRUNCATE TABLE emcs2.EMCS_PROCESS_INSTANCES;
	TRUNCATE TABLE emcs2.EMCS_PROCESS_STATE_INST;
	TRUNCATE TABLE emcs2.EMCS_TIMER_TYPES;
	TRUNCATE TABLE emcs2.EMCS_TIMERS;
	TRUNCATE TABLE emcs2.EMCS_UNAVAILABILITIES;
	TRUNCATE TABLE emcs2.EMCS_USER_TASK_TYPES;
	TRUNCATE TABLE emcs2.EMCS_USER_TASKS;
	TRUNCATE TABLE emcs2.EMCS_USER_TASKS_JN;
	TRUNCATE TABLE emcs2.EMCS_USER_TASKS_SAD_DOCS;
	TRUNCATE TABLE emcs2.EXCISE_PRODUCTS;
	TRUNCATE TABLE emcs2.MESSAGE_TYPES;
	TRUNCATE TABLE emcs2.[MESSAGES];
	TRUNCATE TABLE emcs2.MOVEMENTS;
	TRUNCATE TABLE emcs2.MVMT_CERTIFICATES;
	TRUNCATE TABLE emcs2.MVMT_CONSIGNEE_HISTORY;
	TRUNCATE TABLE emcs2.MVMT_DOWNSTREAM_MOVEMENTS;
	TRUNCATE TABLE emcs2.MVMT_INTERESTED_OFFICES;
	TRUNCATE TABLE emcs2.MVMT_PACKAGES;
	TRUNCATE TABLE emcs2.MVMT_PRODUCTS;
	TRUNCATE TABLE emcs2.MVMT_SAD_DOCUMENTS;
	TRUNCATE TABLE emcs2.MVMT_TRANSPORT_DETAILS;
	TRUNCATE TABLE emcs2.MVMT_WINE_OPERATION_CODES;
	TRUNCATE TABLE emcs2.PACKAGING_CODES;
	TRUNCATE TABLE emcs2.REF_SD2_MIEJSCA_ODBIORU;
	TRUNCATE TABLE emcs2.REF_SD2_PODMIOTY;
	TRUNCATE TABLE emcs2.REF_SD2_PRZEDSTAWICIELE;
	TRUNCATE TABLE emcs2.REF_SD2_UBYTKI_TRANS;
	TRUNCATE TABLE emcs2.REF_SD2_UBYTKI_TRANS_KODY_CN;
	TRUNCATE TABLE emcs2.REF_SD2_UBYTKI_TRANS_OPAK;
	TRUNCATE TABLE emcs2.REF_SD2_UBYTKI_TRANS_SRODKI;
	TRUNCATE TABLE emcs2.REF_SD2_WLASCICIELE;
	TRUNCATE TABLE emcs2.REF_SD2_WYROBY;
	TRUNCATE TABLE emcs2.REF_SD2_ZABEZPIECZENIA;
	TRUNCATE TABLE emcs2.REQUEST_MESSAGES;
	TRUNCATE TABLE emcs2.TFILE;		

	TRUNCATE TABLE emcs2.MVMT_QUATER_SHORTAGES;
	TRUNCATE TABLE emcs2.AR_DOKUMENT;
	TRUNCATE TABLE emcs2.AR_KONTROLA;
	TRUNCATE TABLE emcs2.AR_KONTROLA_PODSUMOWANIE;
	TRUNCATE TABLE emcs2.AR_KONTROLA_POZYCJE;
	TRUNCATE TABLE emcs2.AR_METODY_KONTROLI;
	TRUNCATE TABLE emcs2.AR_ZESPOL_KONTROLI;	

	END