CREATE TABLE [int].[INTRASTAT_Towar] (
    [IdDeklWynikowej]             VARCHAR (30)  NOT NULL,
    [IdPozycji]                   SMALLINT      NOT NULL,
    [Status]                      CHAR (1)      NULL,
    [Komentarz]                   VARCHAR (255) NULL,
    [OpisTowaru]                  VARCHAR (255) NULL,
    [KrajPrzeznaczeniaWysylki]    CHAR (2)      NULL,
    [KrajPrzeznaczeniaWysylkiPid] INT           NULL,
    [WarunkiDostawy]              CHAR (3)      NULL,
    [WarunkiDostawyPid]           INT           NULL,
    [RodzajTransakcji]            CHAR (2)      NULL,
    [RodzajTransakcjiPid]         INT           NULL,
    [RodzajTransportu]            CHAR (2)      NULL,
    [RodzajTransportuPid]         INT           NULL,
    [KodTowarowy]                 VARCHAR (8)   NULL,
    [KodTowarowyPid]              INT           NULL,
    [KrajPochodzenia]             CHAR (2)      NULL,
    [KrajPochodzeniaPid]          INT           NULL,
    [MasaNetto]                   DECIMAL (11)  NULL,
    [IloscUjm]                    DECIMAL (11)  NULL,
    [WartoscFaktury]              DECIMAL (15)  NULL,
    [WartoscStatystyczna]         DECIMAL (15)  NULL,
    CONSTRAINT [PK_INTRASTAT_Towar] PRIMARY KEY CLUSTERED ([IdDeklWynikowej] ASC, [IdPozycji] ASC) ON [FG_INT],
    CONSTRAINT [FK_INTRASTAT_KrajPochodzeniaPid] FOREIGN KEY ([KrajPochodzeniaPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_INTRASTAT_RodzajTransakcjiPid] FOREIGN KEY ([RodzajTransakcjiPid]) REFERENCES [pdr].[s004] ([s004_id]),
    CONSTRAINT [FK_INTRASTAT_RodzajTransportuPid] FOREIGN KEY ([RodzajTransportuPid]) REFERENCES [pdr].[s005] ([s005_id]),
    CONSTRAINT [FK_INTRASTAT_Towar_KrajPrzeznaczeniaWysylkiPid] FOREIGN KEY ([KrajPrzeznaczeniaWysylkiPid]) REFERENCES [pdr].[s007] ([s007_id]),
    CONSTRAINT [FK_INTRASTAT_Towar_WarunkiDostawyPid] FOREIGN KEY ([WarunkiDostawyPid]) REFERENCES [pdr].[s002] ([s002_id])
);

