CREATE TABLE [zef2].[KPCLASSIFICATIONATTRIBUTETABLE] (
    [ATTRIBUTEID]                      NVARCHAR (10)  NULL,
    [NAME]                             NVARCHAR (256) NULL,
    [BLOCKED]                          INT            NULL,
    [TYPE]                             INT            NULL,
    [SUBTYPE]                          INT            NULL,
    [CLASSIFICATIONATTRIBUTEPARENT_FK] BIGINT         NULL,
    [REQUIREDINCLASSIFICATION_PROGRAM] INT            NULL,
    [REQUIREDINCLASSIFICATION_PROJECT] INT            NULL,
    [DEFAULTEMPLOYMENTGROUP_FK]        BIGINT         NULL,
    [ECONGROUPGENERAL_FK]              BIGINT         NULL,
    [VISIBLEINDIMATTRIBUTEVIEW]        INT            NULL,
    [DEFAULTBGTTYPE_FK]                BIGINT         NULL,
    [MODIFIEDDATETIME]                 DATETIME       NULL,
    [MODIFIEDBY]                       NVARCHAR (8)   NULL,
    [MODIFIEDTRANSACTIONID]            BIGINT         NULL,
    [CREATEDDATETIME]                  DATETIME       NULL,
    [CREATEDBY]                        NVARCHAR (8)   NULL,
    [CREATEDTRANSACTIONID]             BIGINT         NULL,
    [RECVERSION]                       INT            NULL,
    [PARTITION]                        BIGINT         NULL,
    [RECID]                            BIGINT         NOT NULL,
    [REQUIREDEMPLGROUPFORLIMITS]       INT            NULL,
    [NATIVESUBSECTION_IC]              INT            NULL,
    [NATIVESUBSECTION_IS]              INT            NULL,
    [NATIVESUBSECTION_UKS]             INT            NULL,
    [operacja]                         NVARCHAR (1)   NULL,
    CONSTRAINT [I_103071RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

