CREATE TABLE [zef2].[KPFINSTATEMENTTABLE] (
    [OPERATIONDATE]                 DATETIME       NULL,
    [FINSTATEMENTID]                NVARCHAR (30)  NULL,
    [DESCRIPTION]                   NVARCHAR (60)  NULL,
    [VOUCHER]                       NVARCHAR (30)  NULL,
    [POSTED]                        INT            NULL,
    [FINSTATEMENTTYPE]              INT            NULL,
    [DISPOSERNUM]                   NVARCHAR (10)  NULL,
    [FINSTATEMENTSEQID]             NVARCHAR (15)  NULL,
    [REFFINANCIALOPERATIONID]       NVARCHAR (20)  NULL,
    [VOUCHERSEQID]                  NVARCHAR (15)  NULL,
    [OFFSETPOSTINGPROFILE]          NVARCHAR (10)  NULL,
    [SUBUNITID]                     NVARCHAR (10)  NULL,
    [NOTES]                         NVARCHAR (MAX) NULL,
    [SUMMARY]                       INT            NULL,
    [XMLSUBDOCUMENT]                INT            NULL,
    [VERSIONONDATE]                 INT            NULL,
    [FINSTATEMENTDEF_FK]            BIGINT         NULL,
    [ORGANIZATIONUNIT_FK]           BIGINT         NULL,
    [STATUS]                        NVARCHAR (20)  NULL,
    [STATUSNAMEID]                  NVARCHAR (10)  NULL,
    [FINSTATEMENTTABLEPARENT_FK]    BIGINT         NULL,
    [ISAGGREGATE]                   INT            NULL,
    [SENTTOPARENTUNIT]              INT            NULL,
    [APPROVED]                      INT            NULL,
    [AGGRFINSTATEMENTIDPATH]        NVARCHAR (255) NULL,
    [PART]                          INT            NULL,
    [ISGENERATED]                   INT            NULL,
    [LEVEL_]                        INT            NULL,
    [AGGRLEVEL]                     INT            NULL,
    [RECIPIENT]                     NVARCHAR (100) NULL,
    [RECEIVED]                      INT            NULL,
    [CANCELLED]                     INT            NULL,
    [FINSTATEMENTTYPEDEF_FK]        BIGINT         NULL,
    [EXPLANATION]                   NVARCHAR (100) NULL,
    [MODIFIEDDATETIME]              DATETIME       NULL,
    [MODIFIEDBY]                    NVARCHAR (8)   NULL,
    [MODIFIEDTRANSACTIONID]         BIGINT         NULL,
    [CREATEDDATETIME]               DATETIME       NULL,
    [CREATEDBY]                     NVARCHAR (8)   NULL,
    [CREATEDTRANSACTIONID]          BIGINT         NULL,
    [RECVERSION]                    INT            NULL,
    [PARTITION]                     BIGINT         NULL,
    [RECID]                         BIGINT         NOT NULL,
    [FINSTATEMENTTABLECANCELLED_FK] BIGINT         NULL,
    [SENDDATE]                      DATETIME       NULL,
    [GENERATEDDATETIME]             DATETIME       NULL,
    [GENERATEDDATETIMETZID]         INT            NULL,
    [POSTEDDATETIME]                DATETIME       NULL,
    [POSTEDDATETIMETZID]            INT            NULL,
    [REVERSED]                      INT            NULL,
    [REVERSEDDATETIME]              DATETIME       NULL,
    [REVERSEDDATETIMETZID]          INT            NULL,
    [REVERSEDBY]                    NVARCHAR (10)  NULL,
    [VOUCHERREVERSE]                NVARCHAR (30)  NULL,
    [TREZORPROCESSCODE]             NVARCHAR (20)  NULL,
    [TREZORENTITYTYPE]              INT            NULL,
    [TREZORENTITYID]                NVARCHAR (10)  NULL,
    [TREZORCUSTOMVERSIONKEYCOMP]    NVARCHAR (20)  NULL,
    [TREZORXML]                     NVARCHAR (MAX) NULL,
    [STATUSTREZOR]                  NVARCHAR (256) NULL,
    [operacja]                      NVARCHAR (1)   NULL,
    CONSTRAINT [I_103091RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

