CREATE TABLE [zef2].[KPFINSTATEMENTDEF] (
    [FINSTATEMENTDEFSEQID]            NVARCHAR (15)  NULL,
    [DOCUTYPEID]                      NVARCHAR (10)  NULL,
    [XMLINTERVAL]                     INT            NULL,
    [XMLTAG]                          NVARCHAR (50)  NULL,
    [XMLDOCUMENTNAME]                 NVARCHAR (40)  NULL,
    [POSTTOACCOUNT]                   INT            NULL,
    [POSTTOTRANS]                     INT            NULL,
    [POSTINGLEVEL]                    INT            NULL,
    [VOUCHERSEQID]                    NVARCHAR (15)  NULL,
    [XMLSUBDOCUMENT]                  INT            NULL,
    [CALCPLANONLYNOZERO]              INT            NULL,
    [AUTOCREATE]                      INT            NULL,
    [DATEFROM]                        DATETIME       NULL,
    [BLOCKED]                         INT            NULL,
    [FINSTATEMENTDEFVERSIONID]        NVARCHAR (10)  NULL,
    [MANDATORYCLASSIFICATION]         INT            NULL,
    [DYNAMICROWS]                     INT            NULL,
    [DEFAULTCONSOLIDATED_FK]          BIGINT         NULL,
    [DEFAULTAGGR_FK]                  BIGINT         NULL,
    [DEFAULTSTATEMENT_FK]             BIGINT         NULL,
    [FINSTATEMENTTYPEDEF_FK]          BIGINT         NULL,
    [PROJECTNOYES]                    INT            NULL,
    [PROGRAMNOYES]                    INT            NULL,
    [PARAGRAPHNOYES]                  INT            NULL,
    [SUBSECTIONNOYES]                 INT            NULL,
    [SECTIONNOYES]                    INT            NULL,
    [EMPLOYMENTGROUPNOYES]            INT            NULL,
    [FINSTATEMENTTYPE]                INT            NULL,
    [PART]                            INT            NULL,
    [RECIPIENT]                       NVARCHAR (100) NULL,
    [PROTECTEDDOCUTYPEID]             NVARCHAR (10)  NULL,
    [CHECKCLASSNAME]                  NVARCHAR (40)  NULL,
    [DATAPREPCLASSNAME]               NVARCHAR (40)  NULL,
    [MODIFIEDDATETIME]                DATETIME       NULL,
    [MODIFIEDBY]                      NVARCHAR (8)   NULL,
    [MODIFIEDTRANSACTIONID]           BIGINT         NULL,
    [CREATEDDATETIME]                 DATETIME       NULL,
    [CREATEDBY]                       NVARCHAR (8)   NULL,
    [CREATEDTRANSACTIONID]            BIGINT         NULL,
    [RECVERSION]                      INT            NULL,
    [PARTITION]                       BIGINT         NULL,
    [RECID]                           BIGINT         NOT NULL,
    [PARTNOYES]                       INT            NULL,
    [WORKNOYES]                       INT            NULL,
    [DESCNOYES]                       INT            NULL,
    [ROWIDNOYES]                      INT            NULL,
    [MRDOSIMPORT]                     INT            NULL,
    [FINCONSOLIDATIONFIELDIDX]        INT            NULL,
    [FINCONSOLIDATIONORGUNITTABLE_FK] BIGINT         NULL,
    [REPORTMENUITEMNAME]              NVARCHAR (40)  NULL,
    [REMARKSNOYES]                    INT            NULL,
    [TREZORIMPORTCLASSNAME]           NVARCHAR (40)  NULL,
    [operacja]                        NVARCHAR (1)   NULL,
    CONSTRAINT [I_30636RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

