CREATE TABLE [zef2].[KPFINSTATEMENTTYPEDEF] (
    [FINSTATEMENTTYPEDEFID]    NVARCHAR (15)  NULL,
    [DESCRIPTION]              NVARCHAR (255) NULL,
    [FINSTATEMENTTYPE]         INT            NULL,
    [PERIODTYPE]               INT            NULL,
    [FINSTATEMENTTYPEDEFGENID] NVARCHAR (20)  NULL,
    [MODIFIEDDATETIME]         DATETIME       NULL,
    [MODIFIEDBY]               NVARCHAR (8)   NULL,
    [MODIFIEDTRANSACTIONID]    BIGINT         NULL,
    [CREATEDDATETIME]          DATETIME       NULL,
    [CREATEDBY]                NVARCHAR (8)   NULL,
    [CREATEDTRANSACTIONID]     BIGINT         NULL,
    [RECVERSION]               INT            NULL,
    [PARTITION]                BIGINT         NULL,
    [RECID]                    BIGINT         NOT NULL,
    [MRDOSRODZAJDOK]           NVARCHAR (20)  NULL,
    [MRDOSIMPORT]              INT            NULL,
    [CONSOLIDATION]            INT            NULL,
    [MODULE]                   INT            NULL,
    [ALLOWTOALLDATAAREA]       INT            NULL,
    [DOCUMENTCODE]             NVARCHAR (10)  NULL,
    [ALLOWSENDTOTREZOR]        INT            NULL,
    [TREZORPROCESSCODE]        NVARCHAR (20)  NULL,
    [USERGROUPID]              NVARCHAR (10)  NULL,
    [FINSTATEMENTUNITTYPE]     INT            NULL,
    [operacja]                 NVARCHAR (1)   NULL,
    CONSTRAINT [I_103044RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

