CREATE TABLE [zef2].[KPFINSTATEMENTTRANS] (
    [DESCRIPTION]                NVARCHAR (250)   NULL,
    [LINENUM]                    NUMERIC (32, 16) NULL,
    [VALUE]                      NUMERIC (32, 16) NULL,
    [VALUE2_]                    NUMERIC (32, 16) NULL,
    [VALUE3_]                    NUMERIC (32, 16) NULL,
    [VALUE4_]                    NUMERIC (32, 16) NULL,
    [VALUE5_]                    NUMERIC (32, 16) NULL,
    [VALUE6_]                    NUMERIC (32, 16) NULL,
    [VALUE7_]                    NUMERIC (32, 16) NULL,
    [VALUE8_]                    NUMERIC (32, 16) NULL,
    [VALUE9_]                    NUMERIC (32, 16) NULL,
    [VALUE10_]                   NUMERIC (32, 16) NULL,
    [VALUE11_]                   NUMERIC (32, 16) NULL,
    [VALUE12_]                   NUMERIC (32, 16) NULL,
    [VALUE13_]                   NUMERIC (32, 16) NULL,
    [VALUE14_]                   NUMERIC (32, 16) NULL,
    [VALUE15_]                   NUMERIC (32, 16) NULL,
    [VALUE16_]                   NUMERIC (32, 16) NULL,
    [VALUE17_]                   NUMERIC (32, 16) NULL,
    [VALUE18_]                   NUMERIC (32, 16) NULL,
    [VALUE19_]                   NUMERIC (32, 16) NULL,
    [VALUE20_]                   NUMERIC (32, 16) NULL,
    [MARKER]                     NVARCHAR (8)     NULL,
    [ROWID]                      NVARCHAR (10)    NULL,
    [FINSTATEMENTTABLE_FK]       BIGINT           NULL,
    [DEFAULTDIMENSION_FK]        BIGINT           NULL,
    [DATACLASSIFICATION_FK]      BIGINT           NULL,
    [DATACLASSSECTION]           NVARCHAR (10)    NULL,
    [DATACLASSSUBSECTION]        NVARCHAR (10)    NULL,
    [DATACLASSPARAGRAPH]         NVARCHAR (10)    NULL,
    [DATACLASSPROJECTID]         NVARCHAR (18)    NULL,
    [DATACLASSPROGRAMID]         NVARCHAR (18)    NULL,
    [DATACLASSEMPLOYMENTGROUPID] NVARCHAR (10)    NULL,
    [LEDGERDIMENSION_FK]         BIGINT           NULL,
    [MODIFIEDDATETIME]           DATETIME         NULL,
    [MODIFIEDBY]                 NVARCHAR (8)     NULL,
    [MODIFIEDTRANSACTIONID]      BIGINT           NULL,
    [CREATEDDATETIME]            DATETIME         NULL,
    [CREATEDBY]                  NVARCHAR (8)     NULL,
    [CREATEDTRANSACTIONID]       BIGINT           NULL,
    [RECVERSION]                 INT              NULL,
    [PARTITION]                  BIGINT           NULL,
    [RECID]                      BIGINT           NOT NULL,
    [DATACLASSWORKID]            NVARCHAR (15)    NULL,
    [DATACLASSPART]              INT              NULL,
    [PROGRAMNAMEFORSTATEMENT]    NVARCHAR (200)   NULL,
    [CUSTNAME]                   NVARCHAR (200)   NULL,
    [CUSTADDRES]                 NVARCHAR (250)   NULL,
    [PRZYCZYNYDECYZJIUMORZENIA]  INT              NULL,
    [WRITEOFFCAUSE]              INT              NULL,
    [TREZORPOSITIONCODE]         NVARCHAR (60)    NULL,
    [TREZORCHAPTERCODE]          NVARCHAR (60)    NULL,
    [DATACLASSPARAGRAPH1]        NVARCHAR (10)    NULL,
    [REMARKS]                    NVARCHAR (150)   NULL,
    [DATACLASSQUALEX]            NVARCHAR (10)    NULL,
    [DATACLASSQUALIN]            NVARCHAR (10)    NULL,
    [operacja]                   NVARCHAR (1)     NULL,
    CONSTRAINT [I_103092RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

