CREATE TABLE [zef2].[KPJOURNALSTATUSTABLE] (
    [STATUSNAME]            NVARCHAR (80) NULL,
    [STATUSNAMEID]          NVARCHAR (10) NOT NULL,
    [STARTSTATUSID]         NVARCHAR (20) NULL,
    [MODIFIEDDATETIME]      DATETIME      NULL,
    [MODIFIEDBY]            NVARCHAR (8)  NULL,
    [MODIFIEDTRANSACTIONID] BIGINT        NULL,
    [CREATEDDATETIME]       DATETIME      NULL,
    [DEL_CREATEDTIME]       INT           NULL,
    [CREATEDBY]             NVARCHAR (8)  NULL,
    [CREATEDTRANSACTIONID]  BIGINT        NULL,
    [RECVERSION]            INT           NULL,
    [PARTITION]             BIGINT        NOT NULL,
    [RECID]                 BIGINT        NULL,
    [operacja]              NVARCHAR (1)  NULL,
    CONSTRAINT [I_30696STATUSIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [STATUSNAMEID] ASC)
);

