CREATE TABLE [zef2].[KPORGANIZATIONUNITTABLE] (
    [ORGANIZATIONUNITID]         NVARCHAR (10)  NULL,
    [NAME]                       NVARCHAR (256) NULL,
    [BLOCKED]                    INT            NULL,
    [LEVEL1]                     INT            NULL,
    [LEVEL2]                     INT            NULL,
    [LEVEL3]                     INT            NULL,
    [LEVEL4]                     INT            NULL,
    [ORGANIZATIONUNITPARENT_FK]  BIGINT         NULL,
    [LEVEL5]                     INT            NULL,
    [UNITDATAAREAID]             NVARCHAR (4)   NULL,
    [DEPARTMENT_FK]              BIGINT         NULL,
    [ENFORCEMENTAUTHORITY]       INT            NULL,
    [TREZORID]                   NVARCHAR (10)  NULL,
    [PART]                       INT            NULL,
    [TAXAUTHORITY]               INT            NULL,
    [LOCATION_FK]                BIGINT         NULL,
    [DEL_EMAILINTERESTDECISION]  NVARCHAR (80)  NULL,
    [EMAILIDPAYMENTDEMAND]       NVARCHAR (10)  NULL,
    [DEL_EMAILTW]                NVARCHAR (80)  NULL,
    [USERTW]                     NVARCHAR (80)  NULL,
    [FINSTATEMENTNAME]           NVARCHAR (120) NULL,
    [REGNUM]                     NVARCHAR (15)  NULL,
    [VISIBLEINDIMATTRIBUTEVIEW]  INT            NULL,
    [TWNAME]                     NVARCHAR (256) NULL,
    [DEL_EMAILIDDEPOSITSUMAPPL]  NVARCHAR (10)  NULL,
    [DEL_EMAILDEPOSITSUMAPPL]    NVARCHAR (80)  NULL,
    [MODIFIEDDATETIME]           DATETIME       NULL,
    [MODIFIEDBY]                 NVARCHAR (8)   NULL,
    [MODIFIEDTRANSACTIONID]      BIGINT         NULL,
    [CREATEDDATETIME]            DATETIME       NULL,
    [CREATEDBY]                  NVARCHAR (8)   NULL,
    [CREATEDTRANSACTIONID]       BIGINT         NULL,
    [RECVERSION]                 INT            NULL,
    [PARTITION]                  BIGINT         NULL,
    [RECID]                      BIGINT         NOT NULL,
    [NUMSEQCUST_FK]              BIGINT         NULL,
    [CUSTACCOUNT]                NVARCHAR (20)  NULL,
    [VISIBLEINREGULOFPROTECTION] INT            NULL,
    [ORGANIZATIONUNITIDSHORT]    NVARCHAR (16)  NULL,
    [ISRECEIVER]                 INT            NULL,
    [NAMEFORLIMITS]              NVARCHAR (256) NULL,
    [LOCATIONEA_FK]              BIGINT         NULL,
    [TAXTREZORID]                NVARCHAR (10)  NULL,
    [TREZORBUDGETUNIT]           NVARCHAR (10)  NULL,
    [operacja]                   NVARCHAR (1)   NULL,
    CONSTRAINT [I_103064RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

