CREATE TABLE [MF\FPLB].[Eliza_Celina_21] (
    [Nr zgłoszenia]            VARCHAR (40)    NULL,
    [Data]                     VARCHAR (10)    NULL,
    [Regon Nadawcy]            VARCHAR (14)    NULL,
    [TIN Nadawcy]              VARCHAR (12)    NULL,
    [Pesel Nadawcy]            VARCHAR (11)    NULL,
    [Nadawca]                  VARCHAR (35)    NULL,
    [Adres N]                  VARCHAR (35)    NULL,
    [KodP N]                   VARCHAR (9)     NULL,
    [Miejscowość N]            VARCHAR (35)    NULL,
    [Kraj N]                   VARCHAR (2)     NULL,
    [Regon Odbiorcy]           VARCHAR (14)    NULL,
    [TIN Odbiorcy]             VARCHAR (12)    NULL,
    [Pesel Odbiorcy]           VARCHAR (11)    NULL,
    [Odbiorca]                 VARCHAR (35)    NULL,
    [Adres O]                  VARCHAR (35)    NULL,
    [KodP O]                   VARCHAR (9)     NULL,
    [Miejscowość O]            VARCHAR (35)    NULL,
    [Kraj O]                   VARCHAR (2)     NULL,
    [Regon Zgłaszającego]      VARCHAR (14)    NULL,
    [TIN Zgłaszającego]        VARCHAR (12)    NULL,
    [Zgłaszajacy]              VARCHAR (35)    NULL,
    [Adres Z]                  VARCHAR (35)    NULL,
    [KodP Z]                   VARCHAR (9)     NULL,
    [Miejscowość Z]            VARCHAR (35)    NULL,
    [Kraj Z]                   VARCHAR (2)     NULL,
    [Procedura]                VARCHAR (4)     NULL,
    [Nr pozycji]               SMALLINT        NULL,
    [Kod towaru]               VARCHAR (8)     NULL,
    [Opis towaru]              VARCHAR (1000)  NULL,
    [Marka]                    VARCHAR (3)     NULL,
    [Nr nadwozia]              VARCHAR (35)    NULL,
    [Rok produkcji]            INT             NULL,
    [Kraj pochodzenia]         VARCHAR (2)     NULL,
    [Kraj wysyłki]             VARCHAR (2)     NULL,
    [Kraj przeznaczenia]       VARCHAR (2)     NULL,
    [Transport na granicy]     VARCHAR (27)    NULL,
    [Transport wewnątrz kraju] VARCHAR (27)    NULL,
    [Waluta]                   VARCHAR (3)     NULL,
    [Kurs waluty]              DECIMAL (10, 4) NULL,
    [Wartość w walucie]        DECIMAL (17, 2) NULL,
    [Masa brutto]              DECIMAL (14, 3) NULL,
    [Masa netto]               DECIMAL (14, 3) NULL,
    [Ilość w ujm]              DECIMAL (14, 3) NULL,
    [Wartość stat w PLN]       BIGINT          NULL
);

