CREATE TABLE [MF\FPLB].[Eliza_21_EXT] (
    [Data przyjęcia]        DATETIME2 (3)   NULL,
    [Data awizacji]         DATETIME2 (3)   NULL,
    [Status]                NCHAR (1)       NOT NULL,
    [Nr zgłoszenia]         NVARCHAR (35)   NULL,
    [UC wyjścia]            NVARCHAR (8)    NULL,
    [Dekl UC wyprowadzenia] NVARCHAR (8)    NULL,
    [UC wyprowadzenia]      NVARCHAR (8)    NULL,
    [UC zmieniony]          NVARCHAR (8)    NULL,
    [Data prezentacji]      DATETIME2 (3)   NULL,
    [Data wyprowadzenia]    DATETIME2 (3)   NULL,
    [Termin dostawy]        DATETIME2 (3)   NULL,
    [TIN Nadawcy]           NVARCHAR (17)   NULL,
    [Nadawca]               NVARCHAR (105)  NULL,
    [Adres N]               NVARCHAR (105)  NULL,
    [KodP N]                NVARCHAR (9)    NULL,
    [Miejscowość N]         NVARCHAR (105)  NULL,
    [Kraj N]                NVARCHAR (2)    NULL,
    [TIN NadawcyPozycja]    NVARCHAR (17)   NULL,
    [NadawcaPozycja]        NVARCHAR (105)  NULL,
    [AdresEPozycja]         NVARCHAR (105)  NULL,
    [KodPEPozycja]          NVARCHAR (9)    NULL,
    [MiejscEPozycja]        NVARCHAR (105)  NULL,
    [KrajEPozycja]          NVARCHAR (2)    NULL,
    [TIN Odbiorcy]          NVARCHAR (17)   NULL,
    [Odbiorca]              NVARCHAR (105)  NULL,
    [Adres O]               NVARCHAR (105)  NULL,
    [KodP O]                NVARCHAR (9)    NULL,
    [Miejscowość O]         NVARCHAR (105)  NULL,
    [Kraj O]                NVARCHAR (2)    NULL,
    [TIN OdbiorcyPozycja]   NVARCHAR (17)   NULL,
    [OdbiorcaPozycja]       NVARCHAR (105)  NULL,
    [AdresOPozycja]         NVARCHAR (105)  NULL,
    [KodPOPozycja]          NVARCHAR (9)    NULL,
    [MiejscOPozycja]        NVARCHAR (105)  NULL,
    [KrajOPozycja]          NVARCHAR (2)    NULL,
    [TIN Przewoźnika]       NVARCHAR (17)   NULL,
    [Przewoźnik]            NVARCHAR (105)  NULL,
    [Adres P]               NVARCHAR (105)  NULL,
    [KodP P]                NVARCHAR (9)    NULL,
    [Miejscowość P]         NVARCHAR (105)  NULL,
    [Kraj P]                NVARCHAR (2)    NULL,
    [Transport na granicy]  NVARCHAR (255)  NULL,
    [Środek transportu]     NVARCHAR (765)  NULL,
    [Kraj wysyłki]          NVARCHAR (2)    NULL,
    [Kraj przeznaczenia]    NVARCHAR (2)    NULL,
    [Masa brutto w kg]      NUMERIC (18, 3) NULL,
    [Masa netto w kg]       NUMERIC (18, 3) NULL,
    [Nr pozycji]            INT             NULL,
    [Kod towaru 1]          NVARCHAR (8)    NULL,
    [Kod towaru]            NVARCHAR (22)   NULL,
    [Opis towaru]           NVARCHAR (840)  NULL,
    [Waluta]                NVARCHAR (3)    NULL,
    [Kwota]                 NUMERIC (17, 2) NULL,
    [Wynik kontroli]        NVARCHAR (2)    NULL
);

