CREATE TABLE [MF\FPLB].[Eliza_NCTS1_21] (
    [Nr zgłoszenia]          VARCHAR (21)    NULL,
    [Typ dokumentu]          VARCHAR (5)     NULL,
    [Data przyjęcia]         VARCHAR (10)    NULL,
    [UC wyjścia]             VARCHAR (8)     NULL,
    [UC przybycia]           VARCHAR (8)     NULL,
    [Dekl UC przeznaczenia]  VARCHAR (8)     NULL,
    [UC przeznaczenia]       VARCHAR (8)     NULL,
    [Kraj wysyłki]           CHAR (2)        NULL,
    [Kraj przeznaczenia]     CHAR (2)        NULL,
    [EORI Nadawcy]           VARCHAR (17)    NULL,
    [Nadawca]                NVARCHAR (105)  NULL,
    [Adres Nadawcy]          NVARCHAR (105)  NULL,
    [KodP N]                 VARCHAR (27)    NULL,
    [Miejscowość N]          NVARCHAR (105)  NULL,
    [Kraj N]                 CHAR (2)        NULL,
    [Nadawca1T]              VARCHAR (17)    NULL,
    [Nadawca1N]              NVARCHAR (105)  NULL,
    [Nadawca1A]              NVARCHAR (105)  NULL,
    [Nadawca1P]              VARCHAR (27)    NULL,
    [Nadawca1M]              NVARCHAR (105)  NULL,
    [Nadawca1K]              CHAR (2)        NULL,
    [Nadawca2T]              VARCHAR (17)    NULL,
    [Nadawca2N]              NVARCHAR (105)  NULL,
    [Nadawca2A]              NVARCHAR (105)  NULL,
    [Nadawca2P]              VARCHAR (27)    NULL,
    [Nadawca2M]              NVARCHAR (105)  NULL,
    [Nadawca2K]              CHAR (2)        NULL,
    [EORI Odbiorcy]          VARCHAR (17)    NULL,
    [Odbiorca]               NVARCHAR (105)  NULL,
    [Adres Odbiorcy]         NVARCHAR (105)  NULL,
    [KodP O]                 VARCHAR (27)    NULL,
    [Miejscowość O]          NVARCHAR (105)  NULL,
    [Kraj O]                 CHAR (2)        NULL,
    [Odbiorca1T]             VARCHAR (17)    NULL,
    [Odbiorca1N]             NVARCHAR (105)  NULL,
    [Odbiorca1A]             NVARCHAR (105)  NULL,
    [Odbiorca1P]             VARCHAR (27)    NULL,
    [Odbiorca1M]             NVARCHAR (105)  NULL,
    [Odbiorca1K]             CHAR (2)        NULL,
    [Odbiorca2T]             VARCHAR (17)    NULL,
    [Odbiorca2N]             NVARCHAR (105)  NULL,
    [Odbiorca2A]             NVARCHAR (105)  NULL,
    [Odbiorca2P]             VARCHAR (27)    NULL,
    [Odbiorca2M]             NVARCHAR (105)  NULL,
    [Odbiorca2K]             CHAR (2)        NULL,
    [EORI Gł Zobowiązanego]  VARCHAR (17)    NULL,
    [Główny Zobowiązany]     NVARCHAR (105)  NULL,
    [Adres Gł Zobowiązanego] NVARCHAR (105)  NULL,
    [KodP GZ]                VARCHAR (27)    NULL,
    [Miejscowość GZ]         NVARCHAR (105)  NULL,
    [Kraj GZ]                CHAR (2)        NULL,
    [EORI Zgłaszającego]     VARCHAR (17)    NULL,
    [Zgłaszający]            NVARCHAR (105)  NULL,
    [Adres Zgłaszającego]    NVARCHAR (105)  NULL,
    [KodP Z]                 VARCHAR (27)    NULL,
    [Miejscowość Z]          NVARCHAR (105)  NULL,
    [Kraj Z]                 CHAR (2)        NULL,
    [EORI Przewoźnika]       VARCHAR (17)    NULL,
    [Przewoźnik]             NVARCHAR (105)  NULL,
    [Adres Przewoźnika]      NVARCHAR (105)  NULL,
    [KodP Prz]               VARCHAR (27)    NULL,
    [Miejscowość Prz]        NVARCHAR (105)  NULL,
    [Kraj Prz]               CHAR (2)        NULL,
    [Kontenery]              VARCHAR (17)    NULL,
    [Termin dostawy]         DATETIME        NULL,
    [Data przybycia]         VARCHAR (10)    NULL,
    [OperZam]                VARCHAR (10)    NULL,
    [RTrW]                   CHAR (2)        NULL,
    [PWew]                   CHAR (2)        NULL,
    [sr_transp]              VARCHAR (81)    NULL,
    [RTrG]                   CHAR (2)        NULL,
    [PGran]                  CHAR (2)        NULL,
    [s_tr_gr]                VARCHAR (81)    NULL,
    [Kontrola UC wyjścia]    CHAR (2)        NULL,
    [Kontrola UC przybycia]  CHAR (2)        NULL,
    [Nr pozycji]             DECIMAL (5)     NULL,
    [Opis towaru]            NVARCHAR (840)  NULL,
    [Kod HS]                 VARCHAR (6)     NULL,
    [Kod CN]                 CHAR (2)        NULL,
    [Masa netto w kg]        DECIMAL (14, 3) NULL,
    [Masa brutto w kg]       DECIMAL (14, 3) NULL,
    [Nr gwarancji]           VARCHAR (24)    NULL,
    [Odnośnik do gwarancji]  VARCHAR (35)    NULL,
    [typ_gwarancji]          CHAR (2)        NULL,
    [Kwota]                  DECIMAL (17, 2) NULL,
    [Waluta]                 VARCHAR (3)     NULL,
    [Status]                 VARCHAR (3)     NULL
);

