CREATE TABLE [MF\FPLB].[elizaD2] (
    [Nr dokumentu1]                         NVARCHAR (255)  NULL,
    [Status dokumentu1]                     NVARCHAR (4000) NULL,
    [Nr VAT UE]                             NVARCHAR (4000) NULL,
    [Deklaracja za okres]                   NVARCHAR (7)    NULL,
    [Zarachowanie]                          NVARCHAR (5)    NULL,
    [Powód zarachowania]                    NVARCHAR (4000) NULL,
    [Urząd celny]                           NVARCHAR (255)  NULL,
    [Deklaracja czy korekta]                INT             NULL,
    [Data złozenia dokumentu]               CHAR (10)       NULL,
    [Nr dokumentu pierwotnego]              NVARCHAR (255)  NULL,
    [Uzasadnienie korekty]                  NVARCHAR (4000) NULL,
    [Rodzaj korekty]                        NVARCHAR (32)   NULL,
    [Data doręczenia korekty z urzędu]      DATETIME2 (7)   NULL,
    [Data wniesienia sprzeciwu]             DATETIME2 (7)   NULL,
    [Czy sprzeciw do korekty z urzędu]      NVARCHAR (5)    NULL,
    [Razem kwota podatku]                   DECIMAL (19, 2) NULL,
    [Zwolnienia/obniżenia]                  DECIMAL (19, 2) NULL,
    [Kwota podatku po obniżeniach]          DECIMAL (19, 4) NULL,
    [Do zapłaty]                            DECIMAL (19, 2) NULL,
    [Imię pełnomocnika]                     NVARCHAR (4000) NULL,
    [Nazwisko pełnomocnika]                 NVARCHAR (4000) NULL,
    [Telefon podatnika lub pełnomocnika]    NVARCHAR (4000) NULL,
    [E-mail Podatnika lub pełnomocnika]     NVARCHAR (4000) NULL,
    [Uwagi urzędu celnego]                  NVARCHAR (4000) NULL,
    [Data złożenia deklaracji pierwotnej]   CHAR (10)       NULL,
    [Czy ostatnia wersja deklaracji]        NVARCHAR (5)    NULL,
    [Data powstania obowiązku podtakowego]  CHAR (10)       NULL,
    [Termin płatności]                      INT             NULL,
    [Data płatności]                        CHAR (10)       NULL,
    [Status dokumentu]                      NVARCHAR (4000) NULL,
    [Nr dokumentu]                          NVARCHAR (255)  NULL,
    [Data wpływu dokumentu]                 DATETIME2 (7)   NULL,
    [Nazwa grupy wyrobów]                   NVARCHAR (4000) NULL,
    [Informacje dodatkowe]                  NVARCHAR (4000) NULL,
    [Kod CN]                                NVARCHAR (255)  NULL,
    [Podstawa obliczenia: ilość]            DECIMAL (19, 4) NULL,
    [Podstawa obliczenia: wartość]          DECIMAL (19, 4) NULL,
    [Stawka podatku - procent]              DECIMAL (19, 4) NULL,
    [Stawka podatku - kwota]                DECIMAL (19, 4) NULL,
    [Minimalna stawka podatku od wyr. tyt.] DECIMAL (19, 4) NULL,
    [Kwota podatku]                         DECIMAL (19, 2) NULL,
    [Stawka spoza ISZTAR]                   NVARCHAR (5)    NULL,
    [Rodzaj stawki spoza ISZTAR]            NVARCHAR (16)   NULL,
    [Wartość stawki spoza ISZTAR]           DECIMAL (19, 4) NULL
);

