--========================================
--Author: Tomasz Pióro
--Date: 2014-08-08
--Description: Procedura usuwania danych za konkretny rok w systemie NCTS1.
--========================================

CREATE PROCEDURE [a2].[ArchNCTSUsunDaneZaRok]
	@Rok int
AS
	DECLARE @DataOd DATE = DATEFROMPARTS(@Rok+0, 1, 1);
	DECLARE @DataDo DATE = DATEFROMPARTS(@Rok+1, 1, 1);

	SET XACT_ABORT ON;
	BEGIN TRANSACTION;

	DELETE i FROM ncts.TRANS_OPER_RISK_PL i
	INNER JOIN ncts.TRANS_OPER tr ON tr.[SID] = i.TRANS_OPER_SID
	WHERE tr.DAT_WRITT_OFF >= @DataOd and tr.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.GUARANTEE_VAL_LIM ds
	INNER JOIN ncts.GUARANTEE_REF g ON g.SID = ds.GUARANTEE_REF_SID
	INNER JOIN ncts.GUARANTEE_I gi ON gi.SID = g.GUARANTEE_I_SID
	INNER JOIN ncts.TRANS_OPER i ON i.[SID] = gi.[SID]
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.DECL_GOODS_ITEM_DOC ds
	INNER JOIN ncts.DECL_GOODS_ITEM j ON j.[SID] = ds.DECL_GOODS_ITEM_SID
	INNER JOIN ncts.TRANS_OPER x ON x.[SID] = j.[TRANS_OPER_SID]
	WHERE x.DAT_WRITT_OFF >= @DataOd and x.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.TRANS_OPER_STAT_HIST ds
	INNER JOIN ncts.TRANS_OPER x ON x.[SID] = ds.[TRANS_OPER_SID]
	WHERE x.DAT_WRITT_OFF >= @DataOd and x.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.DECL_GOODS_ITEM_SPEC_MENT ds
	INNER JOIN ncts.DECL_GOODS_ITEM i ON i.[SID] = ds.DECL_GOODS_ITEM_SID
	INNER JOIN ncts.TRANS_OPER x ON x.[SID] = i.[TRANS_OPER_SID]
	WHERE x.DAT_WRITT_OFF >= @DataOd and x.DAT_WRITT_OFF < @DataDo;

	DELETE GR FROM ncts.GUARANTEE_REF GR
	INNER JOIN ncts.GUARANTEE_I g ON g.[SID] = GR.GUARANTEE_I_SID
	INNER JOIN ncts.TRANS_OPER as TR ON tr.[SID] = G.TRANS_OPER_SID
	WHERE tr.DAT_WRITT_OFF >= @DataOd and tr.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.DECL_GOODS_ITEM_SENS ds
	INNER JOIN ncts.DECL_GOODS_ITEM i ON i.[SID] = ds.DECL_GOODS_ITEM_SID
	INNER JOIN ncts.TRANS_OPER x ON x.SID = i.[TRANS_OPER_SID]
	WHERE x.DAT_WRITT_OFF >= @DataOd and x.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.DECL_GOODS_ITEM_CONT ds
	INNER JOIN ncts.DECL_GOODS_ITEM i ON i.[SID] = ds.DECL_GOODS_ITEM_SID
	INNER JOIN ncts.TRANS_OPER x ON x.SID = i.[TRANS_OPER_SID]
	WHERE x.DAT_WRITT_OFF >= @DataOd and x.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.DECL_GOODS_ITEM_PACK ds
	INNER JOIN ncts.DECL_GOODS_ITEM i ON i.[SID] = ds.DECL_GOODS_ITEM_SID
	INNER JOIN ncts.TRANS_OPER x ON x.[SID] = i.[TRANS_OPER_SID]
	WHERE x.DAT_WRITT_OFF >= @DataOd and x.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].[CONTR_GOODS_ITEM_DOC] ds
	INNER JOIN ncts.CONTR_GOODS_ITEM x ON x.[SID]=ds.[CONTR_GOODS_ITEM_SID]
	INNER JOIN ncts.TRANS_OPER i on i.MRN = x.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].[SEAL_DET_VERS] ds
	INNER JOIN ncts.SEAL_DET x on x.[SID] = ds.[SEAL_DET_SID]
	INNER JOIN ncts.TRANS_OPER j ON j.MRN = x.[DEP_TRANS_OPER_MRN]
	WHERE j.DAT_WRITT_OFF >= @DataOd and j.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.CONTR_GOODS_ITEM_PACK ds
	INNER JOIN ncts.CONTR_GOODS_ITEM x ON x.[SID]=ds.[CONTR_GOODS_ITEM_SID]
	INNER JOIN ncts.TRANS_OPER i on i.MRN = x.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].[CONTR_GOODS_ITEM_DESCR] ds
	INNER JOIN ncts.CONTR_GOODS_ITEM x ON x.[SID]=ds.[CONTR_GOODS_ITEM_SID]
	INNER JOIN ncts.TRANS_OPER i on i.MRN = x.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].[CONTR_GOODS_ITEM_CONT] ds
	INNER JOIN ncts.CONTR_GOODS_ITEM x ON x.[SID]=ds.[CONTR_GOODS_ITEM_SID]
	INNER JOIN ncts.TRANS_OPER i on i.MRN = x.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].[CONTR_GOODS_ITEM_SENS] ds
	INNER JOIN ncts.CONTR_GOODS_ITEM x ON x.[SID]=ds.CONTR_GOODS_ITEM_SID
	INNER JOIN ncts.TRANS_OPER i on i.MRN = x.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].[CONTR_GOODS_ITEM_SPEC_MENT] ds
	INNER JOIN ncts.CONTR_GOODS_ITEM x ON x.[SID]=ds.[CONTR_GOODS_ITEM_SID]
	INNER JOIN ncts.TRANS_OPER i on i.MRN = x.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].DECL_TRANS_OPER_DET ds
	INNER JOIN [ncts].TRANS_OPER i ON i.[SID] = ds.[TRANS_OPER_SID]
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].TRANS_OPER_PASS ds
	INNER JOIN [ncts].TRANS_OPER j ON j.[SID] = ds.TRANS_OPER_SID
	WHERE j.DAT_WRITT_OFF >= @DataOd and j.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].SEAL_DET ds
	INNER JOIN ncts.TRANS_OPER x ON x.MRN = ds.DEP_TRANS_OPER_MRN
	WHERE x.DAT_WRITT_OFF >= @DataOd and x.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.DECL_GOODS_ITEM ds
	INNER JOIN ncts.TRANS_OPER i ON i.SID = ds.[TRANS_OPER_SID]
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE er FROM [ncts].[EN_ROUT_EVENT_DET] er
	INNER JOIN ncts.EN_ROUT_EVENT e ON e.MRN = er.MRN and e.SEQ = er.EN_ROUT_EVENT_SEQ
	INNER JOIN ncts.TRANS_OPER i ON i.MRN = e.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].CONTR_GOODS_ITEM ds
	INNER JOIN [ncts].TRANS_OPER i ON i.SID = ds.SID
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE g FROM [ncts].GUARANTEE_I g
	INNER JOIN ncts.TRANS_OPER tr ON tr.SID = g.TRANS_OPER_SID
	WHERE tr.DAT_WRITT_OFF >= @DataOd and tr.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].TRANS_OPER_VERS ds
	INNER JOIN ncts.TRANS_OPER tr ON tr.SID = ds.TRANS_OPER_SID
	WHERE tr.DAT_WRITT_OFF >= @DataOd and tr.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].ITINERARY ds
	INNER JOIN [ncts].TRANS_OPER i ON i.SID = ds.[TRANS_OPER_SID]
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM ncts.TRANS_OPER_UNL ds
	INNER JOIN ncts.TRANS_OPER i ON i.MRN = ds.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].[CONTR_TRANS_OPER_DET] ds
	INNER JOIN ncts.TRANS_OPER i ON i.MRN = ds.MRN
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].EN_ROUT_EVENT ds
	INNER JOIN [ncts].TRANS_OPER x ON x.MRN = ds.MRN
	WHERE x.DAT_WRITT_OFF >= @DataOd and x.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].[CONTR_TRANS_OPER_DESCR] ds
	INNER JOIN [ncts].TRANS_OPER i ON i.MRN = ds.[MRN]
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].TRADER_ENQUIRY_REQ ds
	INNER JOIN [ncts].TRANS_OPER i ON i.SID = ds.TRANS_OPER_SID
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE ds FROM [ncts].TRADER_ENQUIRY_RESP ds
	INNER JOIN [ncts].TRANS_OPER i ON i.SID = ds.TRANS_OPER_SID
	WHERE i.DAT_WRITT_OFF >= @DataOd and i.DAT_WRITT_OFF < @DataDo;

	DELETE t FROM [ncts].[TRANS_OPER] t
	WHERE t.DAT_WRITT_OFF >= @DataOd and t.DAT_WRITT_OFF < @DataDo;

	DELETE t FROM [ncts].[TRANS_OPER_MESS] t
	WHERE t.DAT_REC >= @DataOd and t.DAT_REC < @DataDo;

	COMMIT TRANSACTION;
RETURN 0