CREATE TABLE [aes2].[aes_psw] (
    [id]                      NUMERIC (19)    NOT NULL,
    [zcp_id]                  NUMERIC (19)    CONSTRAINT [DF__aes_psw__zcp_id__53CEE5E3] DEFAULT ((0)) NOT NULL,
    [psw_status]              NVARCHAR (4)    NULL,
    [psw_prln_date]           DATETIME        NULL,
    [psw_prln_justification]  NVARCHAR (512)  NULL,
    [psw_srd_print]           INT             NULL,
    [psw_prln_mrn]            NVARCHAR (35)   NULL,
    [psw_time_to_autoprocess] DATETIME        NULL,
    [acceptance_date_time]    DATETIME        NULL,
    [psw_proposal_date]       DATETIME        NULL,
    [psw_proposal_justif]     NVARCHAR (1024) NULL,
    [declaration_co]          NVARCHAR (8)    NULL,
    [calc_date]               DATETIME        NULL,
    [regi_date]               DATETIME        NULL,
    [zcp_system_number]       NVARCHAR (35)   NULL,
    [gross_mass]              NUMERIC (16, 6) NULL,
    [no_of_items]             NUMERIC (5)     NULL,
    [number_of_packages]      NUMERIC (8)     NULL,
    [additional_decl_type]    NVARCHAR (5)    NULL,
    [containers]              BIT             CONSTRAINT [DF__aes_psw__contain__54C30A1C] DEFAULT ((0)) NOT NULL,
    [acceptance_date]         DATETIME        NULL,
    [cr_code]                 NVARCHAR (2)    NULL,
    [P1C]                     NVARCHAR (5)    NULL,
    [psw_digital_signature]   TINYINT         NULL,
    [autorized_ex]            TINYINT         NULL,
    CONSTRAINT [aes_psw$pk_aes_psw] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AES2]
);

