CREATE TABLE [aes2].[ecs_query_goods_item] (
    [id]                          NUMERIC (19)    NOT NULL,
    [cc_combined_nomenclature]    NVARCHAR (8)    NULL,
    [cc_national_add_code]        NVARCHAR (4)    NULL,
    [cc_taric_code]               NVARCHAR (2)    NULL,
    [cc_taric_1st_add_code]       NVARCHAR (4)    NULL,
    [cc_taric_2nd_add_code]       NVARCHAR (4)    NULL,
    [gi_country_of_destination]   NVARCHAR (2)    NULL,
    [gi_country_of_export]        NVARCHAR (2)    NULL,
    [gi_crn]                      NVARCHAR (70)   NULL,
    [gi_desc]                     NVARCHAR (280)  NULL,
    [gi_desc_lang]                NVARCHAR (2)    NULL,
    [gi_gross_mass]               NUMERIC (11, 3) NULL,
    [gi_item_no]                  INT             NULL,
    [gi_national_procedure]       NVARCHAR (3)    NULL,
    [gi_net_mass]                 NUMERIC (11, 3) NULL,
    [gi_proc_previous]            NVARCHAR (2)    NULL,
    [gi_proc_requested]           NVARCHAR (2)    NULL,
    [gi_statistical_value]        NUMERIC (17, 2) NULL,
    [gi_statistical_val_currency] NVARCHAR (3)    NULL,
    [gi_transport_fee_pay_type]   NVARCHAR (1)    NULL,
    [gi_un_dangerous_goods]       NVARCHAR (4)    NULL,
    [exportquery_id]              NUMERIC (19)    NULL,
    CONSTRAINT [ecs_query_goods_item$ecs_query__2316688421] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AES2],
    CONSTRAINT [ecs_query_goods_item$fk_goods_item_expquery] FOREIGN KEY ([exportquery_id]) REFERENCES [aes2].[ecs_query_exportquery] ([q_query_decl_id])
);

