CREATE TABLE [aes2].[ecs_spp_goods_item] (
    [id]                            NUMERIC (19)    NOT NULL,
    [gi_cn_code]                    NVARCHAR (8)    NULL,
    [gi_cn_code_spp]                NVARCHAR (8)    NULL,
    [gi_commodity_code_br]          NVARCHAR (22)   NULL,
    [gi_country_of_destination]     NVARCHAR (2)    NULL,
    [gi_country_of_destination_spp] NVARCHAR (2)    NULL,
    [gi_country_of_export]          NVARCHAR (2)    NULL,
    [gi_country_of_export_spp]      NVARCHAR (2)    NULL,
    [gi_country_of_origin]          NVARCHAR (2)    NULL,
    [gi_country_of_origin_spp]      NVARCHAR (2)    NULL,
    [gi_crn]                        NVARCHAR (70)   NULL,
    [gi_crn_spp]                    NVARCHAR (70)   NULL,
    [gi_desc]                       NVARCHAR (280)  NULL,
    [gi_desc_br]                    NVARCHAR (280)  NULL,
    [gi_gross_mass]                 NUMERIC (18, 3) NULL,
    [gi_gross_mass_br]              NUMERIC (18, 3) NULL,
    [gi_gross_mass_spp]             NUMERIC (18, 3) NULL,
    [gi_item_no]                    INT             NULL,
    [gi_net_mass]                   NUMERIC (18, 3) NULL,
    [gi_net_mass_spp]               NUMERIC (18, 3) NULL,
    [gi_proc_detail]                NVARCHAR (3)    NULL,
    [gi_proc_detail_spp]            NVARCHAR (3)    NULL,
    [gi_proc_previous]              NVARCHAR (2)    NULL,
    [gi_proc_previous_spp]          NVARCHAR (2)    NULL,
    [gi_proc_requested]             NVARCHAR (2)    NULL,
    [gi_proc_requested_spp]         NVARCHAR (2)    NULL,
    [gi_quantity_suppl_unit]        NUMERIC (18, 3) NULL,
    [gi_quantity_suppl_unit_spp]    NUMERIC (18, 3) NULL,
    [gi_taric_code]                 NVARCHAR (2)    NULL,
    [gi_taric_code_spp]             NVARCHAR (2)    NULL,
    [gi_taxes_amount]               NUMERIC (17, 2) NULL,
    [gi_taxes_amount_spp]           NUMERIC (17, 2) NULL,
    [gi_transport_charges_mp]       NVARCHAR (1)    NULL,
    [gi_un_dangerous_goods]         NVARCHAR (4)    NULL,
    [gi_un_dangerous_goods_spp]     NVARCHAR (4)    NULL,
    [vog_statistical_currency]      NVARCHAR (3)    NULL,
    [vog_statistical_value]         NUMERIC (17, 2) NULL,
    [vog_statistical_value_spp]     NUMERIC (17, 2) NULL,
    [declcoexpsuppl_decl_id]        NUMERIC (19)    NULL,
    [gi_transport_charges_mp_spp]   NVARCHAR (1)    NULL,
    CONSTRAINT [ecs_spp_goods_item$ecs_spp_go_20153432131] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AES2],
    CONSTRAINT [ecs_spp_goods_item$fk_goods_item_decl_spp] FOREIGN KEY ([declcoexpsuppl_decl_id]) REFERENCES [aes2].[ecs_spp_declcoexpsuppl] ([decl_id])
);

