CREATE TABLE [aes2].[ecs_zwp_declcopresent] (
    [decl_id]                      NUMERIC (19)    NOT NULL,
    [zwp_gross_mass]               NUMERIC (18, 3) NULL,
    [zwp_gross_mass_pt_c]          NVARCHAR (510)  NULL,
    [zwp_no_of_items_pt_c]         NVARCHAR (280)  NULL,
    [crb_code]                     NVARCHAR (2)    NULL,
    [crb_state_of_seals]           TINYINT         NULL,
    [pad_place]                    NVARCHAR (70)   NULL,
    [pad_date]                     DATETIME2 (3)   NULL,
    [s_quantity]                   INT             NULL,
    [cr_code]                      NVARCHAR (2)    NULL,
    [log_co]                       NVARCHAR (8)    NULL,
    [log_location_desc]            NVARCHAR (510)  NULL,
    [log_location_code]            NVARCHAR (17)   NULL,
    [pos_location_desc]            NVARCHAR (510)  NULL,
    [pos_location_code]            NVARCHAR (17)   NULL,
    [it_identity_pt]               NVARCHAR (255)  NULL,
    [it_identity_pt_c]             NVARCHAR (510)  NULL,
    [it_identity]                  NVARCHAR (510)  NULL,
    [zwp_ecs_decl]                 TINYINT         NULL,
    [zwp_co_of_exit]               NVARCHAR (8)    NULL,
    [zwp_co_of_exit_declared]      NVARCHAR (8)    NULL,
    [zwp_co_of_exit_changed_to]    NVARCHAR (8)    NULL,
    [zwp_storing]                  TINYINT         NULL,
    [zwp_co_of_export]             NVARCHAR (8)    NULL,
    [zwp_decl_type_1a]             NVARCHAR (2)    NULL,
    [zwp_no_of_items]              INT             NULL,
    [zwp_no_of_items_pt]           INT             NULL,
    [zwp_no_of_package]            INT             NULL,
    [zwp_no_of_packages_pt]        INT             NULL,
    [zwp_no_of_packages_pt_c]      NVARCHAR (280)  NULL,
    [zwp_country_of_export]        NVARCHAR (2)    NULL,
    [zwp_country_of_dest]          NVARCHAR (2)    NULL,
    [zwp_containers]               TINYINT         NULL,
    [zwp_gross_mass_pt]            NUMERIC (18, 3) NULL,
    [zwp_acceptance_date]          DATETIME2 (3)   NULL,
    [zwp_issuing_date]             DATETIME2 (3)   NULL,
    [zwp_ead_language]             NVARCHAR (2)    NULL,
    [zwp_time_to_send_exit_result] DATETIME2 (3)   NULL,
    [zwp_time_to_border_arrival]   DATETIME2 (3)   NULL,
    [zwp_presentation_date]        DATETIME2 (3)   NULL,
    [zwp_notification_date]        DATETIME2 (3)   NULL,
    [zwp_status]                   NCHAR (1)       NOT NULL,
    [zwp_exit_date]                DATETIME2 (3)   NULL,
    [zwp_present_stopped_date]     DATETIME2 (3)   NULL,
    [zwp_com_ref_num]              NVARCHAR (70)   NULL,
    [zwp_com_ref_num_di]           NVARCHAR (70)   NULL,
    [zwp_com_ref_num_di_c]         NVARCHAR (140)  NULL,
    [zwp_dec_sub_tim]              DATETIME2 (3)   NULL,
    [zwp_tra_cha_met]              NVARCHAR (1)    NULL,
    [zwp_tra_cha_met_di]           NVARCHAR (1)    NULL,
    [zwp_tra_cha_met_di_c]         NVARCHAR (140)  NULL,
    [zwp_spe_cir_ind]              NVARCHAR (1)    NULL,
    [pad_realDate]                 DATETIME2 (3)   NULL,
    [crb_code_before_transit]      NVARCHAR (2)    NULL,
    [transit]                      BIT             NOT NULL,
    CONSTRAINT [ecs_zwp_declcopresent$PK_ecs_ext_declcopresent] PRIMARY KEY CLUSTERED ([decl_id] ASC) ON [FG_AES2],
    CONSTRAINT [ecs_zwp_declcopresent$FK_ecs_zwp_declcopresent_customs_decl] FOREIGN KEY ([decl_id]) REFERENCES [aes2].[customs_decl] ([id])
);

