CREATE TABLE [aes2].[ecs_sum_declcoexit] (
    [decl_id]                      NUMERIC (19)    NOT NULL,
    [pad_place]                    NVARCHAR (35)   NULL,
    [pad_phone]                    NVARCHAR (15)   NULL,
    [pad_date]                     DATETIME2 (3)   NULL,
    [exp_no_of_items]              INT             NULL,
    [exp_co_of_exit]               NVARCHAR (8)    NULL,
    [exp_no_of_packages]           INT             NULL,
    [gross_mass]                   NUMERIC (18, 3) NULL,
    [cr_code]                      NVARCHAR (2)    NULL,
    [exp_acceptance_date]          DATETIME2 (3)   NULL,
    [crn]                          NVARCHAR (70)   NULL,
    [gross_mass_br]                NUMERIC (18, 3) NULL,
    [log_co]                       NVARCHAR (8)    NULL,
    [log_location_desc]            NVARCHAR (255)  NULL,
    [log_location_code]            NVARCHAR (255)  NULL,
    [exp_co_of_exit_chto]          NVARCHAR (8)    NULL,
    [exp_no_of_items_br]           INT             NULL,
    [exp_no_of_items_brc]          NVARCHAR (140)  NULL,
    [exp_no_of_packages_br]        INT             NULL,
    [exp_no_of_packages_brc]       NVARCHAR (140)  NULL,
    [gross_mass_brc]               NVARCHAR (140)  NULL,
    [exp_storing]                  TINYINT         NULL,
    [exp_digital_signature]        TINYINT         NULL,
    [exp_time_to_release_decision] DATETIME2 (3)   NULL,
    [exp_time_to_auto_acceptance]  DATETIME2 (3)   NULL,
    [exp_exit_date]                DATETIME2 (3)   NULL,
    [exp_exit_stopped_date]        DATETIME2 (3)   NULL,
    [exp_release_date]             DATETIME2 (3)   NULL,
    [pres_date]                    DATETIME2 (3)   NULL,
    [transport_fee_pay_type]       NVARCHAR (1)    NULL,
    [exp_co_of_trader]             NVARCHAR (8)    NULL,
    [sum_co_of_lodg]               NVARCHAR (8)    NULL,
    [peculiar_circumstances]       NVARCHAR (1)    NULL,
    [exp_exit_agreementDate]       DATETIME2 (3)   NULL,
    [regi_date]                    DATETIME2 (3)   NULL,
    [exp_status]                   NCHAR (1)       NULL,
    [exp_notification_date]        DATETIME2 (3)   NULL,
    CONSTRAINT [ecs_sum_declcoexit$ecs_sum_de_7534347271] PRIMARY KEY CLUSTERED ([decl_id] ASC) ON [FG_AES2],
    CONSTRAINT [ecs_sum_declcoexit$FK84587912F1D2936B] FOREIGN KEY ([decl_id]) REFERENCES [aes2].[customs_decl] ([id])
);

