CREATE TABLE [aes2].[MESSAGE_ECS] (
    [ID]              NUMERIC (19)   NOT NULL,
    [MESSAGE_CONTENT] NTEXT          NULL,
    [DIRECTION]       NVARCHAR (255) NULL,
    [UNIQUE_NAME]     NVARCHAR (100) NULL,
    [RETRY_COUNTER]   INT            NULL,
    [NEXT_TRY_TIME]   DATETIME2 (3)  NULL,
    CONSTRAINT [PK_MESSAGE_ECS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AES2]
) TEXTIMAGE_ON [FG_AES2];

