CREATE TABLE [pdr].[c152] (
    [c152_id]              INT            NOT NULL,
    [certyfikat_aeo]       VARCHAR (35)   NULL,
    [creation_tm]          DATETIME       NULL,
    [edi]                  BIT            NULL,
    [email]                NVARCHAR (70)  NULL,
    [eori]                 VARCHAR (17)   NULL,
    [fax]                  VARCHAR (40)   NULL,
    [forma_gosp]           VARCHAR (1)    NULL,
    [id_old_pdr]           VARCHAR (20)   NOT NULL,
    [id_pod]               BIGINT         NULL,
    [kod_pocztowy]         VARCHAR (9)    NOT NULL,
    [kraj]                 VARCHAR (2)    NOT NULL,
    [last_modification_tm] DATETIME       NULL,
    [miejscowosc]          NVARCHAR (35)  NOT NULL,
    [nazwa_krotka]         NVARCHAR (35)  NOT NULL,
    [nazwa_pelna]          NVARCHAR (300) NOT NULL,
    [pesel]                VARCHAR (11)   NULL,
    [placowka_edycji]      VARCHAR (8)    NULL,
    [poczta]               NVARCHAR (35)  NULL,
    [podmiot_gosp]         VARCHAR (1)    NULL,
    [regon]                VARCHAR (14)   NULL,
    [telefon]              VARCHAR (40)   NULL,
    [tin]                  VARCHAR (17)   NOT NULL,
    [ulica]                NVARCHAR (35)  NOT NULL,
    [urzad_rejestrowy]     VARCHAR (8)    NULL,
    [uwagi]                NVARCHAR (255) NULL,
    [valid_from]           DATE           NULL,
    [valid_to]             DATE           NULL,
    [version_]             BIGINT         CONSTRAINT [DF__c152__version___5C4299A5] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__c152__61F28AD25FC3C20F] PRIMARY KEY CLUSTERED ([c152_id] ASC) ON [FG_PDR]
);

