CREATE TABLE [MF\CSCI].[MW_12_celina] (
    [Status]                   CHAR (1)        NULL,
    [numerOGL]                 VARCHAR (40)    NULL,
    [DataPrzyjecia]            VARCHAR (10)    NULL,
    [Nadawca: REGON]           VARCHAR (14)    NULL,
    [Nadawca: NIP]             VARCHAR (12)    NULL,
    [Nadawca: Nazwa]           VARCHAR (35)    NULL,
    [Nadawca: Ulica]           VARCHAR (35)    NULL,
    [Nadawca: Kodpoczt]        VARCHAR (9)     NULL,
    [Nadawca: Miejscowosc]     VARCHAR (35)    NULL,
    [Nadawca: kraj]            VARCHAR (2)     NULL,
    [Odbiorca: REGON]          VARCHAR (14)    NULL,
    [Odbiorca: TIN]            VARCHAR (12)    NULL,
    [Odbiorca: Nazwa]          VARCHAR (35)    NULL,
    [Odbiorca: Ulica]          VARCHAR (35)    NULL,
    [Odbiorca: Kodpoczt]       VARCHAR (9)     NULL,
    [Odbiorca: Miejscowosc]    VARCHAR (35)    NULL,
    [Odbiorca: kraj]           VARCHAR (2)     NULL,
    [Zgłaszający: REGON]       VARCHAR (14)    NULL,
    [Zgłaszający: TIN]         VARCHAR (12)    NULL,
    [Zgłaszający: Nazwa]       VARCHAR (35)    NULL,
    [Zgłaszający: Ulica]       VARCHAR (35)    NULL,
    [Zgłaszający: Kodpoczt]    VARCHAR (9)     NULL,
    [Zgłaszający: Miejscowosc] VARCHAR (35)    NULL,
    [Zgłaszający: Kraj]        VARCHAR (2)     NULL,
    [KrajW]                    VARCHAR (2)     NULL,
    [KodDostawy]               VARCHAR (3)     NULL,
    [Waluta]                   VARCHAR (3)     NULL,
    [KursWaluty]               DECIMAL (10, 4) NULL,
    [WartFaktury]              DECIMAL (17, 2) NULL,
    [NrPozycji]                SMALLINT        NULL,
    [kodCN]                    VARCHAR (8)     NULL,
    [OpisCN]                   VARCHAR (1000)  NULL,
    [KrajPoch]                 VARCHAR (2)     NULL,
    [Procedura]                VARCHAR (4)     NULL,
    [WartoscPozycji]           DECIMAL (17, 2) NULL,
    [MasaNetto]                DECIMAL (14, 3) NULL,
    [IloscUzupelniajacaJm]     DECIMAL (14, 3) NULL,
    [WarStat]                  BIGINT          NULL
);

