CREATE TABLE [MF\CSCI].[MW_22_Celina] (
    [Data przyjęcia]              CHAR (10)       NULL,
    [Nr zgłoszenia]               VARCHAR (40)    NULL,
    [1. DEKLARACJA]               VARCHAR (3)     NULL,
    [5. Pozycje]                  SMALLINT        NULL,
    [7. Numer akt]                VARCHAR (14)    NULL,
    [2.Nadawca: REGON]            VARCHAR (14)    NULL,
    [2.Nadawca: NIP]              VARCHAR (12)    NULL,
    [2.Nadawca: Firma]            VARCHAR (35)    NULL,
    [2.Nadawca: Ulica]            VARCHAR (35)    NULL,
    [2.Nadawca: Kod pocztowy]     VARCHAR (9)     NULL,
    [2.Nadawca: Miejscowość]      VARCHAR (35)    NULL,
    [2.Nadawca: Kraj]             VARCHAR (2)     NULL,
    [8.Odbiorca: REGON]           VARCHAR (14)    NULL,
    [8.Odbiorca: NIP]             VARCHAR (12)    NULL,
    [8.Odbiorca: Firma]           VARCHAR (35)    NULL,
    [8.Odbiorca: Ulica]           VARCHAR (35)    NULL,
    [8.Odbiorca: Kod pocztowy]    VARCHAR (9)     NULL,
    [8.Odbiorca: Miejscowość]     VARCHAR (35)    NULL,
    [8.Odbiorca: Kraj]            VARCHAR (2)     NULL,
    [22.Waluta]                   VARCHAR (3)     NULL,
    [22.Wartość faktury]          DECIMAL (17, 2) NULL,
    [31.Opis towaru]              VARCHAR (1000)  NULL,
    [32.Nr pozycji]               SMALLINT        NULL,
    [33.Kod CN]                   VARCHAR (8)     NULL,
    [KodTaric]                    VARCHAR (2)     NULL,
    [37.Procedura]                VARCHAR (4)     NULL,
    [38.Masa netto kg]            DECIMAL (14, 3) NULL,
    [46.Wartość statystyczna PLN] BIGINT          NULL,
    [47. CŁO Typ]                 VARCHAR (3)     NULL,
    [47. CŁO Podstawa opłaty]     DECIMAL (17, 2) NULL,
    [47. CŁO Stawka]              DECIMAL (7, 2)  NULL,
    [47. CŁO Kwota]               DECIMAL (38, 2) NULL,
    [47. CŁO MP]                  CHAR (1)        NULL,
    [47. AKCYZA Typ]              VARCHAR (3)     NULL,
    [47. AKCYZA Podstawa opłaty]  DECIMAL (17, 2) NULL,
    [47. AKCYZA Stawka]           DECIMAL (7, 2)  NULL,
    [47. AKCYZA Kwota]            DECIMAL (38, 2) NULL,
    [47. AKCYZA MP]               CHAR (1)        NULL,
    [47. VAT Typ]                 VARCHAR (3)     NULL,
    [47. VAT Podstawa opłaty]     DECIMAL (17, 2) NULL,
    [47. VAT Stawka]              DECIMAL (7, 2)  NULL,
    [47. VAT Kwota]               DECIMAL (38, 2) NULL,
    [47. VAT MP]                  CHAR (1)        NULL,
    [47. INNY Typ]                VARCHAR (3)     NULL,
    [47. INNY Podstawa opłaty]    DECIMAL (17, 2) NULL,
    [47. INNY Stawka]             DECIMAL (7, 2)  NULL,
    [47. INNY Kwota]              DECIMAL (38, 2) NULL,
    [47. INNY MP]                 CHAR (1)        NULL,
    [54. Miejsce]                 VARCHAR (35)    NULL,
    [54. Data]                    DATETIME        NULL,
    [54. Podpis elektron]         CHAR (1)        NULL,
    [54. Nazwisko i Imię]         VARCHAR (35)    NULL,
    [54. Stanowisko]              VARCHAR (35)    NULL,
    [54. Telefon]                 VARCHAR (15)    NULL
);

