CREATE TABLE [MF\CSCI].[MW_22_ECS_EXP] (
    [UC_wywozu]                                                                                             NVARCHAR (8)    NULL,
    [UC_wyprowadzenia]                                                                                      NVARCHAR (8)    NULL,
    [UC_wyprowadzenia_zmieniony_na]                                                                         NVARCHAR (8)    NULL,
    [MRN]                                                                                                   NVARCHAR (35)   NULL,
    [Data przyjęcia zgłoszenia]                                                                             DATETIME        NULL,
    [Data wyprowadzenia]                                                                                    DATETIME        NULL,
    [1a.Deklaracja]                                                                                         NVARCHAR (2)    NULL,
    [1b.Deklaracja]                                                                                         NVARCHAR (1)    NULL,
    [2.2.Eksporter: Firma]                                                                                  NVARCHAR (105)  NULL,
    [2.Eksporter: Adres]                                                                                    NVARCHAR (105)  NULL,
    [2.Eksporter: Miejscowość]                                                                              NVARCHAR (105)  NULL,
    [2.Eksporter: Kod pocztowy]                                                                             NVARCHAR (9)    NULL,
    [2.Eksporter: Kraj]                                                                                     NVARCHAR (2)    NULL,
    [2.Eksporter: REGON]                                                                                    NVARCHAR (14)   NULL,
    [2.Eksporter: TIN]                                                                                      NVARCHAR (17)   NULL,
    [5.Pozycje]                                                                                             INT             NULL,
    [6.Opakowania]                                                                                          INT             NULL,
    [7.Numer_własny]                                                                                        NVARCHAR (22)   NULL,
    [8.8.Odbiorca: Firma]                                                                                   NVARCHAR (105)  NULL,
    [8.Odbiorca: Adres]                                                                                     NVARCHAR (105)  NULL,
    [8.Odbiorca: Miejscowość]                                                                               NVARCHAR (105)  NULL,
    [8.Odbiorca: Kod pocztowy]                                                                              NVARCHAR (9)    NULL,
    [8.Odbiorca: Kraj]                                                                                      NVARCHAR (2)    NULL,
    [8.Odbiorca: REGON]                                                                                     NVARCHAR (14)   NULL,
    [8.Odbiorca: NIP]                                                                                       NVARCHAR (17)   NULL,
    [14.14.Zgłaszający: Firma]                                                                              NVARCHAR (105)  NULL,
    [14.Zgłaszający: Adres]                                                                                 NVARCHAR (105)  NULL,
    [14.Zgłaszający: Miejscowość]                                                                           NVARCHAR (105)  NULL,
    [14.Zgłaszający: Kod pocztowy]                                                                          NVARCHAR (9)    NULL,
    [14.Zgłaszający: Kraj]                                                                                  NVARCHAR (2)    NULL,
    [14.Zgłaszający: REGON]                                                                                 NVARCHAR (14)   NULL,
    [14.Zgłaszający: NIP]                                                                                   NVARCHAR (17)   NULL,
    [15.Kod_kraju_wywyozu]                                                                                  NVARCHAR (2)    NULL,
    [17.Kod_kraju_przeznaczenia]                                                                            NVARCHAR (2)    NULL,
    [18.Znaki_śr_transportu_w_UWU]                                                                          NVARCHAR (31)   NULL,
    [19.Kontener]                                                                                           TINYINT         NULL,
    [20.Warunki dostawy]                                                                                    NVARCHAR (108)  NULL,
    [21a.Znaki_śr_transp_urząd_wyprowadz]                                                                   NVARCHAR (31)   NULL,
    [21b.Kraj_śr_transp_urząd_wyprowadz]                                                                    NVARCHAR (2)    NULL,
    [22a.Waluta]                                                                                            NVARCHAR (3)    NULL,
    [22b.Ogólna wartość faktury]                                                                            NUMERIC (17, 2) NULL,
    [23.Kurs waluty]                                                                                        NUMERIC (11, 5) NULL,
    [24.Kod rodzaju transakcji]                                                                             NVARCHAR (2)    NULL,
    [25.Rodzaj transp_urząd_wyprowadz]                                                                      NVARCHAR (2)    NULL,
    [26.Rodzaj transportu wewn]                                                                             NVARCHAR (2)    NULL,
    [29. Urząd wyprowadzenia]                                                                               NVARCHAR (8)    NULL,
    [30.Lokalizacja towaru]                                                                                 NVARCHAR (17)   NULL,
    [31.Opakowania i opis towaru]                                                                           NVARCHAR (840)  NULL,
    [32.Pozycja Nr]                                                                                         INT             NULL,
    [33.Kod towaru]                                                                                         NVARCHAR (8)    NULL,
    [33.Kod TARIC]                                                                                          NVARCHAR (2)    NULL,
    [34.Kod kraju poch.]                                                                                    NVARCHAR (2)    NULL,
    [35.Masa brutto (kg)]                                                                                   NUMERIC (18, 3) NULL,
    [37.Procedura]                                                                                          NVARCHAR (4)    NULL,
    [38.Masa netto (kg)]                                                                                    NUMERIC (18, 3) NULL,
    [40.Dokument poprzedni typ]                                                                             NVARCHAR (6)    NULL,
    [40.Dokument poprzedni nr]                                                                              NVARCHAR (105)  NULL,
    [41.Ilość_w_uzup._jednostce_miary]                                                                      NUMERIC (19, 3) NULL,
    [46.Wartość statystyczna]                                                                               NUMERIC (17, 2) NULL,
    [47.Obliczanie opłat:Typ]                                                                               NVARCHAR (3)    NULL,
    [47.Obliczanie opłat:Podstawa opłaty]                                                                   NUMERIC (17, 2) NULL,
    [47.Obliczanie opłat:Stawka]                                                                            NUMERIC (7, 2)  NULL,
    [47.Obliczanie opłat:Kwota]                                                                             NUMERIC (15, 2) NULL,
    [47.Obliczanie opłat:MP]                                                                                NVARCHAR (1)    NULL,
    [Skład]                                                                                                 TINYINT         NULL,
    [54.Miejsce]                                                                                            NVARCHAR (105)  NULL,
    [54.Data]                                                                                               DATETIME        NULL,
    [54.Zgłaszający:Nazw_i_Imię]],gh  
aes2.ecs_exp_declcoexport.pad_capacity [54.Zgłaszający: Stanowisko] NVARCHAR (105)  NULL,
    [54.Zgłaszający: Telefon]                                                                               NVARCHAR (45)   NULL
);

