CREATE TABLE [MF\CSCI].[MW_32_ics] (
    [status_deklaracji]                      NVARCHAR (4)    NULL,
    [status_pozycji]                         NVARCHAR (4)    NULL,
    [nr_MRN]                                 NVARCHAR (35)   NULL,
    [nr_własny]                              NVARCHAR (35)   NULL,
    [rok_miesiąc]                            VARCHAR (4)     NULL,
    [data_przyjęcia]                         VARCHAR (10)    NULL,
    [Data_zwolnienia_towaru]                 VARCHAR (10)    NULL,
    [Typ_Zgłoszenia]                         NVARCHAR (3)    NULL,
    [ADDITIONAL_DECL_TYPE]                   NVARCHAR (5)    NULL,
    [Urząd_celny_zgłoszenia]                 NVARCHAR (8)    NULL,
    [Urząd_celny_wprowadzenia]               NVARCHAR (8)    NULL,
    [Urząd_celny_Przedstawienia_towaru]      BIT             NOT NULL,
    [Masa_brutto]                            NUMERIC (16, 6) NULL,
    [Liczba_pozycji]                         NUMERIC (5)     NULL,
    [Liczba_opakowań]                        NUMERIC (8)     NULL,
    [Kraj_Wysyłki_Dekl]                      NVARCHAR (2)    NULL,
    [Kraj_Przeznaczenia_Dekl]                NVARCHAR (2)    NULL,
    [Rodzaj_transakcji]                      NUMERIC (2)     NULL,
    [Kod_waluty_Dekl]                        NVARCHAR (3)    NULL,
    [Całkowita_wartość_towarów]              NUMERIC (16, 2) NULL,
    [Waluta]                                 NVARCHAR (3)    NULL,
    [Kurs]                                   NUMERIC (12, 5) NULL,
    [id_kod_nat]                             NUMERIC (19)    NULL,
    [NATIONAL_CODE]                          NVARCHAR (4)    NULL,
    [id_kod_Taric]                           NUMERIC (19)    NULL,
    [TARIC_CODE]                             NVARCHAR (4)    NULL,
    [ICS_DECL_id]                            NUMERIC (19)    NOT NULL,
    [MEASURE_TYPE_CODE]                      NVARCHAR (3)    NULL,
    [MEASURE_NO]                             NUMERIC (2)     NULL,
    [NrPozyc]                                NUMERIC (5)     NULL,
    [kod_CN]                                 NVARCHAR (8)    NULL,
    [Kod_TARIC]                              NVARCHAR (2)    NULL,
    [OpisCN]                                 NVARCHAR (1000) NULL,
    [Kod_preferencji]                        NVARCHAR (3)    NULL,
    [kod_kraju_pochodzenia]                  NVARCHAR (2)    NULL,
    [Procedura]                              NVARCHAR (7)    NULL,
    [Procedura_poprzednia]                   NVARCHAR (2)    NULL,
    [Wartość_pozycji]                        NUMERIC (16, 2) NULL,
    [masa_netto_kg]                          NUMERIC (16, 6) NULL,
    [masa_brutto_kg]                         NUMERIC (16, 6) NULL,
    [Ilość_w_uzupełniającej_jednostce_miary] NUMERIC (16, 6) NULL,
    [Wartość_statystyczna_w_PLN]             NUMERIC (16, 2) NULL
);

