CREATE TABLE [MF\CSCI].[MW_73_ics] (
    [status_deklaracji]                        NVARCHAR (4)    NULL,
    [status_pozycji]                           NVARCHAR (4)    NULL,
    [nr_MRN]                                   NVARCHAR (35)   NULL,
    [nr_własny]                                NVARCHAR (35)   NULL,
    [rok_miesiąc]                              VARCHAR (4)     NULL,
    [data_przyjęcia]                           VARCHAR (10)    NULL,
    [Data_zwolnienia_towaru]                   VARCHAR (10)    NULL,
    [Typ_Zgłoszenia]                           NVARCHAR (3)    NULL,
    [ADDITIONAL_DECL_TYPE]                     NVARCHAR (5)    NULL,
    [Urząd_celny_zgłoszenia]                   NVARCHAR (8)    NULL,
    [Urząd_celny_wprowadzenia]                 NVARCHAR (8)    NULL,
    [Urząd_celny_Przedstawienia_towaru]        BIT             NOT NULL,
    [Masa_brutto]                              NUMERIC (16, 6) NULL,
    [Liczba_pozycji]                           NUMERIC (5)     NULL,
    [Liczba_opakowań]                          NUMERIC (8)     NULL,
    [Nadawca]                                  NVARCHAR (14)   NULL,
    [NIP_N]                                    NVARCHAR (17)   NULL,
    [Eori_N]                                   NVARCHAR (17)   NULL,
    [Nazwa_N]                                  NVARCHAR (70)   NULL,
    [Ulica_N]                                  NVARCHAR (70)   NULL,
    [Kod_N]                                    NVARCHAR (9)    NULL,
    [Miejscowosc_N]                            NVARCHAR (35)   NULL,
    [Kraj_N]                                   NVARCHAR (2)    NULL,
    [Odbiorca]                                 NVARCHAR (14)   NULL,
    [NIP_O]                                    NVARCHAR (17)   NULL,
    [Eori_O]                                   NVARCHAR (17)   NULL,
    [Nazwa_O]                                  NVARCHAR (70)   NULL,
    [Ulica_O]                                  NVARCHAR (70)   NULL,
    [Kod_O]                                    NVARCHAR (9)    NULL,
    [Miejscowosc_O]                            NVARCHAR (35)   NULL,
    [Kraj_O]                                   NVARCHAR (2)    NULL,
    [Zgłaszający]                              NVARCHAR (14)   NULL,
    [NIP_Z]                                    NVARCHAR (17)   NULL,
    [Eori_Z]                                   NVARCHAR (17)   NULL,
    [Nazwa_Z]                                  NVARCHAR (70)   NULL,
    [Ulica_Z]                                  NVARCHAR (70)   NULL,
    [Kod_Z]                                    NVARCHAR (9)    NULL,
    [Miejscowosc_Z]                            NVARCHAR (35)   NULL,
    [Kraj_Z]                                   NVARCHAR (2)    NULL,
    [Przedstawiciel]                           NVARCHAR (14)   NULL,
    [NIP_P]                                    NVARCHAR (17)   NULL,
    [Eori_P]                                   NVARCHAR (17)   NULL,
    [Nazwa_P]                                  NVARCHAR (70)   NULL,
    [Ulica_P]                                  NVARCHAR (70)   NULL,
    [Kod_P]                                    NVARCHAR (9)    NULL,
    [Miejscowosc_P]                            NVARCHAR (35)   NULL,
    [Kraj_P]                                   NVARCHAR (2)    NULL,
    [Kraj_Wysyłki_Dekl]                        NVARCHAR (2)    NULL,
    [Kraj_Przeznaczenia_Dekl]                  NVARCHAR (2)    NULL,
    [Rodzaj_transakcji]                        NUMERIC (2)     NULL,
    [Kod_waluty_Dekl]                          NVARCHAR (3)    NULL,
    [Całkowita_wartość_towarów]                NUMERIC (16, 2) NULL,
    [Waluta]                                   NVARCHAR (3)    NULL,
    [Kurs]                                     NUMERIC (12, 5) NULL,
    [Kod_środka_transportu_na_granicy]         NVARCHAR (4)    NULL,
    [Kod_kraju_śeodka_transportu_na_granicy]   NVARCHAR (2)    NULL,
    [Znaki_środka_transp_na_granicy]           NVARCHAR (35)   NULL,
    [Kod_środka_transportu_wewnętrznego]       NVARCHAR (4)    NULL,
    [Kod_kraju_śeodka_transportu_wewnętrznego] NVARCHAR (2)    NULL,
    [Znaki_środka_transp_wewnętrznego]         NVARCHAR (35)   NULL,
    [id_kod_nat]                               NUMERIC (19)    NULL,
    [NATIONAL_CODE]                            NVARCHAR (4)    NULL,
    [id_kod_Taric]                             NUMERIC (19)    NULL,
    [TARIC_CODE]                               NVARCHAR (4)    NULL,
    [ICS_DECL_id]                              NUMERIC (19)    NOT NULL,
    [MEASURE_TYPE_CODE]                        NVARCHAR (3)    NULL,
    [MEASURE_NO]                               NUMERIC (2)     NULL,
    [NrPozyc]                                  NUMERIC (5)     NULL,
    [kod_CN]                                   NVARCHAR (8)    NULL,
    [Kod_TARIC]                                NVARCHAR (2)    NULL,
    [OpisCN]                                   NVARCHAR (1000) NULL,
    [Kod_preferencji]                          NVARCHAR (3)    NULL,
    [kod_kraju_pochodzenia]                    NVARCHAR (2)    NULL,
    [Procedura]                                NVARCHAR (7)    NULL,
    [Procedura_poprzednia]                     NVARCHAR (2)    NULL,
    [Wartość_pozycji]                          NUMERIC (16, 2) NULL,
    [masa_netto_kg]                            NUMERIC (16, 6) NULL,
    [masa_brutto_kg]                           NUMERIC (16, 6) NULL,
    [Ilość_w_uzupełniającej_jednostce_miary]   NUMERIC (16, 6) NULL,
    [Wartość_statystyczna_w_PLN]               NUMERIC (16, 2) NULL
);

