CREATE TABLE [MF\CSCI].[MW_73_aes2_exp] (
    [id]                                     NUMERIC (19)    NULL,
    [id_good]                                NUMERIC (19)    NULL,
    [status]                                 NCHAR (1)       NULL,
    [UC_wywozu]                              NVARCHAR (8)    NULL,
    [UC_wyprowadzenia]                       NVARCHAR (8)    NULL,
    [UC_wyprowadzenia_zmieniony_na]          NVARCHAR (8)    NULL,
    [numer_MRN]                              NVARCHAR (35)   NULL,
    [Data_ewidencji]                         DATETIME        NULL,
    [Data_przekroczenia_granicy_UE]          DATETIME        NULL,
    [Deklaracja_1a]                          NVARCHAR (2)    NULL,
    [Deklaracja_1b]                          NVARCHAR (1)    NULL,
    [Eksporter_nazwa]                        NVARCHAR (105)  NULL,
    [Eks_adres]                              NVARCHAR (105)  NULL,
    [Eks_miasto]                             NVARCHAR (105)  NULL,
    [Eks_kod]                                NVARCHAR (9)    NULL,
    [Eks_kraj]                               NVARCHAR (2)    NULL,
    [Eks_Regon]                              NVARCHAR (14)   NULL,
    [Eks_NIP]                                NVARCHAR (17)   NULL,
    [Pozycje]                                INT             NULL,
    [Opakowania]                             INT             NULL,
    [Odbiorca_nazwa]                         NVARCHAR (105)  NULL,
    [Odb_adres]                              NVARCHAR (105)  NULL,
    [Odb_miasto]                             NVARCHAR (105)  NULL,
    [Odb_kod]                                NVARCHAR (9)    NULL,
    [Odb_kraj]                               NVARCHAR (2)    NULL,
    [Odb_Regon]                              NVARCHAR (14)   NULL,
    [Odb_NIP]                                NVARCHAR (17)   NULL,
    [Odbiorca_tow_nazwa]                     NVARCHAR (105)  NULL,
    [Odb_tow_adres]                          NVARCHAR (105)  NULL,
    [Odb_tow_miasto]                         NVARCHAR (105)  NULL,
    [Odb_tow_kod]                            NVARCHAR (9)    NULL,
    [Odb_tow_kraj]                           NVARCHAR (2)    NULL,
    [Odb_tow_Regon]                          NVARCHAR (14)   NULL,
    [Odb_tow_NIP]                            NVARCHAR (17)   NULL,
    [Zgłaszający_nazwa]                      NVARCHAR (105)  NULL,
    [Zgł_adres]                              NVARCHAR (105)  NULL,
    [Zgł_miasto]                             NVARCHAR (105)  NULL,
    [Zgł_kod]                                NVARCHAR (9)    NULL,
    [Zgł_kraj]                               NVARCHAR (2)    NULL,
    [Zgł_Regon]                              NVARCHAR (14)   NULL,
    [Zgł_NIP]                                NVARCHAR (17)   NULL,
    [Kod_kraju_wywyozu]                      NVARCHAR (2)    NULL,
    [kod_kraju_przeznaczenia]                NVARCHAR (2)    NULL,
    [Znaki_śr_transportu_w_UWU]              NVARCHAR (31)   NULL,
    [kontener]                               TINYINT         NULL,
    [nr_kontenera]                           NVARCHAR (17)   NULL,
    [kod_warunków_dostawy]                   NVARCHAR (3)    NULL,
    [znaki_śr_transp_urząd_wyprowadz]        NVARCHAR (31)   NULL,
    [kraj_śr_transp_urząd_wyprowadz]         NVARCHAR (2)    NULL,
    [waluta]                                 NVARCHAR (3)    NULL,
    [wartość_faktur]                         NUMERIC (17, 2) NULL,
    [kurs_waluty]                            NUMERIC (11, 5) NULL,
    [kod_rodz_transakcji]                    NVARCHAR (2)    NULL,
    [rodz_śr_transp_urząd_wyprowadz]         NVARCHAR (2)    NULL,
    [Rodzaj_śr_transportu_w_UWU]             NVARCHAR (2)    NULL,
    [urząd_wyprowadzenia]                    NVARCHAR (8)    NULL,
    [lokalizacja_towaru]                     NVARCHAR (17)   NULL,
    [opis_towaru]                            NVARCHAR (840)  NULL,
    [nr_poz]                                 INT             NULL,
    [kod_towaru_CN]                          NVARCHAR (8)    NULL,
    [kraj_pochodzenia]                       NVARCHAR (2)    NULL,
    [masa_brutto]                            NUMERIC (18, 3) NULL,
    [procedura]                              NVARCHAR (4)    NULL,
    [masa_netto]                             NUMERIC (18, 3) NULL,
    [ilość_w_uzupełniającej_jednostce_miary] NUMERIC (19, 3) NULL,
    [wartość_statystyczna_w_PLN]             NUMERIC (17, 2) NULL
);

