CREATE TABLE [MF\CSCI].[MW_70_sad] (
    [Data]                       DATETIME        NULL,
    [NrZgloszenia_Ogl]           VARCHAR (40)    NULL,
    [PozycjaSAD]                 SMALLINT        NULL,
    [8.Odbiorca: REGON]          VARCHAR (14)    NULL,
    [8.Odbiorca: NIP]            VARCHAR (12)    NULL,
    [8.Odbiorca: Firma]          VARCHAR (35)    NULL,
    [8.Odbiorca: Ulica]          VARCHAR (35)    NULL,
    [8.Odbiorca: Kod pocztowy]   VARCHAR (9)     NULL,
    [8.Odbiorca: Miejscowość]    VARCHAR (35)    NULL,
    [8.Odbiorca: Kraj]           VARCHAR (2)     NULL,
    [31.Opis towaru]             VARCHAR (1000)  NULL,
    [33.Kod CN]                  VARCHAR (8)     NULL,
    [37.Procedura]               VARCHAR (4)     NULL,
    [Marka]                      VARCHAR (3)     NULL,
    [Nr nadwozia]                VARCHAR (35)    NULL,
    [Rok produkcji]              INT             NULL,
    [Kraj pochodzenia]           VARCHAR (2)     NULL,
    [38.Masa netto kg]           DECIMAL (14, 3) NULL,
    [47. CŁO Typ]                VARCHAR (3)     NULL,
    [47. CŁO Podstawa opłaty]    DECIMAL (17, 2) NULL,
    [47. CŁO Stawka]             DECIMAL (7, 2)  NULL,
    [47. CŁO Kwota]              DECIMAL (38, 2) NULL,
    [47. CŁO MP]                 CHAR (1)        NULL,
    [47. AKCYZA Typ]             VARCHAR (3)     NULL,
    [47. AKCYZA Podstawa opłaty] DECIMAL (17, 2) NULL,
    [47. AKCYZA Stawka]          DECIMAL (7, 2)  NULL,
    [47. AKCYZA Kwota]           DECIMAL (38, 2) NULL,
    [47. AKCYZA MP]              CHAR (1)        NULL,
    [47. VAT Typ]                VARCHAR (3)     NULL,
    [47. VAT Podstawa opłaty]    DECIMAL (17, 2) NULL,
    [47. VAT Stawka]             DECIMAL (7, 2)  NULL,
    [47. VAT Kwota]              DECIMAL (38, 2) NULL,
    [47. VAT MP]                 CHAR (1)        NULL,
    [47. INNY Typ]               VARCHAR (3)     NULL,
    [47. INNY Podstawa opłaty]   DECIMAL (17, 2) NULL,
    [47. INNY Stawka]            DECIMAL (7, 2)  NULL,
    [47. INNY Kwota]             DECIMAL (38, 2) NULL,
    [47. INNY MP]                CHAR (1)        NULL
);

