CREATE TABLE [MF\CSCI].[MW_73_EXT] (
    [Data przyjęcia zgłoszenia]                 CHAR (10)       NULL,
    [Status]                                    NCHAR (1)       NULL,
    [Numer MRN]                                 NVARCHAR (35)   NULL,
    [Data przyjęcia w UC Wywozu]                CHAR (10)       NULL,
    [Data zwolnienia w UC Wywozu]               CHAR (10)       NULL,
    [UC Wywozu]                                 NVARCHAR (8)    NULL,
    [Deklarowany UC Wyprowadzenia]              NVARCHAR (8)    NULL,
    [Obsługujący UC Wyprowadzenia]              NVARCHAR (8)    NULL,
    [Obsługujacy UC Wyprowadzenia zmieniony na] NVARCHAR (8)    NULL,
    [Kod kontroli w UC Wywozu]                  NVARCHAR (2)    NULL,
    [Liczba zamknięć celnych]                   INT             NULL,
    [Kod kontroli w UC Wyprowadzenia]           NVARCHAR (2)    NULL,
    [Stan zamknięć celnych w UC Wyprowadzenia]  TINYINT         NULL,
    [Kontenery]                                 TINYINT         NULL,
    [Masa brutto (kg)]                          NUMERIC (18, 3) NULL,
    [Masa brutto na granicy (kg)]               NUMERIC (18, 3) NULL,
    [Termin_dotarcia_do_UWA]                    CHAR (10)       NULL,
    [Przedstawiający: Firma]                    NVARCHAR (105)  NULL,
    [Przedstawiający: Adres]                    NVARCHAR (105)  NULL,
    [Przedstawiający: Miejscowość]              NVARCHAR (105)  NULL,
    [Przedstawiający: Kod pocztowy]             NVARCHAR (9)    NULL,
    [Przedstawiający: Kraj]                     NVARCHAR (2)    NULL,
    [Przedstawiający: NIP]                      NVARCHAR (17)   NULL,
    [Nadawca: Firma]                            NVARCHAR (105)  NULL,
    [Nadawca: Adres]                            NVARCHAR (105)  NULL,
    [Nadawca: Miejscowość]                      NVARCHAR (105)  NULL,
    [Nadawca: Kod pocztowy]                     NVARCHAR (9)    NULL,
    [Nadawca: Kraj]                             NVARCHAR (2)    NULL,
    [Nadawca: NIP]                              NVARCHAR (17)   NULL,
    [Odbiorca: Firma]                           NVARCHAR (105)  NULL,
    [Odbiorca: Adres]                           NVARCHAR (105)  NULL,
    [Odbiorca: Miejscowość]                     NVARCHAR (105)  NULL,
    [Odbiorca: Kod pocztowy]                    NVARCHAR (9)    NULL,
    [Odbiorca: Kraj]                            NVARCHAR (2)    NULL,
    [Odbiorca: NIP]                             NVARCHAR (17)   NULL,
    [Znaki śr. transp. wewnętrznego]            NVARCHAR (765)  NULL,
    [Znaki śr. transp. na granicy]              NVARCHAR (255)  NULL,
    [Nr pozycji]                                INT             NULL,
    [Kraj wysyłki]                              NVARCHAR (2)    NULL,
    [Kraj przeznaczenia]                        NVARCHAR (2)    NULL,
    [Opis towaru]                               NVARCHAR (840)  NULL,
    [Kod towaru]                                NVARCHAR (22)   NULL,
    [Kod CN]                                    NVARCHAR (8)    NULL,
    [Masa brutto pozycji w kg]                  NUMERIC (18, 3) NULL,
    [Masa brutto pozycji na granicy w kg]       NUMERIC (18, 3) NULL,
    [Masa netto pozycji w kg]                   NUMERIC (18, 3) NULL,
    [Masa netto pozycji na granicy w kg]        NUMERIC (18, 3) NULL,
    [Wartość statystyczna]                      NUMERIC (17, 2) NULL,
    [Waluta wartości statystycznej]             NVARCHAR (3)    NULL
);

