CREATE TABLE [MF\CSCI].[MW_SG_73_celina] (
    [Data przyjęcia]            CHAR (10)       NULL,
    [Nr zgłoszenia]             VARCHAR (40)    NULL,
    [Nadawca: REGON]            VARCHAR (14)    NULL,
    [Nadawca: NIP]              VARCHAR (12)    NULL,
    [Nadawca: Firma]            VARCHAR (35)    NULL,
    [Nadawca: Adres]            VARCHAR (35)    NULL,
    [Nadawca: Kod poczt.]       VARCHAR (9)     NULL,
    [Nadawca: Miejscowość]      VARCHAR (35)    NULL,
    [Nadawca: Kraj]             VARCHAR (2)     NULL,
    [Odbiorca: REGON]           VARCHAR (14)    NULL,
    [Odbiorca: NIP]             VARCHAR (12)    NULL,
    [Odbiorca: Firma]           VARCHAR (35)    NULL,
    [Odbiorca: Adres]           VARCHAR (35)    NULL,
    [Odbiorca: Kod poczt]       VARCHAR (9)     NULL,
    [Odbiorca: Miejscowość]     VARCHAR (35)    NULL,
    [Odbiorca: Kraj]            VARCHAR (2)     NULL,
    [Zgłaszający: NIP]          VARCHAR (14)    NULL,
    [Zgłaszający: REGON]        VARCHAR (12)    NULL,
    [Zgłaszajacy: Firma]        VARCHAR (35)    NULL,
    [Zgłaszający: Adres]        VARCHAR (35)    NULL,
    [Zgłaszający: Kod pocztowy] VARCHAR (9)     NULL,
    [Zgłaszający: Miejscowość]  VARCHAR (35)    NULL,
    [Zgłaszający: Kraj]         VARCHAR (2)     NULL,
    [Kraj wysyłki]              VARCHAR (2)     NULL,
    [Kraj przeznaczenia]        VARCHAR (2)     NULL,
    [UC Zgłoszenia]             VARCHAR (8)     NULL,
    [UC Graniczny]              VARCHAR (8)     NULL,
    [UC Przeznaczenia]          VARCHAR (8)     NULL,
    [Nr pozycji]                SMALLINT        NULL,
    [Kod towaru]                VARCHAR (8)     NULL,
    [Opis towaru]               VARCHAR (1000)  NULL,
    [Marka]                     VARCHAR (3)     NULL,
    [VIN]                       VARCHAR (35)    NULL,
    [Rok produkcji]             INT             NULL,
    [Miejsce dostawy]           VARCHAR (35)    NULL,
    [Procedura]                 VARCHAR (4)     NULL,
    [Masa netto]                DECIMAL (14, 3) NULL,
    [Ilość w uz. jm.]           DECIMAL (14, 3) NULL,
    [Wartość statystyczna]      BIGINT          NULL,
    [Rodzaj transp. gran.]      CHAR (1)        NULL,
    [Nr rej. gran]              VARCHAR (27)    NULL,
    [Rodzaj transp. wewn.]      CHAR (1)        NULL,
    [Nr rej. wewn]              VARCHAR (27)    NULL
);

