CREATE TABLE [aimp2].[DSK_Dokument] (
    [IdDok]                                  NUMERIC (19)    NOT NULL,
    [TypDeklaracji]                          NVARCHAR (4)    NULL,
    [PodmiotAEO]                             TINYINT         NOT NULL,
    [EksportDanych]                          NCHAR (1)       NOT NULL,
    [AwaryjnaRejestracja]                    TINYINT         NULL,
    [FlagaDeklaracji]                        NVARCHAR (4)    NULL,
    [PrzyjetaRecznie]                        TINYINT         NULL,
    [MRN]                                    NVARCHAR (35)   NULL,
    [IdEwidencjaPapierowa]                   NVARCHAR (35)   NULL,
    [EmailPodmiotu]                          NVARCHAR (80)   NULL,
    [PlacowkaPodmiotu]                       NVARCHAR (2)    NULL,
    [SegmentacjaZISAR]                       NTEXT           NULL,
    [NumerWlasny]                            NVARCHAR (35)   NULL,
    [PodpisanaCyfrowo]                       TINYINT         NULL,
    [DataPrzyjeciaDeklaracji]                DATETIME2 (3)   NULL,
    [DataRejestracjiDSK]                     DATETIME        NULL,
    [DodatkowyEmail]                         NVARCHAR (70)   NULL,
    [IdDeklaracjiPTW]                        NUMERIC (19)    NULL,
    [MasaBrutto]                             NUMERIC (16, 6) NULL,
    [NumerReferencyjnyPrzesylki]             NVARCHAR (35)   NULL,
    [IdOdbiorcyOsobaFizyczna]                NUMERIC (19)    NULL,
    [IdOsobyFizycznejDoKontaktu]             NUMERIC (19)    NULL,
    [IdPrzedstawicielaOsobyFizycznej]        NUMERIC (19)    NULL,
    [IdSkladajacegoOsobaFizyczna]            NUMERIC (19)    NULL,
    [IdOdbiorcyPodmiotGospodarczy]           NUMERIC (19)    NULL,
    [IdPodmiotuGospodarczegoDoKontaktu]      NUMERIC (19)    NULL,
    [IdPrzedstawicielaPodmiotuGospodarczego] NUMERIC (19)    NULL,
    [IdSkladajacegoPodmiotGospodarczy]       NUMERIC (19)    NULL,
    [KomunikatPodpisanyElektronicznie]       BIT             NOT NULL,
    [IdMRZPTW]                               NVARCHAR (35)   NULL,
    [ReferencjaDoZT]                         BIT             NOT NULL,
    [StatusDeklaracji]                       NVARCHAR (4)    NULL,
    [UrzadCelnyDeklaracji]                   NVARCHAR (8)    NULL,
    [UrzadCelnyDeklaracjiPid]                INT             NULL,
    [UrzadCelnyNadzoru]                      NVARCHAR (8)    NULL,
    [UrzadCelnyNadzoruPid]                   INT             NULL,
    CONSTRAINT [DSK_Dokument_PK] PRIMARY KEY CLUSTERED ([IdDok] ASC)
);

