CREATE TABLE [zab].[Zabezpieczenia] (
    [IdZabezpieczenia]                    INT             NOT NULL,
    [NumerGRN]                            VARCHAR (50)    NULL,
    [TypZabezpieczeniaPid]                INT             NOT NULL,
    [RodzajZabezpieczeniaPid]             INT             NULL,
    [WariantZabezpieczeniaPid]            INT             NULL,
    [IdPodmiotu]                          BIGINT          NULL,
    [DataRejestracji]                     DATETIME        NOT NULL,
    [UrzadZlozeniaZabezpieczeniaPid]      INT             NULL,
    [KwotaZabezpieczenia]                 DECIMAL (19, 2) NULL,
    [KwotaReferencyjna]                   DECIMAL (19, 2) NULL,
    [ProcentKwotyReferencyjnej]           VARCHAR (5)     NULL,
    [WalutaPid]                           INT             NULL,
    [SaldoZabezpieczenia]                 DECIMAL (19, 2) NULL,
    [WazneOd]                             DATETIME        NOT NULL,
    [WazneDo]                             DATETIME        NULL,
    [StatusPid]                           INT             NULL,
    [AkcyzaCzyObcySkladPodatkowy]         BIT             NULL,
    [AkcyzaCzyNabywcaWewnZaplAkcyzaArt78] BIT             NULL,
    [AkcyzaCzyPodatnikOkreslonyArt13Ust3] BIT             NULL,
    [AkcyzaObszarWaznosci]                CHAR (2)        NULL,
    [TranzytCzyNiewazneNaTerenieUE]       BIT             NULL,
    [GryKrotnoscZlozonychZabezpieczen]    INT             NULL,
    [GryLiczbaKasynPunktowSalonow]        INT             NULL,
    [OplataPaliwowa]                      BIT             NULL,
    [WtymNaOplPaliw]                      NUMERIC (19, 2) NULL,
    CONSTRAINT [PK_Zabezpieczenia] PRIMARY KEY CLUSTERED ([IdZabezpieczenia] ASC)
);

