CREATE TABLE [MF\CQMD].[CAT_19_Celina2] (
    [stat]                  CHAR (1)        NULL,
    [numer]                 VARCHAR (40)    NULL,
    [DataPrzyjecia]         VARCHAR (10)    NULL,
    [Nadawca]               VARCHAR (14)    NULL,
    [NIP]                   VARCHAR (12)    NULL,
    [Nazwa]                 VARCHAR (35)    NULL,
    [Ulica]                 VARCHAR (35)    NULL,
    [Kod]                   VARCHAR (9)     NULL,
    [Miejscowosc]           VARCHAR (35)    NULL,
    [Kraj]                  VARCHAR (2)     NULL,
    [Odbiorca]              VARCHAR (14)    NULL,
    [TIN1]                  VARCHAR (12)    NULL,
    [Nazwa1]                VARCHAR (35)    NULL,
    [Ulica1]                VARCHAR (35)    NULL,
    [Kod1]                  VARCHAR (9)     NULL,
    [Miejscowosc1]          VARCHAR (35)    NULL,
    [Kraj1]                 VARCHAR (2)     NULL,
    [Zgłaszający]           VARCHAR (14)    NULL,
    [TIN2]                  VARCHAR (12)    NULL,
    [Nazwa2]                VARCHAR (35)    NULL,
    [Ulica2]                VARCHAR (35)    NULL,
    [Kod2]                  VARCHAR (9)     NULL,
    [Miejscowosc2]          VARCHAR (35)    NULL,
    [Kraj2]                 VARCHAR (2)     NULL,
    [KrajW]                 VARCHAR (2)     NULL,
    [Kraj_przeznaczenia]    VARCHAR (2)     NULL,
    [KodDos]                VARCHAR (3)     NULL,
    [Miejsce_dostawy]       VARCHAR (35)    NULL,
    [Waluta]                VARCHAR (3)     NULL,
    [KursW]                 DECIMAL (10, 4) NULL,
    [WartFak]               DECIMAL (17, 2) NULL,
    [UC_wwozu]              VARCHAR (8)     NULL,
    [Rodz_transp_granica]   CHAR (1)        NULL,
    [Znaki_transp_granica]  VARCHAR (27)    NULL,
    [Kraj_transp_granica]   VARCHAR (2)     NULL,
    [Rodz_transp_wewmetrz]  CHAR (1)        NULL,
    [Znaki_transp_wewnetrz] VARCHAR (27)    NULL,
    [Kraj_transp_wewnetrz]  VARCHAR (2)     NULL,
    [NrPozyc]               SMALLINT        NULL,
    [CN]                    VARCHAR (8)     NULL,
    [Taric]                 VARCHAR (2)     NULL,
    [OpisCN]                VARCHAR (1000)  NULL,
    [Preferencje]           CHAR (3)        NULL,
    [KrajPoch]              VARCHAR (2)     NULL,
    [Proce]                 VARCHAR (4)     NULL,
    [WartoscPozycji]        DECIMAL (17, 2) NULL,
    [MasaNetto]             DECIMAL (14, 3) NULL,
    [Masa_Brutto]           DECIMAL (14, 3) NULL,
    [IloscUzupelniajacaJm]  DECIMAL (14, 3) NULL,
    [WarStat]               BIGINT          NULL,
    [Samochod_Marka]        VARCHAR (3)     NULL,
    [Samochod_NrNadwozia]   VARCHAR (35)    NULL,
    [Samochod_NrSilnika]    VARCHAR (35)    NULL,
    [Samochod_Pojemnosc]    INT             NULL,
    [Samochod_RodzajPaliwa] VARCHAR (2)     NULL,
    [Samochod_RokProdukcji] INT             NULL
);

