CREATE TABLE [MF\CQMD].[cba_34_NCTS] (
    [id]                                             BIGINT          NOT NULL,
    [mrn]                                            NVARCHAR (18)   NULL,
    [data_utworzenia]                                DATETIME        NULL,
    [data_modyfikacji]                               DATETIME        NULL,
    [data_zwolnienia]                                DATETIME        NULL,
    [typ_deklaracji]                                 NVARCHAR (5)    NULL,
    [data_przyjecia]                                 DATETIME        NULL,
    [data_przybycia]                                 DATETIME        NULL,
    [Termin_dostawy]                                 DATETIME        NULL,
    [UC_przybycia]                                   NVARCHAR (35)   NULL,
    [uc_wyjscia]                                     NVARCHAR (8)    NULL,
    [UC_przeznaczenia_przybycia]                     NVARCHAR (8)    NULL,
    [uc_przeznaczenia_deklarowany]                   NVARCHAR (8)    NULL,
    [kraj_wysylki]                                   NVARCHAR (2)    NULL,
    [kraj_przeznaczenia]                             NVARCHAR (2)    NULL,
    [nadawca_tin]                                    NVARCHAR (17)   NULL,
    [nadawca_nazwa]                                  NVARCHAR (35)   NULL,
    [nadawca_ulica_numer]                            NVARCHAR (100)  NULL,
    [nadawca_kod_pocztowy]                           NVARCHAR (9)    NULL,
    [nadawca_miejscowosc]                            NVARCHAR (52)   NULL,
    [nadawca_kraj]                                   NVARCHAR (2)    NULL,
    [nadawca_TIN_poz]                                NVARCHAR (17)   NULL,
    [nadawca_nazwa_poz]                              NVARCHAR (35)   NULL,
    [nadawca_ulica_nr_poz]                           NVARCHAR (35)   NULL,
    [nadawca_kod_pocztowy_poz]                       NVARCHAR (9)    NULL,
    [nadawca_miescowosc_poz]                         NVARCHAR (35)   NULL,
    [nadawca_kraj_poz]                               NVARCHAR (2)    NULL,
    [odbiorca_tin]                                   NVARCHAR (17)   NULL,
    [odbiorca_nazwa]                                 NVARCHAR (35)   NULL,
    [odbiorca_ulica_numer]                           NVARCHAR (100)  NULL,
    [odbiorca_kod_pocztowy]                          NVARCHAR (9)    NULL,
    [odbiorca_miejscowosc]                           NVARCHAR (52)   NULL,
    [odbiorca_kraj]                                  NVARCHAR (2)    NULL,
    [odbiorca_tin_poz]                               NVARCHAR (17)   NULL,
    [odbiorca_nazwa_poz]                             NVARCHAR (35)   NULL,
    [odbiorca_ulica_nr_poz]                          NVARCHAR (35)   NULL,
    [odbiorca_kod_pocztowy_poz]                      NVARCHAR (9)    NULL,
    [odbiorca_miejscowosc_poz]                       NVARCHAR (35)   NULL,
    [odbiorca_kraj_poz]                              NVARCHAR (2)    NULL,
    [glowny_zobowiazany_tin]                         NVARCHAR (17)   NULL,
    [glowny_zobowiazany_nazwa]                       NVARCHAR (35)   NULL,
    [glowny_zobowiazany_ulica_numer]                 NVARCHAR (100)  NULL,
    [glowny_zobowiazany_kod_pocztowy]                NVARCHAR (9)    NULL,
    [glowny_zobowiazany_miejscowosc]                 NVARCHAR (52)   NULL,
    [glowny_zobowiazany_kraj]                        NVARCHAR (2)    NULL,
    [przedstawiajacy_tin]                            NVARCHAR (17)   NULL,
    [przedstawiajacy_nazwa]                          NVARCHAR (35)   NULL,
    [przedstawiajacy_ulica_numer]                    NVARCHAR (100)  NULL,
    [przedstawiajacy_kod_pocztowy]                   NVARCHAR (9)    NULL,
    [przedstawiajacy_miejscowosc]                    NVARCHAR (52)   NULL,
    [przedstawiajacy_kraj]                           NVARCHAR (2)    NULL,
    [bezpieczenstwo_przewoznik_tin]                  NVARCHAR (17)   NULL,
    [bezpieczenstwo_przewoznik_nazwa]                NVARCHAR (35)   NULL,
    [bezpieczenstwo_przewoznik_ulica_numer]          NVARCHAR (100)  NULL,
    [bezpieczenstwo_przewoznik_kod_pocztowy]         NVARCHAR (9)    NULL,
    [bezpieczenstwo_przewoznik_miejscowosc]          NVARCHAR (52)   NULL,
    [bezpieczenstwo_przewoznik_kraj]                 NVARCHAR (2)    NULL,
    [bezpieczenstwo_nadawca_tin]                     NVARCHAR (17)   NULL,
    [bezpieczenstwo_nadawca_nazwa]                   NVARCHAR (35)   NULL,
    [bezpieczenstwo_nadawca_ulica_numer]             NVARCHAR (100)  NULL,
    [bezpieczenstwo_nadawca_kod_pocztowy]            NVARCHAR (9)    NULL,
    [bezpieczenstwo_nadawca_miejscowosc]             NVARCHAR (52)   NULL,
    [bezpieczenstwo_nadawca_kraj]                    NVARCHAR (2)    NULL,
    [bezpieczenstwo_odbiorca_tin]                    NVARCHAR (17)   NULL,
    [bezpieczenstwo_odbiorca_nazwa]                  NVARCHAR (35)   NULL,
    [bezpieczenstwo_odbiorca_ulica_numer]            NVARCHAR (100)  NULL,
    [bezpieczenstwo_odbiorca_kod_pocztowy]           NVARCHAR (9)    NULL,
    [bezpieczenstwo_odbiorca_miejscowosc]            NVARCHAR (52)   NULL,
    [bezpieczenstwo_odbiorca_kraj]                   NVARCHAR (2)    NULL,
    [przedstawiajacy_przedstawiciel_tin]             NVARCHAR (17)   NULL,
    [glowny_zobowiazany_przedstawiciel_tin]          NVARCHAR (17)   NULL,
    [glowny_zobowiazany_przedstawiciel_nazwa]        NVARCHAR (35)   NULL,
    [glowny_zobowiazany_przedstawiciel_ulica_numer]  NVARCHAR (100)  NULL,
    [glowny_zobowiazany_przedstawiciel_kod_pocztowy] NVARCHAR (9)    NULL,
    [glowny_zobowiazany_przedstawiciel_miejscowosc]  NVARCHAR (52)   NULL,
    [glowny_zobowiazany_przedstawiciel_kraj]         NVARCHAR (2)    NULL,
    [transport_rodzaj]                               NVARCHAR (2)    NULL,
    [transport_znaki]                                NVARCHAR (27)   NULL,
    [transport_kraj]                                 NVARCHAR (2)    NULL,
    [transport_na_granicy_rodzaj]                    NVARCHAR (2)    NULL,
    [transport_na_granicy_znaki]                     NVARCHAR (27)   NULL,
    [transport_na_granicy_kraj]                      NVARCHAR (2)    NULL,
    [poz_id]                                         INT             NULL,
    [kod_towarowy]                                   NVARCHAR (8)    NULL,
    [opis]                                           NVARCHAR (280)  NULL,
    [masa_brutto]                                    NUMERIC (14, 3) NULL,
    [masa_netto]                                     NUMERIC (14, 3) NULL,
    [RodzOpak]                                       NVARCHAR (3)    NULL,
    [Num_kon]                                        NVARCHAR (42)   NULL,
    [Num_kon2]                                       NVARCHAR (17)   NULL,
    [rodzaj]                                         NVARCHAR (1)    NULL,
    [grn]                                            NVARCHAR (24)   NULL,
    [nr]                                             NVARCHAR (35)   NULL,
    [kwota]                                          NUMERIC (15, 2) NULL,
    [waluta]                                         NVARCHAR (3)    NULL,
    [kwota_pln]                                      NUMERIC (15, 2) NULL,
    [kwota_euro]                                     NUMERIC (15, 2) NULL,
    [wyniki_kontroli_uc_przeznaczenia]               NVARCHAR (2)    NULL,
    [wyniki_kontroli_uc_wyjścia]                     NVARCHAR (2)    NULL,
    [status_uc_przeznaczenia]                        NVARCHAR (8)    NULL,
    [status_uc_wyjscia]                              NVARCHAR (8)    NULL
);

