CREATE TABLE [ais2].[ICS_OPER] (
    [ID]        NUMERIC (19)    NOT NULL,
    [ANNO]      NVARCHAR (4000) NULL,
    [CODE]      VARCHAR (4)     NULL,
    [OPER]      VARCHAR (40)    NULL,
    [TIME]      DATETIME2 (3)   NULL,
    [DECL_ID]   NUMERIC (19)    NULL,
    [ANNO_KIND] NVARCHAR (20)   NULL,
    CONSTRAINT [ICS_OPER$ICS_OPER_11033399641] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2]
);

