CREATE TABLE [ais2].[ICS_MESS_KANAL] (
    [ID]      NUMERIC (19) NOT NULL,
    [MESS_ID] NUMERIC (19) NOT NULL,
    [KTYP]    VARCHAR (2)  NOT NULL,
    [KCHOICE] VARCHAR (4)  NOT NULL,
    [VAL]     VARCHAR (70) NOT NULL,
    [VAL_ADD] VARCHAR (70) NULL,
    CONSTRAINT [ICS_MESS_KANAL$ICS_MESS_KANAL_3513372851] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_MESS_KANAL$FK4405DDEFD605A773] FOREIGN KEY ([MESS_ID]) REFERENCES [ais2].[ICS_MESS] ([ID])
);

