CREATE TABLE [ais2].[ICS_BALANCE_REQ] (
    [ID]      NUMERIC (19)  NOT NULL,
    [CREATOR] VARCHAR (50)  NULL,
    [MRN]     VARCHAR (255) NULL,
    [STATUS]  VARCHAR (12)  NOT NULL,
    CONSTRAINT [ICS_BALANCE_REQ$ICS_BALANC_2553369431] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2]
);

