CREATE TABLE [ais2].[ICS_ENS_ITEM_CONT] (
    [ID]          NUMERIC (19)  NOT NULL,
    [NUMBER]      VARCHAR (255) NULL,
    [STATE_BR]    VARCHAR (4)   NULL,
    [ENS_ITEM_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_ITEM_CONT$ICS_ENS_IT_6073381971] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_ENS_ITEM_CONT$FKB41A9863F78C4AEB] FOREIGN KEY ([ENS_ITEM_ID]) REFERENCES [ais2].[ICS_ENS_ITEMS] ([ID])
);

