CREATE TABLE [ais2].[ICS_ENS_ITEM_PACK] (
    [ID]               NUMERIC (19)  NOT NULL,
    [ITEM_COUNT]       INT           NULL,
    [ITEM_COUNT_BR]    INT           NULL,
    [PACK_KIND]        VARCHAR (2)   NULL,
    [PACK_KIND_BR]     VARCHAR (2)   NULL,
    [PACK_MARKS]       VARCHAR (140) NULL,
    [PACK_MARKS_BR]    VARCHAR (140) NULL,
    [PACKAGE_COUNT]    INT           NULL,
    [PACKAGE_COUNT_BR] INT           NULL,
    [STATE_BR]         VARCHAR (4)   NULL,
    [ENS_ITEM_ID]      NUMERIC (19)  NOT NULL,
    CONSTRAINT [PK_ICS_ENS_ITEM_PACK] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_ENS_ITEM_PACK$FKB4204B4AF78C4AEB] FOREIGN KEY ([ENS_ITEM_ID]) REFERENCES [ais2].[ICS_ENS_ITEMS] ([ID])
);

