CREATE TABLE [ais2].[ICS_ENS_ITI] (
    [ID]      NUMERIC (19) NOT NULL,
    [COUNTRY] VARCHAR (2)  NULL,
    [ENS_ID]  NUMERIC (19) NULL,
    CONSTRAINT [ICS_ENS_ITI$ICS_ENS_IT_7353386531] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_ENS_ITI$FKCF151BC33A1257D6] FOREIGN KEY ([ENS_ID]) REFERENCES [ais2].[ICS_ENS] ([ID])
);

