CREATE TABLE [ais2].[ICS_ENS_SPEC_MENT] (
    [ID]          NUMERIC (19) NOT NULL,
    [CODE]        VARCHAR (5)  NULL,
    [TEXT]        VARCHAR (35) NULL,
    [ENS_ITEM_ID] NUMERIC (19) NULL,
    CONSTRAINT [ICS_ENS_SPEC_MENT$ICS_ENS_SP_8313389951] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_ENS_SPEC_MENT$FKCE362AE7F78C4AEB] FOREIGN KEY ([ENS_ITEM_ID]) REFERENCES [ais2].[ICS_ENS_ITEMS] ([ID])
);

