CREATE TABLE [ais2].[ICS_DIRT_CHANGE] (
    [ID]            NUMERIC (19)   NOT NULL,
    [DIRT_ID]       NUMERIC (19)   NULL,
    [AFFECTS]       VARCHAR (30)   NULL,
    [AFTER]         VARCHAR (100)  NULL,
    [JUSTIFICATION] VARCHAR (1024) NULL,
    [INITIAL_VALUE] VARCHAR (100)  NULL,
    CONSTRAINT [ICS_DIRT_CHANGE$PK_ICS_DIRT_CHANGE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_DIRT_CHANGE$FK_ICS_DIRT_CHANGE_ICS_DIRT] FOREIGN KEY ([DIRT_ID]) REFERENCES [ais2].[ICS_DIRT] ([ID])
);

