CREATE TABLE [ais2].[ICS_ENS_ITEM_TRANS] (
    [ID]          NUMERIC (19)  NOT NULL,
    [COMM_BR]     VARCHAR (140) NULL,
    [NATION]      VARCHAR (2)   NULL,
    [NATION_BR]   VARCHAR (2)   NULL,
    [SINGS]       VARCHAR (31)  NULL,
    [STATE_BR]    VARCHAR (4)   NULL,
    [TAB_TYPE]    VARCHAR (2)   NULL,
    [ENS_ITEM_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_ITEM_TRANS$ICS_ENS_IT_7033385391] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_ENS_ITEM_TRANS$FKD0292F77F78C4AEB] FOREIGN KEY ([ENS_ITEM_ID]) REFERENCES [ais2].[ICS_ENS_ITEMS] ([ID])
);

