CREATE TABLE [ais2].[ICS_DECL_PARAM] (
    [id]       NUMERIC (19) NOT NULL,
    [decl_id]  NUMERIC (19) NOT NULL,
    [key_name] VARCHAR (50) NOT NULL,
    [value]    VARCHAR (70) NOT NULL,
    CONSTRAINT [ICS_DECL_PARAM$ICS_DECL_PARAM_3513372851] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_AIS2],
    CONSTRAINT [FK_ICS_DECL_PARAM$FK4405DDEFD605A773] FOREIGN KEY ([decl_id]) REFERENCES [ais2].[ICS_DECL] ([ID])
);

