CREATE TABLE [ais2].[ICS_ENS_PROD_DOCU] (
    [ID]          NUMERIC (19)  NOT NULL,
    [CODE]        VARCHAR (4)   NULL,
    [COMM_BR]     VARCHAR (140) NULL,
    [NUMB]        NVARCHAR (35) NULL,
    [STATE_BR]    INT           NULL,
    [ENS_ITEM_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_PROD_DOCU$ICS_ENS_PR_7673387671] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_ENS_PROD_DOCU$FKF3DA6DAAF78C4AEB] FOREIGN KEY ([ENS_ITEM_ID]) REFERENCES [ais2].[ICS_ENS_ITEMS] ([ID])
);

