CREATE TABLE [ais2].[ICS_BALANCE_REQ_POS] (
    [ID]              NUMERIC (19)    NOT NULL,
    [GROSS_MASS]      NUMERIC (14, 3) NULL,
    [PACKAGES]        INT             NULL,
    [POSITION_NUMBER] INT             NULL,
    [STATUS]          VARCHAR (20)    NULL,
    [ENS_ITEM_ID]     NUMERIC (19)    NULL,
    [REQUEST_ID]      NUMERIC (19)    NULL,
    CONSTRAINT [ICS_BALANCE_REQ_POS$ICS_BALANC_2873370571] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_BALANCE_REQ_POS$FK76E2B6AA718047B1] FOREIGN KEY ([REQUEST_ID]) REFERENCES [ais2].[ICS_BALANCE_REQ] ([ID]),
    CONSTRAINT [ICS_BALANCE_REQ_POS$FK76E2B6AAF78C4AEB] FOREIGN KEY ([ENS_ITEM_ID]) REFERENCES [ais2].[ICS_ENS_ITEMS] ([ID])
);

