CREATE TABLE [ais2].[ICS_DIRT_INTR] (
    [ID]      NUMERIC (19) NOT NULL,
    [CODE]    VARCHAR (4)  NULL,
    [DIRT_ID] NUMERIC (19) NULL,
    CONSTRAINT [ICS_DIRT_INTR$PK_ICS_DIRT_INTR] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_DIRT_INTR$FK_ICS_DIRT_INTR_ICS_DIRT] FOREIGN KEY ([DIRT_ID]) REFERENCES [ais2].[ICS_DIRT] ([ID])
);

