CREATE TABLE [ais2].[ICS_ENS_SEALS] (
    [ID]     NUMERIC (19)  NOT NULL,
    [NUMB]   NVARCHAR (20) NULL,
    [ENS_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_ENS_SEALS$ICS_ENS_SE_7993388811] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_ENS_SEALS$FK5EC33BFB3A1257D6] FOREIGN KEY ([ENS_ID]) REFERENCES [ais2].[ICS_ENS] ([ID])
);

