CREATE TABLE [ais2].[ICS_GAN_ZCP_CUST_DATA_DETL] (
    [ID]                   NUMERIC (19) NOT NULL,
    [GAN_ZCP_CUST_DATA_ID] NUMERIC (19) NOT NULL,
    [POSITION_NO]          NUMERIC (5)  NOT NULL,
    CONSTRAINT [ICS_GAN_ZCP_CUST_DATA_DETL$ICS_GAN_ZC_6740984111] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_GAN_ZCP_CUST_DATA_DETL$ICS_GAN_ZC_1018587786] FOREIGN KEY ([GAN_ZCP_CUST_DATA_ID]) REFERENCES [ais2].[ICS_GAN_ZCP_CUST_DATA] ([ID])
);

