CREATE TABLE [ais2].[ICS_CONTROL_NOTIFICATION_REQ_DOC] (
    [ID]              NUMERIC (19) NOT NULL,
    [NOTIFICATION_ID] NUMERIC (19) NOT NULL,
    [DOC_CODE]        VARCHAR (4)  NULL,
    [DOC_NUMBER]      VARCHAR (35) NULL,
    [DOC_NOTES]       VARCHAR (35) NULL,
    CONSTRAINT [ICS_CONTROL_NOTIFICATION_REQ_DOC$PK_ICS_CONTROL_NOTIFICATION_REQ_DOC] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_CONTROL_NOTIFICATION_REQ_DOC$FK_ICS_CONTROL_NOTIFICATION_REQ_DOC__ICS_CONTROL_NOTIFICATION] FOREIGN KEY ([NOTIFICATION_ID]) REFERENCES [ais2].[ICS_CONTROL_NOTIFICATION] ([ID])
);

