CREATE TABLE [ais2].[ICS_DIRT] (
    [ID]                          NUMERIC (19)   NOT NULL,
    [ADDRESSEE]                   VARCHAR (40)   NULL,
    [AUTHOR]                      VARCHAR (255)  NULL,
    [DIR_FOR_NEXT_CO]             VARCHAR (500)  NULL,
    [DIR_DISPATCHER]              VARCHAR (100)  NULL,
    [INFORMATION]                 VARCHAR (200)  NULL,
    [WARUE]                       VARCHAR (5)    NULL,
    [WAR1]                        VARCHAR (1)    NULL,
    [WAR234]                      VARCHAR (3)    NULL,
    [WAR5]                        VARCHAR (1)    NULL,
    [COMMENT]                     NTEXT          NULL,
    [MRN]                         VARCHAR (18)   NULL,
    [ALGORITHM_NUMBER]            VARCHAR (30)   NULL,
    [OBJECTION_NUMBER]            VARCHAR (30)   NULL,
    [RISK_AREA]                   VARCHAR (12)   NULL,
    [samples]                     TINYINT        NULL,
    [PROFILE]                     VARCHAR (24)   NULL,
    [STATUS]                      VARCHAR (4)    NOT NULL,
    [TEXT]                        NTEXT          NULL,
    [CONTROL_TYPE]                CHAR (1)       NULL,
    [POINTER]                     VARCHAR (255)  NULL,
    [RESULT]                      VARCHAR (1024) NULL,
    [SOURCE]                      VARCHAR (1024) NULL,
    [DECL_ID]                     NUMERIC (19)   NOT NULL,
    [ITEM_TYPE]                   CHAR (3)       NULL,
    [REALISATION_DATE]            DATETIME2 (3)  NULL,
    [ID_VERIFICATION_ITEM]        NUMERIC (19)   NULL,
    [DIRTYPE]                     CHAR (3)       NULL,
    [INTRO]                       INT            NULL,
    [ORIGIN]                      VARCHAR (40)   NULL,
    [VERIFICATION_REQUIRED]       TINYINT        NULL,
    [MODIFIED_BY]                 VARCHAR (255)  NULL,
    [RISK_ANALYSIS_RESULT]        VARCHAR (1)    NULL,
    [RESERVATION_NUMBER]          VARCHAR (30)   NULL,
    [INFORMATION_FOR_DISPATCHER]  VARCHAR (200)  NULL,
    [AGRIM_DISCREPANCY]           BIT            NOT NULL,
    [OFFICIAL_ANNOTATION]         VARCHAR (1024) NULL,
    [ADD_TEXT]                    TEXT           NULL,
    [forced_veri]                 BIT            NOT NULL,
    [correct_calc_tsk]            TINYINT        NULL,
    [zisar_source]                VARCHAR (20)   NULL,
    [zisar_id]                    VARCHAR (100)  NULL,
    [ENTITY_ROLE]                 VARCHAR (3)    NULL,
    [ADDRESSED_TO_CUSTOMS_OFFICE] BIT            NOT NULL,
    CONSTRAINT [ICS_DIRT$PK_ICS_DIRT] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_DIRT$FK_ICS_DIRT_ICS_DECL] FOREIGN KEY ([DECL_ID]) REFERENCES [ais2].[ICS_DECL] ([ID])
) TEXTIMAGE_ON [FG_AIS2];

