CREATE TABLE [ais2].[ICS_DIRT_POINTER] (
    [ID]      NUMERIC (19)   NOT NULL,
    [DIRT_ID] NUMERIC (19)   NULL,
    [NAME]    VARCHAR (1024) NULL,
    [TYPE]    INT            NULL,
    [VALUE]   VARCHAR (1024) NULL,
    CONSTRAINT [ICS_DIRT_POINTER$PK_ICS_DIRT_POINTER] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_DIRT_POINTER$FK_ICS_DIRT_POINTER_ICS_DIRT] FOREIGN KEY ([DIRT_ID]) REFERENCES [ais2].[ICS_DIRT] ([ID])
);

