CREATE TABLE [ais2].[ICS_CANCEL_BALANCE_REQ] (
    [ID]                 NUMERIC (19)  NOT NULL,
    [REQUEST_ID]         VARCHAR (255) NULL,
    [STATUS]             VARCHAR (255) NULL,
    [BALANCE_REQUEST_ID] NUMERIC (19)  NULL,
    CONSTRAINT [ICS_CANCEL_BALANCE_REQ$ICS_CANCEL_3193371711] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2],
    CONSTRAINT [ICS_CANCEL_BALANCE_REQ$FK2D3181BCB4F8CF4] FOREIGN KEY ([BALANCE_REQUEST_ID]) REFERENCES [ais2].[ICS_BALANCE_REQ] ([ID])
);

