CREATE TABLE [ais2].[ICS_CONTROL_NOTIFICATION] (
    [ID]           NUMERIC (19)  NOT NULL,
    [DECL_ID]      NUMERIC (19)  NOT NULL,
    [CONTROL_DATE] DATETIME2 (3) NULL,
    [COMMENTS]     VARCHAR (255) NULL,
    [DTYPE]        VARCHAR (31)  NULL,
    CONSTRAINT [ICS_CONTROL_NOTIFICATION$PK_ICS_CONTROL_NOTIFICATION] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_AIS2]
);

