CREATE TABLE [ncts2].[ar_obsluga_wskazan_kontroli] (
    [id]                                         BIGINT          NOT NULL,
    [ar_dokument_id]                             BIGINT          NULL,
    [zrodlo]                                     NVARCHAR (36)   NULL,
    [nr_algorytmu]                               NVARCHAR (30)   NULL,
    [autor]                                      NVARCHAR (30)   NULL,
    [war1]                                       NVARCHAR (36)   NULL,
    [war1_so]                                    NVARCHAR (36)   NULL,
    [war24]                                      NVARCHAR (36)   NULL,
    [war24_so]                                   NVARCHAR (36)   NULL,
    [war5]                                       NVARCHAR (36)   NULL,
    [war5_so]                                    NVARCHAR (36)   NULL,
    [zmiana_war_uzasadnienie_so]                 NVARCHAR (200)  NULL,
    [obszar_ryzyka]                              NVARCHAR (36)   NULL,
    [zmiana_metod_kontroli_uzasadnienie_so]      NVARCHAR (200)  NULL,
    [tresc_dyrektywy]                            NVARCHAR (350)  NULL,
    [informacja_dla_dyspozytora]                 NVARCHAR (200)  NULL,
    [decyzja_dyspozytora_so]                     SMALLINT        NULL,
    [odstapienie_od_kontroli_uzasadnienie_so]    NVARCHAR (100)  NULL,
    [adresaci_dyrektywy_so]                      NVARCHAR (1000) NULL,
    [zalecenie_dyspozytora_so]                   NVARCHAR (350)  NULL,
    [dyrektywa_dla_kolejnego_uc_wprowadzenia_so] NVARCHAR (500)  NULL,
    [zakres_przebieg_kontroli_so]                NVARCHAR (200)  NULL,
    [wynik_kontroli_so]                          NVARCHAR (36)   NULL,
    [metoda_analizy]                             NVARCHAR (1)    NULL,
    [czy_widoczna_w_innych_uc]                   NVARCHAR (1)    NOT NULL,
    [numer_profilu_algorytmu]                    INT             NULL,
    [numer_zastrzezenia]                         INT             NULL,
    [rola_wystepowania_podmiotu]                 NVARCHAR (36)   NULL,
    [poziom_ryzyka]                              NVARCHAR (1)    NULL,
    [status]                                     NVARCHAR (1)    NULL,
    [obsluzyl_uzytkownik_id]                     BIGINT          NULL,
    [zarejestrowal_wynik_kontroli_uzytkownik_id] BIGINT          NULL,
    [kontroler_obszar_ryzyka]                    NVARCHAR (50)   NULL,
    [kontroler_powod_zmiany_metody]              NVARCHAR (200)  NULL,
    [dyspozytor_powod_zmiany_metody]             NVARCHAR (200)  NULL,
    [kontroler_wynik_kontroli]                   NVARCHAR (1)    NULL,
    [kontroler_przebieg_kontroli]                NVARCHAR (1000) NULL,
    [segment]                                    NVARCHAR (36)   NULL,
    [czas_zarejestrowania_wyniku]                DATETIME        NULL,
    [czas_obslugi]                               DATETIME        NULL,
    [dyspozycja]                                 NVARCHAR (1000) NULL,
    CONSTRAINT [ar_obsluga_wskazan_kontroli_pk] PRIMARY KEY CLUSTERED ([id] ASC)
);

