CREATE TABLE [ncts2].[uwagi_rozladunkowe] (
    [id]                                           BIGINT          NOT NULL,
    [operacja_tranzytowa_id]                       BIGINT          NULL,
    [iteracja]                                     BIGINT          NULL,
    [data_rozladunku]                              DATETIME        NULL,
    [wynik_rozladunku_zakonczenie]                 BIT             NULL,
    [wynik_rozladunku_zgodny]                      BIT             NULL,
    [wynik_rozladunku_zamkniecia_prawidlowe]       BIT             NULL,
    [podmiot_w_miejscu_przeznaczenia_nazwa]        NVARCHAR (35)   NULL,
    [podmiot_w_miejscu_przeznaczenia_ulica_numer]  NVARCHAR (35)   NULL,
    [podmiot_w_miejscu_przeznaczenia_kod_pocztowy] NVARCHAR (9)    NULL,
    [podmiot_w_miejscu_przeznaczenia_miejscowosc]  NVARCHAR (35)   NULL,
    [podmiot_w_miejscu_przeznaczenia_kraj]         NVARCHAR (2)    NULL,
    [podmiot_w_miejscu_przeznaczenia_tin]          NVARCHAR (17)   NULL,
    [uwagi_rozladunkowe]                           NVARCHAR (MAX)  NULL,
    [karnet_tir_nie_dotyczy]                       BIT             NULL,
    [karnet_tir_numer_strony]                      NVARCHAR (2)    NULL,
    [karnet_tir_typ_rozladunku]                    NVARCHAR (1)    NULL,
    [karnet_tir_numer_rozladunku]                  NVARCHAR (2)    NULL,
    [zwolnienie]                                   NVARCHAR (1)    NULL,
    [zamkniecia_celne_ilosc]                       BIGINT          NULL,
    [liczba_pozycji]                               INT             NULL,
    [liczba_opakowan]                              INT             NULL,
    [masa_brutto]                                  NUMERIC (14, 3) NULL,
    [transport_znaki]                              NVARCHAR (27)   NULL,
    [transport_kraj]                               NVARCHAR (2)    NULL,
    [liczba_pozycji_uwagi]                         NVARCHAR (140)  NULL,
    [masa_brutto_uwagi]                            NVARCHAR (140)  NULL,
    [liczba_opakowan_uwagi]                        NVARCHAR (140)  NULL,
    [transport_znaki_uwagi]                        NVARCHAR (140)  NULL,
    [transport_kraj_uwagi]                         NVARCHAR (140)  NULL,
    [data_utworzenia]                              DATETIME        NULL,
    CONSTRAINT [uwagi_rozladunkowe_pk] PRIMARY KEY CLUSTERED ([id] ASC)
);

