CREATE TABLE [ncts2].[wnioski_o_aar] (
    [id]                                   BIGINT        NOT NULL,
    [uc_przedstawienia_wniosku]            NVARCHAR (8)  NULL,
    [status]                               NVARCHAR (12) NULL,
    [mrn]                                  NVARCHAR (18) NULL,
    [zmiana_statusu_data]                  DATETIME      NULL,
    [tin]                                  NVARCHAR (17) NULL,
    [przedstawiajacy_wniosek_nazwa]        NVARCHAR (35) NULL,
    [procedura_uproszczona]                BIT           NULL,
    [komunikat_ie007_id]                   BIGINT        NULL,
    [komunikat_ie002_id]                   BIGINT        NULL,
    [komunikat_ie003_id]                   BIGINT        NULL,
    [przedstawiajacy_wniosek_ulica_numer]  NVARCHAR (35) NULL,
    [przedstawiajacy_wniosek_kod_pocztowy] NVARCHAR (9)  NULL,
    [przedstawiajacy_wniosek_miejscowosc]  NVARCHAR (35) NULL,
    [przedstawiajacy_wniosek_kraj]         NVARCHAR (2)  NULL,
    [przedstawiajacy_wniosek_tin]          NVARCHAR (17) NULL,
    [opis_lokalizacji]                     NVARCHAR (35) NULL,
    [kod_miejsca_uznanego]                 NVARCHAR (17) NULL,
    [miejsce_odpraw_celnych]               NVARCHAR (17) NULL,
    [miejsce_wskazane_w_pozwoleniu]        NVARCHAR (17) NULL,
    [data_powiadomienia]                   DATETIME      NULL,
    [miejsce_powiadomienia]                NVARCHAR (35) NULL,
    [rewizja]                              INT           NULL,
    [data_utworzenia]                      DATETIME      NULL,
    [data_modyfikacji]                     DATETIME      NULL,
    CONSTRAINT [wnioski_o_aar_pk] PRIMARY KEY CLUSTERED ([id] ASC)
);

