CREATE TABLE [zef2].[KPFINSTATEMENTDEF] (
    [FINSTATEMENTDEFSEQID]            NVARCHAR (15)  DEFAULT ('') NOT NULL,
    [DOCUTYPEID]                      NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [XMLINTERVAL]                     INT            DEFAULT ((0)) NOT NULL,
    [XMLTAG]                          NVARCHAR (50)  DEFAULT ('') NOT NULL,
    [XMLDOCUMENTNAME]                 NVARCHAR (40)  DEFAULT ('') NOT NULL,
    [POSTTOACCOUNT]                   INT            DEFAULT ((0)) NOT NULL,
    [POSTTOTRANS]                     INT            DEFAULT ((0)) NOT NULL,
    [POSTINGLEVEL]                    INT            DEFAULT ((0)) NOT NULL,
    [VOUCHERSEQID]                    NVARCHAR (15)  DEFAULT ('') NOT NULL,
    [XMLSUBDOCUMENT]                  INT            DEFAULT ((0)) NOT NULL,
    [CALCPLANONLYNOZERO]              INT            DEFAULT ((0)) NOT NULL,
    [AUTOCREATE]                      INT            DEFAULT ((0)) NOT NULL,
    [DATEFROM]                        DATETIME       DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [BLOCKED]                         INT            DEFAULT ((0)) NOT NULL,
    [FINSTATEMENTDEFVERSIONID]        NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [MANDATORYCLASSIFICATION]         INT            DEFAULT ((0)) NOT NULL,
    [DYNAMICROWS]                     INT            DEFAULT ((0)) NOT NULL,
    [DEFAULTCONSOLIDATED_FK]          BIGINT         DEFAULT ((0)) NOT NULL,
    [DEFAULTAGGR_FK]                  BIGINT         DEFAULT ((0)) NOT NULL,
    [DEFAULTSTATEMENT_FK]             BIGINT         DEFAULT ((0)) NOT NULL,
    [FINSTATEMENTTYPEDEF_FK]          BIGINT         DEFAULT ((0)) NOT NULL,
    [PROJECTNOYES]                    INT            DEFAULT ((0)) NOT NULL,
    [PROGRAMNOYES]                    INT            DEFAULT ((0)) NOT NULL,
    [PARAGRAPHNOYES]                  INT            DEFAULT ((0)) NOT NULL,
    [SUBSECTIONNOYES]                 INT            DEFAULT ((0)) NOT NULL,
    [SECTIONNOYES]                    INT            DEFAULT ((0)) NOT NULL,
    [EMPLOYMENTGROUPNOYES]            INT            DEFAULT ((0)) NOT NULL,
    [FINSTATEMENTTYPE]                INT            DEFAULT ((0)) NOT NULL,
    [PART]                            INT            DEFAULT ((0)) NOT NULL,
    [RECIPIENT]                       NVARCHAR (100) DEFAULT ('') NOT NULL,
    [PROTECTEDDOCUTYPEID]             NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [CHECKCLASSNAME]                  NVARCHAR (40)  DEFAULT ('') NOT NULL,
    [DATAPREPCLASSNAME]               NVARCHAR (40)  DEFAULT ('') NOT NULL,
    [MODIFIEDDATETIME]                DATETIME       DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [MODIFIEDBY]                      NVARCHAR (8)   DEFAULT ('?') NOT NULL,
    [MODIFIEDTRANSACTIONID]           BIGINT         DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]                 DATETIME       DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [CREATEDBY]                       NVARCHAR (8)   DEFAULT ('?') NOT NULL,
    [CREATEDTRANSACTIONID]            BIGINT         DEFAULT ((0)) NOT NULL,
    [RECVERSION]                      INT            DEFAULT ((1)) NOT NULL,
    [PARTITION]                       BIGINT         DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                           BIGINT         NOT NULL,
    [PARTNOYES]                       INT            DEFAULT ((0)) NOT NULL,
    [WORKNOYES]                       INT            DEFAULT ((0)) NOT NULL,
    [DESCNOYES]                       INT            DEFAULT ((0)) NOT NULL,
    [ROWIDNOYES]                      INT            DEFAULT ((0)) NOT NULL,
    [MRDOSIMPORT]                     INT            DEFAULT ((0)) NOT NULL,
    [FINCONSOLIDATIONFIELDIDX]        INT            DEFAULT ((0)) NOT NULL,
    [FINCONSOLIDATIONORGUNITTABLE_FK] BIGINT         DEFAULT ((0)) NOT NULL,
    [REPORTMENUITEMNAME]              NVARCHAR (40)  DEFAULT ('') NOT NULL,
    [REMARKSNOYES]                    INT            NOT NULL,
    [TREZORIMPORTCLASSNAME]           NVARCHAR (40)  NOT NULL,
    CONSTRAINT [I_30636RECID] PRIMARY KEY CLUSTERED ([RECID] ASC) ON [FG_ZEF2],
    CHECK ([RECID]<>(0)),
    CHECK ([RECID]<>(0))
);


GO
ALTER TABLE [zef2].[KPFINSTATEMENTDEF] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);

