CREATE TABLE [zef2].[KPFINSTATEMENTTRANS] (
    [DESCRIPTION]                NVARCHAR (250)   DEFAULT ('') NOT NULL,
    [LINENUM]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE2_]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE3_]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE4_]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE5_]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE6_]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE7_]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE8_]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE9_]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE10_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE11_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE12_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE13_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE14_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE15_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE16_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE17_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE18_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE19_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUE20_]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [MARKER]                     NVARCHAR (8)     DEFAULT ('') NOT NULL,
    [ROWID]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FINSTATEMENTTABLE_FK]       BIGINT           DEFAULT ((0)) NOT NULL,
    [DEFAULTDIMENSION_FK]        BIGINT           DEFAULT ((0)) NOT NULL,
    [DATACLASSIFICATION_FK]      BIGINT           DEFAULT ((0)) NOT NULL,
    [DATACLASSSECTION]           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DATACLASSSUBSECTION]        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DATACLASSPARAGRAPH]         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DATACLASSPROJECTID]         NVARCHAR (18)    DEFAULT ('') NOT NULL,
    [DATACLASSPROGRAMID]         NVARCHAR (18)    DEFAULT ('') NOT NULL,
    [DATACLASSEMPLOYMENTGROUPID] NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [LEDGERDIMENSION_FK]         BIGINT           DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]           DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [MODIFIEDBY]                 NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [MODIFIEDTRANSACTIONID]      BIGINT           DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]            DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [CREATEDBY]                  NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [CREATEDTRANSACTIONID]       BIGINT           DEFAULT ((0)) NOT NULL,
    [RECVERSION]                 INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                  BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                      BIGINT           NOT NULL,
    [DATACLASSWORKID]            NVARCHAR (15)    DEFAULT ('') NOT NULL,
    [DATACLASSPART]              INT              DEFAULT ((0)) NOT NULL,
    [PROGRAMNAMEFORSTATEMENT]    NVARCHAR (200)   DEFAULT ('') NULL,
    [CUSTNAME]                   NVARCHAR (200)   DEFAULT ('') NOT NULL,
    [CUSTADDRES]                 NVARCHAR (250)   DEFAULT ('') NOT NULL,
    [PRZYCZYNYDECYZJIUMORZENIA]  INT              DEFAULT ((0)) NOT NULL,
    [WRITEOFFCAUSE]              INT              DEFAULT ((0)) NOT NULL,
    [TREZORPOSITIONCODE]         NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [TREZORCHAPTERCODE]          NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [DATACLASSPARAGRAPH1]        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [REMARKS]                    NVARCHAR (150)   DEFAULT ('') NOT NULL,
    [DATACLASSQUALEX]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DATACLASSQUALIN]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    CONSTRAINT [I_103092RECID] PRIMARY KEY CLUSTERED ([RECID] ASC) ON [FG_ZEF2],
    CHECK ([RECID]<>(0)),
    CHECK ([RECID]<>(0))
);


GO
ALTER TABLE [zef2].[KPFINSTATEMENTTRANS] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);

