CREATE TABLE [zef2].[KPJOURNALSTATUSTABLE] (
    [STATUSNAME]            NVARCHAR (80) DEFAULT ('') NOT NULL,
    [STATUSNAMEID]          NVARCHAR (10) DEFAULT ('') NOT NULL,
    [STARTSTATUSID]         NVARCHAR (20) DEFAULT ('') NOT NULL,
    [MODIFIEDDATETIME]      DATETIME      DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [MODIFIEDBY]            NVARCHAR (8)  DEFAULT ('?') NOT NULL,
    [MODIFIEDTRANSACTIONID] BIGINT        DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]       DATETIME      DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_CREATEDTIME]       INT           DEFAULT ((0)) NOT NULL,
    [CREATEDBY]             NVARCHAR (8)  DEFAULT ('?') NOT NULL,
    [CREATEDTRANSACTIONID]  BIGINT        DEFAULT ((0)) NOT NULL,
    [RECVERSION]            INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]             BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                 BIGINT        NOT NULL,
    CONSTRAINT [I_30696STATUSIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [STATUSNAMEID] ASC) ON [FG_ZEF2],
    CHECK ([RECID]<>(0)),
    CHECK ([RECID]<>(0))
);


GO
ALTER TABLE [zef2].[KPJOURNALSTATUSTABLE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);

