CREATE TABLE [zef2].[KPORGANIZATIONUNITTABLE] (
    [ORGANIZATIONUNITID]         NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [NAME]                       NVARCHAR (256) DEFAULT ('') NOT NULL,
    [BLOCKED]                    INT            DEFAULT ((0)) NOT NULL,
    [LEVEL1]                     INT            DEFAULT ((0)) NOT NULL,
    [LEVEL2]                     INT            DEFAULT ((0)) NOT NULL,
    [LEVEL3]                     INT            DEFAULT ((0)) NOT NULL,
    [LEVEL4]                     INT            DEFAULT ((0)) NOT NULL,
    [ORGANIZATIONUNITPARENT_FK]  BIGINT         DEFAULT ((0)) NOT NULL,
    [LEVEL5]                     INT            DEFAULT ((0)) NOT NULL,
    [UNITDATAAREAID]             NVARCHAR (4)   DEFAULT ('') NOT NULL,
    [DEPARTMENT_FK]              BIGINT         DEFAULT ((0)) NOT NULL,
    [ENFORCEMENTAUTHORITY]       INT            DEFAULT ((0)) NOT NULL,
    [TREZORID]                   NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [PART]                       INT            DEFAULT ((0)) NOT NULL,
    [TAXAUTHORITY]               INT            DEFAULT ((0)) NOT NULL,
    [LOCATION_FK]                BIGINT         DEFAULT ((0)) NOT NULL,
    [DEL_EMAILINTERESTDECISION]  NVARCHAR (80)  DEFAULT ('') NOT NULL,
    [EMAILIDPAYMENTDEMAND]       NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [DEL_EMAILTW]                NVARCHAR (80)  DEFAULT ('') NOT NULL,
    [USERTW]                     NVARCHAR (80)  DEFAULT ('') NOT NULL,
    [FINSTATEMENTNAME]           NVARCHAR (120) DEFAULT ('') NOT NULL,
    [REGNUM]                     NVARCHAR (15)  DEFAULT ('') NOT NULL,
    [VISIBLEINDIMATTRIBUTEVIEW]  INT            DEFAULT ((0)) NOT NULL,
    [TWNAME]                     NVARCHAR (256) DEFAULT ('') NOT NULL,
    [DEL_EMAILIDDEPOSITSUMAPPL]  NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [DEL_EMAILDEPOSITSUMAPPL]    NVARCHAR (80)  DEFAULT ('') NOT NULL,
    [MODIFIEDDATETIME]           DATETIME       DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [MODIFIEDBY]                 NVARCHAR (8)   DEFAULT ('?') NOT NULL,
    [MODIFIEDTRANSACTIONID]      BIGINT         DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]            DATETIME       DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [CREATEDBY]                  NVARCHAR (8)   DEFAULT ('?') NOT NULL,
    [CREATEDTRANSACTIONID]       BIGINT         DEFAULT ((0)) NOT NULL,
    [RECVERSION]                 INT            DEFAULT ((1)) NOT NULL,
    [PARTITION]                  BIGINT         DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                      BIGINT         NOT NULL,
    [NUMSEQCUST_FK]              BIGINT         DEFAULT ((0)) NOT NULL,
    [CUSTACCOUNT]                NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [VISIBLEINREGULOFPROTECTION] INT            DEFAULT ((0)) NOT NULL,
    [ORGANIZATIONUNITIDSHORT]    NVARCHAR (16)  DEFAULT ('') NOT NULL,
    [ISRECEIVER]                 INT            DEFAULT ((0)) NOT NULL,
    [NAMEFORLIMITS]              NVARCHAR (256) DEFAULT ('') NOT NULL,
    [LOCATIONEA_FK]              BIGINT         DEFAULT ((0)) NOT NULL,
    [TAXTREZORID]                NVARCHAR (10)  NOT NULL,
    [TREZORBUDGETUNIT]           NVARCHAR (10)  NOT NULL,
    CONSTRAINT [I_103064RECID] PRIMARY KEY CLUSTERED ([RECID] ASC) ON [FG_ZEF2],
    CHECK ([RECID]<>(0)),
    CHECK ([RECID]<>(0))
);


GO
ALTER TABLE [zef2].[KPORGANIZATIONUNITTABLE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);

