CREATE TABLE [zef2].[KPPROGRAMTABLE] (
    [DESCRIPTION]               NVARCHAR (320) CONSTRAINT [DF__KPPROGRAM__DESCR__21D6CC45] DEFAULT ('') NOT NULL,
    [NAME]                      NVARCHAR (256) CONSTRAINT [DF__KPPROGRAMT__NAME__22CAF07E] DEFAULT ('') NOT NULL,
    [PROGRAMID]                 NVARCHAR (18)  CONSTRAINT [DF__KPPROGRAM__PROGR__23BF14B7] DEFAULT ('') NOT NULL,
    [BLOCKED]                   INT            CONSTRAINT [DF__KPPROGRAM__BLOCK__24B338F0] DEFAULT ((0)) NOT NULL,
    [FROMDATE]                  DATETIME       CONSTRAINT [DF__KPPROGRAM__FROMD__25A75D29] DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [VISIBLEINDIMATTRIBUTEVIEW] INT            CONSTRAINT [DF__KPPROGRAM__VISIB__269B8162] DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]          DATETIME       CONSTRAINT [DF__KPPROGRAM__MODIF__278FA59B] DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [MODIFIEDBY]                NVARCHAR (8)   CONSTRAINT [DF__KPPROGRAM__MODIF__2883C9D4] DEFAULT ('?') NOT NULL,
    [MODIFIEDTRANSACTIONID]     BIGINT         CONSTRAINT [DF__KPPROGRAM__MODIF__2977EE0D] DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]           DATETIME       CONSTRAINT [DF__KPPROGRAM__CREAT__2A6C1246] DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [CREATEDBY]                 NVARCHAR (8)   CONSTRAINT [DF__KPPROGRAM__CREAT__2B60367F] DEFAULT ('?') NOT NULL,
    [CREATEDTRANSACTIONID]      BIGINT         CONSTRAINT [DF__KPPROGRAM__CREAT__2C545AB8] DEFAULT ((0)) NOT NULL,
    [RECVERSION]                INT            CONSTRAINT [DF__KPPROGRAM__RECVE__2D487EF1] DEFAULT ((1)) NOT NULL,
    [PARTITION]                 BIGINT         CONSTRAINT [DF__KPPROGRAM__PARTI__2E3CA32A] DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                     BIGINT         NOT NULL,
    [PROGRAMGROUPTABLE_FK]      BIGINT         CONSTRAINT [DF__KPPROGRAM__PROGR__2F30C763] DEFAULT ((0)) NOT NULL,
    [NAMEFORSTATEMENT]          NVARCHAR (250) CONSTRAINT [DF__KPPROGRAM__NAMEF__3024EB9C] DEFAULT ('') NOT NULL,
    CONSTRAINT [I_30313RECID] PRIMARY KEY CLUSTERED ([RECID] ASC) ON [FG_ZEF2],
    CONSTRAINT [CK__KPPROGRAM__RECID__4F9D96F5] CHECK ([RECID]<>(0)),
    CONSTRAINT [CK__KPPROGRAM__RECID__73DAF76B] CHECK ([RECID]<>(0))
);


GO
ALTER TABLE [zef2].[KPPROGRAMTABLE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);

