CREATE TABLE [zef2].[Pracownik] (
    [IDPracownika]                   INT             NOT NULL,
    [Login]                          NVARCHAR (50)   NOT NULL,
    [Imie]                           NVARCHAR (50)   NOT NULL,
    [Nazwisko]                       NVARCHAR (50)   NOT NULL,
    [Inicjaly]                       NVARCHAR (5)    NOT NULL,
    [NumerTelefonu]                  NVARCHAR (30)   NOT NULL,
    [NumerFaksu]                     NVARCHAR (30)   NULL,
    [EMail]                          NVARCHAR (255)  NULL,
    [IDKomorki]                      INT             NULL,
    [IDKomorkiZatrudnienia]          INT             NULL,
    [IDStanowiska]                   INT             NULL,
    [IDPrzelozonego]                 INT             NULL,
    [IDPionu]                        INT             NULL,
    [Aktywny]                        BIT             CONSTRAINT [DF_Pracownik_Aktywny] DEFAULT ((0)) NOT NULL,
    [Skaner]                         BIT             DEFAULT ((0)) NULL,
    [FullTextSearch]                 AS              (isnull([Imie]+' ','')+isnull([Nazwisko],'')),
    [ZakresUpowaznieniaDO]           INT             NULL,
    [AkceptacjaPrzezSekretariat]     INT             CONSTRAINT [DF_Pracownik_AkceptacjaPrzezSekretariat] DEFAULT ((0)) NULL,
    [Koszyk]                         NVARCHAR (MAX)  NULL,
    [Archiwista]                     BIT             NULL,
    [AkceptacjaPIN]                  NVARCHAR (512)  NULL,
    [CzyAktAD]                       BIT             NULL,
    [IDJednostkiOrganizacyjnej]      INT             NULL,
    [LiderZespolu]                   BIT             NULL,
    [PrMer]                          BIT             NULL,
    [DataOd]                         DATETIME        NULL,
    [DataDo]                         DATETIME        NULL,
    [IdMetadaneObiektu]              INT             NULL,
    [UrzadMiastoWydaniaDecyzji]      NVARCHAR (200)  NULL,
    [UrzadMiejsceWydaniaDecyzji]     NVARCHAR (200)  NULL,
    [UrzadAdresJednostkaUlica]       NVARCHAR (150)  NULL,
    [UrzadAdresJednostkaKodPocztowy] NVARCHAR (50)   NULL,
    [UrzadAdresJednostkaMiasto]      NVARCHAR (150)  NULL,
    [UrzadAdresJednostkaNrDomu]      NVARCHAR (10)   NULL,
    [UrzadAdresJednostkaNrLokalu]    NVARCHAR (10)   NULL,
    [UrzadMiejcePracyUlica]          NVARCHAR (150)  NULL,
    [UrzadMiejcePracyKodPocztowy]    NVARCHAR (50)   NULL,
    [UrzadMiejcePracyMiasto]         NVARCHAR (150)  NULL,
    [UrzadMiejcePracyNrDomu]         NVARCHAR (10)   NULL,
    [UrzadMiejcePracyNrLokalu]       NVARCHAR (10)   NULL,
    [UrzadStrona]                    NVARCHAR (200)  NULL,
    [UrzadFax]                       NVARCHAR (50)   NULL,
    [UrzadTelefon]                   NVARCHAR (50)   NULL,
    [UrzadEmail]                     NVARCHAR (50)   NULL,
    [UrzadInfo]                      NVARCHAR (200)  NULL,
    [PodstawaPrawna]                 NVARCHAR (2000) NULL,
    [OdNiniejszejDecyzji]            NVARCHAR (2000) NULL,
    [Rozdzielnik]                    NVARCHAR (2000) NULL,
    CONSTRAINT [PK_Pracownik] PRIMARY KEY CLUSTERED ([IDPracownika] ASC) WITH (FILLFACTOR = 90) ON [FG_ZEF2]
) TEXTIMAGE_ON [FG_ZEF2];


GO
ALTER TABLE [zef2].[Pracownik] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = OFF);

