CREATE TABLE [emcs].[ECS_DECLARATIONS] (
    [ID]     BIGINT       NOT NULL,
    [MRN]    VARCHAR (18) NOT NULL,
    [STATUS] VARCHAR (8)  NOT NULL,
    CONSTRAINT [PK_ECS_DECLARATIONS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS],
    CONSTRAINT [AVCON_1314029836_STATU_000] CHECK ([STATUS]='EXPORTED' OR [STATUS]='REJECTED' OR [STATUS]='ACCEPTED' OR [STATUS]='VERIFIED'),
    CONSTRAINT [UK_ECS_DECLARATIONS_1] UNIQUE NONCLUSTERED ([MRN] ASC) ON [FG_EMCS]
);

