CREATE TABLE [emcs].[EMCS_ACO_READERS] (
    [ID]          BIGINT       NOT NULL,
    [ACO_ID]      BIGINT       NOT NULL,
    [ROLE_ID]     DECIMAL (10) NOT NULL,
    [CREATE_DATE] DATETIME     NOT NULL,
    [CREATE_BY]   VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ACO_READERS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS]
);

