CREATE TABLE [emcs].[EMCS_ACO_PROCESS_INSTANCES] (
    [ID]      BIGINT NOT NULL,
    [ACO_ID]  BIGINT NOT NULL,
    [PRIN_ID] BIGINT NOT NULL,
    CONSTRAINT [PK_ACO_PROCESS_INSTANCES] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS],
    CONSTRAINT [UK_ACO_PROCESS_INSTANCES_1] UNIQUE NONCLUSTERED ([PRIN_ID] ASC, [ACO_ID] ASC) ON [FG_EMCS]
);

