CREATE TABLE [emcs].[EMCS_USER_TASKS_SAD_DOCS] (
    [ID]           BIGINT        NOT NULL,
    [SAD_NUMBER]   NVARCHAR (21) NOT NULL,
    [USER_TASK_ID] BIGINT        NOT NULL,
    CONSTRAINT [PK_USER_TASKS_SAD_DOCUMENTS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS]
);

