CREATE TABLE [emcs].[EMCS_ACO_MOVEMENTS] (
    [ID]              BIGINT       NOT NULL,
    [ACO_ID]          BIGINT       NOT NULL,
    [ARC]             VARCHAR (21) NOT NULL,
    [SEQUENCE_NUMBER] DECIMAL (2)  NOT NULL,
    [MVMT_ID]         BIGINT       NULL,
    CONSTRAINT [PK_ACO_MOVEMENTS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS]
);

