CREATE TABLE [emcs].[EMCS_ACO_MESSAGE_RELATIONS] (
    [ID]            BIGINT       NOT NULL,
    [ACOM1_ID]      BIGINT       NOT NULL,
    [ACOM2_ID]      BIGINT       NOT NULL,
    [RELATION_TYPE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ACO_MESSAGE_RELATIONS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS],
    CONSTRAINT [CH_ACO_MESSAGE_RELATIONS_1] CHECK ([ACOM1_ID]<>[ACOM2_ID]),
    CONSTRAINT [UK_ACO_MESSAGE_RELATIONS_1] UNIQUE NONCLUSTERED ([ACOM1_ID] ASC, [ACOM2_ID] ASC) ON [FG_EMCS]
);

