CREATE TABLE [emcs].[MVMT_TRANSPORT_DETAILS] (
    [ID]                           BIGINT         NOT NULL,
    [TRANSPORT_UNIT_CODE]          CHAR (2)       NULL,
    [IDENTITY_OF_TRANSPORT_UNIT]   NVARCHAR (35)  NULL,
    [IDENTITY_OF_COMMERCIAL_SEAL]  NVARCHAR (35)  NULL,
    [SEAL_INFORMATION]             NVARCHAR (350) NULL,
    [SEAL_INFORMATION_LANG_CODE]   CHAR (2)       NULL,
    [COMPLEMENTARY_INFORMATION]    NVARCHAR (350) NULL,
    [COMPLEMENTARY_INFO_LANG_CODE] CHAR (2)       NULL,
    [MVMT_ID]                      BIGINT         NOT NULL,
    CONSTRAINT [PK_MVMTTRANSP] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS]
);

