CREATE TABLE [emcs].[MVMT_CERTIFICATES] (
    [ID]                             BIGINT         NOT NULL,
    [REFERENCE_OF_DOCUMENT]          NVARCHAR (350) NULL,
    [REFERENCE_OF_DOC_LANG_CODE]     CHAR (2)       NULL,
    [DOCUMENT_DESCRIPTION]           NVARCHAR (350) NULL,
    [DOCUMENT_DESCRIPTION_LANG_CODE] CHAR (2)       NULL,
    [MVMT_ID]                        BIGINT         NOT NULL,
    CONSTRAINT [PK_MVMTCERT] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS]
);

