CREATE TABLE [emcs].[MVMT_PACKAGES] (
    [ID]                          BIGINT         NOT NULL,
    [KIND_OF_PACKAGES_CODE]       CHAR (2)       NOT NULL,
    [NUMBER_OF_PACKAGES]          BIGINT         NULL,
    [IDENTITY_OF_COMMERCIAL_SEAL] VARCHAR (35)   NULL,
    [SEAL_INFORMATION]            NVARCHAR (350) NULL,
    [SEAL_INFORMATION_LANG_CODE]  CHAR (2)       NULL,
    [MVMT_PRODUCT_ID]             BIGINT         NOT NULL,
    CONSTRAINT [PK_MVMTPCKGS] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS]
);

