CREATE TABLE [emcs].[PACKAGING_CODES] (
    [ID]                           BIGINT         NOT NULL,
    [CODE]                         CHAR (2)       NOT NULL,
    [DESCRIPTION]                  NVARCHAR (300) NOT NULL,
    [DESCRIPTION_LANG_CODE]        CHAR (2)       NULL,
    [COUNTABLE]                    CHAR (1)       DEFAULT ('0') NOT NULL,
    [VALID_FROM]                   DATE           NOT NULL,
    [VALID_TO]                     DATE           DEFAULT ('9999-12-31') NOT NULL,
    [ACTION_IDENTIFIER]            VARCHAR (20)   NOT NULL,
    [INVALIDATE_ACTION_IDENTIFIER] VARCHAR (20)   NULL,
    [SEED_CODE]                    VARCHAR (4)    NULL,
    CONSTRAINT [PK_PACKAGING_CODES] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS],
    CONSTRAINT [AVCON_1292567153_COUNT_000] CHECK ([COUNTABLE]='1' OR [COUNTABLE]='0'),
    CONSTRAINT [AVCON_1314869814_SEED__000] CHECK ([SEED_CODE]='OnPB' OR [SEED_CODE]='OB' OR [SEED_CODE]='OP' OR [SEED_CODE]='OnC' OR [SEED_CODE]='OC'),
    CONSTRAINT [UK_PACKAGING_CODES_1] UNIQUE NONCLUSTERED ([VALID_FROM] ASC, [CODE] ASC) ON [FG_EMCS]
);

