CREATE TABLE [emcs].[REF_SD2_PODMIOTY] (
    [NRA]                      VARCHAR (13)    NOT NULL,
    [TYP]                      VARCHAR (5)     NOT NULL,
    [NAZWA]                    NVARCHAR (300)  NOT NULL,
    [NIP]                      NVARCHAR (35)   NOT NULL,
    [REGON]                    NVARCHAR (14)   NULL,
    [KOD_KRAJU]                CHAR (2)        NOT NULL,
    [ULICA]                    NVARCHAR (70)   NULL,
    [NR_DOMU]                  NVARCHAR (11)   NOT NULL,
    [NR_LOKALU]                NVARCHAR (240)  NULL,
    [MIEJSCOWOSC]              NVARCHAR (60)   NULL,
    [KOD_POCZTOWY]             VARCHAR (10)    NOT NULL,
    [POCZTA]                   NVARCHAR (60)   NULL,
    [UC_NADZORU]               VARCHAR (8)     NULL,
    [OBOWIAZUJE_OD]            DATE            NOT NULL,
    [OBOWIAZUJE_DO]            DATE            NOT NULL,
    [WYSYLAJACY]               VARCHAR (13)    NULL,
    [INT_DOMYSLNY]             CHAR (1)        NULL,
    [INT_PODSTAWOWY_EMAIL]     NVARCHAR (127)  NULL,
    [INT_EMAIL]                NVARCHAR (240)  NULL,
    [INT_WS_LOGIN]             NVARCHAR (20)   NULL,
    [INT_WS_HASLO]             NVARCHAR (20)   NULL,
    [INT_WS_ADRES]             NVARCHAR (1024) NULL,
    [UC_WYDANIA]               VARCHAR (8)     NOT NULL,
    [INT_WS_EMCS_HASLO]        NVARCHAR (20)   NULL,
    [INT_WS_X509_THUMBPRINT]   VARCHAR (250)   NULL,
    [CZY_DOSTAWA_BEZPOSREDNIA] CHAR (1)        DEFAULT ('0') NULL,
    [WLASCICIEL]               VARCHAR (13)    NULL,
    CONSTRAINT [PK_REF_SD2_PODMIOTY] PRIMARY KEY CLUSTERED ([NRA] ASC, [TYP] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS],
    CONSTRAINT [AVCON_1292567153_CZY_D_000] CHECK ([CZY_DOSTAWA_BEZPOSREDNIA]='1' OR [CZY_DOSTAWA_BEZPOSREDNIA]='0'),
    CONSTRAINT [AVCON_1292567153_INT_D_000] CHECK ([INT_DOMYSLNY]='W' OR [INT_DOMYSLNY]='E'),
    CONSTRAINT [AVCON_1294148986_TYP_000] CHECK ([TYP]='PP' OR [TYP]='RCO' OR [TYP]='RCT' OR [TYP]='TW' OR [TYP]='AWK' OR [TYP]='RCE')
);

