CREATE TABLE [emcs].[REF_SD2_ZABEZPIECZENIA] (
    [ID]                   BIGINT       NOT NULL,
    [REF_SD2_PODMIOTY_NRA] VARCHAR (13) NOT NULL,
    [NR_GRN]               VARCHAR (17) NOT NULL,
    [OBOWIAZUJE_OD]        DATE         NOT NULL,
    [OBOWIAZUJE_DO]        DATE         NULL,
    [REF_SD2_PODMIOTY_TYP] VARCHAR (5)  NOT NULL,
    CONSTRAINT [PK_REF_SD2_ZABEZPIECZENIA] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS],
    CONSTRAINT [AVCON_1294148986_REF_S_001] CHECK ([REF_SD2_PODMIOTY_TYP]='PP' OR [REF_SD2_PODMIOTY_TYP]='RCO' OR [REF_SD2_PODMIOTY_TYP]='RCT' OR [REF_SD2_PODMIOTY_TYP]='TW' OR [REF_SD2_PODMIOTY_TYP]='AWK' OR [REF_SD2_PODMIOTY_TYP]='RCE')
);

