CREATE TABLE [emcs].[REF_SD2_WLASCICIELE] (
    [ID]             BIGINT       NOT NULL,
    [NRA]            VARCHAR (13) NOT NULL,
    [TYP]            VARCHAR (5)  NOT NULL,
    [WLASCICIEL_NRA] VARCHAR (13) NOT NULL,
    [WLASCICIEL_TYP] VARCHAR (5)  DEFAULT ('AWK') NOT NULL,
    CONSTRAINT [PK_REF_SD2_WLASCICIELE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (DATA_COMPRESSION = PAGE) ON [FG_EMCS],
    CONSTRAINT [AVCON_1314275154_TYP_000] CHECK ([TYP]='PP' OR [TYP]='RCO' OR [TYP]='RCT' OR [TYP]='TW' OR [TYP]='AWK' OR [TYP]='RCE'),
    CONSTRAINT [AVCON_1314275154_WLASC_000] CHECK ([WLASCICIEL_TYP]='PP' OR [WLASCICIEL_TYP]='RCO' OR [WLASCICIEL_TYP]='RCT' OR [WLASCICIEL_TYP]='TW' OR [WLASCICIEL_TYP]='AWK' OR [WLASCICIEL_TYP]='RCE')
);

