CREATE TABLE [ncts2].[gwarancje] (
    [id]                                       BIGINT          NOT NULL,
    [operacja_tranzytowa_gwarancja_id]         BIGINT          NULL,
    [grn]                                      NVARCHAR (24)   NULL,
    [kod_dostepu]                              NVARCHAR (4)    NULL,
    [niewazna_na_ue]                           BIT             NULL,
    [poz_id]                                   INT             NULL,
    [nr]                                       NVARCHAR (35)   NULL,
    [kwota]                                    NUMERIC (15, 2) NULL,
    [waluta]                                   NVARCHAR (3)    NULL,
    [status]                                   NVARCHAR (33)   NULL,
    [numer_operacji_zajecia_zabezpieczenia]    NVARCHAR (75)   NULL,
    [numer_operacji_zwolnienia_zabezpieczenia] NVARCHAR (75)   NULL,
    [numer_operacji_wycofania_zabezpieczenia]  NVARCHAR (75)   NULL,
    [niewazna_na_strony_konwencji]             NVARCHAR (500)  NULL,
    [kwota_euro]                               NUMERIC (15, 2) NULL,
    [uc_gwarancji]                             NVARCHAR (8)    NULL,
    [kwota_pln]                                NUMERIC (15, 2) NULL,
    [kod_przyczyny_odrzucenia]                 NVARCHAR (3)    NULL,
    [opis_przyczyny_odrzucenia]                NVARCHAR (350)  NULL,
    [status_integralnosci]                     NVARCHAR (12)   NULL,
    [data_sprawdzenia_integralnosci]           DATETIME        NULL,
    [data_zapytania_o_integralnosc]            DATETIME        NULL,
    CONSTRAINT [gwarancje_pk] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_NCTS2]
);

