CREATE TABLE [ncts2].[operacje_tranzytowe] (
    [id]                                             BIGINT          NOT NULL,
    [data_utworzenia]                                DATETIME        NULL,
    [data_modyfikacji]                               DATETIME        NULL,
    [data_zwolnienia]                                DATETIME        NULL,
    [uc_wyjscia]                                     NVARCHAR (8)    NULL,
    [uc_przeznaczenia]                               NVARCHAR (8)    NULL,
    [nadawca_nazwa]                                  NVARCHAR (35)   NULL,
    [nadawca_ulica_numer]                            NVARCHAR (100)  NULL,
    [nadawca_kod_pocztowy]                           NVARCHAR (9)    NULL,
    [nadawca_miejscowosc]                            NVARCHAR (52)   NULL,
    [nadawca_kraj]                                   NVARCHAR (2)    NULL,
    [nadawca_tin]                                    NVARCHAR (17)   NULL,
    [odbiorca_nazwa]                                 NVARCHAR (35)   NULL,
    [odbiorca_ulica_numer]                           NVARCHAR (100)  NULL,
    [odbiorca_kod_pocztowy]                          NVARCHAR (9)    NULL,
    [odbiorca_miejscowosc]                           NVARCHAR (52)   NULL,
    [odbiorca_kraj]                                  NVARCHAR (2)    NULL,
    [odbiorca_tin]                                   NVARCHAR (17)   NULL,
    [glowny_zobowiazany_nazwa]                       NVARCHAR (35)   NULL,
    [glowny_zobowiazany_ulica_numer]                 NVARCHAR (100)  NULL,
    [glowny_zobowiazany_kod_pocztowy]                NVARCHAR (9)    NULL,
    [glowny_zobowiazany_miejscowosc]                 NVARCHAR (52)   NULL,
    [glowny_zobowiazany_kraj]                        NVARCHAR (2)    NULL,
    [glowny_zobowiazany_tin]                         NVARCHAR (17)   NULL,
    [glowny_zobowiazany_przedstawiciel_tin]          NVARCHAR (17)   NULL,
    [upowazniony_odbiorca_tin]                       NVARCHAR (17)   NULL,
    [transport_rodzaj]                               NVARCHAR (2)    NULL,
    [transport_znaki]                                NVARCHAR (27)   NULL,
    [transport_kraj]                                 NVARCHAR (2)    NULL,
    [transport_na_granicy_rodzaj]                    NVARCHAR (2)    NULL,
    [transport_na_granicy_znaki]                     NVARCHAR (27)   NULL,
    [transport_na_granicy_kraj]                      NVARCHAR (2)    NULL,
    [wynik_kontroli_kod]                             NVARCHAR (2)    NULL,
    [wynik_kontroli_termin_dostarczenia]             DATETIME        NULL,
    [zamkniecia_celne_ilosc]                         INT             NULL,
    [zamkniecia_celne_nakladajacy]                   NVARCHAR (35)   NULL,
    [bezpieczenstwo_spec_warunki]                    NVARCHAR (1)    NULL,
    [bezpieczenstwo_forma_platnosci]                 NVARCHAR (1)    NULL,
    [bezpieczenstwo_nr_referencyjny_przesylki]       NVARCHAR (70)   NULL,
    [bezpieczenstwo_nr_referencyjny_przewozu]        NVARCHAR (35)   NULL,
    [bezpieczenstwo_miejsce_rozladunku]              NVARCHAR (35)   NULL,
    [bezpieczenstwo_nadawca_nazwa]                   NVARCHAR (35)   NULL,
    [bezpieczenstwo_nadawca_ulica_numer]             NVARCHAR (100)  NULL,
    [bezpieczenstwo_nadawca_kod_pocztowy]            NVARCHAR (9)    NULL,
    [bezpieczenstwo_nadawca_miejscowosc]             NVARCHAR (52)   NULL,
    [bezpieczenstwo_nadawca_kraj]                    NVARCHAR (2)    NULL,
    [bezpieczenstwo_nadawca_tin]                     NVARCHAR (17)   NULL,
    [bezpieczenstwo_odbiorca_nazwa]                  NVARCHAR (35)   NULL,
    [bezpieczenstwo_odbiorca_ulica_numer]            NVARCHAR (100)  NULL,
    [bezpieczenstwo_odbiorca_kod_pocztowy]           NVARCHAR (9)    NULL,
    [bezpieczenstwo_odbiorca_miejscowosc]            NVARCHAR (52)   NULL,
    [bezpieczenstwo_odbiorca_kraj]                   NVARCHAR (2)    NULL,
    [bezpieczenstwo_odbiorca_tin]                    NVARCHAR (17)   NULL,
    [bezpieczenstwo_przewoznik_nazwa]                NVARCHAR (35)   NULL,
    [bezpieczenstwo_przewoznik_ulica_numer]          NVARCHAR (100)  NULL,
    [bezpieczenstwo_przewoznik_kod_pocztowy]         NVARCHAR (9)    NULL,
    [bezpieczenstwo_przewoznik_miejscowosc]          NVARCHAR (52)   NULL,
    [bezpieczenstwo_przewoznik_kraj]                 NVARCHAR (2)    NULL,
    [bezpieczenstwo_przewoznik_tin]                  NVARCHAR (17)   NULL,
    [miejsce_data_data]                              DATETIME        NULL,
    [typ_deklaracji]                                 NVARCHAR (5)    NULL,
    [liczba_pozycji]                                 INT             NULL,
    [liczba_opakowan]                                INT             NULL,
    [kraj_wysylki]                                   NVARCHAR (2)    NULL,
    [kraj_przeznaczenia]                             NVARCHAR (2)    NULL,
    [masa_brutto]                                    NUMERIC (14, 3) NULL,
    [miejsce_zaladunku]                              NVARCHAR (17)   NULL,
    [procedura_uproszczona_uc_wyjscia]               BIT             NULL,
    [glowny_zobowiazany_tir_holder]                  BIT             NULL,
    [kontenery]                                      BIT             NULL,
    [lrn]                                            NVARCHAR (21)   NULL,
    [mrn]                                            NVARCHAR (18)   NULL,
    [rewizja]                                        INT             NULL,
    [blokada_czas_wygasniecia]                       DATETIME        NULL,
    [blokada_login_uzytkownika]                      NVARCHAR (32)   NULL,
    [status_uc_przeznaczenia_data]                   DATETIME        NULL,
    [flaga_ar_uc_wyjscia]                            NVARCHAR (1)    NULL,
    [flaga_stop_uc_wyjscia]                          BIT             NULL,
    [status_uc_wyjscia]                              NVARCHAR (8)    NULL,
    [status_uc_wyjscia_data]                         DATETIME        NULL,
    [miejsce_data_miejsce]                           NVARCHAR (35)   NULL,
    [miejsce_data_nazwisko_imie]                     NVARCHAR (35)   NULL,
    [miejsce_data_stanowisko]                        NVARCHAR (35)   NULL,
    [miejsce_uznane]                                 NVARCHAR (1)    NULL,
    [ryzyko_uc_wyjscia]                              INT             NULL,
    [ryzyko_uc_przeznaczenia]                        INT             NULL,
    [data_dokonania]                                 DATETIME        NULL,
    [wiazaca_trasa_przewozu]                         NVARCHAR (200)  NULL,
    [zap_o_przesylke_odp]                            NVARCHAR (500)  NULL,
    [przedstawiajacy_nazwa]                          NVARCHAR (35)   NULL,
    [przedstawiajacy_ulica_numer]                    NVARCHAR (100)  NULL,
    [przedstawiajacy_kod_pocztowy]                   NVARCHAR (9)    NULL,
    [przedstawiajacy_miejscowosc]                    NVARCHAR (52)   NULL,
    [przedstawiajacy_kraj]                           NVARCHAR (2)    NULL,
    [przedstawiajacy_tin]                            NVARCHAR (17)   NULL,
    [flaga_ar_uc_przeznaczenia]                      NVARCHAR (1)    NULL,
    [towary_wrazliwe]                                BIT             NULL,
    [komunikacja_podmiot_wyjscia]                    NVARCHAR (17)   NULL,
    [komunikacja_kraj_wyjscia]                       NVARCHAR (6)    NULL,
    [komunikacja_podmiot_przeznaczenia]              NVARCHAR (17)   NULL,
    [komunikacja_kraj_przeznaczenia]                 NVARCHAR (6)    NULL,
    [procedura_uproszczona_uc_przeznaczenia]         BIT             NULL,
    [data_przyjecia]                                 DATETIME        NULL,
    [status_uc_przeznaczenia]                        NVARCHAR (8)    NULL,
    [nr_karnetu_tir]                                 NVARCHAR (11)   NULL,
    [przedstawiajacy_przedstawiciel_tin]             NVARCHAR (17)   NULL,
    [uc_przeznaczenia_deklarowany]                   NVARCHAR (8)    NULL,
    [data_przybycia]                                 DATETIME        NULL,
    [flaga_uniewaznienie_uc_wyjscia]                 BIT             NULL,
    [jezyk_tdt]                                      NVARCHAR (2)    NULL,
    [data_kontroli]                                  DATETIME        NULL,
    [bezpieczenstwo]                                 BIT             NULL,
    [flaga_aeo]                                      BIT             NULL,
    [flaga_rej_gwar_uc_wyjscia]                      NVARCHAR (1)    NULL,
    [miejsce_przybycia]                              NVARCHAR (35)   NULL,
    [flaga_glow_zob_pozw_na_proc_upro]               BIT             NULL,
    [glowny_zobowiazany_przedstawiciel_nazwa]        NVARCHAR (35)   NULL,
    [glowny_zobowiazany_przedstawiciel_ulica_numer]  NVARCHAR (100)  NULL,
    [glowny_zobowiazany_przedstawiciel_kod_pocztowy] NVARCHAR (9)    NULL,
    [glowny_zobowiazany_przedstawiciel_miejscowosc]  NVARCHAR (52)   NULL,
    [glowny_zobowiazany_przedstawiciel_kraj]         NVARCHAR (2)    NULL,
    [transport_znaki_jezyk]                          NVARCHAR (2)    NULL,
    [flaga_uniewaznienie_aes]                        BIT             NULL,
    [flaga_ostrzezenia]                              BIT             NULL,
    [przedstawiajacy_nr_pozwolenia]                  NVARCHAR (35)   NULL,
    CONSTRAINT [operacje_tranzytowe_pk] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_NCTS2]
);

