CREATE TABLE [ncts2].[towary] (
    [id]                                            BIGINT          NOT NULL,
    [operacja_tranzytowa_id]                        BIGINT          NULL,
    [poz_id]                                        INT             NULL,
    [typ_deklaracji]                                NVARCHAR (5)    NULL,
    [kraj_wysylki]                                  NVARCHAR (2)    NULL,
    [kraj_przeznaczenia]                            NVARCHAR (2)    NULL,
    [opis]                                          NVARCHAR (280)  NULL,
    [kod_towarowy]                                  NVARCHAR (8)    NULL,
    [masa_brutto]                                   NUMERIC (14, 3) NULL,
    [masa_netto]                                    NUMERIC (14, 3) NULL,
    [nadawca_nazwa]                                 NVARCHAR (35)   NULL,
    [nadawca_ulica_numer]                           NVARCHAR (35)   NULL,
    [nadawca_kod_pocztowy]                          NVARCHAR (9)    NULL,
    [nadawca_miejscowosc]                           NVARCHAR (35)   NULL,
    [nadawca_kraj]                                  NVARCHAR (2)    NULL,
    [nadawca_tin]                                   NVARCHAR (17)   NULL,
    [odbiorca_nazwa]                                NVARCHAR (35)   NULL,
    [odbiorca_ulica_numer]                          NVARCHAR (35)   NULL,
    [odbiorca_kod_pocztowy]                         NVARCHAR (9)    NULL,
    [odbiorca_miejscowosc]                          NVARCHAR (35)   NULL,
    [odbiorca_kraj]                                 NVARCHAR (2)    NULL,
    [odbiorca_tin]                                  NVARCHAR (17)   NULL,
    [bezpieczenstwo_forma_platnosci]                NVARCHAR (1)    NULL,
    [bezpieczenstwo_nr_referencyjny_przesylki]      NVARCHAR (70)   NULL,
    [bezpieczenstwo_kod_un_towarow_niebezpiecznych] NVARCHAR (4)    NULL,
    [bezpieczenstwo_nadawca_nazwa]                  NVARCHAR (35)   NULL,
    [bezpieczenstwo_nadawca_ulica_numer]            NVARCHAR (35)   NULL,
    [bezpieczenstwo_nadawca_kod_pocztowy]           NVARCHAR (9)    NULL,
    [bezpieczenstwo_nadawca_miejscowosc]            NVARCHAR (35)   NULL,
    [bezpieczenstwo_nadawca_kraj]                   NVARCHAR (2)    NULL,
    [bezpieczenstwo_nadawca_tin]                    NVARCHAR (17)   NULL,
    [bezpieczenstwo_odbiorca_nazwa]                 NVARCHAR (35)   NULL,
    [bezpieczenstwo_odbiorca_ulica_numer]           NVARCHAR (35)   NULL,
    [bezpieczenstwo_odbiorca_kod_pocztowy]          NVARCHAR (9)    NULL,
    [bezpieczenstwo_odbiorca_miejscowosc]           NVARCHAR (35)   NULL,
    [bezpieczenstwo_odbiorca_kraj]                  NVARCHAR (2)    NULL,
    [bezpieczenstwo_odbiorca_tin]                   NVARCHAR (17)   NULL,
    [tryb_utworzenia_pozycji]                       NVARCHAR (1)    NULL,
    [iteracja_uwag_rozladunkowych]                  SMALLINT        NULL,
    [nadawca_certyfikat_aeo]                        NVARCHAR (35)   NULL,
    [odbiorca_certyfikat_aeo]                       NVARCHAR (35)   NULL,
    [bezpieczenstwo_nadawca_certyfikat_aeo]         NVARCHAR (35)   NULL,
    [bezpieczenstwo_odbiorca_certyfikat_aeo]        NVARCHAR (35)   NULL,
    [opis_jezyk]                                    NVARCHAR (2)    NULL,
    CONSTRAINT [towary_pk] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_NCTS2],
    CONSTRAINT [towary_operacja_tranzytowa_id_id_fk] FOREIGN KEY ([operacja_tranzytowa_id]) REFERENCES [ncts2].[operacje_tranzytowe] ([id])
);

