CREATE TABLE [ncts2].[zdarzenia] (
    [id]                                 BIGINT         NOT NULL,
    [typ]                                NVARCHAR (1)   NULL,
    [poz_id]                             INT            NULL,
    [operacja_tranzytowa_id]             BIGINT         NULL,
    [miejsce]                            NVARCHAR (35)  NULL,
    [kraj]                               NVARCHAR (2)   NULL,
    [czy_inne_zdarzenie]                 BIT            NULL,
    [czy_w_systemie]                     BIT            NULL,
    [zdarzenie_opis]                     NVARCHAR (350) NULL,
    [zdarzenie_data_adnotacji]           DATETIME       NULL,
    [zdarzenie_kraj_adnotacji]           NVARCHAR (2)   NULL,
    [zdarzenie_wladze_adnotacji]         NVARCHAR (35)  NULL,
    [zdarzenie_miejsce_adnotacji]        NVARCHAR (35)  NULL,
    [przeladunek_znaki]                  NVARCHAR (27)  NULL,
    [przeladunek_kraj_srodka_transportu] NVARCHAR (2)   NULL,
    [przeladunek_data_adnotacji]         DATETIME       NULL,
    [przeladunek_kraj_adnotacji]         NVARCHAR (2)   NULL,
    [przeladunek_wladze_adnotacji]       NVARCHAR (35)  NULL,
    [przeladunek_miejsce_adnotacji]      NVARCHAR (35)  NULL,
    [ilosc_zamkniec]                     SMALLINT       NULL,
    [wniosek_o_aar_id]                   BIGINT         NULL,
    [wniosek_o_atr_id]                   BIGINT         NULL,
    [kod_uc]                             NVARCHAR (8)   NULL,
    CONSTRAINT [zdarzenia_pk] PRIMARY KEY CLUSTERED ([id] ASC) ON [FG_NCTS2],
    CONSTRAINT [zdarzenia_operacja_tranzytowa_id_id_fk] FOREIGN KEY ([operacja_tranzytowa_id]) REFERENCES [ncts2].[operacje_tranzytowe] ([id]),
    CONSTRAINT [zdarzenia_wniosek_o_aar_id_id_fk] FOREIGN KEY ([wniosek_o_aar_id]) REFERENCES [ncts2].[wnioski_o_aar] ([id]),
    CONSTRAINT [zdarzenia_wniosek_o_atr_id_id_fk] FOREIGN KEY ([wniosek_o_atr_id]) REFERENCES [ncts2].[wnioski_o_atr] ([id])
);

