CREATE TABLE [zef2DW].[AZNN_Dokument] (
    [IdentyfikatorDokumentu]                     BIGINT          NOT NULL,
    [Instancja]                                  NVARCHAR (10)   NULL,
    [DecyzjaWlasnaUS_SC]                         NVARCHAR (8)    NULL,
    [NazwaOrganuWydajacego]                      NVARCHAR (255)  NULL,
    [DataPostanowienia]                          DATE            NULL,
    [NumerPostanowienia]                         NVARCHAR (255)  NULL,
    [DataDoreczenia]                             DATE            NULL,
    [NrPostanowieniaIInstancji]                  NVARCHAR (255)  NULL,
    [PierwotneRodzaj]                            NVARCHAR (255)  NULL,
    [PierwotneNumer]                             NVARCHAR (255)  NULL,
    [PierwotneDataDokumentu]                     DATE            NULL,
    [PierwotneDataZaliczenia]                    DATE            NULL,
    [PierwotneKwotaNadplaty]                     DECIMAL (19, 2) NULL,
    [PierwotneKwotaOprocentowania]               DECIMAL (19, 2) NULL,
    [PierwotneOkresNaliczeniaOd]                 DATE            NULL,
    [PierwotneOkresNaliczeniaDo]                 DATE            NULL,
    [PierwotneRazemKwotaNadplatyIOprocentowania] DECIMAL (19, 2) NULL,
    [UtrzymanieUchylenie]                        NVARCHAR (10)   NULL,
    [RwUzasadnienie]                             NVARCHAR (MAX)  NULL,
    [AdnotacjeIUwagi]                            NVARCHAR (512)  NULL,
    [RazemNadplata]                              DECIMAL (19, 2) NULL,
    [RazemOdsetki]                               DECIMAL (19, 2) NULL,
    [RazemOplataProlongacyjna]                   DECIMAL (19, 2) NULL,
    [UsKwotaPrzelewuRazem]                       DECIMAL (19, 2) NULL,
    [RwPodstawaPrawna]                           NVARCHAR (4000) NULL,
    [DataArch]                                   DATE            NULL,
    [ID_Pismo_xml]                               BIGINT          NULL,
    [IdentyfikatorPodatnika]                     BIGINT          NOT NULL,
    CONSTRAINT [AZNN_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DW]
);

