CREATE TABLE [zef2DW].[DAKC_Dokument] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [DokumentArchiwalny]                    NVARCHAR (5)    NULL,
    [RodzajPodatku]                         NVARCHAR (64)   NULL,
    [DecyzjaWydanaPrzez]                    NVARCHAR (25)   NULL,
    [OrganWydajacy]                         NVARCHAR (255)  NULL,
    [DataWydania]                           DATE            NULL,
    [DataDoreczenia]                        DATE            NULL,
    [NumerDecyzji]                          NVARCHAR (255)  NULL,
    [TerminPlatnosci]                       DATE            NULL,
    [WWynikuKontroliPostepowania]           NVARCHAR (12)   NULL,
    [NrUpowaznienia]                        NVARCHAR (255)  NULL,
    [NrPostanowieniaOWszczeciuPostepowania] NVARCHAR (255)  NULL,
    [WynikKontroliNumerWniosku]             NVARCHAR (255)  NULL,
    [ZaOkres]                               NVARCHAR (7)    NULL,
    [PierwotnyRodzajDokumentu]              NVARCHAR (255)  NULL,
    [PierwotnyNumerDokumentu]               NVARCHAR (255)  NULL,
    [KwotaDecyzjiRazem]                     DECIMAL (19, 2) NULL,
    [ParametryWniosku]                      NVARCHAR (50)   NULL,
    [JakiOkresRozliczeniowy]                NVARCHAR (16)   NULL,
    [WnioskodawcaPostepowania]              NVARCHAR (25)   NULL,
    [AdnotacjeIUwagi]                       NVARCHAR (512)  NULL,
    [RaportWyslaniaSK]                      NVARCHAR (MAX)  NULL,
    [DataArch]                              DATE            NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [IdentyfikatorPodatnika]                BIGINT          NOT NULL,
    [KodJednostki]                          NVARCHAR (6)    NULL,
    CONSTRAINT [DAKC_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DW]
) TEXTIMAGE_ON [FG_ZEF2DW];

