CREATE TABLE [zef2DW].[DAKO_Dokument] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [DataDoreczenia]                        DATE            NULL,
    [DataWydania]                           DATE            NULL,
    [DecyjaPrzejetaZ]                       NVARCHAR (30)   NULL,
    [ParametryWniosku]                      NVARCHAR (50)   NULL,
    [Okres]                                 NVARCHAR (8)    NULL,
    [OrganWydajacyIc]                       BIGINT          NULL,
    [JakiOkresRozliczeniowy]                NVARCHAR (16)   NULL,
    [PozycjeRazem]                          DECIMAL (19, 2) NULL,
    [PrzyczynaZadluzenia]                   INT             NULL,
    [RodzajPodatku]                         NVARCHAR (64)   NULL,
    [NumerDecyzji]                          NVARCHAR (255)  NULL,
    [RaportWyslaniaSK]                      NVARCHAR (MAX)  NULL,
    [RodzajDeklaracji]                      BIGINT          NULL,
    [ZaOkres]                               NVARCHAR (7)    NULL,
    [DokumentArchiwalny]                    NVARCHAR (5)    NULL,
    [WWynikuKontroliPostepowania]           NVARCHAR (12)   NULL,
    [NrUpowaznienia]                        NVARCHAR (255)  NULL,
    [NrPostanowieniaOWszczeciuPostepowania] NVARCHAR (255)  NULL,
    [WynikKontroliNumerWniosku]             NVARCHAR (255)  NULL,
    [PierwotnyRodzajDokumentu]              NVARCHAR (255)  NULL,
    [PierwotnyNumerDokumentu]               NVARCHAR (255)  NULL,
    [AdnotacjeIUwagi]                       NVARCHAR (MAX)  NULL,
    [WnioskodawcaPostepowania]              NVARCHAR (25)   NULL,
    [DataArch]                              DATE            NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [IdentyfikatorPodatnika]                BIGINT          NOT NULL,
    [KodJednostki]                          NVARCHAR (6)    NULL,
    [MigracjaReczna]                        NVARCHAR (5)    NULL,
    CONSTRAINT [DAKO_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DW]
) TEXTIMAGE_ON [FG_ZEF2DW];

