CREATE TABLE [zef2DW].[DKPI_Dokument] (
    [IdentyfikatorDokumentu]                BIGINT          NOT NULL,
    [DokumentArchiwalny]                    NVARCHAR (5)    NULL,
    [NumerDecyzji]                          NVARCHAR (255)  NULL,
    [RodzajKary]                            NVARCHAR (32)   NULL,
    [DataWydania]                           DATE            NULL,
    [DataOtrzymania]                        DATE            NULL,
    [TerminPlatnosci]                       DATE            NULL,
    [CzyNaliczycOdsetki]                    NVARCHAR (5)    NULL,
    [WWynikuKontroliPostepowania]           NVARCHAR (12)   NULL,
    [NrUpowaznienia]                        NVARCHAR (255)  NULL,
    [NrPostanowieniaOWszczeciuPostepowania] NVARCHAR (255)  NULL,
    [WynikKontroliNumerWniosku]             NVARCHAR (255)  NULL,
    [KaraRazem]                             DECIMAL (19, 2) NULL,
    [OsobaKrajowaZagraniczna]               NVARCHAR (32)   NULL,
    [WnioskodawcaPostepowania]              NVARCHAR (25)   NULL,
    [MigracjaReczna]                        NVARCHAR (5)    NULL,
    [AdnotacjeIUwagi]                       NVARCHAR (512)  NULL,
    [RaportWyslaniaSK]                      NVARCHAR (MAX)  NULL,
    [SposobZaplaty]                         NVARCHAR (27)   NULL,
    [DataArch]                              DATE            NULL,
    [ID_Pismo_xml]                          BIGINT          NULL,
    [IdentyfikatorPodatnika]                BIGINT          NOT NULL,
    [KodJednostki]                          NVARCHAR (6)    NULL,
    [NumerPokwitowania]                     NVARCHAR (255)  NULL,
    [KwotaKaucji]                           DECIMAL (19, 4) NULL,
    CONSTRAINT [DKPI_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DW]
) TEXTIMAGE_ON [FG_ZEF2DW];

