CREATE TABLE [zef2DW].[DPDZ_Dokument] (
    [IdentyfikatorDokumentu]     BIGINT          NOT NULL,
    [NrZgloszenia]               NVARCHAR (255)  NULL,
    [AIS]                        NVARCHAR (5)    NULL,
    [DataPowiadomienia]          DATE            NULL,
    [DataPowstaniaDluguCelnego]  DATE            NULL,
    [DataZgloszenia]             DATE            NULL,
    [DataZwolnieniaTowaru]       DATE            NULL,
    [DokumentArchiwalny]         NVARCHAR (5)    NULL,
    [KwotaZabezpieczeniaTSW]     DECIMAL (19, 2) NULL,
    [NazwaZglaszajacego]         NVARCHAR (255)  NULL,
    [NipZglaszajacego]           NVARCHAR (255)  NULL,
    [NumerZglaszajacego]         NVARCHAR (32)   NULL,
    [PeselZglaszajacego]         NVARCHAR (255)  NULL,
    [ObrotPocztowy]              NVARCHAR (5)    NULL,
    [PozycjeRazem]               DECIMAL (19, 2) NULL,
    [RazemBezZwol]               DECIMAL (19, 2) NULL,
    [RegonZglaszajacego]         NVARCHAR (4000) NULL,
    [TerminPlatnosci]            DATE            NULL,
    [WpisDoRejestruDluguCelnego] NVARCHAR (5)    NULL,
    [DataUrodzeniaZglaszajacego] DATE            NULL,
    [GminaZglaszajacego]         NVARCHAR (4000) NULL,
    [ImieZglaszajacego]          NVARCHAR (4000) NULL,
    [KodPocztowyZglaszajacego]   NVARCHAR (4000) NULL,
    [KrajZglaszajacego]          NVARCHAR (4000) NULL,
    [MiejscowoscZglaszajacego]   NVARCHAR (4000) NULL,
    [NazwaPelnaZglaszajacego]    NVARCHAR (4000) NULL,
    [NazwiskoZglaszajacego]      NVARCHAR (4000) NULL,
    [NrDokumentuZglaszajacego]   NVARCHAR (4000) NULL,
    [NrDomuZglaszajacego]        NVARCHAR (4000) NULL,
    [NrEORIZglaszajacego]        NVARCHAR (4000) NULL,
    [NrLokaluZglaszajacego]      NVARCHAR (4000) NULL,
    [NrVatUeZglaszajacego]       NVARCHAR (4000) NULL,
    [PocztaZglaszajacego]        NVARCHAR (4000) NULL,
    [PowiatZglaszajacego]        NVARCHAR (4000) NULL,
    [RodzajZglaszajacego]        NVARCHAR (64)   NULL,
    [System]                     NVARCHAR (8)    NULL,
    [UlicaZglaszajacego]         NVARCHAR (4000) NULL,
    [UwagiZglaszajacego]         NVARCHAR (4000) NULL,
    [WojewodztwoZglaszajacego]   NVARCHAR (4000) NULL,
    [Usunieto]                   NVARCHAR (5)    NULL,
    [AdnotacjeIUwagi]            NVARCHAR (512)  NULL,
    [RaportWyslaniaSK]           NVARCHAR (MAX)  NULL,
    [DataArch]                   DATE            NULL,
    [ID_Pismo_xml]               BIGINT          NULL,
    [IdentyfikatorPodatnika]     BIGINT          NOT NULL,
    [DataRejestracjiRDC]         DATE            NULL,
    CONSTRAINT [DPDZ_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DW]
) TEXTIMAGE_ON [FG_ZEF2DW];

