CREATE TABLE [zef2DW].[DWNN_Dokument] (
    [IdentyfikatorDokumentu]                    BIGINT          NOT NULL,
    [AIS]                                       NVARCHAR (5)    NULL,
    [DataPowiadomienia]                         DATE            NULL,
    [DataWystawieniaDecyzji]                    DATE            NULL,
    [DataPowstaniaDluguCelnego]                 DATE            NULL,
    [DataZwolnieniaTowaru]                      DATE            NULL,
    [DokumentArchiwalny]                        NVARCHAR (5)    NULL,
    [FormaOdroczenia]                           NVARCHAR (255)  NULL,
    [KwotaZabezpieczeniaTSW]                    DECIMAL (19, 2) NULL,
    [NaliczycOdsetki]                           INT             NULL,
    [NumerPozwolenia]                           NVARCHAR (255)  NULL,
    [OdroczonyTerminPlatnosci]                  DATE            NULL,
    [OkresRozliczeniowy]                        NVARCHAR (7)    NULL,
    [Ownres]                                    NVARCHAR (5)    NULL,
    [PozycjeRazem]                              DECIMAL (19, 2) NULL,
    [RazemBezZwol]                              DECIMAL (19, 2) NULL,
    [ProceduraCelna]                            INT             NULL,
    [ProceduraUproszczona]                      NVARCHAR (32)   NULL,
    [PrzyczynaZadluzenia]                       INT             NULL,
    [RodzajOdprawy]                             NVARCHAR (32)   NULL,
    [NumerDecyzji]                              NVARCHAR (255)  NULL,
    [NumerPozwoleniaSASP]                       NVARCHAR (4000) NULL,
    [OrganCelnySASP]                            NVARCHAR (32)   NULL,
    [TerminPlatnosci]                           DATE            NULL,
    [WpisDoRejestruDluguCelnego]                NVARCHAR (5)    NULL,
    [ZaswiadczenieOZaleglosciach]               NVARCHAR (3)    NULL,
    [NumerZabezpieczniaJednorazowego]           NVARCHAR (255)  NULL,
    [KwotaZabezpieczeniaJednorazowego]          DECIMAL (19, 2) NULL,
    [DataObciazeniaZabezpieczeniaJednorazowego] DATE            NULL,
    [NIPKontrahentaZabezpieczeniaJednorazowego] NVARCHAR (10)   NULL,
    [AdnotacjeIUwagi]                           NVARCHAR (512)  NULL,
    [RaportWyslaniaSK]                          NVARCHAR (MAX)  NULL,
    [NumerZabezpieczeniaGeneralnego]            NVARCHAR (4000) NULL,
    [KwotaZabezpieczeniaGeneralnego]            DECIMAL (19, 2) NULL,
    [DataObciazeniaZabezpieczeniaGeneralnego]   DATE            NULL,
    [CzyZabezpieczenieGeneralneObciazaAIS]      NVARCHAR (5)    NULL,
    [MigracjaReczna]                            NVARCHAR (4000) NULL,
    [DataArch]                                  DATE            NULL,
    [ID_Pismo_xml]                              BIGINT          NULL,
    [IdentyfikatorPodatnika]                    BIGINT          NOT NULL,
    [KodJednostki]                              NVARCHAR (6)    NULL,
    [DataRejestracjiRDC]                        DATE            NULL,
    [NaleznosciCelnoPodatkowe]                  NVARCHAR (255)  NULL,
    [StawkaOdsetek]                             NVARCHAR (255)  NULL,
    CONSTRAINT [DWNN_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DW]
) TEXTIMAGE_ON [FG_ZEF2DW];

