CREATE TABLE [zef2DW].[DZMW_Dokument] (
    [IdentyfikatorDokumentu]   BIGINT         NOT NULL,
    [DataDoreczenia]           DATE           NULL,
    [DataUprawomocnienia]      DATE           NULL,
    [DataWplywu]               DATE           NULL,
    [DataWystawienia]          DATE           NULL,
    [DokumentArchiwalny]       NVARCHAR (5)   NULL,
    [Koszty]                   NVARCHAR (19)  NULL,
    [PierwotnyNumerDokumentu]  NVARCHAR (255) NULL,
    [PierwotnyRodzajDokumentu] NVARCHAR (255) NULL,
    [Roztrzygniecie]           INT            NULL,
    [NumerPostanowienia]       NVARCHAR (255) NULL,
    [TerminPlatnosci]          DATE           NULL,
    [Typ]                      NVARCHAR (32)  NULL,
    [TypDochodu]               NVARCHAR (32)  NULL,
    [UchylenieZWinyOrganu]     NVARCHAR (5)   NULL,
    [WpisDoRejestru]           NVARCHAR (5)   NULL,
    [AdnotacjeIUwagi]          NVARCHAR (512) NULL,
    [SposobNaliczeniaOdsetek]  INT            NULL,
    [DataArch]                 DATE           NULL,
    [ID_Pismo_xml]             BIGINT         NULL,
    [IdentyfikatorPodatnika]   BIGINT         NOT NULL,
    CONSTRAINT [DZMW_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DW]
);

