CREATE TABLE [zef2DW].[SADU_Dokument] (
    [IdentyfikatorDokumentu]      BIGINT          NOT NULL,
    [AIS]                         NVARCHAR (5)    NULL,
    [DataPowiadomienia]           DATE            NULL,
    [DataPowstaniaDluguCelnego]   DATE            NULL,
    [DataUniewaznienia]           DATE            NULL,
    [DataZgloszeniaCelnego]       DATE            NULL,
    [DataZwolnieniaTowaru]        DATE            NULL,
    [FormaOdroczenia]             INT             NULL,
    [NazwaZglaszajacego]          NVARCHAR (255)  NULL,
    [NipZglaszajacego]            NVARCHAR (255)  NULL,
    [NumerPozwolenia]             NVARCHAR (255)  NULL,
    [NumerZglaszajacego]          NVARCHAR (32)   NULL,
    [OdroczonyTerminPlatnosci]    DATE            NULL,
    [PeselZglaszajacego]          NVARCHAR (255)  NULL,
    [PierwotnyNumerBiznesowy]     NVARCHAR (255)  NULL,
    [ObrotPocztowy]               NVARCHAR (5)    NULL,
    [PozycjeRazem]                DECIMAL (19, 2) NULL,
    [RazemBezZwol]                DECIMAL (19, 2) NULL,
    [ProceduraCelna]              INT             NULL,
    [RegonZglaszajacy]            NVARCHAR (4000) NULL,
    [RodzajZgloszenia]            NVARCHAR (32)   NULL,
    [NumerDokumentu]              NVARCHAR (255)  NULL,
    [TerminPlatnosci]             DATE            NULL,
    [WpisDoRejestruDluguCelnego]  NVARCHAR (5)    NULL,
    [ZaswiadczenieOZaleglosciach] NVARCHAR (255)  NULL,
    [ZglaszajacyGmina]            NVARCHAR (4000) NULL,
    [ZglaszajacyKodPocztowy]      NVARCHAR (4000) NULL,
    [ZglaszajacyKraj]             NVARCHAR (4000) NULL,
    [ZglaszajacyMiejscowosc]      NVARCHAR (4000) NULL,
    [ZglaszajacyNrDokumentu]      NVARCHAR (4000) NULL,
    [ZglaszajacyNrDomu]           NVARCHAR (4000) NULL,
    [ZglaszajacyNrEori]           NVARCHAR (4000) NULL,
    [ZglaszajacyNrLokalu]         NVARCHAR (4000) NULL,
    [ZglaszajacyNumerVatUe]       NVARCHAR (4000) NULL,
    [ZglaszajacyPoczta]           NVARCHAR (4000) NULL,
    [ZglaszajacyPowiat]           NVARCHAR (4000) NULL,
    [ZglaszajacyUlica]            NVARCHAR (4000) NULL,
    [ZglaszajacyUwagi]            NVARCHAR (4000) NULL,
    [ZglaszajacyWojewodztwo]      NVARCHAR (4000) NULL,
    [DataUrodzeniaZglaszajacego]  DATE            NULL,
    [ImieZglaszajacego]           NVARCHAR (4000) NULL,
    [NazwaPelnaZglaszajacego]     NVARCHAR (4000) NULL,
    [NazwiskoZglaszajacego]       NVARCHAR (4000) NULL,
    [RodzajZglaszajacego]         NVARCHAR (64)   NULL,
    [ZglaszajacySystem]           NVARCHAR (8)    NULL,
    [AdnotacjeIUwagi]             NVARCHAR (512)  NULL,
    [ProceduraUproszczona]        NVARCHAR (32)   NULL,
    [NumerPozwoleniaSASP]         NVARCHAR (4000) NULL,
    [OrganCelnySASP]              NVARCHAR (32)   NULL,
    [DataArch]                    DATE            NULL,
    [ID_Pismo_xml]                BIGINT          NULL,
    [IdentyfikatorPodatnika]      BIGINT          NOT NULL,
    [DataRejestracjiRDC]          DATE            NULL,
    CONSTRAINT [SADU_Dokument_PK] PRIMARY KEY CLUSTERED ([IdentyfikatorDokumentu] ASC) ON [FG_ZEF2DW]
);

