CREATE TABLE [stat].[dgt_eksport_sads_14] (
    [ek_pcn]                         VARCHAR (9)     NULL,
    [ek_zp]                          CHAR (1)        NULL,
    [ek_pcnp]                        VARCHAR (9)     NULL,
    [ek_kraj_przeznaczenia]          CHAR (2)        NULL,
    [ek_data_odprawy]                VARCHAR (4)     NULL,
    [ek_kod_kraju_sprzedazy]         CHAR (2)        NULL,
    [ek_kraj_wysylki]                CHAR (2)        NULL,
    [ek_kod_waluty]                  VARCHAR (3)     NULL,
    [ek_odbiorca]                    VARCHAR (14)    NULL,
    [ek_sklad_celny]                 CHAR (1)        NULL,
    [ek_urzad_celny]                 VARCHAR (2)     NULL,
    [ek_kod_procedury_celnej]        VARCHAR (4)     NULL,
    [ek_rodzaj_transakcji]           VARCHAR (2)     NULL,
    [ek_kod_transportu]              VARCHAR (2)     NULL,
    [ek_kod_kraju_srodka_transportu] CHAR (2)        NULL,
    [ek_kontener]                    VARCHAR (2)     NULL,
    [ek_znacznik_masy]               VARCHAR (1)     NULL,
    [ek_masa_netto]                  DECIMAL (19, 3) NULL,
    [ek_masa_brutto]                 DECIMAL (19, 3) NULL,
    [ek_ilosc]                       DECIMAL (19, 3) NULL,
    [ek_wartosc_pozycji]             DECIMAL (19, 3) NULL,
    [ek_wartosc_stat_zl]             DECIMAL (19, 3) NULL,
    [ek_wartosc_stat_usd]            DECIMAL (19, 3) NULL,
    [ek_wartosc_stat_euro]           DECIMAL (19, 3) NULL
);

