CREATE TABLE [stat].[dgt_import_intr_agr_reg_555] (
    [im_pcn]                         VARCHAR (8)     NULL,
    [im_zp]                          VARCHAR (1)     NULL,
    [im_pcnp]                        VARCHAR (8)     NULL,
    [im_kraj_pochodzenia]            CHAR (2)        NULL,
    [im_kraj_wysylki]                CHAR (2)        NULL,
    [im_odbiorca]                    VARCHAR (14)    NULL,
    [im_nip]                         VARCHAR (10)    NULL,
    [im_RokMc]                       INT             NULL,
    [im_rodzaj_transakcji]           VARCHAR (2)     NULL,
    [im_kod_transportu]              CHAR (1)        NULL,
    [im_kod_warunkow_dostawy]        VARCHAR (3)     NULL,
    [im_kod_izby_celnej]             VARCHAR (2)     NULL,
    [im_kod_procedury_celnej]        VARCHAR (4)     NULL,
    [im_znacznik_kategorii_progowej] CHAR (1)        NULL,
    [im_masa_netto]                  DECIMAL (19, 3) NULL,
    [im_ilosc]                       DECIMAL (19, 3) NULL,
    [im_wartosc_stat_zl]             DECIMAL (19, 3) NULL,
    [im_wartosc_stat_usd]            DECIMAL (19, 3) NULL,
    [im_wartosc_stat_euro]           DECIMAL (19, 3) NULL,
    [im_wartosc_faktury]             DECIMAL (19, 3) NULL,
    [im_iddoknr]                     BIGINT          NULL,
    [im_id_dok]                      VARCHAR (35)    NULL,
    [im_iddoknr_pozid]               BIGINT          NULL,
    [im_id_dok_pozid]                BIGINT          NULL,
    [im_id]                          BIGINT          NULL
);

