CREATE TABLE [stat].[dgt_import_sad_sads_14] (
    [im_pcn]                         VARCHAR (9)     NULL,
    [im_zp]                          CHAR (1)        NULL,
    [im_pcnp]                        VARCHAR (9)     NULL,
    [im_kraj_pochodzenia]            CHAR (2)        NULL,
    [im_data_odprawy]                VARCHAR (4)     NULL,
    [im_kraj_zakupu]                 CHAR (2)        NULL,
    [im_kraj_wysylki]                CHAR (2)        NULL,
    [im_kod_waluty]                  VARCHAR (3)     NULL,
    [im_odbiorca]                    VARCHAR (14)    NULL,
    [im_sklad_celny]                 CHAR (1)        NULL,
    [im_urzad_celny]                 VARCHAR (2)     NULL,
    [im_kod_procedury_celnej]        VARCHAR (4)     NULL,
    [im_rodzaj_transakcji]           VARCHAR (2)     NULL,
    [im_kod_transportu]              VARCHAR (2)     NULL,
    [im_kod_kraju_srodka_transportu] CHAR (2)        NULL,
    [im_kontener]                    VARCHAR (2)     NULL,
    [im_znacznik_masy]               CHAR (1)        NULL,
    [im_znacznik_podatku03]          CHAR (1)        NULL,
    [im_znacznik_podatku28]          CHAR (1)        NULL,
    [im_masa_netto]                  DECIMAL (19, 3) NULL,
    [im_masa_brutto]                 DECIMAL (19, 3) NULL,
    [im_ilosc]                       DECIMAL (19, 3) NULL,
    [im_wartosc_pozycji]             DECIMAL (19, 3) NULL,
    [im_wartosc_stat_zl]             DECIMAL (19, 3) NULL,
    [im_wartosc_stat_usd]            DECIMAL (19, 3) NULL,
    [im_wartosc_stat_euro]           DECIMAL (19, 3) NULL,
    [im_clo]                         DECIMAL (19, 3) NULL,
    [im_podatek03]                   DECIMAL (19, 3) NULL,
    [im_podatek28]                   DECIMAL (19, 3) NULL,
    [im_podatek813]                  DECIMAL (19, 3) NULL
);

