CREATE TABLE [stat].[dkt_plik_gus_poz] (
    [id_pliku]             BIGINT         NOT NULL,
    [lp]                   BIGINT         IDENTITY (1, 1) NOT NULL,
    [typ]                  VARCHAR (1)    NOT NULL,
    [pcn]                  VARCHAR (10)   NULL,
    [kraj_przeznaczenia]   VARCHAR (2)    NULL,
    [kraj_wysylki]         VARCHAR (2)    NULL,
    [kraj_pochodzenia]     VARCHAR (2)    NULL,
    [regon]                VARCHAR (14)   NULL,
    [miesiac_rok]          VARCHAR (4)    NULL,
    [rodzaj_transakcji]    VARCHAR (2)    NULL,
    [kod_transportu]       VARCHAR (1)    NULL,
    [kod_warunkow_dostawy] VARCHAR (3)    NULL,
    [kod_izby_celnej]      VARCHAR (2)    NULL,
    [kod_procedury_celnej] VARCHAR (4)    NULL,
    [masa_netto]           VARCHAR (15)   NULL,
    [ilosc]                VARCHAR (15)   NULL,
    [wartosc_stat_zl]      VARCHAR (15)   NULL,
    [wartosc_stat_usd]     VARCHAR (15)   NULL,
    [wartosc_stat_euro]    VARCHAR (15)   NULL,
    [komentarz]            VARCHAR (1024) NULL,
    [prog]                 VARCHAR (1)    NULL,
    [propozycja]           VARCHAR (1024) NULL,
    [status]               VARCHAR (1)    NULL,
    CONSTRAINT [pk_plik_gus_poz] PRIMARY KEY CLUSTERED ([id_pliku] ASC, [lp] ASC, [typ] ASC) ON [StatIndeksy]
);

