CREATE TABLE [stat].[eksport_intr_agr993] (
    [ek_pcn]                         VARCHAR (255) NULL,
    [ek_zp]                          VARCHAR (255) NULL,
    [ek_pcnp]                        VARCHAR (255) NULL,
    [ek_kraj_przeznaczenia]          VARCHAR (255) NULL,
    [ek_odbiorca]                    VARCHAR (255) NULL,
    [ek_nip]                         VARCHAR (255) NULL,
    [ek_RokMc]                       INT           NULL,
    [ek_rodzaj_transakcji]           VARCHAR (255) NULL,
    [ek_kod_transportu]              VARCHAR (255) NULL,
    [ek_kod_warunkow_dostawy]        VARCHAR (255) NULL,
    [ek_kod_izby_celnej]             VARCHAR (255) NULL,
    [ek_kod_procedury_celnej]        VARCHAR (255) NULL,
    [ek_znacznik_kategorii_progowej] VARCHAR (255) NULL,
    [ek_masa_netto]                  VARCHAR (255) NULL,
    [ek_ilosc]                       VARCHAR (255) NULL,
    [ek_wartosc_stat_zl]             VARCHAR (255) NULL,
    [ek_wartosc_stat_usd]            VARCHAR (255) NULL,
    [ek_wartosc_stat_euro]           VARCHAR (255) NULL,
    [ek_wartosc_faktury]             VARCHAR (255) NULL,
    [ek_iddoknr]                     VARCHAR (255) NULL,
    [ek_id_dok]                      VARCHAR (255) NULL,
    [ek_iddoknr_pozid]               VARCHAR (255) NULL,
    [ek_id_dok_pozid]                VARCHAR (255) NULL,
    [ek_id]                          VARCHAR (255) NULL
);

