CREATE TABLE [tr].[OperacjeTranzytowe] (
    [SID]                                       INT          NOT NULL,
    [IDKrajuPrzeznaczenia]                      CHAR (2)     NULL,
    [IDKrajuWysylki]                            CHAR (2)     NULL,
    [IDUrzeduPrzybycia]                         VARCHAR (8)  NULL,
    [IDWynikowKontroliUrzadPrzeznaczenia]       CHAR (2)     NULL,
    [IDWynikowKontroliUrzadWyjscia]             CHAR (2)     NULL,
    [AnalizaRyzykawUrzedziePrzeznaczenia]       DECIMAL (3)  NULL,
    [AnalizaRyzykaWUrzedzieTranzytowym]         DECIMAL (3)  NULL,
    [AnalizaRyzykawUrzedzieWyjscia]             DECIMAL (3)  NULL,
    [CzyTowaryWrazliwe]                         BIT          NULL,
    [DataPrzyjeciaZgloszenia]                   DATETIME     NULL,
    [DataKontroliUrzadPrzeznaczenia]            DATETIME     NULL,
    [DataKontroliUrzadWyjscia]                  DATETIME     NULL,
    [DataOdbioruKomunikatuIE18]                 DATETIME     NULL,
    [DataZamknieciaOperacjiTranzytowej]         DATETIME     NULL,
    [DataPrzekierowaniaDoOTS]                   DATETIME     NULL,
    [DataWyjasnieniaNiezgodnosci]               DATETIME     NULL,
    [TerminNaPrzybycie]                         DATETIME     NULL,
    [DataWaznosciPozwoleniaNaTranzyt]           DATETIME     NULL,
    [DataZapytaniaOZwolnienie]                  DATETIME     NULL,
    [DataZgloszeniaNiezgodnosci]                DATETIME     NULL,
    [DataZgloszonegoPrzybycia]                  DATETIME     NULL,
    [DataZmianyStatusu]                         DATETIME     NULL,
    [DataZwolnieniaTowaru]                      DATETIME     NULL,
    [DataZwolnieniaZOdpowiedzialnosci]          DATETIME     NULL,
    [DataZwrotuDokumentu]                       DATETIME     NULL,
    [DataPrzybycia]                             DATETIME     NULL,
    [IDDeklarowanegoUCPrzeznaczenia]            VARCHAR (8)  NULL,
    [LiczbaPlomb]                               DECIMAL (4)  NULL,
    [LRN]                                       VARCHAR (22) NULL,
    [MRN]                                       VARCHAR (21) NULL,
    [NrStronyKarnetuTIR]                        CHAR (2)     NULL,
    [ProcUprWUCWyjscia]                         CHAR (2)     NULL,
    [RodzajZwolnieniaTIR]                       CHAR (2)     NULL,
    [TranzytWysokiegoRyzyka]                    DECIMAL (1)  NULL,
    [SIDAdresuUrzeduPrzybycia]                  INT          NULL,
    [SIDGlownegoZobowiazanegoPDR]               INT          NULL,
    [SIDGlownegoZobowiazanego]                  INT          NULL,
    [SIDPrzedstawiajacegoPDR]                   INT          NULL,
    [SIDPrzedstawiajacego]                      INT          NULL,
    [StatusOperacjiTranzytowejWUCPrzeznaczenia] CHAR (3)     NULL,
    [StatusOperacjiTranzytowejWUCWyjscia]       CHAR (3)     NULL,
    [TypRozladunuTIR]                           CHAR (3)     NULL,
    [ProcUprWUCPrzeznaczenia]                   CHAR (1)     NULL,
    [TypDeklaracji]                             VARCHAR (5)  NULL,
    [IDUrzeduCelnegoPrzeznaczenia]              VARCHAR (8)  NULL,
    [IDUrzeduCelnegoWysylki]                    VARCHAR (8)  NULL,
    [WiazacaTrasaPrzewozu]                      CHAR (1)     NULL,
    CONSTRAINT [PK_OperacjeTranzytowe] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_TR],
    CONSTRAINT [FK_OperacjeTranzytowe_DeklarowanyUCPrzeznaczenia_Urzedy_IDUrzedu] FOREIGN KEY ([IDDeklarowanegoUCPrzeznaczenia]) REFERENCES [tr].[Urzedy] ([IDUrzedu]),
    CONSTRAINT [FK_OperacjeTranzytowe_IDUrzeduPrzybycia_Urzedy_IDUrzedu] FOREIGN KEY ([IDUrzeduPrzybycia]) REFERENCES [tr].[Urzedy] ([IDUrzedu]),
    CONSTRAINT [FK_OperacjeTranzytowe_IDWynikowKontroliUrzadPrzeznaczenia_WynikiKontroli_IDWynikuKontroli] FOREIGN KEY ([IDWynikowKontroliUrzadPrzeznaczenia]) REFERENCES [tr].[RodzajeWynikowKontroli] ([Id]),
    CONSTRAINT [FK_OperacjeTranzytowe_IDWynikowKontroliUrzadWyjscia_WynikiKontroli_IDWynikuKontroli] FOREIGN KEY ([IDWynikowKontroliUrzadWyjscia]) REFERENCES [tr].[RodzajeWynikowKontroli] ([Id]),
    CONSTRAINT [FK_OperacjeTranzytowe_SIDGlownegoZobowiazanego_Podmioty_SID] FOREIGN KEY ([SIDGlownegoZobowiazanego]) REFERENCES [tr].[Podmioty] ([SID]),
    CONSTRAINT [FK_OperacjeTranzytowe_SIDGlownegoZobowiazanegoPDR_PodmiotyPDR_SID] FOREIGN KEY ([SIDGlownegoZobowiazanegoPDR]) REFERENCES [tr].[PodmiotyPDR] ([SID]),
    CONSTRAINT [FK_OperacjeTranzytowe_SIDPrzedstawiajacego_Podmioty_SID] FOREIGN KEY ([SIDPrzedstawiajacego]) REFERENCES [tr].[Podmioty] ([SID]),
    CONSTRAINT [FK_OperacjeTranzytowe_SIDPrzedstawiajacegoPDR_PodmiotyPDR_SID] FOREIGN KEY ([SIDPrzedstawiajacegoPDR]) REFERENCES [tr].[PodmiotyPDR] ([SID]),
    CONSTRAINT [FK_OperacjeTranzytowe_TypDeklaracji_TypyDeklaracji_IDTypuDeklaracji] FOREIGN KEY ([TypDeklaracji]) REFERENCES [tr].[TypyDeklaracji] ([Id]),
    CONSTRAINT [FK_OperacjeTranzytowe_UrzadCelnyPrzeznaczenia_Urzedy_IDUrzedu] FOREIGN KEY ([IDUrzeduCelnegoPrzeznaczenia]) REFERENCES [tr].[Urzedy] ([IDUrzedu]),
    CONSTRAINT [FK_OperacjeTranzytowe_UrzadCelnyWysylki_Urzedy_IDUrzedu] FOREIGN KEY ([IDUrzeduCelnegoWysylki]) REFERENCES [tr].[Urzedy] ([IDUrzedu])
);

