CREATE TABLE [tr].[SzczegolyOperacjiTranzytowej] (
    [SID]                          INT            NOT NULL,
    [IDKrajuSrTranspPrzekrGranice] CHAR (2)       NULL,
    [IDKrajuPrzeznaczenia]         CHAR (2)       NULL,
    [IDKrajuNaWyjezdzie]           CHAR (2)       NULL,
    [IDKrajuWysylki]               CHAR (2)       NULL,
    [CalkowitaLiczbaOpakowan]      DECIMAL (7)    NULL,
    [CalkowitaLiczbaPozycji]       DECIMAL (5)    NULL,
    [CRN]                          VARCHAR (70)   NULL,
    [CzyKontener]                  BIT            NULL,
    [CzyTowaryWrazliwe]            BIT            NULL,
    [DaneBezpieczenstwa]           DECIMAL (1)    NULL,
    [KodMiejscaUznanego]           NVARCHAR (17)  NULL,
    [LiczbaPlomb]                  DECIMAL (4)    NULL,
    [MRN]                          VARCHAR (21)   NULL,
    [NazwaPrzedstawiciela]         NVARCHAR (105) NULL,
    [NumerReferencyjnyPrzewozu]    VARCHAR (35)   NULL,
    [NumerWersji]                  DECIMAL (3)    NOT NULL,
    [UmocowaniePrzedstawiciela]    NVARCHAR (105) NULL,
    [ProcUprWUCWyjscia]            CHAR (2)       NULL,
    [RodzajTransportuNaGranicy]    CHAR (2)       NULL,
    [TypTransportuPrzekrGranice]   VARCHAR (3)    NULL,
    [RodzajTransportu]             CHAR (2)       NULL,
    [SIDOperacjiTranzytowej]       INT            NULL,
    [SIDUpowaznionegoOdbiorcyPDR]  INT            NULL,
    [SIDUpowaznionegoOdbiorcy]     INT            NULL,
    [SIDNadawcyPDR]                INT            NULL,
    [SIDNadawcy]                   INT            NULL,
    [SIDOdbiorcyPDR]               INT            NULL,
    [SIDOdbiorcy]                  INT            NULL,
    [SIDPrzedstawicielaPDR]        INT            NULL,
    [TypDeklaracji]                VARCHAR (5)    NULL,
    [MiejsceUznane]                NVARCHAR (105) NULL,
    [WskaznikWarunkowSzczegolnych] CHAR (1)       NULL,
    [OplataTranspMetodaPlatnosci]  CHAR (1)       NULL,
    [NrSrTranspWMiejscuWyjscia]    VARCHAR (81)   NULL,
    [NrSrTranspPrzekrGranice]      VARCHAR (81)   NULL,
    CONSTRAINT [PK_SzczegolyOperacjiTranzytowej] PRIMARY KEY CLUSTERED ([SID] ASC) ON [FG_TR],
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_IDTypuDeklaracji_TypyDeklaracji_IDTypuDeklaracji] FOREIGN KEY ([TypDeklaracji]) REFERENCES [tr].[TypyDeklaracji] ([Id]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_RodzajTransportuNaGranicy_RodzajeTransportu_IDRodzajuTransportu] FOREIGN KEY ([RodzajTransportuNaGranicy]) REFERENCES [tr].[RodzajeTransportu] ([Id]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_RodzajTransportuWewnetrznego_RodzajeTransportu_ID] FOREIGN KEY ([RodzajTransportu]) REFERENCES [tr].[RodzajeTransportu] ([Id]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_SIDNumerWersji_WersjaOperacjiTranzytowej_SIDOperacjiTranzytowejNumerWersji] FOREIGN KEY ([SIDOperacjiTranzytowej], [NumerWersji]) REFERENCES [tr].[WersjaOperacjiTranzytowej] ([SIDOperacjiTranzytowej], [NumerWersji]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_SIDPodmiotuOdbierajacego_Podmioty_SID] FOREIGN KEY ([SIDOdbiorcy]) REFERENCES [tr].[Podmioty] ([SID]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_SIDPodmiotuOdbierajacego_PodmiotyPDR_SID] FOREIGN KEY ([SIDOdbiorcyPDR]) REFERENCES [tr].[PodmiotyPDR] ([SID]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_SIDPodmiotuWysylajacego_Podmioty_SID] FOREIGN KEY ([SIDNadawcy]) REFERENCES [tr].[Podmioty] ([SID]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_SIDPodmiotuWysylajacegoPDR_PodmiotyPDR_SID] FOREIGN KEY ([SIDNadawcyPDR]) REFERENCES [tr].[PodmiotyPDR] ([SID]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_SIDPrzedstawiciela_PodmiotyPDR_SID] FOREIGN KEY ([SIDPrzedstawicielaPDR]) REFERENCES [tr].[PodmiotyPDR] ([SID]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_SIDUpowaznionegoOdbiorcy_Podmioty_SID] FOREIGN KEY ([SIDUpowaznionegoOdbiorcy]) REFERENCES [tr].[Podmioty] ([SID]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_SIDUpowaznionegoOdbiorcyPDR_PodmiotyPDR_SID] FOREIGN KEY ([SIDUpowaznionegoOdbiorcyPDR]) REFERENCES [tr].[PodmiotyPDR] ([SID]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_TypTransportuPrzekrGranice_TypyTransportuPrzekrGranice_IDTypuTranspPrzekrGranice] FOREIGN KEY ([TypTransportuPrzekrGranice]) REFERENCES [tr].[TypyTransportuPrzekrGranice] ([Id]),
    CONSTRAINT [FK_SzczegolyOperacjiTranzytowej_WskaznikWarunkowSzczegolnych_WskaznikiWarunkowSzczegolnych_IDWskaznikaWarunkowSzczegolnych] FOREIGN KEY ([WskaznikWarunkowSzczegolnych]) REFERENCES [tr].[WskaznikiWarunkowSzczegolnych] ([Id])
);

