








-- =============================================
-- Author:		
-- Create date: 2014-07-07
-- Description:	
-- =============================================

CREATE PROCEDURE [pdr].[MergeAllPdrFromStage]
AS
BEGIN
	SET NOCOUNT ON;

	EXEC [pdr].[MergeTableFromStageHurtownia] 'c001';
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c009' usunięta ze źródła;
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c010';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c010_modele';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c028a';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c084';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c152';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c152_emailedi';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c152_grupa';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c152_reprezentantosobafizyczna';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c152_reprezentantpodmiotgospod';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c152_zakres';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c153';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c153_miejsceobjecia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c153_procedura';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c153_towar_wykluczony';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c153_tranzyt';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c153_urzad_objecia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c153_zamknieciecelne';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c160';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c169';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c170';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c171';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c171_sezon';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c171_pozycja';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c171_rola';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c211';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c211_zakresreprezentacji';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c212';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c212_na_urzad'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c213';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c226';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c227';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c228';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c228_okres_zakonczenia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c228_procedura';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c228_produkt';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c228_towar';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c228_urzad_nadzoru';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c228_urzad_objecia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c228_urzad_zakonczenia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c229';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c229_izba_objecia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c229_izba_procedura';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c229_procedura';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c232';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c232_sezon';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c232_pozycja'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3003';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3004';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3005';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3006';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3007';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3008';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3009';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3010';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3011';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3014';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3015';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3020';
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c3021' usunięta ze źródła;
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c3022' usunięta ze źródła; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3040';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3041';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3042';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3061';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3062';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3063';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3065'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3068';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3081';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3083';
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c3087' usunięta ze źródła; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3088';
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c3100' usunięta ze źródła;
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c3101' usunięta ze źródła; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3102';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3122';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3500';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3501';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3502'; 
--	EXEC [pdr].[MergeTableFromStageHurtownia] 'c350234' usunięta ze źródła; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3503';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3504';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3505'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3506';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3507'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3508';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3509'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3510';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3511';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3512'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c3513';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c400'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000_daneadresowe';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000_daneidentyfikacyjne';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000_oswiadczenia';
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000_statusosoby' usunięta ze źródła;
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000_epuap';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000_certyfikaty';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000_listywpisow';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4000_dokumenttozsamosci';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4001';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4001_reprezentacje';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4001_postepowanie';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4001_uprawnienia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4001_pelnomocnictwoszczegolne';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4001_pelnomocnictwoinne';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4001_rodzajprzedstawicielstwa';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4002';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4002_reprezentacje';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4002_uprawnienia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4002_rodzajprzedstawicielstwa';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_kontabankowe';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_statuspodmiotu';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_stanaktywnosciprawnoekon';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_kanalykomunikacji';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_akcyza';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_daneadresowe';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_obszarydzialalnosci';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_oswiadczenia';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_oddzialy';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_daneidentyfikacyjne';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_zakresdzialalnosci';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_szczegolydzialalnosci';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_epuap';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_daneadresoweoddzialu';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_numeryvatue';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_kodynace';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_kodypkd';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_daneadresowepodmiotuzagr';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c4003_miejscawykonywaniadziala';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c404';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c405'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c409';
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c410' usunięta ze źródła;
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c411' usunięta ze źródła; 
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c412' usunięta ze źródła;
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c413' usunięta ze źródła; 
	--EXEC [pdr].[MergeTableFromStageHurtownia] 'c414' usunięta ze źródła;
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c5000';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c501';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c502'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c503';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'c555';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's002'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's003';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's004'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's005';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's006';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's007'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's008';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's013';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's014'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's015';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's016';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's017'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's018';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's025';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's026';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's028';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's028b';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's029';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's030';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's031';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's033'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's034';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's035';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's036'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's037';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's045';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's047';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's048'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's049';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's050';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's051';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's053'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's054';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's057';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's058';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's060'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's061';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's063';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's067';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's068'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's069';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's070'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's075';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's076';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's077';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's078'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's079';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's080'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's081';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's082';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's083';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's085'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's086';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's087'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's088';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's090'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's091';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's095';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's097';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's100';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's101'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's103';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's106';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's108'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's109';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's109';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's110'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's111';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's112'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's113';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's120'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's123';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's124'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's125';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's133';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's137'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's138';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's147';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1500'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1501';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1502'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1503';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1504'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1505';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1506';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1507'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1508';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1509';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's151';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1510';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1511'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1513';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1514'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1515';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1516';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1517'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1518';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1519';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1520';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's1521';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's163';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's166';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's167';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's168';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's172'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's173';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's174';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's175'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's176';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's177';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's178';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's179';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's180'; 
	EXEC [pdr].[MergeTableFromStageHurtownia] 's181';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's182';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's183';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's185';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's186';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's187';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's188';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's189';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's189';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's190';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's191';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's192';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's193';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's208';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's210';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's215';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's216';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's217';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's219';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's220';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's221';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's222';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's223';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's224';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's225';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's233';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's235';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's237';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's300';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's302';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's303';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's304';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's305';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's306';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's307';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's308';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's311';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's312';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's313';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's314';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's315';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's319';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's320';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's321';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's406';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's407';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's408';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's504';
	--EXEC [pdr].[MergeTableFromStageHurtownia] 's551' usunięta ze źródła;
	--EXEC [pdr].[MergeTableFromStageHurtownia] 's552' usunięta ze źródła;
	--EXEC [pdr].[MergeTableFromStageHurtownia] 's553' usunięta ze źródła;
	EXEC [pdr].[MergeTableFromStageHurtownia] 's600';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's601';
	EXEC [pdr].[MergeTableFromStageHurtownia] 'st001';

	EXEC [pdr].[MergeTableFromStageHurtownia] 's250';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's330';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's370';
	EXEC [pdr].[MergeTableFromStageHurtownia] 's380';

END