CREATE TABLE [emcs2].[AIS_VERIFICATIONS_MVMT] (
    [ID]                   NUMERIC (38)  NOT NULL,
    [CREATE_DATE]          DATETIME2 (6) NOT NULL,
    [MODIFIED_DATE]        DATETIME2 (6) NOT NULL,
    [AIS_VERIFICATION_ID]  NUMERIC (38)  NOT NULL,
    [VERIFICATION_MSG_ID]  NUMERIC (38)  NOT NULL,
    [VERIFICATION_RESULT]  CHAR (1)      NOT NULL,
    [VERIFICATION_ARC]     VARCHAR (21)  NOT NULL,
    [VERIFICATION_MVMT_ID] NUMERIC (38)  NOT NULL,
    [CORRECTION_MSG_ID]    NUMERIC (38)  NULL,
    [CORRECTION_ARC]       VARCHAR (21)  NULL,
    [CORRECTION_MVMT_ID]   NUMERIC (38)  NULL,
    CONSTRAINT [PK_AIS_VERIFICATIONS_MVMT] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [CHK_AIS_VERIFICATIONS_MVMT] CHECK ([VERIFICATION_RESULT]='1' OR [VERIFICATION_RESULT]='0'),
    CONSTRAINT [FK_AIS_VERI_MVMT_1] FOREIGN KEY ([VERIFICATION_MSG_ID]) REFERENCES [emcs2].[EMCS_PROCESS_COMM] ([ID]),
    CONSTRAINT [FK_AIS_VERI_MVMT_2] FOREIGN KEY ([CORRECTION_MSG_ID]) REFERENCES [emcs2].[EMCS_PROCESS_COMM] ([ID]),
    CONSTRAINT [FK_AIS_VERI_MVMT_3] FOREIGN KEY ([AIS_VERIFICATION_ID]) REFERENCES [emcs2].[AIS_VERIFICATIONS] ([ID]),
    CONSTRAINT [FK_AIS_VERI_MVMT_4] FOREIGN KEY ([VERIFICATION_MVMT_ID]) REFERENCES [emcs2].[MOVEMENTS] ([ID]),
    CONSTRAINT [FK_AIS_VERI_MVMT_5] FOREIGN KEY ([CORRECTION_MVMT_ID]) REFERENCES [emcs2].[MOVEMENTS] ([ID])
);

