CREATE TABLE [emcs2].[AR_DOKUMENT] (
    [ID]                    NUMERIC (38)  NOT NULL,
    [PROCESS_COMM_ID]       NUMERIC (38)  NOT NULL,
    [NUMER_DOKUMENTU_ZISAR] VARCHAR (100) NOT NULL,
    [NUMER_DOKUMENTU_SO]    VARCHAR (100) NOT NULL,
    [SYSTEM_OPERACYJNY]     VARCHAR (36)  NOT NULL,
    [RODZAJ_DOKUMENTU]      VARCHAR (36)  NOT NULL,
    [NR_TYPU_KOMUNIKATU]    VARCHAR (36)  NOT NULL,
    [WYNIK_ANALIZY_RYZYKA]  VARCHAR (36)  NOT NULL,
    [UC_ZGLASZAJACY_DO_AAR] VARCHAR (20)  NOT NULL,
    [UC_KONTROLI_TOWAROW]   VARCHAR (20)  NULL,
    CONSTRAINT [PK_AR_DOKUMENT] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2]
);

