CREATE TABLE [emcs2].[AR_KONTROLA_POZYCJE] (
    [ID]                          NUMERIC (38) NOT NULL,
    [OBSLUGA_WSKAZAN_KONTROLI_ID] NUMERIC (38) NOT NULL,
    [NR_POZYCJI]                  NUMERIC (38) NOT NULL,
    CONSTRAINT [PK_AR_KONTROLA_POZYCJE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2]
);

