CREATE TABLE [emcs2].[AR_METODY_KONTROLI] (
    [ID]                          NUMERIC (38) NOT NULL,
    [OBSLUGA_WSKAZAN_KONTROLI_ID] NUMERIC (38) NOT NULL,
    [POZIOM_ZDEFINIOWANIA]        VARCHAR (36) NOT NULL,
    [METODA_KONTROLI]             VARCHAR (36) NOT NULL,
    CONSTRAINT [PK_AR_METODY_KONTROLI] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2]
);

