CREATE TABLE [emcs2].[ECS_DECLARATION_MVMTS] (
    [ID]              NUMERIC (38) NOT NULL,
    [ECSD_ID]         NUMERIC (38) NOT NULL,
    [ARC]             VARCHAR (21) NOT NULL,
    [SEQUENCE_NUMBER] NUMERIC (2)  NULL,
    CONSTRAINT [PK_ECS_DECLARATION_MVMTS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_ECS_DECLARATION_MVMTS_1] FOREIGN KEY ([ECSD_ID]) REFERENCES [emcs2].[ECS_DECLARATIONS] ([ID]),
    CONSTRAINT [UK_ECS_DECLARATION_MVMTS_1] UNIQUE NONCLUSTERED ([ARC] ASC, [ECSD_ID] ASC) ON [FG_EMCS2]
);

