CREATE TABLE [emcs2].[EMCS_ACO_READERS] (
    [ID]          NUMERIC (38)  NOT NULL,
    [ACO_ID]      NUMERIC (38)  NOT NULL,
    [ROLE_ID]     NUMERIC (10)  NOT NULL,
    [CREATE_DATE] DATETIME2 (6) NOT NULL,
    [CREATE_BY]   VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_ACO_READERS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_ACO_READERS_1] FOREIGN KEY ([ACO_ID]) REFERENCES [emcs2].[EMCS_ACO] ([ID])
);

