CREATE TABLE [emcs2].[EMCS_DOWN_DOWNSTREAM_MVMTS] (
    [ID]      NUMERIC (38) NOT NULL,
    [MVMT_ID] NUMERIC (38) NOT NULL,
    [ARC]     VARCHAR (21) NOT NULL,
    CONSTRAINT [PK_DOWN_DOWNSTREAM_MVMTS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [PK_DOWN_DOWNSTREAM_MVMTS_1] FOREIGN KEY ([MVMT_ID]) REFERENCES [emcs2].[EMCS_DOWN_MOVEMENTS] ([ID])
);

