CREATE TABLE [emcs2].[EMCS_UNAVAILABILITIES] (
    [ID]                    NUMERIC (38)  NOT NULL,
    [MEMBER_STATE_CODE]     VARCHAR (2)   NOT NULL,
    [TYPE]                  CHAR (1)      NOT NULL,
    [BUSINESS_PROCESS_CODE] CHAR (1)      NOT NULL,
    [EXPLANATION]           VARCHAR (350) NULL,
    [DOWNTIME_START]        DATETIME2 (6) NOT NULL,
    [DOWNTIME_END]          DATETIME2 (6) NULL,
    CONSTRAINT [PK_EMCS_UNAVAILABILITIES] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2]
);

