CREATE TABLE [emcs2].[EMCS_ACO_MOVEMENTS] (
    [ID]              NUMERIC (38) NOT NULL,
    [ACO_ID]          NUMERIC (38) NOT NULL,
    [ARC]             VARCHAR (21) NOT NULL,
    [SEQUENCE_NUMBER] NUMERIC (2)  NOT NULL,
    [MVMT_ID]         NUMERIC (38) NULL,
    CONSTRAINT [PK_ACO_MOVEMENTS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_ACO_MOVEMENTS_1] FOREIGN KEY ([ACO_ID]) REFERENCES [emcs2].[EMCS_ACO] ([ID]),
    CONSTRAINT [FK_ACO_MOVEMENTS_2] FOREIGN KEY ([MVMT_ID]) REFERENCES [emcs2].[MOVEMENTS] ([ID])
);

