CREATE TABLE [emcs2].[EMCS_USER_TASKS_SAD_DOCS] (
    [ID]           NUMERIC (38)  NOT NULL,
    [SAD_NUMBER]   NVARCHAR (63) NOT NULL,
    [USER_TASK_ID] NUMERIC (38)  NOT NULL,
    CONSTRAINT [PK_USER_TASKS_SAD_DOCUMENTS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_USER_TASKS_SAD_DOCUMENTS] FOREIGN KEY ([USER_TASK_ID]) REFERENCES [emcs2].[EMCS_USER_TASKS] ([ID])
);

