CREATE TABLE [emcs2].[EMCS_ACO_PROCESS_INSTANCES] (
    [ID]      NUMERIC (38) NOT NULL,
    [ACO_ID]  NUMERIC (38) NOT NULL,
    [PRIN_ID] NUMERIC (38) NOT NULL,
    CONSTRAINT [PK_ACO_PROCESS_INSTANCES] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_ACO_PROCESS_INSTANCES_1] FOREIGN KEY ([ACO_ID]) REFERENCES [emcs2].[EMCS_ACO] ([ID]),
    CONSTRAINT [FK_ACO_PROCESS_INSTANCES_2] FOREIGN KEY ([PRIN_ID]) REFERENCES [emcs2].[EMCS_PROCESS_INSTANCES] ([ID]),
    CONSTRAINT [UK_ACO_PROCESS_INSTANCES_1] UNIQUE NONCLUSTERED ([ACO_ID] ASC, [PRIN_ID] ASC) ON [FG_EMCS2]
);

