CREATE TABLE [emcs2].[EMCS_ACO_MESSAGE_RELATIONS] (
    [ID]            NUMERIC (38) NOT NULL,
    [ACOM1_ID]      NUMERIC (38) NOT NULL,
    [ACOM2_ID]      NUMERIC (38) NOT NULL,
    [RELATION_TYPE] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_ACO_MESSAGE_RELATIONS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_ACO_MESSAGE_RELATIONS_1] FOREIGN KEY ([ACOM1_ID]) REFERENCES [emcs2].[EMCS_ACO_MESSAGES] ([ID]),
    CONSTRAINT [FK_ACO_MESSAGE_RELATIONS_2] FOREIGN KEY ([ACOM2_ID]) REFERENCES [emcs2].[EMCS_ACO_MESSAGES] ([ID]),
    CONSTRAINT [UK_ACO_MESSAGE_RELATIONS_1] UNIQUE NONCLUSTERED ([ACOM2_ID] ASC, [ACOM1_ID] ASC) ON [FG_EMCS2]
);

