CREATE TABLE [emcs2].[MVMT_DOWNSTREAM_MOVEMENTS] (
    [ID]      NUMERIC (38) NOT NULL,
    [MVMT_ID] NUMERIC (38) NOT NULL,
    [ARC]     VARCHAR (21) NOT NULL,
    CONSTRAINT [PK_MVMT_DOWNSTREAM_MOVEMENTS] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_MVMT_DOWNSTREAM_MOVEMENTS_1] FOREIGN KEY ([MVMT_ID]) REFERENCES [emcs2].[MOVEMENTS] ([ID])
);

