CREATE TABLE [emcs2].[MVMT_QUATER_SHORTAGES] (
    [ID]                    NUMERIC (38)    NOT NULL,
    [MVMT_ID]               NUMERIC (38)    NOT NULL,
    [PRODUCT_ID]            NUMERIC (38)    NOT NULL,
    [CONSIGNOR_NRA]         VARCHAR (13)    NOT NULL,
    [CONSIGNEE_NRA]         VARCHAR (13)    NULL,
    [YEAR]                  NUMERIC (4)     NOT NULL,
    [QUATER]                NUMERIC (1)     NOT NULL,
    [DATE_OF_ARRIVAL]       DATETIME2 (6)   NOT NULL,
    [EXCISE_PRODUCT_CODE]   VARCHAR (4)     NOT NULL,
    [CN_CODE]               VARCHAR (8)     NULL,
    [TRANSPORT_MODE]        VARCHAR (2)     NULL,
    [KIND_OF_PACKAGES_CODE] VARCHAR (2)     NULL,
    [AMOUNT]                NUMERIC (18, 3) NOT NULL,
    [USER_TASK_ID]          NUMERIC (38)    NULL,
    CONSTRAINT [PK_MVMT_QUATER_SHORTAGES] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_MVMT_QUATER_SHORTAGES_MVMT_ID_MOVEMENTS_ID] FOREIGN KEY ([MVMT_ID]) REFERENCES [emcs2].[MOVEMENTS] ([ID]),
    CONSTRAINT [FK_MVMT_QUATER_SHORTAGES_PRODUCT_ID_MVMT_PRODUCTS_ID] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [emcs2].[MVMT_PRODUCTS] ([ID]),
    CONSTRAINT [FK_MVMT_QUATER_SHORTAGES_USER_TASK_ID_EMCS_USER_TASKS_ID] FOREIGN KEY ([USER_TASK_ID]) REFERENCES [emcs2].[EMCS_USER_TASKS] ([ID])
);

