CREATE TABLE [emcs2].[PACKAGING_CODES] (
    [ID]                           NUMERIC (38)   NOT NULL,
    [CODE]                         VARCHAR (2)    NOT NULL,
    [DESCRIPTION]                  NVARCHAR (900) NOT NULL,
    [DESCRIPTION_LANG_CODE]        VARCHAR (2)    NULL,
    [COUNTABLE]                    CHAR (1)       NOT NULL,
    [VALID_FROM]                   DATETIME2 (0)  NOT NULL,
    [VALID_TO]                     DATETIME2 (0)  NOT NULL,
    [ACTION_IDENTIFIER]            VARCHAR (20)   NOT NULL,
    [INVALIDATE_ACTION_IDENTIFIER] VARCHAR (20)   NULL,
    [SEED_CODE]                    VARCHAR (4)    NULL,
    CONSTRAINT [PK_PACKAGING_CODES] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [UK_PACKAGING_CODES_1] UNIQUE NONCLUSTERED ([CODE] ASC, [VALID_FROM] ASC) ON [FG_EMCS2]
);

