CREATE TABLE [emcs2].[REF_SD2_ZABEZPIECZENIA] (
    [ID]                   NUMERIC (38)  NOT NULL,
    [REF_SD2_PODMIOTY_NRA] VARCHAR (13)  COLLATE Polish_CS_AS NOT NULL,
    [NR_GRN]               NVARCHAR (51) NOT NULL,
    [OBOWIAZUJE_OD]        DATETIME2 (0) NOT NULL,
    [OBOWIAZUJE_DO]        DATETIME2 (0) NULL,
    [REF_SD2_PODMIOTY_TYP] NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_REF_SD2_ZABEZPIECZENIA] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2],
    CONSTRAINT [FK_REF_SD2_ZABEZPIECZENIA] FOREIGN KEY ([REF_SD2_PODMIOTY_NRA], [REF_SD2_PODMIOTY_TYP]) REFERENCES [emcs2].[REF_SD2_PODMIOTY] ([NRA], [TYP])
);

