CREATE TABLE [emcs2].[REF_SD2_UBYTKI_TRANS_SRODKI] (
    [UBT_ID] NUMERIC (38) NOT NULL,
    [RODZAJ] NVARCHAR (6) NOT NULL,
    CONSTRAINT [UTS_PK] PRIMARY KEY CLUSTERED ([UBT_ID] ASC, [RODZAJ] ASC) ON [FG_EMCS2],
    CONSTRAINT [UTS_UBT_FK] FOREIGN KEY ([UBT_ID]) REFERENCES [emcs2].[REF_SD2_UBYTKI_TRANS] ([ID])
);

