CREATE TABLE [emcs2].[REF_SD2_UBYTKI_TRANS_OPAK] (
    [UBT_ID] NUMERIC (38)  NOT NULL,
    [GRUPA]  NVARCHAR (12) NOT NULL,
    CONSTRAINT [UTO_PK] PRIMARY KEY CLUSTERED ([UBT_ID] ASC, [GRUPA] ASC) ON [FG_EMCS2],
    CONSTRAINT [UTO_UBT_FK] FOREIGN KEY ([UBT_ID]) REFERENCES [emcs2].[REF_SD2_UBYTKI_TRANS] ([ID])
);

