CREATE TABLE [emcs2].[REF_SD2_WLASCICIELE] (
    [ID]             NUMERIC (38)  NOT NULL,
    [NRA]            VARCHAR (13)  NOT NULL,
    [TYP]            NVARCHAR (15) NOT NULL,
    [WLASCICIEL_NRA] VARCHAR (13)  NOT NULL,
    [WLASCICIEL_TYP] NVARCHAR (15) NOT NULL,
    CONSTRAINT [PK_REF_SD2_WLASCICIELE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2]
);

