CREATE TABLE [emcs2].[TFILE] (
    [ID]                   NUMERIC (19)    NOT NULL,
    [CONTENTOBJECTID]      NUMERIC (19)    NULL,
    [FILESIZEBYTES]        NUMERIC (19)    NULL,
    [FILENAME]             VARCHAR (510)   NULL,
    [FILEEXTENSION]        VARCHAR (100)   NULL,
    [PRIMARYEDITORID]      NUMERIC (10)    NULL,
    [CHECKSUM]             CHAR (20)       NULL,
    [CREATEDON]            DATETIME2 (0)   NULL,
    [CREATEDBYID]          NUMERIC (10)    NULL,
    [ORIGINPATH]           VARCHAR (2000)  NULL,
    [CONTENT]              VARBINARY (MAX) NULL,
    [COMPRESSIONALGORITHM] VARCHAR (50)    NULL,
    CONSTRAINT [PK_TFILE] PRIMARY KEY CLUSTERED ([ID] ASC) ON [FG_EMCS2]
) TEXTIMAGE_ON [FG_EMCS2];

