CREATE TABLE [aes2].[DWA_Dokument] (
    [Id]                         NUMERIC (19)    NOT NULL,
    [LiczbaPozycji]              INT             NULL,
    [UrzadWyprowadzenia]         NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaPid]      INT             NULL,
    [LiczbaOpakowan]             INT             NULL,
    [MasaBrutto]                 NUMERIC (18, 3) NULL,
    [KontrolaWywozKod]           NVARCHAR (2)    NULL,
    [KontrolaWywozKodPid]        INT             NULL,
    [DataPrzyjecia]              DATETIME2 (3)   NULL,
    [CRN]                        NVARCHAR (70)   NULL,
    [MasaBruttoNaGranicy]        NUMERIC (18, 3) NULL,
    [PrzedstTowUC]               NVARCHAR (8)    NULL,
    [PrzedstTowUCPid]            INT             NULL,
    [PrzedstTowPozaUCKod]        NVARCHAR (255)  NULL,
    [PrzedstTowPozaUCKodPid]     INT             NULL,
    [PrzedstTowPozaUCBezKodu]    NVARCHAR (255)  NULL,
    [UrzadWyprowadzeniaZm]       NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaZmPid]    INT             NULL,
    [LiczbaPozycjiNaGranicy]     INT             NULL,
    [LiczbaPozycjiNaGranicyKom]  NVARCHAR (140)  NULL,
    [LiczbaOpakowanNaGranicy]    INT             NULL,
    [LiczbaOpakowanNaGranicyKom] NVARCHAR (140)  NULL,
    [MasaBruttoNaGranicyKom]     NVARCHAR (140)  NULL,
    [Skladowanie]                TINYINT         NULL,
    [PodpisElektroniczny]        TINYINT         NULL,
    [TerminNaDecyzjeOZwolnieniu] DATETIME2 (3)   NULL,
    [TerminAutomPrzyjZgloszenia] DATETIME2 (3)   NULL,
    [DataWyprowadzenia]          DATETIME2 (3)   NULL,
    [DataZatrzymania]            DATETIME2 (3)   NULL,
    [DataZwolnienia]             DATETIME2 (3)   NULL,
    [DataPrzedstawienia]         DATETIME2 (3)   NULL,
    [KodTypOplatTransp]          NVARCHAR (1)    NULL,
    [KodTypOplatTranspPid]       INT             NULL,
    [UrządCelnyWyprowadzenia]    NVARCHAR (8)    NULL,
    [UrzadZlozenia]              NVARCHAR (8)    NULL,
    [UrzadZlozeniaPid]           INT             NULL,
    [SpecyficzneOkolicznosci]    NVARCHAR (1)    NULL,
    [SpecyficzneOkolicznosciPid] INT             NULL,
    [DataZgody]                  DATETIME2 (3)   NULL,
    [DataRejestracji]            DATETIME2 (3)   NULL,
    [Status]                     NCHAR (1)       NULL,
    [DataPowiadomienia]          DATETIME2 (3)   NULL,
    [NrWlasny]                   NVARCHAR (22)   NULL,
    [MRN]                        NVARCHAR (35)   NULL,
    [EmailZwrotny]               NVARCHAR (80)   NULL,
    [Miejsce]                    NVARCHAR (35)   NULL,
    [Data]                       DATETIME2 (3)   NULL,
    [Telefon]                    NVARCHAR (15)   NULL,
    CONSTRAINT [DWA_Dokument$PK_DWA_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AES2]
);

