CREATE TABLE [aes2].[DWA_Towar] (
    [Id]                      NUMERIC (19)    NOT NULL,
    [MasaBrutto]              NUMERIC (18, 3) NULL,
    [NrPozycji]               INT             NULL,
    [StanTowaruNaGranicy]     NCHAR (1)       NULL,
    [CRN]                     NVARCHAR (70)   NULL,
    [OpisTowaruNaGranicy]     NVARCHAR (280)  NULL,
    [KodTowarowy]             NVARCHAR (8)    NULL,
    [KodTowarowyPid]          INT             NULL,
    [MasaBruttoNaGranicy]     NUMERIC (18, 3) NULL,
    [TowNiebezp]              NVARCHAR (4)    NULL,
    [TowNiebezpPid]           INT             NULL,
    [OplTransp]               NVARCHAR (1)    NULL,
    [OplTranspPid]            INT             NULL,
    [CRNNaGranicy]            NVARCHAR (70)   NULL,
    [KodTowarowyNaGranicy]    NVARCHAR (8)    NULL,
    [KodTowarowyNaGranicyPid] INT             NULL,
    [TowNiebezpNaGranicy]     NVARCHAR (4)    NULL,
    [TowNiebezpNaGranicyPid]  INT             NULL,
    [OplTranspNaGranicy]      NVARCHAR (1)    NULL,
    [OplTranspNaGranicyPid]   INT             NULL,
    [OpisTowaru]              NVARCHAR (280)  NULL,
    [IdDokDWA]                NUMERIC (19)    NULL,
    CONSTRAINT [DWA_Towar$PK_DWA_Towar] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AES2],
    CONSTRAINT [FK__DWA_Towar_IdDokDWA__DWA_Dokument_id] FOREIGN KEY ([IdDokDWA]) REFERENCES [aes2].[DWA_Dokument] ([Id])
);

