CREATE TABLE [aes2].[DWU_Dokument] (
    [DataPrzyjecia]                      DATETIME2 (3)   NULL,
    [DataZgody]                          DATETIME2 (3)   NULL,
    [UrzadWyprowadzenia]                 NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaPid]              INT             NULL,
    [UCZlozenia]                         NVARCHAR (8)    NULL,
    [UCZlozeniaPid]                      INT             NULL,
    [CRN]                                NVARCHAR (70)   NULL,
    [PodpisElektroniczny]                TINYINT         NULL,
    [MasaBrutto]                         NUMERIC (18, 3) NULL,
    [LiczbaPozycji]                      INT             NULL,
    [LiczbaOpakowan]                     INT             NULL,
    [SpecyficzneOkolicznosci]            NVARCHAR (1)    NULL,
    [SpecyficzneOkolicznosciPid]         INT             NULL,
    [Data]                               DATETIME2 (3)   NULL,
    [Telefon]                            NVARCHAR (15)   NULL,
    [Miejsce]                            NVARCHAR (35)   NULL,
    [Status]                             NCHAR (1)       NULL,
    [KodTypOplatTransp]                  NVARCHAR (1)    NULL,
    [KodTypOplatTranspPid]               INT             NULL,
    [Id]                                 NUMERIC (19)    NOT NULL,
    [DataCzasZgodyNaPrzekroczenieGranic] DATETIME2 (3)   NULL,
    [PrzedstTowUC]                       NVARCHAR (8)    NULL,
    [PrzedstTowUCPid]                    INT             NULL,
    [PrzedstTowPozaUCKod]                NVARCHAR (255)  NULL,
    [PrzedstTowPozaUCKodPid]             INT             NULL,
    [PrzedstTowPozaUCBezKodu]            NVARCHAR (255)  NULL,
    [NrWlasny]                           NVARCHAR (22)   NULL,
    [MRN]                                NVARCHAR (35)   NULL,
    CONSTRAINT [DWU_Dokument$PK_DWU_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AES2]
);

