CREATE TABLE [aes2].[QUERY_Towar] (
    [Id]                           NUMERIC (19)    NOT NULL,
    [KodTowaruNomenklaturaScalona] NVARCHAR (8)    NULL,
    [DodatkowyKodKrajowy]          NVARCHAR (4)    NULL,
    [KodTARIC]                     NVARCHAR (2)    NULL,
    [DodKodTARIC1]                 NVARCHAR (4)    NULL,
    [DodKodTARIC1Pid]              INT             NULL,
    [DodKodTARIC2]                 NVARCHAR (4)    NULL,
    [DodKodTARIC2Pid]              INT             NULL,
    [KrajPrzeznaczenia]            NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaPid]         INT             NULL,
    [KrajWysylki]                  NVARCHAR (2)    NULL,
    [KrajWysylkiPid]               INT             NULL,
    [CRN]                          NVARCHAR (70)   NULL,
    [OpisTowaru]                   NVARCHAR (280)  NULL,
    [KodJezykaOpisuTowaru]         NVARCHAR (2)    NULL,
    [MasaBrutto]                   NUMERIC (11, 3) NULL,
    [NrPozycji]                    INT             NULL,
    [ProceduraKrajowa]             NVARCHAR (3)    NULL,
    [ProceduraKrajowaPid]          INT             NULL,
    [MasaNetto]                    NUMERIC (11, 3) NULL,
    [ProceduraPoprz]               NVARCHAR (2)    NULL,
    [ProceduraPoprzPid]            INT             NULL,
    [Procedura]                    NVARCHAR (2)    NULL,
    [ProceduraPid]                 INT             NULL,
    [WartoscStatystyczna]          NUMERIC (17, 2) NULL,
    [WalutaWartosciStat]           NVARCHAR (3)    NULL,
    [WalutaWartosciStatPid]        INT             NULL,
    [KodTypOplatTransp]            NVARCHAR (1)    NULL,
    [KodTypOplatTranspPid]         INT             NULL,
    [TowarNiebezpieczny]           NVARCHAR (4)    NULL,
    [TowarNiebezpiecznyPid]        INT             NULL,
    [IdDokQUERY]                   NUMERIC (19)    NULL,
    CONSTRAINT [QUERY_Towar$PK_QUERY_Towar] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AES2],
    CONSTRAINT [FK__QUERY_Towar_IdDokQUERY__QUERY_Dokument_id] FOREIGN KEY ([IdDokQUERY]) REFERENCES [aes2].[QUERY_Dokument] ([Id])
);

