CREATE TABLE [aes2].[QUERY_Dokument] (
    [Id]                                 NUMERIC (19)    NOT NULL,
    [DataPrzyjecia]                      DATETIME2 (3)   NULL,
    [UrzadWyprowadzenia]                 NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaPid]              INT             NULL,
    [UrzadWywozu]                        NVARCHAR (8)    NULL,
    [UrzadWywozuPid]                     INT             NULL,
    [UrzadZapytania]                     NVARCHAR (8)    NULL,
    [UrzadZapytaniaPid]                  INT             NULL,
    [KonteneryNaGranicy]                 NVARCHAR (3)    NULL,
    [PrzewidywanaDataDotarciaTowaru]     DATETIME2 (3)   NULL,
    [KodWynikuKontroli]                  NVARCHAR (2)    NULL,
    [KodWynikuKontroliPid]               INT             NULL,
    [KrajWysylki]                        NVARCHAR (2)    NULL,
    [KrajWysylkiPid]                     INT             NULL,
    [KrajPrzeznaczenia]                  NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaPid]               INT             NULL,
    [CRN]                                NVARCHAR (70)   NULL,
    [DataWygenerowaniaZapytania]         DATETIME2 (3)   NULL,
    [TypDeklaracji]                      NVARCHAR (9)    NULL,
    [DataZlozeniaZgloszenia]             DATETIME2 (3)   NULL,
    [KodJezykaDokEAD]                    NVARCHAR (2)    NULL,
    [KodJezykaDokEADPid]                 INT             NULL,
    [TypStatusuOperWywoz]                NVARCHAR (3)    NULL,
    [MasaBrutto]                         NUMERIC (11, 3) NULL,
    [IdSrodkaTransportu]                 NVARCHAR (27)   NULL,
    [KodJezykaOpisuSrodkaTransportu]     NVARCHAR (2)    NULL,
    [DataZwolnienia]                     DATETIME2 (3)   NULL,
    [MRN]                                NVARCHAR (21)   NULL,
    [LiczbaPozycji]                      INT             NULL,
    [LiczbaOpakowan]                     INT             NULL,
    [DodatkPytanieOStatusOperWywoz]      NVARCHAR (350)  NULL,
    [KodJezykaDodatkPytania]             NVARCHAR (2)    NULL,
    [OdpNaDodatkPytanieOStatusOperWywoz] NVARCHAR (350)  NULL,
    [KodJezykaOdp]                       NVARCHAR (2)    NULL,
    [PrzyczynaODeklaracje]               NVARCHAR (3)    NULL,
    [LiczbaZamkniecCelnych]              INT             NULL,
    [SpecyficzneOkolicznosci]            NVARCHAR (1)    NULL,
    [SpecyficzneOkolicznosciPid]         INT             NULL,
    [Status]                             NCHAR (1)       NULL,
    [MP]                                 NVARCHAR (1)    NULL,
    [MPPid]                              NVARCHAR (1)    NULL,
    [IdKomunikatuZapytania ]             NUMERIC (19)    NULL,
    [EksportDoAnalityki]                 NCHAR (1)       NOT NULL,
    [KrajWysylki1]                       NVARCHAR (2)    NULL,
    [KrajWysylki1Pid]                    INT             NULL,
    CONSTRAINT [QUERY_Dokument$PK_QUERY_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AES2]
);

