CREATE TABLE [aes2].[ZUZ_Dokument] (
    [UrzadWyprowadzenia]                 NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaPid]              NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaWUzupeln]         NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaWUzupelnPid]      NVARCHAR (8)    NULL,
    [UrzadWywozu]                        NVARCHAR (8)    NULL,
    [UrzadWywozuPid]                     NVARCHAR (8)    NULL,
    [UrzadWywozuWUzupeln]                NVARCHAR (8)    NULL,
    [UrzadWywozuWUzupelnPid]             NVARCHAR (8)    NULL,
    [UrzadZgloszeniaUzupeln]             NVARCHAR (255)  NULL,
    [UrzadZgloszeniaUzupelnPid]          NVARCHAR (255)  NULL,
    [UrzadZgloszeniaUzupelnWUzupeln]     NVARCHAR (255)  NULL,
    [UrzadZgloszeniaUzupelnWUzupelnPid]  NVARCHAR (255)  NULL,
    [Kontenery]                          TINYINT         NULL,
    [KonteneryWUzupeln]                  TINYINT         NULL,
    [KrajPrzeznaczenia]                  NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaPid]               NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaWUzupeln]          NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaWUzupelnPid]       NVARCHAR (2)    NULL,
    [KrajWysylki]                        NVARCHAR (2)    NULL,
    [KrajWysylkiPid]                     NVARCHAR (2)    NULL,
    [KrajWysylkiWUzupeln]                NVARCHAR (2)    NULL,
    [KrajWysylkiWUzupelnPid]             NVARCHAR (2)    NULL,
    [CRN]                                NVARCHAR (70)   NULL,
    [CRNWUzupeln]                        NVARCHAR (70)   NULL,
    [1a]                                 NVARCHAR (2)    NULL,
    [1aPid]                              NVARCHAR (2)    NULL,
    [1b]                                 NVARCHAR (1)    NULL,
    [1bPid]                              NVARCHAR (1)    NULL,
    [KodWarunkowDostawy]                 NVARCHAR (3)    NULL,
    [KodWarunkowDostawyPid]              NVARCHAR (3)    NULL,
    [KodWarunkowDostawyWUzupeln]         NVARCHAR (3)    NULL,
    [KodWarunkowDostawyWUzupelnPid]      NVARCHAR (3)    NULL,
    [MiejsceDostawy]                     NVARCHAR (35)   NULL,
    [KodMiejscaDostawy]                  NVARCHAR (1)    NULL,
    [KodMiejscaDostawyPid]               NVARCHAR (1)    NULL,
    [KodMiejscaDostawyWUzupeln]          NVARCHAR (1)    NULL,
    [KodMiejscaDostawyWUzupelnPid]       NVARCHAR (1)    NULL,
    [PodpisElektroniczny]                TINYINT         NULL,
    [MasaBrutto]                         NUMERIC (18, 3) NULL,
    [MasaBruttoWUzupeln]                 NUMERIC (18, 3) NULL,
    [ZnakiSrodkaPrzewoz]                 NVARCHAR (31)   NULL,
    [ZnakiSrodkaPrzewozWUzupeln]         NVARCHAR (31)   NULL,
    [TrWewnRodzaj]                       NVARCHAR (2)    NULL,
    [TrWewnRodzajPid]                    NVARCHAR (2)    NULL,
    [TrWewnRodzajWUzupeln]               NVARCHAR (2)    NULL,
    [TrWewnRodzajWUzupelnPid]            NVARCHAR (2)    NULL,
    [UC]                                 NVARCHAR (8)    NULL,
    [UCPid]                              NVARCHAR (8)    NULL,
    [UCWUzupeln]                         NVARCHAR (8)    NULL,
    [UCWUzupelnPid]                      NVARCHAR (8)    NULL,
    [MiejsceKodPozaUC]                   NVARCHAR (17)   NULL,
    [MiejsceKodPozaUCPid]                NVARCHAR (17)   NULL,
    [MiejsceKodPozaUCWUzupeln]           NVARCHAR (17)   NULL,
    [MiejsceKodPozaUCWUzupelnPid]        NVARCHAR (17)   NULL,
    [MiejsceBezKoduPozaUC]               NVARCHAR (35)   NULL,
    [LiczbaPozycji]                      INT             NULL,
    [LiczbaPozycjiWUzupeln]              INT             NULL,
    [LiczbaOpakowan]                     INT             NULL,
    [LiczbaOpakowanWUzupeln]             INT             NULL,
    [Stanowisko]                         NVARCHAR (35)   NULL,
    [Data]                               DATETIME2 (3)   NULL,
    [NazwiskoImie]                       NVARCHAR (35)   NULL,
    [Telefon]                            NVARCHAR (15)   NULL,
    [Miejsce]                            NVARCHAR (35)   NULL,
    [SkladTowPozaUCKod]                  NVARCHAR (17)   NULL,
    [SkladTowPozaUCKodWUzupeln]          NVARCHAR (17)   NULL,
    [SkladTowPozaUCBezKodu]              NVARCHAR (35)   NULL,
    [ZamkCelneLiczba]                    INT             NULL,
    [ZamkCelneLiczbaWUzupeln]            INT             NULL,
    [SpecyficzneOkolicznosci]            NVARCHAR (1)    NULL,
    [SpecyficzneOkolicznosciPid]         NVARCHAR (1)    NULL,
    [SpecyficzneOkolicznosciWUzupeln]    NVARCHAR (1)    NULL,
    [SpecyficzneOkolicznosciWUzupelnPid] NVARCHAR (1)    NULL,
    [Status]                             NCHAR (1)       NULL,
    [Skladowanie]                        TINYINT         NULL,
    [SkladowanieWUzupeln]                TINYINT         NULL,
    [SumaOplatPozycjiTowar]              NUMERIC (17, 2) NULL,
    [SumaOplatPozycjiTowarWUzupeln]      NUMERIC (17, 2) NULL,
    [Wartosc]                            NUMERIC (17, 2) NULL,
    [WartoscWUzupeln]                    NUMERIC (17, 2) NULL,
    [KodWaluty]                          NVARCHAR (3)    NULL,
    [KodWalutyPid]                       NVARCHAR (3)    NULL,
    [KodWalutyWUzupeln]                  NVARCHAR (3)    NULL,
    [KodWalutyWUzupelnPid]               NVARCHAR (3)    NULL,
    [KursWaluty]                         NUMERIC (11, 5) NULL,
    [KursWalutyWUzupeln]                 NUMERIC (11, 5) NULL,
    [KodRodzajuTransakcji]               NVARCHAR (2)    NULL,
    [KodRodzajuTransakcjiPid]            NVARCHAR (2)    NULL,
    [KodRodzajuTransakcjiWUzupeln]       NVARCHAR (2)    NULL,
    [KodRodzajuTransakcjiWUzupelnPid]    NVARCHAR (2)    NULL,
    [TrDeklKraj]                         NVARCHAR (2)    NULL,
    [TrDeklKrajPid]                      NVARCHAR (2)    NULL,
    [TrDeklKrajWUzupeln]                 NVARCHAR (2)    NULL,
    [TrDeklKrajWUzupelnPid]              NVARCHAR (2)    NULL,
    [TrWewnZnaki]                        NVARCHAR (31)   NULL,
    [TrWewnZnakiWUzupeln]                NVARCHAR (31)   NULL,
    [TrDeklRodzaj]                       NVARCHAR (2)    NULL,
    [TrDeklRodzajPid]                    NVARCHAR (2)    NULL,
    [TrDeklRodzajWUzupeln]               NVARCHAR (2)    NULL,
    [TrDeklRodzajWUzupelnPid]            NVARCHAR (2)    NULL,
    [KodTypOplatTransp]                  NVARCHAR (1)    NULL,
    [KodTypOplatTranspPid]               NVARCHAR (1)    NULL,
    [KodTypOplatTranspWUzupeln]          NVARCHAR (1)    NULL,
    [KodTypOplatTranspWUzupelnPid]       NVARCHAR (1)    NULL,
    [TowNiebezp]                         NVARCHAR (4)    NULL,
    [TowNiebezpPid]                      NVARCHAR (4)    NULL,
    [TowNiebezpWUzupelnPid]              NVARCHAR (4)    NULL,
    [KodKraju]                           NVARCHAR (2)    NULL,
    [KodKrajuPid]                        NVARCHAR (2)    NULL,
    [KodKrajuNaZWU]                      NVARCHAR (2)    NULL,
    [KodKrajuNaZWUPid]                   NVARCHAR (2)    NULL,
    [MiejsceSkodyfikowanePozaUC]         NVARCHAR (14)   NULL,
    [MiejsceSkodyfikowanePozaUCnaZWU]    NVARCHAR (14)   NULL,
    [Typ]                                NVARCHAR (1)    NULL,
    [TypNaZWU]                           NVARCHAR (1)    NULL,
    [Id]                                 NUMERIC (19)    NOT NULL,
    [DataPowiazaniaZgloszen]             DATETIME2 (3)   NULL,
    [UCZlozenia]                         NVARCHAR (8)    NULL,
    [UCZlozeniaPid]                      NVARCHAR (8)    NULL,
    [TowNiebezpUzupeln]                  NVARCHAR (4)    NULL,
    [NrWlasny]                           NVARCHAR (22)   NULL,
    [MRN]                                NVARCHAR (35)   NULL,
    CONSTRAINT [ZUZ_Dokument$PK_ZUZ_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AES2]
);

