CREATE TABLE [aes2].[ZWP_Dokument] (
    [Id]                               NUMERIC (19)    NOT NULL,
    [MasaBrutto]                       NUMERIC (18, 3) NULL,
    [NrWlasny]                         NVARCHAR (22)   NULL,
    [MRN]                              NVARCHAR (35)   NULL,
    [MasaBruttoNaGranicyKom]           NVARCHAR (510)  NULL,
    [LiczbaPozycjiNaGranicyKom]        NVARCHAR (280)  NULL,
    [KontrolaWyprKod]                  NVARCHAR (2)    NULL,
    [KontrolaWyprKodPid]               NVARCHAR (2)    NULL,
    [KontrolaWyprStan]                 TINYINT         NULL,
    [Miejsce]                          NVARCHAR (70)   NULL,
    [Data]                             DATETIME2 (3)   NULL,
    [ZamkCelneLiczba]                  INT             NULL,
    [KontrolaWywozKod]                 NVARCHAR (2)    NULL,
    [KontrolaWywozKodPid]              NVARCHAR (2)    NULL,
    [PrzedstTowUC]                     NVARCHAR (8)    NULL,
    [PrzedstTowUCPid]                  NVARCHAR (8)    NULL,
    [PrzedstTowPozaUCKod]              NVARCHAR (510)  NULL,
    [PrzedstTowPozaUCKodPid]           NVARCHAR (17)   NULL,
    [PrzedstTowPozaUCBezKodu]          NVARCHAR (17)   NULL,
    [SkladTowPozaUCKod]                NVARCHAR (510)  NULL,
    [SkladTowPozaUCBezKodu]            NVARCHAR (17)   NULL,
    [ZnakiSrodkaPrzewozNaGranicy]      NVARCHAR (255)  NULL,
    [ZnakiSrodkaPrzewozNaGranicyKom]   NVARCHAR (510)  NULL,
    [ZnakiSrodkaPrzewoz]               NVARCHAR (510)  NULL,
    [CzyECS]                           TINYINT         NULL,
    [UrzadWyprowadzenia]               NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaPid]            NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaDekl]           NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaDeklPid]        NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaZm]             NVARCHAR (8)    NULL,
    [UrzadWyprowadzeniaZmPid]          NVARCHAR (8)    NULL,
    [Skladowanie]                      TINYINT         NULL,
    [UrzadWywozu]                      NVARCHAR (8)    NULL,
    [UrzadWywozuPid]                   NVARCHAR (8)    NULL,
    [1a]                               NVARCHAR (2)    NULL,
    [1aPid]                            NVARCHAR (2)    NULL,
    [LiczbaPozycji]                    INT             NULL,
    [LiczbaPozycjiNaGranicy]           INT             NULL,
    [LiczbaOpakowan]                   INT             NULL,
    [LiczbaOpakowanNaGranicy]          INT             NULL,
    [LiczbaOpakowanNaGranicyKom]       NVARCHAR (280)  NULL,
    [KrajWysylki]                      NVARCHAR (2)    NULL,
    [KrajWysylkiPid]                   NVARCHAR (2)    NULL,
    [KrajPrzeznaczenia]                NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaPid]             NVARCHAR (2)    NULL,
    [Kontenery]                        TINYINT         NULL,
    [MasaBruttoNaGranicy]              NUMERIC (18, 3) NULL,
    [DataPrzyjecia]                    DATETIME2 (3)   NULL,
    [DataZwolnienia]                   DATETIME2 (3)   NULL,
    [KodEAD]                           NVARCHAR (2)    NULL,
    [KodEADPid]                        NVARCHAR (2)    NULL,
    [TerminWysylkiKontr]               DATETIME2 (3)   NULL,
    [TerminUrzadWypr]                  DATETIME2 (3)   NULL,
    [DataPrzedstawienia]               DATETIME2 (3)   NULL,
    [DataPowiadomienia]                DATETIME2 (3)   NULL,
    [Status]                           NCHAR (1)       NOT NULL,
    [DataWyprowadzenia]                DATETIME2 (3)   NULL,
    [DataZatrzymania]                  DATETIME2 (3)   NULL,
    [CRN]                              NVARCHAR (70)   NULL,
    [CRNRozbieznosc]                   NVARCHAR (70)   NULL,
    [CRNRozbieznoscKom]                NVARCHAR (140)  NULL,
    [DataWyslania]                     DATETIME2 (3)   NULL,
    [KodTypOplatTransp]                NVARCHAR (1)    NULL,
    [KodTypOplatTranspPid]             NVARCHAR (1)    NULL,
    [KodTypOplatTranspRozbieznosc]     NVARCHAR (1)    NULL,
    [KodTypOplatTranspRozbieznoscKom]  NVARCHAR (140)  NULL,
    [SpecyficzneOkolicznosci]          NVARCHAR (1)    NULL,
    [SpecyficzneOkolicznosciPid]       NVARCHAR (1)    NULL,
    [FaktycznaDataPrzedstawienia]      DATETIME2 (3)   NULL,
    [KodWynikuKontroliPrzedTranzyt]    NVARCHAR (2)    NULL,
    [KodWynikuKontroliPrzedTranzytPid] NVARCHAR (2)    NULL,
    [Tranzyt]                          BIT             NOT NULL,
    CONSTRAINT [ZWP_Dokument$PK_ZWP_Dokument] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AES2]
);

