CREATE TABLE [aes2].[ZWU_Towar] (
    [Id]                            NUMERIC (19)    NOT NULL,
    [MasaBrutto]                    NUMERIC (18, 3) NULL,
    [KrajWysylki]                   NVARCHAR (2)    NULL,
    [KrajWysylkiPid]                NVARCHAR (2)    NULL,
    [KrajPrzeznaczenia]             NVARCHAR (2)    NULL,
    [KrajPrzeznaczeniaPid]          NVARCHAR (2)    NULL,
    [MasaBruttoNaGranicy]           NUMERIC (18, 3) NULL,
    [CRN]                           NVARCHAR (210)  NULL,
    [TowarNiebezpieczny]            NVARCHAR (4)    NULL,
    [TowarNiebezpiecznyPid]         NVARCHAR (4)    NULL,
    [SumaOplat]                     NUMERIC (17, 2) NULL,
    [NrPozycji]                     INT             NULL,
    [StanNaGranicy]                 NCHAR (1)       NOT NULL,
    [WartoscStatystyczna]           NUMERIC (17, 2) NULL,
    [Waluta]                        NVARCHAR (3)    NULL,
    [OpisTowaruNaGranicy]           NVARCHAR (840)  NULL,
    [KodTowarowy]                   NVARCHAR (8)    NULL,
    [KodTowarowyPid]                NVARCHAR (8)    NULL,
    [KodTARIC]                      NVARCHAR (2)    NULL,
    [KodTowarowyNaGranicy]          NVARCHAR (22)   NULL,
    [KodTowarowyNaGranicyPid]       NVARCHAR (22)   NULL,
    [KrajPochodzenia]               NVARCHAR (2)    NULL,
    [KrajPochodzeniaPid]            NVARCHAR (2)    NULL,
    [Procedura]                     NVARCHAR (2)    NULL,
    [ProceduraPid]                  NVARCHAR (2)    NULL,
    [ProceduraPoprz]                NVARCHAR (2)    NULL,
    [ProceduraPoprzPid]             NVARCHAR (2)    NULL,
    [ProceduraSzczegoly]            NVARCHAR (3)    NULL,
    [ProceduraSzczegolyPid]         NVARCHAR (3)    NULL,
    [MasaNetto]                     NUMERIC (18, 3) NULL,
    [MasaNettoNaGranicy]            NUMERIC (18, 3) NULL,
    [IloscUjm]                      NUMERIC (19, 3) NULL,
    [OpisTowaru]                    NVARCHAR (840)  NULL,
    [IdDokZWU]                      NUMERIC (19)    NULL,
    [KodTypOplatTransp]             NVARCHAR (1)    NULL,
    [KodTypOplatTranspPid]          NVARCHAR (1)    NULL,
    [CRNNaGranicy]                  NVARCHAR (70)   NULL,
    [DodKodTARIC1NaGranicy]         NVARCHAR (4)    NULL,
    [DodKodTARIC2NaGranicy]         NVARCHAR (4)    NULL,
    [OplatyTransportoweNaGranicy]   NVARCHAR (1)    NULL,
    [TowarNiebezpiecznyNaGranicy]   NVARCHAR (4)    NULL,
    [WalutaNaGranicy]               NVARCHAR (3)    NULL,
    [WartoscStatystycznaNaGranicy]  NUMERIC (17, 2) NULL,
    [StatusAGREX]                   NVARCHAR (4)    NULL,
    [KontynuacjaPrzetwarzaniaAGREX] BIT             NOT NULL,
    [OpisNiezgodnościAGREX]         NVARCHAR (1024) NULL,
    [SaldoAGREX]                    NVARCHAR (4)    NULL,
    CONSTRAINT [ZWU_Towar$PK_ZWU_Towar] PRIMARY KEY CLUSTERED ([Id] ASC) ON [FG_AES2],
    CONSTRAINT [FK__ZWU_Towar_IdDokZWU_ZWU_Dokument_id] FOREIGN KEY ([IdDokZWU]) REFERENCES [aes2].[ZWU_Dokument] ([Id])
);


GO
ALTER TABLE [aes2].[ZWU_Towar] NOCHECK CONSTRAINT [FK__ZWU_Towar_IdDokZWU_ZWU_Dokument_id];

