CREATE TABLE [her].[ka_dp002] (
    [RV]                BINARY (8)     NULL,
    [DataZap]           DATETIME       NULL,
    [IdUzZap]           INT            NULL,
    [IdPrac]            INT            NOT NULL,
    [IdUmowy]           INT            NOT NULL,
    [IdUmowyPowiaz]     INT            NULL,
    [NrKolUmowy]        INT            NULL,
    [NrUmowy]           VARCHAR (10)   NULL,
    [NrAkt]             VARCHAR (10)   NULL,
    [IdKodEp]           INT            NOT NULL,
    [IdPracodawca]      INT            NULL,
    [KodRodzStosPrac]   VARCHAR (9)    NULL,
    [IdKodRodzStosPrac] INT            NOT NULL,
    [KodRodzUmowy]      VARCHAR (9)    NULL,
    [IdKodRodzUmowy]    INT            NOT NULL,
    [KodSposPrzyj]      VARCHAR (9)    NULL,
    [IdKodSposPrzyj]    INT            NULL,
    [KodStatusPrzyj]    VARCHAR (9)    NULL,
    [IdKodStatusPrzyj]  INT            NULL,
    [KodStatusCzKSC]    VARCHAR (9)    NULL,
    [IdKodStatusCzKSC]  INT            NULL,
    [DataZawUmowy]      DATETIME       NOT NULL,
    [DataRozpPracy]     DATETIME       NULL,
    [DataZakUmowy]      DATETIME       NULL,
    [DataOkrUmowyOd]    DATETIME       NULL,
    [DataOkrUmowyDo]    DATETIME       NULL,
    [DataMianSluzbSC]   DATETIME       NULL,
    [KodZwol]           VARCHAR (9)    NULL,
    [IdKodZwol]         INT            NULL,
    [KodPowZwol]        VARCHAR (9)    NULL,
    [IdKodPowZwol]      INT            NULL,
    [MiejWykPracy]      VARCHAR (1000) NULL,
    [WarunkiZatr]       VARCHAR (1000) NULL,
    [WskPrzejNaEmeryt]  BIT            NULL,
    [WskPrzywDoPracy]   BIT            NULL,
    [ZalDoStazuMcy]     SMALLINT       NULL,
    [ZalDoStazuDni]     SMALLINT       NULL,
    CONSTRAINT [PK_ka_dp002_IdUmowy] PRIMARY KEY CLUSTERED ([IdUmowy] ASC)
);

