CREATE TABLE [tr].[SzczegolyOperacjiTranzytowej] (
    [SID]                          INT            NOT NULL,
    [IDKrajuSrTranspPrzekrGranice] CHAR (2)       NULL,
    [IDKrajuPrzeznaczenia]         CHAR (2)       NULL,
    [IDKrajuNaWyjezdzie]           CHAR (2)       NULL,
    [IDKrajuWysylki]               CHAR (2)       NULL,
    [CalkowitaLiczbaOpakowan]      DECIMAL (7)    NULL,
    [CalkowitaLiczbaPozycji]       DECIMAL (5)    NULL,
    [CRN]                          VARCHAR (70)   NULL,
    [CzyKontener]                  BIT            NULL,
    [CzyTowaryWrazliwe]            BIT            NULL,
    [DaneBezpieczenstwa]           DECIMAL (1)    NULL,
    [KodMiejscaUznanego]           NVARCHAR (17)  NULL,
    [LiczbaPlomb]                  DECIMAL (4)    NULL,
    [MRN]                          VARCHAR (21)   NULL,
    [NazwaPrzedstawiciela]         VARCHAR (105)  NULL,
    [NumerReferencyjnyPrzewozu]    VARCHAR (35)   NULL,
    [NumerWersji]                  DECIMAL (3)    NOT NULL,
    [UmocowaniePrzedstawiciela]    NVARCHAR (105) NULL,
    [ProcUprWUCWyjscia]            CHAR (2)       NULL,
    [RodzajTransportuNaGranicy]    CHAR (2)       NULL,
    [TypTransportuPrzekrGranice]   CHAR (3)       NULL,
    [RodzajTransportu]             CHAR (2)       NULL,
    [SIDOperacjiTranzytowej]       INT            NULL,
    [SIDUpowaznionegoOdbiorcyPDR]  INT            NULL,
    [SIDUpowaznionegoOdbiorcy]     INT            NULL,
    [SIDNadawcyPDR]                INT            NULL,
    [SIDNadawcy]                   INT            NULL,
    [SIDOdbiorcyPDR]               INT            NULL,
    [SIDOdbiorcy]                  INT            NULL,
    [SIDPrzedstawicielaPDR]        INT            NULL,
    [TypDeklaracji]                VARCHAR (5)    NULL,
    [MiejsceUznane]                NVARCHAR (105) NULL,
    [WskaznikWarunkowSzczegolnych] CHAR (1)       NULL,
    [OplataTranspMetodaPlatnosci]  CHAR (1)       NULL,
    [NrSrTranspWMiejscuWyjscia]    VARCHAR (81)   NULL,
    [NrSrTranspPrzekrGranice]      VARCHAR (81)   NULL,
    CONSTRAINT [PK_SzczegolyOperacjiTranzytowej] PRIMARY KEY CLUSTERED ([SID] ASC)
);

